In [34]:
import pandas as pd
import yfinance as yf

In [35]:
GOOG = yf.Ticker('GOOG')
GOOG_df = pd.DataFrame([GOOG.info])
GOOG_df.to_csv('GOOG.csv')

ATVI = yf.Ticker('ATVI')
ATVI_df = pd.DataFrame([ATVI.info])
ATVI_df.to_csv('ATVI.csv')

GOOGL = yf.Ticker('GOOGL')
GOOGL_df = pd.DataFrame([GOOGL.info])
GOOGL_df.to_csv('GOOGL.csv')

T = yf.Ticker('T')
T_df = pd.DataFrame([T.info])
T_df.to_csv('T.csv')

CHTR = yf.Ticker('CHTR')
CHTR_df = pd.DataFrame([CHTR.info])
CHTR_df.to_csv('CHTR.csv')

CMCSA = yf.Ticker('CMCSA')
CMCSA_df = pd.DataFrame([CMCSA.info])
CMCSA_df.to_csv('CMCSA.csv')

DISH = yf.Ticker('DISH')
DISH_df = pd.DataFrame([DISH.info])
DISH_df.to_csv('DISH.csv')

DIS = yf.Ticker('DIS')
DIS_df = pd.DataFrame([DIS.info])
DIS_df.to_csv('DIS.csv')

EA = yf.Ticker('EA')
EA_df = pd.DataFrame([EA.info])
EA_df.to_csv('EA.csv')

FOX = yf.Ticker('FOX')
FOX_df = pd.DataFrame([FOX.info])
FOX_df.to_csv('FOX.csv')

FOXA = yf.Ticker('FOXA')
FOXA_df = pd.DataFrame([FOXA.info])
FOXA_df.to_csv('FOXA.csv')
#
IPG = yf.Ticker('IPG')
IPG_df = pd.DataFrame([IPG.info])
IPG_df.to_csv('IPG.csv')

LYV = yf.Ticker('LYV')
LYV_df = pd.DataFrame([LYV.info])
LYV_df.to_csv('LYV.csv')

LUMN = yf.Ticker('LUMN')
LUMN_df = pd.DataFrame([LUMN.info])
LUMN_df.to_csv('LUMN.csv')

MTCH = yf.Ticker('MTCH')
MTCH_df = pd.DataFrame([MTCH.info])
MTCH_df.to_csv('MTCH.csv')

FB = yf.Ticker('FB')
FB_df = pd.DataFrame([FB.info])
FB_df.to_csv('FB.csv')

NFLX = yf.Ticker('NFLX')
NFLX_df = pd.DataFrame([NFLX.info])
NFLX_df.to_csv('NFLX.csv')

NWSA = yf.Ticker('NWSA')
NWSA_df = pd.DataFrame([NWSA.info])
NWSA_df.to_csv('NWSA.csv')

NWS = yf.Ticker('NWS')
NWS_df = pd.DataFrame([NWS.info])
NWS_df.to_csv('NWS.csv')

OMC = yf.Ticker('OMC')
OMC_df = pd.DataFrame([OMC.info])
OMC_df.to_csv('OMC.csv')

PARA = yf.Ticker('PARA')
PARA_df = pd.DataFrame([PARA.info])
PARA_df.to_csv('PARA.csv')

TMUS = yf.Ticker('TMUS')
TMUS_df = pd.DataFrame([TMUS.info])
TMUS_df.to_csv('TMUS.csv')

#
TTWO = yf.Ticker('TTWO')
TTWO_df = pd.DataFrame([TTWO.info])
TTWO_df.to_csv('TTWO.csv')

TWTR = yf.Ticker('TWTR')
TWTR_df = pd.DataFrame([TWTR.info])
TWTR_df.to_csv('TWTR.csv')

VZ = yf.Ticker('VZ')
VZ_df = pd.DataFrame([VZ.info])
VZ_df.to_csv('VZ.csv')

WBD = yf.Ticker('WBD')
WBD_df = pd.DataFrame([WBD.info])
WBD_df.to_csv('WBD.csv')

In [36]:
df_ATVI = pd.read_csv('ATVI.csv')
df_GOOG = pd.read_csv('GOOG.csv')
df_GOOGL = pd.read_csv('GOOGL.csv')
df_CHTR = pd.read_csv('CHTR.csv')
df_DISH = pd.read_csv('DISH.csv')
df_DIS = pd.read_csv('DIS.csv')
df_EA = pd.read_csv('EA.csv')
df_CMCSA = pd.read_csv('CMCSA.csv')
df_FOX = pd.read_csv('FOX.csv')
df_FOXA = pd.read_csv('FOXA.csv')
df_T = pd.read_csv('T.csv')

df_IPG = pd.read_csv('IPG.csv')
df_LYV = pd.read_csv('LYV.csv')
df_LUMN = pd.read_csv('LUMN.csv')
df_MTCH = pd.read_csv('MTCH.csv')
df_FB = pd.read_csv('FB.csv')
df_NFLX = pd.read_csv('NFLX.csv')

df_NWSA = pd.read_csv('NWSA.csv')
df_NWS = pd.read_csv('NWS.csv')
df_OMC = pd.read_csv('OMC.csv')
df_PARA = pd.read_csv('PARA.csv')
df_TMUS = pd.read_csv('TMUS.csv')
df_TTWO = pd.read_csv('TTWO.csv')
df_TWTR = pd.read_csv('TWTR.csv')
df_VZ = pd.read_csv('VZ.csv')
df_WBD = pd.read_csv('WBD.csv')

In [40]:
valuation_cols = ['symbol', 'marketCap','enterpriseValue','currentPrice', 'fiftyTwoWeekHigh', 'fiftyTwoWeekLow','earningsGrowth','enterpriseToRevenue', 'enterpriseToEbitda',
                  'forwardEps','trailingEps',  'priceToSalesTrailing12Months', 
                  'forwardPE', 'dividendYield']

In [41]:
ATVI_val = df_ATVI[valuation_cols]
GOOG_val = df_GOOG[valuation_cols]
GOOGL_val = df_GOOGL[valuation_cols]
CHTR_val = df_CHTR[valuation_cols]
T_val = df_T[valuation_cols]
DISH_val = df_DISH[valuation_cols]
DIS_val = df_DIS[valuation_cols]
EA_val = df_EA[valuation_cols]
CMCSA_val = df_CMCSA[valuation_cols]
FOX_val = df_FOX[valuation_cols]
FOXA_val = df_FOXA[valuation_cols]
df_IPG  = df_IPG[valuation_cols]
df_LYV = df_LYV[valuation_cols]
df_LUMN = df_LUMN[valuation_cols]
df_MTCH = df_MTCH[valuation_cols]
df_FB = df_FB[valuation_cols]
df_NFLX = df_NFLX[valuation_cols]
df_NWSA = df_NWSA[valuation_cols]
df_NWS = df_NWS[valuation_cols]
df_OMC = df_OMC[valuation_cols]
df_PARA = df_PARA[valuation_cols]
df_TMUS = df_TMUS[valuation_cols]
df_TTWO = df_TTWO[valuation_cols]
df_TWTR = df_TWTR[valuation_cols]
df_VZ = df_VZ[valuation_cols]
df_WBD = df_WBD[valuation_cols]

In [42]:
type(ATVI_val)

pandas.core.frame.DataFrame

In [43]:
df_comm_serve_val_list = [ATVI_val, GOOG_val, GOOGL_val, CHTR_val, T_val, DIS_val, DISH_val, EA_val, CMCSA_val, FOX_val, FOXA_val,
                         df_IPG, df_LUMN, df_LYV, df_MTCH, df_FB, df_NFLX, df_NWS, df_NWSA, df_OMC, df_PARA, df_TMUS, df_TTWO,
                         df_TWTR, df_VZ, df_WBD]




df_comm_serve_val = pd.concat(df_comm_serve_val_list)

In [44]:
df_comm_serve_val

,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,ATVI,6.036121e+10,52990627840,77.20,99.460000,56.40000,-0.367,6.387,16.946,3.93,3.149,7.275942,19.643764,0.0061
0,GOOG,1.467791e+12,1334283993088,2233.33,3042.000000,2127.46000,-0.063,4.936,13.922,132.65,110.585,5.429548,16.836262,NaN
0,GOOGL,1.470895e+12,1328950149120,2229.76,3030.930000,2115.93000,-0.063,4.916,13.866,132.68,110.585,5.441027,16.805548,NaN
0,CHTR,9.070449e+10,177359159296,473.67,825.620000,410.33000,0.681,3.387,8.544,35.97,27.446,1.732324,13.168473,NaN
0,T,1.486924e+11,362527588352,20.77,22.779455,16.63142,-0.364,2.224,6.903,2.55,2.377,0.912056,8.145099,0.0544
0,DIS,1.926944e+11,238684372992,105.79,187.580000,99.47000,-0.478,3.115,22.141,5.44,1.450,2.514804,19.446692,NaN
0,DISH,1.094970e+10,31659296768,20.66,46.310000,17.04000,-0.313,1.787,8.795,1.61,3.480,0.618142,12.832298,NaN
0,EA,3.761907e+10,35559559168,133.77,148.930000,109.24000,2.056,5.086,20.343,8.20,2.760,5.381071,16.313416,0.0058
0,CMCSA,1.921028e+11,280924127232,42.88,61.800000,39.47000,0.099,2.337,7.950,4.06,3.110,1.598326,10.561577,0.0257
0,FOX,1.840711e+10,20478826496,31.62,40.910000,28.96000,-0.479,1.481,7.057,2.35,1.999,1.330859,13.455320,0.0156
0,FOXA,1.840424e+10,24571428864,33.46,44.950000,31.35000,NaN,1.808,8.218,3.56,2.958,1.330651,9.392857,0.0144
0,IPG,1.229019e+10,14508081152,31.22,39.980000,30.11000,0.739,1.559,8.328,2.88,2.558,1.320475,10.840277,0.0378
0,LUMN,1.132422e+10,40479125504,11.06,15.450000,9.31000,NaN,2.056,5.049,1.58,-0.709,0.575213,7.000000,0.0863
0,LYV,2.005765e+10,26995554304,89.28,127.750000,74.23000,NaN,4.307,-2834.476,0.82,-4.165,3.199779,108.878050,NaN
0,MTCH,2.171262e+10,25804969984,76.70,182.000000,67.86900,NaN,8.650,27.773,2.58,1.884,7.278110,29.728682,NaN
0,FB,5.383818e+11,513304657920,193.54,384.330000,169.00000,-0.176,4.289,9.862,14.23,13.974,4.499037,13.600843,NaN
0,NFLX,8.254411e+10,95862595584,186.35,700.990000,162.71000,-0.059,3.153,14.854,13.09,11.091,2.715059,14.236058,NaN
0,NWS,1.053846e+10,13919098880,17.89,26.210000,16.57000,0.018,1.386,10.977,NaN,0.830,1.049021,NaN,0.0111
0,NWSA,1.046078e+10,13889631232,17.61,27.510000,16.54000,0.018,1.383,10.954,1.03,0.830,1.041288,17.097088,0.0112
0,OMC,1.591004e+10,19207329792,74.85,91.610000,65.76000,-0.376,1.346,8.254,6.41,6.420,1.114711,11.677067,0.0364
0,PARA,NaN,32926785536,32.64,47.460000,26.11000,1.326,1.152,7.499,NaN,NaN,NaN,NaN,0.0339
0,TMUS,1.574303e+11,264606859264,126.04,150.200000,101.51000,-0.230,3.288,10.002,3.24,2.660,1.956166,38.901234,NaN
0,TTWO,1.338864e+10,10856370176,116.12,195.830000,101.85000,-0.210,3.180,12.955,6.70,4.836,3.921425,17.331345,NaN
0,TWTR,3.061707e+10,38548004864,38.29,73.340000,31.30000,6.681,7.353,70.533,0.96,-0.228,5.840223,39.885418,NaN
0,VZ,2.079150e+11,376384487424,49.53,57.610000,45.55000,-0.139,2.803,8.344,5.40,5.320,1.548139,9.172222,0.0531
0,WBD,NaN,23732545536,17.74,32.760000,16.51000,2.267,1.890,6.166,NaN,NaN,NaN,NaN,NaN

In [45]:
df_comm_serve_val.isna().sum()

symbol                           0
marketCap                        2
enterpriseValue                  0
currentPrice                     0
fiftyTwoWeekHigh                 0
fiftyTwoWeekLow                  0
earningsGrowth                   4
enterpriseToRevenue              0
enterpriseToEbitda               0
forwardEps                       3
trailingEps                      2
priceToSalesTrailing12Months     2
forwardPE                        3
dividendYield                   13
dtype: int64