In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import numpy as np
from datetime import datetime

In [2]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 200)
pd.set_option('display.min_rows', 20)

In [6]:
today_date = datetime.now()
date = today_date.strftime('%m_%d_%Y')

price_df = pd.read_csv(f'/Users/brendan/Desktop/Python/May 2022/yf_SP500/output/SP500_master_df_{date}.csv')

In [7]:
date

'06_02_2022'

In [8]:
price_df = price_df.drop('Unnamed: 0', 1)

<ipython-input-8-4482bb1f4bcd>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  price_df = price_df.drop('Unnamed: 0', 1)

In [9]:
price_df.head() # price

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,06/02/2022 17:36:11,CSCO,1.931244e+11,194965143552,45.79,64.29,41.02,0.183,3.782,12.193,3.68,2.690,3.746423,12.442935,0.0307
1,06/02/2022 17:36:11,TER,1.802498e+10,16183294976,110.58,168.91,97.63,-0.156,4.402,12.537,6.45,5.309,4.902563,17.144186,0.0041
2,06/02/2022 17:36:11,V,NaN,454458212352,215.05,252.67,186.67,0.234,16.871,23.895,NaN,NaN,NaN,NaN,0.0075
3,06/02/2022 17:36:11,QRVO,1.249488e+10,13396545536,113.36,201.46,98.23,0.121,2.943,8.146,13.15,9.656,2.744748,8.620533,NaN
4,06/02/2022 17:36:11,FOX,1.897212e+10,23107883008,31.86,40.91,28.96,NaN,1.700,7.728,2.35,2.958,1.395933,13.557447,0.0156

In [11]:
master_frame = pd.read_csv(f'/Users/brendan/Desktop/Python/May 2022/yf_SP500/output/SP500_master_df_{date}.csv')

In [12]:
price_df.head()

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,06/02/2022 17:36:11,CSCO,1.931244e+11,194965143552,45.79,64.29,41.02,0.183,3.782,12.193,3.68,2.690,3.746423,12.442935,0.0307
1,06/02/2022 17:36:11,TER,1.802498e+10,16183294976,110.58,168.91,97.63,-0.156,4.402,12.537,6.45,5.309,4.902563,17.144186,0.0041
2,06/02/2022 17:36:11,V,NaN,454458212352,215.05,252.67,186.67,0.234,16.871,23.895,NaN,NaN,NaN,NaN,0.0075
3,06/02/2022 17:36:11,QRVO,1.249488e+10,13396545536,113.36,201.46,98.23,0.121,2.943,8.146,13.15,9.656,2.744748,8.620533,NaN
4,06/02/2022 17:36:11,FOX,1.897212e+10,23107883008,31.86,40.91,28.96,NaN,1.700,7.728,2.35,2.958,1.395933,13.557447,0.0156

In [13]:
symbol_list = price_df['symbol'].to_list()

In [14]:
symbol_list

['CSCO',
 'TER',
 'V',
 'QRVO',
 'FOX',
 'FLT',
 'SWKS',
 'ENPH',
 'MCHP',
 'CDNS',
 'CHTR',
 'T',
 'DISH',
 'APH',
 'MSI',
 'GPN',
 'WBD',
 'DXC',
 'PARA',
 'ADI',
 'ADBE',
 'NOW',
 'NWS',
 'ZBRA',
 'BR',
 'STX',
 'IPG',
 'CDAY',
 'ORCL',
 'INTU',
 'PAYC',
 'IPGP',
 'INTC',
 'GLW',
 'TXN',
 'FTNT',
 'JNPR',
 'ADSK',
 'WDC',
 'LUMN',
 'PYPL',
 'MSFT',
 'ANSS',
 'IT',
 'ACN',
 'VRSN',
 'HPQ',
 'AMAT',
 'ATVI',
 'EA',
 'AMD',
 'KLAC',
 'NXPI',
 'SEDG',
 'MTCH',
 'NVDA',
 'TYL',
 'HPE',
 'CMCSA',
 'CTXS',
 'PTC',
 'FIS',
 'FB',
 'NLOK',
 'IBM',
 'TWTR',
 'MPWR',
 'DIS',
 'NFLX',
 'OMC',
 'AKAM',
 'GOOGL',
 'ANET',
 'PAYX',
 'FOXA',
 'FFIV',
 'SNPS',
 'GOOG',
 'EPAM',
 'LYV',
 'AVGO',
 'VZ',
 'TEL',
 'JKHY',
 'ADP',
 'TRMB',
 'QCOM',
 'MA',
 'NWSA',
 'TTWO',
 'AAPL',
 'TMUS',
 'NTAP',
 'KEYS',
 'CTSH',
 'MU',
 'CDW',
 'CRM',
 'LRCX']

In [15]:
df = price_df.set_index('symbol')
def is_contrarian(symbol):
    price = df.loc[f'{symbol}', 'currentPrice']
    price_high = df.loc[f'{symbol}', 'fiftyTwoWeekHigh']
    price_low = df.loc[f'{symbol}', 'fiftyTwoWeekLow']
    price_band = (price_high - price_low)
    if price < (price_low + (.3*(price_band))):
        return f'{symbol}'
    else:
        return 'OK'

In [16]:
is_contrarian('LRCX')

'LRCX'

In [17]:
contrarian_tickers = map(is_contrarian, symbol_list)
ticks = [i for i in symbol_list if is_contrarian(i) != 'OK' ]

In [18]:
ticks

['CSCO',
 'TER',
 'QRVO',
 'FOX',
 'SWKS',
 'CHTR',
 'DISH',
 'APH',
 'GPN',
 'WBD',
 'PARA',
 'ADBE',
 'NWS',
 'ZBRA',
 'BR',
 'STX',
 'CDAY',
 'ORCL',
 'INTU',
 'PAYC',
 'IPGP',
 'INTC',
 'ADSK',
 'PYPL',
 'MSFT',
 'ANSS',
 'IT',
 'ACN',
 'VRSN',
 'AMAT',
 'MTCH',
 'NVDA',
 'TYL',
 'CMCSA',
 'FB',
 'NLOK',
 'TWTR',
 'DIS',
 'NFLX',
 'OMC',
 'FOXA',
 'FFIV',
 'TEL',
 'TRMB',
 'NWSA',
 'TTWO',
 'NTAP',
 'KEYS',
 'MU',
 'CRM',
 'LRCX']

In [19]:
data = price_df[price_df['symbol'].isin(ticks)]
data.head()

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,06/02/2022 17:36:11,CSCO,1.931244e+11,194965143552,45.79,64.29,41.02,0.183,3.782,12.193,3.68,2.690,3.746423,12.442935,0.0307
1,06/02/2022 17:36:11,TER,1.802498e+10,16183294976,110.58,168.91,97.63,-0.156,4.402,12.537,6.45,5.309,4.902563,17.144186,0.0041
3,06/02/2022 17:36:11,QRVO,1.249488e+10,13396545536,113.36,201.46,98.23,0.121,2.943,8.146,13.15,9.656,2.744748,8.620533,NaN
4,06/02/2022 17:36:11,FOX,1.897212e+10,23107883008,31.86,40.91,28.96,NaN,1.700,7.728,2.35,2.958,1.395933,13.557447,0.0156
6,06/02/2022 17:36:11,SWKS,1.833149e+10,19951753216,110.84,197.62,97.59,-0.213,3.905,9.960,12.87,8.970,3.587728,8.612276,0.0216

In [20]:
len(data)

51

In [21]:
today_date = datetime.now()
date_file =today_date.strftime('%m_%d_%Y')
data.to_csv(f'SP500_contrarian_df_{date_file}.csv')

In [22]:
cont_df = pd.read_csv(f'SP500_contrarian_df_{date_file}.csv')
cont_df

,Unnamed: 0,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,0,06/02/2022 17:36:11,CSCO,1.931244e+11,194965143552,45.79,64.29,41.020,0.183,3.782,12.193,3.68,2.690,3.746423,12.442935,0.0307
1,1,06/02/2022 17:36:11,TER,1.802498e+10,16183294976,110.58,168.91,97.630,-0.156,4.402,12.537,6.45,5.309,4.902563,17.144186,0.0041
2,3,06/02/2022 17:36:11,QRVO,1.249488e+10,13396545536,113.36,201.46,98.230,0.121,2.943,8.146,13.15,9.656,2.744748,8.620533,NaN
3,4,06/02/2022 17:36:11,FOX,1.897212e+10,23107883008,31.86,40.91,28.960,NaN,1.700,7.728,2.35,2.958,1.395933,13.557447,0.0156
4,6,06/02/2022 17:36:11,SWKS,1.833149e+10,19951753216,110.84,197.62,97.590,-0.213,3.905,9.960,12.87,8.970,3.587728,8.612276,0.0216
5,10,06/02/2022 17:36:11,CHTR,8.932636e+10,168875589632,498.22,825.62,410.330,0.681,3.225,8.135,31.27,21.943,1.706004,15.932843,NaN
6,12,06/02/2022 17:36:11,DISH,1.182401e+10,33020866560,22.36,46.31,17.040,-0.308,1.847,8.407,2.77,4.159,0.661257,8.072203,NaN
7,13,06/02/2022 17:36:11,APH,4.304606e+10,46405705728,71.98,88.45,65.840,0.283,4.053,17.165,2.67,2.380,3.759120,26.958801,0.0114
8,15,06/02/2022 17:36:11,GPN,3.816937e+10,49546457088,131.55,196.88,114.800,0.187,5.813,14.373,9.59,3.167,4.477995,13.717414,0.0082
9,16,06/02/2022 17:36:11,WBD,NaN,23732545536,18.00,32.40,16.510,2.267,1.890,6.166,NaN,NaN,NaN,NaN,NaN
10,18,06/02/2022 17:36:11,PARA,NaN,32926785536,31.43,47.46,26.110,1.326,1.152,7.499,NaN,NaN,NaN,NaN,0.0339
11,20,06/02/2022 17:36:11,ADBE,2.099610e+11,187050377216,441.28,699.54,370.270,0.019,11.588,28.684,16.25,10.020,13.007126,27.155693,NaN
12,22,06/02/2022 17:36:11,NWS,1.061504e+10,13919098880,18.02,25.69,16.570,0.018,1.386,10.977,NaN,0.830,1.056644,NaN,0.0111
13,23,06/02/2022 17:36:11,ZBRA,1.854794e+10,20450457600,347.07,615.00,309.000,-0.045,3.634,17.070,19.70,15.684,3.296240,17.617765,NaN
14,24,06/02/2022 17:36:11,BR,1.721041e+10,20994430976,147.63,185.40,132.680,-0.167,3.907,18.797,7.04,4.655,3.202592,20.970171,0.0184
15,25,06/02/2022 17:36:11,STX,1.884391e+10,22073798656,84.64,117.67,76.280,0.122,1.832,8.697,9.28,6.795,1.564329,9.120689,0.0347
16,27,06/02/2022 17:36:11,CDAY,8.648568e+09,9343748096,57.15,130.37,48.930,NaN,9.123,841.779,0.45,-0.561,8.444218,127.000010,NaN
17,28,06/02/2022 17:36:11,ORCL,1.953167e+11,251351728128,73.14,106.34,66.720,-0.500,6.009,13.661,5.26,3.543,4.669632,13.904943,0.0180
18,29,06/02/2022 17:36:11,INTU,1.208727e+11,124250726400,426.86,716.86,339.360,4.000,10.886,39.697,13.64,7.581,10.589861,31.294720,0.0073
19,30,06/02/2022 17:36:11,PAYC,1.819382e+10,16730388480,303.10,558.97,259.950,1.000,15.850,58.850,5.63,2.950,17.236767,53.836590,NaN
20,31,06/02/2022 17:36:11,IPGP,5.597434e+09,3546220800,105.00,220.51,90.510,0.310,2.427,7.896,5.85,4.869,3.831602,17.948719,NaN
21,32,06/02/2022 17:36:11,INTC,1.823643e+11,176790503424,44.84,58.42,40.310,1.415,2.275,5.604,3.70,5.158,2.346910,12.118918,0.0335
22,37,06/02/2022 17:36:11,ADSK,4.709402e+10,42427953152,214.09,344.39,173.900,-0.901,9.673,51.359,6.83,5.928,10.736370,31.345533,NaN
23,40,06/02/2022 17:36:11,PYPL,1.037698e+11,103888453632,88.32,310.16,71.831,-0.533,4.023,21.249,5.27,4.159,4.018815,16.759014,NaN
24,41,06/02/2022 17:36:11,MSFT,2.061541e+12,2048902299648,274.58,349.67,243.000,0.094,10.640,21.571,10.54,8.939,10.706134,26.051231,0.0095
25,42,06/02/2022 17:36:11,ANSS,2.327474e+10,24261203968,266.75,413.89,230.720,-0.067,12.724,38.745,7.94,5.318,12.206720,33.595720,NaN
26,43,06/02/2022 17:36:11,IT,2.208446e+10,26456133632,268.54,369.00,228.200,0.881,5.589,23.045,7.13,8.025,4.665112,37.663395,NaN
27,44,06/02/2022 17:36:11,ACN,1.939399e+11,188926197760,306.62,417.37,268.170,0.139,3.332,19.863,10.45,9.613,3.420763,29.341627,0.0135
28,45,06/02/2022 17:36:11,VRSN,2.003070e+10,20151259136,180.33,257.03,159.690,0.075,14.917,21.681,6.17,5.425,14.827930,29.226904,NaN
29,47,06/02/2022 17:36:11,AMAT,1.042492e+11,97502601216,117.33,167.06,101.330,0.639,4.034,11.943,8.85,6.400,4.312810,13.257627,0.0088
30,54,06/02/2022 17:36:11,MTCH,2.381594e+10,25804969984,84.13,182.00,67.869,NaN,8.650,27.773,2.58,1.884,7.983147,32.608530,NaN
31,55,06/02/2022 17:36:11,NVDA,4.882326e+11,455410810880,195.92,346.47,155.670,1.034,16.921,40.607,5.21,3.243,18.140470,37.604607,0.0009
32,56,06/02/2022 17:36:11,TYL,1.479613e+10,17453617152,361.09,557.55,327.970,0.068,9.953,50.622,8.15,3.825,8.437610,44.305523,NaN
33,58,06/02/2022 17:36:11,CMCSA,2.001187e+11,270841151488,43.80,61.80,39.470,0.099,2.253,7.664,3.69,3.109,1.665020,11.869918,0.0260
34,62,06/02/2022 17:36:11,FB,5.531808e+11,513304657920,198.86,384.33,169.000,-0.176,4.289,9.862,14.23,13.974,4.622706,13.974702,NaN
35,63,06/02/2022 17:36:11,NLOK,1.434608e+10,16732807168,24.66,30.92,23.470,0.140,6.080,12.754,1.97,1.496,5.212965,12.517766,0.0209
36,65,06/02/2022 17:36:11,TWTR,3.191243e+10,38548004864,39.91,73.34,31.300,6.681,7.353,70.533,0.96,-0.228,6.087316,41.572918,NaN
37,67,06/02/2022 17:36:11,DIS,2.015240e+11,256654311424,110.87,187.58,99.470,63.358,3.516,24.304,5.06,1.094,2.761056,21.911068,NaN
38,68,06/02/2022 17:36:11,NFLX,9.084502e+10,95862595584,205.09,700.99,162.710,-0.059,3.153,14.854,13.09,11.091,2.988094,15.667685,NaN
39,69,06/02/2022 17:36:11,OMC,1.557207e+10,19207329792,73.26,91.61,65.760,-0.376,1.346,8.254,6.41,6.420,1.091031,11.429018,0.0364
40,74,06/02/2022 17:36:11,FOXA,1.896349e+10,24571428864,34.42,44.95,31.350,NaN,1.808,8.218,3.56,2.958,1.395298,9.668539,0.0143
41,75,06/02/2022 17:36:11,FFIV,1.030307e+10,9871137792,168.27,249.00,151.660,0.314,3.718,18.315,13.18,5.340,3.880869,12.767072,NaN
42,82,06/02/2022 17:36:11,TEL,4.296563e+10,43690319872,131.67,166.44,119.580,0.130,2.821,11.941,7.91,6.788,2.774124,16.646017,0.0179
43,85,06/02/2022 17:36:11,TRMB,1.762076e+10,17879977984,70.20,96.49,59.890,-0.361,4.886,23.125,2.96,2.197,4.815600,23.716215,NaN
44,88,06/02/2022 17:36:11,NWSA,1.052018e+10,13889631232,17.71,26.87,16.380,0.018,1.383,10.954,1.03,0.830,1.047201,17.194174,0.0112
45,89,06/02/2022 17:36:11,TTWO,1.487947e+10,10856370176,129.05,195.83,101.850,-0.210,3.180,12.955,6.70,4.836,4.358078,19.261194,NaN
46,92,06/02/2022 17:36:11,NTAP,1.620407e+10,15044795392,72.90,96.82,64.580,0.375,2.429,11.038,5.51,4.113,2.616513,13.230490,0.0281
47,93,06/02/2022 17:36:11,KEYS,2.723299e+10,25562640384,148.78,209.08,127.930,0.348,5.101,17.989,7.48,4.780,5.434642,19.890373,NaN
48,95,06/02/2022 17:36:11,MU,8.442721e+10,73692512256,75.37,98.45,65.670,2.774,2.364,4.318,11.51,6.461,2.708692,6.548219,0.0056
49,97,06/02/2022 17:36:11,CRM,1.855740e+11,178013601792,188.40,311.75,154.550,NaN,6.720,58.098,4.71,1.818,7.004907,40.000000,NaN
50,98,06/02/2022 17:36:11,LRCX,7.368012e+10,65261465600,523.30,731.85,442.530,-0.015,3.899,11.775,36.65,29.588,4.402318,14.278307,0.0122

In [23]:
data_merge = cont_df[['symbol', 'marketCap', 'fiftyTwoWeekHigh', 'fiftyTwoWeekLow']]

## Price targets

In [24]:
px_target_cols = ['symbol', 'sector', 'industry','currentPrice', 'targetLowPrice', 'targetMedianPrice','numberOfAnalystOpinions',
            'targetMeanPrice', 'targetHighPrice', 'recommendationMean']

In [25]:
appended_data = []
for ticker in ticks:
    data = yf.Ticker(ticker)
    df = pd.DataFrame([data.info])
    px_target = df[px_target_cols]
    appended_data.append(px_target)

contrarian_df = pd.DataFrame(np.row_stack(appended_data))
contrarian_df.columns =  ['Ticker', 'Sector', 'Industry','Price', 'Low Price', 'Median Price','# of Ratings',
            'Mean Price', 'High Price', 'Avg Rating']
contrarian_df = contrarian_df[['Ticker', 'Sector', 'Industry','Price', 'Low Price', 'Median Price', 'Mean Price', 'High Price',
                 '# of Ratings', 'Avg Rating']]
contrarian_df

,Ticker,Sector,Industry,Price,Low Price,Median Price,Mean Price,High Price,# of Ratings,Avg Rating
0,CSCO,Technology,Communication Equipment,45.79,45,62.5,62.74,73,24,2.5
1,TER,Technology,Semiconductor Equipment & Materials,110.58,90,136.5,135.1,163,20,2.2
2,QRVO,Technology,Semiconductors,113.36,120,135,149.86,235,22,2.5
3,FOX,Communication Services,Broadcasting,31.86,51.5,51.5,51.5,51.5,1,None
4,SWKS,Technology,Semiconductors,110.84,120,150,151,226,25,2.5
5,CHTR,Communication Services,Entertainment,498.22,393,630,623.22,805,27,2.5
6,DISH,Communication Services,Entertainment,22.36,24,44,40.87,61,15,2.2
7,APH,Technology,Electronic Components,71.98,79,87,85.77,94,13,2.2
8,GPN,Industrials,Specialty Business Services,131.55,142,180,180.64,240,34,1.8
9,WBD,Communication Services,Entertainment,18,18,37.5,34.65,52,20,2.4
10,PARA,Communication Services,Entertainment,31.43,24,35,36.56,60,25,2.7
11,ADBE,Technology,Software—Infrastructure,441.28,455,570,563.7,650,27,1.9
12,NWS,Communication Services,Broadcasting,18.02,None,None,None,None,None,None
13,ZBRA,Technology,Communication Equipment,347.07,400,527.5,514.4,600,10,2
14,BR,Technology,Information Technology Services,147.63,161,175.5,178.17,199,6,2.7
15,STX,Technology,Computer Hardware,84.64,None,None,None,None,None,None
16,CDAY,Technology,Software—Application,57.15,None,None,None,None,None,None
17,ORCL,Technology,Software—Infrastructure,73.14,70,89,92.17,126,24,2.7
18,INTU,Technology,Software—Application,426.86,510,625,618.33,720,20,1.8
19,PAYC,Technology,Software—Application,303.1,334,385,385.71,450,17,2
20,IPGP,Technology,Semiconductor Equipment & Materials,105,95,153.5,151.88,183,8,2.3
21,INTC,Technology,Semiconductors,44.84,37,50.5,52.36,74,40,2.9
22,ADSK,Technology,Software—Application,214.09,210,280,284.25,440,19,2
23,PYPL,Financial Services,Credit Services,88.32,82,115,124.23,255,45,2.1
24,MSFT,Technology,Software—Infrastructure,274.58,298.18,360,362.95,425.96,46,1.7
25,ANSS,Technology,Software—Application,266.75,245,320,325.36,420,14,2.7
26,IT,Technology,Information Technology Services,268.54,315,334,330.29,342,7,2.1
27,ACN,Technology,Information Technology Services,306.62,None,None,None,None,None,None
28,VRSN,Technology,Software—Infrastructure,180.33,210,227,240,283,3,2.5
29,AMAT,Technology,Semiconductor Equipment & Materials,117.33,130,170,166.45,205,31,2.1
30,MTCH,Communication Services,Internet Content & Information,84.13,81,125,125,170,21,1.9
31,NVDA,Technology,Semiconductors,195.92,160,350,326.46,400,44,2
32,TYL,Technology,Software—Application,361.09,408,520,509.85,600,17,2.1
33,CMCSA,Communication Services,Entertainment,43.8,40,58,56.03,70,32,2.2
34,FB,Communication Services,Internet Content & Information,198.86,185,300,301.33,553,54,2
35,NLOK,Technology,Software—Infrastructure,24.66,22.4,27.5,27.33,31.6,6,2.2
36,TWTR,Communication Services,Internet Content & Information,39.91,33,54,51.88,77.8,30,3
37,DIS,Communication Services,Entertainment,110.87,None,None,None,None,None,2
38,NFLX,Communication Services,Entertainment,205.09,217,300,338.95,735,38,2.7
39,OMC,Communication Services,Advertising Agencies,73.26,77,90,92.56,107,9,2.5
40,FOXA,Communication Services,Broadcasting,34.42,32,46,44.96,55,23,2.3
41,FFIV,Technology,Software—Infrastructure,168.27,155,215,215.47,303,15,2.5
42,TEL,Technology,Electronic Components,131.67,None,None,None,None,None,None
43,TRMB,Technology,Scientific & Technical Instruments,70.2,70,94,90.75,100,8,2.1
44,NWSA,Communication Services,Broadcasting,17.71,28,30,30.87,34.1,7,1.9
45,TTWO,Communication Services,Electronic Gaming & Multimedia,129.05,155.26,200,200.81,231,25,1.9
46,NTAP,Technology,Computer Hardware,72.9,74,96,97.95,124,19,2.5
47,KEYS,Technology,Scientific & Technical Instruments,148.78,176,195,198.69,230,13,2
48,MU,Technology,Semiconductors,75.37,83,111.5,111.82,165,32,1.9
49,CRM,Technology,Software—Application,188.4,219,297.5,289.83,385,46,1.8
50,LRCX,Technology,Semiconductor Equipment & Materials,523.3,520,625,648.27,840,23,2.1

In [26]:
data_merge.columns = ['Ticker', 'Market Cap', 'FiftyTwoWeekHigh', 'FiftyTwoWeekLow']
data_merge

   Ticker    Market Cap  FiftyTwoWeekHigh  FiftyTwoWeekLow
0    CSCO  1.931244e+11             64.29           41.020
1     TER  1.802498e+10            168.91           97.630
2    QRVO  1.249488e+10            201.46           98.230
3     FOX  1.897212e+10             40.91           28.960
4    SWKS  1.833149e+10            197.62           97.590
5    CHTR  8.932636e+10            825.62          410.330
6    DISH  1.182401e+10             46.31           17.040
7     APH  4.304606e+10             88.45           65.840
8     GPN  3.816937e+10            196.88          114.800
9     WBD           NaN             32.40           16.510
10   PARA           NaN             47.46           26.110
11   ADBE  2.099610e+11            699.54          370.270
12    NWS  1.061504e+10             25.69           16.570
13   ZBRA  1.854794e+10            615.00          309.000
14     BR  1.721041e+10            185.40          132.680
15    STX  1.884391e+10            117.67           76.280
16   CDAY  8.648568e+09            130.37           48.930
17   ORCL  1.953167e+11            106.34           66.720
18   INTU  1.208727e+11            716.86          339.360
19   PAYC  1.819382e+10            558.97          259.950
20   IPGP  5.597434e+09            220.51           90.510
21   INTC  1.823643e+11             58.42           40.310
22   ADSK  4.709402e+10            344.39          173.900
23   PYPL  1.037698e+11            310.16           71.831
24   MSFT  2.061541e+12            349.67          243.000
25   ANSS  2.327474e+10            413.89          230.720
26     IT  2.208446e+10            369.00          228.200
27    ACN  1.939399e+11            417.37          268.170
28   VRSN  2.003070e+10            257.03          159.690
29   AMAT  1.042492e+11            167.06          101.330
30   MTCH  2.381594e+10            182.00           67.869
31   NVDA  4.882326e+11            346.47          155.670
32    TYL  1.479613e+10            557.55          327.970
33  CMCSA  2.001187e+11             61.80           39.470
34     FB  5.531808e+11            384.33          169.000
35   NLOK  1.434608e+10             30.92           23.470
36   TWTR  3.191243e+10             73.34           31.300
37    DIS  2.015240e+11            187.58           99.470
38   NFLX  9.084502e+10            700.99          162.710
39    OMC  1.557207e+10             91.61           65.760
40   FOXA  1.896349e+10             44.95           31.350
41   FFIV  1.030307e+10            249.00          151.660
42    TEL  4.296563e+10            166.44          119.580
43   TRMB  1.762076e+10             96.49           59.890
44   NWSA  1.052018e+10             26.87           16.380
45   TTWO  1.487947e+10            195.83          101.850
46   NTAP  1.620407e+10             96.82           64.580
47   KEYS  2.723299e+10            209.08          127.930
48     MU  8.442721e+10             98.45           65.670
49    CRM  1.855740e+11            311.75          154.550
50   LRCX  7.368012e+10            731.85          442.530

In [27]:
merged_cont_df = contrarian_df.merge(data_merge, how = 'inner', on = ['Ticker'])
merged_cont_df = merged_cont_df[['Ticker', 'Market Cap', 'Sector', 'Industry', 'Price', 'FiftyTwoWeekHigh', 'FiftyTwoWeekLow',
                  'Low Price', 'Median Price', 'Mean Price', 'High Price', '# of Ratings', 'Avg Rating']]

In [28]:
merged_cont_df['Contrarian %'] = (merged_cont_df['Price'] - merged_cont_df['FiftyTwoWeekLow'])/(merged_cont_df['FiftyTwoWeekHigh'] - merged_cont_df['FiftyTwoWeekLow'])*100

In [29]:
merged_cont_df = merged_cont_df[['Ticker', 'Market Cap', 'Sector', 'Industry', 'Price', 'Contrarian %','FiftyTwoWeekHigh', 'FiftyTwoWeekLow',
                  'Low Price', 'Median Price', 'Mean Price', 'High Price', '# of Ratings', 'Avg Rating']]

In [30]:
merged_cont_df['Market Cap $(m)'] = merged_cont_df['Market Cap']/1000000
column_price = ['Price', 'FiftyTwoWeekHigh', 'FiftyTwoWeekLow', 'Low Price', 'Median Price', 'Mean Price', 'High Price']
column_per = ['Contrarian %']
column_dollar = ['Market Cap $(m)']

merged_cont_df = merged_cont_df.drop('Market Cap',1)
merged_cont_df[['Low Price', 'Median Price', 'Mean Price', 'High Price']].apply(pd.to_numeric)
#merged_cont_df.apply(pd.to_numeric, errors='ignore').info()

<ipython-input-30-4be42e965c6f>:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  merged_cont_df = merged_cont_df.drop('Market Cap',1)

    Low Price  Median Price  Mean Price  High Price
0       45.00          62.5       62.74       73.00
1       90.00         136.5      135.10      163.00
2      120.00         135.0      149.86      235.00
3       51.50          51.5       51.50       51.50
4      120.00         150.0      151.00      226.00
5      393.00         630.0      623.22      805.00
6       24.00          44.0       40.87       61.00
7       79.00          87.0       85.77       94.00
8      142.00         180.0      180.64      240.00
9       18.00          37.5       34.65       52.00
10      24.00          35.0       36.56       60.00
11     455.00         570.0      563.70      650.00
12        NaN           NaN         NaN         NaN
13     400.00         527.5      514.40      600.00
14     161.00         175.5      178.17      199.00
15        NaN           NaN         NaN         NaN
16        NaN           NaN         NaN         NaN
17      70.00          89.0       92.17      126.00
18     510.00         625.0      618.33      720.00
19     334.00         385.0      385.71      450.00
20      95.00         153.5      151.88      183.00
21      37.00          50.5       52.36       74.00
22     210.00         280.0      284.25      440.00
23      82.00         115.0      124.23      255.00
24     298.18         360.0      362.95      425.96
25     245.00         320.0      325.36      420.00
26     315.00         334.0      330.29      342.00
27        NaN           NaN         NaN         NaN
28     210.00         227.0      240.00      283.00
29     130.00         170.0      166.45      205.00
30      81.00         125.0      125.00      170.00
31     160.00         350.0      326.46      400.00
32     408.00         520.0      509.85      600.00
33      40.00          58.0       56.03       70.00
34     185.00         300.0      301.33      553.00
35      22.40          27.5       27.33       31.60
36      33.00          54.0       51.88       77.80
37        NaN           NaN         NaN         NaN
38     217.00         300.0      338.95      735.00
39      77.00          90.0       92.56      107.00
40      32.00          46.0       44.96       55.00
41     155.00         215.0      215.47      303.00
42        NaN           NaN         NaN         NaN
43      70.00          94.0       90.75      100.00
44      28.00          30.0       30.87       34.10
45     155.26         200.0      200.81      231.00
46      74.00          96.0       97.95      124.00
47     176.00         195.0      198.69      230.00
48      83.00         111.5      111.82      165.00
49     219.00         297.5      289.83      385.00
50     520.00         625.0      648.27      840.00

In [31]:
merged_cont_df.style.format.apply({'Price': "${:.2f}",'FiftyTwoWeekHigh':"${:.2f}",'FiftyTwoWeekLow':"${:.2f}",
                        'Low Price': "${:.2f}", 'Median Price': "${:.2f}",'Mean Price': "${:.2f}",
                        'High Price': "${:.2f}"})

AttributeError: 'function' object has no attribute 'apply'

In [32]:
merged_cont_df.style.format({'Price': "${:.2f}",'FiftyTwoWeekHigh':"${:.2f}",'FiftyTwoWeekLow':"${:.2f}",
                        'Low Price': "${:.2f}", 'Mean Price': "${:.2f}",'Median Price': "${:.2f}",
                        'High Price': "${:.2f}"})

TypeError: unsupported format string passed to NoneType.__format__

In [33]:
merged_cont_df.head(2)

,Ticker,Sector,Industry,Price,Contrarian %,FiftyTwoWeekHigh,FiftyTwoWeekLow,Low Price,Median Price,Mean Price,High Price,# of Ratings,Avg Rating,Market Cap $(m)
0,CSCO,Technology,Communication Equipment,45.79,20.498496,64.29,41.02,45,62.5,62.74,73,24,2.5,193124.368384
1,TER,Technology,Semiconductor Equipment & Materials,110.58,18.167789,168.91,97.63,90,136.5,135.1,163,20,2.2,18024.982528

In [34]:
date_file =today_date.strftime('%m_%d_%Y')
#raw_df.to_csv(f'SP500_master_df_{date_file}.csv')
date_file

'06_02_2022'

In [35]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://{user}:{pw}@localhost/{db}'.format(user='root',
                                                                        pw='Boston1429$$',
                                                                        db='SP500'))
merged_cont_df.to_sql(f'contrarian_{date_file}', con=engine, if_exists='append', index=False)

51