In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import numpy as np
from datetime import datetime

In [25]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 200)
pd.set_option('display.min_rows', 20)

In [26]:
today_date = datetime.now()
date = today_date.strftime('%m_%d_%Y')

price_df = pd.read_csv(f'/Users/brendan/Desktop/Python/May 2022/yf_SP500/output/SP500_master_df_{date}.csv')

In [27]:
date

'06_06_2022'

In [28]:
price_df = price_df.drop('Unnamed: 0', 1)

<ipython-input-28-4482bb1f4bcd>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  price_df = price_df.drop('Unnamed: 0', 1)

In [29]:
price_df.head() # price

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,06/06/2022 12:25:58,CSCO,1.910366e+11,177767628800,45.295,64.29,41.02,0.076,3.446,11.061,3.55,2.850,3.705923,12.308423,0.0307
1,06/06/2022 12:25:58,TER,1.718498e+10,16304323584,107.270,168.91,97.63,-0.156,4.435,12.630,6.61,5.384,4.674092,16.228441,0.0041
2,06/06/2022 12:25:58,V,4.536053e+11,453458329600,214.350,252.67,186.67,0.234,16.834,23.842,8.37,6.358,16.839489,25.609320,0.0071
3,06/06/2022 12:25:58,QRVO,1.172341e+10,12714641408,110.570,201.46,98.23,-0.247,2.737,7.654,12.73,9.260,2.523489,8.685781,NaN
4,06/06/2022 12:25:58,FOX,1.831854e+10,20874117120,31.520,40.91,28.96,-0.479,1.509,7.193,2.35,1.999,1.324455,13.412766,0.0151

In [30]:
master_frame = pd.read_csv(f'/Users/brendan/Desktop/Python/May 2022/yf_SP500/output/SP500_master_df_{date}.csv')

In [31]:
price_df.head()

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,06/06/2022 12:25:58,CSCO,1.910366e+11,177767628800,45.295,64.29,41.02,0.076,3.446,11.061,3.55,2.850,3.705923,12.308423,0.0307
1,06/06/2022 12:25:58,TER,1.718498e+10,16304323584,107.270,168.91,97.63,-0.156,4.435,12.630,6.61,5.384,4.674092,16.228441,0.0041
2,06/06/2022 12:25:58,V,4.536053e+11,453458329600,214.350,252.67,186.67,0.234,16.834,23.842,8.37,6.358,16.839489,25.609320,0.0071
3,06/06/2022 12:25:58,QRVO,1.172341e+10,12714641408,110.570,201.46,98.23,-0.247,2.737,7.654,12.73,9.260,2.523489,8.685781,NaN
4,06/06/2022 12:25:58,FOX,1.831854e+10,20874117120,31.520,40.91,28.96,-0.479,1.509,7.193,2.35,1.999,1.324455,13.412766,0.0151

In [32]:
symbol_list = price_df['symbol'].to_list()

In [33]:
symbol_list

['CSCO',
 'TER',
 'V',
 'QRVO',
 'FOX',
 'FLT',
 'SWKS',
 'ENPH',
 'MCHP',
 'CDNS',
 'CHTR',
 'T',
 'DISH',
 'APH',
 'MSI',
 'GPN',
 'WBD',
 'DXC',
 'PARA',
 'ADI',
 'ADBE',
 'NOW',
 'NWS',
 'ZBRA',
 'BR',
 'STX',
 'IPG',
 'CDAY',
 'ORCL',
 'INTU',
 'PAYC',
 'IPGP',
 'INTC',
 'GLW',
 'TXN',
 'FTNT',
 'JNPR',
 'ADSK',
 'WDC',
 'LUMN',
 'PYPL',
 'MSFT',
 'ANSS',
 'IT',
 'ACN',
 'VRSN',
 'HPQ',
 'AMAT',
 'ATVI',
 'EA',
 'AMD',
 'KLAC',
 'NXPI',
 'SEDG',
 'MTCH',
 'NVDA',
 'TYL',
 'HPE',
 'CMCSA',
 'CTXS',
 'PTC',
 'FIS',
 'FB',
 'NLOK',
 'IBM',
 'TWTR',
 'MPWR',
 'DIS',
 'NFLX',
 'OMC',
 'AKAM',
 'GOOGL',
 'ANET',
 'PAYX',
 'FOXA',
 'FFIV',
 'SNPS',
 'GOOG',
 'EPAM',
 'LYV',
 'AVGO',
 'VZ',
 'TEL',
 'JKHY',
 'ADP',
 'TRMB',
 'QCOM',
 'MA',
 'NWSA',
 'TTWO',
 'AAPL',
 'TMUS',
 'NTAP',
 'KEYS',
 'CTSH',
 'MU',
 'CDW',
 'CRM',
 'LRCX']

In [34]:
df = price_df.set_index('symbol')
def is_contrarian(symbol):
    price = df.loc[f'{symbol}', 'currentPrice']
    price_high = df.loc[f'{symbol}', 'fiftyTwoWeekHigh']
    price_low = df.loc[f'{symbol}', 'fiftyTwoWeekLow']
    price_band = (price_high - price_low)
    if price < (price_low + (.3*(price_band))):
        return f'{symbol}'
    else:
        return 'OK'

In [35]:
is_contrarian('LRCX')

'LRCX'

In [36]:
contrarian_tickers = map(is_contrarian, symbol_list)
ticks = [i for i in symbol_list if is_contrarian(i) != 'OK' ]

In [37]:
ticks

['CSCO',
 'TER',
 'QRVO',
 'FOX',
 'SWKS',
 'MCHP',
 'CHTR',
 'DISH',
 'APH',
 'GPN',
 'WBD',
 'PARA',
 'ADBE',
 'NOW',
 'NWS',
 'ZBRA',
 'BR',
 'STX',
 'IPG',
 'CDAY',
 'ORCL',
 'INTU',
 'PAYC',
 'IPGP',
 'INTC',
 'TXN',
 'ADSK',
 'PYPL',
 'MSFT',
 'ANSS',
 'IT',
 'ACN',
 'VRSN',
 'AMAT',
 'NXPI',
 'MTCH',
 'NVDA',
 'TYL',
 'CMCSA',
 'FB',
 'NLOK',
 'TWTR',
 'DIS',
 'NFLX',
 'OMC',
 'AKAM',
 'GOOGL',
 'ANET',
 'FOXA',
 'FFIV',
 'GOOG',
 'EPAM',
 'TEL',
 'TRMB',
 'QCOM',
 'NWSA',
 'TTWO',
 'NTAP',
 'KEYS',
 'CTSH',
 'MU',
 'CRM',
 'LRCX']

In [38]:
data = price_df[price_df['symbol'].isin(ticks)]
data.head()

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,06/06/2022 12:25:58,CSCO,1.910366e+11,177767628800,45.295,64.29,41.02,0.076,3.446,11.061,3.55,2.850,3.705923,12.308423,0.0307
1,06/06/2022 12:25:58,TER,1.718498e+10,16304323584,107.270,168.91,97.63,-0.156,4.435,12.630,6.61,5.384,4.674092,16.228441,0.0041
3,06/06/2022 12:25:58,QRVO,1.172341e+10,12714641408,110.570,201.46,98.23,-0.247,2.737,7.654,12.73,9.260,2.523489,8.685781,NaN
4,06/06/2022 12:25:58,FOX,1.831854e+10,20874117120,31.520,40.91,28.96,-0.479,1.509,7.193,2.35,1.999,1.324455,13.412766,0.0151
6,06/06/2022 12:25:58,SWKS,1.715149e+10,18803027968,106.580,197.62,97.59,-0.046,3.566,9.060,12.29,8.239,3.252516,8.672092,0.0210

In [39]:
len(data)

63

In [40]:
today_date = datetime.now()
date_file =today_date.strftime('%m_%d_%Y')
data.to_csv(f'output/SP500_contrarian_df_{date_file}.csv')

In [41]:
cont_df = pd.read_csv(f'output/SP500_contrarian_df_{date_file}.csv')
cont_df

,Unnamed: 0,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,0,06/06/2022 12:25:58,CSCO,1.910366e+11,177767628800,45.2950,64.29,41.020,0.076,3.446,11.061,3.55,2.850,3.705923,12.308423,0.0307
1,1,06/06/2022 12:25:58,TER,1.718498e+10,16304323584,107.2700,168.91,97.630,-0.156,4.435,12.630,6.61,5.384,4.674092,16.228441,0.0041
2,3,06/06/2022 12:25:58,QRVO,1.172341e+10,12714641408,110.5700,201.46,98.230,-0.247,2.737,7.654,12.73,9.260,2.523489,8.685781,NaN
3,4,06/06/2022 12:25:58,FOX,1.831854e+10,20874117120,31.5200,40.91,28.960,-0.479,1.509,7.193,2.35,1.999,1.324455,13.412766,0.0151
4,6,06/06/2022 12:25:58,SWKS,1.715149e+10,18803027968,106.5800,197.62,97.590,-0.046,3.566,9.060,12.29,8.239,3.252516,8.672092,0.0210
5,8,06/06/2022 12:25:58,MCHP,3.931967e+10,47033372672,70.9100,90.00,63.340,2.712,6.895,15.561,5.73,2.270,5.764586,12.375218,0.0155
6,10,06/06/2022 12:25:58,CHTR,8.798617e+10,168875589632,490.7450,825.62,410.330,0.681,3.225,8.135,31.27,21.943,1.680408,15.693795,NaN
7,12,06/06/2022 12:25:58,DISH,1.139991e+10,33020866560,21.5580,46.31,17.040,-0.308,1.847,8.407,2.77,4.159,0.637540,7.782672,NaN
8,13,06/06/2022 12:25:58,APH,4.274704e+10,46405705728,71.4800,88.45,65.840,0.283,4.053,17.165,2.67,2.380,3.733008,26.771536,0.0114
9,15,06/06/2022 12:25:58,GPN,3.764419e+10,49546457088,129.7400,196.88,114.800,0.187,5.813,14.373,9.59,3.167,4.416382,13.528676,0.0082
10,16,06/06/2022 12:25:58,WBD,NaN,23732545536,17.1000,31.98,16.510,2.267,1.890,6.166,NaN,NaN,NaN,NaN,NaN
11,18,06/06/2022 12:25:58,PARA,NaN,33679296512,30.3800,47.46,26.110,-0.552,1.182,9.172,2.08,6.143,NaN,NaN,0.0339
12,20,06/06/2022 12:25:58,ADBE,2.040659e+11,187050377216,428.8900,699.54,370.270,0.019,11.588,28.684,16.25,10.020,12.641919,26.393232,NaN
13,21,06/06/2022 12:25:58,NOW,9.791994e+10,94031495168,492.0600,707.60,406.470,-0.098,15.026,131.697,7.22,1.091,15.647162,68.152360,NaN
14,22,06/06/2022 12:25:58,NWS,1.028516e+10,13301905408,17.4600,25.69,16.570,0.071,1.304,10.016,NaN,0.840,1.023807,NaN,0.0111
15,23,06/06/2022 12:25:58,ZBRA,1.793069e+10,20450457600,335.5200,615.00,309.000,-0.045,3.634,17.070,19.70,15.684,3.186545,17.031471,NaN
16,24,06/06/2022 12:25:58,BR,1.702622e+10,20994430976,146.0500,185.40,132.680,-0.167,3.907,18.797,7.04,4.655,3.168317,20.745739,0.0184
17,25,06/06/2022 12:25:58,STX,1.838305e+10,22073798656,82.5700,117.67,76.280,0.122,1.832,8.697,9.28,6.795,1.526071,8.897630,0.0347
18,26,06/06/2022 12:25:58,IPG,1.230091e+10,14458374144,31.2400,39.98,27.670,0.739,1.553,8.285,2.61,1.771,1.321626,11.969349,0.0361
19,27,06/06/2022 12:25:58,CDAY,8.382224e+09,9343748096,55.3900,130.37,48.930,NaN,9.123,841.779,0.45,-0.561,8.184168,123.088890,NaN
20,28,06/06/2022 12:25:58,ORCL,1.957840e+11,251351728128,73.3150,106.34,66.720,-0.500,6.009,13.661,5.26,3.543,4.680805,13.938212,0.0180
21,29,06/06/2022 12:25:58,INTU,1.160560e+11,124250726400,409.8500,716.86,339.360,4.000,10.886,39.697,13.64,7.581,10.167864,30.047653,0.0073
22,30,06/06/2022 12:25:58,PAYC,1.785167e+10,16730388480,297.4000,558.97,259.950,1.000,15.850,58.850,5.63,2.950,16.912617,52.824154,NaN
23,31,06/06/2022 12:25:58,IPGP,5.474291e+09,3546220800,102.6900,220.51,90.510,0.310,2.427,7.896,5.85,4.869,3.747307,17.553846,NaN
24,32,06/06/2022 12:25:58,INTC,1.763049e+11,176790503424,43.3501,58.42,40.310,1.415,2.275,5.604,3.70,5.158,2.268929,11.716244,0.0335
25,34,06/06/2022 12:25:58,TXN,1.568147e+11,154910294016,169.7900,202.26,160.500,0.257,8.170,14.562,8.23,7.788,8.270819,20.631836,0.0271
26,37,06/06/2022 12:25:58,ADSK,4.583357e+10,42427953152,208.3600,344.39,173.900,-0.901,9.673,51.359,6.83,5.928,10.449018,30.506590,NaN
27,40,06/06/2022 12:25:58,PYPL,1.020661e+11,103888453632,86.8699,310.16,71.831,-0.533,4.023,21.249,5.27,4.159,3.952831,16.483852,NaN
28,41,06/06/2022 12:25:58,MSFT,2.020097e+12,2048902299648,269.0600,349.67,246.440,0.094,10.640,21.571,10.54,8.939,10.490904,25.527514,0.0095
29,42,06/06/2022 12:25:58,ANSS,2.269101e+10,24261203968,260.0600,413.89,230.720,-0.067,12.724,38.745,7.94,5.318,11.900580,32.753147,NaN
30,43,06/06/2022 12:25:58,IT,2.189449e+10,26456133632,266.2300,369.00,228.200,0.881,5.589,23.045,7.13,8.025,4.624982,37.339413,NaN
31,44,06/06/2022 12:25:58,ACN,1.937565e+11,188926197760,306.3300,417.37,268.170,0.139,3.332,19.863,10.45,9.613,3.417528,29.313875,0.0135
32,45,06/06/2022 12:25:58,VRSN,1.974189e+10,20151259136,177.7300,257.03,159.690,0.075,14.917,21.681,6.17,5.425,14.614140,28.805510,NaN
33,47,06/06/2022 12:25:58,AMAT,1.023745e+11,97502601216,115.2200,167.06,101.330,0.639,4.034,11.943,8.85,6.400,4.235251,13.019209,0.0088
34,52,06/06/2022 12:25:58,NXPI,4.751691e+10,53111771136,178.6800,239.91,164.750,1.074,4.801,13.875,12.02,5.585,4.295119,14.865224,0.0195
35,54,06/06/2022 12:25:58,MTCH,2.368006e+10,25804969984,83.6200,182.00,67.869,NaN,8.650,27.773,2.58,1.884,7.937600,32.422480,NaN
36,55,06/06/2022 12:25:58,NVDA,4.657797e+11,455410810880,186.9600,346.47,155.670,1.034,16.921,40.607,5.21,3.243,17.306223,35.875240,0.0009
37,56,06/06/2022 12:25:58,TYL,1.459535e+10,17453617152,356.1900,557.55,327.970,0.068,9.953,50.622,8.15,3.825,8.323111,43.704296,NaN
38,58,06/06/2022 12:25:58,CMCSA,1.937908e+11,270841151488,42.4150,61.80,39.470,0.099,2.253,7.664,3.69,3.109,1.612370,11.494580,0.0260
39,62,06/06/2022 12:25:58,FB,5.260447e+11,513304657920,189.1200,384.33,169.000,-0.176,4.289,9.862,14.23,13.974,4.395941,13.289178,NaN
40,63,06/06/2022 12:25:58,NLOK,1.434899e+10,16732807168,24.6650,30.92,23.470,0.140,6.080,12.754,1.97,1.496,5.214022,12.520305,0.0209
41,65,06/06/2022 12:25:58,TWTR,3.140892e+10,38548004864,39.2803,73.34,31.300,6.681,7.353,70.533,0.96,-0.228,5.991270,40.916980,NaN
42,67,06/06/2022 12:25:58,DIS,1.967617e+11,256654311424,108.2500,187.58,99.470,63.358,3.516,24.304,5.06,1.094,2.695809,21.393280,NaN
43,68,06/06/2022 12:25:58,NFLX,8.699347e+10,95862595584,196.3948,700.99,162.710,-0.059,3.153,14.854,13.09,11.091,2.861408,15.003423,NaN
44,69,06/06/2022 12:25:58,OMC,1.527874e+10,19207329792,71.8800,91.61,65.760,-0.376,1.346,8.254,6.41,6.420,1.070480,11.213728,0.0364
45,70,06/06/2022 12:25:58,AKAM,1.641373e+10,19784464384,101.0200,123.25,93.740,0.424,5.716,16.575,5.94,3.641,4.742176,17.006733,NaN
46,71,06/06/2022 12:25:58,GOOGL,1.550361e+12,1397453881344,2335.5810,3030.93,2037.690,-0.063,5.169,14.581,112.42,103.805,5.734983,20.775494,NaN
47,72,06/06/2022 12:25:58,ANET,3.173487e+10,32227203072,103.2700,148.57,85.180,0.284,10.932,33.051,3.44,2.463,10.764746,30.020348,NaN
48,74,06/06/2022 12:25:58,FOXA,1.875413e+10,24571428864,34.0400,44.95,31.350,NaN,1.808,8.218,3.56,2.958,1.379894,9.561798,0.0143
49,75,06/06/2022 12:25:58,FFIV,1.021674e+10,9871137792,166.8600,249.00,151.660,0.314,3.718,18.315,13.18,5.340,3.848350,12.660090,NaN
50,77,06/06/2022 12:25:58,GOOG,1.552571e+12,1408740491264,2339.1850,3042.00,2044.160,-0.063,5.211,14.699,112.30,103.805,5.743158,20.829786,NaN
51,78,06/06/2022 12:25:58,EPAM,1.863806e+10,13873497088,328.6000,725.40,168.590,0.644,3.692,22.084,11.17,7.211,4.959379,29.418085,NaN
52,82,06/06/2022 12:25:58,TEL,4.295910e+10,43690319872,131.6500,166.44,119.580,0.130,2.821,11.941,7.91,6.788,2.773702,16.643488,0.0179
53,85,06/06/2022 12:25:58,TRMB,1.722166e+10,17879977984,68.6100,96.49,59.890,-0.361,4.886,23.125,2.96,2.197,4.706529,23.179054,NaN
54,86,06/06/2022 12:25:58,QCOM,1.575056e+11,160586792960,140.6300,193.58,122.170,0.680,4.090,11.087,11.64,7.870,4.011450,12.081615,0.0222
55,88,06/06/2022 12:25:58,NWSA,1.021723e+10,13889631232,17.2000,26.87,16.380,0.018,1.383,10.954,1.03,0.830,1.017045,16.699030,0.0112
56,89,06/06/2022 12:25:58,TTWO,1.465002e+10,10856370176,127.0600,195.83,101.850,-0.210,3.180,12.955,6.70,4.836,4.290874,18.964180,NaN
57,92,06/06/2022 12:25:58,NTAP,1.583731e+10,15044795392,71.2500,96.82,64.580,0.375,2.429,11.038,5.51,4.113,2.557292,12.931034,0.0281
58,93,06/06/2022 12:25:58,KEYS,2.700968e+10,25562640384,147.5600,209.08,127.930,0.348,5.101,17.989,7.48,4.780,5.390078,19.727272,NaN
59,94,06/06/2022 12:25:58,CTSH,3.914374e+10,41370865664,73.7200,93.47,66.190,0.853,2.235,12.357,4.52,3.545,2.115078,16.298672,0.0147
60,95,06/06/2022 12:25:58,MU,7.871434e+10,73692512256,70.2700,98.45,65.670,2.774,2.364,4.318,11.51,6.461,2.525405,6.105125,0.0056
61,97,06/06/2022 12:25:58,CRM,1.798511e+11,178013601792,182.5900,311.75,154.550,NaN,6.720,58.098,4.71,1.818,6.788885,38.766453,NaN
62,98,06/06/2022 12:25:58,LRCX,7.274874e+10,65261465600,516.6850,731.85,442.530,-0.015,3.899,11.775,36.65,29.588,4.346669,14.097816,0.0122

In [42]:
data_merge = cont_df[['symbol', 'marketCap', 'fiftyTwoWeekHigh', 'fiftyTwoWeekLow']]

## Price targets

In [43]:
px_target_cols = ['symbol', 'sector', 'industry','currentPrice', 'targetLowPrice', 'targetMedianPrice','numberOfAnalystOpinions',
            'targetMeanPrice', 'targetHighPrice', 'recommendationMean']

In [44]:
appended_data = []
for ticker in ticks:
    data = yf.Ticker(ticker)
    df = pd.DataFrame([data.info])
    px_target = df[px_target_cols]
    appended_data.append(px_target)

contrarian_df = pd.DataFrame(np.row_stack(appended_data))
contrarian_df.columns =  ['Ticker', 'Sector', 'Industry','Price', 'Low Price', 'Median Price','# of Ratings',
            'Mean Price', 'High Price', 'Avg Rating']
contrarian_df = contrarian_df[['Ticker', 'Sector', 'Industry','Price', 'Low Price', 'Median Price', 'Mean Price', 'High Price',
                 '# of Ratings', 'Avg Rating']]
contrarian_df

,Ticker,Sector,Industry,Price,Low Price,Median Price,Mean Price,High Price,# of Ratings,Avg Rating
0,CSCO,Technology,Communication Equipment,45.305,45,62.5,62.74,73,24,2.5
1,TER,Technology,Semiconductor Equipment & Materials,107.16,90,136.5,135.1,163,20,2.2
2,QRVO,Technology,Semiconductors,110.5694,120,135,149.86,235,22,2.5
3,FOX,Communication Services,Broadcasting,31.52,51.5,51.5,51.5,51.5,1,None
4,SWKS,Technology,Semiconductors,106.44,120,150,151,226,25,2.5
5,MCHP,Technology,Semiconductors,70.78,67,85,85.78,125,23,2.2
6,CHTR,Communication Services,Entertainment,490.65,393,630,623.22,805,27,2.5
7,DISH,Communication Services,Entertainment,21.53,24,44,40.87,61,15,2.2
8,APH,Technology,Electronic Components,71.45,79,87,85.77,94,13,2.2
9,GPN,Industrials,Specialty Business Services,129.92,142,180,180.64,240,34,1.8
10,WBD,Communication Services,Entertainment,17.045,18,37.5,34.65,52,20,2.4
11,PARA,Communication Services,Entertainment,30.4,24,35,36.56,60,25,2.7
12,ADBE,Technology,Software—Infrastructure,428.74,455,570,563.7,650,27,1.9
13,NOW,Technology,Software—Application,491.63,390,650,657.68,850,31,1.8
14,NWS,Communication Services,Broadcasting,17.47,None,None,None,None,None,None
15,ZBRA,Technology,Communication Equipment,335.37,400,527.5,514.4,600,10,2
16,BR,Technology,Information Technology Services,146.125,161,175.5,178.17,199,6,2.7
17,STX,Technology,Computer Hardware,82.58,None,None,None,None,None,None
18,IPG,Communication Services,Advertising Agencies,31.23,32,40,40.22,46,9,2.4
19,CDAY,Technology,Software—Application,55.37,None,None,None,None,None,None
20,ORCL,Technology,Software—Infrastructure,73.13,70,89,92.17,126,24,2.7
21,INTU,Technology,Software—Application,408.82,510,625,618.33,720,20,1.8
22,PAYC,Technology,Software—Application,297.905,334,385,385.71,450,17,2
23,IPGP,Technology,Semiconductor Equipment & Materials,102.88,95,153.5,151.88,183,8,2.3
24,INTC,Technology,Semiconductors,43.27,37,50.5,52.36,74,40,2.9
25,TXN,Technology,Semiconductors,168.83,150,187.5,191.93,297,28,2.6
26,ADSK,Technology,Software—Application,207.9192,210,280,284.25,440,19,2
27,PYPL,Financial Services,Credit Services,86.645,82,115,124.23,255,45,2.1
28,MSFT,Technology,Software—Infrastructure,268.45,298.18,360,362.95,425.96,46,1.7
29,ANSS,Technology,Software—Application,259.54,245,320,325.36,420,14,2.7
30,IT,Technology,Information Technology Services,266.215,315,334,330.29,342,7,2.1
31,ACN,Technology,Information Technology Services,305.65,None,None,None,None,None,None
32,VRSN,Technology,Software—Infrastructure,177.64,210,227,240,283,3,2.5
33,AMAT,Technology,Semiconductor Equipment & Materials,114.68,130,170,166.45,205,31,2.1
34,NXPI,Technology,Semiconductors,177.215,160,207.5,213.31,320,26,2.2
35,MTCH,Communication Services,Internet Content & Information,83.29,81,125,125,170,21,1.9
36,NVDA,Technology,Semiconductors,185.73,160,350,326.46,400,44,2
37,TYL,Technology,Software—Application,356.16,408,520,509.85,600,17,2.1
38,CMCSA,Communication Services,Entertainment,42.29,40,58,56.03,70,32,2.2
39,FB,Communication Services,Internet Content & Information,188.4706,185,300,301.33,553,54,2
40,NLOK,Technology,Software—Infrastructure,24.61,22.4,27.5,27.33,31.6,6,2.2
41,TWTR,Communication Services,Internet Content & Information,39.1998,33,54,51.88,77.8,30,3
42,DIS,Communication Services,Entertainment,108.06,None,None,None,None,None,2
43,NFLX,Communication Services,Entertainment,196.08,217,300,338.95,735,38,2.7
44,OMC,Communication Services,Advertising Agencies,71.77,77,90,92.56,107,9,2.5
45,AKAM,Technology,Software—Infrastructure,100.86,90,120,125.53,168,15,2.2
46,GOOGL,Communication Services,Internet Content & Information,2331.8716,2658,3300,3303.83,4533.34,45,1.7
47,ANET,Technology,Computer Hardware,103.035,124,148,150.29,177,17,2.2
48,FOXA,Communication Services,Broadcasting,33.995,32,46,44.96,55,23,2.3
49,FFIV,Technology,Software—Infrastructure,166.45,155,215,215.47,303,15,2.5
50,GOOG,Communication Services,Internet Content & Information,2333.24,2950,3150,3168.89,3600,9,1.5
51,EPAM,Technology,Information Technology Services,328.09,380,411,473.62,771,13,1.7
52,TEL,Technology,Electronic Components,131.53,None,None,None,None,None,None
53,TRMB,Technology,Scientific & Technical Instruments,68.52,70,94,90.75,100,8,2.1
54,QCOM,Technology,Semiconductors,140.46,150,200,202.8,471.6,32,2
55,NWSA,Communication Services,Broadcasting,17.195,28,30,30.87,34.1,7,1.9
56,TTWO,Communication Services,Electronic Gaming & Multimedia,127.015,155.26,200,200.81,231,25,1.9
57,NTAP,Technology,Computer Hardware,71.2,74,96,97.95,124,19,2.5
58,KEYS,Technology,Scientific & Technical Instruments,147.31,176,195,198.69,230,13,2
59,CTSH,Technology,Information Technology Services,73.65,80,93,92.61,103,23,2.4
60,MU,Technology,Semiconductors,70.2,83,111.5,111.82,165,32,1.9
61,CRM,Technology,Software—Application,182.92,219,297.5,289.83,385,46,1.8
62,LRCX,Technology,Semiconductor Equipment & Materials,516.335,520,625,648.27,840,23,2.1

In [45]:
data_merge.columns = ['Ticker', 'Market Cap', 'FiftyTwoWeekHigh', 'FiftyTwoWeekLow']
data_merge

   Ticker    Market Cap  FiftyTwoWeekHigh  FiftyTwoWeekLow
0    CSCO  1.910366e+11             64.29           41.020
1     TER  1.718498e+10            168.91           97.630
2    QRVO  1.172341e+10            201.46           98.230
3     FOX  1.831854e+10             40.91           28.960
4    SWKS  1.715149e+10            197.62           97.590
5    MCHP  3.931967e+10             90.00           63.340
6    CHTR  8.798617e+10            825.62          410.330
7    DISH  1.139991e+10             46.31           17.040
8     APH  4.274704e+10             88.45           65.840
9     GPN  3.764419e+10            196.88          114.800
10    WBD           NaN             31.98           16.510
11   PARA           NaN             47.46           26.110
12   ADBE  2.040659e+11            699.54          370.270
13    NOW  9.791994e+10            707.60          406.470
14    NWS  1.028516e+10             25.69           16.570
15   ZBRA  1.793069e+10            615.00          309.000
16     BR  1.702622e+10            185.40          132.680
17    STX  1.838305e+10            117.67           76.280
18    IPG  1.230091e+10             39.98           27.670
19   CDAY  8.382224e+09            130.37           48.930
20   ORCL  1.957840e+11            106.34           66.720
21   INTU  1.160560e+11            716.86          339.360
22   PAYC  1.785167e+10            558.97          259.950
23   IPGP  5.474291e+09            220.51           90.510
24   INTC  1.763049e+11             58.42           40.310
25    TXN  1.568147e+11            202.26          160.500
26   ADSK  4.583357e+10            344.39          173.900
27   PYPL  1.020661e+11            310.16           71.831
28   MSFT  2.020097e+12            349.67          246.440
29   ANSS  2.269101e+10            413.89          230.720
30     IT  2.189449e+10            369.00          228.200
31    ACN  1.937565e+11            417.37          268.170
32   VRSN  1.974189e+10            257.03          159.690
33   AMAT  1.023745e+11            167.06          101.330
34   NXPI  4.751691e+10            239.91          164.750
35   MTCH  2.368006e+10            182.00           67.869
36   NVDA  4.657797e+11            346.47          155.670
37    TYL  1.459535e+10            557.55          327.970
38  CMCSA  1.937908e+11             61.80           39.470
39     FB  5.260447e+11            384.33          169.000
40   NLOK  1.434899e+10             30.92           23.470
41   TWTR  3.140892e+10             73.34           31.300
42    DIS  1.967617e+11            187.58           99.470
43   NFLX  8.699347e+10            700.99          162.710
44    OMC  1.527874e+10             91.61           65.760
45   AKAM  1.641373e+10            123.25           93.740
46  GOOGL  1.550361e+12           3030.93         2037.690
47   ANET  3.173487e+10            148.57           85.180
48   FOXA  1.875413e+10             44.95           31.350
49   FFIV  1.021674e+10            249.00          151.660
50   GOOG  1.552571e+12           3042.00         2044.160
51   EPAM  1.863806e+10            725.40          168.590
52    TEL  4.295910e+10            166.44          119.580
53   TRMB  1.722166e+10             96.49           59.890
54   QCOM  1.575056e+11            193.58          122.170
55   NWSA  1.021723e+10             26.87           16.380
56   TTWO  1.465002e+10            195.83          101.850
57   NTAP  1.583731e+10             96.82           64.580
58   KEYS  2.700968e+10            209.08          127.930
59   CTSH  3.914374e+10             93.47           66.190
60     MU  7.871434e+10             98.45           65.670
61    CRM  1.798511e+11            311.75          154.550
62   LRCX  7.274874e+10            731.85          442.530

In [46]:
merged_cont_df = contrarian_df.merge(data_merge, how = 'inner', on = ['Ticker'])
merged_cont_df = merged_cont_df[['Ticker', 'Market Cap', 'Sector', 'Industry', 'Price', 'FiftyTwoWeekHigh', 'FiftyTwoWeekLow',
                  'Low Price', 'Median Price', 'Mean Price', 'High Price', '# of Ratings', 'Avg Rating']]

In [47]:
merged_cont_df['Contrarian %'] = (merged_cont_df['Price'] - merged_cont_df['FiftyTwoWeekLow'])/(merged_cont_df['FiftyTwoWeekHigh'] - merged_cont_df['FiftyTwoWeekLow'])*100

In [48]:
merged_cont_df = merged_cont_df[['Ticker', 'Market Cap', 'Sector', 'Industry', 'Price', 'Contrarian %','FiftyTwoWeekHigh', 'FiftyTwoWeekLow',
                  'Low Price', 'Median Price', 'Mean Price', 'High Price', '# of Ratings', 'Avg Rating']]

In [49]:
merged_cont_df['Market Cap $(m)'] = merged_cont_df['Market Cap']/1000000
column_price = ['Price', 'FiftyTwoWeekHigh', 'FiftyTwoWeekLow', 'Low Price', 'Median Price', 'Mean Price', 'High Price']
column_per = ['Contrarian %']
column_dollar = ['Market Cap $(m)']

merged_cont_df = merged_cont_df.drop('Market Cap',1)
merged_cont_df[['Low Price', 'Median Price', 'Mean Price', 'High Price']].apply(pd.to_numeric)
#merged_cont_df.apply(pd.to_numeric, errors='ignore').info()

<ipython-input-49-4be42e965c6f>:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  merged_cont_df = merged_cont_df.drop('Market Cap',1)

    Low Price  Median Price  Mean Price  High Price
0       45.00          62.5       62.74       73.00
1       90.00         136.5      135.10      163.00
2      120.00         135.0      149.86      235.00
3       51.50          51.5       51.50       51.50
4      120.00         150.0      151.00      226.00
5       67.00          85.0       85.78      125.00
6      393.00         630.0      623.22      805.00
7       24.00          44.0       40.87       61.00
8       79.00          87.0       85.77       94.00
9      142.00         180.0      180.64      240.00
10      18.00          37.5       34.65       52.00
11      24.00          35.0       36.56       60.00
12     455.00         570.0      563.70      650.00
13     390.00         650.0      657.68      850.00
14        NaN           NaN         NaN         NaN
15     400.00         527.5      514.40      600.00
16     161.00         175.5      178.17      199.00
17        NaN           NaN         NaN         NaN
18      32.00          40.0       40.22       46.00
19        NaN           NaN         NaN         NaN
20      70.00          89.0       92.17      126.00
21     510.00         625.0      618.33      720.00
22     334.00         385.0      385.71      450.00
23      95.00         153.5      151.88      183.00
24      37.00          50.5       52.36       74.00
25     150.00         187.5      191.93      297.00
26     210.00         280.0      284.25      440.00
27      82.00         115.0      124.23      255.00
28     298.18         360.0      362.95      425.96
29     245.00         320.0      325.36      420.00
30     315.00         334.0      330.29      342.00
31        NaN           NaN         NaN         NaN
32     210.00         227.0      240.00      283.00
33     130.00         170.0      166.45      205.00
34     160.00         207.5      213.31      320.00
35      81.00         125.0      125.00      170.00
36     160.00         350.0      326.46      400.00
37     408.00         520.0      509.85      600.00
38      40.00          58.0       56.03       70.00
39     185.00         300.0      301.33      553.00
40      22.40          27.5       27.33       31.60
41      33.00          54.0       51.88       77.80
42        NaN           NaN         NaN         NaN
43     217.00         300.0      338.95      735.00
44      77.00          90.0       92.56      107.00
45      90.00         120.0      125.53      168.00
46    2658.00        3300.0     3303.83     4533.34
47     124.00         148.0      150.29      177.00
48      32.00          46.0       44.96       55.00
49     155.00         215.0      215.47      303.00
50    2950.00        3150.0     3168.89     3600.00
51     380.00         411.0      473.62      771.00
52        NaN           NaN         NaN         NaN
53      70.00          94.0       90.75      100.00
54     150.00         200.0      202.80      471.60
55      28.00          30.0       30.87       34.10
56     155.26         200.0      200.81      231.00
57      74.00          96.0       97.95      124.00
58     176.00         195.0      198.69      230.00
59      80.00          93.0       92.61      103.00
60      83.00         111.5      111.82      165.00
61     219.00         297.5      289.83      385.00
62     520.00         625.0      648.27      840.00

In [50]:
merged_cont_df.style.format.apply({'Price': "${:.2f}",'FiftyTwoWeekHigh':"${:.2f}",'FiftyTwoWeekLow':"${:.2f}",
                        'Low Price': "${:.2f}", 'Median Price': "${:.2f}",'Mean Price': "${:.2f}",
                        'High Price': "${:.2f}"})

AttributeError: 'function' object has no attribute 'apply'

In [51]:
merged_cont_df.style.format({'Price': "${:.2f}",'FiftyTwoWeekHigh':"${:.2f}",'FiftyTwoWeekLow':"${:.2f}",
                        'Low Price': "${:.2f}", 'Mean Price': "${:.2f}",'Median Price': "${:.2f}",
                        'High Price': "${:.2f}"})

TypeError: unsupported format string passed to NoneType.__format__

In [52]:
merged_cont_df.head(2)

,Ticker,Sector,Industry,Price,Contrarian %,FiftyTwoWeekHigh,FiftyTwoWeekLow,Low Price,Median Price,Mean Price,High Price,# of Ratings,Avg Rating,Market Cap $(m)
0,CSCO,Technology,Communication Equipment,45.305,18.414267,64.29,41.02,45,62.5,62.74,73,24,2.5,191036.637184
1,TER,Technology,Semiconductor Equipment & Materials,107.16,13.369809,168.91,97.63,90,136.5,135.1,163,20,2.2,17184.976896

In [53]:
date_file =today_date.strftime('%m_%d_%Y')
#raw_df.to_csv(f'SP500_master_df_{date_file}.csv')
date_file

'06_06_2022'

In [54]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://{user}:{pw}@localhost/{db}'.format(user='root',
                                                                        pw='Boston1429$$',
                                                                        db='SP500'))
merged_cont_df.to_sql(f'contrarian_{date_file}', con=engine, if_exists='append', index=False)

63