In [79]:
import yfinance as yf

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [80]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 200)
pd.set_option('display.min_rows', 20)

In [81]:
amzn = yf.Ticker('AMZN')
amzn_info = pd.DataFrame([amzn.info])
amzn_info

,zip,sector,fullTimeEmployees,longBusinessSummary,city,phone,state,country,companyOfficers,website,maxAge,address1,industry,ebitdaMargins,profitMargins,grossMargins,operatingCashflow,revenueGrowth,operatingMargins,ebitda,targetLowPrice,recommendationKey,grossProfits,freeCashflow,targetMedianPrice,currentPrice,earningsGrowth,currentRatio,returnOnAssets,numberOfAnalystOpinions,targetMeanPrice,debtToEquity,returnOnEquity,targetHighPrice,totalCash,totalDebt,totalRevenue,totalCashPerShare,financialCurrency,revenuePerShare,quickRatio,recommendationMean,exchange,shortName,longName,exchangeTimezoneName,exchangeTimezoneShortName,isEsgPopulated,gmtOffSetMilliseconds,underlyingSymbol,...,shortPercentOfFloat,sharesShortPriorMonth,category,fiveYearAverageReturn,previousClose,regularMarketOpen,twoHundredDayAverage,trailingAnnualDividendYield,payoutRatio,volume24Hr,regularMarketDayHigh,navPrice,averageDailyVolume10Day,regularMarketPreviousClose,fiftyDayAverage,trailingAnnualDividendRate,open,averageVolume10days,expireDate,algorithm,dividendRate,exDividendDate,circulatingSupply,startDate,regularMarketDayLow,currency,trailingPE,regularMarketVolume,lastMarket,maxSupply,openInterest,marketCap,volumeAllCurrencies,strikePrice,averageVolume,dayLow,ask,askSize,volume,fiftyTwoWeekHigh,fromCurrency,fiveYearAvgDividendYield,fiftyTwoWeekLow,bid,tradeable,dividendYield,bidSize,dayHigh,regularMarketPrice,logo_url
0,98109-5210,Consumer Cyclical,1622000,"Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). It sells merchandise and content purchased for resale from third-party sellers through physical and online stores. The company also manufactures and sells electronic devices, including Kindle, Fire tablets, Fire TVs, Rings, and Echo and other devices; provides Kindle Direct Publishing, an online service that allows independent authors and publishers to make their books available in the Kindle Store; and develops and produces media content. In addition, it offers programs that enable sellers to sell their products on its websites, as well as its stores; and programs that allow authors, musicians, filmmakers, Twitch streamers, skill and app developers, and others to publish and sell content. Further, the company provides compute, storage, database, analytics, machine learning, and other services, as well as fulfillment, advertising, publishing, and digital content subscriptions. Additionally, it offers Amazon Prime, a membership program, which provides free shipping of various items; access to streaming of movies and series; and other services. The company serves consumers, sellers, developers, enterprises, and content creators. Amazon.com, Inc. was incorporated in 1994 and is headquartered in Seattle, Washington.",Seattle,206 266 1000,WA,United States,[],https://www.amazon.com,1,410 Terry Avenue North,Internet Retail,0.11606,0.04482,0.42137,39324000256,0.073,0.0412,55449001984,2250,buy,197478000000,18005624832,3700,2151.82,None,0.96,0.03353,53,3680.85,84.542,0.18046,4655,66384998400,113286995968,477748002816,130.54,USD,941.839,0.709,1.7,NMS,"Amazon.com, Inc.","Amazon.com, Inc.",America/New_York,EDT,True,-14400000,None,...,0.0089,3647235,None,None,2146.38,2191.37,3182.7922,None,0,None,2197.41,None,5078610,2146.38,2846.1582,None,2191.37,5078610,None,None,None,None,None,None,2100.2,USD,42.110806,4975032,None,None,None,1091291250688,None,None,4033216,2100.2,2165,1100,4975032,3773.08,None,None,2048.11,2157.85,False,None,1000,2197.41,2151.82,https://logo.clearbit.com/amazon.com

In [82]:
ticker_list = [['AAPL', 'MSFT', 'FB', 'AMZN', 'GOOGL']]

def stock_daily(ticker_list):
    start = pd.Timestamp('now').normalize() - pd.offsets.Day(1000)
    end = pd.Timestamp('now').normalize() + pd.offsets.BusinessDay(0)
    return yf.download(ticker_list, start=start, end=end).Close

def ticker_data(list):
    data = []
    for ticks in list:
        data.append(stock_daily(ticks))
    return data

res = ticker_data(ticker_list)
dataframes = [pd.DataFrame(ticker_list) for lst in res]
print(dataframes[0])

df = pd.concat(map(stock_daily, ticker_list), axis=1)

# I transposed for prettier printing
df.T

[*********************100%***********************]  5 of 5 completed
      0     1   2     3      4
0  AAPL  MSFT  FB  AMZN  GOOGL
[*********************100%***********************]  5 of 5 completed

Date,2019-08-26 00:00:00,2019-08-27 00:00:00,2019-08-28 00:00:00,2019-08-29 00:00:00,2019-08-30 00:00:00,2019-09-03 00:00:00,2019-09-04 00:00:00,2019-09-05 00:00:00,2019-09-06 00:00:00,2019-09-09 00:00:00,2019-09-10 00:00:00,2019-09-11 00:00:00,2019-09-12 00:00:00,2019-09-13 00:00:00,2019-09-16 00:00:00,2019-09-17 00:00:00,2019-09-18 00:00:00,2019-09-19 00:00:00,2019-09-20 00:00:00,2019-09-23 00:00:00,2019-09-24 00:00:00,2019-09-25 00:00:00,2019-09-26 00:00:00,2019-09-27 00:00:00,2019-09-30 00:00:00,2019-10-01 00:00:00,2019-10-02 00:00:00,2019-10-03 00:00:00,2019-10-04 00:00:00,2019-10-07 00:00:00,2019-10-08 00:00:00,2019-10-09 00:00:00,2019-10-10 00:00:00,2019-10-11 00:00:00,2019-10-14 00:00:00,2019-10-15 00:00:00,2019-10-16 00:00:00,2019-10-17 00:00:00,2019-10-18 00:00:00,2019-10-21 00:00:00,2019-10-22 00:00:00,2019-10-23 00:00:00,2019-10-24 00:00:00,2019-10-25 00:00:00,2019-10-28 00:00:00,2019-10-29 00:00:00,2019-10-30 00:00:00,2019-10-31 00:00:00,2019-11-01 00:00:00,2019-11-04 00:00:00,...,2022-03-11 00:00:00,2022-03-14 00:00:00,2022-03-15 00:00:00,2022-03-16 00:00:00,2022-03-17 00:00:00,2022-03-18 00:00:00,2022-03-21 00:00:00,2022-03-22 00:00:00,2022-03-23 00:00:00,2022-03-24 00:00:00,2022-03-25 00:00:00,2022-03-28 00:00:00,2022-03-29 00:00:00,2022-03-30 00:00:00,2022-03-31 00:00:00,2022-04-01 00:00:00,2022-04-04 00:00:00,2022-04-05 00:00:00,2022-04-06 00:00:00,2022-04-07 00:00:00,2022-04-08 00:00:00,2022-04-11 00:00:00,2022-04-12 00:00:00,2022-04-13 00:00:00,2022-04-14 00:00:00,2022-04-18 00:00:00,2022-04-19 00:00:00,2022-04-20 00:00:00,2022-04-21 00:00:00,2022-04-22 00:00:00,2022-04-25 00:00:00,2022-04-26 00:00:00,2022-04-27 00:00:00,2022-04-28 00:00:00,2022-04-29 00:00:00,2022-05-02 00:00:00,2022-05-03 00:00:00,2022-05-04 00:00:00,2022-05-05 00:00:00,2022-05-06 00:00:00,2022-05-09 00:00:00,2022-05-10 00:00:00,2022-05-11 00:00:00,2022-05-12 00:00:00,2022-05-13 00:00:00,2022-05-16 00:00:00,2022-05-17 00:00:00,2022-05-18 00:00:00,2022-05-19 00:00:00,2022-05-20 00:00:00
AAPL,51.622501,51.040001,51.382500,52.252499,52.185001,51.424999,52.297501,53.320000,53.314999,53.542500,54.174999,55.897499,55.772499,54.687500,54.974998,55.174999,55.692501,55.240002,54.432499,54.680000,54.419998,55.257500,54.972500,54.705002,55.992500,56.147499,54.740002,55.205002,56.752499,56.764999,56.099998,56.757500,57.522499,59.052502,58.967499,58.830002,58.592499,58.820000,59.102501,60.127499,59.990002,60.794998,60.895000,61.645000,62.262501,60.822498,60.814999,62.189999,63.955002,64.375000,...,154.729996,150.619995,155.089996,159.589996,160.619995,163.979996,165.380005,168.820007,170.210007,174.070007,174.720001,175.600006,178.960007,177.770004,174.610001,174.309998,178.440002,175.059998,171.830002,172.139999,170.089996,165.750000,167.660004,170.399994,165.289993,165.070007,167.399994,167.229996,166.419998,161.789993,162.880005,156.800003,156.570007,163.639999,157.649994,157.960007,159.479996,166.020004,156.770004,157.279999,152.059998,154.509995,146.500000,142.559998,147.110001,145.539993,149.240005,140.820007,137.350006,137.589996
AMZN,1768.869995,1761.829956,1764.250000,1786.400024,1776.290039,1789.839966,1800.619995,1840.719971,1833.510010,1831.349976,1820.550049,1822.989990,1843.550049,1839.339966,1807.839966,1822.550049,1817.459961,1821.500000,1794.160034,1785.300049,1741.609985,1768.329956,1739.839966,1725.449951,1735.910034,1735.650024,1713.229980,1724.420044,1739.650024,1732.660034,1705.510010,1721.989990,1720.260010,1731.920044,1736.430054,1767.380005,1777.430054,1787.479980,1757.510010,1785.660034,1765.729980,1762.170044,1780.780029,1761.329956,1777.079956,1762.709961,1779.989990,1776.660034,1791.439941,1804.660034,...,2910.489990,2837.060059,2947.330078,3062.080078,3144.780029,3225.010010,3229.830078,3297.780029,3268.159912,3272.989990,3295.469971,3379.810059,3386.300049,3326.020020,3259.949951,3271.199951,3366.929932,3281.100098,3175.120117,3155.689941,3089.209961,3022.439941,3015.750000,3110.820068,3034.129883,3055.699951,3162.310059,3079.959961,2965.919922,2887.000000,2921.479980,2787.820068,2763.340088,2891.929932,2485.629883,2490.000000,2485.070068,2518.570068,2328.139893,2295.449951,2175.780029,2177.179932,2107.439941,2138.610107,2261.100098,2216.209961,2307.370117,2142.250000,2146.379883,2151.820068
FB,180.360001,181.300003,181.759995,185.570007,185.669998,182.389999,187.139999,190.899994,187.490005,188.759995,186.169998,188.490005,187.470001,187.190002,186.220001,188.080002,188.139999,190.139999,189.929993,186.820007,181.279999,182.800003,180.110001,177.100006,178.080002,175.809998,174.600006,179.380005,180.449997,179.679993,177.750000,179.850006,180.029999,184.190002,183.279999,188.889999,189.550003,190.389999,185.850006,189.759995,182.339996,186.149994,186.380005,187.889999,189.399994,189.309998,188.250000,191.649994,193.619995,194.720001,...,187.610001,186.630005,192.029999,203.630005,207.839996,216.490005,211.490005,216.649994,213.460007,219.570007,221.820007,223.589996,229.860001,227.850006,222.360001,224.850006,233.889999,231.839996,223.300003,222.949997,222.330002,216.460007,214.139999,214.990005,210.179993,210.770004,217.309998,200.419998,188.070007,184.110001,186.990005,180.949997,174.949997,205.729996,200.470001,211.130005,212.029999,223.410004,208.279999,203.770004,196.210007,197.649994,188.740005,191.240005,198.619995,200.039993,202.619995,192.240005,191.289993,193.539993
GOOGL,1171.180054,1170.819946,1173.750000,1194.239990,1190.530029,1169.550049,1182.270020,1212.189941,1206.319946,1205.270020,1205.699951,1220.000000,1234.969971,1240.030029,1231.630005,1229.880005,1232.650024,1238.750000,1229.839966,1234.689941,1218.329956,1245.939941,1242.290039,1225.949951,1221.140015,1206.000000,1177.920044,1189.430054,1210.959961,1208.250000,1190.130005,1202.400024,1209.469971,1215.709961,1217.770020,1242.239990,1243.000000,1252.800049,1244.410034,1244.280029,1241.199951,1257.630005,1259.109985,1264.300049,1288.979980,1260.660034,1260.699951,1258.800049,1272.250000,1289.609985,...,2597.409912,2519.020020,2583.959961,2665.610107,2676.780029,2722.510010,2722.030029,2797.360107,2765.510010,2831.439941,2833.459961,2829.110107,2850.110107,2838.770020,2781.350098,2803.010010,2859.429932,2811.820068,2730.959961,2717.770020,2665.750000,2576.469971,2554.290039,2597.879883,2534.600098,2553.530029,2600.179932,2560.800049,2496.290039,2392.709961,2461.479980,2373.000000,2285.889893,2370.449951,2282.189941,2331.659912,2346.679932,2445.219971,2330.110107,2314.929932,2250.219971,2287.899902,2272.050049,2256.879883,2321.010010,2288.899902,2329.459961,2237.989990,2207.679932,2178.159912
MSFT,135.449997,135.740005,135.559998,138.119995,137.860001,136.039993,137.630005,140.050003,139.100006,137.520004,136.080002,136.119995,137.520004,137.320007,136.330002,137.389999,138.520004,141.070007,139.440002,139.139999,137.380005,139.360001,139.539993,137.729996,139.029999,137.070007,134.649994,136.279999,138.119995,137.119995,135.669998,138.240005,139.100006,139.679993,139.550003,141.570007,140.410004,139.690002,137.410004,138.429993,136.369995,137.240005,139.940002,140.729996,144.190002,142.830002,144.610001,143.369995,143.720001,144.550003,...,280.070007,276.440002,287.149994,294.390015,295.220001,300.429993,299.160004,304.059998,299.489990,304.100006,303.679993,310.700012,315.410004,313.859985,308.309998,309.420013,314.970001,310.880005,299.500000,301.369995,296.970001,285.260010,282.059998,287.619995,279.829987,280.519989,285.299988,286.359985,280.809998,274.029999,280.720001,270.220001,283.220001,289.630005,277.519989,284.470001,281.779999,289.980011,277.350006,274.730011,264.579987,269.500000,260.549988,255.350006,261.119995,261.500000,266.820007,254.080002,253.139999,252.559998

## NDX Tickers

In [83]:
table_yf = pd.read_html('https://en.wikipedia.org/wiki/Nasdaq-100#Components', match='Company')
print(f'Total tables: {len(table_yf)}')
table_yf

ndx_df = pd.DataFrame(np.row_stack(table_yf))
ndx_df.columns = ['Company', 'Ticker', 'Sector', 'Industry']
ndx_df

tech = ndx_df[ndx_df['Sector']=='Information Technology']
tech.head()

Total tables: 1

,Company,Ticker,Sector,Industry
1,Adobe,ADBE,Information Technology,Application Software
2,ADP,ADP,Information Technology,Data Processing & Outsourced Services
8,AMD,AMD,Information Technology,Semiconductors
11,Analog Devices,ADI,Information Technology,Semiconductors
12,Ansys,ANSS,Information Technology,Application Software

In [84]:
semiconductors = tech[tech['Industry']=='Semiconductors']
semiconductors.head()

           Company Ticker                  Sector        Industry
8              AMD    AMD  Information Technology  Semiconductors
11  Analog Devices    ADI  Information Technology  Semiconductors
22        Broadcom   AVGO  Information Technology  Semiconductors
48           Intel   INTC  Information Technology  Semiconductors
63       Microchip   MCHP  Information Technology  Semiconductors

## Price Targets

In [85]:
px_target_cols = ['symbol', 'sector', 'industry','currentPrice', 'targetLowPrice', 'targetMedianPrice','numberOfAnalystOpinions',
            'targetMeanPrice', 'targetHighPrice', 'recommendationMean']

In [86]:
amzn_px_target = amzn_info[px_target_cols]
amzn_px_target

,symbol,sector,industry,currentPrice,targetLowPrice,targetMedianPrice,numberOfAnalystOpinions,targetMeanPrice,targetHighPrice,recommendationMean
0,AMZN,Consumer Cyclical,Internet Retail,2151.82,2250,3700,53,3680.85,4655,1.7

In [87]:
semi_ticker_list = semiconductors['Ticker'].to_list()

def price_target_pull(ticker_list):
    px_target_cols = ['symbol', 'sector', 'industry','currentPrice', 'targetLowPrice', 'targetMedianPrice','numberOfAnalystOpinions',
            'targetMeanPrice', 'targetHighPrice', 'recommendationMean']
    return yf.ticker(i).info[px_target_cols]
    

def stock_daily(ticker_list):
    start = pd.Timestamp('now').normalize() - pd.offsets.Day(1000)
    end = pd.Timestamp('now').normalize() + pd.offsets.BusinessDay(0)
    return yf.download(ticker_list, start=start, end=end).Close

def ticker_data(list):
    data = []
    for ticks in list:
        data.append(stock_daily(ticks))
    return data

res = ticker_data(ticker_list)
dataframes = [pd.DataFrame(ticker_list) for lst in res]
print(dataframes[0])

df = pd.concat(map(stock_daily, ticker_list), axis=1)

# I transposed for prettier printing
df.T

[*********************100%***********************]  5 of 5 completed
      0     1   2     3      4
0  AAPL  MSFT  FB  AMZN  GOOGL
[*********************100%***********************]  5 of 5 completed

Date,2019-08-26 00:00:00,2019-08-27 00:00:00,2019-08-28 00:00:00,2019-08-29 00:00:00,2019-08-30 00:00:00,2019-09-03 00:00:00,2019-09-04 00:00:00,2019-09-05 00:00:00,2019-09-06 00:00:00,2019-09-09 00:00:00,2019-09-10 00:00:00,2019-09-11 00:00:00,2019-09-12 00:00:00,2019-09-13 00:00:00,2019-09-16 00:00:00,2019-09-17 00:00:00,2019-09-18 00:00:00,2019-09-19 00:00:00,2019-09-20 00:00:00,2019-09-23 00:00:00,2019-09-24 00:00:00,2019-09-25 00:00:00,2019-09-26 00:00:00,2019-09-27 00:00:00,2019-09-30 00:00:00,2019-10-01 00:00:00,2019-10-02 00:00:00,2019-10-03 00:00:00,2019-10-04 00:00:00,2019-10-07 00:00:00,2019-10-08 00:00:00,2019-10-09 00:00:00,2019-10-10 00:00:00,2019-10-11 00:00:00,2019-10-14 00:00:00,2019-10-15 00:00:00,2019-10-16 00:00:00,2019-10-17 00:00:00,2019-10-18 00:00:00,2019-10-21 00:00:00,2019-10-22 00:00:00,2019-10-23 00:00:00,2019-10-24 00:00:00,2019-10-25 00:00:00,2019-10-28 00:00:00,2019-10-29 00:00:00,2019-10-30 00:00:00,2019-10-31 00:00:00,2019-11-01 00:00:00,2019-11-04 00:00:00,...,2022-03-11 00:00:00,2022-03-14 00:00:00,2022-03-15 00:00:00,2022-03-16 00:00:00,2022-03-17 00:00:00,2022-03-18 00:00:00,2022-03-21 00:00:00,2022-03-22 00:00:00,2022-03-23 00:00:00,2022-03-24 00:00:00,2022-03-25 00:00:00,2022-03-28 00:00:00,2022-03-29 00:00:00,2022-03-30 00:00:00,2022-03-31 00:00:00,2022-04-01 00:00:00,2022-04-04 00:00:00,2022-04-05 00:00:00,2022-04-06 00:00:00,2022-04-07 00:00:00,2022-04-08 00:00:00,2022-04-11 00:00:00,2022-04-12 00:00:00,2022-04-13 00:00:00,2022-04-14 00:00:00,2022-04-18 00:00:00,2022-04-19 00:00:00,2022-04-20 00:00:00,2022-04-21 00:00:00,2022-04-22 00:00:00,2022-04-25 00:00:00,2022-04-26 00:00:00,2022-04-27 00:00:00,2022-04-28 00:00:00,2022-04-29 00:00:00,2022-05-02 00:00:00,2022-05-03 00:00:00,2022-05-04 00:00:00,2022-05-05 00:00:00,2022-05-06 00:00:00,2022-05-09 00:00:00,2022-05-10 00:00:00,2022-05-11 00:00:00,2022-05-12 00:00:00,2022-05-13 00:00:00,2022-05-16 00:00:00,2022-05-17 00:00:00,2022-05-18 00:00:00,2022-05-19 00:00:00,2022-05-20 00:00:00
AAPL,51.622501,51.040001,51.382500,52.252499,52.185001,51.424999,52.297501,53.320000,53.314999,53.542500,54.174999,55.897499,55.772499,54.687500,54.974998,55.174999,55.692501,55.240002,54.432499,54.680000,54.419998,55.257500,54.972500,54.705002,55.992500,56.147499,54.740002,55.205002,56.752499,56.764999,56.099998,56.757500,57.522499,59.052502,58.967499,58.830002,58.592499,58.820000,59.102501,60.127499,59.990002,60.794998,60.895000,61.645000,62.262501,60.822498,60.814999,62.189999,63.955002,64.375000,...,154.729996,150.619995,155.089996,159.589996,160.619995,163.979996,165.380005,168.820007,170.210007,174.070007,174.720001,175.600006,178.960007,177.770004,174.610001,174.309998,178.440002,175.059998,171.830002,172.139999,170.089996,165.750000,167.660004,170.399994,165.289993,165.070007,167.399994,167.229996,166.419998,161.789993,162.880005,156.800003,156.570007,163.639999,157.649994,157.960007,159.479996,166.020004,156.770004,157.279999,152.059998,154.509995,146.500000,142.559998,147.110001,145.539993,149.240005,140.820007,137.350006,137.589996
AMZN,1768.869995,1761.829956,1764.250000,1786.400024,1776.290039,1789.839966,1800.619995,1840.719971,1833.510010,1831.349976,1820.550049,1822.989990,1843.550049,1839.339966,1807.839966,1822.550049,1817.459961,1821.500000,1794.160034,1785.300049,1741.609985,1768.329956,1739.839966,1725.449951,1735.910034,1735.650024,1713.229980,1724.420044,1739.650024,1732.660034,1705.510010,1721.989990,1720.260010,1731.920044,1736.430054,1767.380005,1777.430054,1787.479980,1757.510010,1785.660034,1765.729980,1762.170044,1780.780029,1761.329956,1777.079956,1762.709961,1779.989990,1776.660034,1791.439941,1804.660034,...,2910.489990,2837.060059,2947.330078,3062.080078,3144.780029,3225.010010,3229.830078,3297.780029,3268.159912,3272.989990,3295.469971,3379.810059,3386.300049,3326.020020,3259.949951,3271.199951,3366.929932,3281.100098,3175.120117,3155.689941,3089.209961,3022.439941,3015.750000,3110.820068,3034.129883,3055.699951,3162.310059,3079.959961,2965.919922,2887.000000,2921.479980,2787.820068,2763.340088,2891.929932,2485.629883,2490.000000,2485.070068,2518.570068,2328.139893,2295.449951,2175.780029,2177.179932,2107.439941,2138.610107,2261.100098,2216.209961,2307.370117,2142.250000,2146.379883,2151.820068
FB,180.360001,181.300003,181.759995,185.570007,185.669998,182.389999,187.139999,190.899994,187.490005,188.759995,186.169998,188.490005,187.470001,187.190002,186.220001,188.080002,188.139999,190.139999,189.929993,186.820007,181.279999,182.800003,180.110001,177.100006,178.080002,175.809998,174.600006,179.380005,180.449997,179.679993,177.750000,179.850006,180.029999,184.190002,183.279999,188.889999,189.550003,190.389999,185.850006,189.759995,182.339996,186.149994,186.380005,187.889999,189.399994,189.309998,188.250000,191.649994,193.619995,194.720001,...,187.610001,186.630005,192.029999,203.630005,207.839996,216.490005,211.490005,216.649994,213.460007,219.570007,221.820007,223.589996,229.860001,227.850006,222.360001,224.850006,233.889999,231.839996,223.300003,222.949997,222.330002,216.460007,214.139999,214.990005,210.179993,210.770004,217.309998,200.419998,188.070007,184.110001,186.990005,180.949997,174.949997,205.729996,200.470001,211.130005,212.029999,223.410004,208.279999,203.770004,196.210007,197.649994,188.740005,191.240005,198.619995,200.039993,202.619995,192.240005,191.289993,193.539993
GOOGL,1171.180054,1170.819946,1173.750000,1194.239990,1190.530029,1169.550049,1182.270020,1212.189941,1206.319946,1205.270020,1205.699951,1220.000000,1234.969971,1240.030029,1231.630005,1229.880005,1232.650024,1238.750000,1229.839966,1234.689941,1218.329956,1245.939941,1242.290039,1225.949951,1221.140015,1206.000000,1177.920044,1189.430054,1210.959961,1208.250000,1190.130005,1202.400024,1209.469971,1215.709961,1217.770020,1242.239990,1243.000000,1252.800049,1244.410034,1244.280029,1241.199951,1257.630005,1259.109985,1264.300049,1288.979980,1260.660034,1260.699951,1258.800049,1272.250000,1289.609985,...,2597.409912,2519.020020,2583.959961,2665.610107,2676.780029,2722.510010,2722.030029,2797.360107,2765.510010,2831.439941,2833.459961,2829.110107,2850.110107,2838.770020,2781.350098,2803.010010,2859.429932,2811.820068,2730.959961,2717.770020,2665.750000,2576.469971,2554.290039,2597.879883,2534.600098,2553.530029,2600.179932,2560.800049,2496.290039,2392.709961,2461.479980,2373.000000,2285.889893,2370.449951,2282.189941,2331.659912,2346.679932,2445.219971,2330.110107,2314.929932,2250.219971,2287.899902,2272.050049,2256.879883,2321.010010,2288.899902,2329.459961,2237.989990,2207.679932,2178.159912
MSFT,135.449997,135.740005,135.559998,138.119995,137.860001,136.039993,137.630005,140.050003,139.100006,137.520004,136.080002,136.119995,137.520004,137.320007,136.330002,137.389999,138.520004,141.070007,139.440002,139.139999,137.380005,139.360001,139.539993,137.729996,139.029999,137.070007,134.649994,136.279999,138.119995,137.119995,135.669998,138.240005,139.100006,139.679993,139.550003,141.570007,140.410004,139.690002,137.410004,138.429993,136.369995,137.240005,139.940002,140.729996,144.190002,142.830002,144.610001,143.369995,143.720001,144.550003,...,280.070007,276.440002,287.149994,294.390015,295.220001,300.429993,299.160004,304.059998,299.489990,304.100006,303.679993,310.700012,315.410004,313.859985,308.309998,309.420013,314.970001,310.880005,299.500000,301.369995,296.970001,285.260010,282.059998,287.619995,279.829987,280.519989,285.299988,286.359985,280.809998,274.029999,280.720001,270.220001,283.220001,289.630005,277.519989,284.470001,281.779999,289.980011,277.350006,274.730011,264.579987,269.500000,260.549988,255.350006,261.119995,261.500000,266.820007,254.080002,253.139999,252.559998

In [88]:
semi_dict = {}
for i in semi_ticker_list:
    semi_dict["px_{0}".format(i)] = yf.Ticker(i)

In [89]:
semi_dict

{'px_AMD': yfinance.Ticker object <AMD>,
 'px_ADI': yfinance.Ticker object <ADI>,
 'px_AVGO': yfinance.Ticker object <AVGO>,
 'px_INTC': yfinance.Ticker object <INTC>,
 'px_MCHP': yfinance.Ticker object <MCHP>,
 'px_MU': yfinance.Ticker object <MU>,
 'px_NVDA': yfinance.Ticker object <NVDA>,
 'px_NXPI': yfinance.Ticker object <NXPI>,
 'px_QCOM': yfinance.Ticker object <QCOM>,
 'px_SWKS': yfinance.Ticker object <SWKS>,
 'px_TXN': yfinance.Ticker object <TXN>}

In [90]:
semi_ticker_list = semiconductors['Ticker'].to_list()
ticker_list = semi_ticker_list
def price_target_pull(ticker_list):
    px_target_cols = ['symbol', 'sector', 'industry','currentPrice', 'targetLowPrice', 'targetMedianPrice','numberOfAnalystOpinions',
            'targetMeanPrice', 'targetHighPrice', 'recommendationMean']
    return yf.ticker(i).info[px_target_cols]
df_2 = price_target_pull(semi_ticker_list)

TypeError: 'module' object is not callable

In [91]:
msft_info = yf.Ticker('MSFT').info
msft_df = pd.DataFrame([yf.Ticker('MSFT').info])
msft_px_target = msft_df[px_target_cols]

In [92]:
msft_px_target

,symbol,sector,industry,currentPrice,targetLowPrice,targetMedianPrice,numberOfAnalystOpinions,targetMeanPrice,targetHighPrice,recommendationMean
0,MSFT,Technology,Software—Infrastructure,252.56,298.18,360,46,362.95,425.96,1.7

## Semis

In [93]:
semi_ticker_list = semiconductors['Ticker'].to_list()
ticker_list = semi_ticker_list
appended_data = []
for ticker in semi_ticker_list:
    data = yf.Ticker(ticker)
    df = pd.DataFrame([data.info])
    px_target = df[px_target_cols]
    appended_data.append(px_target)

In [94]:

semi_df = pd.DataFrame(np.row_stack(appended_data))
semi_df.columns =  ['Ticker', 'Sector', 'Industry','Price', 'Low Price', 'Median Price','# of Ratings',
            'Mean Price', 'High Price', 'Avg Rating']
semi_df = semi_df[['Ticker', 'Sector', 'Industry','Price', 'Low Price', 'Median Price', 'Mean Price', 'High Price',
                 '# of Ratings', 'Avg Rating']]
semi_df

,Ticker,Sector,Industry,Price,Low Price,Median Price,Mean Price,High Price,# of Ratings,Avg Rating
0,AMD,Technology,Semiconductors,93.5,97,140,136.8,200,38,2.2
1,ADI,Technology,Semiconductors,162.44,177,206,203.2,225,25,1.9
2,AVGO,Technology,Semiconductors,543.19,480,700,688.56,780,27,1.8
3,INTC,Technology,Semiconductors,41.65,37,50.5,52.36,74,40,2.9
4,MCHP,Technology,Semiconductors,66.67,67,85,85.78,125,23,2.2
5,MU,Technology,Semiconductors,68.9,83,111.5,111.82,165,32,1.9
6,NVDA,Technology,Semiconductors,166.94,160,350,326.46,400,44,2
7,NXPI,Technology,Semiconductors,180.11,160,207.5,213.31,320,26,2.2
8,QCOM,Technology,Semiconductors,131.6,150,200,202.8,471.6,32,2
9,SWKS,Technology,Semiconductors,103,120,150,151,226,25,2.5
10,TXN,Technology,Semiconductors,169.81,150,187.5,191.93,297,28,2.6

In [95]:
tech['Industry'].value_counts()

Application Software                          17
Semiconductors                                11
Data Processing & Outsourced Services          4
Semiconductor Equipment                        4
Systems Software                               2
Technology Hardware, Storage & Peripherals     1
Communications Equipment                       1
IT Consulting & Other Services                 1
Internet Services & Infrastructure             1
Name: Industry, dtype: int64

## Application software

In [96]:
app_software = tech[tech['Industry']=='Application Software']
app_soft_list = app_software['Ticker'].to_list()
ticker_list = app_soft_list

appended_data = []
for ticker in ticker_list:
    data = yf.Ticker(ticker)
    df = pd.DataFrame([data.info])
    px_target = df[px_target_cols]
    appended_data.append(px_target)

In [97]:
app_sw_df = pd.DataFrame(np.row_stack(appended_data))
app_sw_df.columns =  ['Ticker', 'Sector', 'Industry','Price', 'Low Price', 'Median Price','# of Ratings',
            'Mean Price', 'High Price', 'Avg Rating']
app_sw_df = app_sw_df[['Ticker', 'Sector', 'Industry','Price', 'Low Price', 'Median Price', 'Mean Price', 'High Price',
                 '# of Ratings', 'Avg Rating']]
app_sw_df

,Ticker,Sector,Industry,Price,Low Price,Median Price,Mean Price,High Price,# of Ratings,Avg Rating
0,ADBE,Technology,Software—Infrastructure,399.09,455,570,563.7,650,27,1.9
1,ANSS,Technology,Software—Application,252.15,245,320,325.36,420,14,2.7
2,TEAM,Technology,Software—Application,177.4,220,383.5,377,550,20,2
3,ADSK,Technology,Software—Application,191.41,210,280,284.25,440,19,2
4,CDNS,Technology,Software—Application,146.6,160,193,192.14,240,13,2.2
5,CRWD,Technology,Software—Infrastructure,148.74,210,275,271.16,350,31,1.6
6,DDOG,Technology,Software—Application,94.79,135,168.5,171.72,225,20,2
7,DOCU,Technology,Software—Application,76.75,60,104.5,119.17,250,18,2.3
8,INTU,Technology,Software—Application,367.78,510,625,618.33,720,20,1.8
9,MRVL,Technology,Semiconductors,54.07,70,95,93.71,125,26,1.9
10,OKTA,Technology,Software—Infrastructure,84.22,125,215.5,224.82,320,28,1.9
11,PANW,Technology,Software—Infrastructure,478.68,510,635.1,649.2,823,35,1.7
12,SPLK,Technology,Software—Infrastructure,98.9,125,153.5,159.24,225,30,2.2
13,SNPS,Technology,Software—Infrastructure,306.72,325,396,391.22,445,13,1.9
14,WDAY,Technology,Software—Application,165.99,230,309.5,308.88,360,32,1.7
15,ZM,Technology,Software—Application,89.74,96,160,195.3,643,29,2.3
16,ZS,Technology,Software—Infrastructure,136.89,195,320,322.29,500,33,1.9