In [16]:
import pandas as pd
import glob
from datetime import datetime

In [17]:
files =glob.glob('*csv')

In [18]:
from ticker_convert import ticker_convert

In [19]:
files
SP500_tickers_list = []
for i in files:
    x = i.replace(".csv", "")
    SP500_tickers_list.append(x)
SP500_tickers_list

['CSCO',
 'TER',
 'V',
 'QRVO',
 'FOX',
 'FLT',
 'SWKS',
 'ENPH',
 'MCHP',
 'CDNS',
 'CHTR',
 'T',
 'DISH',
 'APH',
 'MSI',
 'GPN',
 'WBD',
 'DXC',
 'PARA',
 'ADI',
 'ADBE',
 'NOW',
 'NWS',
 'ZBRA',
 'BR',
 'STX',
 'IPG',
 'CDAY',
 'ORCL',
 'INTU',
 'PAYC',
 'IPGP',
 'INTC',
 'GLW',
 'TXN',
 'FTNT',
 'JNPR',
 'ADSK',
 'WDC',
 'LUMN',
 'PYPL',
 'MSFT',
 'ANSS',
 'IT',
 'ACN',
 'VRSN',
 'HPQ',
 'AMAT',
 'ATVI',
 'EA',
 'AMD',
 'KLAC',
 'NXPI',
 'SEDG',
 'MTCH',
 'NVDA',
 'TYL',
 'HPE',
 'CMCSA',
 'CTXS',
 'PTC',
 'FIS',
 'FB',
 'NLOK',
 'IBM',
 'TWTR',
 'MPWR',
 'DIS',
 'NFLX',
 'OMC',
 'AKAM',
 'GOOGL',
 'ANET',
 'PAYX',
 'FOXA',
 'FFIV',
 'SNPS',
 'GOOG',
 'EPAM',
 'LYV',
 'AVGO',
 'VZ',
 'TEL',
 'JKHY',
 'ADP',
 'TRMB',
 'QCOM',
 'MA',
 'NWSA',
 'TTWO',
 'AAPL',
 'TMUS',
 'NTAP',
 'KEYS',
 'CTSH',
 'MU',
 'CDW',
 'CRM',
 'LRCX']

In [20]:
tickers_df = map(ticker_convert,SP500_tickers_list)
SP500_master_df = []
for i in tickers_df:
    df = pd.DataFrame(i)
    SP500_master_df.append(df)
SP500_master_df = pd.concat(SP500_master_df)

In [22]:
today_date = datetime.now()
date = today_date.strftime('%m/%d/%Y %H:%M:%S')
SP500_master_df['Date'] = date
SP500_master_df.to_csv('output/SP500_master_df.csv')

In [23]:
SP500_master_df.columns

Index(['symbol', 'marketCap', 'enterpriseValue', 'currentPrice',
       'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'earningsGrowth',
       'enterpriseToRevenue', 'enterpriseToEbitda', 'forwardEps',
       'trailingEps', 'priceToSalesTrailing12Months', 'forwardPE',
       'dividendYield', 'Date'],
      dtype='object')

In [24]:
raw_df = pd.read_csv('output/SP500_master_df.csv')
raw_df.columns
raw_df = raw_df.drop('Unnamed: 0', 1)
raw_df = raw_df[['Date','symbol', 'marketCap', 'enterpriseValue', 'currentPrice',
       'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'earningsGrowth',
       'enterpriseToRevenue', 'enterpriseToEbitda', 'forwardEps',
       'trailingEps', 'priceToSalesTrailing12Months', 'forwardPE',
       'dividendYield']]
raw_df

<ipython-input-24-5dbd28508f64>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  raw_df = raw_df.drop('Unnamed: 0', 1)

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,06/02/2022 17:36:11,CSCO,1.931244e+11,194965143552,45.79,64.290000,41.02000,0.183,3.782,12.193,3.68,2.690,3.746423,12.442935,0.0307
1,06/02/2022 17:36:11,TER,1.802498e+10,16183294976,110.58,168.910000,97.63000,-0.156,4.402,12.537,6.45,5.309,4.902563,17.144186,0.0041
2,06/02/2022 17:36:11,V,NaN,454458212352,215.05,252.670000,186.67000,0.234,16.871,23.895,NaN,NaN,NaN,NaN,0.0075
3,06/02/2022 17:36:11,QRVO,1.249488e+10,13396545536,113.36,201.460000,98.23000,0.121,2.943,8.146,13.15,9.656,2.744748,8.620533,NaN
4,06/02/2022 17:36:11,FOX,1.897212e+10,23107883008,31.86,40.910000,28.96000,NaN,1.700,7.728,2.35,2.958,1.395933,13.557447,0.0156
5,06/02/2022 17:36:11,FLT,1.991477e+10,24022804480,245.26,282.020000,200.78000,0.122,8.477,16.263,15.29,9.686,7.027743,16.040548,NaN
6,06/02/2022 17:36:11,SWKS,1.833149e+10,19951753216,110.84,197.620000,97.59000,-0.213,3.905,9.960,12.87,8.970,3.587728,8.612276,0.0216
7,06/02/2022 17:36:11,ENPH,2.683804e+10,22035568640,198.93,282.460000,113.40000,0.703,14.482,84.994,2.98,1.152,17.638191,66.755030,NaN
8,06/02/2022 17:36:11,MCHP,4.068314e+10,43838595072,73.32,90.000000,63.34000,8.023,6.803,15.892,4.91,1.143,6.313532,14.932791,0.0165
9,06/02/2022 17:36:11,CDNS,4.473333e+10,40811286528,161.41,192.700000,122.04000,0.269,12.940,39.460,3.56,2.480,14.183128,45.339890,NaN
10,06/02/2022 17:36:11,CHTR,8.932636e+10,168875589632,498.22,825.620000,410.33000,0.681,3.225,8.135,31.27,21.943,1.706004,15.932843,NaN
11,06/02/2022 17:36:11,T,1.513178e+11,343495737344,21.19,22.333838,16.63142,-0.378,2.107,6.308,3.21,0.129,0.928159,6.601246,0.0559
12,06/02/2022 17:36:11,DISH,1.182401e+10,33020866560,22.36,46.310000,17.04000,-0.308,1.847,8.407,2.77,4.159,0.661257,8.072203,NaN
13,06/02/2022 17:36:11,APH,4.304606e+10,46405705728,71.98,88.450000,65.84000,0.283,4.053,17.165,2.67,2.380,3.759120,26.958801,0.0114
14,06/02/2022 17:36:11,MSI,3.785150e+10,40217600000,224.11,273.650000,199.24000,-0.032,4.922,15.947,9.88,7.245,4.632420,22.683199,0.0147
15,06/02/2022 17:36:11,GPN,3.816937e+10,49546457088,131.55,196.880000,114.80000,0.187,5.813,14.373,9.59,3.167,4.477995,13.717414,0.0082
16,06/02/2022 17:36:11,WBD,NaN,23732545536,18.00,32.400000,16.51000,2.267,1.890,6.166,NaN,NaN,NaN,NaN,NaN
17,06/02/2022 17:36:11,DXC,8.861156e+09,10545514496,35.13,44.180000,27.28000,-0.911,0.634,5.487,4.30,1.520,0.532457,8.169767,NaN
18,06/02/2022 17:36:11,PARA,NaN,32926785536,31.43,47.460000,26.11000,1.326,1.152,7.499,NaN,NaN,NaN,NaN,0.0339
19,06/02/2022 17:36:11,ADI,8.890702e+10,85252562944,169.24,191.950000,143.81000,-0.490,10.096,24.725,8.51,3.460,10.528867,19.887192,0.0192
20,06/02/2022 17:36:11,ADBE,2.099610e+11,187050377216,441.28,699.540000,370.27000,0.019,11.588,28.684,16.25,10.020,13.007126,27.155693,NaN
21,06/02/2022 17:36:11,NOW,1.004552e+11,94031495168,504.80,707.600000,406.47000,-0.098,15.026,131.697,7.22,1.091,16.052284,69.916900,NaN
22,06/02/2022 17:36:11,NWS,1.061504e+10,13919098880,18.02,25.690000,16.57000,0.018,1.386,10.977,NaN,0.830,1.056644,NaN,0.0111
23,06/02/2022 17:36:11,ZBRA,1.854794e+10,20450457600,347.07,615.000000,309.00000,-0.045,3.634,17.070,19.70,15.684,3.296240,17.617765,NaN
24,06/02/2022 17:36:11,BR,1.721041e+10,20994430976,147.63,185.400000,132.68000,-0.167,3.907,18.797,7.04,4.655,3.202592,20.970171,0.0184
25,06/02/2022 17:36:11,STX,1.884391e+10,22073798656,84.64,117.670000,76.28000,0.122,1.832,8.697,9.28,6.795,1.564329,9.120689,0.0347
26,06/02/2022 17:36:11,IPG,1.256472e+10,14458374144,31.91,39.980000,27.67000,0.739,1.553,8.285,2.61,1.771,1.349971,12.226054,0.0361
27,06/02/2022 17:36:11,CDAY,8.648568e+09,9343748096,57.15,130.370000,48.93000,NaN,9.123,841.779,0.45,-0.561,8.444218,127.000010,NaN
28,06/02/2022 17:36:11,ORCL,1.953167e+11,251351728128,73.14,106.340000,66.72000,-0.500,6.009,13.661,5.26,3.543,4.669632,13.904943,0.0180
29,06/02/2022 17:36:11,INTU,1.208727e+11,124250726400,426.86,716.860000,339.36000,4.000,10.886,39.697,13.64,7.581,10.589861,31.294720,0.0073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,06/02/2022 17:36:11,OMC,1.557207e+10,19207329792,73.26,91.610000,65.76000,-0.376,1.346,8.254,6.41,6.420,1.091031,11.429018,0.0364
70,06/02/2022 17:36:11,AKAM,1.669319e+10,19784464384,102.74,123.250000,93.74000,0.424,5.716,16.575,5.94,3.641,4.822918,17.296295,NaN
71,06/02/2022 17:36:11,GOOGL,1.561559e+12,1397453881344,2352.45,3030.930000,2037.69000,-0.063,5.169,14.581,112.42,103.805,5.776405,20.925547,NaN
72,06/02/2022 17:36:11,ANET,3.261682e+10,32227203072,106.14,148.570000,83.41500,0.284,10.932,33.051,3.44,2.463,11.063911,30.854650,NaN
73,06/02/2022 17:36:11,PAYX,4.543734e+10,45283831808,125.95,141.920000,100.69000,0.227,10.071,22.757,3.87,3.520,10.104821,32.545220,0.0264
74,06/02/2022 17:36:11,FOXA,1.896349e+10,24571428864,34.42,44.950000,31.35000,NaN,1.808,8.218,3.56,2.958,1.395298,9.668539,0.0143
75,06/02/2022 17:36:11,FFIV,1.030307e+10,9871137792,168.27,249.000000,151.66000,0.314,3.718,18.315,13.18,5.340,3.880869,12.767072,NaN
76,06/02/2022 17:36:11,SNPS,5.075882e+10,43219197952,330.81,377.600000,247.87000,0.932,9.595,37.855,9.02,4.810,11.269403,36.675163,NaN
77,06/02/2022 17:36:11,GOOG,1.563015e+12,1408740491264,2354.92,3042.000000,2044.16000,-0.063,5.211,14.699,112.30,103.805,5.781791,20.969900,NaN
78,06/02/2022 17:36:11,EPAM,1.972367e+10,13873497088,347.74,725.400000,168.59000,0.644,3.692,22.084,11.17,7.211,5.248249,31.131601,NaN
79,06/02/2022 17:36:11,LYV,2.183695e+10,26995554304,97.20,127.750000,74.23000,NaN,4.307,-2834.476,0.82,-4.165,3.483630,118.536580,NaN
80,06/02/2022 17:36:11,AVGO,2.381209e+11,255658999808,576.74,677.760000,455.71000,0.833,8.970,16.300,36.05,15.000,8.354828,15.998336,0.0279
81,06/02/2022 17:36:11,VZ,2.153031e+11,376384487424,51.29,57.610000,45.55000,-0.139,2.803,8.344,5.40,5.320,1.603150,9.498148,0.0531
82,06/02/2022 17:36:11,TEL,4.296563e+10,43690319872,131.67,166.440000,119.58000,0.130,2.821,11.941,7.91,6.788,2.774124,16.646017,0.0179
83,06/02/2022 17:36:11,JKHY,1.388639e+10,14073831424,187.55,205.370000,147.50000,0.383,7.542,28.146,5.15,4.302,7.441732,36.417477,0.0112
84,06/02/2022 17:36:11,ADP,9.426782e+10,92940173312,223.71,248.960000,192.18000,0.163,5.770,22.021,7.47,6.320,5.852381,29.947792,0.0199
85,06/02/2022 17:36:11,TRMB,1.762076e+10,17879977984,70.20,96.490000,59.89000,-0.361,4.886,23.125,2.96,2.197,4.815600,23.716215,NaN
86,06/02/2022 17:36:11,QCOM,1.637440e+11,160586792960,146.20,193.580000,122.17000,0.680,4.090,11.087,11.64,7.870,4.170334,12.560137,0.0222
87,06/02/2022 17:36:11,MA,3.567468e+11,360853635072,363.08,399.920000,305.61000,0.464,18.137,30.555,10.53,8.130,17.930578,34.480530,0.0059
88,06/02/2022 17:36:11,NWSA,1.052018e+10,13889631232,17.71,26.870000,16.38000,0.018,1.383,10.954,1.03,0.830,1.047201,17.194174,0.0112
89,06/02/2022 17:36:11,TTWO,1.487947e+10,10856370176,129.05,195.830000,101.85000,-0.210,3.180,12.955,6.70,4.836,4.358078,19.261194,NaN
90,06/02/2022 17:36:11,AAPL,2.480812e+12,2623592988672,151.21,182.940000,123.13000,0.086,6.797,20.084,6.18,5.610,6.426691,24.467640,0.0063
91,06/02/2022 17:36:11,TMUS,1.696210e+11,264606859264,135.80,150.200000,101.51000,-0.230,3.288,10.002,3.24,2.660,2.107643,41.913580,NaN
92,06/02/2022 17:36:11,NTAP,1.620407e+10,15044795392,72.90,96.820000,64.58000,0.375,2.429,11.038,5.51,4.113,2.616513,13.230490,0.0281
93,06/02/2022 17:36:11,KEYS,2.723299e+10,25562640384,148.78,209.080000,127.93000,0.348,5.101,17.989,7.48,4.780,5.434642,19.890373,NaN
94,06/02/2022 17:36:11,CTSH,3.982917e+10,41370865664,74.96,93.470000,66.19000,0.853,2.235,12.357,4.52,3.545,2.152114,16.584070,0.0147
95,06/02/2022 17:36:11,MU,8.442721e+10,73692512256,75.37,98.450000,65.67000,2.774,2.364,4.318,11.51,6.461,2.708692,6.548219,0.0056
96,06/02/2022 17:36:11,CDW,2.390489e+10,29284814848,176.13,208.710000,155.39000,-0.050,1.407,17.594,9.11,7.116,1.148126,19.333700,0.0118
97,06/02/2022 17:36:11,CRM,1.855740e+11,178013601792,188.40,311.750000,154.55000,NaN,6.720,58.098,4.71,1.818,7.004907,40.000000,NaN
98,06/02/2022 17:36:11,LRCX,7.368012e+10,65261465600,523.30,731.850000,442.53000,-0.015,3.899,11.775,36.65,29.588,4.402318,14.278307,0.0122

In [25]:
date_file =today_date.strftime('%m_%d_%Y')
raw_df.to_csv(f'output/SP500_master_df_{date_file}.csv')

In [26]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://{user}:{pw}@localhost/{db}'.format(user='root',
                                                                        pw='Boston1429$$',
                                                                        db='SP500'))
raw_df.to_sql(f'output/SP500_{date_file}', con=engine, if_exists='append', index=False)

99