In [82]:
import pandas as pd
import glob
from datetime import datetime

In [83]:
files =glob.glob('*csv')

In [84]:
from ticker_convert import ticker_convert

In [85]:
files
SP500_tickers_list = []
for i in files:
    x = i.replace(".csv", "")
    SP500_tickers_list.append(x)
SP500_tickers_list

['CSCO',
 'TER',
 'V',
 'QRVO',
 'FOX',
 'FLT',
 'SWKS',
 'ENPH',
 'MCHP',
 'CDNS',
 'CHTR',
 'T',
 'DISH',
 'APH',
 'MSI',
 'GPN',
 'WBD',
 'DXC',
 'PARA',
 'ADI',
 'ADBE',
 'NOW',
 'NWS',
 'ZBRA',
 'BR',
 'STX',
 'IPG',
 'CDAY',
 'ORCL',
 'INTU',
 'PAYC',
 'IPGP',
 'INTC',
 'GLW',
 'TXN',
 'FTNT',
 'JNPR',
 'ADSK',
 'WDC',
 'LUMN',
 'PYPL',
 'MSFT',
 'ANSS',
 'IT',
 'ACN',
 'VRSN',
 'HPQ',
 'AMAT',
 'ATVI',
 'EA',
 'AMD',
 'KLAC',
 'NXPI',
 'SEDG',
 'MTCH',
 'NVDA',
 'TYL',
 'HPE',
 'CMCSA',
 'CTXS',
 'PTC',
 'FIS',
 'FB',
 'NLOK',
 'IBM',
 'TWTR',
 'MPWR',
 'DIS',
 'NFLX',
 'OMC',
 'AKAM',
 'GOOGL',
 'ANET',
 'PAYX',
 'FOXA',
 'FFIV',
 'SNPS',
 'GOOG',
 'EPAM',
 'LYV',
 'AVGO',
 'VZ',
 'TEL',
 'JKHY',
 'ADP',
 'TRMB',
 'QCOM',
 'MA',
 'NWSA',
 'TTWO',
 'AAPL',
 'TMUS',
 'NTAP',
 'KEYS',
 'CTSH',
 'MU',
 'CSCO',
 'CDW',
 'CRM',
 'LRCX']

In [86]:
tickers_df = map(ticker_convert,SP500_tickers_list)
SP500_master_df = []
for i in tickers_df:
    df = pd.DataFrame(i)
    SP500_master_df.append(df)
SP500_master_df = pd.concat(SP500_master_df)

In [91]:
today_date = datetime.now()
date = today_date.strftime('%m/%d/%Y %H:%M:%S')
SP500_master_df['Date'] = date
SP500_master_df.to_csv('SP500_master_df.csv')

In [94]:
SP500_master_df.columns

Index(['symbol', 'marketCap', 'enterpriseValue', 'currentPrice',
       'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'earningsGrowth',
       'enterpriseToRevenue', 'enterpriseToEbitda', 'forwardEps',
       'trailingEps', 'priceToSalesTrailing12Months', 'forwardPE',
       'dividendYield', 'Date'],
      dtype='object')

In [97]:
raw_df = pd.read_csv('SP500_master_df.csv')
raw_df.columns
raw_df = raw_df.drop('Unnamed: 0', 1)
raw_df = raw_df[['Date','symbol', 'marketCap', 'enterpriseValue', 'currentPrice',
       'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'earningsGrowth',
       'enterpriseToRevenue', 'enterpriseToEbitda', 'forwardEps',
       'trailingEps', 'priceToSalesTrailing12Months', 'forwardPE',
       'dividendYield']]
raw_df

<ipython-input-97-a98c53e3806d>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  raw_df = raw_df.drop('Unnamed: 0', 1)

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,05/24/2022 13:40:36,CSCO,1.783385e+11,167596883968,42.930,64.290000,41.02000,0.076,3.249,10.434,3.56,2.850,3.457446,12.058989,0.0354
1,05/24/2022 13:40:36,TER,1.587932e+10,15493695488,99.120,168.910000,97.63000,-0.156,4.214,11.759,6.61,5.384,4.318971,14.995461,0.0043
2,05/24/2022 13:40:36,V,4.257668e+11,425086353408,201.195,252.670000,186.67000,0.234,15.781,22.351,8.38,6.358,15.806024,24.008951,0.0075
3,05/24/2022 13:40:36,QRVO,1.106223e+10,12666929152,102.020,201.460000,98.23000,-0.247,2.727,7.626,12.73,9.260,2.381170,8.014140,NaN
4,05/24/2022 13:40:36,FOX,1.842428e+10,23107883008,30.940,40.910000,28.96000,NaN,1.700,7.728,2.35,2.958,1.355623,13.165958,0.0156
5,05/24/2022 13:40:36,FLT,1.780772e+10,22924929024,230.250,282.020000,200.78000,0.279,7.605,14.886,17.71,10.594,5.907640,13.001130,NaN
6,05/24/2022 13:40:36,SWKS,1.703486e+10,19951753216,103.000,197.620000,97.59000,-0.213,3.905,9.960,12.87,8.970,3.333959,8.003108,0.0216
7,05/24/2022 13:40:36,ENPH,2.269894e+10,22035568640,168.250,282.460000,113.40000,0.703,14.482,84.994,2.98,1.152,14.917941,56.459732,NaN
8,05/24/2022 13:40:36,MCHP,3.699325e+10,43838595072,66.670,90.000000,63.34000,8.023,6.803,15.892,4.91,1.143,5.740905,13.578411,0.0165
9,05/24/2022 13:40:36,CDNS,4.062887e+10,40811286528,146.600,192.700000,122.04000,0.269,12.940,39.460,3.56,2.480,12.881770,41.179780,NaN
10,05/24/2022 13:40:36,CHTR,8.588577e+10,168875589632,479.030,825.620000,410.33000,0.681,3.225,8.135,31.27,21.943,1.640294,15.319156,NaN
11,05/24/2022 13:40:36,T,1.456764e+11,343495737344,20.400,22.583082,16.63142,-0.378,2.107,6.308,3.21,0.129,0.893556,6.355140,0.0559
12,05/24/2022 13:40:36,DISH,1.098851e+10,33020866560,20.780,46.310000,17.04000,-0.308,1.847,8.407,2.77,4.159,0.614532,7.501805,NaN
13,05/24/2022 13:40:36,APH,4.092306e+10,46405705728,68.430,88.450000,65.84000,0.283,4.053,17.165,2.67,2.380,3.573723,25.629213,0.0114
14,05/24/2022 13:40:36,MSI,3.551566e+10,40217600000,210.280,273.650000,199.24000,-0.032,4.922,15.947,9.88,7.245,4.346550,21.283400,0.0147
15,05/24/2022 13:40:36,GPN,3.542744e+10,49546457088,122.100,197.750000,114.80000,0.187,5.813,14.373,9.59,3.167,4.156315,12.732012,0.0082
16,05/24/2022 13:40:36,WBD,NaN,23732545536,17.740,32.760000,16.51000,2.267,1.890,6.166,NaN,NaN,NaN,NaN,NaN
17,05/24/2022 13:40:36,DXC,7.466275e+09,10545514496,29.600,44.180000,27.28000,-0.911,0.634,5.487,4.30,1.520,0.448640,6.883721,NaN
18,05/24/2022 13:40:36,PARA,NaN,32926785536,32.640,47.460000,26.11000,1.326,1.152,7.499,NaN,NaN,NaN,NaN,0.0339
19,05/24/2022 13:40:36,ADI,8.533477e+10,85252562944,162.440,191.950000,143.81000,-0.490,10.096,24.725,8.51,3.460,10.105821,19.088130,0.0192
20,05/24/2022 13:40:36,ADBE,1.898870e+11,187050377216,399.090,699.540000,370.27000,0.019,11.588,28.684,16.25,10.020,11.763537,24.559385,NaN
21,05/24/2022 13:40:36,NOW,8.617297e+10,94031495168,433.030,707.600000,406.47000,-0.098,15.026,131.697,7.22,1.091,13.770049,59.976456,NaN
22,05/24/2022 13:40:36,NWS,1.053846e+10,13919098880,17.890,26.210000,16.57000,0.018,1.386,10.977,NaN,0.830,1.049021,NaN,0.0111
23,05/24/2022 13:40:36,ZBRA,1.688319e+10,18690953216,321.500,615.000000,309.00000,-0.092,3.272,16.267,22.15,15.129,2.955740,14.514673,NaN
24,05/24/2022 13:40:36,BR,1.617615e+10,20467286016,137.990,185.400000,132.68000,0.064,3.709,17.662,7.06,4.663,2.931631,19.545326,0.0184
25,05/24/2022 13:40:36,STX,1.705861e+10,22050166784,79.400,117.670000,76.28000,0.122,1.830,8.688,9.20,8.148,1.416123,8.630435,0.0342
26,05/24/2022 13:40:36,IPG,1.145956e+10,14720659456,29.110,39.980000,27.66500,0.739,1.582,8.450,2.88,2.558,1.231231,10.107638,0.0372
27,05/24/2022 13:40:36,CDAY,8.218406e+09,9551197184,53.840,130.370000,48.93000,NaN,8.819,1240.415,0.84,-0.553,7.588556,64.095240,NaN
28,05/24/2022 13:40:36,ORCL,1.835427e+11,242386714624,68.790,106.340000,66.72000,-0.500,5.795,13.174,5.26,2.664,4.388140,13.077947,0.0183
29,05/24/2022 13:40:36,INTU,1.020951e+11,110851072000,361.000,716.860000,339.36000,4.000,9.712,35.416,13.78,7.775,8.944729,26.197388,0.0073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,05/24/2022 13:40:36,AKAM,1.584343e+10,19784464384,97.510,123.250000,93.74000,0.424,5.716,16.575,5.94,3.641,4.577407,16.415825,NaN
71,05/24/2022 13:40:36,GOOGL,1.445865e+12,1397453881344,2178.160,3030.930000,2115.92720,-0.063,5.169,14.581,112.42,103.805,5.348439,19.375200,NaN
72,05/24/2022 13:40:36,ANET,3.154127e+10,32227203072,102.640,148.570000,82.94000,0.284,10.932,33.051,3.44,2.463,10.699076,29.837208,NaN
73,05/24/2022 13:40:36,PAYX,4.232762e+10,45283831808,117.330,141.920000,99.88000,0.227,10.071,22.757,3.87,3.520,9.413249,30.317831,0.0264
74,05/24/2022 13:40:36,FOXA,1.843459e+10,24571428864,33.460,44.950000,31.35000,NaN,1.808,8.218,3.56,2.958,1.356382,9.398876,0.0143
75,05/24/2022 13:40:36,FFIV,9.568931e+09,9871137792,156.280,249.000000,151.66000,0.314,3.718,18.315,13.18,5.340,3.604340,11.857359,NaN
76,05/24/2022 13:40:36,SNPS,4.706250e+10,43219197952,306.720,377.600000,247.87000,0.932,9.595,37.855,9.02,4.810,10.448751,34.004433,NaN
77,05/24/2022 13:40:36,GOOG,1.451071e+12,1408740491264,2186.260,3042.000000,2127.46000,-0.063,5.211,14.699,112.30,103.805,5.367697,19.468030,NaN
78,05/24/2022 13:40:36,EPAM,1.817239e+10,13873497088,320.390,725.400000,168.59000,0.644,3.692,22.084,11.17,7.211,4.835470,28.683080,NaN
79,05/24/2022 13:40:36,LYV,2.005765e+10,26995554304,89.280,127.750000,74.23000,NaN,4.307,-2834.476,0.82,-4.165,3.199779,108.878050,NaN
80,05/24/2022 13:40:36,AVGO,2.242690e+11,255658999808,543.190,677.760000,455.53000,0.833,8.970,16.300,36.05,15.000,7.868813,15.067684,0.0279
81,05/24/2022 13:40:36,VZ,2.079150e+11,376384487424,49.530,57.610000,45.55000,-0.139,2.803,8.344,5.40,5.320,1.548139,9.172222,0.0531
82,05/24/2022 13:40:36,TEL,4.003208e+10,43690319872,122.680,166.440000,119.58000,0.130,2.821,11.941,7.91,6.788,2.584716,15.509482,0.0179
83,05/24/2022 13:40:36,JKHY,1.326222e+10,14073831424,179.120,205.370000,147.50000,0.383,7.542,28.146,5.15,4.302,7.107240,34.780582,0.0112
84,05/24/2022 13:40:36,ADP,8.791756e+10,92940173312,208.640,248.960000,192.18000,0.163,5.770,22.021,7.47,6.320,5.458141,27.930390,0.0199
85,05/24/2022 13:40:36,TRMB,1.637325e+10,17879977984,65.230,96.490000,59.89000,-0.361,4.886,23.125,2.96,2.197,4.474667,22.037163,NaN
86,05/24/2022 13:40:36,QCOM,1.473920e+11,160586792960,131.600,193.580000,122.17000,0.680,4.090,11.087,11.64,7.870,3.753871,11.305842,0.0222
87,05/24/2022 13:40:36,MA,3.303160e+11,360853635072,336.180,399.920000,305.61000,0.464,18.137,30.555,10.53,8.130,16.602130,31.925926,0.0059
88,05/24/2022 13:40:36,NWSA,1.046078e+10,13889631232,17.610,27.510000,16.54000,0.018,1.383,10.954,1.03,0.830,1.041288,17.097088,0.0112
89,05/24/2022 13:40:36,TTWO,1.338864e+10,10856370176,116.120,195.830000,101.85000,-0.210,3.180,12.955,6.70,4.836,3.921425,17.331345,NaN
90,05/24/2022 13:40:36,AAPL,2.257357e+12,2623592988672,137.590,182.940000,123.13000,0.086,6.797,20.084,6.18,5.610,5.847817,22.263754,0.0063
91,05/24/2022 13:40:36,TMUS,1.574303e+11,264606859264,126.040,150.200000,101.51000,-0.230,3.288,10.002,3.24,2.660,1.956166,38.901234,NaN
92,05/24/2022 13:40:36,NTAP,1.481261e+10,15044795392,66.640,96.820000,64.58000,0.375,2.429,11.038,5.51,4.113,2.391830,12.094374,0.0281
93,05/24/2022 13:40:36,KEYS,2.522319e+10,25562640384,137.800,209.080000,127.93000,0.348,5.101,17.989,7.48,4.780,5.033564,18.422460,NaN
94,05/24/2022 13:40:36,CTSH,3.763474e+10,41370865664,70.830,93.470000,66.19000,0.853,2.235,12.357,4.52,3.545,2.033541,15.670355,0.0147
95,05/24/2022 13:40:36,MU,7.717972e+10,73692512256,68.900,98.450000,65.67000,2.774,2.364,4.318,11.51,6.461,2.476169,5.986099,0.0056
96,05/24/2022 13:40:36,CSCO,1.811042e+11,194965143552,42.940,64.290000,41.02000,0.183,3.782,12.193,3.68,2.690,3.513243,11.668478,0.0307
97,05/24/2022 13:40:36,CDW,2.174283e+10,29284814848,160.200,208.710000,155.39000,-0.050,1.407,17.594,9.11,7.116,1.044284,17.585072,0.0118
98,05/24/2022 13:40:36,CRM,1.572552e+11,178013601792,159.650,311.750000,154.55000,NaN,6.720,58.098,4.71,1.818,5.935952,33.895966,NaN
99,05/24/2022 13:40:36,LRCX,6.675562e+10,65261465600,474.120,731.850000,442.53000,-0.015,3.899,11.775,36.65,29.588,3.988586,12.936425,0.0122

In [98]:
raw_df.to_csv('SP500_master_df_5_24_22.csv')