In [6]:
import pandas as pd
import glob
from datetime import datetime

In [7]:
files =glob.glob('*csv')

In [8]:
from ticker_convert import ticker_convert

In [9]:
files
SP500_tickers_list = []
for i in files:
    x = i.replace(".csv", "")
    SP500_tickers_list.append(x)
SP500_tickers_list

['CSCO',
 'TER',
 'V',
 'QRVO',
 'FOX',
 'FLT',
 'SWKS',
 'ENPH',
 'MCHP',
 'CDNS',
 'CHTR',
 'T',
 'DISH',
 'APH',
 'MSI',
 'GPN',
 'WBD',
 'DXC',
 'PARA',
 'ADI',
 'ADBE',
 'NOW',
 'NWS',
 'ZBRA',
 'BR',
 'STX',
 'IPG',
 'CDAY',
 'ORCL',
 'INTU',
 'PAYC',
 'IPGP',
 'INTC',
 'GLW',
 'TXN',
 'FTNT',
 'JNPR',
 'ADSK',
 'WDC',
 'LUMN',
 'PYPL',
 'MSFT',
 'ANSS',
 'IT',
 'ACN',
 'VRSN',
 'HPQ',
 'AMAT',
 'ATVI',
 'EA',
 'AMD',
 'KLAC',
 'NXPI',
 'SEDG',
 'MTCH',
 'NVDA',
 'TYL',
 'HPE',
 'CMCSA',
 'CTXS',
 'PTC',
 'FIS',
 'FB',
 'NLOK',
 'IBM',
 'TWTR',
 'MPWR',
 'DIS',
 'NFLX',
 'OMC',
 'AKAM',
 'GOOGL',
 'ANET',
 'PAYX',
 'FOXA',
 'FFIV',
 'SNPS',
 'GOOG',
 'EPAM',
 'LYV',
 'AVGO',
 'VZ',
 'TEL',
 'JKHY',
 'ADP',
 'TRMB',
 'QCOM',
 'MA',
 'NWSA',
 'TTWO',
 'AAPL',
 'TMUS',
 'NTAP',
 'KEYS',
 'CTSH',
 'MU',
 'CDW',
 'CRM',
 'LRCX']

In [10]:
tickers_df = map(ticker_convert,SP500_tickers_list)
SP500_master_df = []
for i in tickers_df:
    df = pd.DataFrame(i)
    SP500_master_df.append(df)
SP500_master_df = pd.concat(SP500_master_df)

In [11]:
today_date = datetime.now()
date = today_date.strftime('%m/%d/%Y %H:%M:%S')
SP500_master_df['Date'] = date
SP500_master_df.to_csv('SP500_master_df.csv')

In [12]:
SP500_master_df.columns

Index(['symbol', 'marketCap', 'enterpriseValue', 'currentPrice',
       'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'earningsGrowth',
       'enterpriseToRevenue', 'enterpriseToEbitda', 'forwardEps',
       'trailingEps', 'priceToSalesTrailing12Months', 'forwardPE',
       'dividendYield', 'Date'],
      dtype='object')

In [13]:
raw_df = pd.read_csv('SP500_master_df.csv')
raw_df.columns
raw_df = raw_df.drop('Unnamed: 0', 1)
raw_df = raw_df[['Date','symbol', 'marketCap', 'enterpriseValue', 'currentPrice',
       'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'earningsGrowth',
       'enterpriseToRevenue', 'enterpriseToEbitda', 'forwardEps',
       'trailingEps', 'priceToSalesTrailing12Months', 'forwardPE',
       'dividendYield']]
raw_df

<ipython-input-13-a98c53e3806d>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  raw_df = raw_df.drop('Unnamed: 0', 1)

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,05/25/2022 12:10:28,CSCO,1.823473e+11,171043045376,43.8950,64.290000,41.02000,0.076,3.316,10.649,3.55,2.850,3.535164,12.364789,0.0347
1,05/25/2022 12:10:28,TER,1.586170e+10,15577000960,99.0100,168.910000,97.63000,-0.156,4.237,11.822,6.61,5.384,4.314178,14.978820,0.0043
2,05/25/2022 12:10:28,V,4.307517e+11,432585572352,203.5506,252.670000,186.67000,0.234,16.059,22.745,8.37,6.358,15.991081,24.319069,0.0072
3,05/25/2022 12:10:28,QRVO,1.102893e+10,11983052800,104.0200,201.460000,98.23000,-0.247,2.579,7.214,12.73,9.260,2.374001,8.171249,NaN
4,05/25/2022 12:10:28,FOX,1.791648e+10,20857415680,30.7800,40.910000,28.96000,-0.479,1.508,7.187,2.35,1.999,1.295386,13.097873,0.0152
5,05/25/2022 12:10:28,FLT,1.809775e+10,23036299264,234.0000,282.020000,200.78000,0.279,7.642,14.959,17.71,10.594,6.003856,13.212874,NaN
6,05/25/2022 12:10:28,SWKS,1.614571e+10,18205990912,100.3300,197.620000,97.59000,-0.046,3.452,8.772,12.29,8.239,3.061784,8.163547,0.0217
7,05/25/2022 12:10:28,ENPH,2.241600e+10,22960513024,166.0100,282.460000,113.40000,0.703,15.090,88.561,4.23,1.174,14.731986,39.245860,NaN
8,05/25/2022 12:10:28,MCHP,3.747872e+10,44682285056,67.5900,90.000000,63.34000,2.712,6.551,14.783,5.73,2.270,5.494688,11.795811,0.0165
9,05/25/2022 12:10:28,CDNS,3.946387e+10,39639310336,143.1100,192.700000,122.04000,0.269,12.568,38.327,4.43,2.679,12.512396,32.304740,NaN
10,05/25/2022 12:10:28,CHTR,9.317474e+10,177359159296,486.5700,825.620000,410.33000,0.681,3.387,8.544,35.97,27.446,1.779502,13.527105,NaN
11,05/25/2022 12:10:28,T,1.456764e+11,343495737344,20.4000,22.583082,16.63142,-0.378,2.107,6.308,3.21,0.129,0.893556,6.355140,0.0559
12,05/25/2022 12:10:28,DISH,1.098851e+10,33020866560,20.7800,46.310000,17.04000,-0.308,1.847,8.407,2.77,4.159,0.614532,7.501805,NaN
13,05/25/2022 12:10:28,APH,4.092306e+10,46405705728,68.4300,88.450000,65.84000,0.283,4.053,17.165,2.67,2.380,3.573723,25.629213,0.0114
14,05/25/2022 12:10:28,MSI,3.551566e+10,40217600000,210.2800,273.650000,199.24000,-0.032,4.922,15.947,9.88,7.245,4.346550,21.283400,0.0147
15,05/25/2022 12:10:28,GPN,3.542744e+10,49546457088,122.1000,197.750000,114.80000,0.187,5.813,14.373,9.59,3.167,4.156315,12.732012,0.0082
16,05/25/2022 12:10:28,WBD,4.132909e+10,23824525312,17.0300,32.760000,16.51000,2.267,1.897,6.190,1.77,1.806,3.291056,9.621469,NaN
17,05/25/2022 12:10:28,DXC,7.466275e+09,10545514496,29.6000,44.180000,27.28000,-0.911,0.634,5.487,4.30,1.520,0.448640,6.883721,NaN
18,05/25/2022 12:10:28,PARA,NaN,32926785536,32.6400,47.460000,26.11000,1.326,1.152,7.499,NaN,NaN,NaN,NaN,0.0339
19,05/25/2022 12:10:28,ADI,8.533477e+10,85252562944,162.4400,191.950000,143.81000,-0.490,10.096,24.725,8.51,3.460,10.105821,19.088130,0.0192
20,05/25/2022 12:10:28,ADBE,1.898870e+11,192158105600,399.6000,699.540000,370.27000,0.019,11.904,29.468,16.10,10.068,11.763537,24.559385,NaN
21,05/25/2022 12:10:28,NOW,8.617297e+10,82314780672,438.6300,707.600000,406.47000,-0.098,13.154,115.287,9.33,1.090,13.770049,59.976456,NaN
22,05/25/2022 12:10:28,NWS,1.053846e+10,13919098880,17.8900,26.210000,16.57000,0.018,1.386,10.977,NaN,0.830,1.049021,NaN,0.0111
23,05/25/2022 12:10:28,ZBRA,1.738826e+10,20450457600,325.3700,615.000000,309.00000,-0.045,3.634,17.070,19.70,15.684,3.090148,16.516243,NaN
24,05/25/2022 12:10:28,BR,1.620201e+10,20994430976,138.9800,185.400000,132.68000,-0.167,3.907,18.797,7.04,4.655,3.014945,19.741476,0.0184
25,05/25/2022 12:10:28,STX,1.783760e+10,22073798656,80.1200,117.670000,76.28000,0.122,1.832,8.697,9.28,6.795,1.480790,8.633621,0.0347
26,05/25/2022 12:10:28,IPG,1.207647e+10,14458374144,30.6700,39.980000,27.67000,0.739,1.553,8.285,2.61,1.771,1.297512,11.750958,0.0361
27,05/25/2022 12:10:28,CDAY,8.565335e+09,9343748096,56.6000,130.370000,48.93000,NaN,9.123,841.779,0.45,-0.561,8.362951,125.777780,NaN
28,05/25/2022 12:10:28,ORCL,1.832730e+11,251351728128,68.6300,106.340000,66.72000,-0.500,6.009,13.661,5.26,3.543,4.381691,13.047527,0.0180
29,05/25/2022 12:10:28,INTU,1.041432e+11,124250726400,367.7800,716.860000,339.36000,4.000,10.886,39.697,13.64,7.581,9.124160,26.963343,0.0073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,05/25/2022 12:10:28,OMC,1.591004e+10,19207329792,74.8500,91.610000,65.76000,-0.376,1.346,8.254,6.41,6.420,1.114711,11.677067,0.0364
70,05/25/2022 12:10:28,AKAM,1.584343e+10,19784464384,97.5100,123.250000,93.74000,0.424,5.716,16.575,5.94,3.641,4.577407,16.415825,NaN
71,05/25/2022 12:10:28,GOOGL,1.445865e+12,1397453881344,2178.1600,3030.930000,2037.69000,-0.063,5.169,14.581,112.42,103.805,5.348439,19.375200,NaN
72,05/25/2022 12:10:28,ANET,3.154127e+10,32227203072,102.6400,148.570000,82.94000,0.284,10.932,33.051,3.44,2.463,10.699076,29.837208,NaN
73,05/25/2022 12:10:28,PAYX,4.232762e+10,45283831808,117.3300,141.920000,99.88000,0.227,10.071,22.757,3.87,3.520,9.413249,30.317831,0.0264
74,05/25/2022 12:10:28,FOXA,1.843459e+10,24571428864,33.4600,44.950000,31.35000,NaN,1.808,8.218,3.56,2.958,1.356382,9.398876,0.0143
75,05/25/2022 12:10:28,FFIV,9.568931e+09,9871137792,156.2800,249.000000,151.66000,0.314,3.718,18.315,13.18,5.340,3.604340,11.857359,NaN
76,05/25/2022 12:10:28,SNPS,4.706250e+10,43219197952,306.7200,377.600000,247.87000,0.932,9.595,37.855,9.02,4.810,10.448751,34.004433,NaN
77,05/25/2022 12:10:28,GOOG,1.451071e+12,1408740491264,2186.2600,3042.000000,2044.16000,-0.063,5.211,14.699,112.30,103.805,5.367697,19.468030,NaN
78,05/25/2022 12:10:28,EPAM,1.817239e+10,13873497088,320.3900,725.400000,168.59000,0.644,3.692,22.084,11.17,7.211,4.835470,28.683080,NaN
79,05/25/2022 12:10:28,LYV,2.005765e+10,26995554304,89.2800,127.750000,74.23000,NaN,4.307,-2834.476,0.82,-4.165,3.199779,108.878050,NaN
80,05/25/2022 12:10:28,AVGO,2.242690e+11,255658999808,543.1900,677.760000,455.53000,0.833,8.970,16.300,36.05,15.000,7.868813,15.067684,0.0279
81,05/25/2022 12:10:28,VZ,2.079150e+11,376384487424,49.5300,57.610000,45.55000,-0.139,2.803,8.344,5.40,5.320,1.548139,9.172222,0.0531
82,05/25/2022 12:10:28,TEL,4.003208e+10,43690319872,122.6800,166.440000,119.58000,0.130,2.821,11.941,7.91,6.788,2.584716,15.509482,0.0179
83,05/25/2022 12:10:28,JKHY,1.326222e+10,14073831424,179.1200,205.370000,147.50000,0.383,7.542,28.146,5.15,4.302,7.107240,34.780582,0.0112
84,05/25/2022 12:10:28,ADP,8.791756e+10,92940173312,208.6400,248.960000,192.18000,0.163,5.770,22.021,7.47,6.320,5.458141,27.930390,0.0199
85,05/25/2022 12:10:28,TRMB,1.637325e+10,17879977984,65.2300,96.490000,59.89000,-0.361,4.886,23.125,2.96,2.197,4.474667,22.037163,NaN
86,05/25/2022 12:10:28,QCOM,1.473920e+11,160586792960,131.6000,193.580000,122.17000,0.680,4.090,11.087,11.64,7.870,3.753871,11.305842,0.0222
87,05/25/2022 12:10:28,MA,3.303160e+11,360853635072,336.1800,399.920000,305.61000,0.464,18.137,30.555,10.53,8.130,16.602130,31.925926,0.0059
88,05/25/2022 12:10:28,NWSA,1.046078e+10,13889631232,17.6100,27.510000,16.38000,0.018,1.383,10.954,1.03,0.830,1.041288,17.097088,0.0112
89,05/25/2022 12:10:28,TTWO,1.338864e+10,10856370176,116.1200,195.830000,101.85000,-0.210,3.180,12.955,6.70,4.836,3.921425,17.331345,NaN
90,05/25/2022 12:10:28,AAPL,2.257357e+12,2623592988672,137.5900,182.940000,123.13000,0.086,6.797,20.084,6.18,5.610,5.847817,22.263754,0.0063
91,05/25/2022 12:10:28,TMUS,1.574303e+11,264606859264,126.0400,150.200000,101.51000,-0.230,3.288,10.002,3.24,2.660,1.956166,38.901234,NaN
92,05/25/2022 12:10:28,NTAP,1.481261e+10,15044795392,66.6400,96.820000,64.58000,0.375,2.429,11.038,5.51,4.113,2.391830,12.094374,0.0281
93,05/25/2022 12:10:28,KEYS,2.522319e+10,25562640384,137.8000,209.080000,127.93000,0.348,5.101,17.989,7.48,4.780,5.033564,18.422460,NaN
94,05/25/2022 12:10:28,CTSH,3.763474e+10,41370865664,70.8300,93.470000,66.19000,0.853,2.235,12.357,4.52,3.545,2.033541,15.670355,0.0147
95,05/25/2022 12:10:28,MU,7.717972e+10,73692512256,68.9000,98.450000,65.67000,2.774,2.364,4.318,11.51,6.461,2.476169,5.986099,0.0056
96,05/25/2022 12:10:28,CDW,2.174283e+10,29284814848,160.2000,208.710000,155.39000,-0.050,1.407,17.594,9.11,7.116,1.044284,17.585072,0.0118
97,05/25/2022 12:10:28,CRM,1.572552e+11,178013601792,159.6500,311.750000,154.55000,NaN,6.720,58.098,4.71,1.818,5.935952,33.895966,NaN
98,05/25/2022 12:10:28,LRCX,6.675562e+10,65261465600,474.1200,731.850000,442.53000,-0.015,3.899,11.775,36.65,29.588,3.988586,12.936425,0.0122

In [14]:
date_file =today_date.strftime('%m_%d_%Y')
raw_df.to_csv(f'SP500_master_df_{date_file}.csv')

In [15]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://{user}:{pw}@localhost/{db}'.format(user='root',
                                                                        pw='Boston1429$$',
                                                                        db='SP500'))
raw_df.to_sql(f'SP500_{date_file}', con=engine, if_exists='append', index=False)