In [22]:
import yfinance as yf
import pandas as pd

In [38]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 200)
pd.set_option('display.min_rows', 20)

In [39]:
amzn = yf.Ticker('AMZN')

In [40]:
# get stock info
amzn.info

{'zip': '98109-5210',
 'sector': 'Consumer Cyclical',
 'fullTimeEmployees': 1622000,
 'longBusinessSummary': 'Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). It sells merchandise and content purchased for resale from third-party sellers through physical and online stores. The company also manufactures and sells electronic devices, including Kindle, Fire tablets, Fire TVs, Rings, and Echo and other devices; provides Kindle Direct Publishing, an online service that allows independent authors and publishers to make their books available in the Kindle Store; and develops and produces media content. In addition, it offers programs that enable sellers to sell their products on its websites, as well as its stores; and programs that allow authors, musicians, filmmakers, Twitch streamers, skill and app developers, and others to publish and sell content. Further, the company provides compute, storage, database, analytics, machine learning, and other services, as well as fulfillment, advertising, publishing, and digital content subscriptions. Additionally, it offers Amazon Prime, a membership program, which provides free shipping of various items; access to streaming of movies and series; and other services. The company serves consumers, sellers, developers, enterprises, and content creators. Amazon.com, Inc. was incorporated in 1994 and is headquartered in Seattle, Washington.',
 'city': 'Seattle',
 'phone': '206 266 1000',
 'state': 'WA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'https://www.amazon.com',
 'maxAge': 1,
 'address1': '410 Terry Avenue North',
 'industry': 'Internet Retail',
 'ebitdaMargins': 0.11658,
 'profitMargins': 0.04482,
 'grossMargins': 0.42137,
 'operatingCashflow': 39324000256,
 'revenueGrowth': 0.073,
 'operatingMargins': 0.04172,
 'ebitda': 55698001920,
 'targetLowPrice': 2250,
 'recommendationKey': 'buy',
 'grossProfits': 197478000000,
 'freeCashflow': -9018749952,
 'targetMedianPrice': 3700,
 'currentPrice': 2151.82,
 'earningsGrowth': None,
 'currentRatio': 0.96,
 'returnOnAssets': 0.03395,
 'numberOfAnalystOpinions': 53,
 'targetMeanPrice': 3634.16,
 'debtToEquity': 109.9,
 'returnOnEquity': 0.18045999,
 'targetHighPrice': 4655,
 'totalCash': 66384998400,
 'totalDebt': 147266994176,
 'totalRevenue': 477748002816,
 'totalCashPerShare': 130.494,
 'financialCurrency': 'USD',
 'revenuePerShare': 941.839,
 'quickRatio': 0.707,
 'recommendationMean': 1.7,
 'exchange': 'NMS',
 'shortName': 'Amazon.com, Inc.',
 'longName': 'Amazon.com, Inc.',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'AMZN',
 'messageBoardId': 'finmb_18749',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 2.45,
 'beta3Year': None,
 'enterpriseToEbitda': 21.019,
 '52WeekChange': -0.32990122,
 'morningStarRiskRating': None,
 'forwardEps': 53.97,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 508720000,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'totalAssets': None,
 'bookValue': 263.501,
 'sharesShort': 3939111,
 'sharesPercentSharesOut': 0.0077,
 'fundFamily': None,
 'lastFiscalYearEnd': 1640908800,
 'heldPercentInstitutions': 0.60493,
 'netIncomeToCommon': 21412999168,
 'trailingEps': 41.69,
 'lastDividendValue': None,
 'SandP52WeekChange': -0.061375976,
 'priceToBook': 8.166269,
 'heldPercentInsiders': 0.09872,
 'nextFiscalYearEnd': 1703980800,
 'yield': None,
 'mostRecentQuarter': 1648684800,
 'shortRatio': 1.1,
 'sharesShortPreviousMonthDate': 1648684800,
 'floatShares': 457955264,
 'beta': 1.231696,
 'enterpriseValue': 1170688442368,
 'priceHint': 2,
 'threeYearAverageReturn': None,
 'lastSplitDate': 936230400,
 'lastSplitFactor': '2:1',
 'legalType': None,
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': None,
 'priceToSalesTrailing12Months': 2.2913208,
 'dateShortInterest': 1651190400,
 'pegRatio': 3.31,
 'ytdReturn': None,
 'forwardPE': 39.87067,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0089,
 'sharesShortPriorMonth': 3647235,
 'impliedSharesOutstanding': 0,
 'category': None,
 'fiveYearAverageReturn': None,
 'previousClose': 2146.38,
 'regularMarketOpen': 2191.37,
 'twoHundredDayAverage': 3188.913,
 'trailingAnnualDividendYield': 0,
 'payoutRatio': 0,
 'volume24Hr': None,
 'regularMarketDayHigh': 2197.41,
 'navPrice': None,
 'averageDailyVolume10Day': 5202040,
 'regularMarketPreviousClose': 2146.38,
 'fiftyDayAverage': 2861.8489,
 'trailingAnnualDividendRate': 0,
 'open': 2191.37,
 'toCurrency': None,
 'averageVolume10days': 5202040,
 'expireDate': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 2100.2,
 'currency': 'USD',
 'trailingPE': 51.61478,
 'regularMarketVolume': 4944753,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 1094673891328,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 4006345,
 'dayLow': 2100.2,
 'ask': 2158.01,
 'askSize': 1200,
 'volume': 4944753,
 'fiftyTwoWeekHigh': 3773.08,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 2048.11,
 'bid': 2151.91,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': 800,
 'dayHigh': 2197.41,
 'regularMarketPrice': 2151.82,
 'logo_url': 'https://logo.clearbit.com/amazon.com'}

In [41]:
# get historical market data
hist = amzn.history(period='max')
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1997-05-15,2.437500,2.500000,1.927083,1.958333,72156000,0,0.0
1997-05-16,1.968750,1.979167,1.708333,1.729167,14700000,0,0.0
1997-05-19,1.760417,1.770833,1.625000,1.708333,6106800,0,0.0
1997-05-20,1.729167,1.750000,1.635417,1.635417,5467200,0,0.0
1997-05-21,1.635417,1.645833,1.375000,1.427083,18853200,0,0.0
1997-05-22,1.437500,1.447917,1.312500,1.395833,11776800,0,0.0
1997-05-23,1.406250,1.520833,1.333333,1.500000,15937200,0,0.0
1997-05-27,1.510417,1.645833,1.458333,1.583333,8697600,0,0.0
1997-05-28,1.625000,1.635417,1.531250,1.531250,4574400,0,0.0
1997-05-29,1.541667,1.541667,1.479167,1.505208,3472800,0,0.0
1997-05-30,1.500000,1.510417,1.479167,1.500000,2594400,0,0.0
1997-06-02,1.510417,1.531250,1.500000,1.510417,591600,0,0.0
1997-06-03,1.531250,1.531250,1.479167,1.479167,1183200,0,0.0
1997-06-04,1.479167,1.489583,1.395833,1.416667,3080400,0,0.0
1997-06-05,1.416667,1.541667,1.375000,1.541667,5672400,0,0.0
1997-06-06,1.515625,1.708333,1.510417,1.656250,7807200,0,0.0
1997-06-09,1.656250,1.708333,1.656250,1.687500,2352000,0,0.0
1997-06-10,1.708333,1.708333,1.531250,1.583333,5458800,0,0.0
1997-06-11,1.593750,1.604167,1.531250,1.541667,1188000,0,0.0
1997-06-12,1.583333,1.645833,1.552083,1.604167,1632000,0,0.0
1997-06-13,1.625000,1.625000,1.583333,1.583333,693600,0,0.0
1997-06-16,1.604167,1.604167,1.562500,1.572917,913200,0,0.0
1997-06-17,1.598958,1.598958,1.494792,1.505208,4706400,0,0.0
1997-06-18,1.520833,1.536458,1.500000,1.510417,2464800,0,0.0
1997-06-19,1.510417,1.531250,1.500000,1.510417,1003200,0,0.0
1997-06-20,1.531250,1.552083,1.500000,1.526042,3387600,0,0.0
1997-06-23,1.541667,1.541667,1.479167,1.500000,1047600,0,0.0
1997-06-24,1.505208,1.526042,1.479167,1.510417,751200,0,0.0
1997-06-25,1.526042,1.526042,1.489583,1.510417,2106000,0,0.0
1997-06-26,1.520833,1.520833,1.505208,1.510417,3189600,0,0.0
1997-06-27,1.515625,1.515625,1.479167,1.489583,1188000,0,0.0
1997-06-30,1.510417,1.598958,1.479167,1.541667,2746800,0,0.0
1997-07-01,1.541667,1.541667,1.510417,1.515625,1292400,0,0.0
1997-07-02,1.515625,1.593750,1.510417,1.588542,3882000,0,0.0
1997-07-03,1.598958,1.916667,1.593750,1.911458,12577200,0,0.0
1997-07-07,1.833333,2.020833,1.833333,2.000000,8053200,0,0.0
1997-07-08,2.041667,2.333333,2.041667,2.302083,15517200,0,0.0
1997-07-09,2.302083,2.385417,2.270833,2.322917,8262000,0,0.0
1997-07-10,2.333333,2.572917,2.333333,2.562500,9051600,0,0.0
1997-07-11,2.520833,2.520833,2.208333,2.291667,10531200,0,0.0
1997-07-14,2.322917,2.333333,2.114583,2.135417,4604400,0,0.0
1997-07-15,2.135417,2.479167,2.135417,2.437500,9274800,0,0.0
1997-07-16,2.447917,2.494792,2.302083,2.333333,3024000,0,0.0
1997-07-17,2.343750,2.343750,2.156250,2.218750,3169200,0,0.0
1997-07-18,2.187500,2.218750,2.156250,2.156250,780000,0,0.0
1997-07-21,2.177083,2.197917,2.145833,2.182292,574800,0,0.0
1997-07-22,2.166667,2.187500,2.062500,2.135417,1563600,0,0.0
1997-07-23,2.187500,2.333333,2.177083,2.291667,3259200,0,0.0
1997-07-24,2.302083,2.312500,2.218750,2.260417,1216800,0,0.0
1997-07-25,2.218750,2.250000,2.218750,2.229167,620400,0,0.0
1997-07-28,2.229167,2.395833,2.218750,2.322917,2574000,0,0.0
1997-07-29,2.364583,2.500000,2.333333,2.479167,4814400,0,0.0
1997-07-30,2.500000,2.505208,2.427083,2.447917,2517600,0,0.0
1997-07-31,2.437500,2.437500,2.333333,2.395833,1454400,0,0.0
1997-08-01,2.343750,2.416667,2.250000,2.416667,3588000,0,0.0
1997-08-04,2.375000,2.411458,2.302083,2.312500,2671200,0,0.0
1997-08-05,2.333333,2.333333,2.145833,2.208333,3032400,0,0.0
1997-08-06,2.208333,2.312500,2.187500,2.250000,1243200,0,0.0
1997-08-07,2.250000,2.260417,2.125000,2.177083,2034000,0,0.0
1997-08-08,2.166667,2.302083,2.104167,2.291667,2211600,0,0.0
1997-08-11,2.291667,2.333333,2.250000,2.328125,1239600,0,0.0
1997-08-12,2.281250,2.302083,2.197917,2.197917,571200,0,0.0
1997-08-13,2.229167,2.229167,2.166667,2.197917,590400,0,0.0
1997-08-14,2.177083,2.250000,2.119792,2.156250,1041600,0,0.0
1997-08-15,2.135417,2.156250,1.937500,2.114583,1597200,0,0.0
1997-08-18,2.052083,2.052083,1.968750,2.041667,1784400,0,0.0
1997-08-19,2.093750,2.208333,2.052083,2.166667,1003200,0,0.0
1997-08-20,2.187500,2.187500,2.072917,2.166667,999600,0,0.0
1997-08-21,2.135417,2.171875,2.072917,2.114583,624000,0,0.0
1997-08-22,2.104167,2.125000,2.093750,2.125000,712800,0,0.0
1997-08-25,2.104167,2.260417,2.104167,2.218750,1126800,0,0.0
1997-08-26,2.239583,2.354167,2.229167,2.343750,2574000,0,0.0
1997-08-27,2.307292,2.322917,2.250000,2.317708,1392000,0,0.0
1997-08-28,2.302083,2.395833,2.281250,2.375000,1147200,0,0.0
1997-08-29,2.364583,2.375000,2.322917,2.338542,722400,0,0.0
1997-09-02,2.343750,2.375000,2.333333,2.354167,732000,0,0.0
1997-09-03,2.343750,2.416667,2.312500,2.333333,1964400,0,0.0
1997-09-04,2.364583,2.552083,2.343750,2.552083,3348000,0,0.0
1997-09-05,2.583333,2.666667,2.458333,2.500000,1908000,0,0.0
1997-09-08,2.531250,3.020833,2.500000,3.000000,5648400,0,0.0
1997-09-09,3.140625,3.385417,3.026042,3.239583,8971200,0,0.0
1997-09-10,3.312500,3.328125,3.125000,3.302083,3866400,0,0.0
1997-09-11,3.333333,3.333333,3.041667,3.156250,4262400,0,0.0
1997-09-12,3.187500,3.697917,3.156250,3.687500,3333600,0,0.0
1997-09-15,3.666667,3.677083,3.052083,3.093750,5583600,0,0.0
1997-09-16,3.125000,3.541667,3.119792,3.354167,6432000,0,0.0
1997-09-17,3.458333,3.500000,3.333333,3.406250,2607600,0,0.0
1997-09-18,3.437500,3.468750,3.281250,3.291667,2128800,0,0.0
1997-09-19,3.380208,4.083333,3.375000,3.947917,8929200,0,0.0
1997-09-22,4.000000,4.677083,3.947917,4.500000,16938000,0,0.0
1997-09-23,4.489583,4.645833,4.395833,4.625000,7682400,0,0.0
1997-09-24,4.645833,4.812500,4.291667,4.375000,8200800,0,0.0
1997-09-25,4.343750,4.354167,4.052083,4.078125,4968000,0,0.0
1997-09-26,4.072917,4.260417,4.052083,4.166667,2731200,0,0.0
1997-09-29,4.145833,4.187500,3.958333,4.041667,2371200,0,0.0
1997-09-30,4.000000,4.348958,3.802083,4.338542,5254800,0,0.0
1997-10-01,4.437500,4.500000,3.937500,4.020833,4999200,0,0.0
1997-10-02,4.041667,4.177083,3.989583,4.010417,1876800,0,0.0
1997-10-03,4.083333,4.125000,3.979167,4.015625,1164000,0,0.0
1997-10-06,4.000000,4.125000,3.942708,4.125000,2028000,0,0.0
...,...,...,...,...,...,...,...
2021-12-29,3416.800049,3424.239990,3372.010010,3384.020020,1787700,0,0.0
2021-12-30,3394.000000,3417.760010,3370.479980,3372.889893,1879200,0,0.0
2021-12-31,3379.120117,3387.000000,3331.169922,3334.340088,2391500,0,0.0
2022-01-03,3351.000000,3414.070068,3323.209961,3408.090088,3176000,0,0.0
2022-01-04,3408.760010,3428.000000,3326.989990,3350.439941,3536300,0,0.0
2022-01-05,3337.659912,3342.530029,3287.139893,3287.139893,3215100,0,0.0
2022-01-06,3269.010010,3296.000000,3238.739990,3265.080078,2597900,0,0.0
2022-01-07,3276.780029,3304.870117,3240.620117,3251.080078,2330300,0,0.0
2022-01-10,3211.709961,3233.229980,3126.090088,3229.719971,4389900,0,0.0
2022-01-11,3230.000000,3327.000000,3214.030029,3307.239990,3140300,0,0.0
2022-01-12,3331.500000,3337.560059,3288.340088,3304.139893,2501500,0,0.0
2022-01-13,3305.010010,3324.429932,3221.820068,3224.280029,2609400,0,0.0
2022-01-14,3203.000000,3245.000000,3196.010010,3242.760010,2298700,0,0.0
2022-01-18,3182.100098,3194.689941,3153.290039,3178.350098,3364600,0,0.0
2022-01-19,3175.239990,3185.000000,3125.000000,3125.979980,2662100,0,0.0
2022-01-20,3135.320068,3160.000000,3027.020020,3033.350098,3598700,0,0.0
2022-01-21,2999.000000,3018.000000,2841.409912,2852.860107,8198600,0,0.0
2022-01-24,2780.000000,2898.899902,2707.040039,2890.879883,7781200,0,0.0
2022-01-25,2844.850098,2872.000000,2762.899902,2799.719971,4541200,0,0.0
2022-01-26,2895.000000,2903.699951,2746.370117,2777.449951,4780100,0,0.0
2022-01-27,2816.000000,2884.870117,2787.000000,2792.750000,3875800,0,0.0
2022-01-28,2817.209961,2879.959961,2758.590088,2879.560059,3719600,0,0.0
2022-01-31,2895.000000,3007.209961,2886.010010,2991.469971,3915400,0,0.0
2022-02-01,3000.000000,3034.159912,2952.550049,3023.870117,2961000,0,0.0
2022-02-02,3101.010010,3101.500000,2977.270020,3012.250000,4366500,0,0.0
2022-02-03,2834.750000,2884.949951,2766.659912,2776.909912,11276600,0,0.0
2022-02-04,3112.129883,3224.000000,3012.159912,3152.790039,12672800,0,0.0
2022-02-07,3170.399902,3253.820068,3145.000000,3158.709961,5131200,0,0.0
2022-02-08,3135.010010,3235.850098,3111.010010,3228.270020,3802000,0,0.0
2022-02-09,3257.469971,3276.689941,3205.000000,3223.790039,3439300,0,0.0
2022-02-10,3167.000000,3214.330078,3155.000000,3180.070068,3413400,0,0.0
2022-02-11,3162.689941,3180.000000,3054.679932,3065.870117,3855000,0,0.0
2022-02-14,3035.020020,3168.969971,3033.000000,3103.340088,4161500,0,0.0
2022-02-15,3152.110107,3160.139893,3092.750000,3130.209961,2822000,0,0.0
2022-02-16,3115.810059,3176.679932,3094.689941,3162.010010,2635200,0,0.0
2022-02-17,3162.919922,3206.979980,3090.000000,3093.050049,3201600,0,0.0
2022-02-18,3109.989990,3109.989990,3017.860107,3052.030029,3180200,0,0.0
2022-02-22,3009.570068,3059.649902,2969.709961,3003.949951,3306400,0,0.0
2022-02-23,3033.010010,3035.260010,2893.020020,2896.540039,3212200,0,0.0
2022-02-24,2796.750000,3034.979980,2790.000000,3027.159912,5039300,0,0.0
2022-02-25,3011.000000,3079.800049,2984.270020,3075.770020,3119800,0,0.0
2022-02-28,3048.500000,3089.000000,3017.000000,3071.260010,2884200,0,0.0
2022-03-01,3054.649902,3081.979980,2999.540039,3022.840088,2243700,0,0.0
2022-03-02,3016.979980,3059.989990,2975.000000,3041.050049,2366700,0,0.0
2022-03-03,3070.629883,3078.580078,2937.120117,2957.969971,3259900,0,0.0
2022-03-04,2943.179932,2957.000000,2876.139893,2912.820068,3046700,0,0.0
2022-03-07,2908.870117,2921.889893,2748.330078,2749.060059,4346700,0,0.0
2022-03-08,2733.669922,2813.989990,2671.449951,2720.290039,4583100,0,0.0
2022-03-09,2790.000000,2805.000000,2736.560059,2785.580078,4132800,0,0.0
2022-03-10,2913.699951,2973.489990,2879.560059,2936.350098,6753100,0,0.0
2022-03-11,2991.489990,2993.500000,2907.379883,2910.489990,3445000,0,0.0
2022-03-14,2919.620117,2949.000000,2817.679932,2837.060059,3704300,0,0.0
2022-03-15,2857.000000,2959.699951,2840.000000,2947.330078,3779200,0,0.0
2022-03-16,2970.000000,3063.000000,2947.070068,3062.080078,4247900,0,0.0
2022-03-17,3052.810059,3149.969971,3042.800049,3144.780029,3646700,0,0.0
2022-03-18,3136.260010,3231.879883,3120.219971,3225.010010,5148100,0,0.0
2022-03-21,3222.419922,3261.679932,3191.060059,3229.830078,3326900,0,0.0
2022-03-22,3236.110107,3323.340088,3233.979980,3297.780029,3204300,0,0.0
2022-03-23,3274.100098,3327.399902,3253.739990,3268.159912,2790600,0,0.0
2022-03-24,3274.989990,3282.370117,3201.000000,3272.989990,2839900,0,0.0
2022-03-25,3280.000000,3307.370117,3245.000000,3295.469971,2451600,0,0.0
2022-03-28,3299.500000,3380.750000,3298.000000,3379.810059,2992700,0,0.0
2022-03-29,3407.679932,3416.629883,3357.370117,3386.300049,3307700,0,0.0
2022-03-30,3370.189941,3379.010010,3310.000000,3326.020020,2808400,0,0.0
2022-03-31,3328.899902,3329.899902,3259.070068,3259.949951,2998300,0,0.0
2022-04-01,3282.989990,3316.540039,3246.389893,3271.199951,2854500,0,0.0
2022-04-04,3282.500000,3367.889893,3264.110107,3366.929932,2494100,0,0.0
2022-04-05,3354.830078,3362.209961,3265.320068,3281.100098,2686400,0,0.0
2022-04-06,3233.010010,3244.000000,3145.090088,3175.120117,3952800,0,0.0
2022-04-07,3168.000000,3201.580078,3090.229980,3155.689941,3406800,0,0.0
2022-04-08,3135.000000,3147.370117,3084.620117,3089.209961,2300100,0,0.0
2022-04-11,3054.260010,3082.729980,3010.689941,3022.439941,2605600,0,0.0
2022-04-12,3073.850098,3101.979980,3007.659912,3015.750000,2758900,0,0.0
2022-04-13,3000.370117,3120.500000,2992.000000,3110.820068,2669500,0,0.0
2022-04-14,3107.800049,3117.939941,3029.439941,3034.129883,2579900,0,0.0
2022-04-18,3030.469971,3080.790039,3005.010010,3055.699951,2325700,0,0.0
2022-04-19,3040.590088,3172.979980,3031.010010,3162.310059,2746300,0,0.0
2022-04-20,3152.050049,3152.050049,3072.070068,3079.959961,2981500,0,0.0
2022-04-21,3094.280029,3134.760010,2951.790039,2965.919922,3198500,0,0.0
2022-04-22,2965.000000,2992.300049,2873.949951,2887.000000,3653900,0,0.0
2022-04-25,2880.459961,2924.429932,2846.129883,2921.479980,3093700,0,0.0
2022-04-26,2896.000000,2897.120117,2778.590088,2787.820068,3876500,0,0.0
2022-04-27,2803.830078,2838.969971,2715.669922,2763.340088,3566800,0,0.0
2022-04-28,2843.560059,2918.750000,2806.000000,2891.929932,5865800,0,0.0
2022-04-29,2596.979980,2615.219971,2432.500000,2485.629883,13616500,0,0.0
2022-05-02,2448.020020,2493.360107,2367.500000,2490.000000,7439400,0,0.0
2022-05-03,2481.070068,2524.409912,2456.500000,2485.070068,3956700,0,0.0
2022-05-04,2472.000000,2520.000000,2383.659912,2518.570068,5537300,0,0.0
2022-05-05,2460.000000,2469.979980,2301.449951,2328.139893,7219600,0,0.0
2022-05-06,2297.000000,2381.010010,2261.629883,2295.449951,6206700,0,0.0
2022-05-09,2226.250000,2280.000000,2159.139893,2175.780029,6406200,0,0.0
2022-05-10,2225.000000,2252.850098,2143.419922,2177.179932,5271700,0,0.0
2022-05-11,2162.070068,2203.120117,2088.570068,2107.439941,5485200,0,0.0
2022-05-12,2055.000000,2215.610107,2048.110107,2138.610107,6601300,0,0.0
2022-05-13,2181.379883,2263.679932,2156.000000,2261.100098,4676700,0,0.0
2022-05-16,2262.000000,2279.850098,2207.080078,2216.209961,3728300,0,0.0
2022-05-17,2265.500000,2316.000000,2225.530029,2307.370117,3822400,0,0.0
2022-05-18,2228.790039,2257.060059,2124.979980,2142.250000,5419000,0,0.0
2022-05-19,2125.610107,2200.679932,2123.860107,2146.379883,4407100,0,0.0
2022-05-20,2191.370117,2197.409912,2100.199951,2151.820068,4944753,0,0.0

In [42]:
# shoe financials
amzn.financials

,2021-12-31 00:00:00,2020-12-31 00:00:00,2019-12-31 00:00:00,2018-12-31 00:00:00
Research Development,56052000000.0,42740000000.0,35931000000.0,28837000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,38155000000.0,24194000000.0,13962000000.0,11270000000.0
Minority Interest,None,None,None,None
Net Income,33364000000.0,21331000000.0,11588000000.0,10073000000.0
Selling General Administrative,116485000000.0,87193000000.0,64313000000.0,52177000000.0
Gross Profit,197478000000.0,152757000000.0,114986000000.0,93731000000.0
Ebit,24879000000.0,22899000000.0,14541000000.0,12421000000.0
Operating Income,24879000000.0,22899000000.0,14541000000.0,12421000000.0
Other Operating Expenses,62000000.0,-75000000.0,201000000.0,296000000.0
Interest Expense,-1809000000.0,-1647000000.0,-1600000000.0,-1417000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,4791000000.0,2863000000.0,2374000000.0,1197000000.0
Total Revenue,469822000000.0,386064000000.0,280522000000.0,232887000000.0
Total Operating Expenses,444943000000.0,363165000000.0,265981000000.0,220466000000.0
Cost Of Revenue,272344000000.0,233307000000.0,165536000000.0,139156000000.0
Total Other Income Expense Net,13276000000.0,1295000000.0,-579000000.0,-1151000000.0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,33364000000.0,21331000000.0,11588000000.0,10073000000.0
Net Income Applicable To Common Shares,33364000000.0,21331000000.0,11588000000.0,10073000000.0

In [43]:
amzn.quarterly_financials

,2022-03-31 00:00:00,2021-12-31 00:00:00,2021-09-30 00:00:00,2021-06-30 00:00:00
Research Development,12270000000.0,21577000000.0,12097000000.0,11794000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,-5266000000.0,14935000000.0,4311000000.0,8646000000.0
Minority Interest,None,None,None,None
Net Income,-3844000000.0,14323000000.0,3156000000.0,7778000000.0
Selling General Administrative,33757000000.0,29516000000.0,30944000000.0,29397000000.0
Gross Profit,49945000000.0,54577000000.0,47882000000.0,48904000000.0
Ebit,3918000000.0,3460000000.0,4852000000.0,7702000000.0
Operating Income,3918000000.0,3460000000.0,4852000000.0,7702000000.0
Other Operating Expenses,NaN,24000000.0,-11000000.0,11000000.0
Interest Expense,-472000000.0,-482000000.0,-493000000.0,-435000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,-1422000000.0,612000000.0,1155000000.0,868000000.0
Total Revenue,116444000000.0,137412000000.0,110812000000.0,113080000000.0
Total Operating Expenses,112526000000.0,133952000000.0,105960000000.0,105378000000.0
Cost Of Revenue,66499000000.0,82835000000.0,62930000000.0,64176000000.0
Total Other Income Expense Net,-9184000000.0,11475000000.0,-541000000.0,944000000.0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,-3844000000.0,14323000000.0,3156000000.0,7778000000.0
Net Income Applicable To Common Shares,-3844000000.0,14323000000.0,3156000000.0,7778000000.0

In [44]:
# major holders
amzn.major_holders

        0                                      1
0   9.87%        % of Shares Held by All Insider
1  60.49%       % of Shares Held by Institutions
2  67.12%        % of Float Held by Institutions
3    5356  Number of Institutions Holding Shares

In [45]:
# show institutional holders
amzn.institutional_holders

,Holder,Shares,Date Reported,% Out,Value
0,"Vanguard Group, Inc. (The)",33965498,2022-03-30,0.0668,110725825205
1,Blackrock Inc.,29143882,2022-03-30,0.0573,95007598125
2,"J.W. Cole Advisors, Inc.",18109019,2022-03-30,0.0356,59034496489
3,State Street Corporation,16593001,2022-03-30,0.0326,54092353609
4,Price (T.Rowe) Associates Inc,16091344,2022-03-30,0.0316,52456976872
5,"FMR, LLC",15115716,2022-03-30,0.0297,49276478374
6,"Geode Capital Management, LLC",7410941,2022-03-30,0.0146,24159297112
7,Capital Research Global Investors,5213777,2022-03-30,0.0102,16996652331
8,Northern Trust Corporation,4829580,2022-03-30,0.0095,15744189321
9,JP Morgan Chase & Company,4537438,2022-03-30,0.0089,14791821008

In [46]:
# show earnings
amzn.earnings

           Revenue     Earnings
Year
2018  232887000000  10073000000
2019  280522000000  11588000000
2020  386064000000  21331000000
2021  469822000000  33364000000

In [47]:
amzn.quarterly_earnings

              Revenue     Earnings
Quarter
2Q2021   113080000000   7778000000
3Q2021   110812000000   3156000000
4Q2021   137412000000  14323000000
1Q2022   116444000000  -3844000000

In [48]:
# show analyst recommendations
amzn.recommendations

                                   Firm      To Grade From Grade Action
Date
2011-12-29 12:47:00        PiperJaffray                            main
2012-02-15 07:33:00        PiperJaffray    Overweight              main
2012-02-16 06:17:00      Morgan Stanley  Equal-Weight              down
2012-04-02 06:06:00        Bank oferica       Neutral              down
2012-04-27 06:21:00        Bank oferica           Buy                up
2012-04-27 07:20:00           Benchmark           Buy              main
2012-04-27 08:09:00   Canaccord Genuity          Hold              main
2012-04-27 08:18:00       Deutsche Bank           Buy              main
2012-04-27 08:38:00           JP Morgan    Overweight              main
2012-04-27 08:41:00     Stifel Nicolaus           Buy              main
...                                 ...           ...        ...    ...
2022-04-29 11:37:58           JP Morgan    Overweight              main
2022-04-29 11:43:12         Susquehanna      Positive              main
2022-04-29 11:46:15      Morgan Stanley    Overweight              main
2022-04-29 11:54:32   Canaccord Genuity           Buy              main
2022-04-29 12:58:22              Stifel           Buy              main
2022-04-29 13:00:50         Cowen & Co.    Outperform              main
2022-04-29 13:04:54         BMO Capital    Outperform              main
2022-04-29 13:08:40  Evercore ISI Group    Outperform              main
2022-04-29 13:11:43   Truist Securities           Buy              main
2022-04-29 13:36:58        MKM Partners           Buy              main

[498 rows x 4 columns]

In [49]:
# show next event
amzn.calendar

                                    0                    1
Earnings Date     2022-07-27 10:59:00  2022-08-01 12:00:00
Earnings Average                 3.12                 3.12
Earnings Low                     -0.6                 -0.6
Earnings High                    8.13                 8.13
Revenue Average          119643000000         119643000000
Revenue Low              116000000000         116000000000
Revenue High             121513000000         121513000000

In [50]:
# show news
amzn.news

AttributeError: 'Ticker' object has no attribute 'news'

In [52]:
type(amzn.info)

dict

In [53]:
amzn_info = pd.DataFrame([amzn.info])
amzn_info

,zip,sector,fullTimeEmployees,longBusinessSummary,city,phone,state,country,companyOfficers,website,maxAge,address1,industry,ebitdaMargins,profitMargins,grossMargins,operatingCashflow,revenueGrowth,operatingMargins,ebitda,targetLowPrice,recommendationKey,grossProfits,freeCashflow,targetMedianPrice,currentPrice,earningsGrowth,currentRatio,returnOnAssets,numberOfAnalystOpinions,targetMeanPrice,debtToEquity,returnOnEquity,targetHighPrice,totalCash,totalDebt,totalRevenue,totalCashPerShare,financialCurrency,revenuePerShare,quickRatio,recommendationMean,exchange,shortName,longName,exchangeTimezoneName,exchangeTimezoneShortName,isEsgPopulated,gmtOffSetMilliseconds,quoteType,...,impliedSharesOutstanding,category,fiveYearAverageReturn,previousClose,regularMarketOpen,twoHundredDayAverage,trailingAnnualDividendYield,payoutRatio,volume24Hr,regularMarketDayHigh,navPrice,averageDailyVolume10Day,regularMarketPreviousClose,fiftyDayAverage,trailingAnnualDividendRate,open,toCurrency,averageVolume10days,expireDate,algorithm,dividendRate,exDividendDate,circulatingSupply,startDate,regularMarketDayLow,currency,trailingPE,regularMarketVolume,lastMarket,maxSupply,openInterest,marketCap,volumeAllCurrencies,strikePrice,averageVolume,dayLow,ask,askSize,volume,fiftyTwoWeekHigh,fromCurrency,fiveYearAvgDividendYield,fiftyTwoWeekLow,bid,tradeable,dividendYield,bidSize,dayHigh,regularMarketPrice,logo_url
0,98109-5210,Consumer Cyclical,1622000,"Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). It sells merchandise and content purchased for resale from third-party sellers through physical and online stores. The company also manufactures and sells electronic devices, including Kindle, Fire tablets, Fire TVs, Rings, and Echo and other devices; provides Kindle Direct Publishing, an online service that allows independent authors and publishers to make their books available in the Kindle Store; and develops and produces media content. In addition, it offers programs that enable sellers to sell their products on its websites, as well as its stores; and programs that allow authors, musicians, filmmakers, Twitch streamers, skill and app developers, and others to publish and sell content. Further, the company provides compute, storage, database, analytics, machine learning, and other services, as well as fulfillment, advertising, publishing, and digital content subscriptions. Additionally, it offers Amazon Prime, a membership program, which provides free shipping of various items; access to streaming of movies and series; and other services. The company serves consumers, sellers, developers, enterprises, and content creators. Amazon.com, Inc. was incorporated in 1994 and is headquartered in Seattle, Washington.",Seattle,206 266 1000,WA,United States,[],https://www.amazon.com,1,410 Terry Avenue North,Internet Retail,0.11658,0.04482,0.42137,39324000256,0.073,0.04172,55698001920,2250,buy,197478000000,-9018749952,3700,2151.82,None,0.96,0.03395,53,3634.16,109.9,0.18046,4655,66384998400,147266994176,477748002816,130.494,USD,941.839,0.707,1.7,NMS,"Amazon.com, Inc.","Amazon.com, Inc.",America/New_York,EDT,False,-14400000,EQUITY,...,0,None,None,2146.38,2191.37,3188.913,0,0,None,2197.41,None,5202040,2146.38,2861.8489,0,2191.37,None,5202040,None,None,None,None,None,None,2100.2,USD,51.61478,4944753,None,None,None,1094673891328,None,None,4006345,2100.2,2158.01,1200,4944753,3773.08,None,None,2048.11,2151.91,False,None,800,2197.41,2151.82,https://logo.clearbit.com/amazon.com

In [57]:
amzn_info.columns.to_list()

['zip',
 'sector',
 'fullTimeEmployees',
 'longBusinessSummary',
 'city',
 'phone',
 'state',
 'country',
 'companyOfficers',
 'website',
 'maxAge',
 'address1',
 'industry',
 'ebitdaMargins',
 'profitMargins',
 'grossMargins',
 'operatingCashflow',
 'revenueGrowth',
 'operatingMargins',
 'ebitda',
 'targetLowPrice',
 'recommendationKey',
 'grossProfits',
 'freeCashflow',
 'targetMedianPrice',
 'currentPrice',
 'earningsGrowth',
 'currentRatio',
 'returnOnAssets',
 'numberOfAnalystOpinions',
 'targetMeanPrice',
 'debtToEquity',
 'returnOnEquity',
 'targetHighPrice',
 'totalCash',
 'totalDebt',
 'totalRevenue',
 'totalCashPerShare',
 'financialCurrency',
 'revenuePerShare',
 'quickRatio',
 'recommendationMean',
 'exchange',
 'shortName',
 'longName',
 'exchangeTimezoneName',
 'exchangeTimezoneShortName',
 'isEsgPopulated',
 'gmtOffSetMilliseconds',
 'quoteType',
 'symbol',
 'messageBoardId',
 'market',
 'annualHoldingsTurnover',
 'enterpriseToRevenue',
 'beta3Year',
 'enterpriseToEbitda',
 '52WeekChange',
 'morningStarRiskRating',
 'forwardEps',
 'revenueQuarterlyGrowth',
 'sharesOutstanding',
 'fundInceptionDate',
 'annualReportExpenseRatio',
 'totalAssets',
 'bookValue',
 'sharesShort',
 'sharesPercentSharesOut',
 'fundFamily',
 'lastFiscalYearEnd',
 'heldPercentInstitutions',
 'netIncomeToCommon',
 'trailingEps',
 'lastDividendValue',
 'SandP52WeekChange',
 'priceToBook',
 'heldPercentInsiders',
 'nextFiscalYearEnd',
 'yield',
 'mostRecentQuarter',
 'shortRatio',
 'sharesShortPreviousMonthDate',
 'floatShares',
 'beta',
 'enterpriseValue',
 'priceHint',
 'threeYearAverageReturn',
 'lastSplitDate',
 'lastSplitFactor',
 'legalType',
 'lastDividendDate',
 'morningStarOverallRating',
 'earningsQuarterlyGrowth',
 'priceToSalesTrailing12Months',
 'dateShortInterest',
 'pegRatio',
 'ytdReturn',
 'forwardPE',
 'lastCapGain',
 'shortPercentOfFloat',
 'sharesShortPriorMonth',
 'impliedSharesOutstanding',
 'category',
 'fiveYearAverageReturn',
 'previousClose',
 'regularMarketOpen',
 'twoHundredDayAverage',
 'trailingAnnualDividendYield',
 'payoutRatio',
 'volume24Hr',
 'regularMarketDayHigh',
 'navPrice',
 'averageDailyVolume10Day',
 'regularMarketPreviousClose',
 'fiftyDayAverage',
 'trailingAnnualDividendRate',
 'open',
 'toCurrency',
 'averageVolume10days',
 'expireDate',
 'algorithm',
 'dividendRate',
 'exDividendDate',
 'circulatingSupply',
 'startDate',
 'regularMarketDayLow',
 'currency',
 'trailingPE',
 'regularMarketVolume',
 'lastMarket',
 'maxSupply',
 'openInterest',
 'marketCap',
 'volumeAllCurrencies',
 'strikePrice',
 'averageVolume',
 'dayLow',
 'ask',
 'askSize',
 'volume',
 'fiftyTwoWeekHigh',
 'fromCurrency',
 'fiveYearAvgDividendYield',
 'fiftyTwoWeekLow',
 'bid',
 'tradeable',
 'dividendYield',
 'bidSize',
 'dayHigh',
 'regularMarketPrice',
 'logo_url']

In [63]:
px_target_cols = ['symbol', 'sector', 'industry','currentPrice', 'targetLowPrice', 'targetMedianPrice','numberOfAnalystOpinions',
            'targetMeanPrice', 'targetHighPrice', 'recommendationMean']

In [66]:
amzn_px_target = amzn_info[px_target_cols]
amzn_px_target

,symbol,sector,industry,currentPrice,targetLowPrice,targetMedianPrice,numberOfAnalystOpinions,targetMeanPrice,targetHighPrice,recommendationMean
0,AMZN,Consumer Cyclical,Internet Retail,2151.82,2250,3700,53,3634.16,4655,1.7

In [67]:
amzn_px_target['% to Median'] = amzn_px_target['targetMedianPrice']/amzn_px_target['currentPrice']-1
amzn_px_target['% Upside'] = amzn_px_target['targetHighPrice']/amzn_px_target['currentPrice']-1
amzn_px_target['% Downside'] = amzn_px_target['targetLowPrice']/amzn_px_target['currentPrice']-1
amzn_px_target

<ipython-input-67-50309bf99f66>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amzn_px_target['% to Median'] = amzn_px_target['targetMedianPrice']/amzn_px_target['currentPrice']-1
<ipython-input-67-50309bf99f66>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amzn_px_target['% Upside'] = amzn_px_target['targetHighPrice']/amzn_px_target['currentPrice']-1
<ipython-input-67-50309bf99f66>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amzn_px_target['% Downside'] = amzn_px_target['targetLowPrice']/amzn_px_target['currentPrice']-1

,symbol,sector,industry,currentPrice,targetLowPrice,targetMedianPrice,numberOfAnalystOpinions,targetMeanPrice,targetHighPrice,recommendationMean,% to Median,% Upside,% Downside
0,AMZN,Consumer Cyclical,Internet Retail,2151.82,2250,3700,53,3634.16,4655,1.7,0.719475,1.163285,0.045626

In [68]:
amzn = yf.Ticker('AMZN')
msft = yf.Ticker('MSFT')
aapl = yf.Ticker('AAPL')
googl = yf.Ticker('GOOGL')

In [70]:
msft_df = pd.DataFrame([msft.info])
aapl_df = pd.DataFrame([aapl.info])
googl_df = pd.DataFrame([googl.info])

In [71]:
msft_px_target = msft_df[px_target_cols]
aapl_px_target = aapl_df[px_target_cols]
googl_px_target = googl_df[px_target_cols]

In [72]:
msft_px_target['% to Median'] = msft_px_target['targetMedianPrice']/msft_px_target['currentPrice']-1
msft_px_target['% Upside'] = msft_px_target['targetHighPrice']/msft_px_target['currentPrice']-1
msft_px_target['% Downside'] = msft_px_target['targetLowPrice']/msft_px_target['currentPrice']-1

aapl_px_target['% to Median'] = aapl_px_target['targetMedianPrice']/aapl_px_target['currentPrice']-1
aapl_px_target['% Upside'] = aapl_px_target['targetHighPrice']/aapl_px_target['currentPrice']-1
aapl_px_target['% Downside'] = aapl_px_target['targetLowPrice']/aapl_px_target['currentPrice']-1

googl_px_target['% to Median'] = googl_px_target['targetMedianPrice']/googl_px_target['currentPrice']-1
googl_px_target['% Upside'] = googl_px_target['targetHighPrice']/googl_px_target['currentPrice']-1
googl_px_target['% Downside'] = googl_px_target['targetLowPrice']/googl_px_target['currentPrice']-1

<ipython-input-72-28e06bbe2746>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msft_px_target['% to Median'] = msft_px_target['targetMedianPrice']/msft_px_target['currentPrice']-1
<ipython-input-72-28e06bbe2746>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msft_px_target['% Upside'] = msft_px_target['targetHighPrice']/msft_px_target['currentPrice']-1
<ipython-input-72-28e06bbe2746>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msft_px_target['% Downside'] = msft_px_target['targetLowPrice']/msft_px_target['currentPrice']-1
<ipython-input-72-28e06bbe2746>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aapl_px_target['% to Median'] = aapl_px_target['targetMedianPrice']/aapl_px_target['currentPrice']-1
<ipython-input-72-28e06bbe2746>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aapl_px_target['% Upside'] = aapl_px_target['targetHighPrice']/aapl_px_target['currentPrice']-1
<ipython-input-72-28e06bbe2746>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aapl_px_target['% Downside'] = aapl_px_target['targetLowPrice']/aapl_px_target['currentPrice']-1
<ipython-input-72-28e06bbe2746>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  googl_px_target['% to Median'] = googl_px_target['targetMedianPrice']/googl_px_target['currentPrice']-1
<ipython-input-72-28e06bbe2746>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  googl_px_target['% Upside'] = googl_px_target['targetHighPrice']/googl_px_target['currentPrice']-1
<ipython-input-72-28e06bbe2746>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  googl_px_target['% Downside'] = googl_px_target['targetLowPrice']/googl_px_target['currentPrice']-1

In [73]:
msft_px_target

,symbol,sector,industry,currentPrice,targetLowPrice,targetMedianPrice,numberOfAnalystOpinions,targetMeanPrice,targetHighPrice,recommendationMean,% to Median,% Upside,% Downside
0,MSFT,Technology,Software—Infrastructure,252.56,298.18,360,46,362.95,425.96,1.7,0.425404,0.68657,0.18063

In [74]:
aapl_px_target

,symbol,sector,industry,currentPrice,targetLowPrice,targetMedianPrice,numberOfAnalystOpinions,targetMeanPrice,targetHighPrice,recommendationMean,% to Median,% Upside,% Downside
0,AAPL,Technology,Consumer Electronics,137.59,157,191,43,189.73,214,1.9,0.388182,0.555346,0.141071

In [75]:
googl_px_target

,symbol,sector,industry,currentPrice,targetLowPrice,targetMedianPrice,numberOfAnalystOpinions,targetMeanPrice,targetHighPrice,recommendationMean,% to Median,% Upside,% Downside
0,GOOGL,Communication Services,Internet Content & Information,2178.16,2658,3300,45,3287.81,4533.34,1.7,0.51504,1.08127,0.220296