In [18]:
import pandas as pd
import numpy as np

In [19]:
df_t0 = pd.DataFrame(np.random.randint(5,1000, size=(100,5)),columns=(['Price','Market Cap', 'Price Target','Date', '% YTD']))

min_date = pd.to_datetime('2021-10-30')
max_date = pd.to_datetime('2022-01-1')

d = (max_date - min_date).days + 1

In [20]:
df_t0['Price'] = np.random.randint(25,1000, size=len(df_t0))
df_t0['Market Cap'] = np.random.randint(500,50000, size=len(df_t0))
df_t0['% YTD'] = np.random.randint(-10,70, size=len(df_t0))
df_t0['Date'] = min_date + pd.to_timedelta(pd.np.random.randint(d,size=len(df_t0)), unit='d')

<ipython-input-20-88b9bda54361>:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  df_t0['Date'] = min_date + pd.to_timedelta(pd.np.random.randint(d,size=len(df_t0)), unit='d')

In [21]:
df_t0 = df_t0.reset_index().head()

In [22]:
df_t1 = pd.DataFrame(np.random.randint(5,1000, size=(100,5)),columns=(['Price','Market Cap', 'Price Target','Date', '% YTD']))

min_date = pd.to_datetime('2021-01-02')
max_date = pd.to_datetime('2022-01-13')

d = (max_date - min_date).days + 1

df_t1['Price'] = np.random.randint(25,1000, size=len(df_t1))
df_t1['Market Cap'] = np.random.randint(500,50000, size=len(df_t1))
df_t1['% YTD'] = np.random.randint(-10,70, size=len(df_t1))
df_t1['Date'] = min_date + pd.to_timedelta(pd.np.random.randint(d,size=len(df_t1)), unit='d')

<ipython-input-22-a473188663aa>:11: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  df_t1['Date'] = min_date + pd.to_timedelta(pd.np.random.randint(d,size=len(df_t1)), unit='d')

In [23]:
df_t1 = df_t1.reset_index().head()

In [24]:
comparison_vals = df_t0.values == df_t1.values
row,cols = np.where(comparison_vals ==False )
for item in zip(row,cols):
    df_t1.iloc[item[0], item[1]] = '{} {}'.format(df_t0.iloc[item[0],item[1]], df_t1.iloc[item[0],item[1]])

In [25]:
df_t0.head()

   index  Price  Market Cap  Price Target       Date  % YTD
0      0    665       18217           603 2021-12-18     45
1      1    562       40179           844 2021-11-20     44
2      2    724       16742           657 2021-11-24     58
3      3    432       39752           292 2021-12-06     54
4      4    341       47001           688 2021-12-08    -10

In [26]:
df_t1.head()

,index,Price,Market Cap,Price Target,Date,% YTD
0,0,665 500,18217 17136,603 674,2021-12-18 00:00:00 2021-06-28 00:00:00,45 67
1,1,562 400,40179 3889,844 601,2021-11-20 00:00:00 2021-03-04 00:00:00,44 5
2,2,724 98,16742 38252,657 416,2021-11-24 00:00:00 2021-10-31 00:00:00,58 7
3,3,432 859,39752 19874,292 224,2021-12-06 00:00:00 2021-02-12 00:00:00,54 68
4,4,341 260,47001 9921,688 586,2021-12-08 00:00:00 2021-01-03 00:00:00,-10 66

In [27]:
dfs = pd.concat([df_t0, df_t1])
dfs

,index,Price,Market Cap,Price Target,Date,% YTD
0,0,665,18217,603,2021-12-18 00:00:00,45
1,1,562,40179,844,2021-11-20 00:00:00,44
2,2,724,16742,657,2021-11-24 00:00:00,58
3,3,432,39752,292,2021-12-06 00:00:00,54
4,4,341,47001,688,2021-12-08 00:00:00,-10
0,0,665 500,18217 17136,603 674,2021-12-18 00:00:00 2021-06-28 00:00:00,45 67
1,1,562 400,40179 3889,844 601,2021-11-20 00:00:00 2021-03-04 00:00:00,44 5
2,2,724 98,16742 38252,657 416,2021-11-24 00:00:00 2021-10-31 00:00:00,58 7
3,3,432 859,39752 19874,292 224,2021-12-06 00:00:00 2021-02-12 00:00:00,54 68
4,4,341 260,47001 9921,688 586,2021-12-08 00:00:00 2021-01-03 00:00:00,-10 66

In [28]:
df_t0.compare(df_t1).head()

  Price          Market Cap              Price Target                Date  \
   self    other       self        other         self    other       self
0   665  665 500      18217  18217 17136          603  603 674 2021-12-18
1   562  562 400      40179   40179 3889          844  844 601 2021-11-20
2   724   724 98      16742  16742 38252          657  657 416 2021-11-24
3   432  432 859      39752  39752 19874          292  292 224 2021-12-06
4   341  341 260      47001   47001 9921          688  688 586 2021-12-08

                                           % YTD
                                     other  self   other
0  2021-12-18 00:00:00 2021-06-28 00:00:00    45   45 67
1  2021-11-20 00:00:00 2021-03-04 00:00:00    44    44 5
2  2021-11-24 00:00:00 2021-10-31 00:00:00    58    58 7
3  2021-12-06 00:00:00 2021-02-12 00:00:00    54   54 68
4  2021-12-08 00:00:00 2021-01-03 00:00:00   -10  -10 66

In [29]:
df_t0.compare(df_t1, align_axis='index').head()

           Price   Market Cap Price Target  \
0 self       665        18217          603
  other  665 500  18217 17136      603 674
1 self       562        40179          844
  other  562 400   40179 3889      844 601
2 self       724        16742          657

                                            Date  % YTD
0 self                       2021-12-18 00:00:00     45
  other  2021-12-18 00:00:00 2021-06-28 00:00:00  45 67
1 self                       2021-11-20 00:00:00     44
  other  2021-11-20 00:00:00 2021-03-04 00:00:00   44 5
2 self                       2021-11-24 00:00:00     58

In [30]:
dictionary = {1:df_t0,2:df_t1}
df_combined=pd.concat(dictionary)
df_combined.drop_duplicates(keep=False).head()

     index Price Market Cap Price Target                 Date % YTD
1 0      0   665      18217          603  2021-12-18 00:00:00    45
  1      1   562      40179          844  2021-11-20 00:00:00    44
  2      2   724      16742          657  2021-11-24 00:00:00    58
  3      3   432      39752          292  2021-12-06 00:00:00    54
  4      4   341      47001          688  2021-12-08 00:00:00   -10

In [31]:
df_t0.compare(df_t1, align_axis=0).head()

           Price   Market Cap Price Target  \
0 self       665        18217          603
  other  665 500  18217 17136      603 674
1 self       562        40179          844
  other  562 400   40179 3889      844 601
2 self       724        16742          657

                                            Date  % YTD
0 self                       2021-12-18 00:00:00     45
  other  2021-12-18 00:00:00 2021-06-28 00:00:00  45 67
1 self                       2021-11-20 00:00:00     44
  other  2021-11-20 00:00:00 2021-03-04 00:00:00   44 5
2 self                       2021-11-24 00:00:00     58

In [32]:
df_all = pd.concat([df_t0.set_index('index'),df_t1.set_index('index')],axis='columns', keys=['First','Second'])
df_all.head()

      First                                            Second               \
      Price Market Cap Price Target       Date % YTD    Price   Market Cap
index
0       665      18217          603 2021-12-18    45  665 500  18217 17136
1       562      40179          844 2021-11-20    44  562 400   40179 3889
2       724      16742          657 2021-11-24    58   724 98  16742 38252
3       432      39752          292 2021-12-06    54  432 859  39752 19874
4       341      47001          688 2021-12-08   -10  341 260   47001 9921


      Price Target                                     Date   % YTD
index
0          603 674  2021-12-18 00:00:00 2021-06-28 00:00:00   45 67
1          844 601  2021-11-20 00:00:00 2021-03-04 00:00:00    44 5
2          657 416  2021-11-24 00:00:00 2021-10-31 00:00:00    58 7
3          292 224  2021-12-06 00:00:00 2021-02-12 00:00:00   54 68
4          688 586  2021-12-08 00:00:00 2021-01-03 00:00:00  -10 66

In [33]:
df_final = df_all.swaplevel(axis='columns')[df_all.columns[1:]]
df_final

KeyError: "None of [MultiIndex([( 'First',   'Market Cap'),\n            ( 'First', 'Price Target'),\n            ( 'First',         'Date'),\n            ( 'First',        '% YTD'),\n            ('Second',        'Price'),\n            ('Second',   'Market Cap'),\n            ('Second', 'Price Target'),\n            ('Second',         'Date'),\n            ('Second',        '% YTD')],\n           )] are in the [columns]"

In [ ]:
def highlight_diff(data, color='coral'):
    attr = 'background-color: {}'.format(color)
    other = data.xs('First', axis='columns', level=-1)
    return pd.DataFrame(np.where(data.ne(other, level=0), attr, ''),
                        index=data.index, columns=data.columns)

df_final.style.apply(highlight_diff, axis=None)