In [1]:
import pandas as pd
import yfinance as yf

In [2]:
raw_df_prices = pd.read_csv('SHARADAR_EQUITY_DAILY.csv')

In [3]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 200)
pd.set_option('display.min_rows', 20)

In [4]:
raw_df_prices.head()

,ticker,date,open,high,low,close,volume,closeadj,closeunadj,lastupdated
0,ABILF,2021-11-09,0.30,0.33,0.30,0.33,7500.0,0.33,0.33,2021-11-09
1,ABILF,2021-11-08,0.35,0.35,0.35,0.35,0.0,0.35,0.35,2021-11-09
2,AAC,2021-09-24,9.74,9.75,9.73,9.75,38502.0,9.75,9.75,2021-09-24
3,AAC.U,2021-09-24,9.95,9.95,9.90,9.90,2692.0,9.90,9.90,2021-09-24
4,AAC.WS,2021-09-24,0.92,0.92,0.87,0.89,38784.0,0.89,0.89,2021-09-24

In [5]:
raw_df_mcap = pd.read_csv('SHARADAR_DAILY_3_mcap.csv')

In [6]:
raw_df_mcap.head()

,ticker,date,lastupdated,ev,evebit,evebitda,marketcap,pb,pe,ps
0,A,2021-09-01,2021-09-01,54542.7,42.8,34.4,53112.7,10.7,53.6,8.6
1,AA,2021-09-01,2021-09-01,9086.1,10.2,5.8,8521.1,2.3,19.8,0.8
2,AAC,2021-09-01,2021-09-01,1211.4,-86528.6,-86528.6,1212.5,242.5,-86607.1,NaN
3,AADI,2021-09-01,2021-09-01,50.1,-2.7,-2.7,86.9,2.5,-4.7,NaN
4,AAIC,2021-09-01,2021-09-01,893.7,259.6,259.6,120.9,0.5,559.7,6.4

In [7]:
raw_df_fundamentals = pd.read_csv('SHARADAR_SF1.csv')

In [8]:
raw_df_fundamentals.head()

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,assetsnc,assetturnover,bvps,capex,cashneq,cashnequsd,cor,consolinc,currentratio,de,debt,debtc,debtnc,debtusd,deferredrev,depamor,deposits,divyield,dps,ebit,ebitda,ebitdamargin,ebitdausd,ebitusd,ebt,eps,epsdil,epsusd,equity,equityavg,equityusd,ev,evebit,evebitda,fcf,fcfps,fxusd,gp,grossmargin,intangibles,...,ncf,ncfbus,ncfcommon,ncfdebt,ncfdiv,ncff,ncfi,ncfinv,ncfo,ncfx,netinc,netinccmn,netinccmnusd,netincdis,netincnci,netmargin,opex,opinc,payables,payoutratio,pb,pe,pe1,ppnenet,prefdivis,price,ps,ps1,receivables,retearn,revenue,revenueusd,rnd,roa,roe,roic,ros,sbcomp,sgna,sharefactor,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
0,A,ARQ,2017-03-31,2017-06-06,2017-04-30,2022-03-03,-477000000.0,8.016000e+09,NaN,3.800000e+09,4.216000e+09,NaN,13.620,-43000000.0,2.389000e+09,2.389000e+09,510000000.0,164000000.0,3.201,0.833,2.043000e+09,241000000.0,1.802000e+09,2.043000e+09,301000000.0,54000000.0,0.0,0.008,0.132,211000000.0,265000000.0,0.240,265000000.0,211000000.0,191000000.0,0.51,0.50,0.51,4.372000e+09,NaN,4.372000e+09,1.896638e+10,25.0,19.553,214000000.0,0.667,1.0,592000000.0,0.537,2.941000e+09,...,0.0,0.0,-75000000.0,52000000.0,-43000000.0,-67000000.0,-43000000.0,0.0,257000000.0,1000000.0,164000000.0,164000000.0,164000000.0,0.0,0.0,0.149,391000000.0,201000000.0,265000000.0,0.259,4.417,33.183,33.389,675000000.0,0.0,60.10,4.466,4.462,677000000.0,-393000000.0,1.102000e+09,1.102000e+09,84000000.0,NaN,NaN,NaN,NaN,15000000.0,307000000.0,1.0,321337443.0,321000000.0,325000000.0,3.433,5.075000e+09,0.0,27000000.0,0.0,15.810,2.613000e+09
1,A,ARQ,2017-06-30,2017-09-06,2017-07-31,2022-03-03,-417000000.0,8.261000e+09,NaN,3.996000e+09,4.265000e+09,NaN,14.355,-43000000.0,2.563000e+09,2.563000e+09,518000000.0,175000000.0,3.220,0.792,2.081000e+09,280000000.0,1.801000e+09,2.081000e+09,301000000.0,51000000.0,0.0,0.008,0.132,212000000.0,263000000.0,0.236,263000000.0,212000000.0,193000000.0,0.55,0.54,0.55,4.608000e+09,NaN,4.608000e+09,2.034349e+10,25.0,19.906,185000000.0,0.576,1.0,596000000.0,0.535,2.987000e+09,...,0.0,-57000000.0,32000000.0,39000000.0,-42000000.0,29000000.0,-101000000.0,-1000000.0,228000000.0,18000000.0,175000000.0,175000000.0,175000000.0,0.0,0.0,0.157,395000000.0,201000000.0,289000000.0,0.240,4.519,32.900,32.848,716000000.0,0.0,64.71,4.740,4.727,678000000.0,-260000000.0,1.114000e+09,1.114000e+09,87000000.0,NaN,NaN,NaN,NaN,13000000.0,308000000.0,1.0,321828003.0,321000000.0,326000000.0,3.470,5.274000e+09,0.0,18000000.0,0.0,16.430,2.755000e+09
2,A,ARQ,2017-09-30,2017-12-21,2017-10-31,2022-03-03,-346000000.0,8.426000e+09,NaN,4.169000e+09,4.257000e+09,NaN,15.003,-58000000.0,2.678000e+09,2.678000e+09,542000000.0,177000000.0,3.301,0.743,2.011000e+09,210000000.0,1.801000e+09,2.011000e+09,291000000.0,52000000.0,0.0,0.008,0.132,246000000.0,298000000.0,0.251,298000000.0,246000000.0,226000000.0,0.55,0.54,0.55,4.831000e+09,NaN,4.831000e+09,2.114318e+10,24.0,19.326,230000000.0,0.714,1.0,647000000.0,0.544,2.968000e+09,...,389000000.0,0.0,8000000.0,-70000000.0,-43000000.0,-106000000.0,-60000000.0,-2000000.0,288000000.0,-7000000.0,177000000.0,177000000.0,177000000.0,0.0,0.0,0.149,414000000.0,233000000.0,305000000.0,0.240,4.515,31.886,31.849,757000000.0,0.0,67.52,4.877,4.862,724000000.0,-126000000.0,1.189000e+09,1.189000e+09,89000000.0,NaN,NaN,NaN,NaN,12000000.0,325000000.0,1.0,323018027.0,322000000.0,329000000.0,3.693,5.458000e+09,0.0,49000000.0,0.0,16.950,2.906000e+09
3,A,ARQ,2017-12-31,2018-03-06,2018-01-31,2022-03-03,-269000000.0,8.698000e+09,NaN,4.397000e+09,4.301000e+09,NaN,14.000,-60000000.0,2.887000e+09,2.887000e+09,538000000.0,-320000000.0,3.231,0.923,2.145000e+09,345000000.0,1.800000e+09,2.145000e+09,321000000.0,51000000.0,0.0,0.008,0.149,253000000.0,304000000.0,0.251,304000000.0,253000000.0,233000000.0,-0.99,-0.99,-0.99,4.522000e+09,NaN,4.522000e+09,2.122188e+10,23.0,18.780,155000000.0,0.480,1.0,673000000.0,0.556,2.974000e+09,...,209000000.0,-6000000.0,-22000000.0,135000000.0,-48000000.0,37000000.0,-67000000.0,-1000000.0,215000000.0,24000000.0,-320000000.0,-320000000.0,-320000000.0,0.0,0.0,-0.264,434000000.0,239000000.0,292000000.0,-0.151,4.857,112.061,109.855,792000000.0,0.0,68.11,4.758,4.766,751000000.0,-529000000.0,1.211000e+09,1.211000e+09,93000000.0,NaN,NaN,NaN,NaN,31000000.0,341000000.0,1.0,322476579.0,323000000.0,323000000.0,3.749,5.724000e+09,0.0,553000000.0,0.0,17.721,3.036000e+09
4,A,ARQ,2018-03-31,2018-05-31,2018-04-30,2022-03-03,-310000000.0,8.784000e+09,NaN,4.525000e+09,4.259000e+09,NaN,14.326,-48000000.0,3.011000e+09,3.011000e+09,562000000.0,205000000.0,3.315,0.903,2.115000e+09,315000000.0,1.800000e+09,2.115000e+09,333000000.0,50000000.0,0.0,0.009,0.149,246000000.0,296000000.0,0.245,296000000.0,246000000.0,227000000.0,0.64,0.63,0.64,4.613000e+09,NaN,4.613000e+09,1.891544e+10,20.0,16.292,255000000.0,0.792,1.0,644000000.0,0.534,2.932000e+09,...,-208000000.0,-1000000.0,-35000000.0,-30000000.0,-48000000.0,-114000000.0,-50000000.0,-2000000.0,303000000.0,-15000000.0,205000000.0,205000000.0,205000000.0,0.0,0.0,0.170,429000000.0,215000000.0,271000000.0,0.233,4.295,83.593,82.560,798000000.0,0.0,61.92,4.197,4.224,754000000.0,-412000000.0,1.206000e+09,1.206000e+09,91000000.0,NaN,NaN,NaN,NaN,12000000.0,338000000.0,1.0,319952126.0,322000000.0,326000000.0,3.745,5.852000e+09,0.0,22000000.0,0.0,18.174,3.160000e+09

In [9]:
raw_df = pd.merge(raw_df_mcap, raw_df_prices)

In [10]:
len(raw_df)

2501958

In [11]:
raw_df.sort_values(by=['marketcap'], ascending=False).head()

,ticker,date,lastupdated,ev,evebit,evebitda,marketcap,pb,pe,ps,open,high,low,close,volume,closeadj,closeunadj
2383346,AAPL,2022-05-06,2022-05-06,2637488.3,21.7,19.8,2545605.3,37.8,25.0,6.6,156.010,159.44,154.18,157.28,115897949.0,157.28,157.28
2388491,AAPL,2022-05-10,2022-05-10,2592655.3,21.3,19.5,2500772.3,37.1,24.5,6.5,155.520,156.74,152.93,154.51,114750399.0,154.51,154.51
2388461,AAPL,2022-05-09,2022-05-09,2553001.6,21.0,19.2,2461118.6,36.5,24.1,6.4,154.925,155.83,151.49,152.06,130291378.0,152.06,152.06
2486706,AAPL,2022-05-27,2022-05-27,2513833.5,20.7,18.9,2421950.5,35.9,23.8,6.3,145.390,149.68,145.26,149.64,90464794.0,149.64,149.64
2423076,AAPL,2022-05-17,2022-05-17,2507359.4,20.6,18.9,2415476.4,35.8,23.7,6.3,148.860,149.77,146.68,149.24,76165406.0,149.24,149.24

In [12]:
raw_df.dtypes

ticker          object
date            object
lastupdated     object
ev             float64
evebit         float64
evebitda       float64
marketcap      float64
pb             float64
pe             float64
ps             float64
open           float64
high           float64
low            float64
close          float64
volume         float64
closeadj       float64
closeunadj     float64
dtype: object

In [13]:
# refine for all companies > $2bn m cap
# 2.5m values --> 677k --> 310k
#universe = (raw_df[raw_df['marketcap']>1000]) & (raw_df[raw_df['evebit']>1.1])

universe = raw_df.loc[(raw_df["marketcap"] > 2000) & (raw_df["evebit"] > 2)]

In [19]:
universe.tail()

,ticker,date,lastupdated,ev,evebit,evebitda,marketcap,pb,pe,ps,open,high,low,close,volume,closeadj,closeunadj
2501915,REPYY,2022-05-27,2022-05-30,17085.2,3.8,1.9,19643.7,0.8,10.3,0.3,15.91,16.15,15.84,16.09,333700.0,16.09,16.09
2501922,SIEGY,2022-05-27,2022-05-30,129724.8,14.3,10.0,110770.5,2.9,19.0,1.1,65.12,65.97,65.08,65.70,169100.0,65.70,65.70
2501928,SUBCY,2022-05-27,2022-05-30,1948.2,4.6,4.6,2000.2,1.7,7.5,0.8,10.22,10.29,10.19,10.26,16800.0,10.26,10.26
2501943,TTDKY,2022-05-27,2022-05-30,11907.2,14.0,7.9,13358.5,2.0,20.2,1.7,34.60,34.60,34.29,34.53,9400.0,34.53,34.53
2501949,VIVHY,2022-05-27,2022-05-30,19203.7,4.3,4.3,14344.9,0.6,3.6,0.6,11.76,11.81,11.72,11.79,51800.0,11.79,11.79

In [15]:
len(universe)

310042

In [17]:
sp500 = pd.read_csv('SP500.csv')

In [53]:
sp500['DATE'] = pd.to_datetime(sp500["DATE"])
sp500 = sp500[sp500['SP500'] != '.']
sp500['SP500'] = pd.to_numeric(sp500['SP500'])
sp500.head()

        DATE    SP500
0 2017-05-31  2411.80
1 2017-06-01  2430.06
2 2017-06-02  2439.07
3 2017-06-05  2436.10
4 2017-06-06  2429.33

In [54]:
sp500.dtypes

DATE     datetime64[ns]
SP500           float64
dtype: object

In [61]:
first = '2021-08-31'
last = '2022-05-27'
sp500_df = sp500.set_index('DATE').loc[first:last]

sp500_df['% SP500 1D Change'] = round(sp500_df['SP500'].pct_change()*100,2)
sp500_df.tail()

              SP500  % SP500 1D Change
DATE
2022-05-23  3973.75               1.86
2022-05-24  3941.48              -0.81
2022-05-25  3978.73               0.95
2022-05-26  4057.84               1.99
2022-05-27  4158.24               2.47

In [63]:
# constituents
SP500_tickers = pd.read_csv('constituents.csv')
SP500_tickers.head()

  Symbol                 Name       Sector
0    MMM                   3M  Industrials
1    AOS          A. O. Smith  Industrials
2    ABT  Abbott Laboratories  Health Care
3   ABBV               AbbVie  Health Care
4   ABMD              Abiomed  Health Care

In [68]:
# isin universe('ticker'); SP500_tickers('Symbol')
SP500_ticker_lst = (SP500_tickers['Symbol'])

In [71]:
df_result = SP500_ticker_lst.isin(universe['ticker'])
df_result.value_counts()

True     485
False     20
Name: Symbol, dtype: int64