In [1]:
from PIL import Image
from pytesseract import pytesseract
import pandas as pd

In [2]:
img = Image.open('/Users/brendan/Desktop/nbanumbers.png')
df = pytesseract.image_to_data(Image.open('/Users/brendan/Desktop/nbanumbers.png'),lang='eng', output_type='data.frame')

In [3]:
df = df[df['text'].notnull()]

df_ = df['text']

In [4]:
df_.to_frame()
df_.to_excel('nba_excel.xlsx')

In [5]:
file = pd.read_excel('/Users/brendan/Desktop/Python/nba_excel_scrubbed.xlsx', sheet_name='data')
file

    text                Player  Score     Year
0    1.0  Kareem Abdul-Jabbar*  25.37  1971-72
1    2.0     Wilt Chamberlain*  24.98  1963-64
2    3.0         George Mikan*  23.43  1950-51
3    4.0     Wilt Chamberlain*  23.11  1961-62
4    5.0  Kareem Abdul-Jabbar*  22.31  1970-71
5    6.0     Wilt Chamberlain*  21.87  1966-67
6    7.0  Kareem Abdul-Jabbar*  21.86  1972-73
7    8.0     Wilt Chamberlain*  21.42  1965-66
8    9.0       Michael Jordan*  21.23  1987-88
9   10.0         George Mikan*  21.13  1949-50
10  11.0     Wilt Chamberlain*  20.94  1962-63
11  12.0         George Mikan*  20.86  1948-49
12  13.0      Oscar Robertson*  20.65  1963-64
13  14.0       Michael Jordan*  20.43  1995-96
14  15.0     Wilt Chamberlain*  20.38  1967-68
15  16.0       Michael Jordan*  20.30  1990-91
16  17.0          LeBron James  20.25  2008-09
17  18.0       David Robinson*  19.98  1993-94
18  19.0       Michael Jordan*  19.80  1988-89
19  20.0        Artis Gilmore*  19.79  1971-72

In [6]:
img = Image.open('/Users/brendan/Desktop/fantasybb.png')
df = pytesseract.image_to_data(Image.open('/Users/brendan/Desktop/fantasybb.png'),lang='eng', output_type='data.frame')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/brendan/Desktop/fantasybb.png'

In [ ]:
df.to_excel('fantasybbprep.xlsx')

In [7]:
img2 = Image.open('/Users/brendan/Desktop/excel_numbers.png')
df = pytesseract.image_to_data(Image.open('/Users/brendan/Desktop/excel_numbers.png'),lang='eng', output_type='data.frame')

In [8]:
df

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,154,748,-1.000000,NaN
1,2,1,1,0,0,0,79,16,59,112,-1.000000,NaN
2,3,1,1,1,0,0,79,16,56,80,-1.000000,NaN
3,4,1,1,1,1,0,79,16,52,16,-1.000000,NaN
4,5,1,1,1,1,1,79,16,52,16,96.558578,308.9
5,4,1,1,1,2,0,90,48,45,16,-1.000000,NaN
6,5,1,1,1,2,1,90,48,45,16,95.826920,7.8%
7,4,1,1,1,3,0,88,80,47,16,-1.000000,NaN
8,5,1,1,1,3,1,88,80,47,16,95.719444,2.2%
9,3,1,1,2,0,0,81,112,57,16,-1.000000,NaN
10,4,1,1,2,1,0,81,112,57,16,-1.000000,NaN
11,5,1,1,2,1,1,81,112,57,16,96.701569,23.4%
12,2,1,2,0,0,0,65,176,73,112,-1.000000,NaN
13,3,1,2,1,0,0,65,176,70,80,-1.000000,NaN
14,4,1,2,1,1,0,79,176,52,16,-1.000000,NaN
15,5,1,2,1,1,1,79,176,52,16,95.572273,750.5
16,4,1,2,1,2,0,65,208,70,16,-1.000000,NaN
17,5,1,2,1,2,1,65,208,70,16,96.632477,185.0%
18,4,1,2,1,3,0,69,240,66,16,-1.000000,NaN
19,5,1,2,1,3,1,69,240,66,16,90.461830,-15.7%
20,3,1,2,2,0,0,81,272,57,16,-1.000000,NaN
21,4,1,2,2,1,0,81,272,57,16,-1.000000,NaN
22,5,1,2,2,1,1,81,272,57,16,96.580399,56.8%
23,2,1,3,0,0,0,80,336,58,112,-1.000000,NaN
24,3,1,3,1,0,0,80,336,55,80,-1.000000,NaN
25,4,1,3,1,1,0,80,336,51,16,-1.000000,NaN
26,5,1,3,1,1,1,80,336,51,16,96.857208,166.2
27,4,1,3,1,2,0,88,368,47,16,-1.000000,NaN
28,5,1,3,1,2,1,88,368,47,16,95.329018,9.9%
29,4,1,3,1,3,0,89,400,46,16,-1.000000,NaN
30,5,1,3,1,3,1,89,400,46,16,95.881737,1.8%
31,3,1,3,2,0,0,82,432,56,16,-1.000000,NaN
32,4,1,3,2,1,0,82,432,56,16,-1.000000,NaN
33,5,1,3,2,1,1,82,432,56,16,96.037262,12.6%
34,2,1,4,0,0,0,81,496,57,112,-1.000000,NaN
35,3,1,4,1,0,0,81,496,54,80,-1.000000,NaN
36,4,1,4,1,1,0,91,496,41,16,-1.000000,NaN
37,5,1,4,1,1,1,91,496,41,16,95.124046,95.4
38,4,1,4,1,2,0,81,528,54,16,-1.000000,NaN
39,5,1,4,1,2,1,81,528,54,16,90.649902,-8.9%
40,4,1,4,1,3,0,81,560,54,16,-1.000000,NaN
41,5,1,4,1,3,1,81,560,54,16,90.877136,-5.3%
42,3,1,4,2,0,0,93,592,45,16,-1.000000,NaN
43,4,1,4,2,1,0,93,592,45,16,-1.000000,NaN
44,5,1,4,2,1,1,93,592,45,16,95.721992,7.2%
45,2,1,5,0,0,0,50,656,85,80,-1.000000,NaN
46,3,1,5,1,0,0,50,656,85,80,-1.000000,NaN
47,4,1,5,1,1,0,50,656,82,19,-1.000000,NaN
48,5,1,5,1,1,1,50,656,82,19,96.424637,"1,321.00"
49,4,1,5,1,2,0,77,688,58,16,-1.000000,NaN
50,5,1,5,1,2,1,77,688,58,16,95.172409,64.0%
51,4,1,5,1,3,0,81,720,54,16,-1.000000,NaN
52,5,1,5,1,3,1,81,720,54,16,90.320328,-9.3%