In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
plt.style.use('fivethirtyeight')
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from datetime import datetime
import dataframe_image as dfi
from statsmodels.tsa.seasonal import seasonal_decompose

In [15]:
raw_df_12_14_2020 = pd.read_csv('/Users/brendan/Desktop/Python/Two Sigma Projects/Airbnb/airBnb Paris time series/airbnb_paris_12_14_2020.csv')
print(f"The 12_14_2020 dataset contains {len(raw_df_12_14_2020)} AirBnb listings; the avg price is ${round(raw_df_12_14_2020['price'].mean(),2)}.")

raw_df_01_10_2021 = pd.read_csv('/Users/brendan/Desktop/Python/Two Sigma Projects/Airbnb/airBnb Paris time series/airbnb_paris_01_10_2021.csv')
print(f"The dataset contains {len(raw_df_01_10_2021)} AirBnb listings.")

raw_df_02_08_2021 = pd.read_csv('/Users/brendan/Desktop/Python/Two Sigma Projects/Airbnb/airBnb Paris time series/airbnb_paris_02-08_2021.csv')
print(f"The dataset contains {len(raw_df_02_08_2021)} AirBnb listings.")

raw_df_03_04_2021 = pd.read_csv('/Users/brendan/Desktop/Python/Two Sigma Projects/Airbnb/airBnb Paris time series/airbnb_paris_03_04_2021.csv')
print(f"The dataset contains {len(raw_df_03_04_2021)} AirBnb listings.")

raw_df_04_10_2021 = pd.read_csv('/Users/brendan/Desktop/Python/Two Sigma Projects/Airbnb/airBnb Paris time series/airbnb_paris_04_10_2021.csv')
print(f"The dataset contains {len(raw_df_04_10_2021)} AirBnb listings.")

raw_df_06_07_2021 = pd.read_csv('/Users/brendan/Desktop/Python/Two Sigma Projects/Airbnb/airBnb Paris time series/airbnb_paris_06_07_2021.csv')
print(f"The 06_07_2021 dataset contains {len(raw_df_06_07_2021)} AirBnb listings; the avg price is ${round(raw_df_06_07_2021['price'].mean(),2)}.")

The 12_14_2020 dataset contains 65917 AirBnb listings; the avg price is $114.28.
The dataset contains 65256 AirBnb listings.
The dataset contains 64690 AirBnb listings.
The dataset contains 64347 AirBnb listings.
The dataset contains 63090 AirBnb listings.
The 06_07_2021 dataset contains 61105 AirBnb listings; the avg price is $117.4.

In [96]:
df_list = [raw_df_12_14_2020, raw_df_01_10_2021, raw_df_02_08_2021, raw_df_03_04_2021, raw_df_04_10_2021,
          raw_df_06_07_2021]
dates = ['12_14_2020', '01_10_2021', '02_08_2021','03_04_2021', '04_10_2021',
        '06_07_2021', '07_06_2021', '09_09_2021', '10_09_2021']

df_final = []

def airbnb_parse(df_list, dates):
    for date in dates:
        df_file = pd.read_csv(f"/Users/brendan/Desktop/Python/Two Sigma Projects/Airbnb/airBnb Paris time series/airbnb_paris_{date}.csv")
        print(f"The {date} Paris dataset contains {len(df_file)} AirBnb listings -- the avg price is ${round(df_file['price'].mean(),2)}.")
        #print(f"The avg price per night out of {len(df_file)} listings is  ${round(df_file['price'].mean(),2)}.")


def airbnb_to_frame(df_list, dates):
    for date in dates:
        df_file = pd.read_csv(f"/Users/brendan/Desktop/Python/Two Sigma Projects/Airbnb/airBnb Paris time series/airbnb_paris_{date}.csv")
        #print(f"The {date} Paris dataset contains {len(df_file)} AirBnb listings -- the avg price is ${round(df_file['price'].mean(),2)}.")
        df_final.append(
        {
            'Date': date,
            '# of Filings': len(df_file),
            'Avg Price': round(df_file['price'].mean(),2),
            'Median Price': round(df_file['price'].median(),2),
            'Min Price': df_file['price'].min(),
            'Max Price': df_file['price'].max()
        })
    
    return pd.DataFrame(df_final)

In [97]:
airbnb_parse(df_list, dates)

The 12_14_2020 Paris dataset contains 65917 AirBnb listings -- the avg price is $114.28.
The 01_10_2021 Paris dataset contains 65256 AirBnb listings -- the avg price is $112.89.
The 02_08_2021 Paris dataset contains 64690 AirBnb listings -- the avg price is $113.1.
The 03_04_2021 Paris dataset contains 64347 AirBnb listings -- the avg price is $112.39.
The 04_10_2021 Paris dataset contains 63090 AirBnb listings -- the avg price is $112.92.
The 06_07_2021 Paris dataset contains 61105 AirBnb listings -- the avg price is $117.4.
The 07_06_2021 Paris dataset contains 51040 AirBnb listings -- the avg price is $124.53.
The 09_09_2021 Paris dataset contains 50133 AirBnb listings -- the avg price is $125.89.
The 10_09_2021 Paris dataset contains 49634 AirBnb listings -- the avg price is $130.2.

In [98]:
airbnb_to_frame(df_list, dates)

         Date  # of Filings  Avg Price  Median Price  Min Price  Max Price
0  12_14_2020         65917     114.28          80.0          0      11600
1  01_10_2021         65256     112.89          80.0          0      11600
2  02_08_2021         64690     113.10          80.0          0      12000
3  03_04_2021         64347     112.39          80.0          0      12000
4  04_10_2021         63090     112.92          80.0          0      11600
5  06_07_2021         61105     117.40          80.0          0      11600
6  07_06_2021         51040     124.53          85.0          0      11600
7  09_09_2021         50133     125.89          88.0          0      11600
8  10_09_2021         49634     130.20          90.0          0      11600

In [54]:
raw_df_12_14_2020.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2577,Loft for 4 by Canal Saint Martin,2827,Karine,NaN,Entrepôt,48.86993,2.36251,Entire home/apt,125,3,1,2019-01-02,0.04,1,364
1,3109,zen and calm,3631,Anne,NaN,Observatoire,48.83349,2.31852,Entire home/apt,60,2,9,2019-10-24,0.19,1,2
2,4890,Quiet Historic & Cute +Free Cruise,6792,Ryan Of Cobblestone,NaN,Temple,48.86409,2.35651,Entire home/apt,69,5,23,2020-09-07,0.21,14,67
3,5396,Explore the heart of old Paris,7903,Borzou,NaN,Hôtel-de-Ville,48.85207,2.35871,Entire home/apt,62,1,231,2020-11-05,1.65,1,90
4,7397,MARAIS - 2ROOMS APT - 2/4 PEOPLE,2626,Franck,NaN,Hôtel-de-Ville,48.85758,2.35275,Entire home/apt,53,15,269,2020-08-15,2.28,3,348