In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import mysql.connector
import matplotlib.pyplot as plt

In [4]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Boston1429$$"
)

print(mydb)

<mysql.connector.connection.MySQLConnection object at 0x7f807c709c10>

In [16]:
mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM MyFitnessPal.food_12_01")

myresult = mycursor.fetchall()

for x in myresult:
    print(x)
    
df_12_01 = pd.DataFrame(myresult, columns=['Date', 'Meal', 'Food', 'Calories', 'Carbs','Fat','Protein','Sodium','Sugar'])
df_12_01

(datetime.date(2021, 12, 1), 'Breakfast', 'Oat Milk, Dark Chocolate, 1 cup', 140, 31, 2, 3, 135, 12)
(datetime.date(2021, 12, 1), 'Breakfast', 'Oat Milk, Dark Chocolate, 1 cup', 140, 31, 2, 3, 135, 12)
(datetime.date(2021, 12, 1), 'Breakfast', 'banana', 105, 27, 0, 1, 1, 14)
(datetime.date(2021, 12, 1), 'Breakfast', 'Noosa - vanilla bean, 8 oz', 280, 32, 12, 12, 130, 32)
(datetime.date(2021, 12, 1), 'Breakfast', 'Blueberries - 0.5 cup', 42, 11, 0, 1, 1, 7)
(datetime.date(2021, 12, 1), 'Lunch', 'Josephs - Avocado Hummus, 2 tbsp', 60, 3, 5, 1, 105, 0)
(datetime.date(2021, 12, 1), 'Lunch', 'Baby Carrots, 10 carrots', 36, 8, 0, 1, 4, 5)
(datetime.date(2021, 12, 1), 'Lunch', 'Blueberries, 1 cup', 84, 21, 0, 1, 1, 15)
(datetime.date(2021, 12, 1), 'Lunch', 'Oat Milk, Dark Chocolate, 1 cup', 140, 31, 2, 3, 135, 12)
(datetime.date(2021, 12, 1), 'Dinner', 'Cucumber, 0.25 cucumber', 11, 3, 0, 0, 2, 1)
(datetime.date(2021, 12, 1), 'Dinner', 'Green bell pepper, 0.5 medium', 12, 3, 0, 1, 2, 1)
(datetime.date(2021, 12, 1), 'Dinner', 'tomato, 0.5 medium', 13, 3, 0, 1, 10, 2)
(datetime.date(2021, 12, 1), 'Dinner', 'Green leaf lettuce, 1 cup', 5, 1, 0, 0, 10, 0)
(datetime.date(2021, 12, 1), 'Dinner', 'Weaver chicken breast nuggets, 4', 190, 12, 11, 10, 630, 0)
(datetime.date(2021, 12, 1), 'Dinner', 'Kens steakhouse caesar, 2 tbsp', 170, 1, 18, 1, 250, 1)
(datetime.date(2021, 12, 1), 'Dinner', 'avocado', 240, 13, 22, 3, 11, 1)
(datetime.date(2021, 12, 1), 'Snacks', 'roasted cashews - 10', 51, 3, 1, 2, 3, 1)

,Date,Meal,Food,Calories,Carbs,Fat,Protein,Sodium,Sugar
0,2021-12-01,Breakfast,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
1,2021-12-01,Breakfast,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
2,2021-12-01,Breakfast,banana,105,27,0,1,1,14
3,2021-12-01,Breakfast,"Noosa - vanilla bean, 8 oz",280,32,12,12,130,32
4,2021-12-01,Breakfast,Blueberries - 0.5 cup,42,11,0,1,1,7
5,2021-12-01,Lunch,"Josephs - Avocado Hummus, 2 tbsp",60,3,5,1,105,0
6,2021-12-01,Lunch,"Baby Carrots, 10 carrots",36,8,0,1,4,5
7,2021-12-01,Lunch,"Blueberries, 1 cup",84,21,0,1,1,15
8,2021-12-01,Lunch,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
9,2021-12-01,Dinner,"Cucumber, 0.25 cucumber",11,3,0,0,2,1
10,2021-12-01,Dinner,"Green bell pepper, 0.5 medium",12,3,0,1,2,1
11,2021-12-01,Dinner,"tomato, 0.5 medium",13,3,0,1,10,2
12,2021-12-01,Dinner,"Green leaf lettuce, 1 cup",5,1,0,0,10,0
13,2021-12-01,Dinner,"Weaver chicken breast nuggets, 4",190,12,11,10,630,0
14,2021-12-01,Dinner,"Kens steakhouse caesar, 2 tbsp",170,1,18,1,250,1
15,2021-12-01,Dinner,avocado,240,13,22,3,11,1
16,2021-12-01,Snacks,roasted cashews - 10,51,3,1,2,3,1