In [65]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import mysql.connector
import matplotlib.pyplot as plt

In [66]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Boston1429$$"
)

print(mydb)

<mysql.connector.connection.MySQLConnection object at 0x7fa028c03ee0>

In [68]:
mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM MyFitnessPal.food_12_01")

myresult = mycursor.fetchall()

for x in myresult:
    print(x)
    
df_12_01 = pd.DataFrame(myresult, columns=['Date', 'Meal', 'Food', 'Calories', 'Carbs','Fat','Protein','Sodium','Sugar'])
df_12_01

(datetime.date(2021, 12, 1), 'Breakfast', 'Oat Milk, Dark Chocolate, 1 cup', 140, 31, 2, 3, 135, 12)
(datetime.date(2021, 12, 1), 'Breakfast', 'Oat Milk, Dark Chocolate, 1 cup', 140, 31, 2, 3, 135, 12)
(datetime.date(2021, 12, 1), 'Breakfast', 'banana', 105, 27, 0, 1, 1, 14)
(datetime.date(2021, 12, 1), 'Breakfast', 'Noosa - vanilla bean, 8 oz', 280, 32, 12, 12, 130, 32)
(datetime.date(2021, 12, 1), 'Breakfast', 'Blueberries - 0.5 cup', 42, 11, 0, 1, 1, 7)
(datetime.date(2021, 12, 1), 'Lunch', 'Josephs - Avocado Hummus, 2 tbsp', 60, 3, 5, 1, 105, 0)
(datetime.date(2021, 12, 1), 'Lunch', 'Baby Carrots, 10 carrots', 36, 8, 0, 1, 4, 5)
(datetime.date(2021, 12, 1), 'Lunch', 'Blueberries, 1 cup', 84, 21, 0, 1, 1, 15)
(datetime.date(2021, 12, 1), 'Lunch', 'Oat Milk, Dark Chocolate, 1 cup', 140, 31, 2, 3, 135, 12)
(datetime.date(2021, 12, 1), 'Dinner', 'Cucumber, 0.25 cucumber', 11, 3, 0, 0, 2, 1)
(datetime.date(2021, 12, 1), 'Dinner', 'Green bell pepper, 0.5 medium', 12, 3, 0, 1, 2, 1)
(datetime.date(2021, 12, 1), 'Dinner', 'tomato, 0.5 medium', 13, 3, 0, 1, 10, 2)
(datetime.date(2021, 12, 1), 'Dinner', 'Green leaf lettuce, 1 cup', 5, 1, 0, 0, 10, 0)
(datetime.date(2021, 12, 1), 'Dinner', 'Weaver chicken breast nuggets, 4', 190, 12, 11, 10, 630, 0)
(datetime.date(2021, 12, 1), 'Dinner', 'Kens steakhouse caesar, 2 tbsp', 170, 1, 18, 1, 250, 1)
(datetime.date(2021, 12, 1), 'Dinner', 'avocado', 240, 13, 22, 3, 11, 1)
(datetime.date(2021, 12, 1), 'Snacks', 'roasted cashews - 10', 51, 3, 1, 2, 3, 1)

,Date,Meal,Food,Calories,Carbs,Fat,Protein,Sodium,Sugar
0,2021-12-01,Breakfast,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
1,2021-12-01,Breakfast,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
2,2021-12-01,Breakfast,banana,105,27,0,1,1,14
3,2021-12-01,Breakfast,"Noosa - vanilla bean, 8 oz",280,32,12,12,130,32
4,2021-12-01,Breakfast,Blueberries - 0.5 cup,42,11,0,1,1,7
5,2021-12-01,Lunch,"Josephs - Avocado Hummus, 2 tbsp",60,3,5,1,105,0
6,2021-12-01,Lunch,"Baby Carrots, 10 carrots",36,8,0,1,4,5
7,2021-12-01,Lunch,"Blueberries, 1 cup",84,21,0,1,1,15
8,2021-12-01,Lunch,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
9,2021-12-01,Dinner,"Cucumber, 0.25 cucumber",11,3,0,0,2,1
10,2021-12-01,Dinner,"Green bell pepper, 0.5 medium",12,3,0,1,2,1
11,2021-12-01,Dinner,"tomato, 0.5 medium",13,3,0,1,10,2
12,2021-12-01,Dinner,"Green leaf lettuce, 1 cup",5,1,0,0,10,0
13,2021-12-01,Dinner,"Weaver chicken breast nuggets, 4",190,12,11,10,630,0
14,2021-12-01,Dinner,"Kens steakhouse caesar, 2 tbsp",170,1,18,1,250,1
15,2021-12-01,Dinner,avocado,240,13,22,3,11,1
16,2021-12-01,Snacks,roasted cashews - 10,51,3,1,2,3,1

In [5]:
mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM MyFitnessPal.food_12_02")

myresult_12_02 = mycursor.fetchall()


df_12_02 = pd.DataFrame(myresult_12_02, columns=['Date', 'Meal', 'Food', 'Calories', 'Carbs','Fat','Protein','Sodium','Sugar'])
df_12_02

,Date,Meal,Food,Calories,Carbs,Fat,Protein,Sodium,Sugar
0,2021-12-02,Breakfast,"Noosa - vanilla bean, 8 oz",280,32,12,12,130,32
1,2021-12-02,Breakfast,Raspberries - 0.5 cup,32,7,0,1,1,3
2,2021-12-02,Lunch,Yogurt Fruit Granole Parfait,260,53,2,7,150,46
3,2021-12-02,Dinner,Cheese Lovers Tortelloni,810,108,30,33,1560,3
4,2021-12-02,Snacks,Roasted Cashews - 10 pieces,101,6,2,3,5,1
5,2021-12-02,Snacks,Roasted Cashews - 10 pieces,101,6,2,3,5,1

In [6]:
mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM MyFitnessPal.food_12_03")

myresult_12_03 = mycursor.fetchall()


df_12_03 = pd.DataFrame(myresult_12_03, columns=['Date', 'Meal', 'Food', 'Calories', 'Carbs','Fat','Protein','Sodium','Sugar'])
df_12_03

,Date,Meal,Food,Calories,Carbs,Fat,Protein,Sodium,Sugar
0,2021-12-03,Breakfast,Raspberries - 0.5 cup,32,7,0,1,1,3
1,2021-12-03,Breakfast,banana,105,27,0,1,1,14
2,2021-12-03,Lunch,"Sicilian pizza, 1 slice",319,43,11,12,668,0
3,2021-12-03,Lunch,"Sicilian pizza, 1 slice",319,43,11,12,668,0
4,2021-12-03,Lunch,"Sicilian pizza, 1 slice",319,43,11,12,668,0
5,2021-12-03,Lunch,Arancini,380,43,17,12,458,6
6,2021-12-03,Dinner,"Trader Joes - Chicken Drumellas, 8",380,24,18,30,480,0
7,2021-12-03,Snack,"Blueberries, 1 cup",84,21,0,1,1,15
8,2021-12-03,Snack,Iced Coffee,5,0,0,1,9,0
9,2021-12-03,Snack,Iced Coffee,5,0,0,1,9,0

In [7]:
mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM MyFitnessPal.food_12_04")

myresult_12_04 = mycursor.fetchall()


df_12_04 = pd.DataFrame(myresult_12_04, columns=['Date', 'Meal', 'Food', 'Calories', 'Carbs','Fat','Protein','Sodium','Sugar'])
df_12_04

,Date,Meal,Food,Calories,Carbs,Fat,Protein,Sodium,Sugar
0,2021-12-04,Breakfast,banana,105,27,0,1,1,14
1,2021-12-04,Lunch,"Anerican cheese, 2 slices",208,2,9,10,936,2
2,2021-12-04,Lunch,"Anerican cheese, 2 slices",208,2,9,10,936,2
3,2021-12-04,Lunch,"Oat Nut bread, 2 slices",220,36,4,8,260,6
4,2021-12-04,Lunch,"Oat Nut bread, 2 slices",220,36,4,8,260,6
5,2021-12-04,Dinner,Trader Joes - chicken chow mein,400,78,3,18,1920,12
6,2021-12-04,Snacks,banana,105,27,0,1,1,14
7,2021-12-04,Snacks,"protein powder, 0.25 cup",33,6,1,22,0,2

## Append all dataframes for week 1

In [8]:
df_week1 = pd.concat([df_12_01, df_12_02, df_12_03, df_12_04])
df_week1

,Date,Meal,Food,Calories,Carbs,Fat,Protein,Sodium,Sugar
0,2021-12-01,Breakfast,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
1,2021-12-01,Breakfast,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
2,2021-12-01,Breakfast,banana,105,27,0,1,1,14
3,2021-12-01,Breakfast,"Noosa - vanilla bean, 8 oz",280,32,12,12,130,32
4,2021-12-01,Breakfast,Blueberries - 0.5 cup,42,11,0,1,1,7
5,2021-12-01,Lunch,"Josephs - Avocado Hummus, 2 tbsp",60,3,5,1,105,0
6,2021-12-01,Lunch,"Baby Carrots, 10 carrots",36,8,0,1,4,5
7,2021-12-01,Lunch,"Blueberries, 1 cup",84,21,0,1,1,15
8,2021-12-01,Lunch,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
9,2021-12-01,Dinner,"Cucumber, 0.25 cucumber",11,3,0,0,2,1
10,2021-12-01,Dinner,"Green bell pepper, 0.5 medium",12,3,0,1,2,1
11,2021-12-01,Dinner,"tomato, 0.5 medium",13,3,0,1,10,2
12,2021-12-01,Dinner,"Green leaf lettuce, 1 cup",5,1,0,0,10,0
13,2021-12-01,Dinner,"Weaver chicken breast nuggets, 4",190,12,11,10,630,0
14,2021-12-01,Dinner,"Kens steakhouse caesar, 2 tbsp",170,1,18,1,250,1
15,2021-12-01,Dinner,avocado,240,13,22,3,11,1
16,2021-12-01,Snacks,roasted cashews - 10,51,3,1,2,3,1
0,2021-12-02,Breakfast,"Noosa - vanilla bean, 8 oz",280,32,12,12,130,32
1,2021-12-02,Breakfast,Raspberries - 0.5 cup,32,7,0,1,1,3
2,2021-12-02,Lunch,Yogurt Fruit Granole Parfait,260,53,2,7,150,46
3,2021-12-02,Dinner,Cheese Lovers Tortelloni,810,108,30,33,1560,3
4,2021-12-02,Snacks,Roasted Cashews - 10 pieces,101,6,2,3,5,1
5,2021-12-02,Snacks,Roasted Cashews - 10 pieces,101,6,2,3,5,1
0,2021-12-03,Breakfast,Raspberries - 0.5 cup,32,7,0,1,1,3
1,2021-12-03,Breakfast,banana,105,27,0,1,1,14
2,2021-12-03,Lunch,"Sicilian pizza, 1 slice",319,43,11,12,668,0
3,2021-12-03,Lunch,"Sicilian pizza, 1 slice",319,43,11,12,668,0
4,2021-12-03,Lunch,"Sicilian pizza, 1 slice",319,43,11,12,668,0
5,2021-12-03,Lunch,Arancini,380,43,17,12,458,6
6,2021-12-03,Dinner,"Trader Joes - Chicken Drumellas, 8",380,24,18,30,480,0
7,2021-12-03,Snack,"Blueberries, 1 cup",84,21,0,1,1,15
8,2021-12-03,Snack,Iced Coffee,5,0,0,1,9,0
9,2021-12-03,Snack,Iced Coffee,5,0,0,1,9,0
0,2021-12-04,Breakfast,banana,105,27,0,1,1,14
1,2021-12-04,Lunch,"Anerican cheese, 2 slices",208,2,9,10,936,2
2,2021-12-04,Lunch,"Anerican cheese, 2 slices",208,2,9,10,936,2
3,2021-12-04,Lunch,"Oat Nut bread, 2 slices",220,36,4,8,260,6
4,2021-12-04,Lunch,"Oat Nut bread, 2 slices",220,36,4,8,260,6
5,2021-12-04,Dinner,Trader Joes - chicken chow mein,400,78,3,18,1920,12
6,2021-12-04,Snacks,banana,105,27,0,1,1,14
7,2021-12-04,Snacks,"protein powder, 0.25 cup",33,6,1,22,0,2

## Week 2

In [45]:
mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM MyFitnessPal.food_12_05")

myresult_12_05 = mycursor.fetchall()
df_12_05 = pd.DataFrame(myresult_12_05, columns=['Date', 'Meal', 'Food', 'Calories', 'Carbs','Fat','Protein','Sodium','Sugar'])
myresult_12_05

[(datetime.date(2021, 12, 5), 'Breakfast', 'banana', 105, 27, 0, 1, 1, 14),
 (datetime.date(2021, 12, 5),
  'Lunch',
  'Blueberries, 1 cup',
  84,
  21,
  0,
  1,
  1,
  15),
 (datetime.date(2021, 12, 5),
  'Lunch',
  'Raspberries - 0.5 cup',
  32,
  7,
  0,
  1,
  1,
  3),
 (datetime.date(2021, 12, 5), 'Lunch', 'baby carrots, 15', 54, 12, 0, 1, 6, 7),
 (datetime.date(2021, 12, 5),
  'Lunch',
  'Josephs - avocado hummus, 2 tbsp',
  60,
  3,
  5,
  1,
  105,
  0),
 (datetime.date(2021, 12, 5),
  'Dinner',
  'Cheese Lovers Tortelloni',
  810,
  108,
  30,
  33,
  1560,
  3),
 (datetime.date(2021, 12, 5),
  'Snacks',
  'Roasted Cashews - 10 pieces',
  101,
  6,
  2,
  3,
  5,
  1),
 (datetime.date(2021, 12, 5),
  'Snacks',
  'Aurora cranberry health mix, 0.25 cup',
  145,
  21,
  7,
  3,
  3,
  13),
 (datetime.date(2021, 12, 5),
  'Snacks',
  'Dired Kiwi, 4 pieces',
  110,
  25,
  0,
  1,
  0,
  15),
 (datetime.date(2021, 12, 5),
  'Snacks',
  'Oat Milk, Dark Chocolate, 1 cup',
  140,
  31,
  2,
  3,
  135,
  12),
 (datetime.date(2021, 12, 5),
  'Snacks',
  'Oat Milk, Dark Chocolate, 1 cup',
  140,
  31,
  2,
  3,
  135,
  12)]

In [10]:
df_week1.head()

,Date,Meal,Food,Calories,Carbs,Fat,Protein,Sodium,Sugar
0,2021-12-01,Breakfast,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
1,2021-12-01,Breakfast,"Oat Milk, Dark Chocolate, 1 cup",140,31,2,3,135,12
2,2021-12-01,Breakfast,banana,105,27,0,1,1,14
3,2021-12-01,Breakfast,"Noosa - vanilla bean, 8 oz",280,32,12,12,130,32
4,2021-12-01,Breakfast,Blueberries - 0.5 cup,42,11,0,1,1,7

In [69]:
mydb_food = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Boston1429$$",
  database='MyFitnessPal'
)

mycursor2 = mydb_food.cursor()

mycursor2.execute("Show tables;")
 
food_file_list = mycursor2.fetchall()
food_file_list

[('food_12_01',),
 ('food_12_02',),
 ('food_12_03',),
 ('food_12_04',),
 ('food_12_05',),
 ('food_12_06',),
 ('food_12_07',),
 ('food_12_08',),
 ('food_12_09',),
 ('food_12_10',),
 ('food_12_11',),
 ('food_12_12',),
 ('food_12_13',),
 ('food_12_14',),
 ('food_12_15',),
 ('food_12_16',),
 ('food_12_17',),
 ('food_12_18',),
 ('food_12_19',),
 ('food_12_20',),
 ('food_12_21',),
 ('food_12_22',),
 ('food_12_23',),
 ('food_12_24',),
 ('food_12_25',)]

In [22]:
elements_remove = [('food_11_30_2021',),('food_database',),('food_diary',),('myfitnesspal',)]


filtered_list = []

for file in food_file_list:
    if file not in elements_remove:
        filtered_list.append(file)
filtered_list

[('food_12_01',),
 ('food_12_02',),
 ('food_12_03',),
 ('food_12_04',),
 ('food_12_05',),
 ('food_12_06',),
 ('food_12_07',),
 ('food_12_08',),
 ('food_12_09',),
 ('food_12_10',),
 ('food_12_11',),
 ('food_12_12',),
 ('food_12_13',),
 ('food_12_14',),
 ('food_12_15',),
 ('food_12_16',),
 ('food_12_17',),
 ('food_12_18',),
 ('food_12_19',),
 ('food_12_20',),
 ('food_12_21',),
 ('food_12_22',),
 ('food_12_23',),
 ('food_12_24',),
 ('food_12_25',)]

In [84]:
import MySQLdb

connection = MySQLdb.connect(
                host = 'localhost',
                user = 'myself',
                passwd = 'mysecret')
mycursor = mydb_food.cursor()




#mycursor.execute("USE MyFitnessPal") # select the database

mycursor.execute("SHOW TABLES") 
mycursor

ModuleNotFoundError: No module named 'MySQLdb'

In [83]:
type(filtered_list)

list