In [131]:
from datetime import date
import quandl
quandl.ApiConfig.api_key = 'Hu3ZHysZhH1VrPCHA6ym'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [132]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 200)
pd.set_option('display.min_rows', 20)

In [133]:
df_SP500 = pd.read_csv('/Users/brendan/Desktop/Python/Quandl/constituents.csv')

In [134]:
df_SP500.head()

  Symbol                 Name       Sector
0    MMM                   3M  Industrials
1    AOS          A. O. Smith  Industrials
2    ABT  Abbott Laboratories  Health Care
3   ABBV               AbbVie  Health Care
4   ABMD              Abiomed  Health Care

In [135]:
tickers_SP500 = list(df_SP500['Symbol'])

In [136]:
df_SP500['Sector'].value_counts()

Industrials               74
Information Technology    74
Financials                65
Health Care               64
Consumer Discretionary    63
Consumer Staples          32
Real Estate               29
Utilities                 28
Materials                 28
Communication Services    27
Energy                    21
Name: Sector, dtype: int64

In [137]:
df_SP500_industrials = df_SP500[df_SP500['Sector']=='Industrials']
df_SP500_tech = df_SP500[df_SP500['Sector']=='Information Technology']
df_SP500_healthcare = df_SP500[df_SP500['Sector']=='Health Care']
df_SP500_consumer = df_SP500[df_SP500['Sector']=='Consumer Discretionary']
df_SP500_comm = df_SP500[df_SP500['Sector']=='Communication Services']

In [138]:
# ticker list
tickers_industrials = list(df_SP500_industrials['Symbol'])
tickers_tech = list(df_SP500_tech['Symbol'])
tickers_healthcare = list(df_SP500_healthcare['Symbol'])
tickers_consumer = list(df_SP500_consumer['Symbol'])
tickers_comm = list(df_SP500_comm['Symbol'])

## Tech

In [139]:
prices_06_03_2022 = pd.read_csv('/Users/brendan/Desktop/Python/Quandl/quandl_prices_06_03_2022.csv')

In [140]:
len(prices_06_03_2022)

10000

In [141]:
prices_06_03_2022_df = prices_06_03_2022[prices_06_03_2022['date']=='2022-06-03']
len(prices_06_03_2022_df)

10

In [142]:
data = quandl.get_table("SHARADAR/SP500", paginate=True)

In [143]:
data.head()

,date,action,ticker,name,contraticker,contraname,note
None,,,,,,,
0,2022-06-02,current,ZTS,ZOETIS INC,N/A,N/A,None
1,2022-06-02,current,ZION,ZIONS BANCORPORATION NATIONAL ASSOCIATION,N/A,N/A,None
2,2022-06-02,current,ZBRA,ZEBRA TECHNOLOGIES CORP,N/A,N/A,None
3,2022-06-02,current,ZBH,ZIMMER BIOMET HOLDINGS INC,N/A,N/A,None
4,2022-06-02,current,YUM,YUM BRANDS INC,N/A,N/A,None

In [144]:
data2 = pd.read_csv('/Users/brendan/Desktop/Python/June 2022/SHARADAR_DAILY_3_06_03_2022.csv')

In [145]:
data2[data2['date']=='2022-06-02'].head()

,ticker,date,lastupdated,ev,evebit,evebitda,marketcap,pb,pe,ps
7394501,ARIZ,2022-06-02,2022-06-02,87.6,NaN,NaN,87.9,-38.0,NaN,NaN
7394502,ARKO,2022-06-02,2022-06-02,2924.2,19.1,11.7,1108.8,4.6,15.7,0.1
7394503,ARKR,2022-06-02,2022-06-02,131.0,6.4,5.3,66.3,1.2,5.2,0.4
7394504,ARL,2022-06-02,2022-06-02,651.0,28.3,17.4,353.6,1.4,-103.8,9.3
7498250,A,2022-06-02,2022-06-02,40282.2,26.7,21.9,38563.2,7.5,30.5,5.9

In [146]:
data3 = pd.read_csv('/Users/brendan/Desktop/Python/June 2022/SHARADAR_SEP_06_03_2022.csv')

In [147]:
data3[data3['date']=='2022-06-02'].head()

,ticker,date,open,high,low,close,volume,closeadj,closeunadj,lastupdated
8568340,AAC.U,2022-06-02,9.81,9.840,9.81,9.84,422.0,9.84,9.84,2022-06-02
8568341,AAC.WS,2022-06-02,0.24,0.240,0.24,0.24,5428.0,0.24,0.24,2022-06-02
8568342,AACG,2022-06-02,0.97,1.035,0.97,1.03,15743.0,1.03,1.03,2022-06-02
8568343,AACI,2022-06-02,9.88,9.890,9.88,9.89,14278.0,9.89,9.89,2022-06-02
8568344,AACIU,2022-06-02,9.93,9.930,9.93,9.93,500.0,9.93,9.93,2022-06-02

In [148]:
SP500_metrics = data2[data2['ticker'].isin(tickers_SP500)]
SP500_metrics_06_02_2022 = SP500_metrics[SP500_metrics['date']=='2022-06-02']

SP500_prices = data3[data3['ticker'].isin(tickers_SP500)]
SP500_prices_06_02_2022 = SP500_prices[SP500_prices['date']=='2022-06-02']

In [149]:
len(SP500_prices_06_02_2022), len(SP500_metrics_06_02_2022)

(496, 491)

In [150]:
SP500_metrics_06_02_2022.head()

,ticker,date,lastupdated,ev,evebit,evebitda,marketcap,pb,pe,ps
7498250,A,2022-06-02,2022-06-02,40282.2,26.7,21.9,38563.2,7.5,30.5,5.9
7498257,AAL,2022-06-02,2022-06-02,55874.5,-47.8,47.9,11340.5,-1.3,-4.8,0.3
7498263,AAP,2022-06-02,2022-06-02,14966.7,19.1,14.2,11587.7,4.0,20.3,1.0
7498264,AAPL,2022-06-02,2022-06-02,2539244.2,20.9,19.1,2447361.2,36.3,24.0,6.3
7498272,ABBV,2022-06-02,2022-06-02,326699.4,20.0,13.2,259323.4,15.9,20.8,4.6

In [151]:
SP500_prices_06_02_2022.head()

,ticker,date,open,high,low,close,volume,closeadj,closeunadj,lastupdated
8568536,AIZ,2022-06-02,178.35,179.95,176.705,179.93,420613.0,179.93,179.93,2022-06-02
8568570,ALLE,2022-06-02,112.62,114.37,112.010,114.11,574690.0,114.11,114.11,2022-06-02
8568815,AVB,2022-06-02,207.60,209.28,204.290,208.97,609325.0,208.97,208.97,2022-06-02
8569043,BR,2022-06-02,145.16,147.65,143.900,147.63,302687.0,147.63,147.63,2022-06-02
8569374,EXR,2022-06-02,178.35,179.97,174.870,179.83,584510.0,179.83,179.83,2022-06-02

In [152]:
SP500_06_02_2022 = pd.merge(SP500_metrics_06_02_2022, SP500_prices_06_02_2022,on='ticker')

In [153]:
SP500_06_02_2022 = SP500_06_02_2022.drop(['lastupdated_x','lastupdated_y', 'date_y'],axis=1)
SP500_06_02_2022.head()

,ticker,date_x,ev,evebit,evebitda,marketcap,pb,pe,ps,open,high,low,close,volume,closeadj,closeunadj
0,A,2022-06-02,40282.2,26.7,21.9,38563.2,7.5,30.5,5.9,122.96,129.19,122.300,129.10,1444412.0,129.10,129.10
1,AAL,2022-06-02,55874.5,-47.8,47.9,11340.5,-1.3,-4.8,0.3,17.27,17.51,17.175,17.46,23195134.0,17.46,17.46
2,AAP,2022-06-02,14966.7,19.1,14.2,11587.7,4.0,20.3,1.0,188.45,191.25,185.895,191.09,729004.0,191.09,191.09
3,AAPL,2022-06-02,2539244.2,20.9,19.1,2447361.2,36.3,24.0,6.3,147.83,151.27,146.860,151.21,72095989.0,151.21,151.21
4,ABBV,2022-06-02,326699.4,20.0,13.2,259323.4,15.9,20.8,4.6,146.65,147.07,142.900,146.75,5998940.0,146.75,146.75

## 1 day

In [154]:
SP500_metrics = data2[data2['ticker'].isin(tickers_SP500)]
SP500_metrics_06_01_2022 = SP500_metrics[SP500_metrics['date']=='2022-06-01']

SP500_prices = data3[data3['ticker'].isin(tickers_SP500)]
SP500_prices_06_01_2022 = SP500_prices[SP500_prices['date']=='2022-06-01']

SP500_06_01_2022 = pd.merge(SP500_metrics_06_01_2022, SP500_prices_06_01_2022,on='ticker')
SP500_06_01_2022 = SP500_06_01_2022.drop(['lastupdated_x','lastupdated_y', 'date_y'],axis=1)
SP500_06_01_2022.head()

,ticker,date_x,ev,evebit,evebitda,marketcap,pb,pe,ps,open,high,low,close,volume,closeadj,closeunadj
0,A,2022-06-01,38487.0,25.5,20.9,36768.0,7.2,29.1,5.6,127.86,128.98,122.43,123.09,1757618.0,123.09,123.09
1,AAL,2022-06-01,55764.1,-47.7,47.8,11230.1,-1.3,-4.7,0.3,18.07,18.10,16.98,17.29,32525103.0,17.29,17.29
2,AAP,2022-06-01,14758.7,18.9,14.0,11379.7,3.9,20.0,1.0,191.62,192.04,187.29,187.66,728568.0,187.66,187.66
3,AAPL,2022-06-01,2498781.3,20.5,18.8,2406898.3,35.7,23.6,6.2,149.90,151.74,147.68,148.71,74046038.0,148.71,148.71
4,ABBV,2022-06-01,325409.4,19.9,13.2,258033.4,15.8,20.7,4.5,147.79,147.89,144.32,146.02,5597906.0,146.02,146.02

## 1 day return

In [165]:
SP500_prices_06_01_2022 = SP500_06_01_2022[['ticker', 'date_x', 'closeadj']]
SP500_prices_06_02_2022 = SP500_06_02_2022[['ticker', 'date_x', 'closeadj']]
SP500_1day_06_02_2022 = pd.concat([SP500_prices_06_01_2022, SP500_prices_06_02_2022])
SP500_1day_06_02_2022['1_day_%'] = SP500_1day_06_02_2022.groupby(['ticker'])['closeadj'].pct_change()*100
SP500_1day_06_02_2022.dropna()

    ticker      date_x  closeadj   1_day_%
0        A  2022-06-02    129.10  4.882606
1      AAL  2022-06-02     17.46  0.983227
2      AAP  2022-06-02    191.09  1.827774
3     AAPL  2022-06-02    151.21  1.681124
4     ABBV  2022-06-02    146.75  0.499932
5      ABC  2022-06-02    148.21 -1.199920
6     ABMD  2022-06-02    269.63  5.588189
7      ABT  2022-06-02    117.51  2.111575
8      ACN  2022-06-02    306.62  2.668676
9     ADBE  2022-06-02    441.28  5.528984
..     ...         ...       ...       ...
481   WYNN  2022-06-02     66.67  2.364502
482    XEL  2022-06-02     75.48  0.479233
483    XOM  2022-06-02     97.67 -0.173753
484   XRAY  2022-06-02     41.80  7.069672
485    XYL  2022-06-02     86.51  3.295522
486    YUM  2022-06-02    120.30  0.736895
487    ZBH  2022-06-02    122.07  2.339034
488   ZBRA  2022-06-02    347.07  3.742340
489   ZION  2022-06-02     57.10  1.964286
490    ZTS  2022-06-02    172.70  3.400790

[491 rows x 4 columns]