In [123]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
raw_df_2019 = pd.read_csv('AAPL_2019.csv')
raw_df_2020 = pd.read_csv('AAPL_2020.csv')

In [124]:
raw_df_2020.dtypes

ticker        object
date          object
marketcap    float64
ev           float64
evebitda     float64
pe           float64
close        float64
dtype: object

In [125]:
raw_df_2020['EPS'] = raw_df_2020['close']/raw_df_2020['pe']
raw_df_2020['date'] = pd.to_datetime(raw_df_2020['date'])
raw_df_2019['date'] = pd.to_datetime(raw_df_2019['date'])

In [126]:
raw_df_2020['date_1yr_ago'] = raw_df_2020['date'] -timedelta(days=365)

In [127]:
len(raw_df_2020)

253

In [128]:
len(raw_df_2019)

252

In [129]:
AAPL_19_20_df = raw_df_2020.merge(raw_df_2019,how='left',on=['ticker'])
len(AAPL_19_20_df)

63756

In [130]:
AAPL_19_20_df = AAPL_19_20_df.drop_duplicates(subset=['date_x','date_y'], keep=False)
AAPL_19_20_df

,ticker,date_x,marketcap_x,ev_x,evebitda_x,pe_x,close_x,EPS,date_1yr_ago,date_y,marketcap_y,ev_y,evebitda_y,pe_y,close_y
0,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-31,1304755.9,1363958.9,16.7,23.6,73.412
1,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-30,1295300.6,1354503.6,16.5,23.4,72.880
2,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-27,1287658.2,1346861.2,16.5,23.3,72.450
3,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-26,1288155.8,1347358.8,16.5,23.3,72.478
4,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-24,1263078.1,1322281.1,16.2,22.9,71.067
5,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-23,1261887.3,1321090.3,16.1,22.8,71.000
6,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-20,1241626.0,1300829.0,15.9,22.5,69.860
7,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-19,1244203.1,1303406.1,15.9,22.5,70.005
8,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-18,1242959.0,1302162.0,15.9,22.5,69.935
9,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-17,1245944.8,1305147.8,15.9,22.5,70.103
10,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-16,1243492.1,1302695.1,15.9,22.5,69.965
11,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-13,1222555.5,1281758.5,15.7,22.1,68.787
12,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-12,1206168.7,1265371.7,15.5,21.8,67.865
13,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-11,1203094.0,1262297.0,15.4,21.8,67.692
14,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-10,1192927.8,1252130.8,15.3,21.6,67.120
15,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-09,1185996.3,1245199.3,15.2,21.5,66.730
16,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-06,1202827.4,1262030.4,15.4,21.8,67.677
17,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-05,1180042.3,1239245.3,15.1,21.4,66.395
18,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-04,1162980.2,1222183.2,14.9,21.0,65.435
19,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-03,1152796.2,1211999.2,14.8,20.9,64.862
20,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-12-02,1173732.9,1232935.9,15.1,21.2,66.040
21,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-29,1187471.5,1246674.5,15.2,21.5,66.812
22,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-27,1190084.1,1249287.1,15.3,21.5,66.960
23,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-26,1174319.4,1233522.4,15.1,21.3,66.073
24,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-25,1183561.4,1242764.4,15.2,21.4,66.593
25,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-22,1163157.9,1222360.9,14.9,21.1,65.445
26,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-21,1164171.0,1223374.0,14.9,21.1,65.502
27,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-20,1169414.0,1228617.0,15.0,21.2,65.797
28,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-19,1183205.9,1242408.9,15.2,21.4,66.573
29,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.690,3.376336,2020-01-01,2019-11-18,1186796.1,1245999.1,15.2,21.5,66.775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63726,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-02-11,798919.3,868878.3,10.3,13.4,42.358
63727,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-02-08,803521.4,873480.4,10.3,13.5,42.602
63728,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-02-07,806030.0,875989.0,10.3,13.6,42.735
63729,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-02-06,821590.4,891549.4,10.5,13.8,43.560
63730,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-02-05,821307.5,891266.5,10.5,13.8,43.545
63731,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-02-04,807501.1,877460.1,10.4,13.6,42.812
63732,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-02-01,785188.4,855147.4,10.1,13.2,41.630
63733,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-31,784811.2,854770.2,10.1,13.2,41.610
63734,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-30,779209.5,849168.5,10.0,13.1,41.312
63735,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-29,734018.2,822588.2,9.5,12.3,38.670
63736,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-28,741705.7,830275.7,9.5,12.5,39.075
63737,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-25,748634.0,837204.0,9.6,12.6,39.440
63738,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-24,724622.3,813192.3,9.3,12.2,38.175
63739,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-23,730411.7,818981.7,9.4,12.3,38.480
63740,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-22,727469.5,816039.5,9.4,12.2,38.325
63741,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-18,744173.3,832743.3,9.6,12.5,39.205
63742,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-17,739617.7,828187.7,9.5,12.4,38.965
63743,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-16,735252.0,823822.0,9.5,12.4,38.735
63744,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-15,726368.6,814938.6,9.4,12.2,38.267
63745,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-14,711809.7,800379.7,9.2,12.0,37.500
63746,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-11,722667.2,811237.2,9.3,12.1,38.072
63747,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-10,729842.2,818412.2,9.4,12.3,38.450
63748,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-09,727526.5,816096.5,9.4,12.2,38.328
63749,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-08,715378.2,803948.2,9.2,12.0,37.688
63750,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-07,701996.2,790566.2,9.1,11.8,36.983
63751,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-04,703552.7,792122.7,9.1,11.8,37.065
63752,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-03,674738.7,763308.7,8.8,11.3,35.547
63753,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-02,749393.3,837963.3,9.6,12.6,39.480
63754,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-05-08,933558.1,1008200.1,12.2,16.3,50.725
63755,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-05-02,962324.0,1036966.0,12.5,16.8,52.288

In [131]:
AAPL_19_20_df['date_x_day'] = AAPL_19_20_df['date_x'].dt.day_name()
AAPL_19_20_df['date_1_yr'] = AAPL_19_20_df['date_1yr_ago'].dt.day_name()
AAPL_19_20_df.tail()

,ticker,date_x,marketcap_x,ev_x,evebitda_x,pe_x,close_x,EPS,date_1yr_ago,date_y,marketcap_y,ev_y,evebitda_y,pe_y,close_y,date_x_day,date_1_yr
63751,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-04,703552.7,792122.7,9.1,11.8,37.065,Wednesday,Tuesday
63752,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-03,674738.7,763308.7,8.8,11.3,35.547,Wednesday,Tuesday
63753,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-01-02,749393.3,837963.3,9.6,12.6,39.480,Wednesday,Tuesday
63754,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-05-08,933558.1,1008200.1,12.2,16.3,50.725,Wednesday,Tuesday
63755,AAPL,2020-04-22,1208070.0,1276591.0,15.3,21.0,69.025,3.286905,2019-04-23,2019-05-02,962324.0,1036966.0,12.5,16.8,52.288,Wednesday,Tuesday

In [132]:
AAPL_19_20_df.head()

,ticker,date_x,marketcap_x,ev_x,evebitda_x,pe_x,close_x,EPS,date_1yr_ago,date_y,marketcap_y,ev_y,evebitda_y,pe_y,close_y,date_x_day,date_1_yr
0,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.69,3.376336,2020-01-01,2019-12-31,1304755.9,1363958.9,16.7,23.6,73.412,Thursday,Wednesday
1,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.69,3.376336,2020-01-01,2019-12-30,1295300.6,1354503.6,16.5,23.4,72.880,Thursday,Wednesday
2,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.69,3.376336,2020-01-01,2019-12-27,1287658.2,1346861.2,16.5,23.3,72.450,Thursday,Wednesday
3,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.69,3.376336,2020-01-01,2019-12-26,1288155.8,1347358.8,16.5,23.3,72.478,Thursday,Wednesday
4,AAPL,2020-12-31,2255969.1,2330389.1,28.8,39.3,132.69,3.376336,2020-01-01,2019-12-24,1263078.1,1322281.1,16.2,22.9,71.067,Thursday,Wednesday

In [133]:
s = pd.bdate_range("2020-01-02", "2020-12-31")
y = pd.bdate_range("2021-01-01", "2021-12-31")
x = pd.bdate_range("2019-01-01", "2019-12-31")
len(s), len(y),len(x)

(261, 261, 261)

In [134]:
AAPL = pd.DataFrame()

AAPL['2019'] = pd.bdate_range("2019-01-01", "2019-12-31")
AAPL['2020'] = pd.bdate_range("2020-01-02", "2020-12-31")
AAPL['2021'] = pd.bdate_range("2021-01-01", "2021-12-31")


AAPL.columns

Index(['2019', '2020', '2021'], dtype='object')

In [135]:
x_2019 = np.linspace(1,len(AAPL['2019']),num=len(AAPL['2019'])).reshape([len(x_2019),1])
x_2020 = np.linspace(1,len(AAPL['2019']),num=len(AAPL['2020'])).reshape([len(x_2020),1])
x_2021 = np.linspace(1,len(AAPL['2019']),num=len(AAPL['2021'])).reshape([len(x_2021),1])

In [138]:
AAPL['BD_2019'] = x_2019
AAPL['BD_2020'] = x_2020
AAPL['BD_2021'] = x_2021
AAPL['Ticker'] = 'AAPL'


#AAPL['2020_px'] = 
#AAPL['2020_px'] = 


AAPL.head()

        2019       2020       2021  BD_2019  BD_2020  BD_2021 Ticker
0 2019-01-01 2020-01-02 2021-01-01      1.0      1.0      1.0   AAPL
1 2019-01-02 2020-01-03 2021-01-04      2.0      2.0      2.0   AAPL
2 2019-01-03 2020-01-06 2021-01-05      3.0      3.0      3.0   AAPL
3 2019-01-04 2020-01-07 2021-01-06      4.0      4.0      4.0   AAPL
4 2019-01-07 2020-01-08 2021-01-07      5.0      5.0      5.0   AAPL

In [148]:
df3 = pd.merge(AAPL, raw_df_2019, left_on='Ticker',right_on='date')[['Ticker','2019','BD_2019', 'close']]

ValueError: You are trying to merge on object and datetime64[ns] columns. If you wish to proceed you should use pd.concat

In [149]:
df3

      Ticker       2019  BD_2019   close
0       AAPL 2019-01-01      1.0  73.412
1       AAPL 2019-01-01      1.0  72.880
2       AAPL 2019-01-01      1.0  72.450
3       AAPL 2019-01-01      1.0  72.478
4       AAPL 2019-01-01      1.0  71.067
...      ...        ...      ...     ...
65767   AAPL 2019-12-31    261.0  37.065
65768   AAPL 2019-12-31    261.0  35.547
65769   AAPL 2019-12-31    261.0  39.480
65770   AAPL 2019-12-31    261.0  50.725
65771   AAPL 2019-12-31    261.0  52.288

[65772 rows x 4 columns]