In [36]:
import pandas as pd

In [37]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 200)
pd.set_option('display.min_rows', 20)

In [38]:
avgo_raw = pd.read_excel('AVGO.xlsx', sheet_name='Python')
avgo_raw.head()

,Unnamed: 0,2008-04-30 00:00:00,2008-07-31 00:00:00,2008-10-31 00:00:00,2009-01-31 00:00:00,2009-04-30 00:00:00,2009-07-31 00:00:00,2009-10-31 00:00:00,2010-01-31 00:00:00,2010-04-30 00:00:00,2010-07-31 00:00:00,2010-10-31 00:00:00,2011-01-31 00:00:00,2011-04-30 00:00:00,2011-07-31 00:00:00,2011-10-31 00:00:00,2012-01-31 00:00:00,2012-04-29 00:00:00,2012-07-30 00:00:00,2012-10-30 00:00:00,2013-01-30 00:00:00,2013-04-29 00:00:00,2013-07-30 00:00:00,2013-10-30 00:00:00,2014-01-30 00:00:00,2014-04-29 00:00:00,2014-07-30 00:00:00,2014-10-30 00:00:00,2015-01-30 00:00:00,2015-04-29 00:00:00,2015-07-30 00:00:00,2015-10-30 00:00:00,2016-01-30 00:00:00,2016-04-28 00:00:00,2016-07-29 00:00:00,2016-10-29 00:00:00,2017-01-29 00:00:00,2017-04-28 00:00:00,2017-07-29 00:00:00,2017-10-29 00:00:00,2018-01-29 00:00:00,2018-04-28 00:00:00,2018-07-29 00:00:00,2018-10-29 00:00:00,2019-01-29 00:00:00,2019-04-28 00:00:00,2019-07-29 00:00:00,2019-10-29 00:00:00,2020-01-29 00:00:00,2020-04-27 00:00:00,2020-07-28 00:00:00,2020-10-28 00:00:00,2021-01-28 00:00:00,2021-04-27 00:00:00,2021-07-28 00:00:00,2021-10-28 00:00:00,2022-01-28 00:00:00,2022-04-27 00:00:00,2022-07-28 00:00:00,2022-10-28 00:00:00,2023-01-28 00:00:00,2023-04-27 00:00:00,2023-07-28 00:00:00,2023-10-28 00:00:00,2024-01-28 00:00:00,2024-04-26 00:00:00,2024-07-27 00:00:00,2024-10-27 00:00:00,2025-01-27 00:00:00
0,NaN,1Q08,2Q08,3Q08,4Q08,1Q09,2Q09,3Q09,4Q09,1Q10,2Q10,3Q10,4Q10,1Q11,2Q11,3Q11,4Q11,1Q12,2Q12,3Q12,4Q12,1Q13,2Q13,3Q13,4Q13,1Q14,2Q14,3Q14,4Q14,1Q15,2Q15,3Q15,4Q15,1Q16,2Q16,3Q16,4Q16,1Q17,2Q17,3Q17,4Q17,1Q18,2Q18,3Q18,4Q18,1Q19,2Q19,3Q19,4Q19,1Q20,2Q20,3Q20,4Q20,1Q21,2Q21,3Q21,4Q21,1Q22,2Q22E,3Q22E,4Q22E,1Q23E,2Q23E,3Q23E,4Q23E,1Q24E,2Q24E,3Q24E,4Q24E
1,Revenue,411,439,447,368,325,363,428,456,515,550,572,550,560,603,623,563,577,606,618,576,562,644,738,709,701,1287,1610,1657,1645,1750,1853,1782,3562,3802,4146,4149,4201,4467,4848,5331,5017,5066,5448,5789,5517,5515,5776,5858,5742,5821,6467,6655,6610,6778,7407,7706,8103,8462.74,8944.9318,9216.879754,8893.035766,8803.905409,8687.0273,8478.746208,8389.971284,8748.569561,9504.312213,9267.339725
2,Revenue % q/q,0,0.068127,0.018223,-0.176734,-0.116848,0.116923,0.179063,0.065421,0.129386,0.067961,0.04,-0.038462,0.018182,0.076786,0.033167,-0.096308,0.024867,0.05026,0.019802,-0.067961,-0.024306,0.145907,0.145963,-0.039295,-0.011283,0.835949,0.250971,0.029193,-0.007242,0.06383,0.058857,-0.038316,0.998878,0.067378,0.090479,0.000724,0.012533,0.063318,0.085292,0.099629,-0.058901,0.009767,0.075405,0.062592,-0.046986,-0.000363,0.047325,0.014197,-0.019802,0.013758,0.110977,0.029071,-0.006762,0.025416,0.0928,0.040367,0.051518,0.044396,0.056978,0.030402,-0.035136,-0.010022,-0.013276,-0.023976,-0.01047,0.042741,0.086385,-0.024933
3,Revenue % y/y,0,0,0,0,-0.209246,-0.173121,-0.042506,0.23913,0.584615,0.515152,0.336449,0.20614,0.087379,0.096364,0.089161,0.023636,0.030357,0.004975,-0.008026,0.023091,-0.025997,0.062706,0.194175,0.230903,0.247331,0.998447,1.181572,1.337094,1.346648,0.359751,0.150932,0.075438,1.16535,1.172571,1.237453,1.328283,0.179394,0.174908,0.16932,0.284888,0.194239,0.134094,0.123762,0.085913,0.099661,0.08863,0.060206,0.011919,0.040783,0.055485,0.119633,0.136053,0.151167,0.164405,0.145353,0.157926,0.22587,0.24856,0.207632,0.196065,0.097499,0.040314,-0.028832,-0.080085,-0.056568,-0.006285,0.094081,0.093008
4,COGS,237,251,263,204,210,205,236,247,268,271,282,265,271,292,305,279,284,297,304,286,276,319,368,346,323,558,677,689,653,694,711,699,1437,1520,1638,1573,1564,1658,1797,1897,1696,1680,1746,1692,1587,1646,1782,1624,1587,1537,1747,1811,1696,1726,1917,1921,1953,2042.935,2173.48295,2216.469939,2125.508942,2113.226352,2094.006825,2011.936552,1979.742821,2079.39239,2278.328053,2189.084931

In [40]:
avgo_raw = avgo_raw.rename(columns={'Unnamed: 0':'Metric'})
avgo_raw.columns = avgo_raw.iloc[0]
avgo_raw.head()

,nan,1Q08,2Q08,3Q08,4Q08,1Q09,2Q09,3Q09,4Q09,1Q10,2Q10,3Q10,4Q10,1Q11,2Q11,3Q11,4Q11,1Q12,2Q12,3Q12,4Q12,1Q13,2Q13,3Q13,4Q13,1Q14,2Q14,3Q14,4Q14,1Q15,2Q15,3Q15,4Q15,1Q16,2Q16,3Q16,4Q16,1Q17,2Q17,3Q17,4Q17,1Q18,2Q18,3Q18,4Q18,1Q19,2Q19,3Q19,4Q19,1Q20,2Q20,3Q20,4Q20,1Q21,2Q21,3Q21,4Q21,1Q22,2Q22E,3Q22E,4Q22E,1Q23E,2Q23E,3Q23E,4Q23E,1Q24E,2Q24E,3Q24E,4Q24E
0,NaN,1Q08,2Q08,3Q08,4Q08,1Q09,2Q09,3Q09,4Q09,1Q10,2Q10,3Q10,4Q10,1Q11,2Q11,3Q11,4Q11,1Q12,2Q12,3Q12,4Q12,1Q13,2Q13,3Q13,4Q13,1Q14,2Q14,3Q14,4Q14,1Q15,2Q15,3Q15,4Q15,1Q16,2Q16,3Q16,4Q16,1Q17,2Q17,3Q17,4Q17,1Q18,2Q18,3Q18,4Q18,1Q19,2Q19,3Q19,4Q19,1Q20,2Q20,3Q20,4Q20,1Q21,2Q21,3Q21,4Q21,1Q22,2Q22E,3Q22E,4Q22E,1Q23E,2Q23E,3Q23E,4Q23E,1Q24E,2Q24E,3Q24E,4Q24E
1,Revenue,411,439,447,368,325,363,428,456,515,550,572,550,560,603,623,563,577,606,618,576,562,644,738,709,701,1287,1610,1657,1645,1750,1853,1782,3562,3802,4146,4149,4201,4467,4848,5331,5017,5066,5448,5789,5517,5515,5776,5858,5742,5821,6467,6655,6610,6778,7407,7706,8103,8462.74,8944.9318,9216.879754,8893.035766,8803.905409,8687.0273,8478.746208,8389.971284,8748.569561,9504.312213,9267.339725
2,Revenue % q/q,0,0.068127,0.018223,-0.176734,-0.116848,0.116923,0.179063,0.065421,0.129386,0.067961,0.04,-0.038462,0.018182,0.076786,0.033167,-0.096308,0.024867,0.05026,0.019802,-0.067961,-0.024306,0.145907,0.145963,-0.039295,-0.011283,0.835949,0.250971,0.029193,-0.007242,0.06383,0.058857,-0.038316,0.998878,0.067378,0.090479,0.000724,0.012533,0.063318,0.085292,0.099629,-0.058901,0.009767,0.075405,0.062592,-0.046986,-0.000363,0.047325,0.014197,-0.019802,0.013758,0.110977,0.029071,-0.006762,0.025416,0.0928,0.040367,0.051518,0.044396,0.056978,0.030402,-0.035136,-0.010022,-0.013276,-0.023976,-0.01047,0.042741,0.086385,-0.024933
3,Revenue % y/y,0,0,0,0,-0.209246,-0.173121,-0.042506,0.23913,0.584615,0.515152,0.336449,0.20614,0.087379,0.096364,0.089161,0.023636,0.030357,0.004975,-0.008026,0.023091,-0.025997,0.062706,0.194175,0.230903,0.247331,0.998447,1.181572,1.337094,1.346648,0.359751,0.150932,0.075438,1.16535,1.172571,1.237453,1.328283,0.179394,0.174908,0.16932,0.284888,0.194239,0.134094,0.123762,0.085913,0.099661,0.08863,0.060206,0.011919,0.040783,0.055485,0.119633,0.136053,0.151167,0.164405,0.145353,0.157926,0.22587,0.24856,0.207632,0.196065,0.097499,0.040314,-0.028832,-0.080085,-0.056568,-0.006285,0.094081,0.093008
4,COGS,237,251,263,204,210,205,236,247,268,271,282,265,271,292,305,279,284,297,304,286,276,319,368,346,323,558,677,689,653,694,711,699,1437,1520,1638,1573,1564,1658,1797,1897,1696,1680,1746,1692,1587,1646,1782,1624,1587,1537,1747,1811,1696,1726,1917,1921,1953,2042.935,2173.48295,2216.469939,2125.508942,2113.226352,2094.006825,2011.936552,1979.742821,2079.39239,2278.328053,2189.084931