In [1]:
import pandas as pd
import glob
from datetime import datetime

In [2]:
files =glob.glob('*csv')

In [3]:
from ticker_convert import ticker_convert

In [4]:
files
SP500_tickers_list = []
for i in files:
    x = i.replace(".csv", "")
    SP500_tickers_list.append(x)
SP500_tickers_list

['CSCO',
 'TER',
 'V',
 'QRVO',
 'FOX',
 'FLT',
 'SWKS',
 'ENPH',
 'MCHP',
 'CDNS',
 'CHTR',
 'T',
 'DISH',
 'APH',
 'MSI',
 'GPN',
 'WBD',
 'DXC',
 'PARA',
 'ADI',
 'ADBE',
 'NOW',
 'NWS',
 'ZBRA',
 'BR',
 'STX',
 'IPG',
 'CDAY',
 'ORCL',
 'INTU',
 'PAYC',
 'IPGP',
 'INTC',
 'GLW',
 'TXN',
 'FTNT',
 'JNPR',
 'ADSK',
 'WDC',
 'LUMN',
 'PYPL',
 'MSFT',
 'ANSS',
 'IT',
 'ACN',
 'VRSN',
 'HPQ',
 'AMAT',
 'ATVI',
 'EA',
 'AMD',
 'KLAC',
 'NXPI',
 'SEDG',
 'MTCH',
 'NVDA',
 'TYL',
 'HPE',
 'CMCSA',
 'CTXS',
 'PTC',
 'FIS',
 'FB',
 'NLOK',
 'IBM',
 'TWTR',
 'MPWR',
 'DIS',
 'NFLX',
 'OMC',
 'AKAM',
 'GOOGL',
 'ANET',
 'PAYX',
 'FOXA',
 'FFIV',
 'SNPS',
 'GOOG',
 'EPAM',
 'LYV',
 'AVGO',
 'VZ',
 'TEL',
 'JKHY',
 'ADP',
 'TRMB',
 'QCOM',
 'MA',
 'NWSA',
 'TTWO',
 'AAPL',
 'TMUS',
 'NTAP',
 'KEYS',
 'CTSH',
 'MU',
 'CDW',
 'CRM',
 'LRCX']

In [5]:
tickers_df = map(ticker_convert,SP500_tickers_list)
SP500_master_df = []
for i in tickers_df:
    df = pd.DataFrame(i)
    SP500_master_df.append(df)
SP500_master_df = pd.concat(SP500_master_df)

In [6]:
today_date = datetime.now()
date = today_date.strftime('%m/%d/%Y %H:%M:%S')
SP500_master_df['Date'] = date
SP500_master_df.to_csv('output/SP500_master_df.csv')

In [7]:
SP500_master_df.columns

Index(['symbol', 'marketCap', 'enterpriseValue', 'currentPrice',
       'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'earningsGrowth',
       'enterpriseToRevenue', 'enterpriseToEbitda', 'forwardEps',
       'trailingEps', 'priceToSalesTrailing12Months', 'forwardPE',
       'dividendYield', 'Date'],
      dtype='object')

In [8]:
raw_df = pd.read_csv('output/SP500_master_df.csv')
raw_df.columns
raw_df = raw_df.drop('Unnamed: 0', 1)
raw_df = raw_df[['Date','symbol', 'marketCap', 'enterpriseValue', 'currentPrice',
       'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'earningsGrowth',
       'enterpriseToRevenue', 'enterpriseToEbitda', 'forwardEps',
       'trailingEps', 'priceToSalesTrailing12Months', 'forwardPE',
       'dividendYield']]
raw_df

<ipython-input-8-5dbd28508f64>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  raw_df = raw_df.drop('Unnamed: 0', 1)

,Date,symbol,marketCap,enterpriseValue,currentPrice,fiftyTwoWeekHigh,fiftyTwoWeekLow,earningsGrowth,enterpriseToRevenue,enterpriseToEbitda,forwardEps,trailingEps,priceToSalesTrailing12Months,forwardPE,dividendYield
0,06/09/2022 09:57:46,CSCO,189459693568,176401104896,45.1000,64.290000,41.02000,0.076,3.420,10.976,3.55,2.850,3.673052,12.704226,0.0338
1,06/09/2022 09:57:46,TER,16807698432,16478944256,104.9150,168.910000,97.63000,-0.156,4.482,12.765,6.61,5.384,4.571477,15.872163,0.0041
2,06/09/2022 09:57:46,V,450134769664,455228948480,212.7100,252.670000,186.67000,0.234,16.900,23.935,8.37,6.358,16.710650,25.413382,0.0070
3,06/09/2022 09:57:46,QRVO,11568606208,12748570624,109.1100,201.460000,98.23000,-0.247,2.744,7.675,12.73,9.260,2.490168,8.571093,NaN
4,06/09/2022 09:57:46,FOX,18235914240,20840712192,31.3700,40.910000,28.96000,-0.479,1.507,7.181,2.35,1.999,1.318481,13.348937,0.0152
5,06/09/2022 09:57:46,FLT,18833258496,24179396608,243.5100,282.020000,200.78000,0.279,8.021,15.701,17.76,10.594,6.247859,13.711148,NaN
6,06/09/2022 09:57:46,SWKS,17145056256,18794981376,106.5400,197.620000,97.59000,-0.046,3.564,9.056,12.29,8.239,3.251296,8.668837,0.0210
7,06/09/2022 09:57:46,ENPH,27846823936,28547981312,206.2300,282.460000,113.40000,0.703,18.762,110.113,4.27,1.174,18.301172,48.297424,NaN
8,06/09/2022 09:57:46,MCHP,38255022080,46722850816,69.0100,90.000000,63.34000,2.712,6.850,15.458,5.73,2.270,5.608501,12.040139,0.0156
9,06/09/2022 09:57:46,CDNS,43696775168,43414450176,158.4600,192.700000,124.51000,0.269,13.765,41.977,4.43,2.679,13.854479,35.769756,NaN
10,06/09/2022 09:57:46,CHTR,82118647808,178314264576,489.2150,825.620000,410.33000,0.681,3.406,8.590,36.01,27.446,1.568347,13.585532,NaN
11,06/09/2022 09:57:46,T,150947512320,366393458688,21.0850,22.167673,16.63142,-0.364,2.247,6.977,2.54,2.377,0.925888,8.301181,0.0530
12,06/09/2022 09:57:46,DISH,10886097920,31924293632,20.5400,46.310000,17.04000,-0.313,1.802,8.869,1.59,3.480,0.614552,12.918240,NaN
13,06/09/2022 09:57:46,APH,41954914304,45808566272,70.2600,88.450000,65.84000,0.283,4.000,16.944,3.05,2.694,3.663833,23.036066,0.0113
14,06/09/2022 09:57:46,MSI,36456357888,42389913600,217.9140,273.650000,199.24000,0.092,5.113,17.093,11.08,7.300,4.397631,19.667328,0.0142
15,06/09/2022 09:57:46,GPN,35410694144,46827921408,125.7750,196.880000,114.80000,0.314,5.389,13.340,11.12,3.503,4.074874,11.310701,0.0078
16,06/09/2022 09:57:46,WBD,39557492736,23088685056,16.3000,31.880000,16.04000,2.267,1.839,5.999,1.62,1.806,3.149983,10.061728,NaN
17,06/09/2022 09:57:46,DXC,8064712192,11948292096,34.9600,44.180000,27.28000,NaN,0.735,3.900,4.95,2.810,0.495832,7.062626,NaN
18,06/09/2022 09:57:46,PARA,19652816896,33640349696,30.1200,47.460000,26.11000,-0.552,1.180,9.161,2.08,6.143,0.689524,14.480770,0.0314
19,06/09/2022 09:57:46,ADI,86100664320,90288676864,165.6400,191.950000,143.81000,0.307,9.256,21.141,10.06,3.419,8.826512,16.465208,0.0184
20,06/09/2022 09:57:46,ADBE,203267145728,202590896128,430.1950,699.540000,370.27000,0.019,12.551,31.067,16.09,10.068,12.592439,26.736794,NaN
21,06/09/2022 09:57:46,NOW,101115772928,99507978240,504.4187,707.600000,406.47000,-0.098,15.901,139.367,9.36,1.090,16.157843,53.890890,NaN
22,06/09/2022 09:57:46,NWS,10066405376,13518629888,17.3600,25.690000,16.57000,0.071,1.325,10.180,NaN,0.840,0.986612,NaN,0.0112
23,06/09/2022 09:57:46,ZBRA,17316163584,18731913216,329.7450,615.000000,309.00000,-0.092,3.279,16.303,21.96,15.129,3.031541,15.015711,NaN
24,06/09/2022 09:57:46,BR,16963449856,21230432256,144.7060,185.400000,132.68000,0.064,3.848,18.321,7.06,4.663,3.074314,20.496600,0.0176
25,06/09/2022 09:57:46,STX,18214473728,22600167424,84.7800,117.670000,76.28000,0.122,1.876,8.905,9.20,8.148,1.512077,9.215218,0.0331
26,06/09/2022 09:57:46,IPG,12065801216,14878125056,30.6500,39.980000,27.67000,0.739,1.599,8.540,2.88,2.558,1.296366,10.642361,0.0367
27,06/09/2022 09:57:46,CDAY,8516064256,9470296064,55.7900,130.370000,48.93000,NaN,8.745,1229.909,0.82,-0.553,7.863401,68.036590,NaN
28,06/09/2022 09:57:46,ORCL,189309157376,249457328128,70.9512,106.340000,66.72000,-0.500,5.964,13.558,5.25,2.664,4.526004,13.514515,0.0176
29,06/09/2022 09:57:46,INTU,116593704960,120968388608,413.3400,716.860000,339.36000,0.185,9.397,32.881,13.87,8.870,9.057229,29.801010,0.0065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,06/09/2022 09:57:46,OMC,14555588608,18468749312,70.7499,91.610000,65.76000,-0.376,1.294,7.936,7.05,6.049,1.019813,10.035447,0.0386
70,06/09/2022 09:57:46,AKAM,16076987392,18889777152,100.2900,123.250000,93.74000,-0.223,5.363,15.653,6.16,3.723,4.564523,16.280846,NaN
71,06/09/2022 09:57:46,GOOGL,1549234077696,1438076633088,2353.2000,3030.930000,2037.69000,-0.063,5.320,15.005,132.46,110.585,5.730815,17.762342,NaN
72,06/09/2022 09:57:46,ANET,31505932288,28400117760,102.5250,148.570000,85.18000,0.491,8.994,27.120,4.26,2.910,9.977996,24.066900,NaN
73,06/09/2022 09:57:46,PAYX,45078384640,45291053056,124.8650,141.920000,101.73000,0.227,10.072,22.760,4.06,3.740,10.024993,30.754927,0.0249
74,06/09/2022 09:57:46,FOXA,18288365568,22227017728,33.9400,44.950000,31.35000,-0.479,1.607,7.659,3.64,1.999,1.322274,9.324175,0.0141
75,06/09/2022 09:57:46,FFIV,9984531456,9837271040,165.1100,249.000000,151.66000,0.314,3.705,17.751,11.30,5.675,3.760884,14.611505,NaN
76,06/09/2022 09:57:46,SNPS,49475850240,49414664192,323.4350,377.600000,255.02000,0.524,10.383,37.722,9.71,6.417,10.396198,33.309475,NaN
77,06/09/2022 09:57:46,GOOG,1551911223296,1438656233472,2357.7500,3042.000000,2044.16000,-0.063,5.322,15.011,132.72,110.585,5.740718,17.764843,NaN
78,06/09/2022 09:57:46,EPAM,18851291136,17932795904,329.8500,725.400000,168.59000,-0.183,4.322,25.263,12.40,7.810,4.543593,26.600807,NaN
79,06/09/2022 09:57:46,LYV,21272670208,23819089920,93.2750,127.750000,74.23000,NaN,3.061,75.899,1.47,-2.047,2.734049,63.452380,NaN
80,06/09/2022 09:57:46,AVGO,239880241152,261154881536,569.2500,677.760000,455.71000,0.797,8.707,15.514,40.36,20.180,7.997607,14.104311,0.0286
81,06/09/2022 09:57:46,VZ,216974409728,398432632832,51.6650,57.610000,45.55000,-0.139,2.967,8.833,5.56,5.138,1.615595,9.292267,0.0496
82,06/09/2022 09:57:46,TEL,43150286848,46155800576,130.4300,166.440000,119.58000,0.130,2.980,12.549,7.68,7.569,2.786046,16.983072,0.0169
83,06/09/2022 09:57:46,JKHY,13496190976,13936442368,185.2300,205.370000,147.50000,0.224,7.295,26.766,5.27,4.879,7.064223,35.148006,0.0104
84,06/09/2022 09:57:46,ADP,91603566592,93676896256,219.2800,248.960000,192.18000,0.163,5.816,22.195,7.73,6.774,5.686978,28.367400,0.0189
85,06/09/2022 09:57:46,TRMB,16719490048,18266597376,66.8400,96.490000,59.89000,-0.023,4.850,23.032,3.22,1.930,4.439235,20.757763,NaN
86,06/09/2022 09:57:46,QCOM,155455995904,163050799104,138.8000,193.580000,122.17000,0.680,4.153,11.257,13.15,9.761,3.959250,10.555134,0.0211
87,06/09/2022 09:57:46,MA,354040676352,359832354816,361.1300,399.920000,305.61000,0.464,18.086,30.468,12.70,9.610,17.794565,28.435434,0.0054
88,06/09/2022 09:57:46,NWSA,10006197248,13360479232,16.9950,26.870000,16.38000,0.071,1.309,10.061,0.99,0.840,0.980711,17.166668,0.0114
89,06/09/2022 09:57:46,TTWO,21362186240,12198807552,131.8800,195.830000,101.85000,-0.497,3.481,16.845,8.65,3.580,6.095123,15.246244,NaN
90,06/09/2022 09:57:46,AAPL,2400062537728,2464038518784,147.5400,182.940000,125.94000,0.086,6.383,18.862,6.56,6.137,6.217505,22.490852,0.0062
91,06/09/2022 09:57:46,TMUS,170186014720,284003336192,135.7600,150.200000,101.51000,-0.230,3.529,10.825,6.19,2.240,2.114664,21.932148,NaN
92,06/09/2022 09:57:46,NTAP,15559716864,14366119936,69.9200,96.820000,64.58000,-0.218,2.274,10.269,6.15,4.090,2.462760,11.369105,0.0280
93,06/09/2022 09:57:46,KEYS,26158749696,26190764032,145.3700,209.080000,127.93000,0.424,5.094,17.414,7.74,5.527,5.088261,18.781654,NaN
94,06/09/2022 09:57:46,CTSH,38045704192,37901770752,73.0000,93.470000,66.19000,0.126,2.002,11.112,5.04,4.170,2.009597,14.484127,0.0146
95,06/09/2022 09:57:46,MU,76313223168,76562350080,68.3600,98.450000,65.67000,2.774,2.456,4.487,12.52,7.945,2.448369,5.458466,0.0057
96,06/09/2022 09:57:46,CDW,23592605696,30711185408,174.6100,208.710000,155.39000,0.123,1.400,17.507,10.53,7.243,1.075697,16.582148,0.0114
97,06/09/2022 09:57:46,CRM,189239050240,189118054400,190.1900,311.750000,154.55000,-0.943,6.769,70.672,5.84,1.012,6.773051,32.566780,NaN
98,06/09/2022 09:57:46,LRCX,70209216512,73262546944,506.1400,731.850000,442.53000,-0.015,4.377,13.218,38.01,32.000,4.194935,13.315970,0.0115

In [9]:
date_file =today_date.strftime('%m_%d_%Y')
raw_df.to_csv(f'output/SP500_master_df_{date_file}.csv')

In [10]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://{user}:{pw}@localhost/{db}'.format(user='root',
                                                                        pw='Boston1429$$',
                                                                        db='SP500'))
raw_df.to_sql(f'SP500_{date_file}', con=engine, if_exists='append', index=False)

99