In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2014-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_CLE = []

# CLE
while season <= 2021:
    df_CLE = get_roster('CLE', season)
    df_CLE['Season'] = season
    df_CLE['Team'] = 'CLE'
    appended_data_CLE.append(df_CLE)
    season = season + 1
appended_data_CLE = pd.concat(appended_data_CLE)

In [4]:
CLE_df_all = appended_data_CLE.copy()
CLE_df_all_csv = CLE_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_players_all.csv', index=False)
CLE_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_players_all.csv')
CLE_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,0,Benoit Benjamin,C,7-0,250,1964-11-22,US,14,Creighton,2000,CLE
1,5,Earl Boykins,PG,5-5,135,1976-06-02,US,1,Eastern Michigan,2000,CLE
2,47,A.J. Bramlett,C,6-10,227,1977-01-10,US,R,Arizona,2000,CLE
3,2,Mark Bryant,PF,6-9,245,1965-04-25,US,11,Seton Hall,2000,CLE
4,32,Pete Chilcutt,PF,6-10,230,1968-09-14,US,8,UNC,2000,CLE

In [5]:
CLE_df_2000 = CLE_df_all[CLE_df_all['Season'] == 2000]
CLE_df_2001 = CLE_df_all[CLE_df_all['Season'] == 2001]
CLE_df_2002 = CLE_df_all[CLE_df_all['Season'] == 2002]
CLE_df_2003 = CLE_df_all[CLE_df_all['Season'] == 2003]
CLE_df_2004 = CLE_df_all[CLE_df_all['Season'] == 2004]
CLE_df_2005 = CLE_df_all[CLE_df_all['Season'] == 2005]
CLE_df_2006 = CLE_df_all[CLE_df_all['Season'] == 2006]
CLE_df_2007 = CLE_df_all[CLE_df_all['Season'] == 2007]
CLE_df_2008 = CLE_df_all[CLE_df_all['Season'] == 2008]
CLE_df_2009 = CLE_df_all[CLE_df_all['Season'] == 2009]
CLE_df_2010 = CLE_df_all[CLE_df_all['Season'] == 2010]
CLE_df_2011 = CLE_df_all[CLE_df_all['Season'] == 2011]
CLE_df_2012 = CLE_df_all[CLE_df_all['Season'] == 2012]
CLE_df_2013 = CLE_df_all[CLE_df_all['Season'] == 2013]
CLE_df_2014 = CLE_df_all[CLE_df_all['Season'] == 2014]
CLE_df_2015 = CLE_df_all[CLE_df_all['Season'] == 2015]
CLE_df_2016 = CLE_df_all[CLE_df_all['Season'] == 2016]
CLE_df_2017 = CLE_df_all[CLE_df_all['Season'] == 2017]
CLE_df_2018 = CLE_df_all[CLE_df_all['Season'] == 2018]
CLE_df_2019 = CLE_df_all[CLE_df_all['Season'] == 2019]
CLE_df_2020 = CLE_df_all[CLE_df_all['Season'] == 2020]
CLE_df_2021 = CLE_df_all[CLE_df_all['Season'] == 2021]

In [6]:
CLE_df_2000_players = CLE_df_2000['PLAYER'].to_list()
CLE_df_2001_players = CLE_df_2001['PLAYER'].to_list()
CLE_df_2002_players = CLE_df_2002['PLAYER'].to_list()
CLE_df_2003_players = CLE_df_2003['PLAYER'].to_list()
CLE_df_2004_players = CLE_df_2004['PLAYER'].to_list()
CLE_df_2005_players = CLE_df_2005['PLAYER'].to_list()

CLE_df_2006_players = CLE_df_2006['PLAYER'].to_list()
CLE_df_2007_players = CLE_df_2007['PLAYER'].to_list()
CLE_df_2008_players = CLE_df_2008['PLAYER'].to_list()
CLE_df_2009_players = CLE_df_2009['PLAYER'].to_list()
CLE_df_2010_players = CLE_df_2010['PLAYER'].to_list()
CLE_df_2011_players = CLE_df_2011['PLAYER'].to_list()

CLE_df_2012_players = CLE_df_2012['PLAYER'].to_list()
CLE_df_2013_players = CLE_df_2013['PLAYER'].to_list()
CLE_df_2014_players = CLE_df_2014['PLAYER'].to_list()
CLE_df_2015_players = CLE_df_2015['PLAYER'].to_list()
CLE_df_2016_players = CLE_df_2016['PLAYER'].to_list()
CLE_df_2017_players = CLE_df_2017['PLAYER'].to_list()

CLE_df_2018_players = CLE_df_2018['PLAYER'].to_list()
CLE_df_2019_players = CLE_df_2019['PLAYER'].to_list()
CLE_df_2020_players = CLE_df_2020['PLAYER'].to_list()
CLE_df_2021_players = CLE_df_2021['PLAYER'].to_list()

In [7]:
# cedric henderson
CLE_2000_gamelog = []



for p in CLE_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2000_gamelog.append(player_log)
CLE_2000_gamelog = pd.concat(CLE_2000_gamelog)    
CLE_2000_gamelogs = CLE_2000_gamelog.copy()
CLE_2000_gamelogs['GAME_SCORE'] = CLE_2000_gamelogs['GAME_SCORE'].astype(float)
CLE_2000_games = CLE_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2000_games_csv = CLE_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2000_games.csv', index=False)
CLE_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2000_games.csv')
CLE_2000_games_proc.head()

You searched for "Benoit Benjamin"
1 result found.
Benoit Benjamin
Results for Benoit Benjamin:

You searched for "Earl Boykins"
1 result found.
Earl Boykins
Results for Earl Boykins:

You searched for "A.J. Bramlett"
1 result found.
A.J. Bramlett
Results for A.J. Bramlett:

You searched for "Mark Bryant"
11 results found.
0: Mark Bryant
1: Mark Blount
2: Mark Bradtke
3: Em Bryant
4: Joe Bryant
5: Kobe Bryant
6: Gary Grant
7: Markel Brown
8: Mark Eaton
9: Mark Workman
10: Mark Sibley
Pick one: 0
Results for Mark Bryant:

You searched for "Pete Chilcutt"
1 result found.
Pete Chilcutt
Results for Pete Chilcutt:

You searched for "Kornél Dávid"
1 result found.
Kornel David
Results for Kornel David:

You searched for "Andrew DeClercq"
1 result found.
Andrew DeClercq
Results for Andrew DeClercq:

You searched for "Danny Ferry"
6 results found.
0: Danny Ferry
1: Danny Finn
2: Danny Ainge
3: Danny Doyle
4: Danny Green
5: Danny Wagner
Pick one: 0
Results for Danny Ferry:

You searched for "Cedric Henderson"
4 results found.
0: Cedric Henderson
1: Cedric Henderson
2: Eric Anderson
3: Kevin Henderson
Pick one: 0
Results for Cedric Henderson:

TypeError: 'NoneType' object does not support item assignment

In [8]:
# cedric henderson
CLE_2001_gamelog = []



for p in CLE_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2001_gamelog.append(player_log)
CLE_2001_gamelog = pd.concat(CLE_2001_gamelog)    
CLE_2001_gamelogs = CLE_2001_gamelog.copy()
CLE_2001_gamelogs['GAME_SCORE'] = CLE_2001_gamelogs['GAME_SCORE'].astype(float)
CLE_2001_games = CLE_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2001_games_csv = CLE_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2001_games.csv', index=False)
CLE_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2001_games.csv')
CLE_2001_games_proc.head()

You searched for "Etdrick Bohannon"
1 result found.
Etdrick Bohannon
Results for Etdrick Bohannon:

You searched for "Chucky Brown"
3 results found.
0: Chucky Brown
1: Bruce Brown
2: Rickey Brown
Pick one: 0
Results for Chucky Brown:

You searched for "Bimbo Coles"
1 result found.
Bimbo Coles
Results for Bimbo Coles:

You searched for "Chris Gatling"
4 results found.
0: Chris Gatling
1: Chris King
2: Chris Mullin
3: Chris Garner
Pick one: 0
Results for Chris Gatling:

You searched for "Matt Harpring"
1 result found.
Matt Harpring
Results for Matt Harpring:

You searched for "Michael Hawkins"
5 results found.
0: Michael Hawkins
1: Marshall Hawkins
2: Michael Jackson
3: Michael Ansley
4: Michael Wilson
Pick one: 0
Results for Michael Hawkins:

You searched for "Cedric Henderson"
4 results found.
0: Cedric Henderson
1: Cedric Henderson
2: Eric Anderson
3: Kevin Henderson
Pick one: 0
Results for Cedric Henderson:

TypeError: 'NoneType' object does not support item assignment

In [32]:
CLE_2002_gamelog = []



for p in CLE_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2002_gamelog.append(player_log)
CLE_2002_gamelog = pd.concat(CLE_2002_gamelog)    
CLE_2002_gamelogs = CLE_2002_gamelog.copy()
CLE_2002_gamelogs['GAME_SCORE'] = CLE_2002_gamelogs['GAME_SCORE'].astype(float)
CLE_2002_games = CLE_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2002_games_csv = CLE_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2002_games.csv', index=False)
CLE_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2002_games.csv')
CLE_2002_games_proc.head()

You searched for "Bimbo Coles"
1 result found.
Bimbo Coles
Results for Bimbo Coles:

You searched for "Ricky Davis"
17 results found.
0: Ricky Davis
1: Mickey Davis
2: Mike Davis
3: Mike Davis
4: Bill Davis
5: Brian Davis
6: Harry Davis
7: Jim Davis
8: Mark Davis
9: Mark Davis
10: Ralph Davis
11: Red Davis
12: Ron Davis
13: Terry Davis
14: Ricky Marsh
15: Ricky Rubio
16: Ricky Grace
Pick one: 0
Results for Ricky Davis:

You searched for "DeSagana Diop"
1 result found.
DeSagana Diop
Results for DeSagana Diop:

You searched for "Michael Doleac"
8 results found.
0: Michael Doleac
1: Michael Holton
2: Michael Jordan
3: Michael Wiley
4: Michael Ansley
5: Michael Cooper
6: Michael Finley
7: Michael Porter
Pick one: 0
Results for Michael Doleac:

You searched for "Tyrone Hill"
5 results found.
0: Tyrone Hill
1: Tyrone Britt
2: Armond Hill
3: Grant Hill
4: Tyronn Lue
Pick one: 0
Results for Tyrone Hill:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "Jumaine Jones"
3 results found.
0: Jumaine Jones
1: Dwayne Jones
2: Jake Jones
Pick one: 0
Results for Jumaine Jones:

You searched for "Trajan Langdon"
1 result found.
Trajan Langdon
Results for Trajan Langdon:

You searched for "Chris Mihm"
22 results found.
0: Chris Mihm
1: Chris King
2: Chris Mills
3: Chris Munk
4: Chris Smith
5: Chris Smith
6: Chris Babb
7: Chris Bosh
8: Chris Carr
9: Chris Duhon
10: Chris Ford
11: Chris Jent
12: Chris Paul
13: Chris Quinn
14: Chris Silva
15: Chris Taft
16: Chris Welp
17: Chris Wright
18: Chris Wright
19: Chris Kaman
20: Chris Morris
21: Chris Mullin
Pick one: 0
Results for Chris Mihm:

You searched for "Andre Miller"
7 results found.
0: Andre Miller
1: Eddie Miller
2: Harry Miller
3: Larry Miller
4: Mike Miller
5: Andre Moore
6: Andre Turner
Pick one: 0
Results for Andre Miller:

You searched for "Lamond Murray"
2 results found.
0: Lamond Murray
1: Jamal Murray
Pick one: 0
Results for Lamond Murray:

You searched for "Wesley Person"
2 results found.
0: Wesley Person
1: Wesley Johnson
Pick one: 0
Results for Wesley Person:

You searched for "Brian Skinner"
6 results found.
0: Brian Skinner
1: Brian Oliver
2: Brian Quinnett
3: Al Skinner
4: Tal Skinner
5: Brian Winters
Pick one: 0
Results for Brian Skinner:

You searched for "Bryant Stith"
1 result found.
Bryant Stith
Results for Bryant Stith:

You searched for "Jeff Trepagnier"
1 result found.
Jeff Trepagnier
Results for Jeff Trepagnier:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-12-19,25-275,CLE,AWAY,BOS,L (-6),1,37:59,14,18,...,8,5,3,0,1,4,36,37.3,-1,Andre Miller
1,2001-12-04,25-260,CLE,HOME,DET,W (+12),1,35:14,12,16,...,8,11,3,3,6,2,34,36.4,9,Andre Miller
2,2002-02-16,28-302,CLE,AWAY,CHI,W (+13),1,41:03,14,23,...,12,2,0,0,0,1,37,32.7,16,Lamond Murray
3,2002-04-13,26-025,CLE,AWAY,ATL,L (-5),1,46:04,10,19,...,6,16,3,0,2,2,27,32.1,2,Andre Miller
4,2002-02-12,25-330,CLE,HOME,TOR,W (+18),1,39:52,8,14,...,10,17,4,0,2,4,22,31.5,14,Andre Miller

In [9]:
CLE_2003_gamelog = []



for p in CLE_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2003_gamelog.append(player_log)
CLE_2003_gamelog = pd.concat(CLE_2003_gamelog)    
CLE_2003_gamelogs = CLE_2003_gamelog.copy()
CLE_2003_gamelogs['GAME_SCORE'] = CLE_2003_gamelogs['GAME_SCORE'].astype(float)
CLE_2003_games = CLE_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2003_games_csv = CLE_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2003_games.csv', index=False)
CLE_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2003_games.csv')
CLE_2003_games_proc.head()

You searched for "Carlos Boozer"
5 results found.
0: Carlos Boozer
1: Carlos Rogers
2: Charles Cooke
3: Carlos Arroyo
4: Carlos Terry
Pick one: 0
Results for Carlos Boozer:

You searched for "Tierre Brown"
8 results found.
0: Tierre Brown
1: Andre Brown
2: Dee Brown
3: Dee Brown
4: George Brown
5: Larry Brown
6: Mike Brown
7: Troy Brown
Pick one: 0
Results for Tierre Brown:

You searched for "Bimbo Coles"
1 result found.
Bimbo Coles
Results for Bimbo Coles:

You searched for "Ricky Davis"
17 results found.
0: Ricky Davis
1: Mickey Davis
2: Mike Davis
3: Mike Davis
4: Bill Davis
5: Brian Davis
6: Harry Davis
7: Jim Davis
8: Mark Davis
9: Mark Davis
10: Ralph Davis
11: Red Davis
12: Ron Davis
13: Terry Davis
14: Ricky Marsh
15: Ricky Rubio
16: Ricky Grace
Pick one: 0
Results for Ricky Davis:

You searched for "DeSagana Diop"
1 result found.
DeSagana Diop
Results for DeSagana Diop:

You searched for "Tyrone Hill"
5 results found.
0: Tyrone Hill
1: Tyrone Britt
2: Armond Hill
3: Grant Hill
4: Tyronn Lue
Pick one: 0
Results for Tyrone Hill:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "Jumaine Jones"
3 results found.
0: Jumaine Jones
1: Dwayne Jones
2: Jake Jones
Pick one: 0
Results for Jumaine Jones:

You searched for "Chris Mihm"
22 results found.
0: Chris Mihm
1: Chris King
2: Chris Mills
3: Chris Munk
4: Chris Smith
5: Chris Smith
6: Chris Babb
7: Chris Bosh
8: Chris Carr
9: Chris Duhon
10: Chris Ford
11: Chris Jent
12: Chris Paul
13: Chris Quinn
14: Chris Silva
15: Chris Taft
16: Chris Welp
17: Chris Wright
18: Chris Wright
19: Chris Kaman
20: Chris Morris
21: Chris Mullin
Pick one: 0
Results for Chris Mihm:

You searched for "Darius Miles"
6 results found.
0: Darius Miles
1: Darius Miller
2: Darius Bazley
3: Aaron Miles
4: Chris Mills
5: Darius Morris
Pick one: 0
Results for Darius Miles:

You searched for "Milt Palacio"
1 result found.
Milt Palacio
Results for Milt Palacio:

You searched for "Smush Parker"
2 results found.
0: Smush Parker
1: Sonny Parker
Pick one: 0
Results for Smush Parker:

You searched for "Michael Stewart"
1 result found.
Michael Stewart
Results for Michael Stewart:

You searched for "Dajuan Wagner"
2 results found.
0: Dajuan Wagner
1: Danny Wagner
Pick one: 0
Results for Dajuan Wagner:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-12-13,23-081,CLE,AWAY,BOS,L (-15),1,43:54,17,26,...,4,8,3,0,0,1,42,39.6,-9,Ricky Davis
1,2002-12-20,23-088,CLE,AWAY,DET,L (-2),1,50:21,13,25,...,8,7,3,1,2,2,42,37.9,-1,Ricky Davis
2,2003-03-25,23-183,CLE,HOME,GSW,W (+21),1,40:26,13,20,...,4,11,3,3,0,2,28,32.8,19,Ricky Davis
3,2003-02-25,27-265,CLE,HOME,NJN,W (+3),1,33:57,10,13,...,8,6,2,3,4,4,29,30.6,15,Zydrunas Ilgauskas
4,2003-01-27,23-126,CLE,HOME,LAC,W (+4),1,41:48,10,21,...,10,8,2,0,1,2,32,30.1,3,Ricky Davis

In [10]:

CLE_2004_gamelog = []



for p in CLE_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2004_gamelog.append(player_log)
CLE_2004_gamelog = pd.concat(CLE_2004_gamelog)    
CLE_2004_gamelogs = CLE_2004_gamelog.copy()
CLE_2004_gamelogs['GAME_SCORE'] = CLE_2004_gamelogs['GAME_SCORE'].astype(float)
CLE_2004_games = CLE_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2004_games_csv = CLE_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2004_games.csv', index=False)
CLE_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2004_games.csv')
CLE_2004_games_proc.head()

You searched for "Tony Battie"
8 results found.
0: Tony Battie
1: John Battle
2: Kenny Battle
3: Tony Harris
4: Tony White
5: Tony Allen
6: Tony Bobbitt
7: Tony Bennett
Pick one: 0
Results for Tony Battie:

You searched for "Carlos Boozer"
5 results found.
0: Carlos Boozer
1: Carlos Rogers
2: Charles Cooke
3: Carlos Arroyo
4: Carlos Terry
Pick one: 0
Results for Carlos Boozer:

You searched for "J.R. Bremer"
3 results found.
0: J.R. Bremer
1: Jim Brewer
2: J.R. Reid
Pick one: 0
Results for J.R. Bremer:

You searched for "Kedrick Brown"
2 results found.
0: Kedrick Brown
1: Derrick Brown
Pick one: 0
Results for Kedrick Brown:

You searched for "Mateen Cleaves"
1 result found.
Mateen Cleaves
Results for Mateen Cleaves:

You searched for "Ricky Davis"
17 results found.
0: Ricky Davis
1: Mickey Davis
2: Mike Davis
3: Mike Davis
4: Bill Davis
5: Brian Davis
6: Harry Davis
7: Jim Davis
8: Mark Davis
9: Mark Davis
10: Ralph Davis
11: Red Davis
12: Ron Davis
13: Terry Davis
14: Ricky Marsh
15: Ricky Rubio
16: Ricky Grace
Pick one: 0
Results for Ricky Davis:

You searched for "DeSagana Diop"
1 result found.
DeSagana Diop
Results for DeSagana Diop:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "LeBron James"
5 results found.
0: LeBron James
1: Aaron James
2: Damion James
3: Henry James
4: Jerome James
Pick one: 0
Results for LeBron James:

You searched for "Jason Kapono"
2 results found.
0: Jason Kapono
1: Jason Lawson
Pick one: 0
Results for Jason Kapono:

You searched for "Jelani McCoy"
1 result found.
Jelani McCoy
Results for Jelani McCoy:

You searched for "Jeff McInnis"
2 results found.
0: Jeff McInnis
1: Jeff Mullins
Pick one: 0
Results for Jeff McInnis:

You searched for "Chris Mihm"
22 results found.
0: Chris Mihm
1: Chris King
2: Chris Mills
3: Chris Munk
4: Chris Smith
5: Chris Smith
6: Chris Babb
7: Chris Bosh
8: Chris Carr
9: Chris Duhon
10: Chris Ford
11: Chris Jent
12: Chris Paul
13: Chris Quinn
14: Chris Silva
15: Chris Taft
16: Chris Welp
17: Chris Wright
18: Chris Wright
19: Chris Kaman
20: Chris Morris
21: Chris Mullin
Pick one: 0
Results for Chris Mihm:

You searched for "Darius Miles"
6 results found.
0: Darius Miles
1: Darius Miller
2: Darius Bazley
3: Aaron Miles
4: Chris Mills
5: Darius Morris
Pick one: 0
Results for Darius Miles:

You searched for "Lee Nailon"
2 results found.
0: Lee Nailon
1: Zeke Nnaji
Pick one: 0
Results for Lee Nailon:

You searched for "Ira Newble"
2 results found.
0: Ira Newble
1: Kira Lewis
Pick one: 0
Results for Ira Newble:

You searched for "Kevin Ollie"
8 results found.
0: Kevin Ollie
1: Kevin Love
2: Kevin Willis
3: Kevin Joyce
4: Kevin Loder
5: Kevin O'Shea
6: Kevin Jones
7: Kelvin Cato
Pick one: 0
Results for Kevin Ollie:

You searched for "Michael Stewart"
1 result found.
Michael Stewart
Results for Michael Stewart:

You searched for "Bruno Šundov"
1 result found.
Bruno Sundov
Results for Bruno Sundov:

You searched for "Dajuan Wagner"
2 results found.
0: Dajuan Wagner
1: Danny Wagner
Pick one: 0
Results for Dajuan Wagner:

You searched for "Eric Williams"
56 results found.
0: Eric Williams
1: Eric McWilliams
2: Art Williams
3: Bernie Williams
4: Deron Williams
5: Derrick Williams
6: Earl Williams
7: Herb Williams
8: Kenrich Williams
9: Kevin Williams
10: Ray Williams
11: Rob Williams
12: Ron Williams
13: Troy Williams
14: Patrick Williams
15: Aaron Williams
16: Al Williams
17: Alan Williams
18: Alvin Williams
19: Bob Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Duck Williams
26: Elliot Williams
27: Fly Williams
28: Frank Williams
29: Gene Williams
30: Grant Williams
31: Gus Williams
32: Guy Williams
33: Hank Williams
34: Jay Williams
35: Jerome Williams
36: John Williams
37: Kenny Williams
38: Lou Williams
39: Marvin Williams
40: Matt Williams
41: Mike Williams
42: Milt Williams
43: Mo Williams
44: Nate Williams
45: Pete Williams
46: Reggie Williams
47: Reggie Williams
48: Rickey Williams
49: Sam Williams
50: Sam Williams
51: Sean Williams
52: Sly Williams
53: Travis Williams
54: Walt Williams
55: Ward Williams
Pick one: 0
Results for Eric Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-03-27,19-088,CLE,HOME,NJN,W (+3),1,43:48,15,29,...,6,13,3,0,2,1,41,39.0,10,LeBron James
1,2004-01-20,22-061,CLE,HOME,SEA,W (+5),1,40:28,9,20,...,20,4,1,1,1,3,32,32.7,14,Carlos Boozer
2,2004-01-17,22-058,CLE,AWAY,UTA,W (+6),1,43:20,12,20,...,18,1,2,1,1,3,32,31.4,24,Carlos Boozer
3,2003-12-28,18-363,CLE,HOME,POR,W (+12),1,39:05,15,23,...,10,9,3,0,5,1,32,30.0,11,LeBron James
4,2003-12-19,18-354,CLE,AWAY,PHI,W (+7),1,41:41,14,24,...,4,5,4,0,4,1,36,29.5,9,LeBron James

In [11]:
# luke jackson

CLE_2005_gamelog = []

for p in CLE_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2005_gamelog.append(player_log)
CLE_2005_gamelog = pd.concat(CLE_2005_gamelog)    
CLE_2005_gamelogs = CLE_2005_gamelog.copy()
CLE_2005_gamelogs['GAME_SCORE'] = CLE_2005_gamelogs['GAME_SCORE'].astype(float)
CLE_2005_games = CLE_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2005_games_csv = CLE_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2005_games.csv', index=False)
CLE_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2005_games.csv')
CLE_2005_games_proc.head()

You searched for "DeSagana Diop"
1 result found.
DeSagana Diop
Results for DeSagana Diop:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Lucious Harris"
1 result found.
Lucious Harris
Results for Lucious Harris:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "Luke Jackson"
15 results found.
0: Luke Jackson
1: Luke Jackson
2: Mike Jackson
3: Al Jackson
4: Greg Jackson
5: Jaren Jackson
6: Jaren Jackson
7: Jim Jackson
8: Josh Jackson
9: Marc Jackson
10: Mark Jackson
11: Phil Jackson
12: Tony Jackson
13: Tony Jackson
14: Luke Walton
Pick one: 0
Results for Luke Jackson:

TypeError: 'NoneType' object does not support item assignment

In [12]:
# luke jackson
CLE_2006_gamelog = []

for p in CLE_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2006_gamelog.append(player_log)
CLE_2006_gamelog = pd.concat(CLE_2006_gamelog)    
CLE_2006_gamelogs = CLE_2006_gamelog.copy()
CLE_2006_gamelogs['GAME_SCORE'] = CLE_2006_gamelogs['GAME_SCORE'].astype(float)
CLE_2006_games = CLE_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2006_games_csv = CLE_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2006_games.csv', index=False)
CLE_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2006_games.csv')
CLE_2006_games_proc.head()

You searched for "Martynas Andriuškevičius"
1 result found.
Martynas Andriuskevicius
Results for Martynas Andriuskevicius:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Stephen Graham"
1 result found.
Stephen Graham
Results for Stephen Graham:

You searched for "Zendon Hamilton"
3 results found.
0: Zendon Hamilton
1: Dennis Hamilton
2: Jordan Hamilton
Pick one: 0
Results for Zendon Hamilton:

You searched for "Alan Henderson"
9 results found.
0: Alan Henderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ryan Anderson
5: Dave Henderson
6: J.R. Henderson
7: Kevin Henderson
8: Tom Henderson
Pick one: 0
Results for Alan Henderson:

You searched for "Larry Hughes"
6 results found.
0: Larry Hughes
1: Larry Bunce
2: Larry Fogle
3: Larry Jones
4: Larry Sykes
5: Larry Wright
Pick one: 0
Results for Larry Hughes:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "Luke Jackson"
15 results found.
0: Luke Jackson
1: Luke Jackson
2: Mike Jackson
3: Al Jackson
4: Greg Jackson
5: Jaren Jackson
6: Jaren Jackson
7: Jim Jackson
8: Josh Jackson
9: Marc Jackson
10: Mark Jackson
11: Phil Jackson
12: Tony Jackson
13: Tony Jackson
14: Luke Walton
Pick one: 0
Results for Luke Jackson:

TypeError: 'NoneType' object does not support item assignment

In [13]:
# sasha pavlovic

CLE_2007_gamelog = []

for p in CLE_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2007_gamelog.append(player_log)
CLE_2007_gamelog = pd.concat(CLE_2007_gamelog)    
CLE_2007_gamelogs = CLE_2007_gamelog.copy()
CLE_2007_gamelogs['GAME_SCORE'] = CLE_2007_gamelogs['GAME_SCORE'].astype(float)
CLE_2007_games = CLE_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2007_games_csv = CLE_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2007_games.csv', index=False)
CLE_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2007_games.csv')
CLE_2007_games_proc.head()

You searched for "Shannon Brown"
2 results found.
0: Shannon Brown
1: Stan Brown
Pick one: 0
Results for Shannon Brown:

You searched for "Daniel Gibson"
4 results found.
0: Daniel Gibson
1: Dee Gibson
2: Mel Gibson
3: Daniel Orton
Pick one: 0
Results for Daniel Gibson:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Larry Hughes"
6 results found.
0: Larry Hughes
1: Larry Bunce
2: Larry Fogle
3: Larry Jones
4: Larry Sykes
5: Larry Wright
Pick one: 0
Results for Larry Hughes:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "LeBron James"
5 results found.
0: LeBron James
1: Aaron James
2: Damion James
3: Henry James
4: Jerome James
Pick one: 0
Results for LeBron James:

You searched for "Damon Jones"
24 results found.
0: Damon Jones
1: Mason Jones
2: Damian Jones
3: Damion James
4: Jalen Jones
5: James Jones
6: Major Jones
7: Sam Jones
8: Aaron James
9: Alvin Jones
10: DeQuan Jones
11: Dwayne Jones
12: Earl Jones
13: Jake Jones
14: Jimmy Jones
15: Kevin Jones
16: Larry Jones
17: Mark Jones
18: Mark Jones
19: Robin Jones
20: Solomon Jones
21: Wali Jones
22: Diamond Stone
23: Damone Brown
Pick one: 0
Results for Damon Jones:

You searched for "Dwayne Jones"
12 results found.
0: Dwayne Jones
1: Dwayne Polee
2: Damon Jones
3: Dwight Jones
4: Jake Jones
5: Jumaine Jones
6: Wali Jones
7: Wayne Molis
8: Wayne Yates
9: Dwayne Bacon
10: Dwayne Morton
11: Dwayne Sutton
Pick one: 0
Results for Dwayne Jones:

You searched for "Donyell Marshall"
3 results found.
0: Donyell Marshall
1: Donny Marshall
2: Kendall Marshall
Pick one: 0
Results for Donyell Marshall:

You searched for "Ira Newble"
2 results found.
0: Ira Newble
1: Kira Lewis
Pick one: 0
Results for Ira Newble:

You searched for "Sasha Pavlović"
2 results found.
0: Sasha Pavlovic
1: Sasha Danilovic
Pick one: 0
Results for Sasha Pavlovic:

AttributeError: 'NoneType' object has no attribute 'replace'

In [14]:
# sasha pavlovic
CLE_2008_gamelog = []

for p in CLE_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2008_gamelog.append(player_log)
CLE_2008_gamelog = pd.concat(CLE_2008_gamelog)    
CLE_2008_gamelogs = CLE_2008_gamelog.copy()
CLE_2008_gamelogs['GAME_SCORE'] = CLE_2008_gamelogs['GAME_SCORE'].astype(float)
CLE_2008_games = CLE_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2008_games_csv = CLE_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2008_games.csv', index=False)
CLE_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2008_games.csv')
CLE_2008_games_proc.head()

You searched for "Lance Allred"
1 result found.
Lance Allred
Results for Lance Allred:

You searched for "Devin Brown"
15 results found.
0: Devin Brown
1: Dee Brown
2: Dee Brown
3: Leon Brown
4: Lewis Brown
5: Devin Green
6: Devin Booker
7: Kevin Brooks
8: Damone Brown
9: Derrick Brown
10: John Brown
11: Myron Brown
12: Stan Brown
13: Devin Gray
14: Jim Browne
Pick one: 0
Results for Devin Brown:

You searched for "Shannon Brown"
2 results found.
0: Shannon Brown
1: Stan Brown
Pick one: 0
Results for Shannon Brown:

You searched for "Kaniel Dickens"
1 result found.
Kaniel Dickens
Results for Kaniel Dickens:

You searched for "Daniel Gibson"
4 results found.
0: Daniel Gibson
1: Dee Gibson
2: Mel Gibson
3: Daniel Orton
Pick one: 0
Results for Daniel Gibson:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Larry Hughes"
6 results found.
0: Larry Hughes
1: Larry Bunce
2: Larry Fogle
3: Larry Jones
4: Larry Sykes
5: Larry Wright
Pick one: 0
Results for Larry Hughes:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "LeBron James"
5 results found.
0: LeBron James
1: Aaron James
2: Damion James
3: Henry James
4: Jerome James
Pick one: 0
Results for LeBron James:

You searched for "Damon Jones"
24 results found.
0: Damon Jones
1: Mason Jones
2: Damian Jones
3: Damion James
4: Jalen Jones
5: James Jones
6: Major Jones
7: Sam Jones
8: Aaron James
9: Alvin Jones
10: DeQuan Jones
11: Dwayne Jones
12: Earl Jones
13: Jake Jones
14: Jimmy Jones
15: Kevin Jones
16: Larry Jones
17: Mark Jones
18: Mark Jones
19: Robin Jones
20: Solomon Jones
21: Wali Jones
22: Diamond Stone
23: Damone Brown
Pick one: 0
Results for Damon Jones:

You searched for "Dwayne Jones"
12 results found.
0: Dwayne Jones
1: Dwayne Polee
2: Damon Jones
3: Dwight Jones
4: Jake Jones
5: Jumaine Jones
6: Wali Jones
7: Wayne Molis
8: Wayne Yates
9: Dwayne Bacon
10: Dwayne Morton
11: Dwayne Sutton
Pick one: 0
Results for Dwayne Jones:

You searched for "Donyell Marshall"
3 results found.
0: Donyell Marshall
1: Donny Marshall
2: Kendall Marshall
Pick one: 0
Results for Donyell Marshall:

You searched for "Ira Newble"
2 results found.
0: Ira Newble
1: Kira Lewis
Pick one: 0
Results for Ira Newble:

You searched for "Demetris Nichols"
1 result found.
Demetris Nichols
Results for Demetris Nichols:

You searched for "Sasha Pavlović"
2 results found.
0: Sasha Pavlovic
1: Sasha Danilovic
Pick one: 0
Results for Sasha Pavlovic:

AttributeError: 'NoneType' object has no attribute 'replace'

In [15]:
# sasha pavlovic
CLE_2009_gamelog = []

for p in CLE_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2009_gamelog.append(player_log)
CLE_2009_gamelog = pd.concat(CLE_2009_gamelog)    
CLE_2009_gamelogs = CLE_2009_gamelog.copy()
CLE_2009_gamelogs['GAME_SCORE'] = CLE_2009_gamelogs['GAME_SCORE'].astype(float)
CLE_2009_games = CLE_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2009_games_csv = CLE_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2009_games.csv', index=False)
CLE_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2009_games.csv')
CLE_2009_games_proc.head()

You searched for "Daniel Gibson"
4 results found.
0: Daniel Gibson
1: Dee Gibson
2: Mel Gibson
3: Daniel Orton
Pick one: 0
Results for Daniel Gibson:

You searched for "J.J. Hickson"
3 results found.
0: J.J. Hickson
1: John Dickson
2: D.J. Wilson
Pick one: 0
Results for J.J. Hickson:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "Darnell Jackson"
5 results found.
0: Darnell Jackson
1: Wardell Jackson
2: Randell Jackson
3: Jaren Jackson
4: Jaren Jackson
Pick one: 0
Results for Darnell Jackson:

You searched for "LeBron James"
5 results found.
0: LeBron James
1: Aaron James
2: Damion James
3: Henry James
4: Jerome James
Pick one: 0
Results for LeBron James:

You searched for "Trey Johnson"
38 results found.
0: Trey Johnson
1: Andy Johnson
2: Avery Johnson
3: Clay Johnson
4: Ed Johnson
5: Eric Johnson
6: Joe Johnson
7: Ken Johnson
8: Ken Johnson
9: Larry Johnson
10: Larry Johnson
11: Lee Johnson
12: Ron Johnson
13: Stew Johnson
14: Tyler Johnson
15: Amir Johnson
16: Armon Johnson
17: Arnie Johnson
18: B.J. Johnson
19: Brice Johnson
20: Buck Johnson
21: Chris Johnson
22: Chris Johnson
23: Darryl Johnson
24: Dave Johnson
25: Ervin Johnson
26: Frank Johnson
27: Gus Johnson
28: Ivan Johnson
29: James Johnson
30: John Johnson
31: Mickey Johnson
32: Neil Johnson
33: Nick Johnson
34: Rich Johnson
35: Stanley Johnson
36: Steve Johnson
37: Wesley Johnson
Pick one: 0
Results for Trey Johnson:

You searched for "Tarence Kinsey"
1 result found.
Tarence Kinsey
Results for Tarence Kinsey:

You searched for "Sasha Pavlović"
2 results found.
0: Sasha Pavlovic
1: Sasha Danilovic
Pick one: 0
Results for Sasha Pavlovic:

AttributeError: 'NoneType' object has no attribute 'replace'

In [16]:
# Shaq
CLE_2010_gamelog = []

for p in CLE_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2010_gamelog.append(player_log)
CLE_2010_gamelog = pd.concat(CLE_2010_gamelog)    
CLE_2010_gamelogs = CLE_2010_gamelog.copy()
CLE_2010_gamelogs['GAME_SCORE'] = CLE_2010_gamelogs['GAME_SCORE'].astype(float)
CLE_2010_games = CLE_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2010_games_csv = CLE_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2010_games.csv', index=False)
CLE_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2010_games.csv')
CLE_2010_games_proc.head()

You searched for "Daniel Gibson"
4 results found.
0: Daniel Gibson
1: Dee Gibson
2: Mel Gibson
3: Daniel Orton
Pick one: 0
Results for Daniel Gibson:

You searched for "Danny Green"
20 results found.
0: Danny Green
1: Kenny Green
2: Johnny Green
3: Danny Finn
4: Danny Granger
5: A.C. Green
6: Devin Green
7: Ken Green
8: Lamar Green
9: Sean Green
10: Sidney Green
11: Donte Greene
12: Lynn Greer
13: Danny Vranes
14: Danny Ainge
15: Danny Doyle
16: Danny Ferry
17: Dennis Grey
18: Danny Wagner
19: Danny Young
Pick one: 0
Results for Danny Green:

You searched for "J.J. Hickson"
3 results found.
0: J.J. Hickson
1: John Dickson
2: D.J. Wilson
Pick one: 0
Results for J.J. Hickson:

You searched for "Zydrunas Ilgauskas"
1 result found.
Zydrunas Ilgauskas
Results for Zydrunas Ilgauskas:

You searched for "Cedric Jackson"
4 results found.
0: Cedric Jackson
1: Marc Jackson
2: Mervin Jackson
3: Reggie Jackson
Pick one: 0
Results for Cedric Jackson:

You searched for "Darnell Jackson"
5 results found.
0: Darnell Jackson
1: Wardell Jackson
2: Randell Jackson
3: Jaren Jackson
4: Jaren Jackson
Pick one: 0
Results for Darnell Jackson:

You searched for "LeBron James"
5 results found.
0: LeBron James
1: Aaron James
2: Damion James
3: Henry James
4: Jerome James
Pick one: 0
Results for LeBron James:

You searched for "Antawn Jamison"
1 result found.
Antawn Jamison
Results for Antawn Jamison:

You searched for "Coby Karl"
3 results found.
0: Coby Karl
1: Cory Carr
2: Rob Kurz
Pick one: 0
Results for Coby Karl:

You searched for "Jamario Moon"
1 result found.
Jamario Moon
Results for Jamario Moon:

You searched for "Shaquille O'Neal"
1 result found.
Shaquille O'Neal
Results for Shaquille O'Neal:

AttributeError: 'NoneType' object has no attribute 'replace'

In [17]:
# mo williams
CLE_2011_gamelog = []

for p in CLE_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2011_gamelog.append(player_log)
CLE_2011_gamelog = pd.concat(CLE_2011_gamelog)    
CLE_2011_gamelogs = CLE_2011_gamelog.copy()
CLE_2011_gamelogs['GAME_SCORE'] = CLE_2011_gamelogs['GAME_SCORE'].astype(float)
CLE_2011_games = CLE_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2011_games_csv = CLE_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2011_games.csv', index=False)
CLE_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2011_games.csv')
CLE_2011_games_proc.head()

You searched for "Baron Davis"
22 results found.
0: Baron Davis
1: Ron Davis
2: Ben Davis
3: Bob Davis
4: Brad Davis
5: Brian Davis
6: Harry Davis
7: Mark Davis
8: Mark Davis
9: Warren Davis
10: Bob Davies
11: Brandon Davies
12: Bill Davis
13: Dale Davis
14: Glen Davis
15: Paul Davis
16: Ralph Davis
17: Red Davis
18: Terry Davis
19: Walt Davis
20: Byron Irvin
21: Aaron James
Pick one: 0
Results for Baron Davis:

You searched for "Semih Erden"
1 result found.
Semih Erden
Results for Semih Erden:

You searched for "Christian Eyenga"
1 result found.
Christian Eyenga
Results for Christian Eyenga:

You searched for "Alonzo Gee"
1 result found.
Alonzo Gee
Results for Alonzo Gee:

You searched for "Daniel Gibson"
4 results found.
0: Daniel Gibson
1: Dee Gibson
2: Mel Gibson
3: Daniel Orton
Pick one: 0
Results for Daniel Gibson:

You searched for "Joey Graham"
5 results found.
0: Joey Graham
1: Greg Graham
2: Mal Graham
3: Paul Graham
4: Joe Hamood
Pick one: 0
Results for Joey Graham:

You searched for "Luke Harangody"
1 result found.
Luke Harangody
Results for Luke Harangody:

You searched for "Manny Harris"
7 results found.
0: Manny Harris
1: Gary Harris
2: Tony Harris
3: Jalen Harris
4: Art Harris
5: Billy Harris
6: Mike Harris
Pick one: 0
Results for Manny Harris:

You searched for "J.J. Hickson"
3 results found.
0: J.J. Hickson
1: John Dickson
2: D.J. Wilson
Pick one: 0
Results for J.J. Hickson:

You searched for "Ryan Hollins"
3 results found.
0: Ryan Hollins
1: Don Collins
2: John Collins
Pick one: 0
Results for Ryan Hollins:

You searched for "Antawn Jamison"
1 result found.
Antawn Jamison
Results for Antawn Jamison:

You searched for "Jamario Moon"
1 result found.
Jamario Moon
Results for Jamario Moon:

You searched for "Anthony Parker"
10 results found.
0: Anthony Parker
1: Anthony Carter
2: Tony Parker
3: Anthony Peeler
4: Anthony Tucker
5: Anthony Bonner
6: Anthony Miller
7: Anthony Taylor
8: Anthony Avent
9: Anthony Pullard
Pick one: 0
Results for Anthony Parker:

You searched for "Leon Powe"
5 results found.
0: Leon Powe
1: Leon Brown
2: Leon Wood
3: Lou Roe
4: Leon Benbow
Pick one: 0
Results for Leon Powe:

You searched for "Samardo Samuels"
1 result found.
Samardo Samuels
Results for Samardo Samuels:

You searched for "Ramon Sessions"
1 result found.
Ramon Sessions
Results for Ramon Sessions:

You searched for "Anderson Varejão"
1 result found.
Anderson Varejao
Results for Anderson Varejao:

You searched for "Jawad Williams"
21 results found.
0: Jawad Williams
1: Alan Williams
2: Jason Williams
3: Jay Williams
4: Ward Williams
5: Aaron Williams
6: Al Williams
7: Art Williams
8: Earl Williams
9: Hank Williams
10: Jayson Williams
11: John Williams
12: Jordan Williams
13: Matt Williams
14: Nate Williams
15: Ray Williams
16: Sam Williams
17: Sam Williams
18: Sean Williams
19: Shawne Williams
20: Walt Williams
Pick one: 0
Results for Jawad Williams:

You searched for "Mo Williams"
40 results found.
0: Mo Williams
1: Al Williams
2: Bob Williams
3: Lou Williams
4: Rob Williams
5: Ron Williams
6: Art Williams
7: Fly Williams
8: Gus Williams
9: Guy Williams
10: Jay Williams
11: John Williams
12: Matt Williams
13: Mike Williams
14: Milt Williams
15: Monty Williams
16: Ray Williams
17: Sam Williams
18: Sam Williams
19: Sly Williams
20: Troy Williams
21: Aaron Williams
22: Alan Williams
23: Buck Williams
24: C.J. Williams
25: Corey Williams
26: Deron Williams
27: Duck Williams
28: Earl Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Nate Williams
35: Pete Williams
36: Scott Williams
37: Sean Williams
38: Walt Williams
39: Ward Williams
Pick one: 0
Results for Mo Williams:

AttributeError: 'NoneType' object has no attribute 'replace'

In [18]:
CLE_2012_gamelog = []

for p in CLE_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2012_gamelog.append(player_log)
CLE_2012_gamelog = pd.concat(CLE_2012_gamelog)    
CLE_2012_gamelogs = CLE_2012_gamelog.copy()
CLE_2012_gamelogs['GAME_SCORE'] = CLE_2012_gamelogs['GAME_SCORE'].astype(float)
CLE_2012_games = CLE_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2012_games_csv = CLE_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2012_games.csv', index=False)
CLE_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2012_games.csv')
CLE_2012_games_proc.head()

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Semih Erden"
1 result found.
Semih Erden
Results for Semih Erden:

You searched for "Christian Eyenga"
1 result found.
Christian Eyenga
Results for Christian Eyenga:

You searched for "Alonzo Gee"
1 result found.
Alonzo Gee
Results for Alonzo Gee:

You searched for "Daniel Gibson"
4 results found.
0: Daniel Gibson
1: Dee Gibson
2: Mel Gibson
3: Daniel Orton
Pick one: 0
Results for Daniel Gibson:

You searched for "Luke Harangody"
1 result found.
Luke Harangody
Results for Luke Harangody:

You searched for "Manny Harris"
7 results found.
0: Manny Harris
1: Gary Harris
2: Tony Harris
3: Jalen Harris
4: Art Harris
5: Billy Harris
6: Mike Harris
Pick one: 0
Results for Manny Harris:

You searched for "Ryan Hollins"
3 results found.
0: Ryan Hollins
1: Don Collins
2: John Collins
Pick one: 0
Results for Ryan Hollins:

You searched for "Lester Hudson"
1 result found.
Lester Hudson
Results for Lester Hudson:

You searched for "Kyrie Irving"
2 results found.
0: Kyrie Irving
1: Byron Irvin
Pick one: 0
Results for Kyrie Irving:

You searched for "Antawn Jamison"
1 result found.
Antawn Jamison
Results for Antawn Jamison:

You searched for "D.J. Kennedy"
3 results found.
0: D.J. Kennedy
1: Goo Kennedy
2: Joe Kennedy
Pick one: 0
Results for D.J. Kennedy:

You searched for "Anthony Parker"
10 results found.
0: Anthony Parker
1: Anthony Carter
2: Tony Parker
3: Anthony Peeler
4: Anthony Tucker
5: Anthony Bonner
6: Anthony Miller
7: Anthony Taylor
8: Anthony Avent
9: Anthony Pullard
Pick one: 0
Results for Anthony Parker:

You searched for "Samardo Samuels"
1 result found.
Samardo Samuels
Results for Samardo Samuels:

You searched for "Ramon Sessions"
1 result found.
Ramon Sessions
Results for Ramon Sessions:

You searched for "Donald Sloan"
3 results found.
0: Donald Sloan
1: Donald Royal
2: Donald Sidle
Pick one: 0
Results for Donald Sloan:

You searched for "Mychel Thompson"
2 results found.
0: Mychel Thompson
1: Mychal Thompson
Pick one: 0
Results for Mychel Thompson:

You searched for "Tristan Thompson"
1 result found.
Tristan Thompson
Results for Tristan Thompson:

You searched for "Ben Uzoh"
5 results found.
0: Ben Uzoh
1: Ben Moore
2: Beno Udrih
3: Ben Kelso
4: Don Ohl
Pick one: 0
Results for Ben Uzoh:

You searched for "Anderson Varejão"
1 result found.
Anderson Varejao
Results for Anderson Varejao:

You searched for "Luke Walton"
6 results found.
0: Luke Walton
1: Luke Jackson
2: Luke Jackson
3: Bill Walton
4: Lloyd Walton
5: Luke Witte
Pick one: 0
Results for Luke Walton:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-02-10,35-243,CLE,HOME,MIL,L (-1),1,43:35,14,21,...,11,3,0,1,0,3,34,29.0,2,Antawn Jamison
1,2012-04-04,36-290,CLE,AWAY,MIL,L (-9),1,31:56,11,14,...,7,4,3,0,1,2,27,28.1,5,Anthony Parker
2,2012-01-27,19-310,CLE,HOME,NJN,L (-3),1,31:17,12,20,...,6,2,2,0,1,2,32,27.0,1,Kyrie Irving
3,2012-03-03,35-265,CLE,AWAY,WAS,L (-3),1,38:18,11,24,...,9,5,4,2,1,1,29,26.8,12,Antawn Jamison
4,2012-03-19,21-006,CLE,AWAY,NJN,W (+5),1,37:29,12,16,...,12,1,0,1,2,3,27,25.2,-8,Tristan Thompson

In [19]:
CLE_2013_gamelog = []

for p in CLE_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2013_gamelog.append(player_log)
CLE_2013_gamelog = pd.concat(CLE_2013_gamelog)    
CLE_2013_gamelogs = CLE_2013_gamelog.copy()
CLE_2013_gamelogs['GAME_SCORE'] = CLE_2013_gamelogs['GAME_SCORE'].astype(float)
CLE_2013_games = CLE_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2013_games_csv = CLE_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2013_games.csv', index=False)
CLE_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2013_games.csv')
CLE_2013_games_proc.head()

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Wayne Ellington"
1 result found.
Wayne Ellington
Results for Wayne Ellington:

You searched for "Alonzo Gee"
1 result found.
Alonzo Gee
Results for Alonzo Gee:

You searched for "Daniel Gibson"
4 results found.
0: Daniel Gibson
1: Dee Gibson
2: Mel Gibson
3: Daniel Orton
Pick one: 0
Results for Daniel Gibson:

You searched for "Kyrie Irving"
2 results found.
0: Kyrie Irving
1: Byron Irvin
Pick one: 0
Results for Kyrie Irving:

You searched for "Kevin Jones"
29 results found.
0: Kevin Jones
1: Alvin Jones
2: Robin Jones
3: Kevin Joyce
4: Kevin Loder
5: Kevin Love
6: Mason Jones
7: Kevin Brooks
8: Kevin Johnson
9: Askia Jones
10: Damian Jones
11: Damon Jones
12: DeQuan Jones
13: Earl Jones
14: Eddie Jones
15: Jalen Jones
16: K.C. Jones
17: Perry Jones
18: Steve Jones
19: Wali Jones
20: Wil Jones
21: Kevin Knox
22: Kevon Looney
23: Kevin Lynch
24: Kevin Porter
25: Kevin Porter
26: Kevin Ollie
27: Devin Brown
28: Kelvin Cato
Pick one: 0
Results for Kevin Jones:

You searched for "Jon Leuer"
18 results found.
0: Jon Leuer
1: Ron Lee
2: Jon Teske
3: Ron Baker
4: Ron Brewer
5: John Coker
6: Don Dee
7: Fat Lever
8: Ron Mercer
9: Ron Reed
10: Von Wafer
11: Joe DePre
12: John Drew
13: Joe Kleine
14: John Long
15: John Olive
16: Ron Riley
17: John Wall
Pick one: 0
Results for Jon Leuer:

You searched for "Shaun Livingston"
2 results found.
0: Shaun Livingston
1: Ron Livingstone
Pick one: 0
Results for Shaun Livingston:

You searched for "C.J. Miles"
7 results found.
0: C.J. Miles
1: C.J. Kupec
2: B.J. Tyler
3: C.J. Wilcox
4: T.J. Leaf
5: A.J. Price
6: D.J. White
Pick one: 0
Results for C.J. Miles:

You searched for "Jeremy Pargo"
4 results found.
0: Jeremy Pargo
1: Jeremy Lamb
2: Jeremy Evans
3: Jeremy Tyler
Pick one: 0
Results for Jeremy Pargo:

You searched for "Chris Quinn"
12 results found.
0: Chris Quinn
1: Chris Duhon
2: Chris King
3: Chris Munk
4: Kris Dunn
5: Chris Jent
6: Chris Kaman
7: Chris Mihm
8: Chris Mullin
9: Chris Owens
10: Chris Smith
11: Chris Smith
Pick one: 0
Results for Chris Quinn:

You searched for "Samardo Samuels"
1 result found.
Samardo Samuels
Results for Samardo Samuels:

You searched for "Donald Sloan"
3 results found.
0: Donald Sloan
1: Donald Royal
2: Donald Sidle
Pick one: 0
Results for Donald Sloan:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Tristan Thompson"
1 result found.
Tristan Thompson
Results for Tristan Thompson:

You searched for "Anderson Varejão"
1 result found.
Anderson Varejao
Results for Anderson Varejao:

You searched for "Dion Waiters"
1 result found.
Dion Waiters
Results for Dion Waiters:

You searched for "Luke Walton"
6 results found.
0: Luke Walton
1: Luke Jackson
2: Luke Jackson
3: Bill Walton
4: Lloyd Walton
5: Luke Witte
Pick one: 0
Results for Luke Walton:

You searched for "Tyler Zeller"
4 results found.
0: Tyler Zeller
1: Dave Zeller
2: Luke Zeller
3: Tyler Herro
Pick one: 0
Results for Tyler Zeller:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-11-13,30-046,CLE,AWAY,BRK,L (-13),1,37:29,16,21,...,18,3,2,0,1,2,35,38.8,4,Anderson Varejão
1,2014-04-05,22-013,CLE,HOME,CHA,L (-2),1,42:35,16,31,...,7,8,3,0,3,3,44,35.6,3,Kyrie Irving
2,2013-12-10,21-262,CLE,HOME,NYK,W (+15),1,36:10,14,23,...,1,11,1,0,1,0,37,34.1,20,Kyrie Irving
3,2012-12-15,20-267,CLE,AWAY,NYK,L (-1),1,39:14,15,25,...,5,5,1,0,3,3,41,31.3,8,Kyrie Irving
4,2013-01-09,20-292,CLE,HOME,ATL,W (+16),1,33:12,11,15,...,1,4,3,0,2,1,33,30.6,15,Kyrie Irving

In [20]:
CLE_2014_gamelog = []

for p in CLE_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2014_gamelog.append(player_log)
CLE_2014_gamelog = pd.concat(CLE_2014_gamelog)    
CLE_2014_gamelogs = CLE_2014_gamelog.copy()
CLE_2014_gamelogs['GAME_SCORE'] = CLE_2014_gamelogs['GAME_SCORE'].astype(float)
CLE_2014_games = CLE_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2014_games_csv = CLE_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2014_games.csv', index=False)
CLE_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2014_games.csv')
CLE_2014_games_proc.head()

You searched for "Anthony Bennett"
3 results found.
0: Anthony Bennett
1: Tony Bennett
2: Anthony Bonner
Pick one: 0
Results for Anthony Bennett:

You searched for "Andrew Bynum"
4 results found.
0: Andrew Bynum
1: Andrew Bogut
2: Andrew Lang
3: Andrew Toney
Pick one: 0
Results for Andrew Bynum:

You searched for "Earl Clark"
7 results found.
0: Earl Clark
1: Gary Clark
2: Carlos Clark
3: Ian Clark
4: Keon Clark
5: Earl Evans
6: Earl Lloyd
Pick one: 0
Results for Earl Clark:

You searched for "Seth Curry"
4 results found.
0: Seth Curry
1: Dell Curry
2: Eddy Curry
3: Stephen Curry
Pick one: 0
Results for Seth Curry:

You searched for "Matthew Dellavedova"
1 result found.
Matthew Dellavedova
Results for Matthew Dellavedova:

You searched for "Luol Deng"
1 result found.
Luol Deng
Results for Luol Deng:

You searched for "Shane Edwards"
6 results found.
0: Shane Edwards
1: Blue Edwards
2: James Edwards
3: Jay Edwards
4: John Edwards
5: Vince Edwards
Pick one: 0
Results for Shane Edwards:

You searched for "Carrick Felix"
1 result found.
Carrick Felix
Results for Carrick Felix:

You searched for "Alonzo Gee"
1 result found.
Alonzo Gee
Results for Alonzo Gee:

You searched for "Spencer Hawes"
3 results found.
0: Spencer Hawes
1: Steve Hawes
2: Spencer Haywood
Pick one: 0
Results for Spencer Hawes:

You searched for "Scotty Hopson"
1 result found.
Scotty Hopson
Results for Scotty Hopson:

You searched for "Kyrie Irving"
2 results found.
0: Kyrie Irving
1: Byron Irvin
Pick one: 0
Results for Kyrie Irving:

You searched for "Jarrett Jack"
1 result found.
Jarrett Jack
Results for Jarrett Jack:

You searched for "Sergey Karasev"
1 result found.
Sergey Karasev
Results for Sergey Karasev:

You searched for "C.J. Miles"
7 results found.
0: C.J. Miles
1: C.J. Kupec
2: B.J. Tyler
3: C.J. Wilcox
4: T.J. Leaf
5: A.J. Price
6: D.J. White
Pick one: 0
Results for C.J. Miles:

You searched for "Arinze Onuaku"
1 result found.
Arinze Onuaku
Results for Arinze Onuaku:

You searched for "Henry Sims"
5 results found.
0: Henry Sims
1: Henry James
2: Henry Akin
3: Henry Bibby
4: Henry Ward
Pick one: 0
Results for Henry Sims:

You searched for "Tristan Thompson"
1 result found.
Tristan Thompson
Results for Tristan Thompson:

You searched for "Anderson Varejão"
1 result found.
Anderson Varejao
Results for Anderson Varejao:

You searched for "Dion Waiters"
1 result found.
Dion Waiters
Results for Dion Waiters:

You searched for "Tyler Zeller"
4 results found.
0: Tyler Zeller
1: Dave Zeller
2: Luke Zeller
3: Tyler Herro
Pick one: 0
Results for Tyler Zeller:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-04-05,22-013,CLE,HOME,CHA,L (-2),1,42:35,16,31,...,7,8,3,0,3,3,44,35.6,3,Kyrie Irving
1,2013-12-10,21-262,CLE,HOME,NYK,W (+15),1,36:10,14,23,...,1,11,1,0,1,0,37,34.1,20,Kyrie Irving
2,2014-01-07,26-295,CLE,HOME,PHI,W (+18),1,31:24,11,18,...,5,2,2,0,0,3,34,29.9,32,C.J. Miles
3,2014-02-26,21-340,CLE,AWAY,OKC,W (+10),1,42:52,10,19,...,5,9,4,0,3,2,31,29.7,4,Kyrie Irving
4,2013-12-20,21-272,CLE,HOME,MIL,W (+3),1,42:13,13,25,...,3,6,0,4,4,2,39,29.4,1,Kyrie Irving

In [21]:
CLE_2015_gamelog = []

for p in CLE_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2015_gamelog.append(player_log)
CLE_2015_gamelog = pd.concat(CLE_2015_gamelog)    
CLE_2015_gamelogs = CLE_2015_gamelog.copy()
CLE_2015_gamelogs['GAME_SCORE'] = CLE_2015_gamelogs['GAME_SCORE'].astype(float)
CLE_2015_games = CLE_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2015_games_csv = CLE_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2015_games.csv', index=False)
CLE_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2015_games.csv')
CLE_2015_games_proc.head()

You searched for "Lou Amundson"
2 results found.
0: Lou Amundson
1: Lou Hudson
Pick one: 0
Results for Lou Amundson:

You searched for "Will Cherry"
4 results found.
0: Will Cherry
1: Will Conroy
2: Bill Henry
3: Dell Curry
Pick one: 0
Results for Will Cherry:

You searched for "Matthew Dellavedova"
1 result found.
Matthew Dellavedova
Results for Matthew Dellavedova:

You searched for "Joe Harris"
20 results found.
0: Joe Harris
1: Bob Harris
2: Jalen Harris
3: John Garris
4: John Hargis
5: Art Harris
6: Mike Harris
7: Tony Harris
8: Moe Barr
9: Jon Barry
10: Joe Ellis
11: Joe Hamood
12: Gary Harris
13: Steve Harris
14: Bob Harrison
15: Jim Jarvis
16: Joe Dumars
17: Ron Harper
18: Joe Thomas
19: Jason Hart
Pick one: 0
Results for Joe Harris:

You searched for "Brendan Haywood"
1 result found.
Brendan Haywood
Results for Brendan Haywood:

You searched for "Kyrie Irving"
2 results found.
0: Kyrie Irving
1: Byron Irvin
Pick one: 0
Results for Kyrie Irving:

You searched for "LeBron James"
5 results found.
0: LeBron James
1: Aaron James
2: Damion James
3: Henry James
4: Jerome James
Pick one: 0
Results for LeBron James:

You searched for "James Jones"
32 results found.
0: James Jones
1: Jake Jones
2: Jalen Jones
3: James Ennis
4: Damon Jones
5: Jimmy Jones
6: Sam Jones
7: James Posey
8: Tre Jones
9: Mason Jones
10: James Johnson
11: Charles Jones
12: Charles Jones
13: Charles Jones
14: Damian Jones
15: Earl Jones
16: Fred Jones
17: Larry Jones
18: Major Jones
19: Mark Jones
20: Mark Jones
21: Tyus Jones
22: Wali Jones
23: James Lang
24: James Silas
25: James Thomas
26: James Wilkes
27: James Young
28: James Cotton
29: James Scott
30: James Webb
31: James White
Pick one: 0
Results for James Jones:

You searched for "Alex Kirk"
6 results found.
0: Alex Kirk
1: Walt Kirk
2: Alex Acker
3: Alec Burks
4: Alex Len
5: Leo Klier
Pick one: 0
Results for Alex Kirk:

You searched for "Kevin Love"
15 results found.
0: Kevin Love
1: Kevin Loder
2: Kevin Jones
3: Kevin Joyce
4: Kevin Ollie
5: Kevin Grevey
6: Kevin Hervey
7: Kevin Knox
8: Kevon Looney
9: Stan Love
10: Kevin Lynch
11: Kevin Porter
12: Kevin Porter
13: Kelvin Cato
14: Melvin Ely
Pick one: 0
Results for Kevin Love:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Timofey Mozgov"
1 result found.
Timofey Mozgov
Results for Timofey Mozgov:

You searched for "Kendrick Perkins"
1 result found.
Kendrick Perkins
Results for Kendrick Perkins:

You searched for "A.J. Price"
6 results found.
0: A.J. Price
1: Jim Price
2: Mark Price
3: Mike Price
4: Tony Price
5: D.J. White
Pick one: 0
Results for A.J. Price:

You searched for "Iman Shumpert"
1 result found.
Iman Shumpert
Results for Iman Shumpert:

You searched for "J.R. Smith"
35 results found.
0: J.R. Smith
1: Jerry Smith
2: Jim Smith
3: Joe Smith
4: John Smith
5: Josh Smith
6: Jalen Smith
7: J.R. Reid
8: Al Smith
9: Bill Smith
10: Chris Smith
11: Chris Smith
12: Deb Smith
13: Derek Smith
14: Don Smith
15: Don Smith
16: Doug Smith
17: Ed Smith
18: Greg Smith
19: Greg Smith
20: Ish Smith
21: Jabari Smith
22: Jason Smith
23: Ken Smith
24: Larry Smith
25: Leon Smith
26: Mike Smith
27: Otis Smith
28: Pete Smith
29: Phil Smith
30: Russ Smith
31: Sam Smith
32: Sam Smith
33: Tony Smith
34: Joe Smyth
Pick one: 0
Results for J.R. Smith:

You searched for "Tristan Thompson"
1 result found.
Tristan Thompson
Results for Tristan Thompson:

You searched for "Anderson Varejão"
1 result found.
Anderson Varejao
Results for Anderson Varejao:

You searched for "Dion Waiters"
1 result found.
Dion Waiters
Results for Dion Waiters:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-03-12,22-354,CLE,AWAY,SAS,W (+3),1,46:34,20,32,...,3,5,4,0,2,3,57,48.2,5,Kyrie Irving
1,2015-01-28,22-311,CLE,HOME,POR,W (+5),1,38:35,17,36,...,4,5,2,0,3,0,55,41.1,12,Kyrie Irving
2,2014-12-12,29-347,CLE,AWAY,NOP,L (-5),1,37:37,17,24,...,5,5,0,1,2,1,41,33.1,-3,LeBron James
3,2015-01-27,22-310,CLE,AWAY,DET,W (+8),1,41:54,13,23,...,3,6,3,1,3,2,38,32.5,8,Kyrie Irving
4,2015-02-26,30-058,CLE,HOME,GSW,W (+11),1,36:12,15,25,...,11,5,3,1,6,5,42,32.2,9,LeBron James

In [23]:
# mo williams

CLE_2016_gamelog = []

for p in CLE_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2016_gamelog.append(player_log)
CLE_2016_gamelog = pd.concat(CLE_2016_gamelog)    
CLE_2016_gamelogs = CLE_2016_gamelog.copy()
CLE_2016_gamelogs['GAME_SCORE'] = CLE_2016_gamelogs['GAME_SCORE'].astype(float)
CLE_2016_games = CLE_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2016_games_csv = CLE_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2016_games.csv', index=False)
CLE_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2016_games.csv')
CLE_2016_games_proc.head()

You searched for "Jared Cunningham"
2 results found.
0: Jared Cunningham
1: Dante Cunningham
Pick one: 0
Results for Jared Cunningham:

You searched for "Matthew Dellavedova"
1 result found.
Matthew Dellavedova
Results for Matthew Dellavedova:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Joe Harris"
20 results found.
0: Joe Harris
1: Bob Harris
2: Jalen Harris
3: John Garris
4: John Hargis
5: Art Harris
6: Mike Harris
7: Tony Harris
8: Moe Barr
9: Jon Barry
10: Joe Ellis
11: Joe Hamood
12: Gary Harris
13: Steve Harris
14: Bob Harrison
15: Jim Jarvis
16: Joe Dumars
17: Ron Harper
18: Joe Thomas
19: Jason Hart
Pick one: 0
Results for Joe Harris:

You searched for "Kyrie Irving"
2 results found.
0: Kyrie Irving
1: Byron Irvin
Pick one: 0
Results for Kyrie Irving:

You searched for "LeBron James"
5 results found.
0: LeBron James
1: Aaron James
2: Damion James
3: Henry James
4: Jerome James
Pick one: 0
Results for LeBron James:

You searched for "Richard Jefferson"
2 results found.
0: Richard Jefferson
1: Richard Anderson
Pick one: 0
Results for Richard Jefferson:

You searched for "Dahntay Jones"
5 results found.
0: Dahntay Jones
1: Damian Jones
2: Dontae' Jones
3: Johnny Jones
4: Wah Wah Jones
Pick one: 0
Results for Dahntay Jones:

You searched for "James Jones"
32 results found.
0: James Jones
1: Jake Jones
2: Jalen Jones
3: James Ennis
4: Damon Jones
5: Jimmy Jones
6: Sam Jones
7: James Posey
8: Tre Jones
9: Mason Jones
10: James Johnson
11: Charles Jones
12: Charles Jones
13: Charles Jones
14: Damian Jones
15: Earl Jones
16: Fred Jones
17: Larry Jones
18: Major Jones
19: Mark Jones
20: Mark Jones
21: Tyus Jones
22: Wali Jones
23: James Lang
24: James Silas
25: James Thomas
26: James Wilkes
27: James Young
28: James Cotton
29: James Scott
30: James Webb
31: James White
Pick one: 0
Results for James Jones:

You searched for "Sasha Kaun"
1 result found.
Sasha Kaun
Results for Sasha Kaun:

You searched for "Kevin Love"
15 results found.
0: Kevin Love
1: Kevin Loder
2: Kevin Jones
3: Kevin Joyce
4: Kevin Ollie
5: Kevin Grevey
6: Kevin Hervey
7: Kevin Knox
8: Kevon Looney
9: Stan Love
10: Kevin Lynch
11: Kevin Porter
12: Kevin Porter
13: Kelvin Cato
14: Melvin Ely
Pick one: 0
Results for Kevin Love:

You searched for "Jordan McRae"
9 results found.
0: Jordan McRae
1: Jordan Nwora
2: Jordan Ford
3: Jordan Bone
4: Jordan Farmar
5: Jordan Mickey
6: Jordan Poole
7: Jordan Adams
8: Jordan Bell
Pick one: 0
Results for Jordan McRae:

You searched for "Timofey Mozgov"
1 result found.
Timofey Mozgov
Results for Timofey Mozgov:

You searched for "Iman Shumpert"
1 result found.
Iman Shumpert
Results for Iman Shumpert:

You searched for "J.R. Smith"
35 results found.
0: J.R. Smith
1: Jerry Smith
2: Jim Smith
3: Joe Smith
4: John Smith
5: Josh Smith
6: Jalen Smith
7: J.R. Reid
8: Al Smith
9: Bill Smith
10: Chris Smith
11: Chris Smith
12: Deb Smith
13: Derek Smith
14: Don Smith
15: Don Smith
16: Doug Smith
17: Ed Smith
18: Greg Smith
19: Greg Smith
20: Ish Smith
21: Jabari Smith
22: Jason Smith
23: Ken Smith
24: Larry Smith
25: Leon Smith
26: Mike Smith
27: Otis Smith
28: Pete Smith
29: Phil Smith
30: Russ Smith
31: Sam Smith
32: Sam Smith
33: Tony Smith
34: Joe Smyth
Pick one: 0
Results for J.R. Smith:

You searched for "Tristan Thompson"
1 result found.
Tristan Thompson
Results for Tristan Thompson:

You searched for "Anderson Varejão"
1 result found.
Anderson Varejao
Results for Anderson Varejao:

You searched for "Mo Williams"
40 results found.
0: Mo Williams
1: Al Williams
2: Bob Williams
3: Lou Williams
4: Rob Williams
5: Ron Williams
6: Art Williams
7: Fly Williams
8: Gus Williams
9: Guy Williams
10: Jay Williams
11: John Williams
12: Matt Williams
13: Mike Williams
14: Milt Williams
15: Monty Williams
16: Ray Williams
17: Sam Williams
18: Sam Williams
19: Sly Williams
20: Troy Williams
21: Aaron Williams
22: Alan Williams
23: Buck Williams
24: C.J. Williams
25: Corey Williams
26: Deron Williams
27: Duck Williams
28: Earl Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Nate Williams
35: Pete Williams
36: Scott Williams
37: Sean Williams
38: Walt Williams
39: Ward Williams
Pick one: 0
Results for Mo Williams:

AttributeError: 'NoneType' object has no attribute 'replace'

In [26]:
# mike dunleavy 
CLE_2017_gamelog = []

for p in CLE_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2017_gamelog.append(player_log)
CLE_2017_gamelog = pd.concat(CLE_2017_gamelog)    
CLE_2017_gamelogs = CLE_2017_gamelog.copy()
CLE_2017_gamelogs['GAME_SCORE'] = CLE_2017_gamelogs['GAME_SCORE'].astype(float)
CLE_2017_games = CLE_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2017_games_csv = CLE_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2017_games.csv', index=False)
CLE_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2017_games.csv')
CLE_2017_games_proc.head()

You searched for "Chris Andersen"
4 results found.
0: Chris Andersen
1: David Andersen
2: Eric Anderson
3: Chris Herren
Pick one: 0
Results for Chris Andersen:

You searched for "Andrew Bogut"
4 results found.
0: Andrew Bogut
1: Andrew Bynum
2: Andrew Toney
3: Andrew Gaze
Pick one: 0
Results for Andrew Bogut:

You searched for "Mike Dunleavy"
3 results found.
0: Mike Dunleavy
1: Mike Dunleavy
2: Mike Conley
Pick one: 0
Results for Mike Dunleavy:

TypeError: 'NoneType' object does not support item assignment

In [27]:
# ;larry nance
CLE_2018_gamelog = []

for p in CLE_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2018_gamelog.append(player_log)
CLE_2018_gamelog = pd.concat(CLE_2018_gamelog)    
CLE_2018_gamelogs = CLE_2018_gamelog.copy()
CLE_2018_gamelogs['GAME_SCORE'] = CLE_2018_gamelogs['GAME_SCORE'].astype(float)
CLE_2018_games = CLE_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2018_games_csv = CLE_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2018_games.csv', index=False)
CLE_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2018_games.csv')
CLE_2018_games_proc.head()

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Jordan Clarkson"
1 result found.
Jordan Clarkson
Results for Jordan Clarkson:

You searched for "Jae Crowder"
4 results found.
0: Jae Crowder
1: Joe Cooper
2: Corey Crowder
3: Joe Strawder
Pick one: 0
Results for Jae Crowder:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Jeff Green"
21 results found.
0: Jeff Green
1: Josh Green
2: Jeff Adrien
3: Jeff Grayer
4: Ken Green
5: Sean Green
6: Jeff Ayres
7: Jeff Cross
8: A.C. Green
9: Devin Green
10: Kenny Green
11: Mike Green
12: Si Green
13: Steve Green
14: Jeff Lebo
15: Jeff Martin
16: Jeff Turner
17: Jeff Webb
18: Jeff Foote
19: Jeff Slade
20: Jeff Teague
Pick one: 0
Results for Jeff Green:

You searched for "George Hill"
11 results found.
0: George Hill
1: George Karl
2: George King
3: George King
4: Gary Hill
5: George Lee
6: George Mikan
7: George Wilson
8: George Zidek
9: George Bucci
10: George Lynch
Pick one: 0
Results for George Hill:

You searched for "John Holland"
11 results found.
0: John Holland
1: Joe Holland
2: John Collins
3: Brad Holland
4: John Logan
5: John Wallace
6: John Douglas
7: Johnny Horan
8: John Oldham
9: John Mandic
10: John Tschogl
Pick one: 0
Results for John Holland:

You searched for "Rodney Hood"
4 results found.
0: Rodney Hood
1: Rodney Buford
2: Rodney Monroe
3: Rodney White
Pick one: 0
Results for Rodney Hood:

You searched for "LeBron James"
5 results found.
0: LeBron James
1: Aaron James
2: Damion James
3: Henry James
4: Jerome James
Pick one: 0
Results for LeBron James:

You searched for "Kyle Korver"
3 results found.
0: Kyle Korver
1: Kyle Weaver
2: Kyle Lowry
Pick one: 0
Results for Kyle Korver:

You searched for "Kevin Love"
15 results found.
0: Kevin Love
1: Kevin Loder
2: Kevin Jones
3: Kevin Joyce
4: Kevin Ollie
5: Kevin Grevey
6: Kevin Hervey
7: Kevin Knox
8: Kevon Looney
9: Stan Love
10: Kevin Lynch
11: Kevin Porter
12: Kevin Porter
13: Kelvin Cato
14: Melvin Ely
Pick one: 0
Results for Kevin Love:

You searched for "Larry Nance"
17 results found.
0: Larry Nance
1: Larry Nance
2: Larry Bunce
3: Larry Finch
4: Larry Cannon
5: Larry Conley
6: Larry Fogle
7: Larry Jones
8: Larry Kenon
9: Larry Moore
10: Larry Sanders
11: Larry Brown
12: Larry Demic
13: Larry Drew
14: Larry Drew
15: Larry Mikan
16: Larry Owens
Pick one: 0
Results for Larry Nance:

TypeError: 'NoneType' object does not support item assignment

In [28]:
# larry nance
CLE_2019_gamelog = []

for p in CLE_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2019_gamelog.append(player_log)
CLE_2019_gamelog = pd.concat(CLE_2019_gamelog)    
CLE_2019_gamelogs = CLE_2019_gamelog.copy()
CLE_2019_gamelogs['GAME_SCORE'] = CLE_2019_gamelogs['GAME_SCORE'].astype(float)
CLE_2019_games = CLE_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2019_games_csv = CLE_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2019_games.csv', index=False)
CLE_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2019_games.csv')
CLE_2019_games_proc.head()

You searched for "Deng Adel"
5 results found.
0: Deng Adel
1: Don Dee
2: Deng Gai
3: Dean Wade
4: Don Grate
Pick one: 0
Results for Deng Adel:

You searched for "Jaron Blossomgame"
1 result found.
Jaron Blossomgame
Results for Jaron Blossomgame:

You searched for "Alec Burks"
3 results found.
0: Alec Burks
1: Trey Burke
2: Alex Kirk
Pick one: 0
Results for Alec Burks:

You searched for "Marquese Chriss"
1 result found.
Marquese Chriss
Results for Marquese Chriss:

You searched for "Jordan Clarkson"
1 result found.
Jordan Clarkson
Results for Jordan Clarkson:

You searched for "Sam Dekker"
1 result found.
Sam Dekker
Results for Sam Dekker:

You searched for "Matthew Dellavedova"
1 result found.
Matthew Dellavedova
Results for Matthew Dellavedova:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Andrew Harrison"
2 results found.
0: Andrew Harrison
1: Aaron Harrison
Pick one: 0
Results for Andrew Harrison:

You searched for "George Hill"
11 results found.
0: George Hill
1: George Karl
2: George King
3: George King
4: Gary Hill
5: George Lee
6: George Mikan
7: George Wilson
8: George Zidek
9: George Bucci
10: George Lynch
Pick one: 0
Results for George Hill:

You searched for "John Holland"
11 results found.
0: John Holland
1: Joe Holland
2: John Collins
3: Brad Holland
4: John Logan
5: John Wallace
6: John Douglas
7: Johnny Horan
8: John Oldham
9: John Mandic
10: John Tschogl
Pick one: 0
Results for John Holland:

You searched for "Rodney Hood"
4 results found.
0: Rodney Hood
1: Rodney Buford
2: Rodney Monroe
3: Rodney White
Pick one: 0
Results for Rodney Hood:

You searched for "Jalen Jones"
27 results found.
0: Jalen Jones
1: Jake Jones
2: James Jones
3: Mason Jones
4: Alvin Jones
5: Damon Jones
6: Wali Jones
7: Jalen Rose
8: Tre Jones
9: Bill Jones
10: Charles Jones
11: Charles Jones
12: Charles Jones
13: Damian Jones
14: Earl Jones
15: Fred Jones
16: Jimmy Jones
17: Johnny Jones
18: Kevin Jones
19: Larry Jones
20: Major Jones
21: Mark Jones
22: Mark Jones
23: Robin Jones
24: Sam Jones
25: Wil Jones
26: Jaylen Brown
Pick one: 0
Results for Jalen Jones:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "Kyle Korver"
3 results found.
0: Kyle Korver
1: Kyle Weaver
2: Kyle Lowry
Pick one: 0
Results for Kyle Korver:

You searched for "Kevin Love"
15 results found.
0: Kevin Love
1: Kevin Loder
2: Kevin Jones
3: Kevin Joyce
4: Kevin Ollie
5: Kevin Grevey
6: Kevin Hervey
7: Kevin Knox
8: Kevon Looney
9: Stan Love
10: Kevin Lynch
11: Kevin Porter
12: Kevin Porter
13: Kelvin Cato
14: Melvin Ely
Pick one: 0
Results for Kevin Love:

You searched for "Patrick McCaw"
1 result found.
Patrick McCaw
Results for Patrick McCaw:

You searched for "Larry Nance"
17 results found.
0: Larry Nance
1: Larry Nance
2: Larry Bunce
3: Larry Finch
4: Larry Cannon
5: Larry Conley
6: Larry Fogle
7: Larry Jones
8: Larry Kenon
9: Larry Moore
10: Larry Sanders
11: Larry Brown
12: Larry Demic
13: Larry Drew
14: Larry Drew
15: Larry Mikan
16: Larry Owens
Pick one: 0
Results for Larry Nance:

TypeError: 'NoneType' object does not support item assignment

In [29]:
# larry nance
CLE_2020_gamelog = []

for p in CLE_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2020_gamelog.append(player_log)
CLE_2020_gamelog = pd.concat(CLE_2020_gamelog)    
CLE_2020_gamelogs = CLE_2020_gamelog.copy()
CLE_2020_gamelogs['GAME_SCORE'] = CLE_2020_gamelogs['GAME_SCORE'].astype(float)
CLE_2020_games = CLE_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2020_games_csv = CLE_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2020_games.csv', index=False)
CLE_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2020_games.csv')
CLE_2020_games_proc.head()

You searched for "Marques Bolden"
1 result found.
Marques Bolden
Results for Marques Bolden:

You searched for "Jordan Clarkson"
1 result found.
Jordan Clarkson
Results for Jordan Clarkson:

You searched for "Tyler Cook"
8 results found.
0: Tyler Cook
1: Tyler Bey
2: Bert Cook
3: Omar Cook
4: Tyler Lydon
5: Tyler Ulis
6: Joe Cooke
7: Tyler Herro
Pick one: 0
Results for Tyler Cook:

You searched for "Matthew Dellavedova"
1 result found.
Matthew Dellavedova
Results for Matthew Dellavedova:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Dante Exum"
1 result found.
Dante Exum
Results for Dante Exum:

You searched for "Darius Garland"
3 results found.
0: Darius Garland
1: Gary Garland
2: Darius Songaila
Pick one: 0
Results for Darius Garland:

You searched for "John Henson"
23 results found.
0: John Henson
1: John Johnson
2: John Paxson
3: John Clawson
4: John Dickson
5: John Hazen
6: Jack Hewson
7: Roy Hinson
8: John Jenkins
9: John Morton
10: Don Nelson
11: Ron Nelson
12: John Pinone
13: John Thompson
14: John Windsor
15: John Chaney
16: John Hargis
17: John Hummer
18: John Long
19: John Mahnken
20: Johan Petro
21: John Warren
22: John Thomas
Pick one: 0
Results for John Henson:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "Kevin Love"
15 results found.
0: Kevin Love
1: Kevin Loder
2: Kevin Jones
3: Kevin Joyce
4: Kevin Ollie
5: Kevin Grevey
6: Kevin Hervey
7: Kevin Knox
8: Kevon Looney
9: Stan Love
10: Kevin Lynch
11: Kevin Porter
12: Kevin Porter
13: Kelvin Cato
14: Melvin Ely
Pick one: 0
Results for Kevin Love:

You searched for "J.P. Macura"
1 result found.
J.P. Macura
Results for J.P. Macura:

You searched for "Alfonzo McKinnie"
1 result found.
Alfonzo McKinnie
Results for Alfonzo McKinnie:

You searched for "Matt Mooney"
5 results found.
0: Matt Mooney
1: Matt Maloney
2: Matt Bonner
3: Matt Barnes
4: Jim Mooney
Pick one: 0
Results for Matt Mooney:

You searched for "Larry Nance"
17 results found.
0: Larry Nance
1: Larry Nance
2: Larry Bunce
3: Larry Finch
4: Larry Cannon
5: Larry Conley
6: Larry Fogle
7: Larry Jones
8: Larry Kenon
9: Larry Moore
10: Larry Sanders
11: Larry Brown
12: Larry Demic
13: Larry Drew
14: Larry Drew
15: Larry Mikan
16: Larry Owens
Pick one: 0
Results for Larry Nance:

TypeError: 'NoneType' object does not support item assignment

In [30]:
# larry nance
CLE_2021_gamelog = []

for p in CLE_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    CLE_2021_gamelog.append(player_log)
CLE_2021_gamelog = pd.concat(CLE_2021_gamelog)    
CLE_2021_gamelogs = CLE_2021_gamelog.copy()
CLE_2021_gamelogs['GAME_SCORE'] = CLE_2021_gamelogs['GAME_SCORE'].astype(float)
CLE_2021_games = CLE_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_2021_games_csv = CLE_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2021_games.csv', index=False)
CLE_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/CLE/CLE_2021_games.csv')
CLE_2021_games_proc.head()

You searched for "Jarrett Allen"
2 results found.
0: Jarrett Allen
1: Jarrett Culver
Pick one: 0
Results for Jarrett Allen:

You searched for "Marques Bolden"
1 result found.
Marques Bolden
Results for Marques Bolden:

You searched for "Quinn Cook"
3 results found.
0: Quinn Cook
1: Brian Cook
2: Quincy Acy
Pick one: 0
Results for Quinn Cook:

You searched for "Matthew Dellavedova"
1 result found.
Matthew Dellavedova
Results for Matthew Dellavedova:

You searched for "Damyean Dotson"
1 result found.
Damyean Dotson
Results for Damyean Dotson:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Dante Exum"
1 result found.
Dante Exum
Results for Dante Exum:

You searched for "Yogi Ferrell"
1 result found.
Yogi Ferrell
Results for Yogi Ferrell:

You searched for "Darius Garland"
3 results found.
0: Darius Garland
1: Gary Garland
2: Darius Songaila
Pick one: 0
Results for Darius Garland:

You searched for "Isaiah Hartenstein"
1 result found.
Isaiah Hartenstein
Results for Isaiah Hartenstein:

You searched for "Mfiondu Kabengele"
1 result found.
Mfiondu Kabengele
Results for Mfiondu Kabengele:

You searched for "Kevin Love"
15 results found.
0: Kevin Love
1: Kevin Loder
2: Kevin Jones
3: Kevin Joyce
4: Kevin Ollie
5: Kevin Grevey
6: Kevin Hervey
7: Kevin Knox
8: Kevon Looney
9: Stan Love
10: Kevin Lynch
11: Kevin Porter
12: Kevin Porter
13: Kelvin Cato
14: Melvin Ely
Pick one: 0
Results for Kevin Love:

You searched for "Thon Maker"
8 results found.
0: Thon Maker
1: Ron Baker
2: Vin Baker
3: Tom Barker
4: Tharon Mayes
5: Tony Parker
6: Tom Riker
7: Von Wafer
Pick one: 0
Results for Thon Maker:

You searched for "Jeremiah Martin"
1 result found.
Jeremiah Martin
Results for Jeremiah Martin:

You searched for "JaVale McGee"
1 result found.
JaVale McGee
Results for JaVale McGee:

You searched for "Larry Nance"
17 results found.
0: Larry Nance
1: Larry Nance
2: Larry Bunce
3: Larry Finch
4: Larry Cannon
5: Larry Conley
6: Larry Fogle
7: Larry Jones
8: Larry Kenon
9: Larry Moore
10: Larry Sanders
11: Larry Brown
12: Larry Demic
13: Larry Drew
14: Larry Drew
15: Larry Mikan
16: Larry Owens
Pick one: 0
Results for Larry Nance:

TypeError: 'NoneType' object does not support item assignment

## combine all seasons

In [33]:
CLE_season_dfs = [CLE_2002_games, CLE_2003_games, CLE_2004_games, CLE_2012_games, CLE_2013_games,
                 CLE_2014_games, CLE_2015_games]

In [34]:
CLE_all = pd.concat(CLE_season_dfs)
CLE_all_sorted = CLE_all.sort_values(by=['GAME_SCORE'], ascending=False)
CLE_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
69,2015-03-12,22-354,CLE,AWAY,SAS,W (+3),1,46:34,20,32,...,3,5,4,0,2,3,57,48.2,+5,Kyrie Irving
48,2015-01-28,22-311,CLE,HOME,POR,W (+5),1,38:35,17,36,...,4,5,2,0,3,0,55,41.1,+12,Kyrie Irving
24,2002-12-13,23-081,CLE,AWAY,BOS,L (-15),1,43:54,17,26,...,4,8,3,0,0,1,42,39.6,-9,Ricky Davis
74,2004-03-27,19-088,CLE,HOME,NJN,W (+3),1,43:48,15,29,...,6,13,3,0,2,1,41,39.0,+10,LeBron James
7,2012-11-13,30-046,CLE,AWAY,BRK,L (-13),1,37:29,16,21,...,18,3,2,0,1,2,35,38.8,+4,Anderson Varejão
28,2002-12-20,23-088,CLE,AWAY,DET,L (-2),1,50:21,13,25,...,8,7,3,1,2,2,42,37.9,-1,Ricky Davis
25,2001-12-19,25-275,CLE,AWAY,BOS,L (-6),1,37:59,14,18,...,8,5,3,0,1,4,36,37.3,-1,Andre Miller
17,2001-12-04,25-260,CLE,HOME,DET,W (+12),1,35:14,12,16,...,8,11,3,3,6,2,34,36.4,+9,Andre Miller
80,2014-04-05,22-013,CLE,HOME,CHA,L (-2),1,42:35,16,31,...,7,8,3,0,3,3,44,35.6,+3,Kyrie Irving
80,2014-04-05,22-013,CLE,HOME,CHA,L (-2),1,42:35,16,31,...,7,8,3,0,3,3,44,35.6,+3,Kyrie Irving
21,2013-12-10,21-262,CLE,HOME,NYK,W (+15),1,36:10,14,23,...,1,11,1,0,1,0,37,34.1,+20,Kyrie Irving
21,2013-12-10,21-262,CLE,HOME,NYK,W (+15),1,36:10,14,23,...,1,11,1,0,1,0,37,34.1,+20,Kyrie Irving
22,2014-12-12,29-347,CLE,AWAY,NOP,L (-5),1,37:37,17,24,...,5,5,0,1,2,1,41,33.1,-3,LeBron James
72,2003-03-25,23-183,CLE,HOME,GSW,W (+21),1,40:26,13,20,...,4,11,3,3,0,2,28,32.8,+19,Ricky Davis
47,2002-02-16,28-302,CLE,AWAY,CHI,W (+13),1,41:03,14,23,...,12,2,0,0,0,1,37,32.7,+16,Lamond Murray
42,2004-01-20,22-061,CLE,HOME,SEA,W (+5),1,40:28,9,20,...,20,4,1,1,1,3,32,32.7,+14,Carlos Boozer
47,2015-01-27,22-310,CLE,AWAY,DET,W (+8),1,41:54,13,23,...,3,6,3,1,3,2,38,32.5,+8,Kyrie Irving
60,2015-02-26,30-058,CLE,HOME,GSW,W (+11),1,36:12,15,25,...,11,5,3,1,6,5,42,32.2,+9,LeBron James
82,2002-04-13,26-025,CLE,AWAY,ATL,L (-5),1,46:04,10,19,...,6,16,3,0,2,2,27,32.1,+2,Andre Miller
42,2015-01-16,22-299,CLE,AWAY,LAC,W (+5),1,41:05,12,18,...,4,5,3,1,4,4,37,32.0,+5,Kyrie Irving
50,2002-02-12,25-330,CLE,HOME,TOR,W (+18),1,39:52,8,14,...,10,17,4,0,2,4,22,31.5,+14,Andre Miller
40,2004-01-17,22-058,CLE,AWAY,UTA,W (+6),1,43:20,12,20,...,18,1,2,1,1,3,32,31.4,+24,Carlos Boozer
78,2002-04-06,26-018,CLE,HOME,CHI,W (+19),1,36:17,8,14,...,3,16,7,0,3,3,23,31.3,+10,Andre Miller
25,2012-12-15,20-267,CLE,AWAY,NYK,L (-1),1,39:14,15,25,...,5,5,1,0,3,3,41,31.3,+8,Kyrie Irving
12,2014-11-24,29-329,CLE,HOME,ORL,W (+32),1,31:00,9,17,...,4,11,3,0,1,0,29,31.2,+19,LeBron James