In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2014-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_DAL = []

# DAL
while season <= 2021:
    df_DAL = get_roster('DAL', season)
    df_DAL['Season'] = season
    df_DAL['Team'] = 'DAL'
    appended_data_DAL.append(df_DAL)
    season = season + 1
appended_data_DAL = pd.concat(appended_data_DAL)

In [4]:
DAL_df_all = appended_data_DAL.copy()
DAL_df_all_csv = DAL_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_players_all.csv', index=False)
DAL_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_players_all.csv')
DAL_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,44,Shawn Bradley,C,7-6,235,1972-03-22,DE,6,BYU,2000,DAL
1,21,Greg Buckner,SG,6-4,210,1976-09-16,US,R,Clemson,2000,DAL
2,23,Cedric Ceballos,SF,6-6,190,1969-08-02,US,9,Cal State Fullerton,2000,DAL
3,24,Hubert Davis,PG,6-5,183,1970-05-17,US,7,UNC,2000,DAL
4,4,Michael Finley,SF,6-7,215,1973-03-06,US,4,Wisconsin,2000,DAL

In [5]:
DAL_df_2000 = DAL_df_all[DAL_df_all['Season'] == 2000]
DAL_df_2001 = DAL_df_all[DAL_df_all['Season'] == 2001]
DAL_df_2002 = DAL_df_all[DAL_df_all['Season'] == 2002]
DAL_df_2003 = DAL_df_all[DAL_df_all['Season'] == 2003]
DAL_df_2004 = DAL_df_all[DAL_df_all['Season'] == 2004]
DAL_df_2005 = DAL_df_all[DAL_df_all['Season'] == 2005]
DAL_df_2006 = DAL_df_all[DAL_df_all['Season'] == 2006]
DAL_df_2007 = DAL_df_all[DAL_df_all['Season'] == 2007]
DAL_df_2008 = DAL_df_all[DAL_df_all['Season'] == 2008]
DAL_df_2009 = DAL_df_all[DAL_df_all['Season'] == 2009]
DAL_df_2010 = DAL_df_all[DAL_df_all['Season'] == 2010]
DAL_df_2011 = DAL_df_all[DAL_df_all['Season'] == 2011]
DAL_df_2012 = DAL_df_all[DAL_df_all['Season'] == 2012]
DAL_df_2013 = DAL_df_all[DAL_df_all['Season'] == 2013]
DAL_df_2014 = DAL_df_all[DAL_df_all['Season'] == 2014]
DAL_df_2015 = DAL_df_all[DAL_df_all['Season'] == 2015]
DAL_df_2016 = DAL_df_all[DAL_df_all['Season'] == 2016]
DAL_df_2017 = DAL_df_all[DAL_df_all['Season'] == 2017]
DAL_df_2018 = DAL_df_all[DAL_df_all['Season'] == 2018]
DAL_df_2019 = DAL_df_all[DAL_df_all['Season'] == 2019]
DAL_df_2020 = DAL_df_all[DAL_df_all['Season'] == 2020]
DAL_df_2021 = DAL_df_all[DAL_df_all['Season'] == 2021]

In [6]:
# changing names
#DAL_df_2002.loc[DAL_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#DAL_df_2004.loc[DAL_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [7]:
DAL_df_2000_players = DAL_df_2000['PLAYER'].to_list()
DAL_df_2001_players = DAL_df_2001['PLAYER'].to_list()
DAL_df_2002_players = DAL_df_2002['PLAYER'].to_list()
DAL_df_2003_players = DAL_df_2003['PLAYER'].to_list()
DAL_df_2004_players = DAL_df_2004['PLAYER'].to_list()
DAL_df_2005_players = DAL_df_2005['PLAYER'].to_list()

DAL_df_2006_players = DAL_df_2006['PLAYER'].to_list()
DAL_df_2007_players = DAL_df_2007['PLAYER'].to_list()
DAL_df_2008_players = DAL_df_2008['PLAYER'].to_list()
DAL_df_2009_players = DAL_df_2009['PLAYER'].to_list()
DAL_df_2010_players = DAL_df_2010['PLAYER'].to_list()
DAL_df_2011_players = DAL_df_2011['PLAYER'].to_list()

DAL_df_2012_players = DAL_df_2012['PLAYER'].to_list()
DAL_df_2013_players = DAL_df_2013['PLAYER'].to_list()
DAL_df_2014_players = DAL_df_2014['PLAYER'].to_list()
DAL_df_2015_players = DAL_df_2015['PLAYER'].to_list()
DAL_df_2016_players = DAL_df_2016['PLAYER'].to_list()
DAL_df_2017_players = DAL_df_2017['PLAYER'].to_list()

DAL_df_2018_players = DAL_df_2018['PLAYER'].to_list()
DAL_df_2019_players = DAL_df_2019['PLAYER'].to_list()
DAL_df_2020_players = DAL_df_2020['PLAYER'].to_list()
DAL_df_2021_players = DAL_df_2021['PLAYER'].to_list()

## players to drop

In [64]:

#DAL_df_2004_players.remove("Mamadou N'Diaye")
#DAL_df_2005_players.remove("Didier Ilunga-Mbenga")
#DAL_df_2006_players.remove("Didier Ilunga-Mbenga")
#DAL_df_2007_players.remove("J.J. Barea")
#DAL_df_2007_players.remove("Didier Ilunga-Mbenga")
#DAL_df_2008_players.remove("J.J. Barea")

#DAL_df_2009_players.remove("Antoine Wright")
#DAL_df_2011_players.remove("Sasha Pavlović")
#DAL_df_2009_players.remove("J.J. Barea")
#DAL_df_2010_players.remove("J.J. Barea")
#DAL_df_2011_players.remove("J.J. Barea")
#DAL_df_2012_players.remove("J.J. Barea")
#DAL_df_2013_players.remove("J.J. Barea")
#DAL_df_2014_players.remove("J.J. Barea")
#DAL_df_2015_players.remove("J.J. Barea")
#DAL_df_2015_players.remove("Greg Smith")
#DAL_df_2016_players.remove("J.J. Barea")
#DAL_df_2016_players.remove("David Lee")
#DAL_df_2017_players.remove("J.J. Barea")
#DAL_df_2018_players.remove("J.J. Barea")
#DAL_df_2019_players.remove("J.J. Barea")
#DAL_df_2020_players.remove("J.J. Barea")
#DAL_df_2018_players.remove("Maxi Kleber")
#DAL_df_2018_players.remove("Dennis Smith")
#DAL_df_2019_players.remove("Maxi Kleber")
#DAL_df_2019_players.remove("Dennis Smith")
#DAL_df_2020_players.remove("Maxi Kleber")
#DAL_df_2021_players.remove("Maxi Kleber")
DAL_df_2020_players.remove("Michael Kidd-Gilchrist")

In [8]:

DAL_2000_gamelog = []



for p in DAL_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2000_gamelog.append(player_log)
DAL_2000_gamelog = pd.concat(DAL_2000_gamelog)    
DAL_2000_gamelogs = DAL_2000_gamelog.copy()
DAL_2000_gamelogs['GAME_SCORE'] = DAL_2000_gamelogs['GAME_SCORE'].astype(float)
DAL_2000_games = DAL_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2000_games_csv = DAL_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2000_games.csv', index=False)
DAL_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2000_games.csv')
DAL_2000_games_proc.head()

You searched for "Shawn Bradley"
1 result found.
Shawn Bradley
Results for Shawn Bradley:

You searched for "Greg Buckner"
4 results found.
0: Greg Buckner
1: Greg Butler
2: Greg Bunch
3: Greg Jackson
Pick one: 0
Results for Greg Buckner:

You searched for "Cedric Ceballos"
2 results found.
0: Cedric Ceballos
1: Cedric Ball
Pick one: 0
Results for Cedric Ceballos:

You searched for "Hubert Davis"
5 results found.
0: Hubert Davis
1: Aubrey Davis
2: Ben Davis
3: Harry Davis
4: Tyler Davis
Pick one: 0
Results for Hubert Davis:

You searched for "Michael Finley"
8 results found.
0: Michael Finley
1: Michael Wiley
2: Michael Ansley
3: Michael Beasley
4: Michael Bradley
5: Michael Gbinije
6: Michael Wilson
7: Michael Ruffin
Pick one: 0
Results for Michael Finley:

You searched for "Rick Hughes"
2 results found.
0: Rick Hughes
1: Kim Hughes
Pick one: 0
Results for Rick Hughes:

You searched for "Randell Jackson"
3 results found.
0: Randell Jackson
1: Wardell Jackson
2: Darnell Jackson
Pick one: 0
Results for Randell Jackson:

You searched for "Damon Jones"
24 results found.
0: Damon Jones
1: Mason Jones
2: Damian Jones
3: Damion James
4: Jalen Jones
5: James Jones
6: Major Jones
7: Sam Jones
8: Aaron James
9: Alvin Jones
10: DeQuan Jones
11: Dwayne Jones
12: Earl Jones
13: Jake Jones
14: Jimmy Jones
15: Kevin Jones
16: Larry Jones
17: Mark Jones
18: Mark Jones
19: Robin Jones
20: Solomon Jones
21: Wali Jones
22: Diamond Stone
23: Damone Brown
Pick one: 0
Results for Damon Jones:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Robert Pack"
6 results found.
0: Robert Pack
1: Robert Hahn
2: Robert Sacre
3: Robert Hite
4: Robert Parish
5: Robert Reid
Pick one: 0
Results for Robert Pack:

You searched for "Rodrick Rhodes"
1 result found.
Rodrick Rhodes
Results for Rodrick Rhodes:

You searched for "Dennis Rodman"
4 results found.
0: Dennis Rodman
1: Dennis Holman
2: Donnie Forman
3: Dennis Hopson
Pick one: 0
Results for Dennis Rodman:

You searched for "Sean Rooks"
8 results found.
0: Sean Rooks
1: Sean Marks
2: Kevin Brooks
3: Stan Brown
4: Sean Colson
5: Brian Cook
6: Sean Green
7: Jerry Rook
Pick one: 0
Results for Sean Rooks:

You searched for "Erick Strickland"
3 results found.
0: Erick Strickland
1: Mark Strickland
2: Rod Strickland
Pick one: 0
Results for Erick Strickland:

You searched for "Bruno Šundov"
1 result found.
Bruno Sundov
Results for Bruno Sundov:

You searched for "Gary Trent"
14 results found.
0: Gary Trent
1: Gary Trent
2: Gary Grant
3: Gary Bergen
4: Gary Gray
5: Gary Gregor
6: Gary Neal
7: Gary Turner
8: Gary Clark
9: Larry Drew
10: Larry Drew
11: Gary Forbes
12: Gary Freeman
13: Gary Suiter
Pick one: 0
Results for Gary Trent:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-01-17,30-168,DAL,HOME,HOU,L (-10),1,34:09,11,21,...,9,1,2,2,1,6,39,32.9,-10,Cedric Ceballos
1,2000-04-13,27-038,DAL,AWAY,HOU,L (-9),1,45:55,11,22,...,5,9,1,0,1,0,35,31.8,-7,Michael Finley
2,2000-03-11,26-107,DAL,HOME,PHO,W (+5),1,43:32,11,19,...,8,3,4,0,1,3,36,31.8,12,Erick Strickland
3,1999-12-23,26-292,DAL,AWAY,PHO,W (+1),1,48:00,12,25,...,13,13,4,0,7,2,33,31.5,1,Michael Finley
4,1999-12-11,26-280,DAL,HOME,PHO,W (+5),1,48:00,12,26,...,14,10,2,0,2,1,33,30.8,5,Michael Finley

In [9]:

DAL_2001_gamelog = []


for p in DAL_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2001_gamelog.append(player_log)
DAL_2001_gamelog = pd.concat(DAL_2001_gamelog)    
DAL_2001_gamelogs = DAL_2001_gamelog.copy()
DAL_2001_gamelogs['GAME_SCORE'] = DAL_2001_gamelogs['GAME_SCORE'].astype(float)
DAL_2001_games = DAL_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2001_games_csv = DAL_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2001_games.csv', index=False)
DAL_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2001_games.csv')
DAL_2001_games_proc.head()

You searched for "Courtney Alexander"
2 results found.
0: Courtney Alexander
1: Cory Alexander
Pick one: 0
Results for Courtney Alexander:

You searched for "Calvin Booth"
3 results found.
0: Calvin Booth
1: Calvin Natt
2: Alvin Scott
Pick one: 0
Results for Calvin Booth:

You searched for "Shawn Bradley"
1 result found.
Shawn Bradley
Results for Shawn Bradley:

You searched for "Mark Bryant"
11 results found.
0: Mark Bryant
1: Mark Blount
2: Mark Bradtke
3: Em Bryant
4: Joe Bryant
5: Kobe Bryant
6: Gary Grant
7: Markel Brown
8: Mark Eaton
9: Mark Workman
10: Mark Sibley
Pick one: 0
Results for Mark Bryant:

You searched for "Greg Buckner"
4 results found.
0: Greg Buckner
1: Greg Butler
2: Greg Bunch
3: Greg Jackson
Pick one: 0
Results for Greg Buckner:

You searched for "Bill Curley"
14 results found.
0: Bill Curley
1: Bill Turner
2: Bill Allen
3: Bill Bradley
4: Bill Bradley
5: Bill Crow
6: Dell Curry
7: Bill Downey
8: Bill Garner
9: Bill Keller
10: Bill Miller
11: Bill Closs
12: Bill McGill
13: Bill Meyer
Pick one: 0
Results for Bill Curley:

You searched for "Hubert Davis"
5 results found.
0: Hubert Davis
1: Aubrey Davis
2: Ben Davis
3: Harry Davis
4: Tyler Davis
Pick one: 0
Results for Hubert Davis:

You searched for "Howard Eisley"
1 result found.
Howard Eisley
Results for Howard Eisley:

You searched for "Obinna Ekezie"
1 result found.
Obinna Ekezie
Results for Obinna Ekezie:

You searched for "Michael Finley"
8 results found.
0: Michael Finley
1: Michael Wiley
2: Michael Ansley
3: Michael Beasley
4: Michael Bradley
5: Michael Gbinije
6: Michael Wilson
7: Michael Ruffin
Pick one: 0
Results for Michael Finley:

You searched for "Donnell Harvey"
1 result found.
Donnell Harvey
Results for Donnell Harvey:

You searched for "Juwan Howard"
4 results found.
0: Juwan Howard
1: Brian Howard
2: Josh Howard
3: Juwan Morgan
Pick one: 0
Results for Juwan Howard:

You searched for "Christian Laettner"
1 result found.
Christian Laettner
Results for Christian Laettner:

You searched for "Vernon Maxwell"
1 result found.
Vernon Maxwell
Results for Vernon Maxwell:

You searched for "Eduardo Nájera"
1 result found.
Eduardo Najera
Results for Eduardo Najera:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Gary Trent"
14 results found.
0: Gary Trent
1: Gary Trent
2: Gary Grant
3: Gary Bergen
4: Gary Gray
5: Gary Gregor
6: Gary Neal
7: Gary Turner
8: Gary Clark
9: Larry Drew
10: Larry Drew
11: Gary Forbes
12: Gary Freeman
13: Gary Suiter
Pick one: 0
Results for Gary Trent:

You searched for "Loy Vaught"
3 results found.
0: Loy Vaught
1: Bob Faught
2: Roy Pugh
Pick one: 0
Results for Loy Vaught:

You searched for "Wang Zhizhi"
1 result found.
Wang Zhizhi
Results for Wang Zhizhi:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-12-26,27-295,DAL,HOME,SEA,W (+21),1,44:47,16,22,...,9,8,1,2,3,3,38,34.3,19,Michael Finley
1,2001-03-17,22-271,DAL,HOME,PHO,W (+10),1,46:15,12,20,...,13,1,1,4,2,4,34,31.2,10,Dirk Nowitzki
2,2000-12-15,22-179,DAL,AWAY,PHI,W (+18),1,39:49,13,19,...,6,1,0,1,0,1,36,31.1,10,Dirk Nowitzki
3,2000-12-18,26-315,DAL,AWAY,BOS,W (+8),1,40:31,6,7,...,5,14,5,0,2,2,20,31.0,10,Steve Nash
4,2001-02-27,22-253,DAL,AWAY,VAN,W (+4),1,39:40,9,15,...,6,4,4,2,3,2,31,30.7,11,Dirk Nowitzki

In [10]:
DAL_2002_gamelog = []


for p in DAL_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2002_gamelog.append(player_log)
DAL_2002_gamelog = pd.concat(DAL_2002_gamelog)    
DAL_2002_gamelogs = DAL_2002_gamelog.copy()
DAL_2002_gamelogs['GAME_SCORE'] = DAL_2002_gamelogs['GAME_SCORE'].astype(float)
DAL_2002_games = DAL_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2002_games_csv = DAL_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2002_games.csv', index=False)
DAL_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2002_games.csv')
DAL_2002_games_proc.head()

You searched for "Tariq Abdul-Wahad"
1 result found.
Tariq Abdul-Wahad
Results for Tariq Abdul-Wahad:

You searched for "Charlie Bell"
6 results found.
0: Charlie Bell
1: Charlie Black
2: Charlie Brown
3: Charlie Paulk
4: Charlie Tyra
5: Charlie Ward
Pick one: 0
Results for Charlie Bell:

You searched for "Shawn Bradley"
1 result found.
Shawn Bradley
Results for Shawn Bradley:

You searched for "Greg Buckner"
4 results found.
0: Greg Buckner
1: Greg Butler
2: Greg Bunch
3: Greg Jackson
Pick one: 0
Results for Greg Buckner:

You searched for "Evan Eschmeyer"
1 result found.
Evan Eschmeyer
Results for Evan Eschmeyer:

You searched for "Michael Finley"
8 results found.
0: Michael Finley
1: Michael Wiley
2: Michael Ansley
3: Michael Beasley
4: Michael Bradley
5: Michael Gbinije
6: Michael Wilson
7: Michael Ruffin
Pick one: 0
Results for Michael Finley:

You searched for "Adrian Griffin"
2 results found.
0: Adrian Griffin
1: Eddie Griffin
Pick one: 0
Results for Adrian Griffin:

You searched for "Tim Hardaway"
2 results found.
0: Tim Hardaway
1: Tim Hardaway Jr.
Pick one: 0
Results for Tim Hardaway:

You searched for "Donnell Harvey"
1 result found.
Donnell Harvey
Results for Donnell Harvey:

You searched for "Juwan Howard"
4 results found.
0: Juwan Howard
1: Brian Howard
2: Josh Howard
3: Juwan Morgan
Pick one: 0
Results for Juwan Howard:

You searched for "Avery Johnson"
27 results found.
0: Avery Johnson
1: Amir Johnson
2: Andy Johnson
3: Dave Johnson
4: Larry Johnson
5: Larry Johnson
6: Trey Johnson
7: Alize Johnson
8: Armon Johnson
9: Arnie Johnson
10: Cameron Johnson
11: Clay Johnson
12: Dakari Johnson
13: Darryl Johnson
14: Ed Johnson
15: Eric Johnson
16: Ivan Johnson
17: James Johnson
18: Joe Johnson
19: Ken Johnson
20: Ken Johnson
21: Lee Johnson
22: Neil Johnson
23: Omari Johnson
24: Steve Johnson
25: Stew Johnson
26: Tyler Johnson
Pick one: 0
Results for Avery Johnson:

You searched for "Raef LaFrentz"
1 result found.
Raef LaFrentz
Results for Raef LaFrentz:

You searched for "Danny Manning"
3 results found.
0: Danny Manning
1: Danny Ainge
2: Guy Manning
Pick one: 0
Results for Danny Manning:

You searched for "Darrick Martin"
5 results found.
0: Darrick Martin
1: Maurice Martin
2: Derrick Gervin
3: Cartier Martin
4: Derrick Walton
Pick one: 0
Results for Darrick Martin:

You searched for "Eduardo Nájera"
1 result found.
Eduardo Najera
Results for Eduardo Najera:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Johnny Newman"
4 results found.
0: Johnny Newman
1: Johnny Neumann
2: Johnny Egan
3: Johnny Horan
Pick one: 0
Results for Johnny Newman:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Nick Van Exel"
1 result found.
Nick Van Exel
Results for Nick Van Exel:

You searched for "Wang Zhizhi"
1 result found.
Wang Zhizhi
Results for Wang Zhizhi:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-02-21,23-247,DAL,HOME,BOS,W (+6),1,44:42,12,23,...,23,8,1,4,3,2,33,36.2,1,Dirk Nowitzki
1,2001-12-11,27-307,DAL,HOME,POR,W (+2),1,41:12,12,16,...,3,7,1,1,3,3,39,34.7,4,Steve Nash
2,2001-12-29,23-193,DAL,HOME,ATL,W (+16),1,43:28,12,17,...,12,1,2,2,1,2,35,34.2,13,Dirk Nowitzki
3,2002-01-15,23-210,DAL,AWAY,ATL,W (+9),1,48:00,12,22,...,11,1,1,1,0,2,40,33.1,9,Dirk Nowitzki
4,2001-11-01,29-339,DEN,HOME,MIL,L (-1),1,40:43,16,32,...,7,8,0,1,4,1,44,31.6,0,Nick Van Exel

In [11]:
DAL_2003_gamelog = []



for p in DAL_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2003_gamelog.append(player_log)
DAL_2003_gamelog = pd.concat(DAL_2003_gamelog)    
DAL_2003_gamelogs = DAL_2003_gamelog.copy()
DAL_2003_gamelogs['GAME_SCORE'] = DAL_2003_gamelogs['GAME_SCORE'].astype(float)
DAL_2003_games = DAL_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2003_games_csv = DAL_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2003_games.csv', index=False)
DAL_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2003_games.csv')
DAL_2003_games_proc.head()

You searched for "Tariq Abdul-Wahad"
1 result found.
Tariq Abdul-Wahad
Results for Tariq Abdul-Wahad:

You searched for "Raja Bell"
2 results found.
0: Raja Bell
1: Troy Bell
Pick one: 0
Results for Raja Bell:

You searched for "Shawn Bradley"
1 result found.
Shawn Bradley
Results for Shawn Bradley:

You searched for "Evan Eschmeyer"
1 result found.
Evan Eschmeyer
Results for Evan Eschmeyer:

You searched for "Michael Finley"
8 results found.
0: Michael Finley
1: Michael Wiley
2: Michael Ansley
3: Michael Beasley
4: Michael Bradley
5: Michael Gbinije
6: Michael Wilson
7: Michael Ruffin
Pick one: 0
Results for Michael Finley:

You searched for "Adrian Griffin"
2 results found.
0: Adrian Griffin
1: Eddie Griffin
Pick one: 0
Results for Adrian Griffin:

You searched for "Adam Harrington"
2 results found.
0: Adam Harrington
1: Al Harrington
Pick one: 0
Results for Adam Harrington:

You searched for "Avery Johnson"
27 results found.
0: Avery Johnson
1: Amir Johnson
2: Andy Johnson
3: Dave Johnson
4: Larry Johnson
5: Larry Johnson
6: Trey Johnson
7: Alize Johnson
8: Armon Johnson
9: Arnie Johnson
10: Cameron Johnson
11: Clay Johnson
12: Dakari Johnson
13: Darryl Johnson
14: Ed Johnson
15: Eric Johnson
16: Ivan Johnson
17: James Johnson
18: Joe Johnson
19: Ken Johnson
20: Ken Johnson
21: Lee Johnson
22: Neil Johnson
23: Omari Johnson
24: Steve Johnson
25: Stew Johnson
26: Tyler Johnson
Pick one: 0
Results for Avery Johnson:

You searched for "Popeye Jones"
6 results found.
0: Popeye Jones
1: Bobby Jones
2: Bobby Jones
3: Ozell Jones
4: Perry Jones
5: Steve Jones
Pick one: 0
Results for Popeye Jones:

You searched for "Raef LaFrentz"
1 result found.
Raef LaFrentz
Results for Raef LaFrentz:

You searched for "Eduardo Nájera"
1 result found.
Eduardo Najera
Results for Eduardo Najera:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Antoine Rigaudeau"
1 result found.
Antoine Rigaudeau
Results for Antoine Rigaudeau:

You searched for "Mark Strickland"
3 results found.
0: Mark Strickland
1: Erick Strickland
2: Rod Strickland
Pick one: 0
Results for Mark Strickland:

You searched for "Nick Van Exel"
1 result found.
Nick Van Exel
Results for Nick Van Exel:

You searched for "Walt Williams"
45 results found.
0: Walt Williams
1: Al Williams
2: Art Williams
3: Matt Williams
4: Milt Williams
5: Ward Williams
6: Alan Williams
7: Earl Williams
8: Fly Williams
9: Grant Williams
10: Hank Williams
11: Jay Williams
12: Nate Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Walt Bellamy
18: Aaron Williams
19: Alvin Williams
20: Bob Williams
21: Buck Williams
22: C.J. Williams
23: Duck Williams
24: Elliot Williams
25: Eric Williams
26: Frank Williams
27: Gene Williams
28: Gus Williams
29: Guy Williams
30: Herb Williams
31: Jason Williams
32: Jawad Williams
33: John Williams
34: Lou Williams
35: Mike Williams
36: Mo Williams
37: Monty Williams
38: Pete Williams
39: Rob Williams
40: Ron Williams
41: Scott Williams
42: Sean Williams
43: Troy Williams
44: Willie Williams
Pick one: 0
Results for Walt Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-12-30,24-194,DAL,HOME,MIL,L (-3),1,47:53,12,25,...,14,5,2,1,2,1,40,36.1,-3,Dirk Nowitzki
1,2003-04-14,24-299,DAL,HOME,SEA,W (+3),1,45:36,14,21,...,10,7,1,1,3,3,39,34.9,2,Dirk Nowitzki
2,2002-12-17,29-286,DAL,HOME,IND,W (+21),1,35:15,13,21,...,13,3,2,0,0,0,33,32.7,23,Michael Finley
3,2002-11-27,29-266,DAL,AWAY,DET,W (+20),1,39:23,13,28,...,10,2,2,0,2,1,42,31.6,28,Michael Finley
4,2003-04-12,24-297,DAL,HOME,GSW,W (+9),1,39:49,10,22,...,12,5,1,0,2,2,37,30.5,16,Dirk Nowitzki

In [14]:
# removed Mamadou N'Diaye

DAL_2004_gamelog = []



for p in DAL_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2004_gamelog.append(player_log)
DAL_2004_gamelog = pd.concat(DAL_2004_gamelog)    
DAL_2004_gamelogs = DAL_2004_gamelog.copy()
DAL_2004_gamelogs['GAME_SCORE'] = DAL_2004_gamelogs['GAME_SCORE'].astype(float)
DAL_2004_games = DAL_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2004_games_csv = DAL_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2004_games.csv', index=False)
DAL_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2004_games.csv')
DAL_2004_games_proc.head()

You searched for "Travis Best"
6 results found.
0: Travis Best
1: Travis Wear
2: Travis Grant
3: Travis Leslie
4: Travis Mays
5: David West
Pick one: 0
Results for Travis Best:

You searched for "Shawn Bradley"
1 result found.
Shawn Bradley
Results for Shawn Bradley:

You searched for "Marquis Daniels"
1 result found.
Marquis Daniels
Results for Marquis Daniels:

You searched for "Tony Delk"
12 results found.
0: Tony Delk
1: Tony Snell
2: Tony Zeno
3: Tony Allen
4: Troy Bell
5: Don Dee
6: Tony Dumas
7: Tony Koski
8: Deng Adel
9: Sonny Dove
10: Tony Price
11: Tony White
Pick one: 0
Results for Tony Delk:

You searched for "Michael Finley"
8 results found.
0: Michael Finley
1: Michael Wiley
2: Michael Ansley
3: Michael Beasley
4: Michael Bradley
5: Michael Gbinije
6: Michael Wilson
7: Michael Ruffin
Pick one: 0
Results for Michael Finley:

You searched for "Danny Fortson"
1 result found.
Danny Fortson
Results for Danny Fortson:

You searched for "Josh Howard"
8 results found.
0: Josh Howard
1: Josh Hart
2: Mo Howard
3: Josh Hall
4: Greg Howard
5: Juwan Howard
6: Otis Howard
7: Josh Powell
Pick one: 0
Results for Josh Howard:

You searched for "Antawn Jamison"
1 result found.
Antawn Jamison
Results for Antawn Jamison:

You searched for "Eduardo Nájera"
1 result found.
Eduardo Najera
Results for Eduardo Najera:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Antoine Walker"
2 results found.
0: Antoine Walker
1: Antoine Carr
Pick one: 0
Results for Antoine Walker:

You searched for "Scott Williams"
22 results found.
0: Scott Williams
1: Matt Williams
2: Art Williams
3: Bob Williams
4: C.J. Williams
5: Corey Williams
6: Grant Williams
7: John Williams
8: Lou Williams
9: Milt Williams
10: Mo Williams
11: Monty Williams
12: Nate Williams
13: Pete Williams
14: Rob Williams
15: Ron Williams
16: Sam Williams
17: Sam Williams
18: Sean Williams
19: Sly Williams
20: Troy Williams
21: Walt Williams
Pick one: 0
Results for Scott Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-02-07,25-233,DAL,HOME,DET,W (+3),1,42:23,15,24,...,8,3,4,1,2,3,40,34.8,10,Dirk Nowitzki
1,2004-01-27,25-222,DAL,AWAY,SEA,W (+2),1,40:58,16,22,...,4,2,2,1,5,1,43,33.5,-1,Dirk Nowitzki
2,2004-03-30,25-285,DAL,HOME,CLE,W (+17),1,42:51,14,23,...,18,4,1,1,1,3,35,33.0,19,Dirk Nowitzki
3,2003-12-25,25-189,DAL,AWAY,SAC,W (+8),1,47:33,9,22,...,14,5,3,3,0,4,31,30.8,9,Dirk Nowitzki
4,2004-02-26,30-357,DAL,HOME,SAS,W (+24),1,34:07,10,14,...,6,4,1,2,0,0,30,30.8,22,Michael Finley

In [17]:
# removed Didier Ilunga-Mbenga

DAL_2005_gamelog = []

for p in DAL_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2005_gamelog.append(player_log)
DAL_2005_gamelog = pd.concat(DAL_2005_gamelog)    
DAL_2005_gamelogs = DAL_2005_gamelog.copy()
DAL_2005_gamelogs['GAME_SCORE'] = DAL_2005_gamelogs['GAME_SCORE'].astype(float)
DAL_2005_games = DAL_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2005_games_csv = DAL_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2005_games.csv', index=False)
DAL_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2005_games.csv')
DAL_2005_games_proc.head()

You searched for "Darrell Armstrong"
1 result found.
Darrell Armstrong
Results for Darrell Armstrong:

You searched for "Calvin Booth"
3 results found.
0: Calvin Booth
1: Calvin Natt
2: Alvin Scott
Pick one: 0
Results for Calvin Booth:

You searched for "Shawn Bradley"
1 result found.
Shawn Bradley
Results for Shawn Bradley:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "Marquis Daniels"
1 result found.
Marquis Daniels
Results for Marquis Daniels:

You searched for "Dan Dickau"
3 results found.
0: Dan Dickau
1: Dan Tieman
2: Dan Kraus
Pick one: 0
Results for Dan Dickau:

You searched for "Michael Finley"
8 results found.
0: Michael Finley
1: Michael Wiley
2: Michael Ansley
3: Michael Beasley
4: Michael Bradley
5: Michael Gbinije
6: Michael Wilson
7: Michael Ruffin
Pick one: 0
Results for Michael Finley:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Alan Henderson"
9 results found.
0: Alan Henderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ryan Anderson
5: Dave Henderson
6: J.R. Henderson
7: Kevin Henderson
8: Tom Henderson
Pick one: 0
Results for Alan Henderson:

You searched for "Josh Howard"
8 results found.
0: Josh Howard
1: Josh Hart
2: Mo Howard
3: Josh Hall
4: Greg Howard
5: Juwan Howard
6: Otis Howard
7: Josh Powell
Pick one: 0
Results for Josh Howard:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Pavel Podkolzin"
1 result found.
Pavel Podkolzin
Results for Pavel Podkolzin:

You searched for "Jerry Stackhouse"
1 result found.
Jerry Stackhouse
Results for Jerry Stackhouse:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

You searched for "Keith Van Horn"
2 results found.
0: Keith Van Horn
1: Keith Langford
Pick one: 0
Results for Keith Van Horn:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-12-02,26-166,DAL,HOME,HOU,W (+7),1,49:36,15,32,...,16,2,3,4,1,2,53,48.0,12,Dirk Nowitzki
1,2004-11-11,26-145,DAL,AWAY,MIA,W (+20),1,42:21,12,24,...,10,4,0,2,2,2,41,33.8,30,Dirk Nowitzki
2,2005-02-15,26-241,DAL,AWAY,GSW,W (+7),1,38:29,10,17,...,11,5,1,2,3,2,35,32.1,1,Dirk Nowitzki
3,2004-11-13,26-147,DAL,AWAY,NJN,W (+16),1,43:35,10,18,...,7,7,4,0,1,3,31,30.4,20,Dirk Nowitzki
4,2005-01-02,26-197,DAL,HOME,MIL,W (+19),1,45:20,14,25,...,5,6,1,2,4,1,39,30.4,26,Dirk Nowitzki

In [20]:
# removed Didier Ilunga-Mbenga
DAL_2006_gamelog = []

for p in DAL_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2006_gamelog.append(player_log)
DAL_2006_gamelog = pd.concat(DAL_2006_gamelog)    
DAL_2006_gamelogs = DAL_2006_gamelog.copy()
DAL_2006_gamelogs['GAME_SCORE'] = DAL_2006_gamelogs['GAME_SCORE'].astype(float)
DAL_2006_games = DAL_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2006_games_csv = DAL_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2006_games.csv', index=False)
DAL_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2006_games.csv')
DAL_2006_games_proc.head()

You searched for "Darrell Armstrong"
1 result found.
Darrell Armstrong
Results for Darrell Armstrong:

You searched for "Doug Christie"
2 results found.
0: Doug Christie
1: Doug Kistler
Pick one: 0
Results for Doug Christie:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "Marquis Daniels"
1 result found.
Marquis Daniels
Results for Marquis Daniels:

You searched for "DeSagana Diop"
1 result found.
DeSagana Diop
Results for DeSagana Diop:

You searched for "Adrian Griffin"
2 results found.
0: Adrian Griffin
1: Eddie Griffin
Pick one: 0
Results for Adrian Griffin:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Josh Howard"
8 results found.
0: Josh Howard
1: Josh Hart
2: Mo Howard
3: Josh Hall
4: Greg Howard
5: Juwan Howard
6: Otis Howard
7: Josh Powell
Pick one: 0
Results for Josh Howard:

You searched for "Rawle Marshall"
2 results found.
0: Rawle Marshall
1: Naji Marshall
Pick one: 0
Results for Rawle Marshall:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Pavel Podkolzin"
1 result found.
Pavel Podkolzin
Results for Pavel Podkolzin:

You searched for "Josh Powell"
7 results found.
0: Josh Powell
1: Josh Hall
2: Josh Howard
3: Kasib Powell
4: Roger Powell
5: Josh Selby
6: Josh Okogie
Pick one: 0
Results for Josh Powell:

You searched for "Jerry Stackhouse"
1 result found.
Jerry Stackhouse
Results for Jerry Stackhouse:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

You searched for "Keith Van Horn"
2 results found.
0: Keith Van Horn
1: Keith Langford
Pick one: 0
Results for Keith Van Horn:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-03-23,27-277,DAL,HOME,GSW,L (-1),1,40:50,16,24,...,9,5,2,1,5,3,51,44.1,3,Dirk Nowitzki
1,2005-12-23,27-187,DAL,AWAY,SEA,W (+3),1,39:48,9,20,...,13,7,1,0,1,1,34,32.4,21,Dirk Nowitzki
2,2005-12-22,27-186,DAL,AWAY,SAC,W (+10),1,40:19,14,23,...,10,4,1,0,1,1,37,31.9,15,Dirk Nowitzki
3,2006-03-31,27-285,DAL,AWAY,ORL,L (-9),1,43:36,15,27,...,15,4,0,1,3,2,38,30.1,2,Dirk Nowitzki
4,2005-11-29,28-075,DAL,AWAY,MIL,L (-2),1,50:59,14,23,...,1,3,1,0,0,0,37,29.1,0,Jason Terry

In [25]:

DAL_2007_gamelog = []

for p in DAL_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2007_gamelog.append(player_log)
DAL_2007_gamelog = pd.concat(DAL_2007_gamelog)    
DAL_2007_gamelogs = DAL_2007_gamelog.copy()
DAL_2007_gamelogs['GAME_SCORE'] = DAL_2007_gamelogs['GAME_SCORE'].astype(float)
DAL_2007_games = DAL_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2007_games_csv = DAL_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2007_games.csv', index=False)
DAL_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2007_games.csv')
DAL_2007_games_proc.head()

You searched for "Maurice Ager"
8 results found.
0: Maurice Ager
1: Maurice Baker
2: Maurice Carter
3: Maurice King
4: Maurice Ndour
5: Maurice Taylor
6: Maurice Evans
7: Maurice Lucas
Pick one: 0
Results for Maurice Ager:

You searched for "Greg Buckner"
4 results found.
0: Greg Buckner
1: Greg Butler
2: Greg Bunch
3: Greg Jackson
Pick one: 0
Results for Greg Buckner:

You searched for "Austin Croshere"
1 result found.
Austin Croshere
Results for Austin Croshere:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "DeSagana Diop"
1 result found.
DeSagana Diop
Results for DeSagana Diop:

You searched for "Devean George"
1 result found.
Devean George
Results for Devean George:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Josh Howard"
8 results found.
0: Josh Howard
1: Josh Hart
2: Mo Howard
3: Josh Hall
4: Greg Howard
5: Juwan Howard
6: Otis Howard
7: Josh Powell
Pick one: 0
Results for Josh Howard:

You searched for "Anthony Johnson"
8 results found.
0: Anthony Johnson
1: Andy Johnson
2: Armon Johnson
3: Linton Johnson
4: Anthony Jones
5: Anthony Mason
6: Anthony Roberson
7: Anthony Bonner
Pick one: 0
Results for Anthony Johnson:

You searched for "Pops Mensah-Bonsu"
1 result found.
Pops Mensah-Bonsu
Results for Pops Mensah-Bonsu:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Jerry Stackhouse"
1 result found.
Jerry Stackhouse
Results for Jerry Stackhouse:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

You searched for "Kevin Willis"
4 results found.
0: Kevin Willis
1: Kevin Williams
2: Kevin Ollie
3: Alvin Williams
Pick one: 0
Results for Kevin Willis:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-02-07,28-233,DAL,HOME,MEM,W (+16),1,37:33,14,20,...,10,6,3,4,0,3,38,42.6,14,Dirk Nowitzki
1,2006-12-28,29-104,DAL,HOME,PHO,W (+2),1,41:38,12,20,...,3,8,3,0,1,0,35,34.7,10,Jason Terry
2,2007-02-13,28-239,DAL,AWAY,MIL,W (+6),1,42:34,15,28,...,11,8,2,0,2,3,38,33.3,12,Dirk Nowitzki
3,2007-01-12,28-207,DAL,AWAY,IND,W (+2),1,44:14,13,24,...,12,2,0,0,3,1,43,33.0,18,Dirk Nowitzki
4,2007-01-14,28-209,DAL,AWAY,TOR,W (+1),1,46:25,14,30,...,11,5,2,3,1,1,38,32.1,7,Dirk Nowitzki

In [28]:

DAL_2008_gamelog = []

for p in DAL_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2008_gamelog.append(player_log)
DAL_2008_gamelog = pd.concat(DAL_2008_gamelog)    
DAL_2008_gamelogs = DAL_2008_gamelog.copy()
DAL_2008_gamelogs['GAME_SCORE'] = DAL_2008_gamelogs['GAME_SCORE'].astype(float)
DAL_2008_games = DAL_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2008_games_csv = DAL_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2008_games.csv', index=False)
DAL_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2008_games.csv')
DAL_2008_games_proc.head()

You searched for "Maurice Ager"
8 results found.
0: Maurice Ager
1: Maurice Baker
2: Maurice Carter
3: Maurice King
4: Maurice Ndour
5: Maurice Taylor
6: Maurice Evans
7: Maurice Lucas
Pick one: 0
Results for Maurice Ager:

You searched for "Malik Allen"
10 results found.
0: Malik Allen
1: Bill Allen
2: Lavoy Allen
3: Randy Allen
4: Ray Allen
5: Willie Allen
6: Malik Beasley
7: Malik Rose
8: Malik Monk
9: Malik Sealy
Pick one: 0
Results for Malik Allen:

You searched for "Brandon Bass"
5 results found.
0: Brandon Bass
1: Brandon Paul
2: Brandon Rush
3: Brandon Davies
4: Brandon Roy
Pick one: 0
Results for Brandon Bass:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "DeSagana Diop"
1 result found.
DeSagana Diop
Results for DeSagana Diop:

You searched for "Nick Fazekas"
1 result found.
Nick Fazekas
Results for Nick Fazekas:

You searched for "Devean George"
1 result found.
Devean George
Results for Devean George:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Trenton Hassell"
1 result found.
Trenton Hassell
Results for Trenton Hassell:

You searched for "Josh Howard"
8 results found.
0: Josh Howard
1: Josh Hart
2: Mo Howard
3: Josh Hall
4: Greg Howard
5: Juwan Howard
6: Otis Howard
7: Josh Powell
Pick one: 0
Results for Josh Howard:

You searched for "Juwan Howard"
4 results found.
0: Juwan Howard
1: Brian Howard
2: Josh Howard
3: Juwan Morgan
Pick one: 0
Results for Juwan Howard:

You searched for "Eddie Jones"
21 results found.
0: Eddie Jones
1: Edgar Jones
2: Eddie Miles
3: Eddie Owens
4: Tre Jones
5: Eddie House
6: Eddie Hughes
7: Eddie Johnson
8: Eddie Johnson
9: Alvin Jones
10: Askia Jones
11: Earl Jones
12: Jake Jones
13: Kevin Jones
14: Robin Jones
15: Steve Jones
16: Wali Jones
17: Wil Jones
18: Willie Jones
19: Eddie Jordan
20: Eddie Mast
Pick one: 0
Results for Eddie Jones:

You searched for "Jason Kidd"
5 results found.
0: Jason Kidd
1: Jason Hart
2: Stanton Kidd
3: Warren Kidd
4: Jason Smith
Pick one: 0
Results for Jason Kidd:

You searched for "Tyronn Lue"
3 results found.
0: Tyronn Lue
1: Ron Lee
2: Tyrone Hill
Pick one: 0
Results for Tyronn Lue:

You searched for "Jamaal Magloire"
1 result found.
Jamaal Magloire
Results for Jamaal Magloire:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Jerry Stackhouse"
1 result found.
Jerry Stackhouse
Results for Jerry Stackhouse:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

You searched for "Antoine Wright"
2 results found.
0: Antoine Wright
1: Antoine Walker
Pick one: 0
Results for Antoine Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-12-08,27-224,DAL,HOME,UTA,W (+8),1,42:26,14,19,...,10,2,0,1,1,4,47,43.4,19,Josh Howard
1,2008-04-16,35-024,DAL,HOME,NOH,W (+13),1,36:55,9,14,...,10,10,0,0,1,2,27,30.6,11,Jason Kidd
2,2008-03-30,27-337,DAL,AWAY,GSW,L (-10),1,39:11,13,25,...,9,3,2,2,1,3,36,30.5,-8,Josh Howard
3,2008-02-06,29-232,DAL,HOME,MIL,W (+11),1,41:33,9,17,...,10,12,0,1,2,2,29,30.4,19,Dirk Nowitzki
4,2008-03-08,29-263,DAL,HOME,NJN,W (+20),1,31:52,10,18,...,9,2,1,0,2,1,34,29.3,18,Dirk Nowitzki

In [33]:

DAL_2009_gamelog = []

for p in DAL_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2009_gamelog.append(player_log)
DAL_2009_gamelog = pd.concat(DAL_2009_gamelog)    
DAL_2009_gamelogs = DAL_2009_gamelog.copy()
DAL_2009_gamelogs['GAME_SCORE'] = DAL_2009_gamelogs['GAME_SCORE'].astype(float)
DAL_2009_games = DAL_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2009_games_csv = DAL_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2009_games.csv', index=False)
DAL_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2009_games.csv')
DAL_2009_games_proc.head()

You searched for "Brandon Bass"
5 results found.
0: Brandon Bass
1: Brandon Paul
2: Brandon Rush
3: Brandon Davies
4: Brandon Roy
Pick one: 0
Results for Brandon Bass:

You searched for "Matt Carroll"
1 result found.
Matt Carroll
Results for Matt Carroll:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "DeSagana Diop"
1 result found.
DeSagana Diop
Results for DeSagana Diop:

You searched for "Devean George"
1 result found.
Devean George
Results for Devean George:

You searched for "Gerald Green"
6 results found.
0: Gerald Green
1: Gerald Brown
2: Gerald Govan
3: Gerald Glass
4: Erick Green
5: Sean Green
Pick one: 0
Results for Gerald Green:

You searched for "Ryan Hollins"
3 results found.
0: Ryan Hollins
1: Don Collins
2: John Collins
Pick one: 0
Results for Ryan Hollins:

You searched for "Josh Howard"
8 results found.
0: Josh Howard
1: Josh Hart
2: Mo Howard
3: Josh Hall
4: Greg Howard
5: Juwan Howard
6: Otis Howard
7: Josh Powell
Pick one: 0
Results for Josh Howard:

You searched for "Jason Kidd"
5 results found.
0: Jason Kidd
1: Jason Hart
2: Stanton Kidd
3: Warren Kidd
4: Jason Smith
Pick one: 0
Results for Jason Kidd:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "James Singleton"
2 results found.
0: James Singleton
1: Chris Singleton
Pick one: 0
Results for James Singleton:

You searched for "Jerry Stackhouse"
1 result found.
Jerry Stackhouse
Results for Jerry Stackhouse:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

You searched for "Shawne Williams"
14 results found.
0: Shawne Williams
1: Hank Williams
2: Sean Williams
3: Alan Williams
4: Charles Williams
5: Frank Williams
6: Gene Williams
7: Grant Williams
8: Jawad Williams
9: Nate Williams
10: Sam Williams
11: Sam Williams
12: Shammond Williams
13: Shelden Williams
Pick one: 0
Results for Shawne Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2009-01-13,30-208,DAL,AWAY,DEN,L (-2),1,42:05,15,26,...,14,0,1,0,1,3,44,35.6,7,Dirk Nowitzki
1,2008-11-16,30-150,DAL,AWAY,NYK,W (+10),1,44:10,13,27,...,15,4,1,1,0,1,39,34.7,13,Dirk Nowitzki
2,2008-12-13,30-177,DAL,HOME,OKC,W (+4),1,39:50,17,30,...,8,4,0,2,5,2,46,33.0,5,Dirk Nowitzki
3,2009-02-07,30-233,DAL,HOME,CHI,W (+1),1,44:15,16,34,...,9,1,2,3,2,2,44,32.1,0,Dirk Nowitzki
4,2008-12-04,30-168,DAL,HOME,PHO,W (+15),1,37:46,17,25,...,9,2,0,1,2,3,39,30.7,15,Dirk Nowitzki

In [34]:

DAL_2010_gamelog = []

for p in DAL_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2010_gamelog.append(player_log)
DAL_2010_gamelog = pd.concat(DAL_2010_gamelog)    
DAL_2010_gamelogs = DAL_2010_gamelog.copy()
DAL_2010_gamelogs['GAME_SCORE'] = DAL_2010_gamelogs['GAME_SCORE'].astype(float)
DAL_2010_games = DAL_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2010_games_csv = DAL_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2010_games.csv', index=False)
DAL_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2010_games.csv')
DAL_2010_games_proc.head()

You searched for "Rodrigue Beaubois"
1 result found.
Rodrigue Beaubois
Results for Rodrigue Beaubois:

You searched for "Caron Butler"
4 results found.
0: Caron Butler
1: Al Butler
2: Greg Butler
3: Carl Fuller
Pick one: 0
Results for Caron Butler:

You searched for "Matt Carroll"
1 result found.
Matt Carroll
Results for Matt Carroll:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Brendan Haywood"
1 result found.
Brendan Haywood
Results for Brendan Haywood:

You searched for "Josh Howard"
8 results found.
0: Josh Howard
1: Josh Hart
2: Mo Howard
3: Josh Hall
4: Greg Howard
5: Juwan Howard
6: Otis Howard
7: Josh Powell
Pick one: 0
Results for Josh Howard:

You searched for "Kris Humphries"
2 results found.
0: Kris Humphries
1: Jay Humphries
Pick one: 0
Results for Kris Humphries:

You searched for "Jason Kidd"
5 results found.
0: Jason Kidd
1: Jason Hart
2: Stanton Kidd
3: Warren Kidd
4: Jason Smith
Pick one: 0
Results for Jason Kidd:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Eduardo Nájera"
1 result found.
Eduardo Najera
Results for Eduardo Najera:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Quinton Ross"
2 results found.
0: Quinton Ross
1: Quinton Rose
Pick one: 0
Results for Quinton Ross:

You searched for "James Singleton"
2 results found.
0: James Singleton
1: Chris Singleton
Pick one: 0
Results for James Singleton:

You searched for "DeShawn Stevenson"
1 result found.
DeShawn Stevenson
Results for DeShawn Stevenson:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

You searched for "Tim Thomas"
16 results found.
0: Tim Thomas
1: Jim Thomas
2: Etan Thomas
3: Joe Thomas
4: Jim Chones
5: Tim James
6: Billy Thomas
7: Carl Thomas
8: Isiah Thomas
9: Jamel Thomas
10: James Thomas
11: John Thomas
12: Kurt Thomas
13: Matt Thomas
14: Terry Thomas
15: Tyrus Thomas
Pick one: 0
Results for Tim Thomas:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2009-11-03,31-137,DAL,HOME,UTA,W (+11),1,39:06,12,22,...,11,5,2,5,0,2,40,41.3,23,Dirk Nowitzki
1,2010-02-08,32-146,DAL,AWAY,GSW,W (+10),1,42:18,9,17,...,6,9,3,0,3,1,36,35.0,17,Jason Terry
2,2010-03-29,31-283,DAL,HOME,DEN,W (+16),1,37:16,7,17,...,10,10,0,1,2,3,34,33.2,20,Dirk Nowitzki
3,2010-04-10,31-295,DAL,AWAY,SAC,W (+18),1,37:17,12,20,...,7,2,0,0,2,1,39,31.7,15,Dirk Nowitzki
4,2010-02-28,31-254,DAL,HOME,NOH,W (+8),1,38:49,14,25,...,8,7,1,0,0,3,36,31.2,5,Dirk Nowitzki

In [39]:

DAL_2011_gamelog = []

for p in DAL_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2011_gamelog.append(player_log)
DAL_2011_gamelog = pd.concat(DAL_2011_gamelog)    
DAL_2011_gamelogs = DAL_2011_gamelog.copy()
DAL_2011_gamelogs['GAME_SCORE'] = DAL_2011_gamelogs['GAME_SCORE'].astype(float)
DAL_2011_games = DAL_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2011_games_csv = DAL_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2011_games.csv', index=False)
DAL_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2011_games.csv')
DAL_2011_games_proc.head()

You searched for "Alexis Ajinça"
1 result found.
Alexis Ajinca
Results for Alexis Ajinca:

You searched for "Rodrigue Beaubois"
1 result found.
Rodrigue Beaubois
Results for Rodrigue Beaubois:

You searched for "Corey Brewer"
4 results found.
0: Corey Brewer
1: Corey Crowder
2: Corey Beck
3: Ron Brewer
Pick one: 0
Results for Corey Brewer:

You searched for "Caron Butler"
4 results found.
0: Caron Butler
1: Al Butler
2: Greg Butler
3: Carl Fuller
Pick one: 0
Results for Caron Butler:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Tyson Chandler"
3 results found.
0: Tyson Chandler
1: Wilson Chandler
2: Tyson Wheeler
Pick one: 0
Results for Tyson Chandler:

You searched for "Brendan Haywood"
1 result found.
Brendan Haywood
Results for Brendan Haywood:

You searched for "Dominique Jones"
1 result found.
Dominique Jones
Results for Dominique Jones:

You searched for "Jason Kidd"
5 results found.
0: Jason Kidd
1: Jason Hart
2: Stanton Kidd
3: Warren Kidd
4: Jason Smith
Pick one: 0
Results for Jason Kidd:

You searched for "Ian Mahinmi"
2 results found.
0: Ian Mahinmi
1: Brian Martin
Pick one: 0
Results for Ian Mahinmi:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Steve Novak"
9 results found.
0: Steve Novak
1: Steve Blake
2: Steve Jones
3: Steve Nash
4: Mike Novak
5: Steve Bardo
6: Steve Green
7: Steve Kerr
8: Steve Henson
Pick one: 0
Results for Steve Novak:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "DeShawn Stevenson"
1 result found.
DeShawn Stevenson
Results for DeShawn Stevenson:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-11-23,32-157,DAL,HOME,DET,W (+4),1,39:58,13,23,...,12,1,0,2,1,4,42,35.0,9,Dirk Nowitzki
1,2010-12-11,32-175,DAL,HOME,UTA,W (+6),1,39:00,10,12,...,15,4,0,1,3,1,31,30.4,21,Dirk Nowitzki
2,2011-02-17,32-243,DAL,AWAY,PHO,W (+6),1,37:12,13,18,...,1,4,1,0,2,2,35,28.9,12,Dirk Nowitzki
3,2011-03-16,32-270,DAL,AWAY,GSW,W (+6),1,34:39,10,22,...,13,2,0,1,1,3,34,28.8,4,Dirk Nowitzki
4,2010-11-24,32-158,DAL,AWAY,OKC,W (+8),1,39:06,9,15,...,4,4,1,0,3,1,34,28.3,13,Dirk Nowitzki

In [40]:

DAL_2012_gamelog = []

for p in DAL_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2012_gamelog.append(player_log)
DAL_2012_gamelog = pd.concat(DAL_2012_gamelog)    
DAL_2012_gamelogs = DAL_2012_gamelog.copy()
DAL_2012_gamelogs['GAME_SCORE'] = DAL_2012_gamelogs['GAME_SCORE'].astype(float)
DAL_2012_games = DAL_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2012_games_csv = DAL_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2012_games.csv', index=False)
DAL_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2012_games.csv')
DAL_2012_games_proc.head()

You searched for "Kelenna Azubuike"
1 result found.
Kelenna Azubuike
Results for Kelenna Azubuike:

You searched for "Rodrigue Beaubois"
1 result found.
Rodrigue Beaubois
Results for Rodrigue Beaubois:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Brendan Haywood"
1 result found.
Brendan Haywood
Results for Brendan Haywood:

You searched for "Yi Jianlian"
1 result found.
Yi Jianlian
Results for Yi Jianlian:

You searched for "Dominique Jones"
1 result found.
Dominique Jones
Results for Dominique Jones:

You searched for "Jason Kidd"
5 results found.
0: Jason Kidd
1: Jason Hart
2: Stanton Kidd
3: Warren Kidd
4: Jason Smith
Pick one: 0
Results for Jason Kidd:

You searched for "Ian Mahinmi"
2 results found.
0: Ian Mahinmi
1: Brian Martin
Pick one: 0
Results for Ian Mahinmi:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Lamar Odom"
1 result found.
Lamar Odom
Results for Lamar Odom:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

You searched for "Delonte West"
1 result found.
Delonte West
Results for Delonte West:

You searched for "Sean Williams"
50 results found.
0: Sean Williams
1: Alan Williams
2: Sam Williams
3: Sam Williams
4: Al Williams
5: Deron Williams
6: Earl Williams
7: Frank Williams
8: Gene Williams
9: Grant Williams
10: Hank Williams
11: Herb Williams
12: Jay Williams
13: John Williams
14: Kenny Williams
15: Kevin Williams
16: Pete Williams
17: Ray Williams
18: Ron Williams
19: Shawne Williams
20: Sly Williams
21: Aaron Williams
22: Alvin Williams
23: Art Williams
24: Bernie Williams
25: Bob Williams
26: Buck Williams
27: C.J. Williams
28: Duck Williams
29: Eric Williams
30: Fly Williams
31: Freeman Williams
32: Gus Williams
33: Guy Williams
34: Jason Williams
35: Jawad Williams
36: Jordan Williams
37: Justin Williams
38: Lou Williams
39: Matt Williams
40: Mike Williams
41: Milt Williams
42: Mo Williams
43: Nate Williams
44: Rob Williams
45: Scott Williams
46: Shelden Williams
47: Troy Williams
48: Walt Williams
49: Ward Williams
Pick one: 0
Results for Sean Williams:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,GAME_SCORE,3P,3PA,3P%,ORB,DRB,STL,BLK,TOV,Player
0,2012-04-16,33-302,DAL,AWAY,UTA,L (-2),1,52:57,13,26,...,29.7,2,7,0.286,1,8,0,0,3,Dirk Nowitzki
1,2012-03-03,33-258,DAL,HOME,UTA,W (+6),1,28:50,14,21,...,28.9,3,8,0.375,1,5,1,0,4,Dirk Nowitzki
2,2012-04-18,33-304,DAL,HOME,HOU,W (+7),1,38:32,10,18,...,28.8,3,4,0.750,0,4,1,0,0,Dirk Nowitzki
3,2012-03-19,33-274,DAL,AWAY,DEN,W (+17),1,31:21,12,19,...,28.5,3,4,0.750,1,10,0,1,3,Dirk Nowitzki
4,2012-02-10,33-236,DAL,AWAY,MIN,W (+7),1,35:04,11,19,...,27.5,4,7,0.571,1,3,1,3,1,Dirk Nowitzki

In [41]:
DAL_2013_gamelog = []

for p in DAL_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2013_gamelog.append(player_log)
DAL_2013_gamelog = pd.concat(DAL_2013_gamelog)    
DAL_2013_gamelogs = DAL_2013_gamelog.copy()
DAL_2013_gamelogs['GAME_SCORE'] = DAL_2013_gamelogs['GAME_SCORE'].astype(float)
DAL_2013_games = DAL_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2013_games_csv = DAL_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2013_games.csv', index=False)
DAL_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2013_games.csv')
DAL_2013_games_proc.head()

You searched for "Josh Akognon"
4 results found.
0: Josh Akognon
1: Josh Okogie
2: Josh Boone
3: Josh Jackson
Pick one: 0
Results for Josh Akognon:

You searched for "Rodrigue Beaubois"
1 result found.
Rodrigue Beaubois
Results for Rodrigue Beaubois:

You searched for "Elton Brand"
1 result found.
Elton Brand
Results for Elton Brand:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Darren Collison"
3 results found.
0: Darren Collison
1: Darren Tillis
2: Jarron Collins
Pick one: 0
Results for Darren Collison:

You searched for "Jae Crowder"
4 results found.
0: Jae Crowder
1: Joe Cooper
2: Corey Crowder
3: Joe Strawder
Pick one: 0
Results for Jae Crowder:

You searched for "Jared Cunningham"
2 results found.
0: Jared Cunningham
1: Dante Cunningham
Pick one: 0
Results for Jared Cunningham:

You searched for "Eddy Curry"
4 results found.
0: Eddy Curry
1: Dell Curry
2: Seth Curry
3: Kenny Carr
Pick one: 0
Results for Eddy Curry:

You searched for "Justin Dentmon"
2 results found.
0: Justin Dentmon
1: Justin Patton
Pick one: 0
Results for Justin Dentmon:

You searched for "Chris Douglas-Roberts"
1 result found.
Chris Douglas-Roberts
Results for Chris Douglas-Roberts:

You searched for "Derek Fisher"
2 results found.
0: Derek Fisher
1: Derek Harper
Pick one: 0
Results for Derek Fisher:

You searched for "Bernard James"
3 results found.
0: Bernard James
1: Henry James
2: Bernard Toone
Pick one: 0
Results for Bernard James:

You searched for "Mike James"
33 results found.
0: Mike James
1: Mike James
2: Mike Davis
3: Mike Davis
4: Mike Farmer
5: Mike Gale
6: Gene James
7: Tim James
8: Mike Niles
9: Mike Barr
10: Mike Evans
11: Mike Green
12: Mike Hall
13: Mike Harper
14: Mike Harris
15: Mike Jackson
16: Billy James
17: Damion James
18: Jake Jones
19: Mike Kearns
20: Mike Lewis
21: Mike Maloy
22: Mike McGee
23: Mike Sanders
24: Mike Smrek
25: Mike Tobey
26: Mike Wilks
27: Mike Bantom
28: Mike Bloom
29: Mike Bratz
30: Mike Novak
31: Mike Pratt
32: Mike Price
Pick one: 0
Results for Mike James:

You searched for "Dahntay Jones"
5 results found.
0: Dahntay Jones
1: Damian Jones
2: Dontae' Jones
3: Johnny Jones
4: Wah Wah Jones
Pick one: 0
Results for Dahntay Jones:

You searched for "Dominique Jones"
1 result found.
Dominique Jones
Results for Dominique Jones:

You searched for "Chris Kaman"
12 results found.
0: Chris Kaman
1: Chris Babb
2: Chris Carr
3: Chris Duhon
4: Chris King
5: Chris Munk
6: Chris Paul
7: Chris Quinn
8: Chris Taft
9: Chris Jent
10: Chris Mihm
11: Chris Silva
Pick one: 0
Results for Chris Kaman:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "O.J. Mayo"
2 results found.
0: O.J. Mayo
1: T.J. Leaf
Pick one: 0
Results for O.J. Mayo:

You searched for "Anthony Morrow"
10 results found.
0: Anthony Morrow
1: Anthony Brown
2: Anthony Cook
3: Anthony Mason
4: Anthony Bonner
5: Anthony Bowie
6: Anthony Carter
7: Anthony Miller
8: Anthony Parker
9: Anthony Taylor
Pick one: 0
Results for Anthony Morrow:

You searched for "Troy Murphy"
8 results found.
0: Troy Murphy
1: Tod Murphy
2: Erik Murphy
3: Jay Murphy
4: Roy Hurley
5: Dick Murphy
6: John Murphy
7: Tracy Murray
Pick one: 0
Results for Troy Murphy:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

You searched for "Chris Wright"
12 results found.
0: Chris Wright
1: Chris Wright
2: Chris Mihm
3: Chris Smith
4: Chris Smith
5: Brad Wright
6: Howie Wright
7: Larry Wright
8: Leroy Wright
9: Chris Webber
10: Chris Harris
11: Chris Morris
Pick one: 0
Results for Chris Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-01-29,35-224,DAL,HOME,HOU,L (-2),1,35:04,13,21,...,17,3,0,0,2,1,38,34.9,6,Dirk Nowitzki
1,2014-01-11,35-206,DAL,HOME,NOP,W (+3),1,33:27,10,20,...,4,4,2,0,1,2,40,33.8,11,Dirk Nowitzki
2,2012-12-08,25-033,DAL,AWAY,HOU,W (+7),1,42:02,15,26,...,8,3,2,0,2,2,40,31.9,20,O.J. Mayo
3,2014-04-01,35-286,DAL,HOME,GSW,L (-2),1,39:40,13,21,...,11,3,2,1,0,0,33,31.2,-1,Dirk Nowitzki
4,2013-11-20,35-154,DAL,HOME,HOU,W (+3),1,33:38,13,20,...,7,4,1,1,1,3,35,31.0,6,Dirk Nowitzki

In [42]:
DAL_2014_gamelog = []

for p in DAL_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2014_gamelog.append(player_log)
DAL_2014_gamelog = pd.concat(DAL_2014_gamelog)    
DAL_2014_gamelogs = DAL_2014_gamelog.copy()
DAL_2014_gamelogs['GAME_SCORE'] = DAL_2014_gamelogs['GAME_SCORE'].astype(float)
DAL_2014_games = DAL_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2014_games_csv = DAL_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2014_games.csv', index=False)
DAL_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2014_games.csv')
DAL_2014_games_proc.head()

You searched for "DeJuan Blair"
2 results found.
0: DeJuan Blair
1: DeJuan Wheat
Pick one: 0
Results for DeJuan Blair:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Jae Crowder"
4 results found.
0: Jae Crowder
1: Joe Cooper
2: Corey Crowder
3: Joe Strawder
Pick one: 0
Results for Jae Crowder:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Wayne Ellington"
1 result found.
Wayne Ellington
Results for Wayne Ellington:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Bernard James"
3 results found.
0: Bernard James
1: Henry James
2: Bernard Toone
Pick one: 0
Results for Bernard James:

You searched for "Shane Larkin"
1 result found.
Shane Larkin
Results for Shane Larkin:

You searched for "Ricky Ledo"
7 results found.
0: Ricky Ledo
1: Ricky Berry
2: Dick Lee
3: Rock Lee
4: Ricky Rubio
5: Rick Fox
6: Ricky Grace
Pick one: 0
Results for Ricky Ledo:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Gal Mekel"
4 results found.
0: Gal Mekel
1: Hal Jeter
2: Fab Melo
3: Ken Menke
Pick one: 0
Results for Gal Mekel:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-01-29,35-224,DAL,HOME,HOU,L (-2),1,35:04,13,21,...,17,3,0,0,2,1,38,34.9,6,Dirk Nowitzki
1,2014-01-11,35-206,DAL,HOME,NOP,W (+3),1,33:27,10,20,...,4,4,2,0,1,2,40,33.8,11,Dirk Nowitzki
2,2013-11-20,28-025,DAL,HOME,HOU,W (+3),1,40:17,13,18,...,2,9,2,0,3,4,37,32.7,2,Monta Ellis
3,2014-04-01,35-286,DAL,HOME,GSW,L (-2),1,39:40,13,21,...,11,3,2,1,0,0,33,31.2,-1,Dirk Nowitzki
4,2013-11-20,35-154,DAL,HOME,HOU,W (+3),1,33:38,13,20,...,7,4,1,1,1,3,35,31.0,6,Dirk Nowitzki

In [47]:
# remofed jj barea
# removed greg smith

DAL_2015_gamelog = []

for p in DAL_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2015_gamelog.append(player_log)
DAL_2015_gamelog = pd.concat(DAL_2015_gamelog)    
DAL_2015_gamelogs = DAL_2015_gamelog.copy()
DAL_2015_gamelogs['GAME_SCORE'] = DAL_2015_gamelogs['GAME_SCORE'].astype(float)
DAL_2015_games = DAL_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2015_games_csv = DAL_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2015_games.csv', index=False)
DAL_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2015_games.csv')
DAL_2015_games_proc.head()

You searched for "Al-Farouq Aminu"
1 result found.
Al-Farouq Aminu
Results for Al-Farouq Aminu:

You searched for "Tyson Chandler"
3 results found.
0: Tyson Chandler
1: Wilson Chandler
2: Tyson Wheeler
Pick one: 0
Results for Tyson Chandler:

You searched for "Jae Crowder"
4 results found.
0: Jae Crowder
1: Joe Cooper
2: Corey Crowder
3: Joe Strawder
Pick one: 0
Results for Jae Crowder:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Raymond Felton"
1 result found.
Raymond Felton
Results for Raymond Felton:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Bernard James"
3 results found.
0: Bernard James
1: Henry James
2: Bernard Toone
Pick one: 0
Results for Bernard James:

You searched for "Richard Jefferson"
2 results found.
0: Richard Jefferson
1: Richard Anderson
Pick one: 0
Results for Richard Jefferson:

You searched for "Ricky Ledo"
7 results found.
0: Ricky Ledo
1: Ricky Berry
2: Dick Lee
3: Rock Lee
4: Ricky Rubio
5: Rick Fox
6: Ricky Grace
Pick one: 0
Results for Ricky Ledo:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Chandler Parsons"
1 result found.
Chandler Parsons
Results for Chandler Parsons:

You searched for "Dwight Powell"
3 results found.
0: Dwight Powell
1: Dwight Howard
2: Dwight Jones
Pick one: 0
Results for Dwight Powell:

You searched for "Rajon Rondo"
2 results found.
0: Rajon Rondo
1: Brandon Roy
Pick one: 0
Results for Rajon Rondo:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "Charlie Villanueva"
1 result found.
Charlie Villanueva
Results for Charlie Villanueva:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-12-20,29-055,DAL,HOME,SAS,W (+6),1,40:15,15,23,...,0,1,4,0,2,1,38,29.0,15,Monta Ellis
1,2014-12-17,26-053,DAL,AWAY,DET,W (+11),1,35:29,10,17,...,7,2,2,0,2,0,32,28.4,15,Chandler Parsons
2,2015-03-24,29-149,DAL,HOME,SAS,W (+7),1,39:47,16,27,...,2,5,2,0,3,2,38,27.8,3,Monta Ellis
3,2014-12-09,26-045,DAL,AWAY,MEM,L (-9),1,33:32,10,18,...,7,3,2,1,1,0,30,27.3,-5,Chandler Parsons
4,2014-11-29,32-058,DAL,AWAY,PHI,W (+7),1,31:47,7,9,...,13,3,4,0,1,2,20,27.1,29,Tyson Chandler

In [50]:
# removed david lee
DAL_2016_gamelog = []

for p in DAL_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2016_gamelog.append(player_log)
DAL_2016_gamelog = pd.concat(DAL_2016_gamelog)    
DAL_2016_gamelogs = DAL_2016_gamelog.copy()
DAL_2016_gamelogs['GAME_SCORE'] = DAL_2016_gamelogs['GAME_SCORE'].astype(float)
DAL_2016_games = DAL_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2016_games_csv = DAL_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2016_games.csv', index=False)
DAL_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2016_games.csv')
DAL_2016_games_proc.head()

You searched for "Justin Anderson"
1 result found.
Justin Anderson
Results for Justin Anderson:

You searched for "Jeremy Evans"
5 results found.
0: Jeremy Evans
1: Tyreke Evans
2: Jeremy Lamb
3: Jeremy Lin
4: Jeremy Tyler
Pick one: 0
Results for Jeremy Evans:

You searched for "Raymond Felton"
1 result found.
Raymond Felton
Results for Raymond Felton:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "John Jenkins"
5 results found.
0: John Jenkins
1: John Collins
2: John Henson
3: John Johnson
4: John Mahnken
Pick one: 0
Results for John Jenkins:

You searched for "Wesley Matthews"
2 results found.
0: Wesley Matthews
1: Wes Matthews
Pick one: 0
Results for Wesley Matthews:

You searched for "JaVale McGee"
1 result found.
JaVale McGee
Results for JaVale McGee:

You searched for "Salah Mejri"
1 result found.
Salah Mejri
Results for Salah Mejri:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Zaza Pachulia"
1 result found.
Zaza Pachulia
Results for Zaza Pachulia:

You searched for "Chandler Parsons"
1 result found.
Chandler Parsons
Results for Chandler Parsons:

You searched for "Dwight Powell"
3 results found.
0: Dwight Powell
1: Dwight Howard
2: Dwight Jones
Pick one: 0
Results for Dwight Powell:

You searched for "Charlie Villanueva"
1 result found.
Charlie Villanueva
Results for Charlie Villanueva:

You searched for "Deron Williams"
33 results found.
0: Deron Williams
1: Aaron Williams
2: Ron Williams
3: Eric Williams
4: Herb Williams
5: Jason Williams
6: Jerome Williams
7: Kevin Williams
8: Rob Williams
9: Sean Williams
10: Troy Williams
11: Alan Williams
12: Alvin Williams
13: Art Williams
14: Bernie Williams
15: Bob Williams
16: Corey Williams
17: Derrick Williams
18: Duck Williams
19: Earl Williams
20: Frank Williams
21: Gene Williams
22: Grant Williams
23: Jayson Williams
24: John Williams
25: Jordan Williams
26: Kenny Williams
27: Lou Williams
28: Marvin Williams
29: Mo Williams
30: Pete Williams
31: Ray Williams
32: Ward Williams
Pick one: 0
Results for Deron Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-03-20,31-268,DAL,HOME,POR,W (+12),1,42:39,11,18,...,3,16,3,0,5,0,31,32.9,20,Deron Williams
1,2016-03-20,37-275,DAL,HOME,POR,W (+12),1,39:11,16,26,...,8,4,2,0,2,5,40,31.4,7,Dirk Nowitzki
2,2015-12-06,29-053,DAL,AWAY,WAS,W (+12),1,41:07,12,23,...,6,5,1,1,1,2,36,29.9,21,Wesley Matthews
3,2015-12-01,31-158,DAL,AWAY,POR,W (+3),1,44:45,11,17,...,6,8,0,2,1,4,30,28.7,-3,Deron Williams
4,2016-02-28,27-126,DAL,HOME,MIN,W (+27),1,26:58,10,15,...,6,4,1,0,0,1,29,28.1,31,Chandler Parsons

In [51]:


DAL_2017_gamelog = []

for p in DAL_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2017_gamelog.append(player_log)
DAL_2017_gamelog = pd.concat(DAL_2017_gamelog)    
DAL_2017_gamelogs = DAL_2017_gamelog.copy()
DAL_2017_gamelogs['GAME_SCORE'] = DAL_2017_gamelogs['GAME_SCORE'].astype(float)
DAL_2017_games = DAL_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2017_games_csv = DAL_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2017_games.csv', index=False)
DAL_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2017_games.csv')
DAL_2017_games_proc.head()

You searched for "Quincy Acy"
2 results found.
0: Quincy Acy
1: Quincy Douby
Pick one: 0
Results for Quincy Acy:

You searched for "Justin Anderson"
1 result found.
Justin Anderson
Results for Justin Anderson:

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Ben Bentil"
2 results found.
0: Ben Bentil
1: Ben Kelso
Pick one: 0
Results for Ben Bentil:

You searched for "Andrew Bogut"
4 results found.
0: Andrew Bogut
1: Andrew Bynum
2: Andrew Toney
3: Andrew Gaze
Pick one: 0
Results for Andrew Bogut:

You searched for "Nicolás Brussino"
1 result found.
Nicolas Brussino
Results for Nicolas Brussino:

You searched for "Quinn Cook"
3 results found.
0: Quinn Cook
1: Brian Cook
2: Quincy Acy
Pick one: 0
Results for Quinn Cook:

You searched for "Seth Curry"
4 results found.
0: Seth Curry
1: Dell Curry
2: Eddy Curry
3: Stephen Curry
Pick one: 0
Results for Seth Curry:

You searched for "Yogi Ferrell"
1 result found.
Yogi Ferrell
Results for Yogi Ferrell:

You searched for "Dorian Finney-Smith"
1 result found.
Dorian Finney-Smith
Results for Dorian Finney-Smith:

You searched for "Jonathan Gibson"
2 results found.
0: Jonathan Gibson
1: Jonathan Isaac
Pick one: 0
Results for Jonathan Gibson:

You searched for "A.J. Hammons"
2 results found.
0: A.J. Hammons
1: R.J. Hampton
Pick one: 0
Results for A.J. Hammons:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Manny Harris"
7 results found.
0: Manny Harris
1: Gary Harris
2: Tony Harris
3: Jalen Harris
4: Art Harris
5: Billy Harris
6: Mike Harris
Pick one: 0
Results for Manny Harris:

You searched for "Pierre Jackson"
2 results found.
0: Pierre Jackson
1: Mike Jackson
Pick one: 0
Results for Pierre Jackson:

You searched for "DeAndre Liggins"
2 results found.
0: DeAndre Liggins
1: Andrew Wiggins
Pick one: 0
Results for DeAndre Liggins:

You searched for "Wesley Matthews"
2 results found.
0: Wesley Matthews
1: Wes Matthews
Pick one: 0
Results for Wesley Matthews:

You searched for "Salah Mejri"
1 result found.
Salah Mejri
Results for Salah Mejri:

You searched for "Nerlens Noel"
1 result found.
Nerlens Noel
Results for Nerlens Noel:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Dwight Powell"
3 results found.
0: Dwight Powell
1: Dwight Howard
2: Dwight Jones
Pick one: 0
Results for Dwight Powell:

You searched for "Jarrod Uthoff"
1 result found.
Jarrod Uthoff
Results for Jarrod Uthoff:

You searched for "Deron Williams"
33 results found.
0: Deron Williams
1: Aaron Williams
2: Ron Williams
3: Eric Williams
4: Herb Williams
5: Jason Williams
6: Jerome Williams
7: Kevin Williams
8: Rob Williams
9: Sean Williams
10: Troy Williams
11: Alan Williams
12: Alvin Williams
13: Art Williams
14: Bernie Williams
15: Bob Williams
16: Corey Williams
17: Derrick Williams
18: Duck Williams
19: Earl Williams
20: Frank Williams
21: Gene Williams
22: Grant Williams
23: Jayson Williams
24: John Williams
25: Jordan Williams
26: Kenny Williams
27: Lou Williams
28: Marvin Williams
29: Mo Williams
30: Pete Williams
31: Ray Williams
32: Ward Williams
Pick one: 0
Results for Deron Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-11-06,24-160,DAL,HOME,MIL,W (+11),1,48:23,13,26,...,8,2,2,0,1,0,34,26.6,14,Harrison Barnes
1,2017-02-03,23-270,DAL,AWAY,POR,W (+4),1,39:05,11,17,...,2,5,0,0,2,4,32,24.6,3,Yogi Ferrell
2,2017-04-12,23-144,PHI,AWAY,NYK,L (-1),1,34:35,9,11,...,2,3,3,1,2,3,26,24.3,8,Justin Anderson
3,2017-04-02,24-307,DAL,AWAY,MIL,W (+4),1,38:54,9,13,...,2,0,1,0,3,2,31,23.3,-3,Harrison Barnes
4,2017-01-24,22-289,PHI,HOME,LAC,W (+11),1,29:16,8,10,...,8,5,2,3,1,4,19,23.0,-2,Nerlens Noel

In [56]:


DAL_2018_gamelog = []

for p in DAL_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2018_gamelog.append(player_log)
DAL_2018_gamelog = pd.concat(DAL_2018_gamelog)    
DAL_2018_gamelogs = DAL_2018_gamelog.copy()
DAL_2018_gamelogs['GAME_SCORE'] = DAL_2018_gamelogs['GAME_SCORE'].astype(float)
DAL_2018_games = DAL_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2018_games_csv = DAL_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2018_games.csv', index=False)
DAL_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2018_games.csv')
DAL_2018_games_proc.head()

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Gian Clavell"
1 result found.
Gian Clavell
Results for Gian Clavell:

You searched for "Antonius Cleveland"
1 result found.
Antonius Cleveland
Results for Antonius Cleveland:

You searched for "Kyle Collinsworth"
1 result found.
Kyle Collinsworth
Results for Kyle Collinsworth:

You searched for "Yogi Ferrell"
1 result found.
Yogi Ferrell
Results for Yogi Ferrell:

You searched for "Dorian Finney-Smith"
1 result found.
Dorian Finney-Smith
Results for Dorian Finney-Smith:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Aaron Harrison"
5 results found.
0: Aaron Harrison
1: Andrew Harrison
2: Bob Harrison
3: David Harrison
4: Aaron Jackson
Pick one: 0
Results for Aaron Harrison:

You searched for "Scotty Hopson"
1 result found.
Scotty Hopson
Results for Scotty Hopson:

You searched for "Jalen Jones"
27 results found.
0: Jalen Jones
1: Jake Jones
2: James Jones
3: Mason Jones
4: Alvin Jones
5: Damon Jones
6: Wali Jones
7: Jalen Rose
8: Tre Jones
9: Bill Jones
10: Charles Jones
11: Charles Jones
12: Charles Jones
13: Damian Jones
14: Earl Jones
15: Fred Jones
16: Jimmy Jones
17: Johnny Jones
18: Kevin Jones
19: Larry Jones
20: Major Jones
21: Mark Jones
22: Mark Jones
23: Robin Jones
24: Sam Jones
25: Wil Jones
26: Jaylen Brown
Pick one: 0
Results for Jalen Jones:

You searched for "Wesley Matthews"
2 results found.
0: Wesley Matthews
1: Wes Matthews
Pick one: 0
Results for Wesley Matthews:

You searched for "Doug McDermott"
2 results found.
0: Doug McDermott
1: Sean McDermott
Pick one: 0
Results for Doug McDermott:

You searched for "Josh McRoberts"
2 results found.
0: Josh McRoberts
1: Joe Roberts
Pick one: 0
Results for Josh McRoberts:

You searched for "Salah Mejri"
1 result found.
Salah Mejri
Results for Salah Mejri:

You searched for "Johnathan Motley"
1 result found.
Johnathan Motley
Results for Johnathan Motley:

You searched for "Nerlens Noel"
1 result found.
Nerlens Noel
Results for Nerlens Noel:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Dwight Powell"
3 results found.
0: Dwight Powell
1: Dwight Howard
2: Dwight Jones
Pick one: 0
Results for Dwight Powell:

You searched for "Jameel Warney"
1 result found.
Jameel Warney
Results for Jameel Warney:

You searched for "Jeff Withey"
2 results found.
0: Jeff Withey
1: Jeff Webb
Pick one: 0
Results for Jeff Withey:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-01-24,31-102,DAL,HOME,HOU,L (-7),1,38:05,10,18,...,4,5,2,1,2,2,29,25.0,-17,Wesley Matthews
1,2018-01-10,25-225,DAL,AWAY,CHO,W (+4),1,35:05,9,13,...,11,2,0,1,0,1,25,24.9,5,Harrison Barnes
2,2018-04-01,25-306,DAL,AWAY,CLE,L (-11),1,36:12,10,19,...,3,5,0,0,1,0,30,24.1,0,Harrison Barnes
3,2017-11-07,25-161,DAL,AWAY,WAS,W (+14),1,39:25,11,18,...,9,1,1,1,3,3,31,24.1,12,Harrison Barnes
4,2018-03-13,25-287,DAL,AWAY,NYK,W (+13),1,33:57,10,19,...,4,4,0,0,2,0,30,23.5,17,Harrison Barnes

In [62]:


DAL_2019_gamelog = []

for p in DAL_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2019_gamelog.append(player_log)
DAL_2019_gamelog = pd.concat(DAL_2019_gamelog)    
DAL_2019_gamelogs = DAL_2019_gamelog.copy()
DAL_2019_gamelogs['GAME_SCORE'] = DAL_2019_gamelogs['GAME_SCORE'].astype(float)
DAL_2019_games = DAL_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2019_games_csv = DAL_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2019_games.csv', index=False)
DAL_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2019_games.csv')
DAL_2019_games_proc.head()

You searched for "Kostas Antetokounmpo"
1 result found.
Kostas Antetokounmpo
Results for Kostas Antetokounmpo:

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Ryan Broekhoff"
1 result found.
Ryan Broekhoff
Results for Ryan Broekhoff:

You searched for "Jalen Brunson"
1 result found.
Jalen Brunson
Results for Jalen Brunson:

You searched for "Trey Burke"
5 results found.
0: Trey Burke
1: Pat Burke
2: Alec Burks
3: Corey Beck
4: Troy Bell
Pick one: 0
Results for Trey Burke:

You searched for "Luka Dončić"
1 result found.
Luka Doncic
Results for Luka Doncic:

You searched for "Dorian Finney-Smith"
1 result found.
Dorian Finney-Smith
Results for Dorian Finney-Smith:

You searched for "Tim Hardaway"
2 results found.
0: Tim Hardaway
1: Tim Hardaway Jr.
Pick one: 1
Results for Tim Hardaway Jr.:

You searched for "Devin Harris"
8 results found.
0: Devin Harris
1: Jalen Harris
2: Bernie Harris
3: Chris Harris
4: Elias Harris
5: Steve Harris
6: David Harrison
7: Kevin Martin
Pick one: 0
Results for Devin Harris:

You searched for "Justin Jackson"
8 results found.
0: Justin Jackson
1: Jaren Jackson
2: Jaren Jackson
3: Jim Jackson
4: Josh Jackson
5: Mervin Jackson
6: Justin James
7: Justin Patton
Pick one: 0
Results for Justin Jackson:

You searched for "DeAndre Jordan"
2 results found.
0: DeAndre Jordan
1: Eddie Jordan
Pick one: 0
Results for DeAndre Jordan:

You searched for "Courtney Lee"
3 results found.
0: Courtney Lee
1: Courtney Sims
2: Joe Courtney
Pick one: 0
Results for Courtney Lee:

You searched for "Daryl Macon"
3 results found.
0: Daryl Macon
1: Mark Macon
2: Karl Malone
Pick one: 0
Results for Daryl Macon:

You searched for "Wesley Matthews"
2 results found.
0: Wesley Matthews
1: Wes Matthews
Pick one: 0
Results for Wesley Matthews:

You searched for "Salah Mejri"
1 result found.
Salah Mejri
Results for Salah Mejri:

You searched for "Dirk Nowitzki"
1 result found.
Dirk Nowitzki
Results for Dirk Nowitzki:

You searched for "Dwight Powell"
3 results found.
0: Dwight Powell
1: Dwight Howard
2: Dwight Jones
Pick one: 0
Results for Dwight Powell:

You searched for "Ray Spalding"
1 result found.
Ray Spalding
Results for Ray Spalding:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-03-12,22-193,DAL,HOME,SAS,L (-7),1,36:31,12,16,...,5,4,1,0,1,1,34,31.5,5,Jalen Brunson
1,2019-01-27,19-333,DAL,HOME,TOR,L (-3),1,35:53,14,24,...,12,10,0,0,3,3,35,30.2,-2,Luka Dončić
2,2019-02-25,27-220,DAL,AWAY,LAC,L (-9),1,36:44,10,11,...,8,4,2,2,0,2,24,29.7,-3,Dwight Powell
3,2019-04-03,27-257,DAL,HOME,MIN,L (-2),1,30:35,8,9,...,8,2,2,1,0,3,25,28.4,-1,Dwight Powell
4,2019-03-06,27-229,DAL,AWAY,WAS,L (-9),1,36:00,11,12,...,10,2,0,1,0,0,26,27.9,-15,Dwight Powell

In [65]:


DAL_2020_gamelog = []

for p in DAL_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2020_gamelog.append(player_log)
DAL_2020_gamelog = pd.concat(DAL_2020_gamelog)    
DAL_2020_gamelogs = DAL_2020_gamelog.copy()
DAL_2020_gamelogs['GAME_SCORE'] = DAL_2020_gamelogs['GAME_SCORE'].astype(float)
DAL_2020_games = DAL_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2020_games_csv = DAL_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2020_games.csv', index=False)
DAL_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2020_games.csv')
DAL_2020_games_proc.head()

You searched for "Ryan Broekhoff"
1 result found.
Ryan Broekhoff
Results for Ryan Broekhoff:

You searched for "Jalen Brunson"
1 result found.
Jalen Brunson
Results for Jalen Brunson:

You searched for "Trey Burke"
5 results found.
0: Trey Burke
1: Pat Burke
2: Alec Burks
3: Corey Beck
4: Troy Bell
Pick one: 0
Results for Trey Burke:

You searched for "Willie Cauley-Stein"
1 result found.
Willie Cauley-Stein
Results for Willie Cauley-Stein:

You searched for "Antonius Cleveland"
1 result found.
Antonius Cleveland
Results for Antonius Cleveland:

You searched for "Seth Curry"
4 results found.
0: Seth Curry
1: Dell Curry
2: Eddy Curry
3: Stephen Curry
Pick one: 0
Results for Seth Curry:

You searched for "Luka Dončić"
1 result found.
Luka Doncic
Results for Luka Doncic:

You searched for "Dorian Finney-Smith"
1 result found.
Dorian Finney-Smith
Results for Dorian Finney-Smith:

You searched for "Tim Hardaway"
2 results found.
0: Tim Hardaway
1: Tim Hardaway Jr.
Pick one: 1
Results for Tim Hardaway Jr.:

You searched for "Justin Jackson"
8 results found.
0: Justin Jackson
1: Jaren Jackson
2: Jaren Jackson
3: Jim Jackson
4: Josh Jackson
5: Mervin Jackson
6: Justin James
7: Justin Patton
Pick one: 0
Results for Justin Jackson:

You searched for "Courtney Lee"
3 results found.
0: Courtney Lee
1: Courtney Sims
2: Joe Courtney
Pick one: 0
Results for Courtney Lee:

You searched for "Boban Marjanović"
1 result found.
Boban Marjanovic
Results for Boban Marjanovic:

You searched for "Kristaps Porziņģis"
1 result found.
Kristaps Porzingis
Results for Kristaps Porzingis:

You searched for "Dwight Powell"
3 results found.
0: Dwight Powell
1: Dwight Howard
2: Dwight Jones
Pick one: 0
Results for Dwight Powell:

You searched for "Josh Reaves"
4 results found.
0: Josh Reaves
1: Joe Reaves
2: Josh Davis
3: Josh Green
Pick one: 0
Results for Josh Reaves:

You searched for "Delon Wright"
4 results found.
0: Delon Wright
1: Leroy Wright
2: Dorell Wright
3: Julian Wright
Pick one: 0
Results for Delon Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-08-08,21-162,DAL,HOME,MIL,W (+4),1,41:34,12,24,...,14,19,1,0,2,1,36,40.1,12,Luka Dončić
1,2019-11-29,20-274,DAL,AWAY,PHO,W (+7),1,37:33,12,24,...,9,11,1,0,2,4,42,37.4,3,Luka Dončić
2,2019-12-28,20-303,DAL,AWAY,GSW,W (+20),1,30:05,8,16,...,12,15,2,0,3,0,31,36.9,20,Luka Dončić
3,2019-12-12,20-287,DAL,AWAY,DET,W (+11),1,33:39,14,24,...,12,11,0,0,3,2,41,35.7,29,Luka Dončić
4,2019-11-20,20-265,DAL,HOME,GSW,W (+48),1,25:30,11,18,...,10,11,4,0,5,3,35,35.3,45,Luka Dončić

In [66]:

DAL_2021_gamelog = []

for p in DAL_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    DAL_2021_gamelog.append(player_log)
DAL_2021_gamelog = pd.concat(DAL_2021_gamelog)    
DAL_2021_gamelogs = DAL_2021_gamelog.copy()
DAL_2021_gamelogs['GAME_SCORE'] = DAL_2021_gamelogs['GAME_SCORE'].astype(float)
DAL_2021_games = DAL_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_2021_games_csv = DAL_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2021_games.csv', index=False)
DAL_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2021_games.csv')
DAL_2021_games_proc.head()

You searched for "Tyler Bey"
7 results found.
0: Tyler Bey
1: Tyler Cook
2: Tyler Dorsey
3: Kyle Guy
4: Tyler Herro
5: Tyler Ulis
6: Ty Jerome
Pick one: 0
Results for Tyler Bey:

You searched for "Jalen Brunson"
1 result found.
Jalen Brunson
Results for Jalen Brunson:

You searched for "Trey Burke"
5 results found.
0: Trey Burke
1: Pat Burke
2: Alec Burks
3: Corey Beck
4: Troy Bell
Pick one: 0
Results for Trey Burke:

You searched for "Willie Cauley-Stein"
1 result found.
Willie Cauley-Stein
Results for Willie Cauley-Stein:

You searched for "Luka Dončić"
1 result found.
Luka Doncic
Results for Luka Doncic:

You searched for "Dorian Finney-Smith"
1 result found.
Dorian Finney-Smith
Results for Dorian Finney-Smith:

You searched for "Josh Green"
14 results found.
0: Josh Green
1: Josh Grant
2: Josh Gray
3: Jeff Green
4: Si Green
5: A.C. Green
6: Johnny Green
7: Ken Green
8: Mike Green
9: Sean Green
10: John Greig
11: Josh Reaves
12: Josh Boone
13: Josh Okogie
Pick one: 0
Results for Josh Green:

You searched for "Tim Hardaway"
2 results found.
0: Tim Hardaway
1: Tim Hardaway Jr.
Pick one: 1
Results for Tim Hardaway Jr.:

You searched for "Nate Hinton"
4 results found.
0: Nate Hinton
1: Nat Clifton
2: Nate Johnston
3: Nate Robinson
Pick one: 0
Results for Nate Hinton:

You searched for "Wesley Iwundu"
1 result found.
Wesley Iwundu
Results for Wesley Iwundu:

You searched for "James Johnson"
32 results found.
0: James Johnson
1: Amir Johnson
2: Dave Johnson
3: Joe Johnson
4: James Robinson
5: James Cotton
6: Andy Johnson
7: Armon Johnson
8: Avery Johnson
9: Cameron Johnson
10: Charles Johnson
11: Cheese Johnson
12: Chris Johnson
13: Chris Johnson
14: Ed Johnson
15: Gus Johnson
16: JaJuan Johnson
17: John Johnson
18: Ken Johnson
19: Ken Johnson
20: Larry Johnson
21: Larry Johnson
22: Lee Johnson
23: Magic Johnson
24: Marques Johnson
25: Ralph Johnson
26: Stew Johnson
27: Trey Johnson
28: Tyler Johnson
29: Nate Johnston
30: James Jones
31: James Collins
Pick one: 0
Results for James Johnson:

You searched for "Boban Marjanović"
1 result found.
Boban Marjanovic
Results for Boban Marjanovic:

You searched for "Nicolò Melli"
1 result found.
Nicolo Melli
Results for Nicolo Melli:

You searched for "Kristaps Porziņģis"
1 result found.
Kristaps Porzingis
Results for Kristaps Porzingis:

You searched for "Dwight Powell"
3 results found.
0: Dwight Powell
1: Dwight Howard
2: Dwight Jones
Pick one: 0
Results for Dwight Powell:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Josh Richardson"
4 results found.
0: Josh Richardson
1: Pooh Richardson
2: Jason Richardson
3: Norm Richardson
Pick one: 0
Results for Josh Richardson:

You searched for "Tyrell Terry"
1 result found.
Tyrell Terry
Results for Tyrell Terry:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-02-12,21-350,DAL,HOME,NOP,W (+13),1,40:01,17,30,...,8,12,1,1,3,4,46,39.3,13,Luka Dončić
1,2021-02-14,21-352,DAL,HOME,POR,L (-3),1,36:21,14,20,...,7,9,0,0,5,4,44,37.4,-10,Luka Dončić
2,2021-01-25,21-332,DAL,HOME,DEN,L (-4),1,39:03,11,23,...,11,16,4,1,5,3,35,37.1,8,Luka Dončić
3,2021-03-17,22-017,DAL,HOME,LAC,W (+16),1,42:48,16,28,...,6,9,3,2,4,2,42,36.5,29,Luka Dončić
4,2021-01-07,21-314,DAL,AWAY,DEN,W (+7),1,43:17,13,22,...,9,13,5,1,8,0,38,35.3,14,Luka Dončić

## combine all seasons

In [67]:
DAL_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2000_games.csv')
DAL_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2001_games.csv')
DAL_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2002_games.csv')
DAL_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2003_games.csv')
DAL_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2004_games.csv')
DAL_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2005_games.csv')
DAL_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2006_games.csv')
DAL_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2007_games.csv')
DAL_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2008_games.csv')
DAL_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2009_games.csv')
DAL_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2010_games.csv')
DAL_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2011_games.csv')
DAL_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2012_games.csv')
DAL_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2013_games.csv')
DAL_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2014_games.csv')
DAL_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2015_games.csv')
DAL_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2016_games.csv')
DAL_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2017_games.csv')
DAL_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2018_games.csv')
DAL_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2019_games.csv')
DAL_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2020_games.csv')
DAL_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DAL/DAL_2021_games.csv')

In [68]:
DAL_season_dfs = [DAL_2000_games_io, DAL_2001_games_io, DAL_2002_games_io, DAL_2003_games_io, DAL_2004_games_io, DAL_2005_games_io,
                 DAL_2006_games_io, DAL_2007_games_io, DAL_2008_games_io, DAL_2009_games_io, DAL_2010_games_io, DAL_2011_games_io,
                 DAL_2012_games_io, DAL_2013_games_io, DAL_2014_games_io, DAL_2015_games_io, DAL_2016_games_io, DAL_2017_games_io,
                 DAL_2018_games_io, DAL_2019_games_io, DAL_2020_games_io, DAL_2021_games_io]

In [69]:
DAL_all = pd.concat(DAL_season_dfs)
DAL_all_sorted = DAL_all.sort_values(by=['GAME_SCORE'], ascending=False)
DAL_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-12-02,26-166,DAL,HOME,HOU,W (+7),1,49:36,15,32,...,16,2,3,4,1,2,53,48.0,12,Dirk Nowitzki
0,2006-03-23,27-277,DAL,HOME,GSW,L (-1),1,40:50,16,24,...,9,5,2,1,5,3,51,44.1,3,Dirk Nowitzki
0,2007-12-08,27-224,DAL,HOME,UTA,W (+8),1,42:26,14,19,...,10,2,0,1,1,4,47,43.4,19,Josh Howard
0,2007-02-07,28-233,DAL,HOME,MEM,W (+16),1,37:33,14,20,...,10,6,3,4,0,3,38,42.6,14,Dirk Nowitzki
0,2009-11-03,31-137,DAL,HOME,UTA,W (+11),1,39:06,12,22,...,11,5,2,5,0,2,40,41.3,23,Dirk Nowitzki
0,2020-08-08,21-162,DAL,HOME,MIL,W (+4),1,41:34,12,24,...,14,19,1,0,2,1,36,40.1,12,Luka Dončić
0,2021-02-12,21-350,DAL,HOME,NOP,W (+13),1,40:01,17,30,...,8,12,1,1,3,4,46,39.3,13,Luka Dončić
1,2019-11-29,20-274,DAL,AWAY,PHO,W (+7),1,37:33,12,24,...,9,11,1,0,2,4,42,37.4,3,Luka Dončić
1,2021-02-14,21-352,DAL,HOME,POR,L (-3),1,36:21,14,20,...,7,9,0,0,5,4,44,37.4,-10,Luka Dončić
2,2021-01-25,21-332,DAL,HOME,DEN,L (-4),1,39:03,11,23,...,11,16,4,1,5,3,35,37.1,8,Luka Dončić
2,2019-12-28,20-303,DAL,AWAY,GSW,W (+20),1,30:05,8,16,...,12,15,2,0,3,0,31,36.9,20,Luka Dončić
3,2021-03-17,22-017,DAL,HOME,LAC,W (+16),1,42:48,16,28,...,6,9,3,2,4,2,42,36.5,29,Luka Dončić
0,2002-02-21,23-247,DAL,HOME,BOS,W (+6),1,44:42,12,23,...,23,8,1,4,3,2,33,36.2,1,Dirk Nowitzki
0,2002-12-30,24-194,DAL,HOME,MIL,L (-3),1,47:53,12,25,...,14,5,2,1,2,1,40,36.1,-3,Dirk Nowitzki
3,2019-12-12,20-287,DAL,AWAY,DET,W (+11),1,33:39,14,24,...,12,11,0,0,3,2,41,35.7,29,Luka Dončić
0,2009-01-13,30-208,DAL,AWAY,DEN,L (-2),1,42:05,15,26,...,14,0,1,0,1,3,44,35.6,7,Dirk Nowitzki
4,2019-11-20,20-265,DAL,HOME,GSW,W (+48),1,25:30,11,18,...,10,11,4,0,5,3,35,35.3,45,Luka Dončić
4,2021-01-07,21-314,DAL,AWAY,DEN,W (+7),1,43:17,13,22,...,9,13,5,1,8,0,38,35.3,14,Luka Dončić
0,2010-11-23,32-157,DAL,HOME,DET,W (+4),1,39:58,13,23,...,12,1,0,2,1,4,42,35.0,9,Dirk Nowitzki
1,2010-02-08,32-146,DAL,AWAY,GSW,W (+10),1,42:18,9,17,...,6,9,3,0,3,1,36,35.0,17,Jason Terry
1,2003-04-14,24-299,DAL,HOME,SEA,W (+3),1,45:36,14,21,...,10,7,1,1,3,3,39,34.9,2,Dirk Nowitzki
0,2014-01-29,35-224,DAL,HOME,HOU,L (-2),1,35:04,13,21,...,17,3,0,0,2,1,38,34.9,6,Dirk Nowitzki
0,2014-01-29,35-224,DAL,HOME,HOU,L (-2),1,35:04,13,21,...,17,3,0,0,2,1,38,34.9,6,Dirk Nowitzki
0,2004-02-07,25-233,DAL,HOME,DET,W (+3),1,42:23,15,24,...,8,3,4,1,2,3,40,34.8,10,Dirk Nowitzki
1,2008-11-16,30-150,DAL,AWAY,NYK,W (+10),1,44:10,13,27,...,15,4,1,1,0,1,39,34.7,13,Dirk Nowitzki