In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [3]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2014-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [4]:
season = 2000
appended_data_DET = []

# DET
while season <= 2021:
    df_DET = get_roster('DET', season)
    df_DET['Season'] = season
    df_DET['Team'] = 'DET'
    appended_data_DET.append(df_DET)
    season = season + 1
appended_data_DET = pd.concat(appended_data_DET)

In [5]:
DET_df_all = appended_data_DET.copy()
DET_df_all_csv = DET_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_players_all.csv', index=False)
DET_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_players_all.csv')
DET_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,20,Marcus Brown,SG,6-3,185,1974-04-03,US,1,Murray State,2000,DET
1,30,Jud Buechler,SF,6-6,220,1968-06-19,US,9,Arizona,2000,DET
2,22,John Crotty,PG,6-1,185,1969-07-15,US,7,Virginia,2000,DET
3,12,Michael Curry,SG,6-5,210,1968-08-22,US,5,Georgia Southern University,2000,DET
4,33,Grant Hill,SF,6-8,225,1972-10-05,US,5,Duke,2000,DET

In [6]:
DET_df_2000 = DET_df_all[DET_df_all['Season'] == 2000]
DET_df_2001 = DET_df_all[DET_df_all['Season'] == 2001]
DET_df_2002 = DET_df_all[DET_df_all['Season'] == 2002]
DET_df_2003 = DET_df_all[DET_df_all['Season'] == 2003]
DET_df_2004 = DET_df_all[DET_df_all['Season'] == 2004]
DET_df_2005 = DET_df_all[DET_df_all['Season'] == 2005]
DET_df_2006 = DET_df_all[DET_df_all['Season'] == 2006]
DET_df_2007 = DET_df_all[DET_df_all['Season'] == 2007]
DET_df_2008 = DET_df_all[DET_df_all['Season'] == 2008]
DET_df_2009 = DET_df_all[DET_df_all['Season'] == 2009]
DET_df_2010 = DET_df_all[DET_df_all['Season'] == 2010]
DET_df_2011 = DET_df_all[DET_df_all['Season'] == 2011]
DET_df_2012 = DET_df_all[DET_df_all['Season'] == 2012]
DET_df_2013 = DET_df_all[DET_df_all['Season'] == 2013]
DET_df_2014 = DET_df_all[DET_df_all['Season'] == 2014]
DET_df_2015 = DET_df_all[DET_df_all['Season'] == 2015]
DET_df_2016 = DET_df_all[DET_df_all['Season'] == 2016]
DET_df_2017 = DET_df_all[DET_df_all['Season'] == 2017]
DET_df_2018 = DET_df_all[DET_df_all['Season'] == 2018]
DET_df_2019 = DET_df_all[DET_df_all['Season'] == 2019]
DET_df_2020 = DET_df_all[DET_df_all['Season'] == 2020]
DET_df_2021 = DET_df_all[DET_df_all['Season'] == 2021]

In [7]:
# changing names
#DET_df_2003.loc[DET_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#DET_df_2004.loc[DET_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [8]:
DET_df_2000_players = DET_df_2000['PLAYER'].to_list()
DET_df_2001_players = DET_df_2001['PLAYER'].to_list()
DET_df_2002_players = DET_df_2002['PLAYER'].to_list()
DET_df_2003_players = DET_df_2003['PLAYER'].to_list()
DET_df_2004_players = DET_df_2004['PLAYER'].to_list()
DET_df_2005_players = DET_df_2005['PLAYER'].to_list()

DET_df_2006_players = DET_df_2006['PLAYER'].to_list()
DET_df_2007_players = DET_df_2007['PLAYER'].to_list()
DET_df_2008_players = DET_df_2008['PLAYER'].to_list()
DET_df_2009_players = DET_df_2009['PLAYER'].to_list()
DET_df_2010_players = DET_df_2010['PLAYER'].to_list()
DET_df_2011_players = DET_df_2011['PLAYER'].to_list()

DET_df_2012_players = DET_df_2012['PLAYER'].to_list()
DET_df_2013_players = DET_df_2013['PLAYER'].to_list()
DET_df_2014_players = DET_df_2014['PLAYER'].to_list()
DET_df_2015_players = DET_df_2015['PLAYER'].to_list()
DET_df_2016_players = DET_df_2016['PLAYER'].to_list()
DET_df_2017_players = DET_df_2017['PLAYER'].to_list()

DET_df_2018_players = DET_df_2018['PLAYER'].to_list()
DET_df_2019_players = DET_df_2019['PLAYER'].to_list()
DET_df_2020_players = DET_df_2020['PLAYER'].to_list()
DET_df_2021_players = DET_df_2021['PLAYER'].to_list()

## players to drop

In [47]:
# 2003 - Nene Hiulario
#DET_df_2015_players.remove("Luigi Datome")
#DET_df_2014_players.remove("Luigi Datome")
#DET_df_2019_players.remove("Glenn Robinson")
#DET_df_2021_players.remove("Dennis Smith")
DET_df_2012_players.remove("Walker Russell")

In [10]:

DET_2000_gamelog = []



for p in DET_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2000_gamelog.append(player_log)
DET_2000_gamelog = pd.concat(DET_2000_gamelog)    
DET_2000_gamelogs = DET_2000_gamelog.copy()
DET_2000_gamelogs['GAME_SCORE'] = DET_2000_gamelogs['GAME_SCORE'].astype(float)
DET_2000_games = DET_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2000_games_csv = DET_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2000_games.csv', index=False)
DET_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2000_games.csv')
DET_2000_games_proc.head()

You searched for "Marcus Brown"
11 results found.
0: Marcus Brown
1: Markel Brown
2: Marcus Banks
3: Harold Brown
4: Larry Brown
5: Moses Brown
6: Myron Brown
7: Marcus Camby
8: Marcus Fizer
9: Marcus Smart
10: Marcus Webb
Pick one: 0
Results for Marcus Brown:

You searched for "Jud Buechler"
1 result found.
Jud Buechler
Results for Jud Buechler:

You searched for "John Crotty"
8 results found.
0: John Crotty
1: John Brown
2: John Chaney
3: John Coker
4: John Roche
5: John Morton
6: John Stroud
7: Johan Petro
Pick one: 0
Results for John Crotty:

You searched for "Michael Curry"
7 results found.
0: Michael Curry
1: Michael Cage
2: Michael Wiley
3: Michael Cooper
4: Michael Porter
5: Michael Redd
6: Michael Young
Pick one: 0
Results for Michael Curry:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Lindsey Hunter"
2 results found.
0: Lindsey Hunter
1: Vince Hunter
Pick one: 0
Results for Lindsey Hunter:

You searched for "Jermaine Jackson"
2 results found.
0: Jermaine Jackson
1: Mervin Jackson
Pick one: 0
Results for Jermaine Jackson:

You searched for "Christian Laettner"
1 result found.
Christian Laettner
Results for Christian Laettner:

You searched for "Terry Mills"
12 results found.
0: Terry Mills
1: Terry Davis
2: Harry Giles
3: Jerry Kelly
4: Harry Miller
5: Larry Miller
6: Chris Mills
7: Patty Mills
8: Perry Moss
9: Jerry Rullo
10: Terry Tyler
11: Jerry Smith
Pick one: 0
Results for Terry Mills:

You searched for "Eric Montross"
1 result found.
Eric Montross
Results for Eric Montross:

You searched for "Mikki Moore"
2 results found.
0: Mikki Moore
1: Jackie Moore
Pick one: 0
Results for Mikki Moore:

You searched for "Don Reid"
33 results found.
0: Don Reid
1: Ron Reed
2: Don Dee
3: Don Ford
4: Don Ray
5: Davon Reed
6: Jim Reid
7: Naz Reid
8: Ryan Reid
9: Don Buse
10: Don Grate
11: John Greig
12: Don Kojis
13: Ron Lee
14: Don Martin
15: Don May
16: Don Ohl
17: Hub Reed
18: J.R. Reid
19: John Rudd
20: Don Smith
21: Don Smith
22: Don Boven
23: John Drew
24: Deng Gai
25: Ron Horn
26: Doug Lee
27: Don Otten
28: Ron Riley
29: Rob Rose
30: Bob Rule
31: Doug Moe
32: Ron Moore
Pick one: 0
Results for Don Reid:

You searched for "Jerry Stackhouse"
1 result found.
Jerry Stackhouse
Results for Jerry Stackhouse:

You searched for "Loy Vaught"
3 results found.
0: Loy Vaught
1: Bob Faught
2: Roy Pugh
Pick one: 0
Results for Loy Vaught:

You searched for "Jerome Williams"
16 results found.
0: Jerome Williams
1: Bernie Williams
2: Deron Williams
3: Aaron Williams
4: Eric Williams
5: Gene Williams
6: Herb Williams
7: Jason Williams
8: John Williams
9: Jordan Williams
10: Pete Williams
11: Reggie Williams
12: Reggie Williams
13: Rob Williams
14: Ron Williams
15: Troy Williams
Pick one: 0
Results for Jerome Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-01-05,27-092,DET,AWAY,ATL,W (+12),1,42:47,14,23,...,3,6,2,1,1,1,42,37.5,20,Grant Hill
1,2000-01-15,27-102,DET,AWAY,WAS,W (+5),1,38:34,15,20,...,6,5,1,1,1,2,39,35.0,4,Grant Hill
2,2000-01-03,27-090,DET,AWAY,ORL,W (+12),1,44:14,17,30,...,7,8,2,1,3,2,42,34.8,14,Grant Hill
3,2000-03-08,25-124,DET,HOME,DEN,W (+14),1,34:14,13,21,...,1,4,0,1,1,1,40,32.9,14,Jerry Stackhouse
4,2000-02-29,27-147,DET,AWAY,IND,L (-10),1,38:26,15,24,...,7,5,2,0,1,0,37,32.0,-12,Grant Hill

In [11]:

DET_2001_gamelog = []


for p in DET_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2001_gamelog.append(player_log)
DET_2001_gamelog = pd.concat(DET_2001_gamelog)    
DET_2001_gamelogs = DET_2001_gamelog.copy()
DET_2001_gamelogs['GAME_SCORE'] = DET_2001_gamelogs['GAME_SCORE'].astype(float)
DET_2001_games = DET_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2001_games_csv = DET_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2001_games.csv', index=False)
DET_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2001_games.csv')
DET_2001_games_proc.head()

You searched for "Chucky Atkins"
1 result found.
Chucky Atkins
Results for Chucky Atkins:

You searched for "Dana Barros"
3 results found.
0: Dana Barros
1: Earl Barron
2: Don Carlos
Pick one: 0
Results for Dana Barros:

You searched for "Jud Buechler"
1 result found.
Jud Buechler
Results for Jud Buechler:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Cedric Ceballos"
2 results found.
0: Cedric Ceballos
1: Cedric Ball
Pick one: 0
Results for Cedric Ceballos:

You searched for "Mateen Cleaves"
1 result found.
Mateen Cleaves
Results for Mateen Cleaves:

You searched for "Michael Curry"
7 results found.
0: Michael Curry
1: Michael Cage
2: Michael Wiley
3: Michael Cooper
4: Michael Porter
5: Michael Redd
6: Michael Young
Pick one: 0
Results for Michael Curry:

You searched for "Kornél Dávid"
1 result found.
Kornel David
Results for Kornel David:

You searched for "Eric Montross"
1 result found.
Eric Montross
Results for Eric Montross:

You searched for "Mikki Moore"
2 results found.
0: Mikki Moore
1: Jackie Moore
Pick one: 0
Results for Mikki Moore:

You searched for "Billy Owens"
9 results found.
0: Billy Owens
1: Billy Evans
2: Billy James
3: Bill Jones
4: Jim Owens
5: Larry Owens
6: Billy Reid
7: Bill Downey
8: Bill Henry
Pick one: 0
Results for Billy Owens:

You searched for "Joe Smith"
41 results found.
0: Joe Smith
1: Joe Smyth
2: Don Smith
3: Don Smith
4: Jim Smith
5: John Smith
6: Josh Smith
7: Jalen Smith
8: Al Smith
9: Deb Smith
10: Doug Smith
11: Ed Smith
12: Greg Smith
13: Greg Smith
14: Ish Smith
15: J.R. Smith
16: Jason Smith
17: Ken Smith
18: Leon Smith
19: Mike Smith
20: Pete Smith
21: Sam Smith
22: Sam Smith
23: Tony Smith
24: Tom Stith
25: Bill Smith
26: Bobby Smith
27: Derek Smith
28: Donta Smith
29: Elmore Smith
30: Jerry Smith
31: Nolan Smith
32: Otis Smith
33: Phil Smith
34: Robert Smith
35: Russ Smith
36: Steve Smith
37: Rik Smits
38: Sam Stith
39: Joe Ellis
40: Joe Fulks
Pick one: 0
Results for Joe Smith:

You searched for "Jerry Stackhouse"
1 result found.
Jerry Stackhouse
Results for Jerry Stackhouse:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "John Wallace"
11 results found.
0: John Wallace
1: John Wall
2: Ben Wallace
3: John Havlicek
4: John Holland
5: John Salley
6: John Vallely
7: Red Wallace
8: John Williams
9: John Bagley
10: John Warren
Pick one: 0
Results for John Wallace:

You searched for "Jerome Williams"
16 results found.
0: Jerome Williams
1: Bernie Williams
2: Deron Williams
3: Aaron Williams
4: Eric Williams
5: Gene Williams
6: Herb Williams
7: Jason Williams
8: John Williams
9: Jordan Williams
10: Pete Williams
11: Reggie Williams
12: Reggie Williams
13: Rob Williams
14: Ron Williams
15: Troy Williams
Pick one: 0
Results for Jerome Williams:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-04-03,26-149,DET,AWAY,CHI,W (+27),1,41:40,21,36,...,4,5,1,0,4,2,57,40.3,34,Jerry Stackhouse
1,2001-01-04,26-060,DET,AWAY,HOU,L (-10),1,45:09,15,27,...,0,2,3,0,4,1,46,32.7,-7,Jerry Stackhouse
2,2001-01-18,26-074,DET,AWAY,CHI,W (+6),1,45:04,9,25,...,6,11,1,0,2,2,36,31.0,6,Jerry Stackhouse
3,2001-01-14,26-070,DET,HOME,POR,L (-7),1,43:37,13,18,...,2,5,2,2,8,3,41,30.3,-8,Jerry Stackhouse
4,2001-02-25,26-112,DET,HOME,CLE,L (-7),1,40:34,9,22,...,3,6,3,1,3,1,35,28.6,-11,Jerry Stackhouse

In [12]:
DET_2002_gamelog = []


for p in DET_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2002_gamelog.append(player_log)
DET_2002_gamelog = pd.concat(DET_2002_gamelog)    
DET_2002_gamelogs = DET_2002_gamelog.copy()
DET_2002_gamelogs['GAME_SCORE'] = DET_2002_gamelogs['GAME_SCORE'].astype(float)
DET_2002_games = DET_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2002_games_csv = DET_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2002_games.csv', index=False)
DET_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2002_games.csv')
DET_2002_games_proc.head()

You searched for "Victor Alexander"
2 results found.
0: Victor Alexander
1: Cory Alexander
Pick one: 0
Results for Victor Alexander:

You searched for "Chucky Atkins"
1 result found.
Chucky Atkins
Results for Chucky Atkins:

You searched for "Dana Barros"
3 results found.
0: Dana Barros
1: Earl Barron
2: Don Carlos
Pick one: 0
Results for Dana Barros:

You searched for "Jon Barry"
30 results found.
0: Jon Barry
1: John Barr
2: Moe Barr
3: Ron Perry
4: John Bagley
5: Ron Baker
6: John Barber
7: Brent Barry
8: Drew Barry
9: Rick Barry
10: Jay Carty
11: Bob Ferry
12: John Garris
13: Joe Harris
14: Don May
15: Don Ray
16: Jason Terry
17: John Warren
18: Vin Baker
19: Tom Barker
20: Mike Barr
21: Cory Carr
22: Ron Carter
23: Ron Harper
24: Jason Hart
25: Josh Hart
26: Jon Leuer
27: Jack Parr
28: Von Wafer
29: John Wall
Pick one: 0
Results for Jon Barry:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Michael Curry"
7 results found.
0: Michael Curry
1: Michael Cage
2: Michael Wiley
3: Michael Cooper
4: Michael Porter
5: Michael Redd
6: Michael Young
Pick one: 0
Results for Michael Curry:

You searched for "Damon Jones"
24 results found.
0: Damon Jones
1: Mason Jones
2: Damian Jones
3: Damion James
4: Jalen Jones
5: James Jones
6: Major Jones
7: Sam Jones
8: Aaron James
9: Alvin Jones
10: DeQuan Jones
11: Dwayne Jones
12: Earl Jones
13: Jake Jones
14: Jimmy Jones
15: Kevin Jones
16: Larry Jones
17: Mark Jones
18: Mark Jones
19: Robin Jones
20: Solomon Jones
21: Wali Jones
22: Diamond Stone
23: Damone Brown
Pick one: 0
Results for Damon Jones:

You searched for "Mikki Moore"
2 results found.
0: Mikki Moore
1: Jackie Moore
Pick one: 0
Results for Mikki Moore:

You searched for "Željko Rebrača"
1 result found.
Zeljko Rebraca
Results for Zeljko Rebraca:

You searched for "Clifford Robinson"
2 results found.
0: Clifford Robinson
1: Cliff Robinson
Pick one: 0
Results for Clifford Robinson:

You searched for "Jerry Stackhouse"
1 result found.
Jerry Stackhouse
Results for Jerry Stackhouse:

You searched for "Ratko Varda"
1 result found.
Ratko Varda
Results for Ratko Varda:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Rodney White"
9 results found.
0: Rodney White
1: Randy White
2: Rory White
3: Royce White
4: Rudy White
5: Tony White
6: Rodney Hood
7: Andrew White
8: Coby White
Pick one: 0
Results for Rodney White:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-04-05,27-151,DET,AWAY,PHI,W (+4),1,39:05,8,19,...,4,7,1,0,1,1,34,29.6,13,Jerry Stackhouse
1,2002-01-23,27-079,DET,HOME,MIN,W (+21),1,40:20,17,28,...,1,3,2,1,3,1,40,28.5,14,Jerry Stackhouse
2,2002-03-24,27-139,DET,HOME,BOS,W (+8),1,36:22,9,19,...,8,8,2,0,2,1,30,27.9,20,Jerry Stackhouse
3,2002-01-15,27-071,DET,HOME,TOR,L (-2),1,43:33,13,25,...,6,3,2,0,3,3,38,27.4,-3,Jerry Stackhouse
4,2001-11-21,34-340,DET,AWAY,PHI,L (-5),1,44:41,10,21,...,5,4,2,0,3,3,35,26.0,-2,Clifford Robinson

In [13]:
DET_2003_gamelog = []



for p in DET_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2003_gamelog.append(player_log)
DET_2003_gamelog = pd.concat(DET_2003_gamelog)    
DET_2003_gamelogs = DET_2003_gamelog.copy()
DET_2003_gamelogs['GAME_SCORE'] = DET_2003_gamelogs['GAME_SCORE'].astype(float)
DET_2003_games = DET_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2003_games_csv = DET_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2003_games.csv', index=False)
DET_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2003_games.csv')
DET_2003_games_proc.head()

You searched for "Chucky Atkins"
1 result found.
Chucky Atkins
Results for Chucky Atkins:

You searched for "Jon Barry"
30 results found.
0: Jon Barry
1: John Barr
2: Moe Barr
3: Ron Perry
4: John Bagley
5: Ron Baker
6: John Barber
7: Brent Barry
8: Drew Barry
9: Rick Barry
10: Jay Carty
11: Bob Ferry
12: John Garris
13: Joe Harris
14: Don May
15: Don Ray
16: Jason Terry
17: John Warren
18: Vin Baker
19: Tom Barker
20: Mike Barr
21: Cory Carr
22: Ron Carter
23: Ron Harper
24: Jason Hart
25: Josh Hart
26: Jon Leuer
27: Jack Parr
28: Von Wafer
29: John Wall
Pick one: 0
Results for Jon Barry:

You searched for "Chauncey Billups"
1 result found.
Chauncey Billups
Results for Chauncey Billups:

You searched for "Michael Curry"
7 results found.
0: Michael Curry
1: Michael Cage
2: Michael Wiley
3: Michael Cooper
4: Michael Porter
5: Michael Redd
6: Michael Young
Pick one: 0
Results for Michael Curry:

You searched for "Hubert Davis"
5 results found.
0: Hubert Davis
1: Aubrey Davis
2: Ben Davis
3: Harry Davis
4: Tyler Davis
Pick one: 0
Results for Hubert Davis:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Danny Manning"
3 results found.
0: Danny Manning
1: Danny Ainge
2: Guy Manning
Pick one: 0
Results for Danny Manning:

You searched for "Mehmet Okur"
1 result found.
Mehmet Okur
Results for Mehmet Okur:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Željko Rebrača"
1 result found.
Zeljko Rebraca
Results for Zeljko Rebraca:

You searched for "Don Reid"
33 results found.
0: Don Reid
1: Ron Reed
2: Don Dee
3: Don Ford
4: Don Ray
5: Davon Reed
6: Jim Reid
7: Naz Reid
8: Ryan Reid
9: Don Buse
10: Don Grate
11: John Greig
12: Don Kojis
13: Ron Lee
14: Don Martin
15: Don May
16: Don Ohl
17: Hub Reed
18: J.R. Reid
19: John Rudd
20: Don Smith
21: Don Smith
22: Don Boven
23: John Drew
24: Deng Gai
25: Ron Horn
26: Doug Lee
27: Don Otten
28: Ron Riley
29: Rob Rose
30: Bob Rule
31: Doug Moe
32: Ron Moore
Pick one: 0
Results for Don Reid:

You searched for "Clifford Robinson"
2 results found.
0: Clifford Robinson
1: Cliff Robinson
Pick one: 0
Results for Clifford Robinson:

You searched for "Pepe Sánchez"
1 result found.
Pepe Sanchez
Results for Pepe Sanchez:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-03-12,26-168,DET,HOME,LAL,W (+23),1,42:43,12,20,...,3,6,2,0,0,1,33,29.7,16,Chauncey Billups
1,2003-03-09,26-165,DET,HOME,GSW,W (+2),1,43:40,11,15,...,2,8,1,0,1,4,31,29.1,1,Chauncey Billups
2,2002-12-11,24-300,DET,HOME,ATL,W (+11),1,36:26,14,26,...,5,4,2,1,0,1,32,26.8,17,Richard Hamilton
3,2003-02-17,25-003,DET,HOME,MIA,W (+31),1,27:37,14,22,...,4,3,0,0,1,3,34,26.5,25,Richard Hamilton
4,2002-11-18,24-277,DET,AWAY,NYK,L (-3),1,36:01,11,18,...,4,3,2,1,0,5,31,26.4,7,Richard Hamilton

In [14]:


DET_2004_gamelog = []



for p in DET_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2004_gamelog.append(player_log)
DET_2004_gamelog = pd.concat(DET_2004_gamelog)    
DET_2004_gamelogs = DET_2004_gamelog.copy()
DET_2004_gamelogs['GAME_SCORE'] = DET_2004_gamelogs['GAME_SCORE'].astype(float)
DET_2004_games = DET_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2004_games_csv = DET_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2004_games.csv', index=False)
DET_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2004_games.csv')
DET_2004_games_proc.head()

You searched for "Chucky Atkins"
1 result found.
Chucky Atkins
Results for Chucky Atkins:

You searched for "Chauncey Billups"
1 result found.
Chauncey Billups
Results for Chauncey Billups:

You searched for "Elden Campbell"
1 result found.
Elden Campbell
Results for Elden Campbell:

You searched for "Hubert Davis"
5 results found.
0: Hubert Davis
1: Aubrey Davis
2: Ben Davis
3: Harry Davis
4: Tyler Davis
Pick one: 0
Results for Hubert Davis:

You searched for "Tremaine Fowlkes"
1 result found.
Tremaine Fowlkes
Results for Tremaine Fowlkes:

You searched for "Darvin Ham"
1 result found.
Darvin Ham
Results for Darvin Ham:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Lindsey Hunter"
2 results found.
0: Lindsey Hunter
1: Vince Hunter
Pick one: 0
Results for Lindsey Hunter:

You searched for "Mike James"
33 results found.
0: Mike James
1: Mike James
2: Mike Davis
3: Mike Davis
4: Mike Farmer
5: Mike Gale
6: Gene James
7: Tim James
8: Mike Niles
9: Mike Barr
10: Mike Evans
11: Mike Green
12: Mike Hall
13: Mike Harper
14: Mike Harris
15: Mike Jackson
16: Billy James
17: Damion James
18: Jake Jones
19: Mike Kearns
20: Mike Lewis
21: Mike Maloy
22: Mike McGee
23: Mike Sanders
24: Mike Smrek
25: Mike Tobey
26: Mike Wilks
27: Mike Bantom
28: Mike Bloom
29: Mike Bratz
30: Mike Novak
31: Mike Pratt
32: Mike Price
Pick one: 0
Results for Mike James:

You searched for "Darko Miličić"
2 results found.
0: Darko Milicic
1: Marko Milic
Pick one: 0
Results for Darko Milicic:

You searched for "Mehmet Okur"
1 result found.
Mehmet Okur
Results for Mehmet Okur:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Željko Rebrača"
1 result found.
Zeljko Rebraca
Results for Zeljko Rebraca:

You searched for "Bob Sura"
26 results found.
0: Bob Sura
1: Bob Shea
2: Bob Ford
3: Rob Kurz
4: Bob Rule
5: Bob Sims
6: Bob Verga
7: Bob Burrow
8: Bob Cousy
9: Bob Doll
10: Bob Duffy
11: Bob Duffy
12: Bob Ferry
13: Bob Love
14: Bob Nash
15: Bob Quick
16: Bob Tough
17: Bob Wood
18: Bob Davis
19: Bob Evans
20: Bob Gross
21: Bob Naber
22: Don Ray
23: Rob Rose
24: Bob Royer
25: Bob Weiss
Pick one: 0
Results for Bob Sura:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Rasheed Wallace"
2 results found.
0: Rasheed Wallace
1: Red Wallace
Pick one: 0
Results for Rasheed Wallace:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-11-28,25-287,DET,HOME,CLE,W (+4),1,38:45,15,23,...,7,5,1,0,2,3,44,36.9,8,Richard Hamilton
1,2004-01-14,24-233,DET,HOME,TOR,W (+4),1,31:39,7,13,...,14,0,2,1,1,1,27,28.6,11,Mehmet Okur
2,2004-04-02,31-008,ATL,AWAY,ORL,W (+8),1,43:39,11,20,...,8,5,3,0,2,3,32,28.5,15,Bob Sura
3,2003-11-19,27-055,DET,AWAY,MEM,W (+7),1,39:04,11,21,...,7,5,3,0,2,3,33,28.1,8,Chauncey Billups
4,2004-02-29,27-157,DET,AWAY,LAC,W (+12),1,38:50,7,11,...,4,7,1,0,1,2,28,28.0,12,Chauncey Billups

In [15]:


DET_2005_gamelog = []

for p in DET_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2005_gamelog.append(player_log)
DET_2005_gamelog = pd.concat(DET_2005_gamelog)    
DET_2005_gamelogs = DET_2005_gamelog.copy()
DET_2005_gamelogs['GAME_SCORE'] = DET_2005_gamelogs['GAME_SCORE'].astype(float)
DET_2005_games = DET_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2005_games_csv = DET_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2005_games.csv', index=False)
DET_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2005_games.csv')
DET_2005_games_proc.head()

You searched for "Carlos Arroyo"
2 results found.
0: Carlos Arroyo
1: Carlos Terry
Pick one: 0
Results for Carlos Arroyo:

You searched for "Chauncey Billups"
1 result found.
Chauncey Billups
Results for Chauncey Billups:

You searched for "Elden Campbell"
1 result found.
Elden Campbell
Results for Elden Campbell:

You searched for "Derrick Coleman"
2 results found.
0: Derrick Coleman
1: Norris Coleman
Pick one: 0
Results for Derrick Coleman:

You searched for "Carlos Delfino"
1 result found.
Carlos Delfino
Results for Carlos Delfino:

You searched for "Ronald Dupree"
2 results found.
0: Ronald Dupree
1: Ronald Murray
Pick one: 0
Results for Ronald Dupree:

You searched for "Anthony Goldwire"
2 results found.
0: Anthony Goldwire
1: Anthony Bowie
Pick one: 0
Results for Anthony Goldwire:

You searched for "Darvin Ham"
1 result found.
Darvin Ham
Results for Darvin Ham:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Lindsey Hunter"
2 results found.
0: Lindsey Hunter
1: Vince Hunter
Pick one: 0
Results for Lindsey Hunter:

You searched for "Horace Jenkins"
1 result found.
Horace Jenkins
Results for Horace Jenkins:

You searched for "Antonio McDyess"
1 result found.
Antonio McDyess
Results for Antonio McDyess:

You searched for "Darko Miličić"
2 results found.
0: Darko Milicic
1: Marko Milic
Pick one: 0
Results for Darko Milicic:

You searched for "Smush Parker"
2 results found.
0: Smush Parker
1: Sonny Parker
Pick one: 0
Results for Smush Parker:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Rasheed Wallace"
2 results found.
0: Rasheed Wallace
1: Red Wallace
Pick one: 0
Results for Rasheed Wallace:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-03-14,30-178,DET,AWAY,ATL,W (+6),1,42:48,10,18,...,12,3,3,3,2,2,28,29.8,11,Rasheed Wallace
1,2004-12-27,26-317,DET,HOME,NJN,W (+10),1,45:07,12,19,...,4,3,3,0,4,2,37,29.6,19,Richard Hamilton
2,2005-03-16,28-172,DET,HOME,SEA,W (+7),1,37:00,7,12,...,2,4,0,0,0,1,32,29.4,22,Chauncey Billups
3,2004-12-22,28-088,DET,HOME,CHI,L (-7),1,38:45,9,16,...,3,7,1,0,2,4,32,28.0,4,Chauncey Billups
4,2004-12-29,28-095,DET,AWAY,WAS,W (+2),1,40:30,11,16,...,2,6,2,1,4,3,32,27.5,9,Chauncey Billups

In [16]:

DET_2006_gamelog = []

for p in DET_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2006_gamelog.append(player_log)
DET_2006_gamelog = pd.concat(DET_2006_gamelog)    
DET_2006_gamelogs = DET_2006_gamelog.copy()
DET_2006_gamelogs['GAME_SCORE'] = DET_2006_gamelogs['GAME_SCORE'].astype(float)
DET_2006_games = DET_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2006_games_csv = DET_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2006_games.csv', index=False)
DET_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2006_games.csv')
DET_2006_games_proc.head()

You searched for "Alex Acker"
8 results found.
0: Alex Acker
1: Alex Kirk
2: Alex Len
3: Alex Scales
4: Al Tucker
5: Alex Garcia
6: Alex Groza
7: Al Cervi
Pick one: 0
Results for Alex Acker:

You searched for "Carlos Arroyo"
2 results found.
0: Carlos Arroyo
1: Carlos Terry
Pick one: 0
Results for Carlos Arroyo:

You searched for "Chauncey Billups"
1 result found.
Chauncey Billups
Results for Chauncey Billups:

You searched for "Kelvin Cato"
4 results found.
0: Kelvin Cato
1: Calvin Natt
2: Kevin Knox
3: Kevin Love
Pick one: 0
Results for Kelvin Cato:

You searched for "Dale Davis"
29 results found.
0: Dale Davis
1: Walt Davis
2: Bill Davis
3: Glen Davis
4: Lee Davis
5: Mark Davis
6: Mark Davis
7: Mel Davis
8: Mike Davis
9: Mike Davis
10: Paul Davis
11: Ralph Davis
12: Tyler Davis
13: Walter Davis
14: Dale Ellis
15: Baron Davis
16: Ben Davis
17: Bob Davis
18: Brad Davis
19: Charles Davis
20: Charlie Davis
21: Ed Davis
22: Harry Davis
23: Jim Davis
24: Josh Davis
25: Red Davis
26: Ron Davis
27: Warren Davis
28: Willie Davis
Pick one: 0
Results for Dale Davis:

You searched for "Carlos Delfino"
1 result found.
Carlos Delfino
Results for Carlos Delfino:

You searched for "Tony Delk"
12 results found.
0: Tony Delk
1: Tony Snell
2: Tony Zeno
3: Tony Allen
4: Troy Bell
5: Don Dee
6: Tony Dumas
7: Tony Koski
8: Deng Adel
9: Sonny Dove
10: Tony Price
11: Tony White
Pick one: 0
Results for Tony Delk:

You searched for "Maurice Evans"
6 results found.
0: Maurice Evans
1: Mike Evans
2: Maurice King
3: Maurice Lucas
4: Maurice Ager
5: Maurice Baker
Pick one: 0
Results for Maurice Evans:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Lindsey Hunter"
2 results found.
0: Lindsey Hunter
1: Vince Hunter
Pick one: 0
Results for Lindsey Hunter:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Antonio McDyess"
1 result found.
Antonio McDyess
Results for Antonio McDyess:

You searched for "Darko Miličić"
2 results found.
0: Darko Milicic
1: Marko Milic
Pick one: 0
Results for Darko Milicic:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Rasheed Wallace"
2 results found.
0: Rasheed Wallace
1: Red Wallace
Pick one: 0
Results for Rasheed Wallace:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-01-03,29-100,DET,HOME,ORL,W (+9),1,43:10,9,15,...,2,9,2,0,1,3,37,36.0,14,Chauncey Billups
1,2006-03-28,29-184,DET,HOME,DAL,W (+7),1,37:16,8,14,...,4,11,3,0,1,2,31,35.3,21,Chauncey Billups
2,2005-12-14,29-080,DET,HOME,SAC,W (+11),1,40:45,10,15,...,3,19,1,0,4,2,28,31.9,24,Chauncey Billups
3,2006-01-25,27-345,DET,HOME,MIL,W (+4),1,43:20,15,23,...,3,4,4,0,2,5,35,29.4,7,Richard Hamilton
4,2005-11-02,27-261,DET,HOME,PHI,W (+20),1,38:19,16,24,...,6,3,1,0,3,3,37,28.1,17,Richard Hamilton

In [17]:

DET_2007_gamelog = []

for p in DET_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2007_gamelog.append(player_log)
DET_2007_gamelog = pd.concat(DET_2007_gamelog)    
DET_2007_gamelogs = DET_2007_gamelog.copy()
DET_2007_gamelogs['GAME_SCORE'] = DET_2007_gamelogs['GAME_SCORE'].astype(float)
DET_2007_games = DET_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2007_games_csv = DET_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2007_games.csv', index=False)
DET_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2007_games.csv')
DET_2007_games_proc.head()

You searched for "Chauncey Billups"
1 result found.
Chauncey Billups
Results for Chauncey Billups:

You searched for "Will Blalock"
1 result found.
Will Blalock
Results for Will Blalock:

You searched for "Dale Davis"
29 results found.
0: Dale Davis
1: Walt Davis
2: Bill Davis
3: Glen Davis
4: Lee Davis
5: Mark Davis
6: Mark Davis
7: Mel Davis
8: Mike Davis
9: Mike Davis
10: Paul Davis
11: Ralph Davis
12: Tyler Davis
13: Walter Davis
14: Dale Ellis
15: Baron Davis
16: Ben Davis
17: Bob Davis
18: Brad Davis
19: Charles Davis
20: Charlie Davis
21: Ed Davis
22: Harry Davis
23: Jim Davis
24: Josh Davis
25: Red Davis
26: Ron Davis
27: Warren Davis
28: Willie Davis
Pick one: 0
Results for Dale Davis:

You searched for "Carlos Delfino"
1 result found.
Carlos Delfino
Results for Carlos Delfino:

You searched for "Ronald Dupree"
2 results found.
0: Ronald Dupree
1: Ronald Murray
Pick one: 0
Results for Ronald Dupree:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Lindsey Hunter"
2 results found.
0: Lindsey Hunter
1: Vince Hunter
Pick one: 0
Results for Lindsey Hunter:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Antonio McDyess"
1 result found.
Antonio McDyess
Results for Antonio McDyess:

You searched for "Nazr Mohammed"
1 result found.
Nazr Mohammed
Results for Nazr Mohammed:

You searched for "Ronald Murray"
4 results found.
0: Ronald Murray
1: Ronald Dupree
2: Jamal Murray
3: Ronald Franz
Pick one: 0
Results for Ronald Murray:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Rasheed Wallace"
2 results found.
0: Rasheed Wallace
1: Red Wallace
Pick one: 0
Results for Rasheed Wallace:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-11-25,30-061,DET,AWAY,WAS,W (+4),1,36:49,4,7,...,5,7,2,0,1,2,29,32.3,-6,Chauncey Billups
1,2006-12-27,28-316,DET,AWAY,NYK,L (-6),1,54:58,19,37,...,2,2,0,0,1,4,51,32.1,2,Richard Hamilton
2,2007-03-30,30-186,DET,HOME,NJN,W (+5),1,40:14,7,17,...,3,14,0,0,0,5,32,31.6,10,Chauncey Billups
3,2006-12-16,30-082,DET,AWAY,NJN,W (+8),1,36:12,11,15,...,2,11,5,0,1,2,27,31.2,-1,Chauncey Billups
4,2007-01-09,26-315,DET,AWAY,PHI,W (+9),1,42:23,13,18,...,5,4,1,1,2,1,33,29.6,14,Tayshaun Prince

In [18]:

DET_2008_gamelog = []

for p in DET_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2008_gamelog.append(player_log)
DET_2008_gamelog = pd.concat(DET_2008_gamelog)    
DET_2008_gamelogs = DET_2008_gamelog.copy()
DET_2008_gamelogs['GAME_SCORE'] = DET_2008_gamelogs['GAME_SCORE'].astype(float)
DET_2008_games = DET_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2008_games_csv = DET_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2008_games.csv', index=False)
DET_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2008_games.csv')
DET_2008_games_proc.head()

You searched for "Arron Afflalo"
1 result found.
Arron Afflalo
Results for Arron Afflalo:

You searched for "Chauncey Billups"
1 result found.
Chauncey Billups
Results for Chauncey Billups:

You searched for "Primož Brezec"
1 result found.
Primoz Brezec
Results for Primoz Brezec:

You searched for "Juan Dixon"
1 result found.
Juan Dixon
Results for Juan Dixon:

You searched for "Ronald Dupree"
2 results found.
0: Ronald Dupree
1: Ronald Murray
Pick one: 0
Results for Ronald Dupree:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Jarvis Hayes"
4 results found.
0: Jarvis Hayes
1: Elvin Hayes
2: Jaxson Hayes
3: Jim Hayes
Pick one: 0
Results for Jarvis Hayes:

You searched for "Walter Herrmann"
1 result found.
Walter Herrmann
Results for Walter Herrmann:

You searched for "Lindsey Hunter"
2 results found.
0: Lindsey Hunter
1: Vince Hunter
Pick one: 0
Results for Lindsey Hunter:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Antonio McDyess"
1 result found.
Antonio McDyess
Results for Antonio McDyess:

You searched for "Nazr Mohammed"
1 result found.
Nazr Mohammed
Results for Nazr Mohammed:

You searched for "Ronald Murray"
4 results found.
0: Ronald Murray
1: Ronald Dupree
2: Jamal Murray
3: Ronald Franz
Pick one: 0
Results for Ronald Murray:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Theo Ratliff"
3 results found.
0: Theo Ratliff
1: Ed Ratleff
2: Mike Ratliff
Pick one: 0
Results for Theo Ratliff:

You searched for "Cheikh Samb"
1 result found.
Cheikh Samb
Results for Cheikh Samb:

You searched for "Rodney Stuckey"
1 result found.
Rodney Stuckey
Results for Rodney Stuckey:

You searched for "Rasheed Wallace"
2 results found.
0: Rasheed Wallace
1: Red Wallace
Pick one: 0
Results for Rasheed Wallace:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-01-15,29-335,DET,HOME,TOR,W (+14),1,38:22,16,22,...,4,6,0,0,0,1,39,34.6,23,Richard Hamilton
1,2007-11-21,31-057,DET,HOME,NYK,W (+12),1,34:51,7,13,...,4,15,3,1,0,1,25,33.7,36,Chauncey Billups
2,2007-12-11,31-077,DET,AWAY,MEM,W (+10),1,38:38,7,15,...,5,14,3,0,1,2,28,33.2,19,Chauncey Billups
3,2008-01-18,31-115,DET,HOME,SAC,L (-7),1,40:23,7,14,...,8,10,2,0,0,2,28,32.0,4,Chauncey Billups
4,2008-03-09,31-166,DET,HOME,CHI,W (+7),1,34:46,9,12,...,2,4,0,0,2,2,34,29.4,8,Chauncey Billups

In [19]:

DET_2009_gamelog = []

for p in DET_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2009_gamelog.append(player_log)
DET_2009_gamelog = pd.concat(DET_2009_gamelog)    
DET_2009_gamelogs = DET_2009_gamelog.copy()
DET_2009_gamelogs['GAME_SCORE'] = DET_2009_gamelogs['GAME_SCORE'].astype(float)
DET_2009_games = DET_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2009_games_csv = DET_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2009_games.csv', index=False)
DET_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2009_games.csv')
DET_2009_games_proc.head()

You searched for "Alex Acker"
8 results found.
0: Alex Acker
1: Alex Kirk
2: Alex Len
3: Alex Scales
4: Al Tucker
5: Alex Garcia
6: Alex Groza
7: Al Cervi
Pick one: 0
Results for Alex Acker:

You searched for "Arron Afflalo"
1 result found.
Arron Afflalo
Results for Arron Afflalo:

You searched for "Chauncey Billups"
1 result found.
Chauncey Billups
Results for Chauncey Billups:

You searched for "Kwame Brown"
9 results found.
0: Kwame Brown
1: Andre Brown
2: Bruce Brown
3: Damone Brown
4: Dee Brown
5: Dee Brown
6: Mike Brown
7: Stan Brown
8: Jim Browne
Pick one: 0
Results for Kwame Brown:

You searched for "Will Bynum"
3 results found.
0: Will Bynum
1: Will Barton
2: Bill Ebben
Pick one: 0
Results for Will Bynum:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Walter Herrmann"
1 result found.
Walter Herrmann
Results for Walter Herrmann:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Antonio McDyess"
1 result found.
Antonio McDyess
Results for Antonio McDyess:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Walter Sharpe"
1 result found.
Walter Sharpe
Results for Walter Sharpe:

You searched for "Rodney Stuckey"
1 result found.
Rodney Stuckey
Results for Rodney Stuckey:

You searched for "Rasheed Wallace"
2 results found.
0: Rasheed Wallace
1: Red Wallace
Pick one: 0
Results for Rasheed Wallace:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-12-23,22-246,DET,HOME,CHI,W (+6),1,41:57,15,24,...,2,4,4,0,3,2,40,32.4,10,Rodney Stuckey
1,2008-12-19,33-195,DET,HOME,UTA,L (-6),1,53:46,13,24,...,5,7,3,0,6,1,38,29.8,-10,Allen Iverson
2,2008-11-05,28-251,DET,AWAY,TOR,W (+7),1,38:41,10,13,...,9,3,1,2,0,0,27,29.1,10,Tayshaun Prince
3,2008-12-02,32-068,DEN,HOME,TOR,W (+39),1,31:53,8,12,...,1,14,1,0,1,0,24,28.9,48,Chauncey Billups
4,2008-11-11,33-157,DET,AWAY,SAC,W (+8),1,45:38,9,19,...,7,9,2,0,3,1,30,27.3,7,Allen Iverson

In [20]:

DET_2010_gamelog = []

for p in DET_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2010_gamelog.append(player_log)
DET_2010_gamelog = pd.concat(DET_2010_gamelog)    
DET_2010_gamelogs = DET_2010_gamelog.copy()
DET_2010_gamelogs['GAME_SCORE'] = DET_2010_gamelogs['GAME_SCORE'].astype(float)
DET_2010_games = DET_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2010_games_csv = DET_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2010_games.csv', index=False)
DET_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2010_games.csv')
DET_2010_games_proc.head()

You searched for "Chucky Atkins"
1 result found.
Chucky Atkins
Results for Chucky Atkins:

You searched for "Kwame Brown"
9 results found.
0: Kwame Brown
1: Andre Brown
2: Bruce Brown
3: Damone Brown
4: Dee Brown
5: Dee Brown
6: Mike Brown
7: Stan Brown
8: Jim Browne
Pick one: 0
Results for Kwame Brown:

You searched for "Will Bynum"
3 results found.
0: Will Bynum
1: Will Barton
2: Bill Ebben
Pick one: 0
Results for Will Bynum:

You searched for "Austin Daye"
4 results found.
0: Austin Daye
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Austin Daye:

You searched for "Ben Gordon"
9 results found.
0: Ben Gordon
1: Drew Gordon
2: Aaron Gordon
3: Eric Gordon
4: Paul Gordon
5: Ken Green
6: Ed Horton
7: Ken Norman
8: Ben Moore
Pick one: 0
Results for Ben Gordon:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Jonas Jerebko"
1 result found.
Jonas Jerebko
Results for Jonas Jerebko:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Rodney Stuckey"
1 result found.
Rodney Stuckey
Results for Rodney Stuckey:

You searched for "DaJuan Summers"
1 result found.
DaJuan Summers
Results for DaJuan Summers:

You searched for "Charlie Villanueva"
1 result found.
Charlie Villanueva
Results for Charlie Villanueva:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Chris Wilcox"
8 results found.
0: Chris Wilcox
1: Chris Mills
2: Chris Silva
3: Chris Welp
4: C.J. Wilcox
5: Chris Childs
6: Chris Wright
7: Chris Wright
Pick one: 0
Results for Chris Wilcox:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-04-09,27-005,DET,AWAY,MIA,W (+7),1,36:37,12,21,...,0,3,2,0,1,2,39,31.4,11,Ben Gordon
1,2010-03-26,30-026,DET,AWAY,NJN,L (-8),1,37:34,13,18,...,8,7,2,1,0,3,27,29.6,-3,Tayshaun Prince
2,2010-02-17,32-003,DET,AWAY,ORL,L (-25),1,36:25,12,18,...,5,3,0,0,2,4,36,29.4,-15,Richard Hamilton
3,2010-04-09,30-040,DET,AWAY,MIA,W (+7),1,42:43,12,19,...,6,7,0,0,1,0,28,26.0,15,Tayshaun Prince
4,2009-11-11,25-079,DET,HOME,CHA,W (+23),1,31:18,13,17,...,4,0,2,1,1,2,30,25.4,28,Charlie Villanueva

In [21]:

DET_2011_gamelog = []

for p in DET_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2011_gamelog.append(player_log)
DET_2011_gamelog = pd.concat(DET_2011_gamelog)    
DET_2011_gamelogs = DET_2011_gamelog.copy()
DET_2011_gamelogs['GAME_SCORE'] = DET_2011_gamelogs['GAME_SCORE'].astype(float)
DET_2011_games = DET_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2011_games_csv = DET_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2011_games.csv', index=False)
DET_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2011_games.csv')
DET_2011_games_proc.head()

You searched for "Will Bynum"
3 results found.
0: Will Bynum
1: Will Barton
2: Bill Ebben
Pick one: 0
Results for Will Bynum:

You searched for "Austin Daye"
4 results found.
0: Austin Daye
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Austin Daye:

You searched for "Ben Gordon"
9 results found.
0: Ben Gordon
1: Drew Gordon
2: Aaron Gordon
3: Eric Gordon
4: Paul Gordon
5: Ken Green
6: Ed Horton
7: Ken Norman
8: Ben Moore
Pick one: 0
Results for Ben Gordon:

You searched for "Richard Hamilton"
2 results found.
0: Richard Hamilton
1: Richard Morton
Pick one: 0
Results for Richard Hamilton:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Greg Monroe"
7 results found.
0: Greg Monroe
1: Greg Minor
2: Earl Monroe
3: Greg Foster
4: Greg Howard
5: Greg Oden
6: Greg Sutton
Pick one: 0
Results for Greg Monroe:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Rodney Stuckey"
1 result found.
Rodney Stuckey
Results for Rodney Stuckey:

You searched for "DaJuan Summers"
1 result found.
DaJuan Summers
Results for DaJuan Summers:

You searched for "Charlie Villanueva"
1 result found.
Charlie Villanueva
Results for Charlie Villanueva:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Chris Wilcox"
8 results found.
0: Chris Wilcox
1: Chris Mills
2: Chris Silva
3: Chris Welp
4: C.J. Wilcox
5: Chris Childs
6: Chris Wright
7: Chris Wright
Pick one: 0
Results for Chris Wilcox:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-12-19,30-294,DET,HOME,NOH,W (+3),1,46:51,12,16,...,12,8,1,3,2,4,28,30.3,8,Tayshaun Prince
1,2011-04-11,24-355,DET,HOME,CLE,L (-9),1,44:52,8,14,...,2,14,0,0,2,2,29,30.0,3,Rodney Stuckey
2,2010-11-28,30-273,DET,HOME,NYK,L (-9),1,43:23,13,22,...,8,7,0,0,0,1,31,28.5,-9,Tayshaun Prince
3,2010-12-11,36-092,DET,HOME,TOR,L (-4),1,39:04,10,13,...,14,4,5,0,4,3,23,27.5,-6,Ben Wallace
4,2011-04-06,33-051,DET,HOME,NJN,W (+7),1,34:50,8,11,...,5,9,2,0,2,3,25,27.1,7,Richard Hamilton

In [48]:
# removed nene hilario
DET_2012_gamelog = []

for p in DET_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2012_gamelog.append(player_log)
DET_2012_gamelog = pd.concat(DET_2012_gamelog)    
DET_2012_gamelogs = DET_2012_gamelog.copy()
DET_2012_gamelogs['GAME_SCORE'] = DET_2012_gamelogs['GAME_SCORE'].astype(float)
DET_2012_games = DET_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2012_games_csv = DET_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2012_games.csv', index=False)
DET_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2012_games.csv')
DET_2012_games_proc.head()

You searched for "Will Bynum"
3 results found.
0: Will Bynum
1: Will Barton
2: Bill Ebben
Pick one: 0
Results for Will Bynum:

You searched for "Austin Daye"
4 results found.
0: Austin Daye
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Austin Daye:

You searched for "Ben Gordon"
9 results found.
0: Ben Gordon
1: Drew Gordon
2: Aaron Gordon
3: Eric Gordon
4: Paul Gordon
5: Ken Green
6: Ed Horton
7: Ken Norman
8: Ben Moore
Pick one: 0
Results for Ben Gordon:

You searched for "Jonas Jerebko"
1 result found.
Jonas Jerebko
Results for Jonas Jerebko:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "Vernon Macklin"
2 results found.
0: Vernon Macklin
1: Vernon Maxwell
Pick one: 0
Results for Vernon Macklin:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Greg Monroe"
7 results found.
0: Greg Monroe
1: Greg Minor
2: Earl Monroe
3: Greg Foster
4: Greg Howard
5: Greg Oden
6: Greg Sutton
Pick one: 0
Results for Greg Monroe:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Rodney Stuckey"
1 result found.
Rodney Stuckey
Results for Rodney Stuckey:

You searched for "Charlie Villanueva"
1 result found.
Charlie Villanueva
Results for Charlie Villanueva:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Damien Wilkins"
1 result found.
Damien Wilkins
Results for Damien Wilkins:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-03-21,28-352,DET,AWAY,DEN,L (-1),1,41:20,13,22,...,0,8,2,0,2,5,45,38.0,10,Ben Gordon
1,2012-01-12,21-222,DET,AWAY,MIL,L (-9),1,39:42,12,16,...,16,2,2,1,2,4,32,32.5,-9,Greg Monroe
2,2012-03-14,25-328,DET,AWAY,SAC,W (+12),1,41:47,10,18,...,5,6,0,0,1,0,35,31.1,23,Rodney Stuckey
3,2012-02-17,25-302,DET,HOME,SAC,W (+6),1,39:31,12,20,...,3,0,1,1,1,1,36,28.0,11,Rodney Stuckey
4,2012-03-14,21-284,DET,AWAY,SAC,W (+12),1,35:05,15,20,...,11,3,0,0,2,4,32,27.8,15,Greg Monroe

In [22]:
DET_2013_gamelog = []

for p in DET_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2013_gamelog.append(player_log)
DET_2013_gamelog = pd.concat(DET_2013_gamelog)    
DET_2013_gamelogs = DET_2013_gamelog.copy()
DET_2013_gamelogs['GAME_SCORE'] = DET_2013_gamelogs['GAME_SCORE'].astype(float)
DET_2013_games = DET_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2013_games_csv = DET_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2013_games.csv', index=False)
DET_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2013_games.csv')
DET_2013_games_proc.head()

You searched for "Will Bynum"
3 results found.
0: Will Bynum
1: Will Barton
2: Bill Ebben
Pick one: 0
Results for Will Bynum:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Austin Daye"
4 results found.
0: Austin Daye
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Austin Daye:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Kim English"
3 results found.
0: Kim English
1: A.J. English
2: Alex English
Pick one: 0
Results for Kim English:

You searched for "Jonas Jerebko"
1 result found.
Jonas Jerebko
Results for Jonas Jerebko:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "Viacheslav Kravtsov"
1 result found.
Viacheslav Kravtsov
Results for Viacheslav Kravtsov:

You searched for "Corey Maggette"
1 result found.
Corey Maggette
Results for Corey Maggette:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Khris Middleton"
2 results found.
0: Khris Middleton
1: Chris Singleton
Pick one: 0
Results for Khris Middleton:

You searched for "Greg Monroe"
7 results found.
0: Greg Monroe
1: Greg Minor
2: Earl Monroe
3: Greg Foster
4: Greg Howard
5: Greg Oden
6: Greg Sutton
Pick one: 0
Results for Greg Monroe:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Kyle Singler"
2 results found.
0: Kyle Singler
1: Kyle Wiltjer
Pick one: 0
Results for Kyle Singler:

You searched for "Rodney Stuckey"
1 result found.
Rodney Stuckey
Results for Rodney Stuckey:

You searched for "Charlie Villanueva"
1 result found.
Charlie Villanueva
Results for Charlie Villanueva:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-12-01,20-113,DET,HOME,PHI,W (+15),1,32:59,12,15,...,19,0,6,2,1,2,31,34.6,25,Andre Drummond
1,2012-12-19,22-198,DET,AWAY,TOR,L (-6),1,34:36,14,22,...,10,2,2,0,1,2,35,31.8,5,Greg Monroe
2,2013-12-31,22-029,MIL,AWAY,LAL,W (+15),1,38:48,15,25,...,8,2,4,0,2,1,37,30.9,17,Brandon Knight
3,2013-04-15,22-315,DET,HOME,PHI,W (+8),1,36:49,10,14,...,16,4,0,1,2,1,27,29.5,17,Greg Monroe
4,2014-04-11,20-244,DET,AWAY,CHI,L (-8),1,41:51,11,17,...,26,0,3,1,2,4,26,29.2,1,Andre Drummond

In [29]:
DET_2014_gamelog = []

for p in DET_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2014_gamelog.append(player_log)
DET_2014_gamelog = pd.concat(DET_2014_gamelog)    
DET_2014_gamelogs = DET_2014_gamelog.copy()
DET_2014_gamelogs['GAME_SCORE'] = DET_2014_gamelogs['GAME_SCORE'].astype(float)
DET_2014_games = DET_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2014_games_csv = DET_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2014_games.csv', index=False)
DET_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2014_games.csv')
DET_2014_games_proc.head()

You searched for "Chauncey Billups"
1 result found.
Chauncey Billups
Results for Chauncey Billups:

You searched for "Will Bynum"
3 results found.
0: Will Bynum
1: Will Barton
2: Bill Ebben
Pick one: 0
Results for Will Bynum:

You searched for "Kentavious Caldwell-Pope"
1 result found.
Kentavious Caldwell-Pope
Results for Kentavious Caldwell-Pope:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Josh Harrellson"
1 result found.
Josh Harrellson
Results for Josh Harrellson:

You searched for "Brandon Jennings"
1 result found.
Brandon Jennings
Results for Brandon Jennings:

You searched for "Jonas Jerebko"
1 result found.
Jonas Jerebko
Results for Jonas Jerebko:

You searched for "Tony Mitchell"
5 results found.
0: Tony Mitchell
1: Tony Mitchell
2: Todd Mitchell
3: Mike Mitchell
4: Sam Mitchell
Pick one: 0
Results for Tony Mitchell:

You searched for "Greg Monroe"
7 results found.
0: Greg Monroe
1: Greg Minor
2: Earl Monroe
3: Greg Foster
4: Greg Howard
5: Greg Oden
6: Greg Sutton
Pick one: 0
Results for Greg Monroe:

You searched for "Kyle Singler"
2 results found.
0: Kyle Singler
1: Kyle Wiltjer
Pick one: 0
Results for Kyle Singler:

You searched for "Peyton Siva"
1 result found.
Peyton Siva
Results for Peyton Siva:

You searched for "Josh Smith"
39 results found.
0: Josh Smith
1: Ish Smith
2: Joe Smith
3: John Smith
4: Don Smith
5: Don Smith
6: Doug Smith
7: J.R. Smith
8: Jason Smith
9: Jim Smith
10: Russ Smith
11: Tony Smith
12: Joe Smyth
13: Jalen Smith
14: Josh Hart
15: Josh Selby
16: Al Smith
17: Bill Smith
18: Bobby Smith
19: Deb Smith
20: Donta Smith
21: Ed Smith
22: Greg Smith
23: Greg Smith
24: Jerry Smith
25: Keith Smith
26: Ken Smith
27: Leon Smith
28: Mike Smith
29: Nolan Smith
30: Otis Smith
31: Pete Smith
32: Phil Smith
33: Sam Smith
34: Sam Smith
35: Tom Stith
36: Josh Hall
37: Josh Davis
38: Josh Grant
Pick one: 0
Results for Josh Smith:

You searched for "Rodney Stuckey"
1 result found.
Rodney Stuckey
Results for Rodney Stuckey:

You searched for "Charlie Villanueva"
1 result found.
Charlie Villanueva
Results for Charlie Villanueva:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-12-01,20-113,DET,HOME,PHI,W (+15),1,32:59,12,15,...,19,0,6,2,1,2,31,34.6,25,Andre Drummond
1,2014-02-08,24-138,DET,HOME,DEN,W (+17),1,40:17,11,22,...,1,12,2,0,2,1,35,32.3,29,Brandon Jennings
2,2014-04-11,20-244,DET,AWAY,CHI,L (-8),1,41:51,11,17,...,26,0,3,1,2,4,26,29.2,1,Andre Drummond
3,2013-12-15,28-010,DET,HOME,POR,L (-2),1,45:33,13,17,...,7,4,1,1,1,4,31,28.7,0,Josh Smith
4,2014-03-03,20-205,DET,HOME,NYK,W (+11),1,46:14,6,9,...,26,0,2,3,0,2,17,26.2,13,Andre Drummond

In [25]:
# remove luigi datome
DET_2015_gamelog = []

for p in DET_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2015_gamelog.append(player_log)
DET_2015_gamelog = pd.concat(DET_2015_gamelog)    
DET_2015_gamelogs = DET_2015_gamelog.copy()
DET_2015_gamelogs['GAME_SCORE'] = DET_2015_gamelogs['GAME_SCORE'].astype(float)
DET_2015_games = DET_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2015_games_csv = DET_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2015_games.csv', index=False)
DET_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2015_games.csv')
DET_2015_games_proc.head()

You searched for "Joel Anthony"
3 results found.
0: Joel Anthony
1: Cole Anthony
2: Greg Anthony
Pick one: 0
Results for Joel Anthony:

You searched for "D.J. Augustin"
1 result found.
D.J. Augustin
Results for D.J. Augustin:

You searched for "Caron Butler"
4 results found.
0: Caron Butler
1: Al Butler
2: Greg Butler
3: Carl Fuller
Pick one: 0
Results for Caron Butler:

You searched for "Kentavious Caldwell-Pope"
1 result found.
Kentavious Caldwell-Pope
Results for Kentavious Caldwell-Pope:

You searched for "Spencer Dinwiddie"
1 result found.
Spencer Dinwiddie
Results for Spencer Dinwiddie:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Reggie Jackson"
6 results found.
0: Reggie Jackson
1: Reggie Hanson
2: Reggie Johnson
3: Cedric Jackson
4: Greg Jackson
5: Mervin Jackson
Pick one: 0
Results for Reggie Jackson:

You searched for "Brandon Jennings"
1 result found.
Brandon Jennings
Results for Brandon Jennings:

You searched for "Jonas Jerebko"
1 result found.
Jonas Jerebko
Results for Jonas Jerebko:

You searched for "John Lucas III"
2 results found.
0: John Lucas III
1: John Lucas
Pick one: 0
Results for John Lucas III:

You searched for "Cartier Martin"
5 results found.
0: Cartier Martin
1: Caleb Martin
2: Darrick Martin
3: LaRue Martin
4: Slater Martin
Pick one: 0
Results for Cartier Martin:

You searched for "Jodie Meeks"
1 result found.
Jodie Meeks
Results for Jodie Meeks:

You searched for "Quincy Miller"
3 results found.
0: Quincy Miller
1: Dick Miller
2: Quincy Lewis
Pick one: 0
Results for Quincy Miller:

You searched for "Greg Monroe"
7 results found.
0: Greg Monroe
1: Greg Minor
2: Earl Monroe
3: Greg Foster
4: Greg Howard
5: Greg Oden
6: Greg Sutton
Pick one: 0
Results for Greg Monroe:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Kyle Singler"
2 results found.
0: Kyle Singler
1: Kyle Wiltjer
Pick one: 0
Results for Kyle Singler:

You searched for "Josh Smith"
39 results found.
0: Josh Smith
1: Ish Smith
2: Joe Smith
3: John Smith
4: Don Smith
5: Don Smith
6: Doug Smith
7: J.R. Smith
8: Jason Smith
9: Jim Smith
10: Russ Smith
11: Tony Smith
12: Joe Smyth
13: Jalen Smith
14: Josh Hart
15: Josh Selby
16: Al Smith
17: Bill Smith
18: Bobby Smith
19: Deb Smith
20: Donta Smith
21: Ed Smith
22: Greg Smith
23: Greg Smith
24: Jerry Smith
25: Keith Smith
26: Ken Smith
27: Leon Smith
28: Mike Smith
29: Nolan Smith
30: Otis Smith
31: Pete Smith
32: Phil Smith
33: Sam Smith
34: Sam Smith
35: Tom Stith
36: Josh Hall
37: Josh Davis
38: Josh Grant
Pick one: 0
Results for Josh Smith:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

You searched for "Shawne Williams"
14 results found.
0: Shawne Williams
1: Hank Williams
2: Sean Williams
3: Alan Williams
4: Charles Williams
5: Frank Williams
6: Gene Williams
7: Grant Williams
8: Jawad Williams
9: Nate Williams
10: Sam Williams
11: Sam Williams
12: Shammond Williams
13: Shelden Williams
Pick one: 0
Results for Shawne Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-03-29,21-231,DET,AWAY,MIA,L (-7),1,39:02,14,17,...,14,2,1,2,0,3,32,33.3,1,Andre Drummond
1,2015-01-25,27-076,DET,AWAY,TOR,L (-4),1,37:21,12,20,...,4,8,0,0,2,1,35,30.2,-3,D.J. Augustin
2,2015-01-04,25-103,DET,HOME,SAC,W (+19),1,30:33,14,21,...,2,7,2,0,2,3,35,30.2,12,Brandon Jennings
3,2015-01-12,25-111,DET,AWAY,TOR,W (+3),1,33:38,11,22,...,2,10,2,0,2,1,34,29.8,9,Brandon Jennings
4,2015-02-03,27-085,DET,HOME,MIA,W (+17),1,35:18,8,14,...,4,13,1,0,0,0,25,29.7,37,D.J. Augustin

In [26]:

DET_2016_gamelog = []

for p in DET_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2016_gamelog.append(player_log)
DET_2016_gamelog = pd.concat(DET_2016_gamelog)    
DET_2016_gamelogs = DET_2016_gamelog.copy()
DET_2016_gamelogs['GAME_SCORE'] = DET_2016_gamelogs['GAME_SCORE'].astype(float)
DET_2016_games = DET_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2016_games_csv = DET_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2016_games.csv', index=False)
DET_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2016_games.csv')
DET_2016_games_proc.head()

You searched for "Joel Anthony"
3 results found.
0: Joel Anthony
1: Cole Anthony
2: Greg Anthony
Pick one: 0
Results for Joel Anthony:

You searched for "Aron Baynes"
8 results found.
0: Aron Baynes
1: Ron Baker
2: Harry Barnes
3: Marvin Barnes
4: Ron Boone
5: Aaron James
6: Tharon Mayes
7: Cameron Payne
Pick one: 0
Results for Aron Baynes:

You searched for "Steve Blake"
11 results found.
0: Steve Blake
1: Steve Bracey
2: Steve Bardo
3: Steve Burtt
4: Steve Hamer
5: Steve Hawes
6: Steve Hayes
7: Steve Nash
8: Steve Novak
9: Steve Kerr
10: Steven Hill
Pick one: 0
Results for Steve Blake:

You searched for "Reggie Bullock"
1 result found.
Reggie Bullock
Results for Reggie Bullock:

You searched for "Kentavious Caldwell-Pope"
1 result found.
Kentavious Caldwell-Pope
Results for Kentavious Caldwell-Pope:

You searched for "Spencer Dinwiddie"
1 result found.
Spencer Dinwiddie
Results for Spencer Dinwiddie:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Justin Harper"
4 results found.
0: Justin Harper
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Justin Harper:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "Darrun Hilliard"
1 result found.
Darrun Hilliard
Results for Darrun Hilliard:

You searched for "Ersan İlyasova"
1 result found.
Ersan Ilyasova
Results for Ersan Ilyasova:

You searched for "Reggie Jackson"
6 results found.
0: Reggie Jackson
1: Reggie Hanson
2: Reggie Johnson
3: Cedric Jackson
4: Greg Jackson
5: Mervin Jackson
Pick one: 0
Results for Reggie Jackson:

You searched for "Brandon Jennings"
1 result found.
Brandon Jennings
Results for Brandon Jennings:

You searched for "Stanley Johnson"
9 results found.
0: Stanley Johnson
1: Stanley Jackson
2: Andy Johnson
3: Charles Johnson
4: Steve Johnson
5: Stew Johnson
6: Trey Johnson
7: Tyler Johnson
8: Wesley Johnson
Pick one: 0
Results for Stanley Johnson:

You searched for "Jodie Meeks"
1 result found.
Jodie Meeks
Results for Jodie Meeks:

You searched for "Marcus Morris"
5 results found.
0: Marcus Morris
1: Darius Morris
2: Marcus Cousin
3: Chris Morris
4: Max Morris
Pick one: 0
Results for Marcus Morris:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-12-02,25-230,DET,HOME,PHO,W (+5),1,39:56,12,20,...,3,16,1,0,3,3,34,33.7,27,Reggie Jackson
1,2015-11-08,22-090,DET,AWAY,POR,W (+17),1,35:52,14,19,...,27,0,2,3,1,3,29,32.9,14,Andre Drummond
2,2015-11-08,25-206,DET,AWAY,POR,W (+17),1,34:17,15,26,...,5,5,2,0,2,1,40,32.8,22,Reggie Jackson
3,2016-04-08,25-358,DET,HOME,WAS,W (+13),1,34:24,14,20,...,4,9,0,0,5,3,39,32.3,20,Reggie Jackson
4,2016-04-01,26-212,DET,HOME,DAL,L (-9),1,39:39,12,17,...,12,4,1,2,0,2,31,32.3,12,Marcus Morris

In [30]:


DET_2017_gamelog = []

for p in DET_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2017_gamelog.append(player_log)
DET_2017_gamelog = pd.concat(DET_2017_gamelog)    
DET_2017_gamelogs = DET_2017_gamelog.copy()
DET_2017_gamelogs['GAME_SCORE'] = DET_2017_gamelogs['GAME_SCORE'].astype(float)
DET_2017_games = DET_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2017_games_csv = DET_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2017_games.csv', index=False)
DET_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2017_games.csv')
DET_2017_games_proc.head()

You searched for "Aron Baynes"
8 results found.
0: Aron Baynes
1: Ron Baker
2: Harry Barnes
3: Marvin Barnes
4: Ron Boone
5: Aaron James
6: Tharon Mayes
7: Cameron Payne
Pick one: 0
Results for Aron Baynes:

You searched for "Reggie Bullock"
1 result found.
Reggie Bullock
Results for Reggie Bullock:

You searched for "Kentavious Caldwell-Pope"
1 result found.
Kentavious Caldwell-Pope
Results for Kentavious Caldwell-Pope:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Henry Ellenson"
1 result found.
Henry Ellenson
Results for Henry Ellenson:

You searched for "Michael Gbinije"
2 results found.
0: Michael Gbinije
1: Michael Finley
Pick one: 0
Results for Michael Gbinije:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "Darrun Hilliard"
1 result found.
Darrun Hilliard
Results for Darrun Hilliard:

You searched for "Reggie Jackson"
6 results found.
0: Reggie Jackson
1: Reggie Hanson
2: Reggie Johnson
3: Cedric Jackson
4: Greg Jackson
5: Mervin Jackson
Pick one: 0
Results for Reggie Jackson:

You searched for "Stanley Johnson"
9 results found.
0: Stanley Johnson
1: Stanley Jackson
2: Andy Johnson
3: Charles Johnson
4: Steve Johnson
5: Stew Johnson
6: Trey Johnson
7: Tyler Johnson
8: Wesley Johnson
Pick one: 0
Results for Stanley Johnson:

You searched for "Jon Leuer"
18 results found.
0: Jon Leuer
1: Ron Lee
2: Jon Teske
3: Ron Baker
4: Ron Brewer
5: John Coker
6: Don Dee
7: Fat Lever
8: Ron Mercer
9: Ron Reed
10: Von Wafer
11: Joe DePre
12: John Drew
13: Joe Kleine
14: John Long
15: John Olive
16: Ron Riley
17: John Wall
Pick one: 0
Results for Jon Leuer:

You searched for "Boban Marjanović"
1 result found.
Boban Marjanovic
Results for Boban Marjanovic:

You searched for "Marcus Morris"
5 results found.
0: Marcus Morris
1: Darius Morris
2: Marcus Cousin
3: Chris Morris
4: Max Morris
Pick one: 0
Results for Marcus Morris:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-02-28,27-179,DET,HOME,POR,W (+7),1,41:43,13,23,...,8,6,0,0,0,2,37,32.7,4,Marcus Morris
1,2017-02-01,23-349,DET,HOME,NOP,W (+20),1,38:33,12,18,...,4,1,4,0,2,2,38,32.5,11,Kentavious Caldwell-Pope
2,2017-01-30,23-173,DET,AWAY,BOS,L (-4),1,40:40,12,19,...,22,3,2,2,1,2,28,31.4,0,Andre Drummond
3,2017-02-03,27-154,DET,HOME,MIN,W (+8),1,38:18,12,19,...,5,2,1,0,2,1,36,28.2,14,Marcus Morris
4,2017-01-08,23-151,DET,AWAY,POR,W (+1),1,51:54,13,20,...,14,0,4,2,1,4,28,26.6,5,Andre Drummond

In [31]:


DET_2018_gamelog = []

for p in DET_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2018_gamelog.append(player_log)
DET_2018_gamelog = pd.concat(DET_2018_gamelog)    
DET_2018_gamelogs = DET_2018_gamelog.copy()
DET_2018_gamelogs['GAME_SCORE'] = DET_2018_gamelogs['GAME_SCORE'].astype(float)
DET_2018_games = DET_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2018_games_csv = DET_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2018_games.csv', index=False)
DET_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2018_games.csv')
DET_2018_games_proc.head()

You searched for "Avery Bradley"
4 results found.
0: Avery Bradley
1: Alex Bradley
2: Joe Bradley
3: Tony Bradley
Pick one: 0
Results for Avery Bradley:

You searched for "Reggie Bullock"
1 result found.
Reggie Bullock
Results for Reggie Bullock:

You searched for "Dwight Buycks"
1 result found.
Dwight Buycks
Results for Dwight Buycks:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Henry Ellenson"
1 result found.
Henry Ellenson
Results for Henry Ellenson:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Kay Felder"
6 results found.
0: Kay Felder
1: Ray Felix
2: Gary Keller
3: Ken Keller
4: Jay Miller
5: Gary Zeller
Pick one: 0
Results for Kay Felder:

You searched for "Langston Galloway"
1 result found.
Langston Galloway
Results for Langston Galloway:

You searched for "Blake Griffin"
3 results found.
0: Blake Griffin
1: Eddie Griffin
2: Paul Griffin
Pick one: 0
Results for Blake Griffin:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "Reggie Hearn"
11 results found.
0: Reggie Hearn
1: Reggie Geary
2: Reggie Perry
3: Reggie Evans
4: Reggie Hanson
5: Reggie Harding
6: Reggie Lewis
7: Reggie Theus
8: Reggie King
9: Reggie Slater
10: Reggie Smith
Pick one: 0
Results for Reggie Hearn:

You searched for "Reggie Jackson"
6 results found.
0: Reggie Jackson
1: Reggie Hanson
2: Reggie Johnson
3: Cedric Jackson
4: Greg Jackson
5: Mervin Jackson
Pick one: 0
Results for Reggie Jackson:

You searched for "Stanley Johnson"
9 results found.
0: Stanley Johnson
1: Stanley Jackson
2: Andy Johnson
3: Charles Johnson
4: Steve Johnson
5: Stew Johnson
6: Trey Johnson
7: Tyler Johnson
8: Wesley Johnson
Pick one: 0
Results for Stanley Johnson:

You searched for "Luke Kennard"
1 result found.
Luke Kennard
Results for Luke Kennard:

You searched for "Jon Leuer"
18 results found.
0: Jon Leuer
1: Ron Lee
2: Jon Teske
3: Ron Baker
4: Ron Brewer
5: John Coker
6: Don Dee
7: Fat Lever
8: Ron Mercer
9: Ron Reed
10: Von Wafer
11: Joe DePre
12: John Drew
13: Joe Kleine
14: John Long
15: John Olive
16: Ron Riley
17: John Wall
Pick one: 0
Results for Jon Leuer:

You searched for "Boban Marjanović"
1 result found.
Boban Marjanovic
Results for Boban Marjanovic:

You searched for "Luis Montero"
1 result found.
Luis Montero
Results for Luis Montero:

You searched for "Eric Moreland"
1 result found.
Eric Moreland
Results for Eric Moreland:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Willie Reed"
12 results found.
0: Willie Reed
1: Willis Reed
2: Willie Green
3: Willie Allen
4: Willie Jones
5: Willie Long
6: Willie Porter
7: Billy Reid
8: Willie Rogers
9: Willie Warren
10: Willie Wise
11: Willie White
Pick one: 0
Results for Willie Reed:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-01-24,24-167,DET,HOME,UTA,L (-3),1,39:28,11,17,...,24,4,3,6,5,4,30,34.7,-3,Andre Drummond
1,2017-11-27,24-109,DET,AWAY,BOS,W (+10),1,39:50,10,12,...,22,6,4,0,3,2,26,32.6,13,Andre Drummond
2,2018-03-20,29-004,DET,AWAY,PHO,W (+27),1,32:25,9,15,...,9,10,0,1,0,1,26,29.9,26,Blake Griffin
3,2018-02-23,25-223,LAC,AWAY,PHO,W (+11),1,35:51,10,15,...,12,4,1,2,1,4,30,29.3,13,Tobias Harris
4,2018-03-24,24-226,DET,HOME,CHI,W (+22),1,35:48,6,9,...,20,4,4,4,0,0,15,29.1,20,Andre Drummond

In [34]:
# removed glenn robinson

DET_2019_gamelog = []

for p in DET_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2019_gamelog.append(player_log)
DET_2019_gamelog = pd.concat(DET_2019_gamelog)    
DET_2019_gamelogs = DET_2019_gamelog.copy()
DET_2019_gamelogs['GAME_SCORE'] = DET_2019_gamelogs['GAME_SCORE'].astype(float)
DET_2019_games = DET_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2019_games_csv = DET_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2019_games.csv', index=False)
DET_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2019_games.csv')
DET_2019_games_proc.head()

You searched for "Bruce Brown"
16 results found.
0: Bruce Brown
1: Bruce Bowen
2: Andre Brown
3: Bob Brown
4: Bobby Brown
5: Chucky Brown
6: Dee Brown
7: Dee Brown
8: Fred Brown
9: Kwame Brown
10: Mike Brown
11: Rickey Brown
12: Roger Brown
13: Roger Brown
14: Troy Brown
15: Bryce Drew
Pick one: 0
Results for Bruce Brown:

You searched for "Reggie Bullock"
1 result found.
Reggie Bullock
Results for Reggie Bullock:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Henry Ellenson"
1 result found.
Henry Ellenson
Results for Henry Ellenson:

You searched for "Wayne Ellington"
1 result found.
Wayne Ellington
Results for Wayne Ellington:

You searched for "Langston Galloway"
1 result found.
Langston Galloway
Results for Langston Galloway:

You searched for "Blake Griffin"
3 results found.
0: Blake Griffin
1: Eddie Griffin
2: Paul Griffin
Pick one: 0
Results for Blake Griffin:

You searched for "Reggie Jackson"
6 results found.
0: Reggie Jackson
1: Reggie Hanson
2: Reggie Johnson
3: Cedric Jackson
4: Greg Jackson
5: Mervin Jackson
Pick one: 0
Results for Reggie Jackson:

You searched for "Stanley Johnson"
9 results found.
0: Stanley Johnson
1: Stanley Jackson
2: Andy Johnson
3: Charles Johnson
4: Steve Johnson
5: Stew Johnson
6: Trey Johnson
7: Tyler Johnson
8: Wesley Johnson
Pick one: 0
Results for Stanley Johnson:

You searched for "Luke Kennard"
1 result found.
Luke Kennard
Results for Luke Kennard:

You searched for "Jon Leuer"
18 results found.
0: Jon Leuer
1: Ron Lee
2: Jon Teske
3: Ron Baker
4: Ron Brewer
5: John Coker
6: Don Dee
7: Fat Lever
8: Ron Mercer
9: Ron Reed
10: Von Wafer
11: Joe DePre
12: John Drew
13: Joe Kleine
14: John Long
15: John Olive
16: Ron Riley
17: John Wall
Pick one: 0
Results for Jon Leuer:

You searched for "Zach Lofton"
2 results found.
0: Zach Lofton
1: Jack Cotton
Pick one: 0
Results for Zach Lofton:

You searched for "Kalin Lucas"
3 results found.
0: Kalin Lucas
1: Al Lucas
2: John Lucas
Pick one: 0
Results for Kalin Lucas:

You searched for "Thon Maker"
8 results found.
0: Thon Maker
1: Ron Baker
2: Vin Baker
3: Tom Barker
4: Tharon Mayes
5: Tony Parker
6: Tom Riker
7: Von Wafer
Pick one: 0
Results for Thon Maker:

You searched for "Sviatoslav Mykhailiuk"
1 result found.
Sviatoslav Mykhailiuk
Results for Sviatoslav Mykhailiuk:

You searched for "Zaza Pachulia"
1 result found.
Zaza Pachulia
Results for Zaza Pachulia:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Khyri Thomas"
6 results found.
0: Khyri Thomas
1: Kurt Thomas
2: Carl Thomas
3: Kenny Thomas
4: Terry Thomas
5: Tyrus Thomas
Pick one: 0
Results for Khyri Thomas:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-04-05,30-020,DET,AWAY,OKC,L (-13),1,34:35,11,20,...,7,3,2,0,1,0,45,39.8,-11,Blake Griffin
1,2018-10-23,29-221,DET,HOME,PHI,W (+1),1,44:02,20,35,...,14,6,0,1,1,4,50,38.8,4,Blake Griffin
2,2019-01-12,29-302,DET,AWAY,LAC,W (+5),1,40:04,13,23,...,8,5,3,1,4,4,44,36.7,12,Blake Griffin
3,2019-02-08,25-182,DET,HOME,NYK,W (+17),1,33:13,12,15,...,20,2,1,3,1,4,29,32.0,39,Andre Drummond
4,2019-02-11,25-185,DET,HOME,WAS,W (+9),1,35:35,12,19,...,17,0,4,1,1,3,32,31.9,15,Andre Drummond

In [35]:


DET_2020_gamelog = []

for p in DET_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2020_gamelog.append(player_log)
DET_2020_gamelog = pd.concat(DET_2020_gamelog)    
DET_2020_gamelogs = DET_2020_gamelog.copy()
DET_2020_gamelogs['GAME_SCORE'] = DET_2020_gamelogs['GAME_SCORE'].astype(float)
DET_2020_games = DET_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2020_games_csv = DET_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2020_games.csv', index=False)
DET_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2020_games.csv')
DET_2020_games_proc.head()

You searched for "Jordan Bone"
10 results found.
0: Jordan Bone
1: Jordan Bowden
2: Jordan Ford
3: Jordan Bell
4: Jordan Loyd
5: Jordan Poole
6: Jordan Nwora
7: Jordan Hill
8: Jordan McRae
9: Ryan Bowen
Pick one: 0
Results for Jordan Bone:

You searched for "Bruce Brown"
16 results found.
0: Bruce Brown
1: Bruce Bowen
2: Andre Brown
3: Bob Brown
4: Bobby Brown
5: Chucky Brown
6: Dee Brown
7: Dee Brown
8: Fred Brown
9: Kwame Brown
10: Mike Brown
11: Rickey Brown
12: Roger Brown
13: Roger Brown
14: Troy Brown
15: Bryce Drew
Pick one: 0
Results for Bruce Brown:

You searched for "Sekou Doumbouya"
1 result found.
Sekou Doumbouya
Results for Sekou Doumbouya:

You searched for "Andre Drummond"
1 result found.
Andre Drummond
Results for Andre Drummond:

You searched for "Tim Frazier"
4 results found.
0: Tim Frazier
1: Will Frazier
2: Jim Farmer
3: Walt Frazier
Pick one: 0
Results for Tim Frazier:

You searched for "Langston Galloway"
1 result found.
Langston Galloway
Results for Langston Galloway:

You searched for "Blake Griffin"
3 results found.
0: Blake Griffin
1: Eddie Griffin
2: Paul Griffin
Pick one: 0
Results for Blake Griffin:

You searched for "Donta Hall"
5 results found.
0: Donta Hall
1: Josh Hall
2: Lonzo Ball
3: Devon Hall
4: Donta Smith
Pick one: 0
Results for Donta Hall:

You searched for "John Henson"
23 results found.
0: John Henson
1: John Johnson
2: John Paxson
3: John Clawson
4: John Dickson
5: John Hazen
6: Jack Hewson
7: Roy Hinson
8: John Jenkins
9: John Morton
10: Don Nelson
11: Ron Nelson
12: John Pinone
13: John Thompson
14: John Windsor
15: John Chaney
16: John Hargis
17: John Hummer
18: John Long
19: John Mahnken
20: Johan Petro
21: John Warren
22: John Thomas
Pick one: 0
Results for John Henson:

You searched for "Reggie Jackson"
6 results found.
0: Reggie Jackson
1: Reggie Hanson
2: Reggie Johnson
3: Cedric Jackson
4: Greg Jackson
5: Mervin Jackson
Pick one: 0
Results for Reggie Jackson:

You searched for "Luke Kennard"
1 result found.
Luke Kennard
Results for Luke Kennard:

You searched for "Louis King"
7 results found.
0: Louis King
1: Chris King
2: Loyd King
3: Jim King
4: Ron King
5: Tom King
6: Louis Orr
Pick one: 0
Results for Louis King:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "Thon Maker"
8 results found.
0: Thon Maker
1: Ron Baker
2: Vin Baker
3: Tom Barker
4: Tharon Mayes
5: Tony Parker
6: Tom Riker
7: Von Wafer
Pick one: 0
Results for Thon Maker:

You searched for "Jordan McRae"
9 results found.
0: Jordan McRae
1: Jordan Nwora
2: Jordan Ford
3: Jordan Bone
4: Jordan Farmar
5: Jordan Mickey
6: Jordan Poole
7: Jordan Adams
8: Jordan Bell
Pick one: 0
Results for Jordan McRae:

You searched for "Markieff Morris"
1 result found.
Markieff Morris
Results for Markieff Morris:

You searched for "Sviatoslav Mykhailiuk"
1 result found.
Sviatoslav Mykhailiuk
Results for Sviatoslav Mykhailiuk:

You searched for "Derrick Rose"
9 results found.
0: Derrick Rose
1: Derrick Brown
2: Derrick Jones
3: Derrick Dial
4: Derrick McKey
5: Derrick White
6: Derrick Byars
7: Derrick Favors
8: Rick Robey
Pick one: 0
Results for Derrick Rose:

You searched for "Tony Snell"
16 results found.
0: Tony Snell
1: Tony Delk
2: Troy Bell
3: Tony Lavelli
4: Tom Sewell
5: Tony Smith
6: Tony Zeno
7: Tony Allen
8: Tony Brown
9: Tony Dumas
10: Tony Jaros
11: Tom Kelly
12: Tony Koski
13: Tony Price
14: Tony White
15: Tony Dawson
Pick one: 0
Results for Tony Snell:

You searched for "Khyri Thomas"
6 results found.
0: Khyri Thomas
1: Kurt Thomas
2: Carl Thomas
3: Kenny Thomas
4: Terry Thomas
5: Tyrus Thomas
Pick one: 0
Results for Khyri Thomas:

You searched for "Derrick Walton"
5 results found.
0: Derrick Walton
1: Derrick Alston
2: Darrick Martin
3: Derrick White
4: Derrick Jones
Pick one: 0
Results for Derrick Walton:

You searched for "Christian Wood"
1 result found.
Christian Wood
Results for Christian Wood:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-10-23,26-074,DET,AWAY,IND,W (+9),1,40:48,12,18,...,23,2,3,4,2,4,32,36.7,4,Andre Drummond
1,2020-02-05,26-179,DET,HOME,PHO,W (+8),1,38:08,14,19,...,19,4,3,0,3,1,31,33.4,14,Andre Drummond
2,2019-11-02,26-084,DET,HOME,BRK,W (+4),1,38:51,10,16,...,20,6,3,5,4,4,25,29.7,8,Andre Drummond
3,2020-03-11,24-166,DET,AWAY,PHI,L (-18),1,38:58,14,18,...,7,2,3,2,3,1,32,28.7,-4,Christian Wood
4,2020-01-07,26-150,DET,AWAY,CLE,W (+2),1,38:26,8,12,...,20,5,1,2,3,2,23,28.3,7,Andre Drummond

In [45]:

DET_2021_gamelog = []

for p in DET_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    DET_2021_gamelog.append(player_log)
DET_2021_gamelog = pd.concat(DET_2021_gamelog)    
DET_2021_gamelogs = DET_2021_gamelog.copy()
DET_2021_gamelogs['GAME_SCORE'] = DET_2021_gamelogs['GAME_SCORE'].astype(float)
DET_2021_games = DET_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
DET_2021_games_csv = DET_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2021_games.csv', index=False)
DET_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2021_games.csv')
DET_2021_games_proc.head()

You searched for "Saddiq Bey"
1 result found.
Saddiq Bey
Results for Saddiq Bey:

You searched for "Tyler Cook"
8 results found.
0: Tyler Cook
1: Tyler Bey
2: Bert Cook
3: Omar Cook
4: Tyler Lydon
5: Tyler Ulis
6: Joe Cooke
7: Tyler Herro
Pick one: 0
Results for Tyler Cook:

You searched for "Hamidou Diallo"
1 result found.
Hamidou Diallo
Results for Hamidou Diallo:

You searched for "Sekou Doumbouya"
1 result found.
Sekou Doumbouya
Results for Sekou Doumbouya:

You searched for "Wayne Ellington"
1 result found.
Wayne Ellington
Results for Wayne Ellington:

You searched for "Jerami Grant"
4 results found.
0: Jerami Grant
1: Jerian Grant
2: Horace Grant
3: Travis Grant
Pick one: 0
Results for Jerami Grant:

You searched for "Blake Griffin"
3 results found.
0: Blake Griffin
1: Eddie Griffin
2: Paul Griffin
Pick one: 0
Results for Blake Griffin:

You searched for "Killian Hayes"
2 results found.
0: Killian Hayes
1: Elvin Hayes
Pick one: 0
Results for Killian Hayes:

You searched for "Frank Jackson"
15 results found.
0: Frank Jackson
1: Mark Jackson
2: Tracy Jackson
3: Frank Johnson
4: Frank Mason
5: Aaron Jackson
6: Al Jackson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Marc Jackson
11: Myron Jackson
12: Ralph Jackson
13: Tony Jackson
14: Tony Jackson
Pick one: 0
Results for Frank Jackson:

You searched for "Josh Jackson"
18 results found.
0: Josh Jackson
1: Jim Jackson
2: Tony Jackson
3: Tony Jackson
4: John Dickson
5: Al Jackson
6: Bobby Jackson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Mike Jackson
16: Phil Jackson
17: Ralph Jackson
Pick one: 0
Results for Josh Jackson:

You searched for "Cory Joseph"
4 results found.
0: Cory Joseph
1: Garth Joseph
2: Kris Joseph
3: Yvon Joseph
Pick one: 0
Results for Cory Joseph:

You searched for "Saben Lee"
8 results found.
0: Saben Lee
1: Damion Lee
2: David Lee
3: David Lee
4: Greg Lee
5: Ron Lee
6: Alex Len
7: Ed Leede
Pick one: 0
Results for Saben Lee:

You searched for "Rodney McGruder"
1 result found.
Rodney McGruder
Results for Rodney McGruder:

You searched for "Sviatoslav Mykhailiuk"
1 result found.
Sviatoslav Mykhailiuk
Results for Sviatoslav Mykhailiuk:

You searched for "Jahlil Okafor"
1 result found.
Jahlil Okafor
Results for Jahlil Okafor:

You searched for "Mason Plumlee"
2 results found.
0: Mason Plumlee
1: Miles Plumlee
Pick one: 0
Results for Mason Plumlee:

You searched for "Derrick Rose"
9 results found.
0: Derrick Rose
1: Derrick Brown
2: Derrick Jones
3: Derrick Dial
4: Derrick McKey
5: Derrick White
6: Derrick Byars
7: Derrick Favors
8: Rick Robey
Pick one: 0
Results for Derrick Rose:

You searched for "Deividas Sirvydis"
1 result found.
Deividas Sirvydis
Results for Deividas Sirvydis:

You searched for "Isaiah Stewart"
1 result found.
Isaiah Stewart
Results for Isaiah Stewart:

You searched for "Delon Wright"
4 results found.
0: Delon Wright
1: Leroy Wright
2: Dorell Wright
3: Julian Wright
Pick one: 0
Results for Delon Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-01-25,28-274,DET,HOME,PHI,W (+15),1,36:00,8,12,...,7,9,2,1,3,1,28,30.9,22,Delon Wright
1,2021-05-05,29-009,SAC,AWAY,IND,W (+11),1,39:43,8,14,...,7,6,6,1,2,1,23,29.0,18,Delon Wright
2,2021-02-17,26-342,DET,AWAY,CHI,L (-3),1,37:48,15,25,...,2,0,0,1,3,5,43,27.8,-7,Jerami Grant
3,2021-03-17,21-342,DET,HOME,TOR,W (+4),1,38:39,8,14,...,12,2,2,0,0,4,28,27.6,4,Saddiq Bey
4,2021-01-16,26-310,DET,AWAY,MIA,W (+20),1,35:05,10,19,...,9,6,2,4,0,1,24,26.4,22,Jerami Grant

## combine all seasons

In [49]:
DET_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2000_games.csv')
DET_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2001_games.csv')
DET_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2002_games.csv')
DET_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2003_games.csv')
DET_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2004_games.csv')
DET_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2005_games.csv')
DET_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2006_games.csv')
DET_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2007_games.csv')
DET_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2008_games.csv')
DET_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2009_games.csv')
DET_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2010_games.csv')
DET_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2011_games.csv')
DET_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2012_games.csv')
DET_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2013_games.csv')
DET_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2014_games.csv')
DET_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2015_games.csv')
DET_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2016_games.csv')
DET_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2017_games.csv')
DET_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2018_games.csv')
DET_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2019_games.csv')
DET_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2020_games.csv')
DET_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/DET/DET_2021_games.csv')

In [50]:
DET_season_dfs = [DET_2000_games_io, DET_2001_games_io, DET_2002_games_io, DET_2003_games_io, DET_2004_games_io, DET_2005_games_io,
                 DET_2006_games_io, DET_2007_games_io, DET_2008_games_io, DET_2009_games_io, DET_2010_games_io, DET_2011_games_io,
                 DET_2012_games_io, DET_2013_games_io, DET_2014_games_io, DET_2015_games_io, DET_2016_games_io, DET_2017_games_io,
                 DET_2018_games_io, DET_2019_games_io, DET_2020_games_io, DET_2021_games_io]

In [51]:
DET_all = pd.concat(DET_season_dfs)
DET_all_sorted = DET_all.sort_values(by=['GAME_SCORE'], ascending=False)
DET_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-04-03,26-149,DET,AWAY,CHI,W (+27),1,41:40,21,36,...,4,5,1,0,4,2,57,40.3,34,Jerry Stackhouse
0,2019-04-05,30-020,DET,AWAY,OKC,L (-13),1,34:35,11,20,...,7,3,2,0,1,0,45,39.8,-11,Blake Griffin
1,2018-10-23,29-221,DET,HOME,PHI,W (+1),1,44:02,20,35,...,14,6,0,1,1,4,50,38.8,4,Blake Griffin
0,2012-03-21,28-352,DET,AWAY,DEN,L (-1),1,41:20,13,22,...,0,8,2,0,2,5,45,38.0,10,Ben Gordon
0,2000-01-05,27-092,DET,AWAY,ATL,W (+12),1,42:47,14,23,...,3,6,2,1,1,1,42,37.5,20,Grant Hill
0,2003-11-28,25-287,DET,HOME,CLE,W (+4),1,38:45,15,23,...,7,5,1,0,2,3,44,36.9,8,Richard Hamilton
2,2019-01-12,29-302,DET,AWAY,LAC,W (+5),1,40:04,13,23,...,8,5,3,1,4,4,44,36.7,12,Blake Griffin
0,2019-10-23,26-074,DET,AWAY,IND,W (+9),1,40:48,12,18,...,23,2,3,4,2,4,32,36.7,4,Andre Drummond
0,2006-01-03,29-100,DET,HOME,ORL,W (+9),1,43:10,9,15,...,2,9,2,0,1,3,37,36.0,14,Chauncey Billups
1,2006-03-28,29-184,DET,HOME,DAL,W (+7),1,37:16,8,14,...,4,11,3,0,1,2,31,35.3,21,Chauncey Billups
1,2000-01-15,27-102,DET,AWAY,WAS,W (+5),1,38:34,15,20,...,6,5,1,1,1,2,39,35.0,4,Grant Hill
2,2000-01-03,27-090,DET,AWAY,ORL,W (+12),1,44:14,17,30,...,7,8,2,1,3,2,42,34.8,14,Grant Hill
0,2018-01-24,24-167,DET,HOME,UTA,L (-3),1,39:28,11,17,...,24,4,3,6,5,4,30,34.7,-3,Andre Drummond
0,2013-12-01,20-113,DET,HOME,PHI,W (+15),1,32:59,12,15,...,19,0,6,2,1,2,31,34.6,25,Andre Drummond
0,2008-01-15,29-335,DET,HOME,TOR,W (+14),1,38:22,16,22,...,4,6,0,0,0,1,39,34.6,23,Richard Hamilton
0,2013-12-01,20-113,DET,HOME,PHI,W (+15),1,32:59,12,15,...,19,0,6,2,1,2,31,34.6,25,Andre Drummond
0,2015-12-02,25-230,DET,HOME,PHO,W (+5),1,39:56,12,20,...,3,16,1,0,3,3,34,33.7,27,Reggie Jackson
1,2007-11-21,31-057,DET,HOME,NYK,W (+12),1,34:51,7,13,...,4,15,3,1,0,1,25,33.7,36,Chauncey Billups
1,2020-02-05,26-179,DET,HOME,PHO,W (+8),1,38:08,14,19,...,19,4,3,0,3,1,31,33.4,14,Andre Drummond
0,2015-03-29,21-231,DET,AWAY,MIA,L (-7),1,39:02,14,17,...,14,2,1,2,0,3,32,33.3,1,Andre Drummond
2,2007-12-11,31-077,DET,AWAY,MEM,W (+10),1,38:38,7,15,...,5,14,3,0,1,2,28,33.2,19,Chauncey Billups
1,2015-11-08,22-090,DET,AWAY,POR,W (+17),1,35:52,14,19,...,27,0,2,3,1,3,29,32.9,14,Andre Drummond
3,2000-03-08,25-124,DET,HOME,DEN,W (+14),1,34:14,13,21,...,1,4,0,1,1,1,40,32.9,14,Jerry Stackhouse
2,2015-11-08,25-206,DET,AWAY,POR,W (+17),1,34:17,15,26,...,5,5,2,0,2,1,40,32.8,22,Reggie Jackson
0,2017-02-28,27-179,DET,HOME,POR,W (+7),1,41:43,13,23,...,8,6,0,0,0,2,37,32.7,4,Marcus Morris