In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2014-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_GSW = []

# GSW
while season <= 2021:
    df_GSW = get_roster('GSW', season)
    df_GSW['Season'] = season
    df_GSW['Team'] = 'GSW'
    appended_data_GSW.append(df_GSW)
    season = season + 1
appended_data_GSW = pd.concat(appended_data_GSW)

In [4]:
GSW_df_all = appended_data_GSW.copy()
GSW_df_all_csv = GSW_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_players_all.csv', index=False)
GSW_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_players_all.csv')
GSW_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,2,Drew Barry,PG,6-5,191,1973-02-17,US,2,Georgia Tech,2000,GSW
1,10,Mookie Blaylock,PG,6-0,180,1967-03-20,US,10,"Midland College, Oklahoma",2000,GSW
2,21,Jason Caffey,PF,6-8,255,1973-06-12,US,4,Alabama,2000,GSW
3,43,Chris Carr,SG,6-5,207,1974-03-12,US,4,Southern Illinois,2000,GSW
4,35,Terry Cummings,PF,6-9,220,1961-03-15,US,17,DePaul,2000,GSW

In [5]:
GSW_df_2000 = GSW_df_all[GSW_df_all['Season'] == 2000]
GSW_df_2001 = GSW_df_all[GSW_df_all['Season'] == 2001]
GSW_df_2002 = GSW_df_all[GSW_df_all['Season'] == 2002]
GSW_df_2003 = GSW_df_all[GSW_df_all['Season'] == 2003]
GSW_df_2004 = GSW_df_all[GSW_df_all['Season'] == 2004]
GSW_df_2005 = GSW_df_all[GSW_df_all['Season'] == 2005]
GSW_df_2006 = GSW_df_all[GSW_df_all['Season'] == 2006]
GSW_df_2007 = GSW_df_all[GSW_df_all['Season'] == 2007]
GSW_df_2008 = GSW_df_all[GSW_df_all['Season'] == 2008]
GSW_df_2009 = GSW_df_all[GSW_df_all['Season'] == 2009]
GSW_df_2010 = GSW_df_all[GSW_df_all['Season'] == 2010]
GSW_df_2011 = GSW_df_all[GSW_df_all['Season'] == 2011]
GSW_df_2012 = GSW_df_all[GSW_df_all['Season'] == 2012]
GSW_df_2013 = GSW_df_all[GSW_df_all['Season'] == 2013]
GSW_df_2014 = GSW_df_all[GSW_df_all['Season'] == 2014]
GSW_df_2015 = GSW_df_all[GSW_df_all['Season'] == 2015]
GSW_df_2016 = GSW_df_all[GSW_df_all['Season'] == 2016]
GSW_df_2017 = GSW_df_all[GSW_df_all['Season'] == 2017]
GSW_df_2018 = GSW_df_all[GSW_df_all['Season'] == 2018]
GSW_df_2019 = GSW_df_all[GSW_df_all['Season'] == 2019]
GSW_df_2020 = GSW_df_all[GSW_df_all['Season'] == 2020]
GSW_df_2021 = GSW_df_all[GSW_df_all['Season'] == 2021]

In [7]:
# changing names
#GSW_df_2002.loc[GSW_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#GSW_df_2004.loc[GSW_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [6]:
GSW_df_2000_players = GSW_df_2000['PLAYER'].to_list()
GSW_df_2001_players = GSW_df_2001['PLAYER'].to_list()
GSW_df_2002_players = GSW_df_2002['PLAYER'].to_list()
GSW_df_2003_players = GSW_df_2003['PLAYER'].to_list()
GSW_df_2004_players = GSW_df_2004['PLAYER'].to_list()
GSW_df_2005_players = GSW_df_2005['PLAYER'].to_list()

GSW_df_2006_players = GSW_df_2006['PLAYER'].to_list()
GSW_df_2007_players = GSW_df_2007['PLAYER'].to_list()
GSW_df_2008_players = GSW_df_2008['PLAYER'].to_list()
GSW_df_2009_players = GSW_df_2009['PLAYER'].to_list()
GSW_df_2010_players = GSW_df_2010['PLAYER'].to_list()
GSW_df_2011_players = GSW_df_2011['PLAYER'].to_list()

GSW_df_2012_players = GSW_df_2012['PLAYER'].to_list()
GSW_df_2013_players = GSW_df_2013['PLAYER'].to_list()
GSW_df_2014_players = GSW_df_2014['PLAYER'].to_list()
GSW_df_2015_players = GSW_df_2015['PLAYER'].to_list()
GSW_df_2016_players = GSW_df_2016['PLAYER'].to_list()
GSW_df_2017_players = GSW_df_2017['PLAYER'].to_list()

GSW_df_2018_players = GSW_df_2018['PLAYER'].to_list()
GSW_df_2019_players = GSW_df_2019['PLAYER'].to_list()
GSW_df_2020_players = GSW_df_2020['PLAYER'].to_list()
GSW_df_2021_players = GSW_df_2021['PLAYER'].to_list()

## players to drop

In [84]:

#GSW_df_2000_players.remove("Mark Davis")
#GSW_df_2002_players.remove("Cedric Henderson")
#GSW_df_2003_players.remove("Mike Dunleavy")
#GSW_df_2004_players.remove("Mike Dunleavy")
#GSW_df_2005_players.remove("Mike Dunleavy")
#GSW_df_2006_players.remove("Mike Dunleavy")
#GSW_df_2007_players.remove("Mike Dunleavy")
#GSW_df_2007_players.remove("Patrick O'Bryant")
#GSW_df_2008_players.remove("Didier Ilunga-Mbenga")
#GSW_df_2008_players.remove("Patrick O'Bryant")
#GSW_df_2011_players.remove("David Lee")
#GSW_df_2010_players.remove("Reggie Williams")
#GSW_df_2011_players.remove("Reggie Williams")
#GSW_df_2012_players.remove("David Lee")
#GSW_df_2013_players.remove("Dwayne Jones")
#GSW_df_2013_players.remove("David Lee")
#GSW_df_2014_players.remove("David Lee")
#GSW_df_2014_players.remove("Jermaine O'Neal")
#GSW_df_2015_players.remove("David Lee")
#GSW_df_2015_players.remove("James Michael McAdoo")
#GSW_df_2016_players.remove("James Michael McAdoo")
#GSW_df_2017_players.remove("James Michael McAdoo")
#GSW_df_2020_players.remove("Glenn Robinson")
#GSW_df_2020_players.remove("D'Angelo Russell")
#GSW_df_2021_players.remove("Kelly Oubre")
GSW_df_2021_players.remove("Gary Payton")

In [9]:

GSW_2000_gamelog = []



for p in GSW_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2000_gamelog.append(player_log)
GSW_2000_gamelog = pd.concat(GSW_2000_gamelog)    
GSW_2000_gamelogs = GSW_2000_gamelog.copy()
GSW_2000_gamelogs['GAME_SCORE'] = GSW_2000_gamelogs['GAME_SCORE'].astype(float)
GSW_2000_games = GSW_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2000_games_csv = GSW_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2000_games.csv', index=False)
GSW_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2000_games.csv')
GSW_2000_games_proc.head()

You searched for "Drew Barry"
5 results found.
0: Drew Barry
1: Brent Barry
2: Moe Barr
3: Jon Barry
4: Rick Barry
Pick one: 0
Results for Drew Barry:

You searched for "Mookie Blaylock"
1 result found.
Mookie Blaylock
Results for Mookie Blaylock:

You searched for "Jason Caffey"
2 results found.
0: Jason Caffey
1: Jason Sasser
Pick one: 0
Results for Jason Caffey:

You searched for "Chris Carr"
21 results found.
0: Chris Carr
1: Chris Babb
2: Cory Carr
3: Chris Ford
4: Chris Garner
5: Chris Harris
6: Chris Paul
7: Chris Taft
8: Chris Bosh
9: Chris Herren
10: Chris Jent
11: Chris Kaman
12: Chris King
13: Chris McCray
14: Chris Mihm
15: Chris Morris
16: Chris Munk
17: Chris Porter
18: Chris Richard
19: Chris Welp
20: Chris Silva
Pick one: 0
Results for Chris Carr:

You searched for "Terry Cummings"
1 result found.
Terry Cummings
Results for Terry Cummings:

You searched for "Vonteego Cummings"
1 result found.
Vonteego Cummings
Results for Vonteego Cummings:

You searched for "Bill Curley"
14 results found.
0: Bill Curley
1: Bill Turner
2: Bill Allen
3: Bill Bradley
4: Bill Bradley
5: Bill Crow
6: Dell Curry
7: Bill Downey
8: Bill Garner
9: Bill Keller
10: Bill Miller
11: Bill Closs
12: Bill McGill
13: Bill Meyer
Pick one: 0
Results for Bill Curley:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "Tony Farmer"
14 results found.
0: Tony Farmer
1: Tony Parker
2: Tony Fuller
3: Tony Allen
4: Tom Barker
5: Ron Carter
6: Jim Farmer
7: Mike Farmer
8: Ron Harper
9: Tony Harris
10: Tony Jaros
11: Tony Kappen
12: Sonny Parker
13: Tony Battie
Pick one: 0
Results for Tony Farmer:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Larry Hughes"
6 results found.
0: Larry Hughes
1: Larry Bunce
2: Larry Fogle
3: Larry Jones
4: Larry Sykes
5: Larry Wright
Pick one: 0
Results for Larry Hughes:

You searched for "Sam Jacobson"
3 results found.
0: Sam Jacobson
1: Al Jackson
2: Jim Jackson
Pick one: 0
Results for Sam Jacobson:

You searched for "Antawn Jamison"
1 result found.
Antawn Jamison
Results for Antawn Jamison:

You searched for "Damon Jones"
24 results found.
0: Damon Jones
1: Mason Jones
2: Damian Jones
3: Damion James
4: Jalen Jones
5: James Jones
6: Major Jones
7: Sam Jones
8: Aaron James
9: Alvin Jones
10: DeQuan Jones
11: Dwayne Jones
12: Earl Jones
13: Jake Jones
14: Jimmy Jones
15: Kevin Jones
16: Larry Jones
17: Mark Jones
18: Mark Jones
19: Robin Jones
20: Solomon Jones
21: Wali Jones
22: Diamond Stone
23: Damone Brown
Pick one: 0
Results for Damon Jones:

You searched for "Tim Legler"
2 results found.
0: Tim Legler
1: Tim Perry
Pick one: 0
Results for Tim Legler:

You searched for "Sam Mack"
9 results found.
0: Sam Mack
1: Sam Cash
2: Sam Lacey
3: Yam Madar
4: Tom Black
5: Sean Marks
6: Sean May
7: Sam Smith
8: Sam Smith
Pick one: 0
Results for Sam Mack:

You searched for "Donyell Marshall"
3 results found.
0: Donyell Marshall
1: Donny Marshall
2: Kendall Marshall
Pick one: 0
Results for Donyell Marshall:

You searched for "Chris Mills"
19 results found.
0: Chris Mills
1: Chris Childs
2: Chris Mihm
3: Chris Mullin
4: Chris Silva
5: Chris King
6: Darius Miles
7: Terry Mills
8: Chris Morris
9: Chris Munk
10: Chris Owens
11: Chris Paul
12: Chris Smith
13: Chris Smith
14: Chris Welp
15: Chris Wilcox
16: Chris Bosh
17: Chris Kaman
18: Chris Quinn
Pick one: 0
Results for Chris Mills:

You searched for "Billy Owens"
9 results found.
0: Billy Owens
1: Billy Evans
2: Billy James
3: Bill Jones
4: Jim Owens
5: Larry Owens
6: Billy Reid
7: Bill Downey
8: Bill Henry
Pick one: 0
Results for Billy Owens:

You searched for "John Starks"
9 results found.
0: John Starks
1: John Shasky
2: John Barr
3: John Edwards
4: John Garris
5: John Hargis
6: John Stroud
7: John Trapp
8: John Kuester
Pick one: 0
Results for John Starks:

You searched for "Jamel Thomas"
9 results found.
0: Jamel Thomas
1: James Thomas
2: Carl Thomas
3: Jim Thomas
4: Joe Thomas
5: John Thomas
6: Lance Thomas
7: Matt Thomas
8: Tim Thomas
Pick one: 0
Results for Jamel Thomas:

You searched for "Tim Young"
10 results found.
0: Tim Young
1: Sam Young
2: Joe Young
3: Nick Young
4: Trae Young
5: Jim King
6: Tom King
7: James Young
8: Jim Nolan
9: Tim Perry
Pick one: 0
Results for Tim Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-02-23,26-281,GSW,AWAY,MIL,W (+5),1,43:56,15,25,...,21,3,3,2,3,4,37,36.5,6,Donyell Marshall
1,2000-04-09,21-077,GSW,HOME,DEN,W (+14),1,44:18,16,29,...,6,7,3,1,3,2,44,35.1,21,Larry Hughes
2,2000-03-09,21-046,GSW,HOME,LAL,L (-17),1,40:34,15,25,...,3,3,3,1,0,3,41,33.8,-3,Larry Hughes
3,2000-04-05,26-323,GSW,HOME,LAL,L (-7),1,45:16,9,18,...,18,5,3,0,2,2,32,33.3,-7,Donyell Marshall
4,2000-01-21,23-223,GSW,HOME,CLE,W (+12),1,42:02,13,24,...,18,4,2,0,3,4,37,33.0,4,Antawn Jamison

In [10]:

GSW_2001_gamelog = []


for p in GSW_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2001_gamelog.append(player_log)
GSW_2001_gamelog = pd.concat(GSW_2001_gamelog)    
GSW_2001_gamelogs = GSW_2001_gamelog.copy()
GSW_2001_gamelogs['GAME_SCORE'] = GSW_2001_gamelogs['GAME_SCORE'].astype(float)
GSW_2001_games = GSW_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2001_games_csv = GSW_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2001_games.csv', index=False)
GSW_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2001_games.csv')
GSW_2001_games_proc.head()

You searched for "Mookie Blaylock"
1 result found.
Mookie Blaylock
Results for Mookie Blaylock:

You searched for "Corie Blount"
2 results found.
0: Corie Blount
1: Mark Blount
Pick one: 0
Results for Corie Blount:

You searched for "Chucky Brown"
3 results found.
0: Chucky Brown
1: Bruce Brown
2: Rickey Brown
Pick one: 0
Results for Chucky Brown:

You searched for "John Coker"
28 results found.
0: John Coker
1: Ron Baker
2: John Barber
3: John Barr
4: John Brisker
5: John Chaney
6: John Comeaux
7: Joe Cooke
8: Joe Cooper
9: John Crotty
10: John Drew
11: John Duren
12: John Hazen
13: John Hummer
14: Jon Leuer
15: John Logan
16: John Long
17: John Richter
18: John Roche
19: John Turner
20: John Block
21: John Brown
22: Johnny Cox
23: John Lucas
24: John Olive
25: John Pilch
26: John Pinone
27: John Rudd
Pick one: 0
Results for John Coker:

You searched for "Vonteego Cummings"
1 result found.
Vonteego Cummings
Results for Vonteego Cummings:

You searched for "Bill Curley"
14 results found.
0: Bill Curley
1: Bill Turner
2: Bill Allen
3: Bill Bradley
4: Bill Bradley
5: Bill Crow
6: Dell Curry
7: Bill Downey
8: Bill Garner
9: Bill Keller
10: Bill Miller
11: Bill Closs
12: Bill McGill
13: Bill Meyer
Pick one: 0
Results for Bill Curley:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "Vinny Del Negro"
1 result found.
Vinny Del Negro
Results for Vinny Del Negro:

You searched for "Danny Fortson"
1 result found.
Danny Fortson
Results for Danny Fortson:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Rubén Garcés"
1 result found.
Ruben Garces
Results for Ruben Garces:

You searched for "Chris Garner"
10 results found.
0: Chris Garner
1: Chris Carr
2: Chris Porter
3: Chris Engler
4: Chuck Gardner
5: Chris Harris
6: Chris Herren
7: Chris Hunter
8: Chris Webber
9: Chris Gatling
Pick one: 0
Results for Chris Garner:

You searched for "Larry Hughes"
6 results found.
0: Larry Hughes
1: Larry Bunce
2: Larry Fogle
3: Larry Jones
4: Larry Sykes
5: Larry Wright
Pick one: 0
Results for Larry Hughes:

You searched for "Marc Jackson"
24 results found.
0: Marc Jackson
1: Mark Jackson
2: Aaron Jackson
3: Al Jackson
4: Jaren Jackson
5: Jaren Jackson
6: Mike Jackson
7: Myron Jackson
8: Marc Gasol
9: Cedric Jackson
10: Frank Jackson
11: Greg Jackson
12: Jim Jackson
13: Josh Jackson
14: Luke Jackson
15: Luke Jackson
16: Mervin Jackson
17: Phil Jackson
18: Ralph Jackson
19: Tony Jackson
20: Tony Jackson
21: Tracy Jackson
22: Mark Macon
23: Marcus Banks
Pick one: 0
Results for Marc Jackson:

You searched for "Antawn Jamison"
1 result found.
Antawn Jamison
Results for Antawn Jamison:

You searched for "Adam Keefe"
1 result found.
Adam Keefe
Results for Adam Keefe:

You searched for "Randy Livingston"
2 results found.
0: Randy Livingston
1: Ron Livingstone
Pick one: 0
Results for Randy Livingston:

You searched for "Paul McPherson"
1 result found.
Paul McPherson
Results for Paul McPherson:

You searched for "Chris Mills"
19 results found.
0: Chris Mills
1: Chris Childs
2: Chris Mihm
3: Chris Mullin
4: Chris Silva
5: Chris King
6: Darius Miles
7: Terry Mills
8: Chris Morris
9: Chris Munk
10: Chris Owens
11: Chris Paul
12: Chris Smith
13: Chris Smith
14: Chris Welp
15: Chris Wilcox
16: Chris Bosh
17: Chris Kaman
18: Chris Quinn
Pick one: 0
Results for Chris Mills:

You searched for "Chris Mullin"
10 results found.
0: Chris Mullin
1: Chris Mills
2: Chris Dudley
3: Chris Duhon
4: Chris Gatling
5: Chris Morris
6: Chris Munk
7: Chris Quinn
8: Chris King
9: Chris Mihm
Pick one: 0
Results for Chris Mullin:

You searched for "Chris Porter"
15 results found.
0: Chris Porter
1: Chris Garner
2: Chris Hunter
3: Chris Anstey
4: Chris Boucher
5: Chris Carr
6: Chris Engler
7: Chris Ford
8: Chris Herren
9: Chris Morris
10: Kevin Porter
11: Kevin Porter
12: Terry Porter
13: Chris Webber
14: Chris Owens
Pick one: 0
Results for Chris Porter:

You searched for "Bob Sura"
26 results found.
0: Bob Sura
1: Bob Shea
2: Bob Ford
3: Rob Kurz
4: Bob Rule
5: Bob Sims
6: Bob Verga
7: Bob Burrow
8: Bob Cousy
9: Bob Doll
10: Bob Duffy
11: Bob Duffy
12: Bob Ferry
13: Bob Love
14: Bob Nash
15: Bob Quick
16: Bob Tough
17: Bob Wood
18: Bob Davis
19: Bob Evans
20: Bob Gross
21: Bob Naber
22: Don Ray
23: Rob Rose
24: Bob Royer
25: Bob Weiss
Pick one: 0
Results for Bob Sura:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-12-06,24-177,GSW,HOME,LAL,W (+3),1,53:00,21,29,...,13,5,2,1,4,2,51,46.0,3,Antawn Jamison
1,2000-12-03,24-174,GSW,AWAY,SEA,L (-16),1,48:00,23,36,...,14,2,3,2,1,2,51,45.2,-16,Antawn Jamison
2,2001-01-18,24-220,GSW,HOME,HOU,L (-8),1,46:42,14,27,...,15,1,1,1,1,4,43,34.8,-4,Antawn Jamison
3,2000-12-30,24-201,GSW,AWAY,VAN,W (+1),1,43:54,12,24,...,18,3,4,0,3,3,35,31.5,9,Antawn Jamison
4,2000-11-10,24-151,GSW,HOME,SAC,L (-7),1,50:42,12,23,...,9,2,5,0,2,4,37,30.8,-13,Antawn Jamison

In [14]:
GSW_2002_gamelog = []


for p in GSW_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2002_gamelog.append(player_log)
GSW_2002_gamelog = pd.concat(GSW_2002_gamelog)    
GSW_2002_gamelogs = GSW_2002_gamelog.copy()
GSW_2002_gamelogs['GAME_SCORE'] = GSW_2002_gamelogs['GAME_SCORE'].astype(float)
GSW_2002_games = GSW_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2002_games_csv = GSW_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2002_games.csv', index=False)
GSW_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2002_games.csv')
GSW_2002_games_proc.head()

You searched for "Gilbert Arenas"
1 result found.
Gilbert Arenas
Results for Gilbert Arenas:

You searched for "Mookie Blaylock"
1 result found.
Mookie Blaylock
Results for Mookie Blaylock:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "Danny Fortson"
1 result found.
Danny Fortson
Results for Danny Fortson:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Dean Garrett"
5 results found.
0: Dean Garrett
1: Diante Garrett
2: Dick Garrett
3: Ken Durrett
4: Kevin Garnett
Pick one: 0
Results for Dean Garrett:

You searched for "Larry Hughes"
6 results found.
0: Larry Hughes
1: Larry Bunce
2: Larry Fogle
3: Larry Jones
4: Larry Sykes
5: Larry Wright
Pick one: 0
Results for Larry Hughes:

You searched for "Marc Jackson"
24 results found.
0: Marc Jackson
1: Mark Jackson
2: Aaron Jackson
3: Al Jackson
4: Jaren Jackson
5: Jaren Jackson
6: Mike Jackson
7: Myron Jackson
8: Marc Gasol
9: Cedric Jackson
10: Frank Jackson
11: Greg Jackson
12: Jim Jackson
13: Josh Jackson
14: Luke Jackson
15: Luke Jackson
16: Mervin Jackson
17: Phil Jackson
18: Ralph Jackson
19: Tony Jackson
20: Tony Jackson
21: Tracy Jackson
22: Mark Macon
23: Marcus Banks
Pick one: 0
Results for Marc Jackson:

You searched for "Antawn Jamison"
1 result found.
Antawn Jamison
Results for Antawn Jamison:

You searched for "Chris Mills"
19 results found.
0: Chris Mills
1: Chris Childs
2: Chris Mihm
3: Chris Mullin
4: Chris Silva
5: Chris King
6: Darius Miles
7: Terry Mills
8: Chris Morris
9: Chris Munk
10: Chris Owens
11: Chris Paul
12: Chris Smith
13: Chris Smith
14: Chris Welp
15: Chris Wilcox
16: Chris Bosh
17: Chris Kaman
18: Chris Quinn
Pick one: 0
Results for Chris Mills:

You searched for "Troy Murphy"
8 results found.
0: Troy Murphy
1: Tod Murphy
2: Erik Murphy
3: Jay Murphy
4: Roy Hurley
5: Dick Murphy
6: John Murphy
7: Tracy Murray
Pick one: 0
Results for Troy Murphy:

You searched for "Dean Oliver"
5 results found.
0: Dean Oliver
1: Brian Oliver
2: Dion Glover
3: John Olive
4: Dean Tolson
Pick one: 0
Results for Dean Oliver:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Bob Sura"
26 results found.
0: Bob Sura
1: Bob Shea
2: Bob Ford
3: Rob Kurz
4: Bob Rule
5: Bob Sims
6: Bob Verga
7: Bob Burrow
8: Bob Cousy
9: Bob Doll
10: Bob Duffy
11: Bob Duffy
12: Bob Ferry
13: Bob Love
14: Bob Nash
15: Bob Quick
16: Bob Tough
17: Bob Wood
18: Bob Davis
19: Bob Evans
20: Bob Gross
21: Bob Naber
22: Don Ray
23: Rob Rose
24: Bob Royer
25: Bob Weiss
Pick one: 0
Results for Bob Sura:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-02-22,21-033,GSW,AWAY,MIL,L (-4),1,42:24,16,22,...,3,5,0,1,1,2,35,30.1,4,Jason Richardson
1,2002-03-21,20-074,GSW,HOME,LAC,L (-20),1,35:06,11,15,...,4,5,3,1,3,4,32,29.7,-15,Gilbert Arenas
2,2002-04-16,21-086,GSW,AWAY,SAC,L (-14),1,40:41,18,28,...,2,2,3,0,3,6,40,27.6,-5,Jason Richardson
3,2002-01-06,25-208,GSW,AWAY,MIA,L (-8),1,39:17,11,18,...,5,0,3,0,1,1,31,26.7,-1,Antawn Jamison
4,2001-11-03,25-144,GSW,AWAY,LAC,W (+2),1,46:16,10,26,...,19,5,1,0,0,1,29,26.6,0,Antawn Jamison

In [17]:
GSW_2003_gamelog = []



for p in GSW_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2003_gamelog.append(player_log)
GSW_2003_gamelog = pd.concat(GSW_2003_gamelog)    
GSW_2003_gamelogs = GSW_2003_gamelog.copy()
GSW_2003_gamelogs['GAME_SCORE'] = GSW_2003_gamelogs['GAME_SCORE'].astype(float)
GSW_2003_games = GSW_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2003_games_csv = GSW_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2003_games.csv', index=False)
GSW_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2003_games.csv')
GSW_2003_games_proc.head()

You searched for "Gilbert Arenas"
1 result found.
Gilbert Arenas
Results for Gilbert Arenas:

You searched for "Earl Boykins"
1 result found.
Earl Boykins
Results for Earl Boykins:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "Danny Fortson"
1 result found.
Danny Fortson
Results for Danny Fortson:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "A.J. Guyton"
1 result found.
A.J. Guyton
Results for A.J. Guyton:

You searched for "Antawn Jamison"
1 result found.
Antawn Jamison
Results for Antawn Jamison:

You searched for "Chris Mills"
19 results found.
0: Chris Mills
1: Chris Childs
2: Chris Mihm
3: Chris Mullin
4: Chris Silva
5: Chris King
6: Darius Miles
7: Terry Mills
8: Chris Morris
9: Chris Munk
10: Chris Owens
11: Chris Paul
12: Chris Smith
13: Chris Smith
14: Chris Welp
15: Chris Wilcox
16: Chris Bosh
17: Chris Kaman
18: Chris Quinn
Pick one: 0
Results for Chris Mills:

You searched for "Troy Murphy"
8 results found.
0: Troy Murphy
1: Tod Murphy
2: Erik Murphy
3: Jay Murphy
4: Roy Hurley
5: Dick Murphy
6: John Murphy
7: Tracy Murray
Pick one: 0
Results for Troy Murphy:

You searched for "Dean Oliver"
5 results found.
0: Dean Oliver
1: Brian Oliver
2: Dion Glover
3: John Olive
4: Dean Tolson
Pick one: 0
Results for Dean Oliver:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Guy Rucker"
4 results found.
0: Guy Rucker
1: Guy Rodgers
2: Al Tucker
3: Jim Tucker
Pick one: 0
Results for Guy Rucker:

You searched for "Bob Sura"
26 results found.
0: Bob Sura
1: Bob Shea
2: Bob Ford
3: Rob Kurz
4: Bob Rule
5: Bob Sims
6: Bob Verga
7: Bob Burrow
8: Bob Cousy
9: Bob Doll
10: Bob Duffy
11: Bob Duffy
12: Bob Ferry
13: Bob Love
14: Bob Nash
15: Bob Quick
16: Bob Tough
17: Bob Wood
18: Bob Davis
19: Bob Evans
20: Bob Gross
21: Bob Naber
22: Don Ray
23: Rob Rose
24: Bob Royer
25: Bob Weiss
Pick one: 0
Results for Bob Sura:

You searched for "Óscar Torres"
1 result found.
Oscar Torres
Results for Oscar Torres:

You searched for "Jiří Welsch"
2 results found.
0: Jiri Welsch
1: Jim Walsh
Pick one: 0
Results for Jiri Welsch:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-04-06,26-298,GSW,HOME,DEN,W (+7),1,42:59,17,24,...,14,1,2,1,2,2,41,37.0,10,Antawn Jamison
1,2002-12-18,26-189,GSW,HOME,NOH,W (+5),1,44:09,13,22,...,13,1,1,1,1,3,35,31.3,2,Antawn Jamison
2,2003-03-08,26-269,GSW,AWAY,MIL,L (-5),1,41:37,14,21,...,4,2,0,0,1,2,40,30.9,-10,Antawn Jamison
3,2003-03-23,26-284,GSW,HOME,WAS,W (+6),1,44:58,14,24,...,11,3,2,0,3,1,37,30.6,7,Antawn Jamison
4,2002-11-09,20-307,GSW,AWAY,HOU,L (-7),1,40:06,11,15,...,6,10,1,0,0,5,28,30.1,8,Gilbert Arenas

In [21]:


GSW_2004_gamelog = []



for p in GSW_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2004_gamelog.append(player_log)
GSW_2004_gamelog = pd.concat(GSW_2004_gamelog)    
GSW_2004_gamelogs = GSW_2004_gamelog.copy()
GSW_2004_gamelogs['GAME_SCORE'] = GSW_2004_gamelogs['GAME_SCORE'].astype(float)
GSW_2004_games = GSW_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2004_games_csv = GSW_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2004_games.csv', index=False)
GSW_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2004_games.csv')
GSW_2004_games_proc.head()

You searched for "J.R. Bremer"
3 results found.
0: J.R. Bremer
1: Jim Brewer
2: J.R. Reid
Pick one: 0
Results for J.R. Bremer:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Calbert Cheaney"
1 result found.
Calbert Cheaney
Results for Calbert Cheaney:

You searched for "Speedy Claxton"
1 result found.
Speedy Claxton
Results for Speedy Claxton:

You searched for "Erick Dampier"
2 results found.
0: Erick Dampier
1: Erik Daniels
Pick one: 0
Results for Erick Dampier:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Avery Johnson"
27 results found.
0: Avery Johnson
1: Amir Johnson
2: Andy Johnson
3: Dave Johnson
4: Larry Johnson
5: Larry Johnson
6: Trey Johnson
7: Alize Johnson
8: Armon Johnson
9: Arnie Johnson
10: Cameron Johnson
11: Clay Johnson
12: Dakari Johnson
13: Darryl Johnson
14: Ed Johnson
15: Eric Johnson
16: Ivan Johnson
17: James Johnson
18: Joe Johnson
19: Ken Johnson
20: Ken Johnson
21: Lee Johnson
22: Neil Johnson
23: Omari Johnson
24: Steve Johnson
25: Stew Johnson
26: Tyler Johnson
Pick one: 0
Results for Avery Johnson:

You searched for "Popeye Jones"
6 results found.
0: Popeye Jones
1: Bobby Jones
2: Bobby Jones
3: Ozell Jones
4: Perry Jones
5: Steve Jones
Pick one: 0
Results for Popeye Jones:

You searched for "Sean Lampley"
2 results found.
0: Sean Lampley
1: Jim Lampley
Pick one: 0
Results for Sean Lampley:

You searched for "Dan Langhi"
6 results found.
0: Dan Langhi
1: Dan King
2: James Lang
3: Grant Long
4: Shawn Long
5: Dan Tieman
Pick one: 0
Results for Dan Langhi:

You searched for "Rusty LaRue"
1 result found.
Rusty LaRue
Results for Rusty LaRue:

You searched for "Troy Murphy"
8 results found.
0: Troy Murphy
1: Tod Murphy
2: Erik Murphy
3: Jay Murphy
4: Roy Hurley
5: Dick Murphy
6: John Murphy
7: Tracy Murray
Pick one: 0
Results for Troy Murphy:

You searched for "Cherokee Parks"
2 results found.
0: Cherokee Parks
1: Charles Parks
Pick one: 0
Results for Cherokee Parks:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Clifford Robinson"
2 results found.
0: Clifford Robinson
1: Cliff Robinson
Pick one: 0
Results for Clifford Robinson:

You searched for "Nick Van Exel"
1 result found.
Nick Van Exel
Results for Nick Van Exel:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-01-15,37-030,GSW,HOME,CLE,W (+17),1,42:19,11,19,...,8,4,1,3,0,2,35,34.0,26,Clifford Robinson
1,2004-02-11,26-285,GSW,HOME,PHO,W (+11),1,44:34,10,14,...,8,3,2,1,2,4,32,30.2,13,Brian Cardinal
2,2004-04-03,23-074,GSW,AWAY,CLE,W (+3),1,42:12,12,18,...,4,5,1,2,3,2,35,29.7,0,Jason Richardson
3,2004-02-27,28-228,GSW,AWAY,MIN,L (-10),1,37:55,10,14,...,19,2,0,3,2,2,24,27.4,-9,Erick Dampier
4,2004-01-24,23-004,GSW,AWAY,POR,W (+18),1,40:44,12,17,...,5,4,2,1,4,1,31,26.5,13,Jason Richardson

In [24]:


GSW_2005_gamelog = []

for p in GSW_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2005_gamelog.append(player_log)
GSW_2005_gamelog = pd.concat(GSW_2005_gamelog)    
GSW_2005_gamelogs = GSW_2005_gamelog.copy()
GSW_2005_gamelogs['GAME_SCORE'] = GSW_2005_gamelogs['GAME_SCORE'].astype(float)
GSW_2005_games = GSW_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2005_games_csv = GSW_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2005_games.csv', index=False)
GSW_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2005_games.csv')
GSW_2005_games_proc.head()

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Žarko Čabarkapa"
1 result found.
Zarko Cabarkapa
Results for Zarko Cabarkapa:

You searched for "Calbert Cheaney"
1 result found.
Calbert Cheaney
Results for Calbert Cheaney:

You searched for "Speedy Claxton"
1 result found.
Speedy Claxton
Results for Speedy Claxton:

You searched for "Baron Davis"
22 results found.
0: Baron Davis
1: Ron Davis
2: Ben Davis
3: Bob Davis
4: Brad Davis
5: Brian Davis
6: Harry Davis
7: Mark Davis
8: Mark Davis
9: Warren Davis
10: Bob Davies
11: Brandon Davies
12: Bill Davis
13: Dale Davis
14: Glen Davis
15: Paul Davis
16: Ralph Davis
17: Red Davis
18: Terry Davis
19: Walt Davis
20: Byron Irvin
21: Aaron James
Pick one: 0
Results for Baron Davis:

You searched for "Dale Davis"
29 results found.
0: Dale Davis
1: Walt Davis
2: Bill Davis
3: Glen Davis
4: Lee Davis
5: Mark Davis
6: Mark Davis
7: Mel Davis
8: Mike Davis
9: Mike Davis
10: Paul Davis
11: Ralph Davis
12: Tyler Davis
13: Walter Davis
14: Dale Ellis
15: Baron Davis
16: Ben Davis
17: Bob Davis
18: Brad Davis
19: Charles Davis
20: Charlie Davis
21: Ed Davis
22: Harry Davis
23: Jim Davis
24: Josh Davis
25: Red Davis
26: Ron Davis
27: Warren Davis
28: Willie Davis
Pick one: 0
Results for Dale Davis:

You searched for "Derek Fisher"
2 results found.
0: Derek Fisher
1: Derek Harper
Pick one: 0
Results for Derek Fisher:

You searched for "Luis Flores"
1 result found.
Luis Flores
Results for Luis Flores:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Troy Murphy"
8 results found.
0: Troy Murphy
1: Tod Murphy
2: Erik Murphy
3: Jay Murphy
4: Roy Hurley
5: Dick Murphy
6: John Murphy
7: Tracy Murray
Pick one: 0
Results for Troy Murphy:

You searched for "Eduardo Nájera"
1 result found.
Eduardo Najera
Results for Eduardo Najera:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Clifford Robinson"
2 results found.
0: Clifford Robinson
1: Cliff Robinson
Pick one: 0
Results for Clifford Robinson:

You searched for "Ansu Sesay"
1 result found.
Ansu Sesay
Results for Ansu Sesay:

You searched for "Nikoloz Tskitishvili"
1 result found.
Nikoloz Tskitishvili
Results for Nikoloz Tskitishvili:

You searched for "Rodney White"
9 results found.
0: Rodney White
1: Randy White
2: Rory White
3: Royce White
4: Rudy White
5: Tony White
6: Rodney Hood
7: Andrew White
8: Coby White
Pick one: 0
Results for Rodney White:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-04-05,25-357,GSW,HOME,HOU,W (+5),1,38:28,11,20,...,5,13,5,0,3,1,40,42.2,4,Baron Davis
1,2005-01-17,23-363,GSW,HOME,DEN,W (+10),1,39:14,17,30,...,3,8,3,1,1,1,42,37.0,18,Jason Richardson
2,2005-03-17,24-056,GSW,HOME,SAC,W (+3),1,43:19,16,28,...,10,5,2,1,2,2,40,34.0,13,Jason Richardson
3,2005-03-04,24-043,GSW,AWAY,WAS,W (+13),1,40:20,12,19,...,8,4,2,3,3,1,34,32.2,19,Jason Richardson
4,2004-11-05,25-206,NOH,HOME,ORL,L (-1),1,36:54,15,26,...,6,7,2,1,1,3,36,30.2,7,Baron Davis

In [27]:

GSW_2006_gamelog = []

for p in GSW_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2006_gamelog.append(player_log)
GSW_2006_gamelog = pd.concat(GSW_2006_gamelog)    
GSW_2006_gamelogs = GSW_2006_gamelog.copy()
GSW_2006_gamelogs['GAME_SCORE'] = GSW_2006_gamelogs['GAME_SCORE'].astype(float)
GSW_2006_games = GSW_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2006_games_csv = GSW_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2006_games.csv', index=False)
GSW_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2006_games.csv')
GSW_2006_games_proc.head()

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Will Bynum"
3 results found.
0: Will Bynum
1: Will Barton
2: Bill Ebben
Pick one: 0
Results for Will Bynum:

You searched for "Žarko Čabarkapa"
1 result found.
Zarko Cabarkapa
Results for Zarko Cabarkapa:

You searched for "Calbert Cheaney"
1 result found.
Calbert Cheaney
Results for Calbert Cheaney:

You searched for "Baron Davis"
22 results found.
0: Baron Davis
1: Ron Davis
2: Ben Davis
3: Bob Davis
4: Brad Davis
5: Brian Davis
6: Harry Davis
7: Mark Davis
8: Mark Davis
9: Warren Davis
10: Bob Davies
11: Brandon Davies
12: Bill Davis
13: Dale Davis
14: Glen Davis
15: Paul Davis
16: Ralph Davis
17: Red Davis
18: Terry Davis
19: Walt Davis
20: Byron Irvin
21: Aaron James
Pick one: 0
Results for Baron Davis:

You searched for "Ike Diogu"
4 results found.
0: Ike Diogu
1: Ike Anigbogu
2: Mike Davis
3: Mike Davis
Pick one: 0
Results for Ike Diogu:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Derek Fisher"
2 results found.
0: Derek Fisher
1: Derek Harper
Pick one: 0
Results for Derek Fisher:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Aaron Miles"
7 results found.
0: Aaron Miles
1: Aaron James
2: Harry Giles
3: Tharon Mayes
4: Aaron McKie
5: Darius Miles
6: Ron Riley
Pick one: 0
Results for Aaron Miles:

You searched for "Troy Murphy"
8 results found.
0: Troy Murphy
1: Tod Murphy
2: Erik Murphy
3: Jay Murphy
4: Roy Hurley
5: Dick Murphy
6: John Murphy
7: Tracy Murray
Pick one: 0
Results for Troy Murphy:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Chris Taft"
15 results found.
0: Chris Taft
1: Chris Babb
2: Chris Carr
3: Chris Jent
4: Chris Paul
5: Chris Bosh
6: Chris Ford
7: Chris Kaman
8: Chris King
9: Chris Mihm
10: Chris Munk
11: Chris Smith
12: Chris Smith
13: Chris Welp
14: Chris Silva
Pick one: 0
Results for Chris Taft:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-01-28,26-290,GSW,HOME,POR,W (+15),1,39:27,9,15,...,8,16,2,0,1,0,29,36.3,17,Baron Davis
1,2006-03-23,25-062,GSW,AWAY,DAL,W (+1),1,40:47,14,23,...,3,4,3,1,1,1,40,35.5,3,Jason Richardson
2,2005-12-28,24-342,GSW,HOME,BOS,W (+2),1,42:20,16,24,...,4,4,5,1,2,2,36,32.9,4,Jason Richardson
3,2006-03-07,25-046,GSW,AWAY,ATL,L (-7),1,42:52,16,29,...,7,4,2,1,2,4,42,31.7,-8,Jason Richardson
4,2006-03-10,25-049,GSW,AWAY,MIA,W (+5),1,38:47,17,26,...,6,3,0,0,3,1,44,31.1,3,Jason Richardson

In [32]:

GSW_2007_gamelog = []

for p in GSW_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2007_gamelog.append(player_log)
GSW_2007_gamelog = pd.concat(GSW_2007_gamelog)    
GSW_2007_gamelogs = GSW_2007_gamelog.copy()
GSW_2007_gamelogs['GAME_SCORE'] = GSW_2007_gamelogs['GAME_SCORE'].astype(float)
GSW_2007_games = GSW_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2007_games_csv = GSW_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2007_games.csv', index=False)
GSW_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2007_games.csv')
GSW_2007_games_proc.head()

You searched for "Kelenna Azubuike"
1 result found.
Kelenna Azubuike
Results for Kelenna Azubuike:

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Baron Davis"
22 results found.
0: Baron Davis
1: Ron Davis
2: Ben Davis
3: Bob Davis
4: Brad Davis
5: Brian Davis
6: Harry Davis
7: Mark Davis
8: Mark Davis
9: Warren Davis
10: Bob Davies
11: Brandon Davies
12: Bill Davis
13: Dale Davis
14: Glen Davis
15: Paul Davis
16: Ralph Davis
17: Red Davis
18: Terry Davis
19: Walt Davis
20: Byron Irvin
21: Aaron James
Pick one: 0
Results for Baron Davis:

You searched for "Ike Diogu"
4 results found.
0: Ike Diogu
1: Ike Anigbogu
2: Mike Davis
3: Mike Davis
Pick one: 0
Results for Ike Diogu:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Al Harrington"
5 results found.
0: Al Harrington
1: Adam Harrington
2: Bob Carrington
3: Al Hairston
4: Matt Harpring
Pick one: 0
Results for Al Harrington:

You searched for "Stephen Jackson"
3 results found.
0: Stephen Jackson
1: Stanley Jackson
2: Stephen Wilson
Pick one: 0
Results for Stephen Jackson:

You searched for "Šarūnas Jasikevičius"
1 result found.
Sarunas Jasikevicius
Results for Sarunas Jasikevicius:

You searched for "Renaldo Major"
1 result found.
Renaldo Major
Results for Renaldo Major:

You searched for "Keith McLeod"
4 results found.
0: Keith McLeod
1: Keith McCord
2: Keith Closs
3: Keith Lee
Pick one: 0
Results for Keith McLeod:

You searched for "Troy Murphy"
8 results found.
0: Troy Murphy
1: Tod Murphy
2: Erik Murphy
3: Jay Murphy
4: Roy Hurley
5: Dick Murphy
6: John Murphy
7: Tracy Murray
Pick one: 0
Results for Troy Murphy:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "Josh Powell"
7 results found.
0: Josh Powell
1: Josh Hall
2: Josh Howard
3: Kasib Powell
4: Roger Powell
5: Josh Selby
6: Josh Okogie
Pick one: 0
Results for Josh Powell:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Anthony Roberson"
4 results found.
0: Anthony Roberson
1: Anthony Roberts
2: Anthony Johnson
3: Tony Robertson
Pick one: 0
Results for Anthony Roberson:

You searched for "Dajuan Wagner"
2 results found.
0: Dajuan Wagner
1: Danny Wagner
Pick one: 0
Results for Dajuan Wagner:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-03-23,27-344,GSW,HOME,WAS,W (+7),1,37:40,10,16,...,9,15,4,0,3,4,34,38.2,19,Baron Davis
1,2006-11-09,27-210,GSW,HOME,NOK,W (+5),1,43:34,11,17,...,4,9,3,0,0,3,36,36.2,11,Baron Davis
2,2007-04-15,26-085,GSW,HOME,MIN,W (+13),1,37:07,11,17,...,12,7,3,1,1,2,32,36.1,41,Jason Richardson
3,2006-11-16,27-217,GSW,HOME,SAC,W (+12),1,45:16,12,20,...,8,18,3,0,8,5,36,35.2,16,Baron Davis
4,2006-12-22,27-253,GSW,AWAY,ORL,W (+9),1,42:56,11,23,...,2,9,4,1,2,1,38,34.7,3,Baron Davis

In [40]:

GSW_2008_gamelog = []

for p in GSW_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2008_gamelog.append(player_log)
GSW_2008_gamelog = pd.concat(GSW_2008_gamelog)    
GSW_2008_gamelogs = GSW_2008_gamelog.copy()
GSW_2008_gamelogs['GAME_SCORE'] = GSW_2008_gamelogs['GAME_SCORE'].astype(float)
GSW_2008_games = GSW_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2008_games_csv = GSW_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2008_games.csv', index=False)
GSW_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2008_games.csv')
GSW_2008_games_proc.head()

You searched for "Kelenna Azubuike"
1 result found.
Kelenna Azubuike
Results for Kelenna Azubuike:

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Marco Belinelli"
1 result found.
Marco Belinelli
Results for Marco Belinelli:

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Austin Croshere"
1 result found.
Austin Croshere
Results for Austin Croshere:

You searched for "Baron Davis"
22 results found.
0: Baron Davis
1: Ron Davis
2: Ben Davis
3: Bob Davis
4: Brad Davis
5: Brian Davis
6: Harry Davis
7: Mark Davis
8: Mark Davis
9: Warren Davis
10: Bob Davies
11: Brandon Davies
12: Bill Davis
13: Dale Davis
14: Glen Davis
15: Paul Davis
16: Ralph Davis
17: Red Davis
18: Terry Davis
19: Walt Davis
20: Byron Irvin
21: Aaron James
Pick one: 0
Results for Baron Davis:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Al Harrington"
5 results found.
0: Al Harrington
1: Adam Harrington
2: Bob Carrington
3: Al Hairston
4: Matt Harpring
Pick one: 0
Results for Al Harrington:

You searched for "Troy Hudson"
3 results found.
0: Troy Hudson
1: Roy Hinson
2: Lou Hudson
Pick one: 0
Results for Troy Hudson:

You searched for "Stephen Jackson"
3 results found.
0: Stephen Jackson
1: Stanley Jackson
2: Stephen Wilson
Pick one: 0
Results for Stephen Jackson:

You searched for "Stéphane Lasme"
1 result found.
Stephane Lasme
Results for Stephane Lasme:

You searched for "Kosta Perović"
1 result found.
Kosta Perovic
Results for Kosta Perovic:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "C.J. Watson"
6 results found.
0: C.J. Watson
1: D.J. Wilson
2: T.J. Warren
3: Earl Watson
4: Paul Watson
5: C.J. Wilcox
Pick one: 0
Results for C.J. Watson:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-01-07,28-269,GSW,HOME,SAS,W (+9),1,48:02,11,18,...,6,14,1,0,0,2,34,37.2,13,Baron Davis
1,2007-11-23,28-224,GSW,AWAY,WAS,W (+8),1,40:59,11,21,...,11,15,0,0,1,3,33,34.3,19,Baron Davis
2,2008-01-24,22-090,GSW,HOME,NJN,W (+2),1,40:48,13,18,...,4,2,3,0,1,4,39,34.2,7,Monta Ellis
3,2007-11-03,27-259,GSW,AWAY,UTA,L (-23),1,38:30,15,20,...,7,3,2,0,2,4,38,33.4,-11,Al Harrington
4,2008-02-09,22-106,GSW,HOME,SAC,W (+3),1,37:57,12,15,...,9,5,1,0,2,3,34,33.1,7,Monta Ellis

In [41]:

GSW_2009_gamelog = []

for p in GSW_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2009_gamelog.append(player_log)
GSW_2009_gamelog = pd.concat(GSW_2009_gamelog)    
GSW_2009_gamelogs = GSW_2009_gamelog.copy()
GSW_2009_gamelogs['GAME_SCORE'] = GSW_2009_gamelogs['GAME_SCORE'].astype(float)
GSW_2009_games = GSW_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2009_games_csv = GSW_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2009_games.csv', index=False)
GSW_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2009_games.csv')
GSW_2009_games_proc.head()

You searched for "Kelenna Azubuike"
1 result found.
Kelenna Azubuike
Results for Kelenna Azubuike:

You searched for "Marco Belinelli"
1 result found.
Marco Belinelli
Results for Marco Belinelli:

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Jamal Crawford"
3 results found.
0: Jamal Crawford
1: Joe Crawford
2: Jordan Crawford
Pick one: 0
Results for Jamal Crawford:

You searched for "Jermareo Davidson"
1 result found.
Jermareo Davidson
Results for Jermareo Davidson:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Al Harrington"
5 results found.
0: Al Harrington
1: Adam Harrington
2: Bob Carrington
3: Al Hairston
4: Matt Harpring
Pick one: 0
Results for Al Harrington:

You searched for "Stephen Jackson"
3 results found.
0: Stephen Jackson
1: Stanley Jackson
2: Stephen Wilson
Pick one: 0
Results for Stephen Jackson:

You searched for "Rob Kurz"
13 results found.
0: Rob Kurz
1: Bob Sura
2: Bob Ford
3: Ron Horn
4: Coby Karl
5: Red Kerr
6: Ron King
7: Ray Kuka
8: Rob Lock
9: Roy Pugh
10: Rob Rose
11: Bob Rule
12: Ron Baker
Pick one: 0
Results for Rob Kurz:

You searched for "Corey Maggette"
1 result found.
Corey Maggette
Results for Corey Maggette:

You searched for "Anthony Morrow"
10 results found.
0: Anthony Morrow
1: Anthony Brown
2: Anthony Cook
3: Anthony Mason
4: Anthony Bonner
5: Anthony Bowie
6: Anthony Carter
7: Anthony Miller
8: Anthony Parker
9: Anthony Taylor
Pick one: 0
Results for Anthony Morrow:

You searched for "DeMarcus Nelson"
1 result found.
DeMarcus Nelson
Results for DeMarcus Nelson:

You searched for "Anthony Randolph"
1 result found.
Anthony Randolph
Results for Anthony Randolph:

You searched for "Ronny Turiaf"
1 result found.
Ronny Turiaf
Results for Ronny Turiaf:

You searched for "C.J. Watson"
6 results found.
0: C.J. Watson
1: D.J. Wilson
2: T.J. Warren
3: Earl Watson
4: Paul Watson
5: C.J. Wilcox
Pick one: 0
Results for C.J. Watson:

You searched for "Marcus Williams"
10 results found.
0: Marcus Williams
1: Marcus Williams
2: Marvin Williams
3: Aaron Williams
4: Art Williams
5: Charles Williams
6: Earl Williams
7: Gus Williams
8: Matt Williams
9: Ward Williams
Pick one: 0
Results for Marcus Williams:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-12-20,28-275,GSW,AWAY,CHA,W (+7),1,45:51,14,26,...,2,5,0,1,1,2,50,40.0,15,Jamal Crawford
1,2009-02-10,30-311,GSW,HOME,NYK,W (+17),1,47:09,9,20,...,6,10,2,0,0,2,35,35.8,18,Stephen Jackson
2,2009-04-11,24-359,GSW,AWAY,UTA,W (+10),1,39:15,10,16,...,7,9,1,0,4,4,38,35.0,2,C.J. Watson
3,2008-12-01,28-256,GSW,HOME,MIA,L (-1),1,50:23,11,22,...,1,7,0,0,1,0,40,32.8,1,Jamal Crawford
4,2008-12-10,28-297,NYK,AWAY,NJN,W (+12),1,45:42,11,21,...,13,3,2,0,4,4,39,31.5,15,Al Harrington

In [42]:

GSW_2010_gamelog = []

for p in GSW_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2010_gamelog.append(player_log)
GSW_2010_gamelog = pd.concat(GSW_2010_gamelog)    
GSW_2010_gamelogs = GSW_2010_gamelog.copy()
GSW_2010_gamelogs['GAME_SCORE'] = GSW_2010_gamelogs['GAME_SCORE'].astype(float)
GSW_2010_games = GSW_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2010_games_csv = GSW_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2010_games.csv', index=False)
GSW_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2010_games.csv')
GSW_2010_games_proc.head()

You searched for "Kelenna Azubuike"
1 result found.
Kelenna Azubuike
Results for Kelenna Azubuike:

You searched for "Raja Bell"
2 results found.
0: Raja Bell
1: Troy Bell
Pick one: 0
Results for Raja Bell:

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Devean George"
1 result found.
Devean George
Results for Devean George:

You searched for "Chris Hunter"
14 results found.
0: Chris Hunter
1: Cedric Hunter
2: Chris Porter
3: Chris Anstey
4: Chris Boucher
5: Chris Dudley
6: Chris Engler
7: Chris Garner
8: Chris Herren
9: Les Hunter
10: Chris Jent
11: Chris Munk
12: Chris Webber
13: Chris Mullin
Pick one: 0
Results for Chris Hunter:

You searched for "Stephen Jackson"
3 results found.
0: Stephen Jackson
1: Stanley Jackson
2: Stephen Wilson
Pick one: 0
Results for Stephen Jackson:

You searched for "Coby Karl"
3 results found.
0: Coby Karl
1: Cory Carr
2: Rob Kurz
Pick one: 0
Results for Coby Karl:

You searched for "Acie Law"
3 results found.
0: Acie Law
1: Acie Earl
2: Vic Law
Pick one: 0
Results for Acie Law:

You searched for "Corey Maggette"
1 result found.
Corey Maggette
Results for Corey Maggette:

You searched for "Cartier Martin"
5 results found.
0: Cartier Martin
1: Caleb Martin
2: Darrick Martin
3: LaRue Martin
4: Slater Martin
Pick one: 0
Results for Cartier Martin:

You searched for "Mikki Moore"
2 results found.
0: Mikki Moore
1: Jackie Moore
Pick one: 0
Results for Mikki Moore:

You searched for "Anthony Morrow"
10 results found.
0: Anthony Morrow
1: Anthony Brown
2: Anthony Cook
3: Anthony Mason
4: Anthony Bonner
5: Anthony Bowie
6: Anthony Carter
7: Anthony Miller
8: Anthony Parker
9: Anthony Taylor
Pick one: 0
Results for Anthony Morrow:

You searched for "Vladimir Radmanović"
1 result found.
Vladimir Radmanovic
Results for Vladimir Radmanovic:

You searched for "Anthony Randolph"
1 result found.
Anthony Randolph
Results for Anthony Randolph:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

You searched for "Ronny Turiaf"
1 result found.
Ronny Turiaf
Results for Ronny Turiaf:

You searched for "C.J. Watson"
6 results found.
0: C.J. Watson
1: D.J. Wilson
2: T.J. Warren
3: Earl Watson
4: Paul Watson
5: C.J. Wilcox
Pick one: 0
Results for C.J. Watson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-04-14,22-031,GSW,AWAY,POR,W (+6),1,48:00,13,25,...,9,8,2,1,2,0,42,39.9,6,Stephen Curry
1,2010-01-12,31-282,CHA,HOME,HOU,W (+8),1,43:17,15,22,...,8,3,3,0,2,4,43,37.9,12,Stephen Jackson
2,2010-03-13,21-364,GSW,HOME,TOR,W (+12),1,42:21,13,21,...,6,10,4,1,2,1,35,37.4,6,Stephen Curry
3,2010-02-17,25-306,GSW,HOME,SAC,W (+32),1,43:23,16,23,...,7,6,2,0,1,0,40,36.8,34,C.J. Watson
4,2009-11-25,24-030,GSW,AWAY,SAS,L (-14),1,44:22,16,25,...,4,4,3,1,4,2,42,33.8,-21,Monta Ellis

In [47]:

GSW_2011_gamelog = []

for p in GSW_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2011_gamelog.append(player_log)
GSW_2011_gamelog = pd.concat(GSW_2011_gamelog)    
GSW_2011_gamelogs = GSW_2011_gamelog.copy()
GSW_2011_gamelogs['GAME_SCORE'] = GSW_2011_gamelogs['GAME_SCORE'].astype(float)
GSW_2011_games = GSW_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2011_games_csv = GSW_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2011_games.csv', index=False)
GSW_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2011_games.csv')
GSW_2011_games_proc.head()

You searched for "Jeff Adrien"
10 results found.
0: Jeff Adrien
1: Jeff Ayres
2: Jeff Green
3: Jeff Martin
4: Jeff Turner
5: Jeff Grayer
6: Jeff Malone
7: Jeff Ruland
8: Jeff Sanders
9: Jeff Taylor
Pick one: 0
Results for Jeff Adrien:

You searched for "Lou Amundson"
2 results found.
0: Lou Amundson
1: Lou Hudson
Pick one: 0
Results for Lou Amundson:

You searched for "Charlie Bell"
6 results found.
0: Charlie Bell
1: Charlie Black
2: Charlie Brown
3: Charlie Paulk
4: Charlie Tyra
5: Charlie Ward
Pick one: 0
Results for Charlie Bell:

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Rodney Carney"
3 results found.
0: Rodney Carney
1: Rodney McCray
2: Rodney Monroe
Pick one: 0
Results for Rodney Carney:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Dan Gadzuric"
1 result found.
Dan Gadzuric
Results for Dan Gadzuric:

You searched for "Acie Law"
3 results found.
0: Acie Law
1: Acie Earl
2: Vic Law
Pick one: 0
Results for Acie Law:

You searched for "Jeremy Lin"
5 results found.
0: Jeremy Lin
1: Jeremy Lamb
2: Jeremy Evans
3: Jerome Lane
4: Jeremy Tyler
Pick one: 0
Results for Jeremy Lin:

You searched for "Vladimir Radmanović"
1 result found.
Vladimir Radmanovic
Results for Vladimir Radmanovic:

You searched for "Al Thornton"
7 results found.
0: Al Thornton
1: Bob Thornton
2: Al Hairston
3: Ed Horton
4: Dallas Thornton
5: Mel Thurston
6: Al Horford
Pick one: 0
Results for Al Thornton:

You searched for "Ekpe Udoh"
1 result found.
Ekpe Udoh
Results for Ekpe Udoh:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

You searched for "Dorell Wright"
2 results found.
0: Dorell Wright
1: Delon Wright
Pick one: 0
Results for Dorell Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-12-20,25-055,GSW,HOME,HOU,L (-9),1,41:54,15,20,...,1,7,3,0,3,4,44,38.4,-8,Monta Ellis
1,2011-03-11,25-136,GSW,HOME,ORL,W (+3),1,53:00,14,24,...,6,11,4,1,3,2,39,37.8,3,Monta Ellis
2,2010-10-27,25-001,GSW,HOME,HOU,W (+4),1,39:45,18,24,...,3,2,2,0,1,4,46,36.9,9,Monta Ellis
3,2011-03-27,25-152,GSW,HOME,WAS,W (+10),1,48:00,14,24,...,7,13,0,0,2,4,37,33.8,10,Monta Ellis
4,2011-03-04,25-129,GSW,AWAY,BOS,L (-4),1,44:29,13,24,...,6,4,1,1,2,2,41,32.5,3,Monta Ellis

In [52]:

GSW_2012_gamelog = []

for p in GSW_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2012_gamelog.append(player_log)
GSW_2012_gamelog = pd.concat(GSW_2012_gamelog)    
GSW_2012_gamelogs = GSW_2012_gamelog.copy()
GSW_2012_gamelogs['GAME_SCORE'] = GSW_2012_gamelogs['GAME_SCORE'].astype(float)
GSW_2012_games = GSW_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2012_games_csv = GSW_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2012_games.csv', index=False)
GSW_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2012_games.csv')
GSW_2012_games_proc.head()

You searched for "Earl Barron"
10 results found.
0: Earl Barron
1: Earl Watson
2: Dana Barros
3: Will Barton
4: Carl Braun
5: Earl Cureton
6: Earl Monroe
7: Earl Shannon
8: Earl Gardner
9: Earl Jones
Pick one: 0
Results for Earl Barron:

You searched for "Keith Benson"
8 results found.
0: Keith Benson
1: Kent Benson
2: Keith Herron
3: Keith Edmonson
4: Keith Owens
5: Keith Bogans
6: Keith Booth
7: Keith Askins
Pick one: 0
Results for Keith Benson:

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Kwame Brown"
9 results found.
0: Kwame Brown
1: Andre Brown
2: Bruce Brown
3: Damone Brown
4: Dee Brown
5: Dee Brown
6: Mike Brown
7: Stan Brown
8: Jim Browne
Pick one: 0
Results for Kwame Brown:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Monta Ellis"
5 results found.
0: Monta Ellis
1: Monti Davis
2: Bo Ellis
3: Boo Ellis
4: Joe Ellis
Pick one: 0
Results for Monta Ellis:

You searched for "Mickell Gladness"
1 result found.
Mickell Gladness
Results for Mickell Gladness:

You searched for "Richard Jefferson"
2 results found.
0: Richard Jefferson
1: Richard Anderson
Pick one: 0
Results for Richard Jefferson:

You searched for "Charles Jenkins"
5 results found.
0: Charles Jenkins
1: Charles Jones
2: Charles Jones
3: Charles Jones
4: Charles Johnson
Pick one: 0
Results for Charles Jenkins:

You searched for "Dominic McGuire"
1 result found.
Dominic McGuire
Results for Dominic McGuire:

You searched for "Mikki Moore"
2 results found.
0: Mikki Moore
1: Jackie Moore
Pick one: 0
Results for Mikki Moore:

You searched for "Nate Robinson"
12 results found.
0: Nate Robinson
1: James Robinson
2: Wayne Robinson
3: Nate Hinton
4: Nate Johnston
5: David Robinson
6: Eddie Robinson
7: Jackie Robinson
8: Jamal Robinson
9: Larry Robinson
10: Ronnie Robinson
11: Samuel Robinson
Pick one: 0
Results for Nate Robinson:

You searched for "Brandon Rush"
4 results found.
0: Brandon Rush
1: Brandon Bass
2: Brandon Roy
3: Brandon Paul
Pick one: 0
Results for Brandon Rush:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Klay Thompson"
7 results found.
0: Klay Thompson
1: Billy Thompson
2: Corny Thompson
3: Jack Thompson
4: John Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Klay Thompson:

You searched for "Jeremy Tyler"
4 results found.
0: Jeremy Tyler
1: Terry Tyler
2: Jeremy Lin
3: Jeremy Lamb
Pick one: 0
Results for Jeremy Tyler:

You searched for "Ekpe Udoh"
1 result found.
Ekpe Udoh
Results for Ekpe Udoh:

You searched for "Chris Wright"
12 results found.
0: Chris Wright
1: Chris Wright
2: Chris Mihm
3: Chris Smith
4: Chris Smith
5: Brad Wright
6: Howie Wright
7: Larry Wright
8: Leroy Wright
9: Chris Webber
10: Chris Harris
11: Chris Morris
Pick one: 0
Results for Chris Wright:

You searched for "Dorell Wright"
2 results found.
0: Dorell Wright
1: Delon Wright
Pick one: 0
Results for Dorell Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-02-07,26-104,GSW,HOME,OKC,L (-3),1,41:45,18,29,...,7,2,2,1,3,2,48,37.3,5,Monta Ellis
1,2012-02-09,23-332,GSW,AWAY,DEN,W (+8),1,35:55,13,17,...,7,7,0,2,1,3,36,34.3,15,Stephen Curry
2,2012-01-25,23-317,GSW,HOME,POR,W (+8),1,37:54,12,19,...,6,7,4,0,1,0,32,32.8,7,Stephen Curry
3,2012-02-02,23-325,GSW,HOME,UTA,W (+18),1,38:15,10,14,...,5,12,3,0,3,4,29,31.1,18,Stephen Curry
4,2012-04-11,26-168,MIL,HOME,NYK,L (-4),1,40:44,14,25,...,6,10,4,0,5,2,35,29.7,-8,Monta Ellis

In [57]:
GSW_2013_gamelog = []

for p in GSW_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2013_gamelog.append(player_log)
GSW_2013_gamelog = pd.concat(GSW_2013_gamelog)    
GSW_2013_gamelogs = GSW_2013_gamelog.copy()
GSW_2013_gamelogs['GAME_SCORE'] = GSW_2013_gamelogs['GAME_SCORE'].astype(float)
GSW_2013_games = GSW_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2013_games_csv = GSW_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2013_games.csv', index=False)
GSW_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2013_games.csv')
GSW_2013_games_proc.head()

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Kent Bazemore"
1 result found.
Kent Bazemore
Results for Kent Bazemore:

You searched for "Andris Biedriņš"
1 result found.
Andris Biedrins
Results for Andris Biedrins:

You searched for "Andrew Bogut"
4 results found.
0: Andrew Bogut
1: Andrew Bynum
2: Andrew Toney
3: Andrew Gaze
Pick one: 0
Results for Andrew Bogut:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Festus Ezeli"
1 result found.
Festus Ezeli
Results for Festus Ezeli:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Jarrett Jack"
1 result found.
Jarrett Jack
Results for Jarrett Jack:

You searched for "Richard Jefferson"
2 results found.
0: Richard Jefferson
1: Richard Anderson
Pick one: 0
Results for Richard Jefferson:

You searched for "Charles Jenkins"
5 results found.
0: Charles Jenkins
1: Charles Jones
2: Charles Jones
3: Charles Jones
4: Charles Johnson
Pick one: 0
Results for Charles Jenkins:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Scott Machado"
1 result found.
Scott Machado
Results for Scott Machado:

You searched for "Brandon Rush"
4 results found.
0: Brandon Rush
1: Brandon Bass
2: Brandon Roy
3: Brandon Paul
Pick one: 0
Results for Brandon Rush:

You searched for "Malcolm Thomas"
1 result found.
Malcolm Thomas
Results for Malcolm Thomas:

You searched for "Klay Thompson"
7 results found.
0: Klay Thompson
1: Billy Thompson
2: Corny Thompson
3: Jack Thompson
4: John Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Klay Thompson:

You searched for "Jeremy Tyler"
4 results found.
0: Jeremy Tyler
1: Terry Tyler
2: Jeremy Lin
3: Jeremy Lamb
Pick one: 0
Results for Jeremy Tyler:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-02-27,24-350,GSW,AWAY,NYK,L (-4),1,48:00,18,28,...,6,7,3,0,4,3,54,46.1,-4,Stephen Curry
1,2013-04-12,25-029,GSW,AWAY,LAL,L (-2),1,44:17,17,31,...,6,9,3,0,1,3,47,42.2,3,Stephen Curry
2,2014-04-13,26-030,GSW,AWAY,POR,L (-2),1,45:26,16,29,...,1,5,4,0,4,3,47,36.1,6,Stephen Curry
3,2014-01-26,25-318,GSW,HOME,POR,W (+15),1,34:38,13,23,...,7,8,2,0,2,1,38,33.6,12,Stephen Curry
4,2013-03-30,25-016,GSW,HOME,POR,W (+27),1,37:28,14,22,...,5,6,1,0,3,2,39,32.9,15,Stephen Curry

In [62]:
GSW_2014_gamelog = []

for p in GSW_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2014_gamelog.append(player_log)
GSW_2014_gamelog = pd.concat(GSW_2014_gamelog)    
GSW_2014_gamelogs = GSW_2014_gamelog.copy()
GSW_2014_gamelogs['GAME_SCORE'] = GSW_2014_gamelogs['GAME_SCORE'].astype(float)
GSW_2014_games = GSW_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2014_games_csv = GSW_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2014_games.csv', index=False)
GSW_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2014_games.csv')
GSW_2014_games_proc.head()

You searched for "Hilton Armstrong"
1 result found.
Hilton Armstrong
Results for Hilton Armstrong:

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Kent Bazemore"
1 result found.
Kent Bazemore
Results for Kent Bazemore:

You searched for "Steve Blake"
11 results found.
0: Steve Blake
1: Steve Bracey
2: Steve Bardo
3: Steve Burtt
4: Steve Hamer
5: Steve Hawes
6: Steve Hayes
7: Steve Nash
8: Steve Novak
9: Steve Kerr
10: Steven Hill
Pick one: 0
Results for Steve Blake:

You searched for "Andrew Bogut"
4 results found.
0: Andrew Bogut
1: Andrew Bynum
2: Andrew Toney
3: Andrew Gaze
Pick one: 0
Results for Andrew Bogut:

You searched for "MarShon Brooks"
2 results found.
0: MarShon Brooks
1: Aaron Brooks
Pick one: 0
Results for MarShon Brooks:

You searched for "Jordan Crawford"
4 results found.
0: Jordan Crawford
1: Jordan Ford
2: Jamal Crawford
3: Joe Crawford
Pick one: 0
Results for Jordan Crawford:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Dewayne Dedmon"
1 result found.
Dewayne Dedmon
Results for Dewayne Dedmon:

You searched for "Toney Douglas"
4 results found.
0: Toney Douglas
1: John Douglas
2: Leon Douglas
3: Tony Dumas
Pick one: 0
Results for Toney Douglas:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Ognjen Kuzmić"
1 result found.
Ognjen Kuzmic
Results for Ognjen Kuzmic:

You searched for "Nemanja Nedović"
1 result found.
Nemanja Nedovic
Results for Nemanja Nedovic:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Klay Thompson"
7 results found.
0: Klay Thompson
1: Billy Thompson
2: Corny Thompson
3: Jack Thompson
4: John Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Klay Thompson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-04-13,26-030,GSW,AWAY,POR,L (-2),1,45:26,16,29,...,1,5,4,0,4,3,47,36.1,6,Stephen Curry
1,2014-01-26,25-318,GSW,HOME,POR,W (+15),1,34:38,13,23,...,7,8,2,0,2,1,38,33.6,12,Stephen Curry
2,2014-01-17,25-309,GSW,AWAY,OKC,L (-6),1,37:57,11,18,...,3,11,3,0,7,2,37,32.6,-10,Stephen Curry
3,2014-01-31,25-323,GSW,AWAY,UTA,W (+5),1,38:06,14,26,...,2,4,0,0,2,0,44,32.4,15,Stephen Curry
4,2014-04-06,26-023,GSW,HOME,UTA,W (+28),1,29:28,12,18,...,1,16,3,0,5,2,31,31.9,31,Stephen Curry

In [67]:

GSW_2015_gamelog = []

for p in GSW_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2015_gamelog.append(player_log)
GSW_2015_gamelog = pd.concat(GSW_2015_gamelog)    
GSW_2015_gamelogs = GSW_2015_gamelog.copy()
GSW_2015_gamelogs['GAME_SCORE'] = GSW_2015_gamelogs['GAME_SCORE'].astype(float)
GSW_2015_games = GSW_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2015_games_csv = GSW_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2015_games.csv', index=False)
GSW_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2015_games.csv')
GSW_2015_games_proc.head()

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Andrew Bogut"
4 results found.
0: Andrew Bogut
1: Andrew Bynum
2: Andrew Toney
3: Andrew Gaze
Pick one: 0
Results for Andrew Bogut:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Festus Ezeli"
1 result found.
Festus Ezeli
Results for Festus Ezeli:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Justin Holiday"
1 result found.
Justin Holiday
Results for Justin Holiday:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Ognjen Kuzmić"
1 result found.
Ognjen Kuzmic
Results for Ognjen Kuzmic:

You searched for "Shaun Livingston"
2 results found.
0: Shaun Livingston
1: Ron Livingstone
Pick one: 0
Results for Shaun Livingston:

You searched for "Brandon Rush"
4 results found.
0: Brandon Rush
1: Brandon Bass
2: Brandon Roy
3: Brandon Paul
Pick one: 0
Results for Brandon Rush:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Klay Thompson"
7 results found.
0: Klay Thompson
1: Billy Thompson
2: Corny Thompson
3: Jack Thompson
4: John Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Klay Thompson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-01-23,24-349,GSW,HOME,SAC,W (+25),1,32:49,16,25,...,2,5,4,2,4,3,52,44.8,38,Klay Thompson
1,2015-02-04,26-327,GSW,HOME,DAL,W (+14),1,36:57,16,26,...,4,4,1,0,3,3,51,39.2,0,Stephen Curry
2,2015-04-09,27-026,GSW,HOME,POR,W (+11),1,35:13,17,23,...,2,10,0,0,4,2,45,38.9,21,Stephen Curry
3,2014-11-25,26-256,GSW,AWAY,MIA,W (+17),1,37:05,12,19,...,6,7,3,1,2,2,40,38.7,28,Stephen Curry
4,2015-04-13,25-064,GSW,HOME,MEM,W (+4),1,29:58,15,20,...,5,3,1,0,2,0,42,36.6,25,Klay Thompson

In [70]:

GSW_2016_gamelog = []

for p in GSW_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2016_gamelog.append(player_log)
GSW_2016_gamelog = pd.concat(GSW_2016_gamelog)    
GSW_2016_gamelogs = GSW_2016_gamelog.copy()
GSW_2016_gamelogs['GAME_SCORE'] = GSW_2016_gamelogs['GAME_SCORE'].astype(float)
GSW_2016_games = GSW_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2016_games_csv = GSW_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2016_games.csv', index=False)
GSW_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2016_games.csv')
GSW_2016_games_proc.head()

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Andrew Bogut"
4 results found.
0: Andrew Bogut
1: Andrew Bynum
2: Andrew Toney
3: Andrew Gaze
Pick one: 0
Results for Andrew Bogut:

You searched for "Ian Clark"
4 results found.
0: Ian Clark
1: Earl Clark
2: Gary Clark
3: Keon Clark
Pick one: 0
Results for Ian Clark:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Festus Ezeli"
1 result found.
Festus Ezeli
Results for Festus Ezeli:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Shaun Livingston"
2 results found.
0: Shaun Livingston
1: Ron Livingstone
Pick one: 0
Results for Shaun Livingston:

You searched for "Kevon Looney"
5 results found.
0: Kevon Looney
1: Kevin Jones
2: Kevin Loder
3: Kevin Love
4: Devon Dotson
Pick one: 0
Results for Kevon Looney:

You searched for "Brandon Rush"
4 results found.
0: Brandon Rush
1: Brandon Bass
2: Brandon Roy
3: Brandon Paul
Pick one: 0
Results for Brandon Rush:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "Klay Thompson"
7 results found.
0: Klay Thompson
1: Billy Thompson
2: Corny Thompson
3: Jack Thompson
4: John Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Klay Thompson:

You searched for "Anderson Varejão"
1 result found.
Anderson Varejao
Results for Anderson Varejao:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-10-31,27-231,GSW,AWAY,NOP,W (+14),1,35:38,17,27,...,4,9,4,0,2,3,53,49.2,16,Stephen Curry
1,2016-02-25,27-348,GSW,AWAY,ORL,W (+16),1,34:02,20,27,...,7,8,0,1,5,1,51,43.1,11,Stephen Curry
2,2016-01-22,27-314,GSW,HOME,IND,W (+12),1,36:49,11,19,...,10,12,1,0,2,1,39,40.9,22,Stephen Curry
3,2016-04-13,28-030,GSW,HOME,MEM,W (+21),1,29:46,15,24,...,4,6,2,0,2,2,46,40.2,19,Stephen Curry
4,2016-01-27,25-353,GSW,HOME,DAL,W (+20),1,31:33,14,20,...,5,1,0,2,1,1,45,38.8,14,Klay Thompson

In [73]:


GSW_2017_gamelog = []

for p in GSW_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2017_gamelog.append(player_log)
GSW_2017_gamelog = pd.concat(GSW_2017_gamelog)    
GSW_2017_gamelogs = GSW_2017_gamelog.copy()
GSW_2017_gamelogs['GAME_SCORE'] = GSW_2017_gamelogs['GAME_SCORE'].astype(float)
GSW_2017_games = GSW_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2017_games_csv = GSW_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2017_games.csv', index=False)
GSW_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2017_games.csv')
GSW_2017_games_proc.head()

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Ian Clark"
4 results found.
0: Ian Clark
1: Earl Clark
2: Gary Clark
3: Keon Clark
Pick one: 0
Results for Ian Clark:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Kevin Durant"
5 results found.
0: Kevin Durant
1: Devin Durrant
2: Kevin Murphy
3: Ken Durrett
4: Kevin Martin
Pick one: 0
Results for Kevin Durant:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Damian Jones"
14 results found.
0: Damian Jones
1: Damon Jones
2: Damion James
3: DeQuan Jones
4: Mason Jones
5: Alvin Jones
6: Askia Jones
7: Dahntay Jones
8: Jalen Jones
9: James Jones
10: Kevin Jones
11: Robin Jones
12: Sam Jones
13: Wali Jones
Pick one: 0
Results for Damian Jones:

You searched for "Shaun Livingston"
2 results found.
0: Shaun Livingston
1: Ron Livingstone
Pick one: 0
Results for Shaun Livingston:

You searched for "Kevon Looney"
5 results found.
0: Kevon Looney
1: Kevin Jones
2: Kevin Loder
3: Kevin Love
4: Devon Dotson
Pick one: 0
Results for Kevon Looney:

You searched for "Patrick McCaw"
1 result found.
Patrick McCaw
Results for Patrick McCaw:

You searched for "JaVale McGee"
1 result found.
JaVale McGee
Results for JaVale McGee:

You searched for "Zaza Pachulia"
1 result found.
Zaza Pachulia
Results for Zaza Pachulia:

You searched for "Klay Thompson"
7 results found.
0: Klay Thompson
1: Billy Thompson
2: Corny Thompson
3: Jack Thompson
4: John Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Klay Thompson:

You searched for "Anderson Varejão"
1 result found.
Anderson Varejao
Results for Anderson Varejao:

You searched for "Briante Weber"
1 result found.
Briante Weber
Results for Briante Weber:

You searched for "David West"
18 results found.
0: David West
1: David Wear
2: David Lee
3: David Lee
4: David Wesley
5: Mario West
6: David Wood
7: David Benoit
8: Travis Best
9: David Noel
10: David Nwaba
11: David Pope
12: Doug West
13: Mark West
14: David Burns
15: David Cooke
16: David Gaines
17: David Rivers
Pick one: 0
Results for David West:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-12-05,26-301,GSW,HOME,IND,W (+36),1,29:03,21,33,...,2,1,0,0,0,0,60,46.2,37,Klay Thompson
1,2017-01-18,28-111,GSW,HOME,OKC,W (+21),1,33:49,13,16,...,12,4,0,3,2,2,40,40.1,31,Kevin Durant
2,2017-02-01,28-324,GSW,HOME,CHO,W (+15),1,30:16,14,20,...,5,8,3,0,1,2,39,39.3,25,Stephen Curry
3,2017-04-05,29-022,GSW,AWAY,PHO,W (+9),1,35:11,15,25,...,4,11,2,2,3,0,42,38.6,25,Stephen Curry
4,2017-01-28,28-320,GSW,HOME,LAC,W (+46),1,28:57,15,23,...,9,6,0,0,2,1,43,37.4,42,Stephen Curry

In [74]:


GSW_2018_gamelog = []

for p in GSW_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2018_gamelog.append(player_log)
GSW_2018_gamelog = pd.concat(GSW_2018_gamelog)    
GSW_2018_gamelogs = GSW_2018_gamelog.copy()
GSW_2018_gamelogs['GAME_SCORE'] = GSW_2018_gamelogs['GAME_SCORE'].astype(float)
GSW_2018_games = GSW_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2018_games_csv = GSW_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2018_games.csv', index=False)
GSW_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2018_games.csv')
GSW_2018_games_proc.head()

You searched for "Jordan Bell"
10 results found.
0: Jordan Bell
1: Jordan Hill
2: Jordan Bone
3: Jordan Ford
4: Jordan Loyd
5: Jordan Poole
6: Jordan Sibert
7: Jordan Bowden
8: Ryan Kelly
9: Jordan McRae
Pick one: 0
Results for Jordan Bell:

You searched for "Chris Boucher"
5 results found.
0: Chris Boucher
1: Chris Bosh
2: Chris Hunter
3: Chris Porter
4: Chris Herren
Pick one: 0
Results for Chris Boucher:

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Quinn Cook"
3 results found.
0: Quinn Cook
1: Brian Cook
2: Quincy Acy
Pick one: 0
Results for Quinn Cook:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Kevin Durant"
5 results found.
0: Kevin Durant
1: Devin Durrant
2: Kevin Murphy
3: Ken Durrett
4: Kevin Martin
Pick one: 0
Results for Kevin Durant:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Damian Jones"
14 results found.
0: Damian Jones
1: Damon Jones
2: Damion James
3: DeQuan Jones
4: Mason Jones
5: Alvin Jones
6: Askia Jones
7: Dahntay Jones
8: Jalen Jones
9: James Jones
10: Kevin Jones
11: Robin Jones
12: Sam Jones
13: Wali Jones
Pick one: 0
Results for Damian Jones:

You searched for "Shaun Livingston"
2 results found.
0: Shaun Livingston
1: Ron Livingstone
Pick one: 0
Results for Shaun Livingston:

You searched for "Kevon Looney"
5 results found.
0: Kevon Looney
1: Kevin Jones
2: Kevin Loder
3: Kevin Love
4: Devon Dotson
Pick one: 0
Results for Kevon Looney:

You searched for "Patrick McCaw"
1 result found.
Patrick McCaw
Results for Patrick McCaw:

You searched for "JaVale McGee"
1 result found.
JaVale McGee
Results for JaVale McGee:

You searched for "Zaza Pachulia"
1 result found.
Zaza Pachulia
Results for Zaza Pachulia:

You searched for "Klay Thompson"
7 results found.
0: Klay Thompson
1: Billy Thompson
2: Corny Thompson
3: Jack Thompson
4: John Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Klay Thompson:

You searched for "David West"
18 results found.
0: David West
1: David Wear
2: David Lee
3: David Lee
4: David Wesley
5: Mario West
6: David Wood
7: David Benoit
8: Travis Best
9: David Noel
10: David Nwaba
11: David Pope
12: Doug West
13: Mark West
14: David Burns
15: David Cooke
16: David Gaines
17: David Rivers
Pick one: 0
Results for David West:

You searched for "Nick Young"
10 results found.
0: Nick Young
1: Rick Mount
2: Tim Young
3: Dick Bunt
4: Nick Jones
5: Joe Young
6: Sam Young
7: Trae Young
8: Dick Holub
9: Nick Vanos
Pick one: 0
Results for Nick Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-01-27,29-319,GSW,HOME,BOS,W (+4),1,36:48,16,24,...,4,5,2,0,1,2,49,43.1,6,Stephen Curry
1,2018-02-22,29-345,GSW,HOME,LAC,W (+7),1,37:08,14,19,...,6,10,2,0,4,4,44,41.9,8,Stephen Curry
2,2018-02-14,29-138,GSW,AWAY,POR,L (-6),1,37:16,17,27,...,7,6,0,2,4,1,50,41.2,-6,Kevin Durant
3,2018-01-06,29-298,GSW,AWAY,LAC,W (+16),1,29:51,11,21,...,6,3,3,0,2,2,45,39.2,28,Stephen Curry
4,2017-12-08,29-070,GSW,AWAY,DET,W (+4),1,38:38,12,23,...,10,7,1,5,2,3,36,33.9,11,Kevin Durant

In [75]:


GSW_2019_gamelog = []

for p in GSW_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2019_gamelog.append(player_log)
GSW_2019_gamelog = pd.concat(GSW_2019_gamelog)    
GSW_2019_gamelogs = GSW_2019_gamelog.copy()
GSW_2019_gamelogs['GAME_SCORE'] = GSW_2019_gamelogs['GAME_SCORE'].astype(float)
GSW_2019_games = GSW_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2019_games_csv = GSW_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2019_games.csv', index=False)
GSW_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2019_games.csv')
GSW_2019_games_proc.head()

You searched for "Jordan Bell"
10 results found.
0: Jordan Bell
1: Jordan Hill
2: Jordan Bone
3: Jordan Ford
4: Jordan Loyd
5: Jordan Poole
6: Jordan Sibert
7: Jordan Bowden
8: Ryan Kelly
9: Jordan McRae
Pick one: 0
Results for Jordan Bell:

You searched for "Andrew Bogut"
4 results found.
0: Andrew Bogut
1: Andrew Bynum
2: Andrew Toney
3: Andrew Gaze
Pick one: 0
Results for Andrew Bogut:

You searched for "Quinn Cook"
3 results found.
0: Quinn Cook
1: Brian Cook
2: Quincy Acy
Pick one: 0
Results for Quinn Cook:

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Marcus Derrickson"
1 result found.
Marcus Derrickson
Results for Marcus Derrickson:

You searched for "Kevin Durant"
5 results found.
0: Kevin Durant
1: Devin Durrant
2: Kevin Murphy
3: Ken Durrett
4: Kevin Martin
Pick one: 0
Results for Kevin Durant:

You searched for "Jacob Evans"
5 results found.
0: Jacob Evans
1: Bob Evans
2: Jawun Evans
3: Earl Evans
4: Jacob Wiley
Pick one: 0
Results for Jacob Evans:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Jonas Jerebko"
1 result found.
Jonas Jerebko
Results for Jonas Jerebko:

You searched for "Damian Jones"
14 results found.
0: Damian Jones
1: Damon Jones
2: Damion James
3: DeQuan Jones
4: Mason Jones
5: Alvin Jones
6: Askia Jones
7: Dahntay Jones
8: Jalen Jones
9: James Jones
10: Kevin Jones
11: Robin Jones
12: Sam Jones
13: Wali Jones
Pick one: 0
Results for Damian Jones:

You searched for "Damion Lee"
9 results found.
0: Damion Lee
1: David Lee
2: David Lee
3: Saben Lee
4: Don Dee
5: Damion James
6: Dick Lee
7: Ron Lee
8: Davon Reed
Pick one: 0
Results for Damion Lee:

You searched for "Shaun Livingston"
2 results found.
0: Shaun Livingston
1: Ron Livingstone
Pick one: 0
Results for Shaun Livingston:

You searched for "Kevon Looney"
5 results found.
0: Kevon Looney
1: Kevin Jones
2: Kevin Loder
3: Kevin Love
4: Devon Dotson
Pick one: 0
Results for Kevon Looney:

You searched for "Alfonzo McKinnie"
1 result found.
Alfonzo McKinnie
Results for Alfonzo McKinnie:

You searched for "Klay Thompson"
7 results found.
0: Klay Thompson
1: Billy Thompson
2: Corny Thompson
3: Jack Thompson
4: John Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Klay Thompson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-11-29,30-061,GSW,AWAY,TOR,L (-3),1,42:56,18,31,...,11,6,0,0,1,4,51,42.2,-5,Kevin Durant
1,2018-10-24,30-224,GSW,HOME,WAS,W (+22),1,31:35,15,24,...,4,3,0,1,2,1,51,41.8,19,Stephen Curry
2,2019-01-13,30-305,GSW,AWAY,DAL,W (+5),1,36:51,17,32,...,6,5,1,2,0,5,48,39.3,9,Stephen Curry
3,2018-10-29,28-263,GSW,AWAY,CHI,W (+25),1,26:33,18,29,...,4,0,2,0,2,2,52,39.3,28,Klay Thompson
4,2018-12-05,30-266,GSW,AWAY,CLE,W (+24),1,33:47,11,20,...,9,7,1,0,2,1,42,38.2,22,Stephen Curry

In [80]:


GSW_2020_gamelog = []

for p in GSW_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2020_gamelog.append(player_log)
GSW_2020_gamelog = pd.concat(GSW_2020_gamelog)    
GSW_2020_gamelogs = GSW_2020_gamelog.copy()
GSW_2020_gamelogs['GAME_SCORE'] = GSW_2020_gamelogs['GAME_SCORE'].astype(float)
GSW_2020_games = GSW_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2020_games_csv = GSW_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2020_games.csv', index=False)
GSW_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2020_games.csv')
GSW_2020_games_proc.head()

You searched for "Dragan Bender"
1 result found.
Dragan Bender
Results for Dragan Bender:

You searched for "Ky Bowman"
4 results found.
0: Ky Bowman
1: Ira Bowman
2: Nate Bowman
3: Ken Norman
Pick one: 0
Results for Ky Bowman:

You searched for "Alec Burks"
3 results found.
0: Alec Burks
1: Trey Burke
2: Alex Kirk
Pick one: 0
Results for Alec Burks:

You searched for "Willie Cauley-Stein"
1 result found.
Willie Cauley-Stein
Results for Willie Cauley-Stein:

You searched for "Marquese Chriss"
1 result found.
Marquese Chriss
Results for Marquese Chriss:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Jacob Evans"
5 results found.
0: Jacob Evans
1: Bob Evans
2: Jawun Evans
3: Earl Evans
4: Jacob Wiley
Pick one: 0
Results for Jacob Evans:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Damion Lee"
9 results found.
0: Damion Lee
1: David Lee
2: David Lee
3: Saben Lee
4: Don Dee
5: Damion James
6: Dick Lee
7: Ron Lee
8: Davon Reed
Pick one: 0
Results for Damion Lee:

You searched for "Kevon Looney"
5 results found.
0: Kevon Looney
1: Kevin Jones
2: Kevin Loder
3: Kevin Love
4: Devon Dotson
Pick one: 0
Results for Kevon Looney:

You searched for "Mychal Mulder"
1 result found.
Mychal Mulder
Results for Mychal Mulder:

You searched for "Zach Norvell"
1 result found.
Zach Norvell
Results for Zach Norvell:

You searched for "Jeremy Pargo"
4 results found.
0: Jeremy Pargo
1: Jeremy Lamb
2: Jeremy Evans
3: Jeremy Tyler
Pick one: 0
Results for Jeremy Pargo:

You searched for "Eric Paschall"
1 result found.
Eric Paschall
Results for Eric Paschall:

You searched for "Jordan Poole"
9 results found.
0: Jordan Poole
1: Jordan Bone
2: Jordan Nwora
3: Jordan Bowden
4: Jordan Ford
5: Jordan Bell
6: Jordan Hill
7: Jordan Loyd
8: Jordan McRae
Pick one: 0
Results for Jordan Poole:

You searched for "Chasson Randle"
1 result found.
Chasson Randle
Results for Chasson Randle:

You searched for "Alen Smailagić"
1 result found.
Alen Smailagic
Results for Alen Smailagic:

You searched for "Omari Spellman"
1 result found.
Omari Spellman
Results for Omari Spellman:

You searched for "Juan Toscano-Anderson"
1 result found.
Juan Toscano-Anderson
Results for Juan Toscano-Anderson:

You searched for "Andrew Wiggins"
2 results found.
0: Andrew Wiggins
1: DeAndre Liggins
Pick one: 0
Results for Andrew Wiggins:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-01-27,24-338,MIN,HOME,SAC,L (-4),1,42:47,13,21,...,9,8,0,1,2,4,36,30.7,8,Andrew Wiggins
1,2020-01-20,28-184,GSW,AWAY,POR,L (-5),1,39:16,11,23,...,7,8,1,3,0,6,33,30.5,0,Alec Burks
2,2019-11-08,24-258,MIN,HOME,GSW,W (+6),1,44:37,17,33,...,5,7,0,3,0,4,40,29.4,13,Andrew Wiggins
3,2019-11-04,23-000,GSW,HOME,POR,W (+9),1,39:32,11,19,...,13,0,0,1,1,2,34,29.1,11,Eric Paschall
4,2020-02-12,24-354,GSW,AWAY,PHO,L (-6),1,33:47,9,14,...,4,5,2,4,2,0,27,28.3,9,Andrew Wiggins

In [85]:

GSW_2021_gamelog = []

for p in GSW_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    GSW_2021_gamelog.append(player_log)
GSW_2021_gamelog = pd.concat(GSW_2021_gamelog)    
GSW_2021_gamelogs = GSW_2021_gamelog.copy()
GSW_2021_gamelogs['GAME_SCORE'] = GSW_2021_gamelogs['GAME_SCORE'].astype(float)
GSW_2021_games = GSW_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_2021_games_csv = GSW_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2021_games.csv', index=False)
GSW_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2021_games.csv')
GSW_2021_games_proc.head()

You searched for "Kent Bazemore"
1 result found.
Kent Bazemore
Results for Kent Bazemore:

You searched for "Jordan Bell"
10 results found.
0: Jordan Bell
1: Jordan Hill
2: Jordan Bone
3: Jordan Ford
4: Jordan Loyd
5: Jordan Poole
6: Jordan Sibert
7: Jordan Bowden
8: Ryan Kelly
9: Jordan McRae
Pick one: 0
Results for Jordan Bell:

You searched for "Marquese Chriss"
1 result found.
Marquese Chriss
Results for Marquese Chriss:

You searched for "Stephen Curry"
3 results found.
0: Stephen Curry
1: Stephen Chubin
2: Seth Curry
Pick one: 0
Results for Stephen Curry:

You searched for "Draymond Green"
2 results found.
0: Draymond Green
1: Raymond Brown
Pick one: 0
Results for Draymond Green:

You searched for "Damion Lee"
9 results found.
0: Damion Lee
1: David Lee
2: David Lee
3: Saben Lee
4: Don Dee
5: Damion James
6: Dick Lee
7: Ron Lee
8: Davon Reed
Pick one: 0
Results for Damion Lee:

You searched for "Kevon Looney"
5 results found.
0: Kevon Looney
1: Kevin Jones
2: Kevin Loder
3: Kevin Love
4: Devon Dotson
Pick one: 0
Results for Kevon Looney:

You searched for "Nico Mannion"
4 results found.
0: Nico Mannion
1: Pace Mannion
2: Rich Manning
3: Nick Mantis
Pick one: 0
Results for Nico Mannion:

You searched for "Mychal Mulder"
1 result found.
Mychal Mulder
Results for Mychal Mulder:

You searched for "Eric Paschall"
1 result found.
Eric Paschall
Results for Eric Paschall:

You searched for "Jordan Poole"
9 results found.
0: Jordan Poole
1: Jordan Bone
2: Jordan Nwora
3: Jordan Bowden
4: Jordan Ford
5: Jordan Bell
6: Jordan Hill
7: Jordan Loyd
8: Jordan McRae
Pick one: 0
Results for Jordan Poole:

You searched for "Alen Smailagić"
1 result found.
Alen Smailagic
Results for Alen Smailagic:

You searched for "Juan Toscano-Anderson"
1 result found.
Juan Toscano-Anderson
Results for Juan Toscano-Anderson:

You searched for "Brad Wanamaker"
1 result found.
Brad Wanamaker
Results for Brad Wanamaker:

You searched for "Andrew Wiggins"
2 results found.
0: Andrew Wiggins
1: DeAndre Liggins
Pick one: 0
Results for Andrew Wiggins:

You searched for "James Wiseman"
2 results found.
0: James Wiseman
1: James Phelan
Pick one: 0
Results for James Wiseman:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-01-03,32-295,GSW,HOME,POR,W (+15),1,36:27,18,31,...,5,4,0,0,5,0,62,46.8,20,Stephen Curry
1,2021-02-06,32-329,GSW,AWAY,DAL,L (-2),1,37:04,19,31,...,2,5,1,0,3,3,57,43.8,7,Stephen Curry
2,2021-04-12,33-029,GSW,HOME,DEN,W (+9),1,35:42,14,24,...,6,4,0,0,5,3,53,39.8,16,Stephen Curry
3,2021-04-14,33-031,GSW,AWAY,OKC,W (+38),1,29:23,14,20,...,6,8,0,0,0,3,42,39.8,31,Stephen Curry
4,2021-05-08,33-055,GSW,HOME,OKC,W (+39),1,29:20,14,26,...,5,2,1,0,1,2,49,38.5,31,Stephen Curry

## combine all seasons

In [86]:
GSW_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2000_games.csv')
GSW_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2001_games.csv')
GSW_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2002_games.csv')
GSW_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2003_games.csv')
GSW_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2004_games.csv')
GSW_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2005_games.csv')
GSW_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2006_games.csv')
GSW_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2007_games.csv')
GSW_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2008_games.csv')
GSW_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2009_games.csv')
GSW_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2010_games.csv')
GSW_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2011_games.csv')
GSW_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2012_games.csv')
GSW_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2013_games.csv')
GSW_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2014_games.csv')
GSW_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2015_games.csv')
GSW_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2016_games.csv')
GSW_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2017_games.csv')
GSW_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2018_games.csv')
GSW_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2019_games.csv')
GSW_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2020_games.csv')
GSW_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/GSW/GSW_2021_games.csv')

In [87]:
GSW_season_dfs = [GSW_2000_games_io, GSW_2001_games_io, GSW_2002_games_io, GSW_2003_games_io, GSW_2004_games_io, GSW_2005_games_io,
                 GSW_2006_games_io, GSW_2007_games_io, GSW_2008_games_io, GSW_2009_games_io, GSW_2010_games_io, GSW_2011_games_io,
                 GSW_2012_games_io, GSW_2013_games_io, GSW_2014_games_io, GSW_2015_games_io, GSW_2016_games_io, GSW_2017_games_io,
                 GSW_2018_games_io, GSW_2019_games_io, GSW_2020_games_io, GSW_2021_games_io]

In [88]:
GSW_all = pd.concat(GSW_season_dfs)
GSW_all_sorted = GSW_all.sort_values(by=['GAME_SCORE'], ascending=False)
GSW_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-10-31,27-231,GSW,AWAY,NOP,W (+14),1,35:38,17,27,...,4,9,4,0,2,3,53,49.2,16,Stephen Curry
0,2021-01-03,32-295,GSW,HOME,POR,W (+15),1,36:27,18,31,...,5,4,0,0,5,0,62,46.8,20,Stephen Curry
0,2016-12-05,26-301,GSW,HOME,IND,W (+36),1,29:03,21,33,...,2,1,0,0,0,0,60,46.2,37,Klay Thompson
0,2013-02-27,24-350,GSW,AWAY,NYK,L (-4),1,48:00,18,28,...,6,7,3,0,4,3,54,46.1,-4,Stephen Curry
0,2000-12-06,24-177,GSW,HOME,LAL,W (+3),1,53:00,21,29,...,13,5,2,1,4,2,51,46.0,3,Antawn Jamison
1,2000-12-03,24-174,GSW,AWAY,SEA,L (-16),1,48:00,23,36,...,14,2,3,2,1,2,51,45.2,-16,Antawn Jamison
0,2015-01-23,24-349,GSW,HOME,SAC,W (+25),1,32:49,16,25,...,2,5,4,2,4,3,52,44.8,38,Klay Thompson
1,2021-02-06,32-329,GSW,AWAY,DAL,L (-2),1,37:04,19,31,...,2,5,1,0,3,3,57,43.8,7,Stephen Curry
1,2016-02-25,27-348,GSW,AWAY,ORL,W (+16),1,34:02,20,27,...,7,8,0,1,5,1,51,43.1,11,Stephen Curry
0,2018-01-27,29-319,GSW,HOME,BOS,W (+4),1,36:48,16,24,...,4,5,2,0,1,2,49,43.1,6,Stephen Curry
0,2018-11-29,30-061,GSW,AWAY,TOR,L (-3),1,42:56,18,31,...,11,6,0,0,1,4,51,42.2,-5,Kevin Durant
1,2013-04-12,25-029,GSW,AWAY,LAL,L (-2),1,44:17,17,31,...,6,9,3,0,1,3,47,42.2,3,Stephen Curry
0,2005-04-05,25-357,GSW,HOME,HOU,W (+5),1,38:28,11,20,...,5,13,5,0,3,1,40,42.2,4,Baron Davis
1,2018-02-22,29-345,GSW,HOME,LAC,W (+7),1,37:08,14,19,...,6,10,2,0,4,4,44,41.9,8,Stephen Curry
1,2018-10-24,30-224,GSW,HOME,WAS,W (+22),1,31:35,15,24,...,4,3,0,1,2,1,51,41.8,19,Stephen Curry
2,2018-02-14,29-138,GSW,AWAY,POR,L (-6),1,37:16,17,27,...,7,6,0,2,4,1,50,41.2,-6,Kevin Durant
2,2016-01-22,27-314,GSW,HOME,IND,W (+12),1,36:49,11,19,...,10,12,1,0,2,1,39,40.9,22,Stephen Curry
3,2016-04-13,28-030,GSW,HOME,MEM,W (+21),1,29:46,15,24,...,4,6,2,0,2,2,46,40.2,19,Stephen Curry
1,2017-01-18,28-111,GSW,HOME,OKC,W (+21),1,33:49,13,16,...,12,4,0,3,2,2,40,40.1,31,Kevin Durant
0,2008-12-20,28-275,GSW,AWAY,CHA,W (+7),1,45:51,14,26,...,2,5,0,1,1,2,50,40.0,15,Jamal Crawford
0,2010-04-14,22-031,GSW,AWAY,POR,W (+6),1,48:00,13,25,...,9,8,2,1,2,0,42,39.9,6,Stephen Curry
2,2021-04-12,33-029,GSW,HOME,DEN,W (+9),1,35:42,14,24,...,6,4,0,0,5,3,53,39.8,16,Stephen Curry
3,2021-04-14,33-031,GSW,AWAY,OKC,W (+38),1,29:23,14,20,...,6,8,0,0,0,3,42,39.8,31,Stephen Curry
3,2018-10-29,28-263,GSW,AWAY,CHI,W (+25),1,26:33,18,29,...,4,0,2,0,2,2,52,39.3,28,Klay Thompson
2,2019-01-13,30-305,GSW,AWAY,DAL,W (+5),1,36:51,17,32,...,6,5,1,2,0,5,48,39.3,9,Stephen Curry