In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2014-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_HOU = []

# HOU
while season <= 2021:
    df_HOU = get_roster('HOU', season)
    df_HOU['Season'] = season
    df_HOU['Team'] = 'HOU'
    appended_data_HOU.append(df_HOU)
    season = season + 1
appended_data_HOU = pd.concat(appended_data_HOU)

In [4]:
HOU_df_all = appended_data_HOU.copy()
HOU_df_all_csv = HOU_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_players_all.csv', index=False)
HOU_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_players_all.csv')
HOU_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,40,Shandon Anderson,SF,6-6,208,1973-12-31,US,3,Georgia,2000,HOU
1,4,Charles Barkley,PF,6-6,252,1963-02-20,US,15,Auburn,2000,HOU
2,50,Matt Bullard,PF,6-10,215,1967-06-05,US,8,"Colorado, Iowa",2000,HOU
3,13,Kelvin Cato,C,6-11,255,1974-08-26,US,2,"University of South Alabama, Iowa State",2000,HOU
4,15,Bill Curley,PF,6-9,220,1972-05-29,US,3,Boston College,2000,HOU

In [5]:
HOU_df_2000 = HOU_df_all[HOU_df_all['Season'] == 2000]
HOU_df_2001 = HOU_df_all[HOU_df_all['Season'] == 2001]
HOU_df_2002 = HOU_df_all[HOU_df_all['Season'] == 2002]
HOU_df_2003 = HOU_df_all[HOU_df_all['Season'] == 2003]
HOU_df_2004 = HOU_df_all[HOU_df_all['Season'] == 2004]
HOU_df_2005 = HOU_df_all[HOU_df_all['Season'] == 2005]
HOU_df_2006 = HOU_df_all[HOU_df_all['Season'] == 2006]
HOU_df_2007 = HOU_df_all[HOU_df_all['Season'] == 2007]
HOU_df_2008 = HOU_df_all[HOU_df_all['Season'] == 2008]
HOU_df_2009 = HOU_df_all[HOU_df_all['Season'] == 2009]
HOU_df_2010 = HOU_df_all[HOU_df_all['Season'] == 2010]
HOU_df_2011 = HOU_df_all[HOU_df_all['Season'] == 2011]
HOU_df_2012 = HOU_df_all[HOU_df_all['Season'] == 2012]
HOU_df_2013 = HOU_df_all[HOU_df_all['Season'] == 2013]
HOU_df_2014 = HOU_df_all[HOU_df_all['Season'] == 2014]
HOU_df_2015 = HOU_df_all[HOU_df_all['Season'] == 2015]
HOU_df_2016 = HOU_df_all[HOU_df_all['Season'] == 2016]
HOU_df_2017 = HOU_df_all[HOU_df_all['Season'] == 2017]
HOU_df_2018 = HOU_df_all[HOU_df_all['Season'] == 2018]
HOU_df_2019 = HOU_df_all[HOU_df_all['Season'] == 2019]
HOU_df_2020 = HOU_df_all[HOU_df_all['Season'] == 2020]
HOU_df_2021 = HOU_df_all[HOU_df_all['Season'] == 2021]

In [6]:
# changing names
#HOU_df_2002.loc[HOU_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#HOU_df_2004.loc[HOU_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [7]:
HOU_df_2000_players = HOU_df_2000['PLAYER'].to_list()
HOU_df_2001_players = HOU_df_2001['PLAYER'].to_list()
HOU_df_2002_players = HOU_df_2002['PLAYER'].to_list()
HOU_df_2003_players = HOU_df_2003['PLAYER'].to_list()
HOU_df_2004_players = HOU_df_2004['PLAYER'].to_list()
HOU_df_2005_players = HOU_df_2005['PLAYER'].to_list()

HOU_df_2006_players = HOU_df_2006['PLAYER'].to_list()
HOU_df_2007_players = HOU_df_2007['PLAYER'].to_list()
HOU_df_2008_players = HOU_df_2008['PLAYER'].to_list()
HOU_df_2009_players = HOU_df_2009['PLAYER'].to_list()
HOU_df_2010_players = HOU_df_2010['PLAYER'].to_list()
HOU_df_2011_players = HOU_df_2011['PLAYER'].to_list()

HOU_df_2012_players = HOU_df_2012['PLAYER'].to_list()
HOU_df_2013_players = HOU_df_2013['PLAYER'].to_list()
HOU_df_2014_players = HOU_df_2014['PLAYER'].to_list()
HOU_df_2015_players = HOU_df_2015['PLAYER'].to_list()
HOU_df_2016_players = HOU_df_2016['PLAYER'].to_list()
HOU_df_2017_players = HOU_df_2017['PLAYER'].to_list()

HOU_df_2018_players = HOU_df_2018['PLAYER'].to_list()
HOU_df_2019_players = HOU_df_2019['PLAYER'].to_list()
HOU_df_2020_players = HOU_df_2020['PLAYER'].to_list()
HOU_df_2021_players = HOU_df_2021['PLAYER'].to_list()

## players to drop

In [65]:

#HOU_df_2000_players.remove("Mark Davis")
#HOU_df_2008_players.remove("Bobby Jones")
#HOU_df_2009_players.remove("Metta World Peace")
#HOU_df_2012_players.remove("Greg Smith")
#HOU_df_2013_players.remove("Greg Smith")
#HOU_df_2014_players.remove("Greg Smith")
#HOU_df_2015_players.remove("Clint Capela")
#HOU_df_2016_players.remove("Clint Capela")
#HOU_df_2017_players.remove("Clint Capela")
#HOU_df_2018_players.remove("Clint Capela")
#HOU_df_2019_players.remove("Clint Capela")
#HOU_df_2020_players.remove("Clint Capela")
#HOU_df_2021_players.remove("Clint Capela")
#HOU_df_2017_players.remove("Nenê Hilário")
#HOU_df_2018_players.remove("Nenê Hilário")
#HOU_df_2019_players.remove("Nenê Hilário")
#HOU_df_2021_players.remove("Armoni Brooks")
#HOU_df_2021_players.remove("Cameron Oliver")
#HOU_df_2021_players.remove("Kevin Porter")
HOU_df_2021_players.remove("Jae'Sean Tate")

In [9]:

HOU_2000_gamelog = []



for p in HOU_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2000_gamelog.append(player_log)
HOU_2000_gamelog = pd.concat(HOU_2000_gamelog)    
HOU_2000_gamelogs = HOU_2000_gamelog.copy()
HOU_2000_gamelogs['GAME_SCORE'] = HOU_2000_gamelogs['GAME_SCORE'].astype(float)
HOU_2000_games = HOU_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2000_games_csv = HOU_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2000_games.csv', index=False)
HOU_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2000_games.csv')
HOU_2000_games_proc.head()

You searched for "Shandon Anderson"
1 result found.
Shandon Anderson
Results for Shandon Anderson:

You searched for "Charles Barkley"
7 results found.
0: Charles Barkley
1: Charles Oakley
2: Charles Beasley
3: Charles Bradley
4: Charles Dudley
5: Charles Parks
6: Charlie Parsley
Pick one: 0
Results for Charles Barkley:

You searched for "Matt Bullard"
2 results found.
0: Matt Bullard
1: Matt Barnes
Pick one: 0
Results for Matt Bullard:

You searched for "Kelvin Cato"
4 results found.
0: Kelvin Cato
1: Calvin Natt
2: Kevin Knox
3: Kevin Love
Pick one: 0
Results for Kelvin Cato:

You searched for "Bill Curley"
14 results found.
0: Bill Curley
1: Bill Turner
2: Bill Allen
3: Bill Bradley
4: Bill Bradley
5: Bill Crow
6: Dell Curry
7: Bill Downey
8: Bill Garner
9: Bill Keller
10: Bill Miller
11: Bill Closs
12: Bill McGill
13: Bill Meyer
Pick one: 0
Results for Bill Curley:

You searched for "Bryce Drew"
3 results found.
0: Bryce Drew
1: Bruce Brown
2: Bruce Hale
Pick one: 0
Results for Bryce Drew:

You searched for "Steve Francis"
3 results found.
0: Steve Francis
1: Steve Bracey
2: Steve Harris
Pick one: 0
Results for Steve Francis:

You searched for "Devin Gray"
10 results found.
0: Devin Gray
1: Evric Gray
2: Devin Green
3: Devin Brown
4: Aaron Gray
5: Ed Gray
6: Kevin Grevey
7: Dennis Grey
8: Don Ray
9: Don Grate
Pick one: 0
Results for Devin Gray:

You searched for "Thomas Hamilton"
1 result found.
Thomas Hamilton
Results for Thomas Hamilton:

You searched for "Tony Massenburg"
1 result found.
Tony Massenburg
Results for Tony Massenburg:

You searched for "Anthony Miller"
9 results found.
0: Anthony Miller
1: Anthony Peeler
2: Anthony Bonner
3: Anthony Carter
4: Anthony Parker
5: Anthony Pullard
6: Anthony Taylor
7: Anthony Tolliver
8: Anthony Tucker
Pick one: 0
Results for Anthony Miller:

You searched for "Cuttino Mobley"
1 result found.
Cuttino Mobley
Results for Cuttino Mobley:

You searched for "Moochie Norris"
1 result found.
Moochie Norris
Results for Moochie Norris:

You searched for "Hakeem Olajuwon"
1 result found.
Hakeem Olajuwon
Results for Hakeem Olajuwon:

You searched for "Carlos Rogers"
6 results found.
0: Carlos Rogers
1: Carlos Boozer
2: Harry Rogers
3: Roy Rogers
4: Carlos Terry
5: Carlos Arroyo
Pick one: 0
Results for Carlos Rogers:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Walt Williams"
45 results found.
0: Walt Williams
1: Al Williams
2: Art Williams
3: Matt Williams
4: Milt Williams
5: Ward Williams
6: Alan Williams
7: Earl Williams
8: Fly Williams
9: Grant Williams
10: Hank Williams
11: Jay Williams
12: Nate Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Walt Bellamy
18: Aaron Williams
19: Alvin Williams
20: Bob Williams
21: Buck Williams
22: C.J. Williams
23: Duck Williams
24: Elliot Williams
25: Eric Williams
26: Frank Williams
27: Gene Williams
28: Gus Williams
29: Guy Williams
30: Herb Williams
31: Jason Williams
32: Jawad Williams
33: John Williams
34: Lou Williams
35: Mike Williams
36: Mo Williams
37: Monty Williams
38: Pete Williams
39: Rob Williams
40: Ron Williams
41: Scott Williams
42: Sean Williams
43: Troy Williams
44: Willie Williams
Pick one: 0
Results for Walt Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-03-23,23-031,HOU,HOME,LAC,W (+15),1,40:47,13,19,...,9,14,3,0,2,4,34,37.8,12,Steve Francis
1,2000-04-05,26-096,HOU,AWAY,POR,W (+13),1,43:33,10,12,...,10,3,1,0,3,2,30,29.1,12,Shandon Anderson
2,2000-03-14,23-022,HOU,AWAY,NYK,L (-6),1,41:02,12,17,...,5,4,4,0,3,4,32,28.6,-4,Steve Francis
3,2000-01-15,22-328,HOU,AWAY,CHI,W (+3),1,41:28,12,17,...,4,11,2,1,3,2,27,28.5,3,Steve Francis
4,2000-02-03,26-034,HOU,HOME,PHI,W (+3),1,39:23,10,17,...,7,2,3,0,2,2,32,28.2,0,Shandon Anderson

In [10]:

HOU_2001_gamelog = []


for p in HOU_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2001_gamelog.append(player_log)
HOU_2001_gamelog = pd.concat(HOU_2001_gamelog)    
HOU_2001_gamelogs = HOU_2001_gamelog.copy()
HOU_2001_gamelogs['GAME_SCORE'] = HOU_2001_gamelogs['GAME_SCORE'].astype(float)
HOU_2001_games = HOU_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2001_games_csv = HOU_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2001_games.csv', index=False)
HOU_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2001_games.csv')
HOU_2001_games_proc.head()

You searched for "Shandon Anderson"
1 result found.
Shandon Anderson
Results for Shandon Anderson:

You searched for "Matt Bullard"
2 results found.
0: Matt Bullard
1: Matt Barnes
Pick one: 0
Results for Matt Bullard:

You searched for "Kelvin Cato"
4 results found.
0: Kelvin Cato
1: Calvin Natt
2: Kevin Knox
3: Kevin Love
Pick one: 0
Results for Kelvin Cato:

You searched for "Jason Collier"
3 results found.
0: Jason Collier
1: Jason Collins
2: Jarron Collins
Pick one: 0
Results for Jason Collier:

You searched for "Sean Colson"
3 results found.
0: Sean Colson
1: Dean Tolson
2: Sean Rooks
Pick one: 0
Results for Sean Colson:

You searched for "Steve Francis"
3 results found.
0: Steve Francis
1: Steve Bracey
2: Steve Harris
Pick one: 0
Results for Steve Francis:

You searched for "Dan Langhi"
6 results found.
0: Dan Langhi
1: Dan King
2: James Lang
3: Grant Long
4: Shawn Long
5: Dan Tieman
Pick one: 0
Results for Dan Langhi:

You searched for "Anthony Miller"
9 results found.
0: Anthony Miller
1: Anthony Peeler
2: Anthony Bonner
3: Anthony Carter
4: Anthony Parker
5: Anthony Pullard
6: Anthony Taylor
7: Anthony Tolliver
8: Anthony Tucker
Pick one: 0
Results for Anthony Miller:

You searched for "Cuttino Mobley"
1 result found.
Cuttino Mobley
Results for Cuttino Mobley:

You searched for "Moochie Norris"
1 result found.
Moochie Norris
Results for Moochie Norris:

You searched for "Hakeem Olajuwon"
1 result found.
Hakeem Olajuwon
Results for Hakeem Olajuwon:

You searched for "Carlos Rogers"
6 results found.
0: Carlos Rogers
1: Carlos Boozer
2: Harry Rogers
3: Roy Rogers
4: Carlos Terry
5: Carlos Arroyo
Pick one: 0
Results for Carlos Rogers:

You searched for "Maurice Taylor"
6 results found.
0: Maurice Taylor
1: Marlon Taylor
2: Maurice Ager
3: Maurice Baker
4: Maurice Carter
5: Mike Taylor
Pick one: 0
Results for Maurice Taylor:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Walt Williams"
45 results found.
0: Walt Williams
1: Al Williams
2: Art Williams
3: Matt Williams
4: Milt Williams
5: Ward Williams
6: Alan Williams
7: Earl Williams
8: Fly Williams
9: Grant Williams
10: Hank Williams
11: Jay Williams
12: Nate Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Walt Bellamy
18: Aaron Williams
19: Alvin Williams
20: Bob Williams
21: Buck Williams
22: C.J. Williams
23: Duck Williams
24: Elliot Williams
25: Eric Williams
26: Frank Williams
27: Gene Williams
28: Gus Williams
29: Guy Williams
30: Herb Williams
31: Jason Williams
32: Jawad Williams
33: John Williams
34: Lou Williams
35: Mike Williams
36: Mo Williams
37: Monty Williams
38: Pete Williams
39: Rob Williams
40: Ron Williams
41: Scott Williams
42: Sean Williams
43: Troy Williams
44: Willie Williams
Pick one: 0
Results for Walt Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-02-17,23-362,HOU,HOME,CLE,W (+12),1,36:40,11,19,...,10,4,5,0,2,5,35,35.3,8,Steve Francis
1,2000-12-05,23-288,HOU,HOME,DAL,W (+7),1,48:00,11,16,...,10,4,1,1,3,2,36,33.7,7,Steve Francis
2,2001-01-18,25-139,HOU,AWAY,GSW,W (+8),1,45:11,14,26,...,9,0,1,0,0,2,41,30.9,12,Cuttino Mobley
3,2001-03-15,25-195,HOU,HOME,NJN,W (+2),1,45:16,11,18,...,6,11,1,0,2,0,30,29.9,-1,Cuttino Mobley
4,2001-02-23,24-116,HOU,HOME,ORL,W (+10),1,48:00,11,20,...,6,5,2,2,3,1,34,29.3,10,Maurice Taylor

In [11]:
HOU_2002_gamelog = []


for p in HOU_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2002_gamelog.append(player_log)
HOU_2002_gamelog = pd.concat(HOU_2002_gamelog)    
HOU_2002_gamelogs = HOU_2002_gamelog.copy()
HOU_2002_gamelogs['GAME_SCORE'] = HOU_2002_gamelogs['GAME_SCORE'].astype(float)
HOU_2002_games = HOU_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2002_games_csv = HOU_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2002_games.csv', index=False)
HOU_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2002_games.csv')
HOU_2002_games_proc.head()

You searched for "Tierre Brown"
8 results found.
0: Tierre Brown
1: Andre Brown
2: Dee Brown
3: Dee Brown
4: George Brown
5: Larry Brown
6: Mike Brown
7: Troy Brown
Pick one: 0
Results for Tierre Brown:

You searched for "Kelvin Cato"
4 results found.
0: Kelvin Cato
1: Calvin Natt
2: Kevin Knox
3: Kevin Love
Pick one: 0
Results for Kelvin Cato:

You searched for "Jason Collier"
3 results found.
0: Jason Collier
1: Jason Collins
2: Jarron Collins
Pick one: 0
Results for Jason Collier:

You searched for "Steve Francis"
3 results found.
0: Steve Francis
1: Steve Bracey
2: Steve Harris
Pick one: 0
Results for Steve Francis:

You searched for "Eddie Griffin"
3 results found.
0: Eddie Griffin
1: Adrian Griffin
2: Blake Griffin
Pick one: 0
Results for Eddie Griffin:

You searched for "Dan Langhi"
6 results found.
0: Dan Langhi
1: Dan King
2: James Lang
3: Grant Long
4: Shawn Long
5: Dan Tieman
Pick one: 0
Results for Dan Langhi:

You searched for "Cuttino Mobley"
1 result found.
Cuttino Mobley
Results for Cuttino Mobley:

You searched for "Terence Morris"
2 results found.
0: Terence Morris
1: Terence Davis
Pick one: 0
Results for Terence Morris:

You searched for "Moochie Norris"
1 result found.
Moochie Norris
Results for Moochie Norris:

You searched for "Glen Rice"
7 results found.
0: Glen Rice
1: Glen Rice
2: Greg Kite
3: Brent Price
4: Gene Rock
5: Jalen Rose
6: Glen Davis
Pick one: 0
Results for Glen Rice:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Óscar Torres"
1 result found.
Oscar Torres
Results for Oscar Torres:

You searched for "Walt Williams"
45 results found.
0: Walt Williams
1: Al Williams
2: Art Williams
3: Matt Williams
4: Milt Williams
5: Ward Williams
6: Alan Williams
7: Earl Williams
8: Fly Williams
9: Grant Williams
10: Hank Williams
11: Jay Williams
12: Nate Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Walt Bellamy
18: Aaron Williams
19: Alvin Williams
20: Bob Williams
21: Buck Williams
22: C.J. Williams
23: Duck Williams
24: Elliot Williams
25: Eric Williams
26: Frank Williams
27: Gene Williams
28: Gus Williams
29: Guy Williams
30: Herb Williams
31: Jason Williams
32: Jawad Williams
33: John Williams
34: Lou Williams
35: Mike Williams
36: Mo Williams
37: Monty Williams
38: Pete Williams
39: Rob Williams
40: Ron Williams
41: Scott Williams
42: Sean Williams
43: Troy Williams
44: Willie Williams
Pick one: 0
Results for Walt Williams:

You searched for "Kevin Willis"
4 results found.
0: Kevin Willis
1: Kevin Williams
2: Kevin Ollie
3: Alvin Williams
Pick one: 0
Results for Kevin Willis:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-01-03,24-316,HOU,HOME,DET,W (+2),1,44:57,12,19,...,5,8,1,0,3,2,36,31.4,4,Steve Francis
1,2001-11-01,24-253,HOU,HOME,LAC,W (+6),1,49:20,10,20,...,10,7,3,0,3,3,32,30.3,5,Steve Francis
2,2001-12-22,26-112,HOU,HOME,MIL,W (+5),1,48:00,11,23,...,2,6,0,0,2,1,39,30.1,5,Cuttino Mobley
3,2002-02-23,26-175,HOU,HOME,BOS,W (+10),1,41:40,13,26,...,7,1,3,1,4,1,40,29.9,6,Cuttino Mobley
4,2002-03-05,25-012,HOU,HOME,TOR,W (+3),1,39:32,13,25,...,6,7,2,0,3,0,35,29.2,5,Steve Francis

In [12]:
HOU_2003_gamelog = []



for p in HOU_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2003_gamelog.append(player_log)
HOU_2003_gamelog = pd.concat(HOU_2003_gamelog)    
HOU_2003_gamelogs = HOU_2003_gamelog.copy()
HOU_2003_gamelogs['GAME_SCORE'] = HOU_2003_gamelogs['GAME_SCORE'].astype(float)
HOU_2003_games = HOU_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2003_games_csv = HOU_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2003_games.csv', index=False)
HOU_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2003_games.csv')
HOU_2003_games_proc.head()

You searched for "Kelvin Cato"
4 results found.
0: Kelvin Cato
1: Calvin Natt
2: Kevin Knox
3: Kevin Love
Pick one: 0
Results for Kelvin Cato:

You searched for "Jason Collier"
3 results found.
0: Jason Collier
1: Jason Collins
2: Jarron Collins
Pick one: 0
Results for Jason Collier:

You searched for "Steve Francis"
3 results found.
0: Steve Francis
1: Steve Bracey
2: Steve Harris
Pick one: 0
Results for Steve Francis:

You searched for "Eddie Griffin"
3 results found.
0: Eddie Griffin
1: Adrian Griffin
2: Blake Griffin
Pick one: 0
Results for Eddie Griffin:

You searched for "Juaquin Hawkins"
1 result found.
Juaquin Hawkins
Results for Juaquin Hawkins:

You searched for "Tito Maddox"
2 results found.
0: Tito Maddox
1: Jack Maddox
Pick one: 0
Results for Tito Maddox:

You searched for "Yao Ming"
6 results found.
0: Yao Ming
1: Dan King
2: Dave Bing
3: Jim King
4: Ron King
5: Tom King
Pick one: 0
Results for Yao Ming:

You searched for "Cuttino Mobley"
1 result found.
Cuttino Mobley
Results for Cuttino Mobley:

You searched for "Terence Morris"
2 results found.
0: Terence Morris
1: Terence Davis
Pick one: 0
Results for Terence Morris:

You searched for "Boštjan Nachbar"
1 result found.
Bostjan Nachbar
Results for Bostjan Nachbar:

You searched for "Moochie Norris"
1 result found.
Moochie Norris
Results for Moochie Norris:

You searched for "James Posey"
14 results found.
0: James Posey
1: James Jones
2: James Bailey
3: James Hardy
4: James Ray
5: Jalen Rose
6: James Worthy
7: James Young
8: James Ennis
9: James Scott
10: James Silas
11: James Thomas
12: James Webb
13: James White
Pick one: 0
Results for James Posey:

You searched for "Glen Rice"
7 results found.
0: Glen Rice
1: Glen Rice
2: Greg Kite
3: Brent Price
4: Gene Rock
5: Jalen Rose
6: Glen Davis
Pick one: 0
Results for Glen Rice:

You searched for "Maurice Taylor"
6 results found.
0: Maurice Taylor
1: Marlon Taylor
2: Maurice Ager
3: Maurice Baker
4: Maurice Carter
5: Mike Taylor
Pick one: 0
Results for Maurice Taylor:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-01-17,25-330,HOU,HOME,LAL,W (+4),1,48:57,12,21,...,6,11,2,0,7,3,44,36.2,2,Steve Francis
1,2003-02-24,26-003,HOU,AWAY,BOS,W (+6),1,48:26,10,18,...,9,9,2,2,2,3,33,33.2,9,Steve Francis
2,2003-03-23,26-030,HOU,AWAY,SAC,L (-1),1,38:09,14,22,...,5,9,0,0,2,4,38,32.0,2,Steve Francis
3,2003-03-14,26-021,HOU,HOME,CHI,W (+30),1,35:32,5,5,...,9,10,5,2,5,2,23,31.4,33,Steve Francis
4,2003-02-12,25-356,HOU,AWAY,UTA,W (+30),1,37:53,11,19,...,3,7,2,0,2,3,36,30.9,27,Steve Francis

In [13]:


HOU_2004_gamelog = []



for p in HOU_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2004_gamelog.append(player_log)
HOU_2004_gamelog = pd.concat(HOU_2004_gamelog)    
HOU_2004_gamelogs = HOU_2004_gamelog.copy()
HOU_2004_gamelogs['GAME_SCORE'] = HOU_2004_gamelogs['GAME_SCORE'].astype(float)
HOU_2004_games = HOU_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2004_games_csv = HOU_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2004_games.csv', index=False)
HOU_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2004_games.csv')
HOU_2004_games_proc.head()

You searched for "Torraye Braggs"
1 result found.
Torraye Braggs
Results for Torraye Braggs:

You searched for "Kelvin Cato"
4 results found.
0: Kelvin Cato
1: Calvin Natt
2: Kevin Knox
3: Kevin Love
Pick one: 0
Results for Kelvin Cato:

You searched for "Alton Ford"
6 results found.
0: Alton Ford
1: Don Ford
2: Alphonso Ford
3: Bob Ford
4: Al Horford
5: Leon Wood
Pick one: 0
Results for Alton Ford:

You searched for "Steve Francis"
3 results found.
0: Steve Francis
1: Steve Bracey
2: Steve Harris
Pick one: 0
Results for Steve Francis:

You searched for "Adrian Griffin"
2 results found.
0: Adrian Griffin
1: Eddie Griffin
Pick one: 0
Results for Adrian Griffin:

You searched for "Jim Jackson"
21 results found.
0: Jim Jackson
1: Al Jackson
2: Josh Jackson
3: Mike Jackson
4: Phil Jackson
5: Jim Paxson
6: Jim Paxson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Tony Jackson
16: Tony Jackson
17: Sam Jacobson
18: Jim Wilson
19: Jim Eakins
20: Jim Chones
Pick one: 0
Results for Jim Jackson:

You searched for "Mark Jackson"
25 results found.
0: Mark Jackson
1: Marc Jackson
2: Aaron Jackson
3: Al Jackson
4: Frank Jackson
5: Jaren Jackson
6: Jaren Jackson
7: Mike Jackson
8: Myron Jackson
9: Mark Macon
10: Mark Eaton
11: Greg Jackson
12: Jim Jackson
13: Josh Jackson
14: Luke Jackson
15: Luke Jackson
16: Mervin Jackson
17: Phil Jackson
18: Ralph Jackson
19: Tony Jackson
20: Tony Jackson
21: Tracy Jackson
22: Mark Madsen
23: Mark Jones
24: Mark Jones
Pick one: 0
Results for Mark Jackson:

You searched for "Yao Ming"
6 results found.
0: Yao Ming
1: Dan King
2: Dave Bing
3: Jim King
4: Ron King
5: Tom King
Pick one: 0
Results for Yao Ming:

You searched for "Cuttino Mobley"
1 result found.
Cuttino Mobley
Results for Cuttino Mobley:

You searched for "Boštjan Nachbar"
1 result found.
Bostjan Nachbar
Results for Bostjan Nachbar:

You searched for "Moochie Norris"
1 result found.
Moochie Norris
Results for Moochie Norris:

You searched for "Charles Oakley"
8 results found.
0: Charles Oakley
1: Charles Barkley
2: Charles Beasley
3: Charles Bradley
4: Charles Dudley
5: Charles Cooke
6: Charles Jordan
7: Charles Thomas
Pick one: 0
Results for Charles Oakley:

You searched for "Scott Padgett"
1 result found.
Scott Padgett
Results for Scott Padgett:

You searched for "Eric Piatkowski"
1 result found.
Eric Piatkowski
Results for Eric Piatkowski:

You searched for "Maurice Taylor"
6 results found.
0: Maurice Taylor
1: Marlon Taylor
2: Maurice Ager
3: Maurice Baker
4: Maurice Carter
5: Mike Taylor
Pick one: 0
Results for Maurice Taylor:

You searched for "Clarence Weatherspoon"
1 result found.
Clarence Weatherspoon
Results for Clarence Weatherspoon:

You searched for "Mike Wilks"
22 results found.
0: Mike Wilks
1: Mike Niles
2: Mike Bibby
3: Mike Davis
4: Mike Davis
5: Mike Evans
6: Mike Gale
7: Mike Hall
8: Mile Ilic
9: Mike James
10: Mike James
11: Mike Lewis
12: Mike Maloy
13: Mike Miller
14: Mike Williams
15: Mike Brown
16: Mike Lynn
17: Mike Newlin
18: Mike Novak
19: Mike Price
20: Mike Smith
21: Mike Smrek
Pick one: 0
Results for Mike Wilks:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-02-22,23-163,HOU,HOME,ATL,W (+2),1,49:34,15,21,...,16,7,0,2,5,4,41,37.6,15,Yao Ming
1,2004-04-09,27-048,HOU,HOME,DEN,W (+3),1,43:10,10,19,...,3,11,4,0,4,3,33,30.3,8,Steve Francis
2,2004-01-25,23-135,HOU,AWAY,ORL,W (+12),1,33:43,15,23,...,10,0,0,2,1,3,37,29.9,13,Yao Ming
3,2004-03-15,23-185,HOU,HOME,PHO,L (-2),1,43:23,11,16,...,19,1,0,6,4,4,29,29.2,1,Yao Ming
4,2003-11-08,26-260,HOU,HOME,ORL,W (+10),1,43:47,11,18,...,7,6,2,2,3,1,31,29.1,23,Steve Francis

In [14]:


HOU_2005_gamelog = []

for p in HOU_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2005_gamelog.append(player_log)
HOU_2005_gamelog = pd.concat(HOU_2005_gamelog)    
HOU_2005_gamelogs = HOU_2005_gamelog.copy()
HOU_2005_gamelogs['GAME_SCORE'] = HOU_2005_gamelogs['GAME_SCORE'].astype(float)
HOU_2005_games = HOU_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2005_games_csv = HOU_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2005_games.csv', index=False)
HOU_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2005_games.csv')
HOU_2005_games_proc.head()

You searched for "Vin Baker"
8 results found.
0: Vin Baker
1: Ron Baker
2: Von Wafer
3: Norm Baker
4: Tom Barker
5: Devin Booker
6: Thon Maker
7: Zan Tabak
Pick one: 0
Results for Vin Baker:

You searched for "Andre Barrett"
5 results found.
0: Andre Barrett
1: Ernie Barrett
2: Mike Barrett
3: RJ Barrett
4: Andre Emmett
Pick one: 0
Results for Andre Barrett:

You searched for "Jon Barry"
30 results found.
0: Jon Barry
1: John Barr
2: Moe Barr
3: Ron Perry
4: John Bagley
5: Ron Baker
6: John Barber
7: Brent Barry
8: Drew Barry
9: Rick Barry
10: Jay Carty
11: Bob Ferry
12: John Garris
13: Joe Harris
14: Don May
15: Don Ray
16: Jason Terry
17: John Warren
18: Vin Baker
19: Tom Barker
20: Mike Barr
21: Cory Carr
22: Ron Carter
23: Ron Harper
24: Jason Hart
25: Josh Hart
26: Jon Leuer
27: Jack Parr
28: Von Wafer
29: John Wall
Pick one: 0
Results for Jon Barry:

You searched for "Ryan Bowen"
13 results found.
0: Ryan Bowen
1: Brian Bowen
2: Ryan Gomes
3: Jordan Bowden
4: Don Boven
5: Bruce Bowen
6: Stan Brown
7: Ray Owes
8: Ron Rowan
9: Jordan Bone
10: Ron Boone
11: Red Owens
12: Ryan Reid
Pick one: 0
Results for Ryan Bowen:

You searched for "Torraye Braggs"
1 result found.
Torraye Braggs
Results for Torraye Braggs:

You searched for "Reece Gaines"
1 result found.
Reece Gaines
Results for Reece Gaines:

You searched for "Juwan Howard"
4 results found.
0: Juwan Howard
1: Brian Howard
2: Josh Howard
3: Juwan Morgan
Pick one: 0
Results for Juwan Howard:

You searched for "Jim Jackson"
21 results found.
0: Jim Jackson
1: Al Jackson
2: Josh Jackson
3: Mike Jackson
4: Phil Jackson
5: Jim Paxson
6: Jim Paxson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Tony Jackson
16: Tony Jackson
17: Sam Jacobson
18: Jim Wilson
19: Jim Eakins
20: Jim Chones
Pick one: 0
Results for Jim Jackson:

You searched for "Mike James"
33 results found.
0: Mike James
1: Mike James
2: Mike Davis
3: Mike Davis
4: Mike Farmer
5: Mike Gale
6: Gene James
7: Tim James
8: Mike Niles
9: Mike Barr
10: Mike Evans
11: Mike Green
12: Mike Hall
13: Mike Harper
14: Mike Harris
15: Mike Jackson
16: Billy James
17: Damion James
18: Jake Jones
19: Mike Kearns
20: Mike Lewis
21: Mike Maloy
22: Mike McGee
23: Mike Sanders
24: Mike Smrek
25: Mike Tobey
26: Mike Wilks
27: Mike Bantom
28: Mike Bloom
29: Mike Bratz
30: Mike Novak
31: Mike Pratt
32: Mike Price
Pick one: 0
Results for Mike James:

You searched for "Brandin Knight"
5 results found.
0: Brandin Knight
1: Brandon Knight
2: Brevin Knight
3: Brandan Wright
4: Travis Knight
Pick one: 0
Results for Brandin Knight:

You searched for "Tyronn Lue"
3 results found.
0: Tyronn Lue
1: Ron Lee
2: Tyrone Hill
Pick one: 0
Results for Tyronn Lue:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Yao Ming"
6 results found.
0: Yao Ming
1: Dan King
2: Dave Bing
3: Jim King
4: Ron King
5: Tom King
Pick one: 0
Results for Yao Ming:

You searched for "Dikembe Mutombo"
1 result found.
Dikembe Mutombo
Results for Dikembe Mutombo:

You searched for "Boštjan Nachbar"
1 result found.
Bostjan Nachbar
Results for Bostjan Nachbar:

You searched for "Moochie Norris"
1 result found.
Moochie Norris
Results for Moochie Norris:

You searched for "Scott Padgett"
1 result found.
Scott Padgett
Results for Scott Padgett:

You searched for "Rod Strickland"
4 results found.
0: Rod Strickland
1: Roger Strickland
2: Erick Strickland
3: Mark Strickland
Pick one: 0
Results for Rod Strickland:

You searched for "Bob Sura"
26 results found.
0: Bob Sura
1: Bob Shea
2: Bob Ford
3: Rob Kurz
4: Bob Rule
5: Bob Sims
6: Bob Verga
7: Bob Burrow
8: Bob Cousy
9: Bob Doll
10: Bob Duffy
11: Bob Duffy
12: Bob Ferry
13: Bob Love
14: Bob Nash
15: Bob Quick
16: Bob Tough
17: Bob Wood
18: Bob Davis
19: Bob Evans
20: Bob Gross
21: Bob Naber
22: Don Ray
23: Rob Rose
24: Bob Royer
25: Bob Weiss
Pick one: 0
Results for Bob Sura:

You searched for "Maurice Taylor"
6 results found.
0: Maurice Taylor
1: Marlon Taylor
2: Maurice Ager
3: Maurice Baker
4: Maurice Carter
5: Mike Taylor
Pick one: 0
Results for Maurice Taylor:

You searched for "Charlie Ward"
8 results found.
0: Charlie Ward
1: Charlie Tyra
2: Charlie Bell
3: Charlie Black
4: Charlie Davis
5: Charlie Lowery
6: Charlie Paulk
7: Charlie Brown
Pick one: 0
Results for Charlie Ward:

You searched for "Clarence Weatherspoon"
1 result found.
Clarence Weatherspoon
Results for Clarence Weatherspoon:

You searched for "David Wesley"
8 results found.
0: David Wesley
1: David West
2: David Lee
3: David Lee
4: David Wear
5: Walt Wesley
6: David Gaines
7: David Rivers
Pick one: 0
Results for David Wesley:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-03-28,25-308,HOU,AWAY,UTA,W (+14),1,37:44,15,21,...,6,4,5,1,0,2,44,42.8,6,Tracy McGrady
1,2004-12-02,25-192,HOU,AWAY,DAL,L (-7),1,50:22,19,36,...,9,9,2,3,2,3,48,41.1,0,Tracy McGrady
2,2005-01-09,25-230,HOU,AWAY,DEN,W (+18),1,41:53,15,26,...,12,5,1,3,3,4,45,36.8,27,Tracy McGrady
3,2004-12-20,24-099,HOU,HOME,TOR,W (+12),1,32:33,13,16,...,10,1,0,1,2,4,40,34.8,13,Yao Ming
4,2004-12-31,25-221,HOU,HOME,MIL,W (+15),1,47:00,13,24,...,10,5,2,0,4,2,42,33.7,14,Tracy McGrady

In [15]:

HOU_2006_gamelog = []

for p in HOU_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2006_gamelog.append(player_log)
HOU_2006_gamelog = pd.concat(HOU_2006_gamelog)    
HOU_2006_gamelogs = HOU_2006_gamelog.copy()
HOU_2006_gamelogs['GAME_SCORE'] = HOU_2006_gamelogs['GAME_SCORE'].astype(float)
HOU_2006_games = HOU_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2006_games_csv = HOU_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2006_games.csv', index=False)
HOU_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2006_games.csv')
HOU_2006_games_proc.head()

You searched for "Rafer Alston"
1 result found.
Rafer Alston
Results for Rafer Alston:

You searched for "Derek Anderson"
12 results found.
0: Derek Anderson
1: Eric Anderson
2: Greg Anderson
3: Andrew Anderson
4: Dan Anderson
5: Dan Anderson
6: James Anderson
7: Jerome Anderson
8: Kenny Anderson
9: Kyle Anderson
10: Nick Anderson
11: Ron Anderson
Pick one: 0
Results for Derek Anderson:

You searched for "Jon Barry"
30 results found.
0: Jon Barry
1: John Barr
2: Moe Barr
3: Ron Perry
4: John Bagley
5: Ron Baker
6: John Barber
7: Brent Barry
8: Drew Barry
9: Rick Barry
10: Jay Carty
11: Bob Ferry
12: John Garris
13: Joe Harris
14: Don May
15: Don Ray
16: Jason Terry
17: John Warren
18: Vin Baker
19: Tom Barker
20: Mike Barr
21: Cory Carr
22: Ron Carter
23: Ron Harper
24: Jason Hart
25: Josh Hart
26: Jon Leuer
27: Jack Parr
28: Von Wafer
29: John Wall
Pick one: 0
Results for Jon Barry:

You searched for "Lonny Baxter"
3 results found.
0: Lonny Baxter
1: Sonny Parker
2: Kenny Battle
Pick one: 0
Results for Lonny Baxter:

You searched for "Keith Bogans"
5 results found.
0: Keith Bogans
1: Keith Owens
2: Keith Askins
3: Keith Booth
4: Keith Benson
Pick one: 0
Results for Keith Bogans:

You searched for "Ryan Bowen"
13 results found.
0: Ryan Bowen
1: Brian Bowen
2: Ryan Gomes
3: Jordan Bowden
4: Don Boven
5: Bruce Bowen
6: Stan Brown
7: Ray Owes
8: Ron Rowan
9: Jordan Bone
10: Ron Boone
11: Red Owens
12: Ryan Reid
Pick one: 0
Results for Ryan Bowen:

You searched for "Rick Brunson"
6 results found.
0: Rick Brunson
1: Ricky Blanton
2: Nick Johnson
3: Rich Johnson
4: Rick Wilson
5: Rickey Brown
Pick one: 0
Results for Rick Brunson:

You searched for "Josh Davis"
27 results found.
0: Josh Davis
1: Bob Davis
2: Jim Davis
3: Ron Davis
4: Josh Reaves
5: Josh Hall
6: Bob Davies
7: Ben Davis
8: Bill Davis
9: Brad Davis
10: Dale Davis
11: Ed Davis
12: Glen Davis
13: Johnny Davis
14: Lee Davis
15: Mark Davis
16: Mark Davis
17: Mel Davis
18: Mike Davis
19: Mike Davis
20: Monti Davis
21: Paul Davis
22: Ralph Davis
23: Red Davis
24: Walt Davis
25: Josh Hart
26: Josh Grant
Pick one: 0
Results for Josh Davis:

You searched for "Richie Frahm"
2 results found.
0: Richie Frahm
1: Richie Regan
Pick one: 0
Results for Richie Frahm:

You searched for "Stephen Graham"
1 result found.
Stephen Graham
Results for Stephen Graham:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Luther Head"
2 results found.
0: Luther Head
1: Luther Green
Pick one: 0
Results for Luther Head:

You searched for "Juwan Howard"
4 results found.
0: Juwan Howard
1: Brian Howard
2: Josh Howard
3: Juwan Morgan
Pick one: 0
Results for Juwan Howard:

You searched for "Maciej Lampe"
1 result found.
Maciej Lampe
Results for Maciej Lampe:

You searched for "John Lucas III"
2 results found.
0: John Lucas III
1: John Lucas
Pick one: 0
Results for John Lucas III:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Yao Ming"
6 results found.
0: Yao Ming
1: Dan King
2: Dave Bing
3: Jim King
4: Ron King
5: Tom King
Pick one: 0
Results for Yao Ming:

You searched for "Dikembe Mutombo"
1 result found.
Dikembe Mutombo
Results for Dikembe Mutombo:

You searched for "Moochie Norris"
1 result found.
Moochie Norris
Results for Moochie Norris:

You searched for "Stromile Swift"
1 result found.
Stromile Swift
Results for Stromile Swift:

You searched for "David Wesley"
8 results found.
0: David Wesley
1: David West
2: David Lee
3: David Lee
4: David Wear
5: Walt Wesley
6: David Gaines
7: David Rivers
Pick one: 0
Results for David Wesley:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-03-08,25-177,HOU,HOME,IND,W (+4),1,37:52,14,21,...,10,1,0,5,3,3,38,33.1,-2,Yao Ming
1,2006-03-15,25-184,HOU,HOME,DAL,L (-14),1,38:25,12,17,...,12,2,1,1,2,4,36,32.0,-9,Yao Ming
2,2005-12-06,26-196,HOU,HOME,BOS,W (+18),1,38:21,14,20,...,7,5,2,2,2,4,35,32.0,21,Tracy McGrady
3,2006-03-29,25-198,HOU,HOME,SEA,W (+28),1,29:58,9,14,...,10,5,3,1,2,2,29,31.8,29,Yao Ming
4,2006-02-22,25-163,HOU,HOME,LAC,W (+4),1,35:41,11,16,...,15,1,1,2,0,1,29,31.4,8,Yao Ming

In [16]:

HOU_2007_gamelog = []

for p in HOU_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2007_gamelog.append(player_log)
HOU_2007_gamelog = pd.concat(HOU_2007_gamelog)    
HOU_2007_gamelogs = HOU_2007_gamelog.copy()
HOU_2007_gamelogs['GAME_SCORE'] = HOU_2007_gamelogs['GAME_SCORE'].astype(float)
HOU_2007_games = HOU_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2007_games_csv = HOU_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2007_games.csv', index=False)
HOU_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2007_games.csv')
HOU_2007_games_proc.head()

You searched for "Rafer Alston"
1 result found.
Rafer Alston
Results for Rafer Alston:

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Luther Head"
2 results found.
0: Luther Head
1: Luther Green
Pick one: 0
Results for Luther Head:

You searched for "Juwan Howard"
4 results found.
0: Juwan Howard
1: Brian Howard
2: Josh Howard
3: Juwan Morgan
Pick one: 0
Results for Juwan Howard:

You searched for "John Lucas III"
2 results found.
0: John Lucas III
1: John Lucas
Pick one: 0
Results for John Lucas III:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Yao Ming"
6 results found.
0: Yao Ming
1: Dan King
2: Dave Bing
3: Jim King
4: Ron King
5: Tom King
Pick one: 0
Results for Yao Ming:

You searched for "Dikembe Mutombo"
1 result found.
Dikembe Mutombo
Results for Dikembe Mutombo:

You searched for "Steve Novak"
9 results found.
0: Steve Novak
1: Steve Blake
2: Steve Jones
3: Steve Nash
4: Mike Novak
5: Steve Bardo
6: Steve Green
7: Steve Kerr
8: Steve Henson
Pick one: 0
Results for Steve Novak:

You searched for "Scott Padgett"
1 result found.
Scott Padgett
Results for Scott Padgett:

You searched for "Kirk Snyder"
4 results found.
0: Kirk Snyder
1: Dick Snyder
2: Kirk Penney
3: Kirk Haston
Pick one: 0
Results for Kirk Snyder:

You searched for "Vassilis Spanoulis"
1 result found.
Vassilis Spanoulis
Results for Vassilis Spanoulis:

You searched for "Jake Tsakalidis"
1 result found.
Jake Tsakalidis
Results for Jake Tsakalidis:

You searched for "Bonzi Wells"
3 results found.
0: Bonzi Wells
1: Bubba Wells
2: Owen Wells
Pick one: 0
Results for Bonzi Wells:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-01-16,27-237,HOU,AWAY,DAL,L (-13),1,40:14,17,29,...,5,7,1,1,1,1,45,37.4,0,Tracy McGrady
1,2006-12-09,26-088,HOU,AWAY,WAS,W (+5),1,39:21,13,19,...,11,2,1,6,4,2,38,34.2,7,Yao Ming
2,2007-01-31,27-252,HOU,HOME,SEA,W (+10),1,33:31,13,23,...,5,9,2,0,3,0,36,31.9,12,Tracy McGrady
3,2007-04-08,27-319,HOU,AWAY,SAC,W (+6),1,39:44,14,28,...,8,10,2,1,6,2,40,30.9,6,Tracy McGrady
4,2006-11-10,26-059,HOU,HOME,NYK,W (+9),1,38:10,15,21,...,17,2,1,7,8,3,35,30.3,20,Yao Ming

In [19]:

HOU_2008_gamelog = []

for p in HOU_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2008_gamelog.append(player_log)
HOU_2008_gamelog = pd.concat(HOU_2008_gamelog)    
HOU_2008_gamelogs = HOU_2008_gamelog.copy()
HOU_2008_gamelogs['GAME_SCORE'] = HOU_2008_gamelogs['GAME_SCORE'].astype(float)
HOU_2008_games = HOU_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2008_games_csv = HOU_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2008_games.csv', index=False)
HOU_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2008_games.csv')
HOU_2008_games_proc.head()

You searched for "Rafer Alston"
1 result found.
Rafer Alston
Results for Rafer Alston:

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Aaron Brooks"
5 results found.
0: Aaron Brooks
1: MarShon Brooks
2: Dillon Brooks
3: Kevin Brooks
4: Aaron Gordon
Pick one: 0
Results for Aaron Brooks:

You searched for "Steve Francis"
3 results found.
0: Steve Francis
1: Steve Bracey
2: Steve Harris
Pick one: 0
Results for Steve Francis:

You searched for "Gerald Green"
6 results found.
0: Gerald Green
1: Gerald Brown
2: Gerald Govan
3: Gerald Glass
4: Erick Green
5: Sean Green
Pick one: 0
Results for Gerald Green:

You searched for "Mike Harris"
26 results found.
0: Mike Harris
1: Mike Barr
2: Mike Davis
3: Mike Davis
4: Mike Harper
5: Joe Harris
6: Jalen Harris
7: Mike Barrett
8: Mike Farmer
9: Mike Hall
10: Art Harris
11: Billy Harris
12: Bob Harris
13: Elias Harris
14: Gary Harris
15: Manny Harris
16: Steve Harris
17: Tony Harris
18: Mike Higgins
19: Mike James
20: Mike James
21: Mike Kearns
22: Mike Lewis
23: Mike Morrison
24: Mike Price
25: Mike Taylor
Pick one: 0
Results for Mike Harris:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Luther Head"
2 results found.
0: Luther Head
1: Luther Green
Pick one: 0
Results for Luther Head:

You searched for "Bobby Jackson"
10 results found.
0: Bobby Jackson
1: Tony Jackson
2: Tony Jackson
3: Bobby Watson
4: Josh Jackson
5: Tracy Jackson
6: Bobby Wilson
7: Bobby Wilson
8: Bobby Jones
9: Bobby Jones
Pick one: 0
Results for Bobby Jackson:

You searched for "Mike James"
33 results found.
0: Mike James
1: Mike James
2: Mike Davis
3: Mike Davis
4: Mike Farmer
5: Mike Gale
6: Gene James
7: Tim James
8: Mike Niles
9: Mike Barr
10: Mike Evans
11: Mike Green
12: Mike Hall
13: Mike Harper
14: Mike Harris
15: Mike Jackson
16: Billy James
17: Damion James
18: Jake Jones
19: Mike Kearns
20: Mike Lewis
21: Mike Maloy
22: Mike McGee
23: Mike Sanders
24: Mike Smrek
25: Mike Tobey
26: Mike Wilks
27: Mike Bantom
28: Mike Bloom
29: Mike Bratz
30: Mike Novak
31: Mike Pratt
32: Mike Price
Pick one: 0
Results for Mike James:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Yao Ming"
6 results found.
0: Yao Ming
1: Dan King
2: Dave Bing
3: Jim King
4: Ron King
5: Tom King
Pick one: 0
Results for Yao Ming:

You searched for "Dikembe Mutombo"
1 result found.
Dikembe Mutombo
Results for Dikembe Mutombo:

You searched for "Steve Novak"
9 results found.
0: Steve Novak
1: Steve Blake
2: Steve Jones
3: Steve Nash
4: Mike Novak
5: Steve Bardo
6: Steve Green
7: Steve Kerr
8: Steve Henson
Pick one: 0
Results for Steve Novak:

You searched for "Luis Scola"
1 result found.
Luis Scola
Results for Luis Scola:

You searched for "Kirk Snyder"
4 results found.
0: Kirk Snyder
1: Dick Snyder
2: Kirk Penney
3: Kirk Haston
Pick one: 0
Results for Kirk Snyder:

You searched for "Bonzi Wells"
3 results found.
0: Bonzi Wells
1: Bubba Wells
2: Owen Wells
Pick one: 0
Results for Bonzi Wells:

You searched for "Justin Williams"
10 results found.
0: Justin Williams
1: Jason Williams
2: Alvin Williams
3: Gus Williams
4: Jayson Williams
5: John Williams
6: Jordan Williams
7: Kevin Williams
8: Marvin Williams
9: Sean Williams
Pick one: 0
Results for Justin Williams:

You searched for "Loren Woods"
3 results found.
0: Loren Woods
1: Leon Wood
2: Tommy Woods
Pick one: 0
Results for Loren Woods:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-03-08,28-289,HOU,HOME,NOH,W (+10),1,48:00,17,27,...,6,9,0,2,3,0,41,35.4,10,Tracy McGrady
1,2008-01-09,27-119,HOU,AWAY,NYK,W (+9),1,41:34,14,21,...,11,3,0,2,2,2,36,31.3,11,Yao Ming
2,2007-11-13,28-173,HOU,AWAY,MEM,L (-6),1,36:28,16,28,...,4,4,2,0,1,0,41,31.2,-1,Tracy McGrady
3,2007-11-11,27-060,HOU,AWAY,CHA,W (+3),1,39:56,13,15,...,8,4,0,3,6,4,34,29.2,8,Yao Ming
4,2008-01-21,27-131,HOU,HOME,SEA,W (+7),1,38:33,12,19,...,17,2,0,3,2,2,30,28.9,17,Yao Ming

In [24]:

HOU_2009_gamelog = []

for p in HOU_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2009_gamelog.append(player_log)
HOU_2009_gamelog = pd.concat(HOU_2009_gamelog)    
HOU_2009_gamelogs = HOU_2009_gamelog.copy()
HOU_2009_gamelogs['GAME_SCORE'] = HOU_2009_gamelogs['GAME_SCORE'].astype(float)
HOU_2009_games = HOU_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2009_games_csv = HOU_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2009_games.csv', index=False)
HOU_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2009_games.csv')
HOU_2009_games_proc.head()

You searched for "Rafer Alston"
1 result found.
Rafer Alston
Results for Rafer Alston:

You searched for "Brent Barry"
4 results found.
0: Brent Barry
1: Drew Barry
2: Jon Barry
3: Rick Barry
Pick one: 0
Results for Brent Barry:

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Aaron Brooks"
5 results found.
0: Aaron Brooks
1: MarShon Brooks
2: Dillon Brooks
3: Kevin Brooks
4: Aaron Gordon
Pick one: 0
Results for Aaron Brooks:

You searched for "Brian Cook"
9 results found.
0: Brian Cook
1: Quinn Cook
2: Brian Bowen
3: Bert Cook
4: Bobby Cook
5: Darwin Cook
6: Omar Cook
7: Brian Rowsom
8: Brian Shaw
Pick one: 0
Results for Brian Cook:

You searched for "Joey Dorsey"
4 results found.
0: Joey Dorsey
1: Jacky Dorsey
2: Ron Dorsey
3: Tyler Dorsey
Pick one: 0
Results for Joey Dorsey:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Luther Head"
2 results found.
0: Luther Head
1: Luther Green
Pick one: 0
Results for Luther Head:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Yao Ming"
6 results found.
0: Yao Ming
1: Dan King
2: Dave Bing
3: Jim King
4: Ron King
5: Tom King
Pick one: 0
Results for Yao Ming:

You searched for "Dikembe Mutombo"
1 result found.
Dikembe Mutombo
Results for Dikembe Mutombo:

You searched for "Luis Scola"
1 result found.
Luis Scola
Results for Luis Scola:

You searched for "Von Wafer"
14 results found.
0: Von Wafer
1: Ron Baker
2: Vin Baker
3: Ron Carter
4: Ron Harper
5: Jon Leuer
6: Thon Maker
7: Bob Naber
8: Ron Watts
9: Don Ford
10: Don Grate
11: Dean Wade
12: John Wall
13: Ron Rowan
Pick one: 0
Results for Von Wafer:

You searched for "James White"
10 results found.
0: James White
1: James Bailey
2: James Scott
3: James Webb
4: Jahidi White
5: Jo Jo White
6: Randy White
7: James Wilkes
8: James Worthy
9: James Ennis
Pick one: 0
Results for James White:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-12-05,28-084,HOU,HOME,GSW,W (+19),1,35:27,8,12,...,14,5,1,1,5,4,33,32.2,22,Yao Ming
1,2009-02-07,28-148,HOU,HOME,MIN,W (+17),1,36:23,12,18,...,6,1,1,5,1,1,30,29.0,14,Yao Ming
2,2008-10-30,28-048,HOU,AWAY,DAL,W (+10),1,40:44,11,15,...,13,3,0,2,3,3,30,28.7,12,Yao Ming
3,2008-12-19,28-098,HOU,HOME,SAC,W (+11),1,34:10,11,13,...,6,4,0,3,3,4,30,27.4,16,Yao Ming
4,2009-03-18,28-187,HOU,HOME,DET,W (+5),1,44:59,13,22,...,15,2,0,4,2,4,31,26.3,15,Yao Ming

In [25]:

HOU_2010_gamelog = []

for p in HOU_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2010_gamelog.append(player_log)
HOU_2010_gamelog = pd.concat(HOU_2010_gamelog)    
HOU_2010_gamelogs = HOU_2010_gamelog.copy()
HOU_2010_gamelogs['GAME_SCORE'] = HOU_2010_gamelogs['GAME_SCORE'].astype(float)
HOU_2010_games = HOU_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2010_games_csv = HOU_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2010_games.csv', index=False)
HOU_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2010_games.csv')
HOU_2010_games_proc.head()

You searched for "David Andersen"
4 results found.
0: David Andersen
1: Chris Andersen
2: Dan Anderson
3: Dan Anderson
Pick one: 0
Results for David Andersen:

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Hilton Armstrong"
1 result found.
Hilton Armstrong
Results for Hilton Armstrong:

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Aaron Brooks"
5 results found.
0: Aaron Brooks
1: MarShon Brooks
2: Dillon Brooks
3: Kevin Brooks
4: Aaron Gordon
Pick one: 0
Results for Aaron Brooks:

You searched for "Chase Budinger"
1 result found.
Chase Budinger
Results for Chase Budinger:

You searched for "Will Conroy"
6 results found.
0: Will Conroy
1: Will Cherry
2: Bill Crow
3: Bill Henry
4: Will Barton
5: Willie Long
Pick one: 0
Results for Will Conroy:

You searched for "Brian Cook"
9 results found.
0: Brian Cook
1: Quinn Cook
2: Brian Bowen
3: Bert Cook
4: Bobby Cook
5: Darwin Cook
6: Omar Cook
7: Brian Rowsom
8: Brian Shaw
Pick one: 0
Results for Brian Cook:

You searched for "Joey Dorsey"
4 results found.
0: Joey Dorsey
1: Jacky Dorsey
2: Ron Dorsey
3: Tyler Dorsey
Pick one: 0
Results for Joey Dorsey:

You searched for "Mike Harris"
26 results found.
0: Mike Harris
1: Mike Barr
2: Mike Davis
3: Mike Davis
4: Mike Harper
5: Joe Harris
6: Jalen Harris
7: Mike Barrett
8: Mike Farmer
9: Mike Hall
10: Art Harris
11: Billy Harris
12: Bob Harris
13: Elias Harris
14: Gary Harris
15: Manny Harris
16: Steve Harris
17: Tony Harris
18: Mike Higgins
19: Mike James
20: Mike James
21: Mike Kearns
22: Mike Lewis
23: Mike Morrison
24: Mike Price
25: Mike Taylor
Pick one: 0
Results for Mike Harris:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Jordan Hill"
8 results found.
0: Jordan Hill
1: Jordan Bell
2: Jordan Ford
3: Jordan Bone
4: Grant Hill
5: Jordan Loyd
6: Jordan Poole
7: John Mills
Pick one: 0
Results for Jordan Hill:

You searched for "Jared Jeffries"
1 result found.
Jared Jeffries
Results for Jared Jeffries:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Pops Mensah-Bonsu"
1 result found.
Pops Mensah-Bonsu
Results for Pops Mensah-Bonsu:

You searched for "Luis Scola"
1 result found.
Luis Scola
Results for Luis Scola:

You searched for "Jermaine Taylor"
1 result found.
Jermaine Taylor
Results for Jermaine Taylor:

You searched for "Garrett Temple"
1 result found.
Garrett Temple
Results for Garrett Temple:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-03-13,29-317,HOU,HOME,NJN,W (+8),1,41:20,20,25,...,12,3,2,1,4,2,44,39.7,9,Luis Scola
1,2009-11-02,26-274,SAC,HOME,MEM,W (+11),1,52:28,14,27,...,5,4,4,1,3,2,48,38.3,10,Kevin Martin
2,2010-01-13,24-364,HOU,HOME,MIN,W (+6),1,59:25,14,30,...,3,5,1,0,1,3,43,29.6,15,Aaron Brooks
3,2009-11-13,24-136,HOU,AWAY,SAC,L (-9),1,43:31,10,21,...,6,5,5,1,0,1,28,28.7,0,Trevor Ariza
4,2010-04-12,27-070,HOU,AWAY,SAC,W (+10),1,39:50,11,20,...,2,1,0,0,1,3,39,28.5,10,Kevin Martin

In [26]:

HOU_2011_gamelog = []

for p in HOU_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2011_gamelog.append(player_log)
HOU_2011_gamelog = pd.concat(HOU_2011_gamelog)    
HOU_2011_gamelogs = HOU_2011_gamelog.copy()
HOU_2011_gamelogs['GAME_SCORE'] = HOU_2011_gamelogs['GAME_SCORE'].astype(float)
HOU_2011_games = HOU_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2011_games_csv = HOU_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2011_games.csv', index=False)
HOU_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2011_games.csv')
HOU_2011_games_proc.head()

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Aaron Brooks"
5 results found.
0: Aaron Brooks
1: MarShon Brooks
2: Dillon Brooks
3: Kevin Brooks
4: Aaron Gordon
Pick one: 0
Results for Aaron Brooks:

You searched for "Chase Budinger"
1 result found.
Chase Budinger
Results for Chase Budinger:

You searched for "DeMarre Carroll"
1 result found.
DeMarre Carroll
Results for DeMarre Carroll:

You searched for "Goran Dragić"
2 results found.
0: Goran Dragic
1: Zoran Dragic
Pick one: 0
Results for Goran Dragic:

You searched for "Mike Harris"
26 results found.
0: Mike Harris
1: Mike Barr
2: Mike Davis
3: Mike Davis
4: Mike Harper
5: Joe Harris
6: Jalen Harris
7: Mike Barrett
8: Mike Farmer
9: Mike Hall
10: Art Harris
11: Billy Harris
12: Bob Harris
13: Elias Harris
14: Gary Harris
15: Manny Harris
16: Steve Harris
17: Tony Harris
18: Mike Higgins
19: Mike James
20: Mike James
21: Mike Kearns
22: Mike Lewis
23: Mike Morrison
24: Mike Price
25: Mike Taylor
Pick one: 0
Results for Mike Harris:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Jordan Hill"
8 results found.
0: Jordan Hill
1: Jordan Bell
2: Jordan Ford
3: Jordan Bone
4: Grant Hill
5: Jordan Loyd
6: Jordan Poole
7: John Mills
Pick one: 0
Results for Jordan Hill:

You searched for "Jared Jeffries"
1 result found.
Jared Jeffries
Results for Jared Jeffries:

You searched for "Courtney Lee"
3 results found.
0: Courtney Lee
1: Courtney Sims
2: Joe Courtney
Pick one: 0
Results for Courtney Lee:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Brad Miller"
12 results found.
0: Brad Miller
1: Bill Miller
2: Bob Miller
3: Jay Miller
4: Brad Sellers
5: Grant Riller
6: Dick Miller
7: Harry Miller
8: Larry Miller
9: Mike Miller
10: Walt Miller
11: Brady Walker
Pick one: 0
Results for Brad Miller:

You searched for "Yao Ming"
6 results found.
0: Yao Ming
1: Dan King
2: Dave Bing
3: Jim King
4: Ron King
5: Tom King
Pick one: 0
Results for Yao Ming:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "Luis Scola"
1 result found.
Luis Scola
Results for Luis Scola:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Jermaine Taylor"
1 result found.
Jermaine Taylor
Results for Jermaine Taylor:

You searched for "Hasheem Thabeet"
1 result found.
Hasheem Thabeet
Results for Hasheem Thabeet:

You searched for "Terrence Williams"
3 results found.
0: Terrence Williams
1: Bernie Williams
2: Derrick Williams
Pick one: 0
Results for Terrence Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2011-01-05,27-338,HOU,HOME,POR,L (-3),1,39:04,13,18,...,2,4,0,0,4,2,45,35.4,6,Kevin Martin
1,2011-02-16,24-328,HOU,HOME,PHI,L (-9),1,43:09,15,18,...,4,7,1,0,1,3,36,33.9,-6,Kyle Lowry
2,2011-03-20,24-360,HOU,HOME,UTA,W (+2),1,43:39,9,14,...,11,10,3,0,1,3,28,33.7,0,Kyle Lowry
3,2010-12-11,27-313,HOU,HOME,CLE,W (+15),1,33:30,12,19,...,2,2,0,0,1,1,40,31.7,15,Kevin Martin
4,2010-10-27,30-180,HOU,AWAY,GSW,L (-4),1,37:33,14,24,...,16,0,1,1,0,0,36,31.3,-10,Luis Scola

In [29]:

HOU_2012_gamelog = []

for p in HOU_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2012_gamelog.append(player_log)
HOU_2012_gamelog = pd.concat(HOU_2012_gamelog)    
HOU_2012_gamelogs = HOU_2012_gamelog.copy()
HOU_2012_gamelogs['GAME_SCORE'] = HOU_2012_gamelogs['GAME_SCORE'].astype(float)
HOU_2012_games = HOU_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2012_games_csv = HOU_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2012_games.csv', index=False)
HOU_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2012_games.csv')
HOU_2012_games_proc.head()

You searched for "Jeff Adrien"
10 results found.
0: Jeff Adrien
1: Jeff Ayres
2: Jeff Green
3: Jeff Martin
4: Jeff Turner
5: Jeff Grayer
6: Jeff Malone
7: Jeff Ruland
8: Jeff Sanders
9: Jeff Taylor
Pick one: 0
Results for Jeff Adrien:

You searched for "Earl Boykins"
1 result found.
Earl Boykins
Results for Earl Boykins:

You searched for "Chase Budinger"
1 result found.
Chase Budinger
Results for Chase Budinger:

You searched for "Marcus Camby"
6 results found.
0: Marcus Camby
1: Marcus Banks
2: Marcus Landry
3: Marcus Paige
4: Marcus Webb
5: Marcus Smart
Pick one: 0
Results for Marcus Camby:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Goran Dragić"
2 results found.
0: Goran Dragic
1: Zoran Dragic
Pick one: 0
Results for Goran Dragic:

You searched for "Jonny Flynn"
4 results found.
0: Jonny Flynn
1: Danny Finn
2: Lonnie Lynn
3: Johnny Egan
Pick one: 0
Results for Jonny Flynn:

You searched for "Courtney Fortson"
1 result found.
Courtney Fortson
Results for Courtney Fortson:

You searched for "Jordan Hill"
8 results found.
0: Jordan Hill
1: Jordan Bell
2: Jordan Ford
3: Jordan Bone
4: Grant Hill
5: Jordan Loyd
6: Jordan Poole
7: John Mills
Pick one: 0
Results for Jordan Hill:

You searched for "Courtney Lee"
3 results found.
0: Courtney Lee
1: Courtney Sims
2: Joe Courtney
Pick one: 0
Results for Courtney Lee:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Marcus Morris"
5 results found.
0: Marcus Morris
1: Darius Morris
2: Marcus Cousin
3: Chris Morris
4: Max Morris
Pick one: 0
Results for Marcus Morris:

You searched for "Chandler Parsons"
1 result found.
Chandler Parsons
Results for Chandler Parsons:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "Luis Scola"
1 result found.
Luis Scola
Results for Luis Scola:

You searched for "Hasheem Thabeet"
1 result found.
Hasheem Thabeet
Results for Hasheem Thabeet:

You searched for "Terrence Williams"
3 results found.
0: Terrence Williams
1: Bernie Williams
2: Derrick Williams
Pick one: 0
Results for Terrence Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-02-19,25-331,HOU,HOME,UTA,W (+16),1,37:55,9,13,...,1,9,1,0,1,3,32,31.9,22,Kyle Lowry
1,2012-03-02,29-030,HOU,HOME,DEN,L (-12),1,42:01,10,15,...,3,4,0,1,4,4,35,27.3,0,Kevin Martin
2,2012-02-15,29-014,HOU,HOME,OKC,W (+1),1,37:52,10,18,...,1,3,2,0,1,2,32,26.0,3,Kevin Martin
3,2012-01-13,30-248,HOU,HOME,SAC,W (+14),1,33:28,9,11,...,16,0,1,4,1,3,21,25.7,21,Samuel Dalembert
4,2012-01-13,25-294,HOU,HOME,SAC,W (+14),1,41:02,7,15,...,7,9,2,0,2,3,25,25.3,27,Kyle Lowry

In [32]:
HOU_2013_gamelog = []

for p in HOU_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2013_gamelog.append(player_log)
HOU_2013_gamelog = pd.concat(HOU_2013_gamelog)    
HOU_2013_gamelogs = HOU_2013_gamelog.copy()
HOU_2013_gamelogs['GAME_SCORE'] = HOU_2013_gamelogs['GAME_SCORE'].astype(float)
HOU_2013_games = HOU_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2013_games_csv = HOU_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2013_games.csv', index=False)
HOU_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2013_games.csv')
HOU_2013_games_proc.head()

You searched for "Cole Aldrich"
1 result found.
Cole Aldrich
Results for Cole Aldrich:

You searched for "James Anderson"
10 results found.
0: James Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Derek Anderson
5: Greg Anderson
6: J.J. Anderson
7: Jerome Anderson
8: Kim Anderson
9: Kyle Anderson
Pick one: 0
Results for James Anderson:

You searched for "Ömer Aşık"
2 results found.
0: Omer Asik
1: Omar Cook
Pick one: 0
Results for Omer Asik:

You searched for "Patrick Beverley"
1 result found.
Patrick Beverley
Results for Patrick Beverley:

You searched for "Aaron Brooks"
5 results found.
0: Aaron Brooks
1: MarShon Brooks
2: Dillon Brooks
3: Kevin Brooks
4: Aaron Gordon
Pick one: 0
Results for Aaron Brooks:

You searched for "Daequan Cook"
2 results found.
0: Daequan Cook
1: Darwin Cook
Pick one: 0
Results for Daequan Cook:

You searched for "Carlos Delfino"
1 result found.
Carlos Delfino
Results for Carlos Delfino:

You searched for "Toney Douglas"
4 results found.
0: Toney Douglas
1: John Douglas
2: Leon Douglas
3: Tony Dumas
Pick one: 0
Results for Toney Douglas:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "Terrence Jones"
3 results found.
0: Terrence Jones
1: Terrence Ross
2: Derrick Jones
Pick one: 0
Results for Terrence Jones:

You searched for "Jeremy Lin"
5 results found.
0: Jeremy Lin
1: Jeremy Lamb
2: Jeremy Evans
3: Jerome Lane
4: Jeremy Tyler
Pick one: 0
Results for Jeremy Lin:

You searched for "Scott Machado"
1 result found.
Scott Machado
Results for Scott Machado:

You searched for "Marcus Morris"
5 results found.
0: Marcus Morris
1: Darius Morris
2: Marcus Cousin
3: Chris Morris
4: Max Morris
Pick one: 0
Results for Marcus Morris:

You searched for "Donatas Motiejūnas"
1 result found.
Donatas Motiejunas
Results for Donatas Motiejunas:

You searched for "Tim Ohlbrecht"
1 result found.
Tim Ohlbrecht
Results for Tim Ohlbrecht:

You searched for "Chandler Parsons"
1 result found.
Chandler Parsons
Results for Chandler Parsons:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "Thomas Robinson"
4 results found.
0: Thomas Robinson
1: Chris Robinson
2: Jamal Robinson
3: James Robinson
Pick one: 0
Results for Thomas Robinson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-02-20,23-178,HOU,HOME,OKC,W (+3),1,44:14,14,19,...,7,6,2,1,2,2,46,44.5,8,James Harden
1,2014-03-22,24-208,HOU,AWAY,CLE,W (+7),1,29:28,9,15,...,3,10,4,1,1,1,37,41.3,20,James Harden
2,2014-02-25,24-183,HOU,AWAY,SAC,W (+26),1,31:10,11,20,...,2,8,3,0,5,2,43,36.4,29,James Harden
3,2013-02-08,23-166,HOU,HOME,POR,W (+15),1,37:47,13,16,...,7,11,1,0,3,2,35,36.0,21,James Harden
4,2013-02-06,23-164,HOU,AWAY,MIA,L (-6),1,40:45,10,16,...,12,7,3,0,4,3,36,35.5,-7,James Harden

In [35]:
HOU_2014_gamelog = []

for p in HOU_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2014_gamelog.append(player_log)
HOU_2014_gamelog = pd.concat(HOU_2014_gamelog)    
HOU_2014_gamelogs = HOU_2014_gamelog.copy()
HOU_2014_gamelogs['GAME_SCORE'] = HOU_2014_gamelogs['GAME_SCORE'].astype(float)
HOU_2014_games = HOU_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2014_games_csv = HOU_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2014_games.csv', index=False)
HOU_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2014_games.csv')
HOU_2014_games_proc.head()

You searched for "Ömer Aşık"
2 results found.
0: Omer Asik
1: Omar Cook
Pick one: 0
Results for Omer Asik:

You searched for "Patrick Beverley"
1 result found.
Patrick Beverley
Results for Patrick Beverley:

You searched for "Ronnie Brewer"
4 results found.
0: Ronnie Brewer
1: Ron Brewer
2: Ronnie Lester
3: Ronnie Price
Pick one: 0
Results for Ronnie Brewer:

You searched for "Aaron Brooks"
5 results found.
0: Aaron Brooks
1: MarShon Brooks
2: Dillon Brooks
3: Kevin Brooks
4: Aaron Gordon
Pick one: 0
Results for Aaron Brooks:

You searched for "Isaiah Canaan"
1 result found.
Isaiah Canaan
Results for Isaiah Canaan:

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Robert Covington"
1 result found.
Robert Covington
Results for Robert Covington:

You searched for "Troy Daniels"
4 results found.
0: Troy Daniels
1: Erik Daniels
2: Lloyd Daniels
3: Mel Daniels
Pick one: 0
Results for Troy Daniels:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Jordan Hamilton"
4 results found.
0: Jordan Hamilton
1: Joe Hamilton
2: Justin Hamilton
3: Zendon Hamilton
Pick one: 0
Results for Jordan Hamilton:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Terrence Jones"
3 results found.
0: Terrence Jones
1: Terrence Ross
2: Derrick Jones
Pick one: 0
Results for Terrence Jones:

You searched for "Jeremy Lin"
5 results found.
0: Jeremy Lin
1: Jeremy Lamb
2: Jeremy Evans
3: Jerome Lane
4: Jeremy Tyler
Pick one: 0
Results for Jeremy Lin:

You searched for "Donatas Motiejūnas"
1 result found.
Donatas Motiejunas
Results for Donatas Motiejunas:

You searched for "Chandler Parsons"
1 result found.
Chandler Parsons
Results for Chandler Parsons:

You searched for "Josh Powell"
7 results found.
0: Josh Powell
1: Josh Hall
2: Josh Howard
3: Kasib Powell
4: Roger Powell
5: Josh Selby
6: Josh Okogie
Pick one: 0
Results for Josh Powell:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-03-22,24-208,HOU,AWAY,CLE,W (+7),1,29:28,9,15,...,3,10,4,1,1,1,37,41.3,20,James Harden
1,2014-02-25,24-183,HOU,AWAY,SAC,W (+26),1,31:10,11,20,...,2,8,3,0,5,2,43,36.4,29,James Harden
2,2014-01-18,22-009,HOU,HOME,MIL,W (+10),1,38:16,14,20,...,11,1,1,2,0,1,36,34.8,15,Terrence Jones
3,2014-03-09,24-195,HOU,HOME,POR,W (+5),1,47:12,12,28,...,10,6,6,1,4,5,41,34.5,10,James Harden
4,2014-04-08,24-225,HOU,AWAY,LAL,W (+15),1,31:46,10,15,...,3,12,0,1,1,3,33,34.3,26,James Harden

In [38]:
# removed clint capella
HOU_2015_gamelog = []

for p in HOU_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2015_gamelog.append(player_log)
HOU_2015_gamelog = pd.concat(HOU_2015_gamelog)    
HOU_2015_gamelogs = HOU_2015_gamelog.copy()
HOU_2015_gamelogs['GAME_SCORE'] = HOU_2015_gamelogs['GAME_SCORE'].astype(float)
HOU_2015_games = HOU_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2015_games_csv = HOU_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2015_games.csv', index=False)
HOU_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2015_games.csv')
HOU_2015_games_proc.head()

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Patrick Beverley"
1 result found.
Patrick Beverley
Results for Patrick Beverley:

You searched for "Tarik Black"
3 results found.
0: Tarik Black
1: Charlie Black
2: Tom Black
Pick one: 0
Results for Tarik Black:

You searched for "Corey Brewer"
4 results found.
0: Corey Brewer
1: Corey Crowder
2: Corey Beck
3: Ron Brewer
Pick one: 0
Results for Corey Brewer:

You searched for "Isaiah Canaan"
1 result found.
Isaiah Canaan
Results for Isaiah Canaan:

You searched for "Troy Daniels"
4 results found.
0: Troy Daniels
1: Erik Daniels
2: Lloyd Daniels
3: Mel Daniels
Pick one: 0
Results for Troy Daniels:

You searched for "Joey Dorsey"
4 results found.
0: Joey Dorsey
1: Jacky Dorsey
2: Ron Dorsey
3: Tyler Dorsey
Pick one: 0
Results for Joey Dorsey:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Nick Johnson"
32 results found.
0: Nick Johnson
1: Buck Johnson
2: Rich Johnson
3: Brice Johnson
4: Eric Johnson
5: Mickey Johnson
6: Neil Johnson
7: Rick Brunson
8: Nick Collison
9: Alize Johnson
10: Amir Johnson
11: Andy Johnson
12: Arnie Johnson
13: B.J. Johnson
14: Clay Johnson
15: Dave Johnson
16: Ed Johnson
17: Frank Johnson
18: Gus Johnson
19: Ivan Johnson
20: Joe Johnson
21: John Johnson
22: Ken Johnson
23: Ken Johnson
24: Lee Johnson
25: Magic Johnson
26: Ron Johnson
27: Stew Johnson
28: Trey Johnson
29: Nate Johnston
30: Neil Johnston
31: Nick Jones
Pick one: 0
Results for Nick Johnson:

You searched for "Terrence Jones"
3 results found.
0: Terrence Jones
1: Terrence Ross
2: Derrick Jones
Pick one: 0
Results for Terrence Jones:

You searched for "K.J. McDaniels"
2 results found.
0: K.J. McDaniels
1: Jim McDaniels
Pick one: 0
Results for K.J. McDaniels:

You searched for "Donatas Motiejūnas"
1 result found.
Donatas Motiejunas
Results for Donatas Motiejunas:

You searched for "Kostas Papanikolaou"
1 result found.
Kostas Papanikolaou
Results for Kostas Papanikolaou:

You searched for "Pablo Prigioni"
1 result found.
Pablo Prigioni
Results for Pablo Prigioni:

You searched for "Alexey Shved"
1 result found.
Alexey Shved
Results for Alexey Shved:

You searched for "Josh Smith"
39 results found.
0: Josh Smith
1: Ish Smith
2: Joe Smith
3: John Smith
4: Don Smith
5: Don Smith
6: Doug Smith
7: J.R. Smith
8: Jason Smith
9: Jim Smith
10: Russ Smith
11: Tony Smith
12: Joe Smyth
13: Jalen Smith
14: Josh Hart
15: Josh Selby
16: Al Smith
17: Bill Smith
18: Bobby Smith
19: Deb Smith
20: Donta Smith
21: Ed Smith
22: Greg Smith
23: Greg Smith
24: Jerry Smith
25: Keith Smith
26: Ken Smith
27: Leon Smith
28: Mike Smith
29: Nolan Smith
30: Otis Smith
31: Pete Smith
32: Phil Smith
33: Sam Smith
34: Sam Smith
35: Tom Stith
36: Josh Hall
37: Josh Davis
38: Josh Grant
Pick one: 0
Results for Josh Smith:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-01-19,25-146,HOU,HOME,IND,W (+12),1,39:56,12,18,...,1,7,4,1,5,0,45,42.1,17,James Harden
1,2015-04-01,25-218,HOU,HOME,SAC,W (+4),1,37:33,16,25,...,8,6,3,0,7,1,51,42.1,10,James Harden
2,2014-12-22,25-118,HOU,HOME,POR,W (+15),1,31:50,14,26,...,3,7,5,0,1,2,44,40.0,19,James Harden
3,2015-02-08,25-166,HOU,HOME,POR,L (-11),1,39:50,11,25,...,9,8,2,0,4,2,45,37.4,-5,James Harden
4,2015-02-10,25-168,HOU,AWAY,PHO,W (+9),1,42:39,13,23,...,12,9,3,1,5,1,40,37.3,16,James Harden

In [47]:
# removed clint capella
HOU_2016_gamelog = []

for p in HOU_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2016_gamelog.append(player_log)
HOU_2016_gamelog = pd.concat(HOU_2016_gamelog)    
HOU_2016_gamelogs = HOU_2016_gamelog.copy()
HOU_2016_gamelogs['GAME_SCORE'] = HOU_2016_gamelogs['GAME_SCORE'].astype(float)
HOU_2016_games = HOU_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2016_games_csv = HOU_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2016_games.csv', index=False)
HOU_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2016_games.csv')
HOU_2016_games_proc.head()

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Michael Beasley"
5 results found.
0: Michael Beasley
1: Michael Bradley
2: Michael Ansley
3: Michael Finley
4: Michael Wiley
Pick one: 0
Results for Michael Beasley:

You searched for "Patrick Beverley"
1 result found.
Patrick Beverley
Results for Patrick Beverley:

You searched for "Corey Brewer"
4 results found.
0: Corey Brewer
1: Corey Crowder
2: Corey Beck
3: Ron Brewer
Pick one: 0
Results for Corey Brewer:

You searched for "Sam Dekker"
1 result found.
Sam Dekker
Results for Sam Dekker:

You searched for "Andrew Goudelock"
1 result found.
Andrew Goudelock
Results for Andrew Goudelock:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "Montrezl Harrell"
1 result found.
Montrezl Harrell
Results for Montrezl Harrell:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Terrence Jones"
3 results found.
0: Terrence Jones
1: Terrence Ross
2: Derrick Jones
Pick one: 0
Results for Terrence Jones:

You searched for "Ty Lawson"
3 results found.
0: Ty Lawson
1: Tony Dawson
2: Mo Layton
Pick one: 0
Results for Ty Lawson:

You searched for "K.J. McDaniels"
2 results found.
0: K.J. McDaniels
1: Jim McDaniels
Pick one: 0
Results for K.J. McDaniels:

You searched for "Donatas Motiejūnas"
1 result found.
Donatas Motiejunas
Results for Donatas Motiejunas:

You searched for "Josh Smith"
39 results found.
0: Josh Smith
1: Ish Smith
2: Joe Smith
3: John Smith
4: Don Smith
5: Don Smith
6: Doug Smith
7: J.R. Smith
8: Jason Smith
9: Jim Smith
10: Russ Smith
11: Tony Smith
12: Joe Smyth
13: Jalen Smith
14: Josh Hart
15: Josh Selby
16: Al Smith
17: Bill Smith
18: Bobby Smith
19: Deb Smith
20: Donta Smith
21: Ed Smith
22: Greg Smith
23: Greg Smith
24: Jerry Smith
25: Keith Smith
26: Ken Smith
27: Leon Smith
28: Mike Smith
29: Nolan Smith
30: Otis Smith
31: Pete Smith
32: Phil Smith
33: Sam Smith
34: Sam Smith
35: Tom Stith
36: Josh Hall
37: Josh Davis
38: Josh Grant
Pick one: 0
Results for Josh Smith:

You searched for "Jason Terry"
8 results found.
0: Jason Terry
1: Jon Barry
2: JamesOn Curry
3: Jason Hart
4: Ron Perry
5: Carlos Terry
6: Jason Smith
7: Jason Sasser
Pick one: 0
Results for Jason Terry:

You searched for "Marcus Thornton"
2 results found.
0: Marcus Thornton
1: Dallas Thornton
Pick one: 0
Results for Marcus Thornton:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-01-30,26-157,HOU,HOME,WAS,L (-1),1,37:20,12,20,...,7,11,4,0,2,5,40,41.0,-2,James Harden
1,2015-11-18,26-084,HOU,HOME,POR,W (+5),1,47:24,11,29,...,8,11,5,1,5,2,45,39.1,10,James Harden
2,2016-01-18,30-041,HOU,AWAY,LAC,L (-8),1,45:29,11,16,...,26,4,1,1,4,2,36,39.1,-5,Dwight Howard
3,2016-03-06,26-193,HOU,AWAY,TOR,W (+6),1,42:41,11,20,...,5,14,1,0,1,4,40,38.5,17,James Harden
4,2015-11-06,26-072,HOU,AWAY,SAC,W (+6),1,41:51,13,23,...,6,13,2,0,7,0,43,37.6,24,James Harden

In [51]:
# removed clint capella
# removed nene hilario

HOU_2017_gamelog = []

for p in HOU_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2017_gamelog.append(player_log)
HOU_2017_gamelog = pd.concat(HOU_2017_gamelog)    
HOU_2017_gamelogs = HOU_2017_gamelog.copy()
HOU_2017_gamelogs['GAME_SCORE'] = HOU_2017_gamelogs['GAME_SCORE'].astype(float)
HOU_2017_games = HOU_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2017_games_csv = HOU_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2017_games.csv', index=False)
HOU_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2017_games.csv')
HOU_2017_games_proc.head()

You searched for "Ryan Anderson"
14 results found.
0: Ryan Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ron Anderson
5: Kyle Anderson
6: Eric Anderson
7: Greg Anderson
8: J.J. Anderson
9: Kenny Anderson
10: Kim Anderson
11: Nick Anderson
12: Alan Henderson
13: Ryan Robertson
Pick one: 0
Results for Ryan Anderson:

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Patrick Beverley"
1 result found.
Patrick Beverley
Results for Patrick Beverley:

You searched for "Corey Brewer"
4 results found.
0: Corey Brewer
1: Corey Crowder
2: Corey Beck
3: Ron Brewer
Pick one: 0
Results for Corey Brewer:

You searched for "Bobby Brown"
14 results found.
0: Bobby Brown
1: Bob Brown
2: Tony Brown
3: Bobby Croft
4: Bruce Brown
5: John Brown
6: Larry Brown
7: Moses Brown
8: Randy Brown
9: Roger Brown
10: Roger Brown
11: Troy Brown
12: Bobby Cook
13: Bobby Lloyd
Pick one: 0
Results for Bobby Brown:

You searched for "Sam Dekker"
1 result found.
Sam Dekker
Results for Sam Dekker:

You searched for "Tyler Ennis"
6 results found.
0: Tyler Ennis
1: Tyler Davis
2: Tyler Ulis
3: James Ennis
4: Tyler Herro
5: Tyler Lydon
Pick one: 0
Results for Tyler Ennis:

You searched for "Eric Gordon"
12 results found.
0: Eric Gordon
1: Drew Gordon
2: Eric Dawson
3: Aaron Gordon
4: Ben Gordon
5: Paul Gordon
6: Erick Green
7: Eric Johnson
8: Phil Jordon
9: Eric Murdock
10: Eric Maynor
11: Eric Money
Pick one: 0
Results for Eric Gordon:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "Montrezl Harrell"
1 result found.
Montrezl Harrell
Results for Montrezl Harrell:

You searched for "K.J. McDaniels"
2 results found.
0: K.J. McDaniels
1: Jim McDaniels
Pick one: 0
Results for K.J. McDaniels:

You searched for "Chinanu Onuaku"
1 result found.
Chinanu Onuaku
Results for Chinanu Onuaku:

You searched for "Isaiah Taylor"
3 results found.
0: Isaiah Taylor
1: Brian Taylor
2: Isaiah Thomas
Pick one: 0
Results for Isaiah Taylor:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

You searched for "Troy Williams"
46 results found.
0: Troy Williams
1: Ray Williams
2: Rob Williams
3: Ron Williams
4: Aaron Williams
5: Art Williams
6: Bob Williams
7: Corey Williams
8: Deron Williams
9: Eric Williams
10: Fly Williams
11: Guy Williams
12: Jay Williams
13: Lou Williams
14: Mo Williams
15: Sly Williams
16: Al Williams
17: Alan Williams
18: Buck Williams
19: C.J. Williams
20: Duck Williams
21: Earl Williams
22: Frank Williams
23: Gene Williams
24: Grant Williams
25: Gus Williams
26: Hank Williams
27: Herb Williams
28: Hot Rod Williams
29: Jason Williams
30: Jerome Williams
31: John Williams
32: Kenny Williams
33: Matt Williams
34: Mike Williams
35: Milt Williams
36: Monty Williams
37: Nate Williams
38: Pete Williams
39: Sam Williams
40: Sam Williams
41: Scott Williams
42: Sean Williams
43: Travis Williams
44: Walt Williams
45: Ward Williams
Pick one: 0
Results for Troy Williams:

You searched for "Kyle Wiltjer"
3 results found.
0: Kyle Wiltjer
1: Kyle Singler
2: Kyle Weaver
Pick one: 0
Results for Kyle Wiltjer:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-12-31,27-127,HOU,HOME,NYK,W (+7),1,42:05,14,26,...,16,17,0,0,8,2,53,48.7,13,James Harden
1,2017-01-27,27-154,HOU,AWAY,PHI,W (+5),1,39:09,16,28,...,13,13,2,1,5,4,51,46.9,13,James Harden
2,2016-11-01,27-067,HOU,AWAY,CLE,L (-8),1,38:10,13,20,...,7,15,1,0,1,3,41,42.4,10,James Harden
3,2017-03-17,27-203,HOU,AWAY,NOP,L (-16),1,39:35,12,21,...,14,11,2,0,5,2,41,39.6,-12,James Harden
4,2017-03-24,27-210,HOU,HOME,NOP,W (+10),1,37:45,12,24,...,7,17,2,1,3,2,38,38.5,12,James Harden

In [52]:
# removed clint capella
# removed nene hilario

HOU_2018_gamelog = []

for p in HOU_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2018_gamelog.append(player_log)
HOU_2018_gamelog = pd.concat(HOU_2018_gamelog)    
HOU_2018_gamelogs = HOU_2018_gamelog.copy()
HOU_2018_gamelogs['GAME_SCORE'] = HOU_2018_gamelogs['GAME_SCORE'].astype(float)
HOU_2018_games = HOU_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2018_games_csv = HOU_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2018_games.csv', index=False)
HOU_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2018_games.csv')
HOU_2018_games_proc.head()

You searched for "Ryan Anderson"
14 results found.
0: Ryan Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ron Anderson
5: Kyle Anderson
6: Eric Anderson
7: Greg Anderson
8: J.J. Anderson
9: Kenny Anderson
10: Kim Anderson
11: Nick Anderson
12: Alan Henderson
13: Ryan Robertson
Pick one: 0
Results for Ryan Anderson:

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Tarik Black"
3 results found.
0: Tarik Black
1: Charlie Black
2: Tom Black
Pick one: 0
Results for Tarik Black:

You searched for "Bobby Brown"
14 results found.
0: Bobby Brown
1: Bob Brown
2: Tony Brown
3: Bobby Croft
4: Bruce Brown
5: John Brown
6: Larry Brown
7: Moses Brown
8: Randy Brown
9: Roger Brown
10: Roger Brown
11: Troy Brown
12: Bobby Cook
13: Bobby Lloyd
Pick one: 0
Results for Bobby Brown:

You searched for "Markel Brown"
14 results found.
0: Markel Brown
1: Darrell Brown
2: Marcus Brown
3: Mike Brown
4: Fred Brown
5: Harold Brown
6: Jaylen Brown
7: Larry Brown
8: Moses Brown
9: Myron Brown
10: Rickey Brown
11: Mark Crow
12: Mark Blount
13: Mark Bryant
Pick one: 0
Results for Markel Brown:

You searched for "Isaiah Canaan"
1 result found.
Isaiah Canaan
Results for Isaiah Canaan:

You searched for "Eric Gordon"
12 results found.
0: Eric Gordon
1: Drew Gordon
2: Eric Dawson
3: Aaron Gordon
4: Ben Gordon
5: Paul Gordon
6: Erick Green
7: Eric Johnson
8: Phil Jordon
9: Eric Murdock
10: Eric Maynor
11: Eric Money
Pick one: 0
Results for Eric Gordon:

You searched for "Gerald Green"
6 results found.
0: Gerald Green
1: Gerald Brown
2: Gerald Govan
3: Gerald Glass
4: Erick Green
5: Sean Green
Pick one: 0
Results for Gerald Green:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "R.J. Hunter"
4 results found.
0: R.J. Hunter
1: Les Hunter
2: P.J. Tucker
3: A.J. Wynder
Pick one: 0
Results for R.J. Hunter:

You searched for "Aaron Jackson"
16 results found.
0: Aaron Jackson
1: Jaren Jackson
2: Jaren Jackson
3: Myron Jackson
4: Marc Jackson
5: Mark Jackson
6: Aaron Harrison
7: Al Jackson
8: Frank Jackson
9: Greg Jackson
10: Mervin Jackson
11: Ralph Jackson
12: Tony Jackson
13: Tony Jackson
14: Aaron James
15: Aaron Swinson
Pick one: 0
Results for Aaron Jackson:

You searched for "Demetrius Jackson"
1 result found.
Demetrius Jackson
Results for Demetrius Jackson:

You searched for "Joe Johnson"
40 results found.
0: Joe Johnson
1: John Johnson
2: Lee Johnson
3: Ron Johnson
4: Dave Johnson
5: Ed Johnson
6: Gus Johnson
7: James Johnson
8: Ken Johnson
9: Ken Johnson
10: Stew Johnson
11: Trey Johnson
12: Joe Binion
13: Joe Dolhon
14: Alize Johnson
15: Amir Johnson
16: Andy Johnson
17: Armon Johnson
18: Arnie Johnson
19: Avery Johnson
20: B.J. Johnson
21: Brice Johnson
22: Buck Johnson
23: Clay Johnson
24: Eddie Johnson
25: Eddie Johnson
26: Eric Johnson
27: George Johnson
28: George Johnson
29: George Johnson
30: Ivan Johnson
31: Neil Johnson
32: Nick Johnson
33: Ollie Johnson
34: Rich Johnson
35: Steve Johnson
36: Tyler Johnson
37: Nate Johnston
38: Jim Johnstone
39: Joe Colone
Pick one: 0
Results for Joe Johnson:

You searched for "Luc Mbah a Moute"
1 result found.
Luc Mbah a Moute
Results for Luc Mbah a Moute:

You searched for "Chinanu Onuaku"
1 result found.
Chinanu Onuaku
Results for Chinanu Onuaku:

You searched for "Chris Paul"
15 results found.
0: Chris Paul
1: Chris Babb
2: Chris Carr
3: Chris Taft
4: Chris Bosh
5: Chris Ford
6: Chris Jent
7: Chris Kaman
8: Chris King
9: Chris Mihm
10: Chris Mills
11: Chris Munk
12: Charlie Paulk
13: Chris Welp
14: Chris Silva
Pick one: 0
Results for Chris Paul:

You searched for "Zhou Qi"
1 result found.
Zhou Qi
Results for Zhou Qi:

You searched for "Tim Quarterman"
1 result found.
Tim Quarterman
Results for Tim Quarterman:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

You searched for "Briante Weber"
1 result found.
Briante Weber
Results for Briante Weber:

You searched for "Troy Williams"
46 results found.
0: Troy Williams
1: Ray Williams
2: Rob Williams
3: Ron Williams
4: Aaron Williams
5: Art Williams
6: Bob Williams
7: Corey Williams
8: Deron Williams
9: Eric Williams
10: Fly Williams
11: Guy Williams
12: Jay Williams
13: Lou Williams
14: Mo Williams
15: Sly Williams
16: Al Williams
17: Alan Williams
18: Buck Williams
19: C.J. Williams
20: Duck Williams
21: Earl Williams
22: Frank Williams
23: Gene Williams
24: Grant Williams
25: Gus Williams
26: Hank Williams
27: Herb Williams
28: Hot Rod Williams
29: Jason Williams
30: Jerome Williams
31: John Williams
32: Kenny Williams
33: Matt Williams
34: Mike Williams
35: Milt Williams
36: Monty Williams
37: Nate Williams
38: Pete Williams
39: Sam Williams
40: Sam Williams
41: Scott Williams
42: Sean Williams
43: Travis Williams
44: Walt Williams
45: Ward Williams
Pick one: 0
Results for Troy Williams:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-01-30,28-157,HOU,HOME,ORL,W (+7),1,46:26,19,30,...,10,11,4,1,5,2,60,56.6,7,James Harden
1,2017-11-05,28-071,HOU,HOME,UTA,W (+27),1,35:15,19,25,...,2,13,2,0,7,3,56,49.2,25,James Harden
2,2017-11-16,28-082,HOU,AWAY,PHO,W (+26),1,34:37,12,22,...,2,7,2,1,5,3,48,39.4,15,James Harden
3,2017-12-09,28-105,HOU,AWAY,POR,W (+7),1,37:19,16,29,...,8,3,3,0,2,2,48,38.4,9,James Harden
4,2017-12-31,28-127,HOU,HOME,LAL,W (+6),1,40:47,10,20,...,2,11,2,2,1,2,40,38.3,4,James Harden

In [53]:
# removed clint capella
# removed nene hilario

HOU_2019_gamelog = []

for p in HOU_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2019_gamelog.append(player_log)
HOU_2019_gamelog = pd.concat(HOU_2019_gamelog)    
HOU_2019_gamelogs = HOU_2019_gamelog.copy()
HOU_2019_gamelogs['GAME_SCORE'] = HOU_2019_gamelogs['GAME_SCORE'].astype(float)
HOU_2019_games = HOU_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2019_games_csv = HOU_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2019_games.csv', index=False)
HOU_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2019_games.csv')
HOU_2019_games_proc.head()

You searched for "Carmelo Anthony"
1 result found.
Carmelo Anthony
Results for Carmelo Anthony:

You searched for "Michael Carter-Williams"
1 result found.
Michael Carter-Williams
Results for Michael Carter-Williams:

You searched for "Chris Chiozza"
2 results found.
0: Chris Chiozza
1: Chris Childs
Pick one: 0
Results for Chris Chiozza:

You searched for "Marquese Chriss"
1 result found.
Marquese Chriss
Results for Marquese Chriss:

You searched for "Gary Clark"
15 results found.
0: Gary Clark
1: Earl Clark
2: Ian Clark
3: Gary Alcorn
4: Cory Carr
5: Carlos Clark
6: Keon Clark
7: Coty Clarke
8: Gary Grant
9: Gary Gray
10: Gar Heard
11: Gary Neal
12: Jay Carty
13: Gary Keller
14: Gary Zeller
Pick one: 0
Results for Gary Clark:

You searched for "Vince Edwards"
5 results found.
0: Vince Edwards
1: Bill Edwards
2: Blue Edwards
3: Kevin Edwards
4: Shane Edwards
Pick one: 0
Results for Vince Edwards:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Kenneth Faried"
2 results found.
0: Kenneth Faried
1: Kenneth Gardner
Pick one: 0
Results for Kenneth Faried:

You searched for "Eric Gordon"
12 results found.
0: Eric Gordon
1: Drew Gordon
2: Eric Dawson
3: Aaron Gordon
4: Ben Gordon
5: Paul Gordon
6: Erick Green
7: Eric Johnson
8: Phil Jordon
9: Eric Murdock
10: Eric Maynor
11: Eric Money
Pick one: 0
Results for Eric Gordon:

You searched for "Gerald Green"
6 results found.
0: Gerald Green
1: Gerald Brown
2: Gerald Govan
3: Gerald Glass
4: Erick Green
5: Sean Green
Pick one: 0
Results for Gerald Green:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "Isaiah Hartenstein"
1 result found.
Isaiah Hartenstein
Results for Isaiah Hartenstein:

You searched for "Danuel House"
2 results found.
0: Danuel House
1: Daniel Theis
Pick one: 0
Results for Danuel House:

You searched for "Terrence Jones"
3 results found.
0: Terrence Jones
1: Terrence Ross
2: Derrick Jones
Pick one: 0
Results for Terrence Jones:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "James Nunnally"
1 result found.
James Nunnally
Results for James Nunnally:

You searched for "Chris Paul"
15 results found.
0: Chris Paul
1: Chris Babb
2: Chris Carr
3: Chris Taft
4: Chris Bosh
5: Chris Ford
6: Chris Jent
7: Chris Kaman
8: Chris King
9: Chris Mihm
10: Chris Mills
11: Chris Munk
12: Charlie Paulk
13: Chris Welp
14: Chris Silva
Pick one: 0
Results for Chris Paul:

You searched for "Zhou Qi"
1 result found.
Zhou Qi
Results for Zhou Qi:

You searched for "Austin Rivers"
1 result found.
Austin Rivers
Results for Austin Rivers:

You searched for "Iman Shumpert"
1 result found.
Iman Shumpert
Results for Iman Shumpert:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-02-28,29-186,HOU,HOME,MIA,W (+3),1,43:52,16,32,...,7,10,4,1,4,1,58,52.2,10,James Harden
1,2019-01-23,29-150,HOU,AWAY,NYK,W (+4),1,40:00,17,38,...,15,4,5,0,5,3,61,48.5,19,James Harden
2,2019-03-22,29-208,HOU,HOME,SAS,W (+6),1,36:40,19,34,...,7,1,3,0,3,3,61,46.0,18,James Harden
3,2019-03-20,29-206,HOU,AWAY,MEM,L (-1),1,45:37,18,39,...,7,8,2,2,3,3,57,44.2,11,James Harden
4,2019-01-16,29-143,HOU,HOME,BRK,L (-3),1,45:02,16,34,...,10,6,1,1,4,5,58,43.1,-8,James Harden

In [54]:
# removed clint capella

HOU_2020_gamelog = []

for p in HOU_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2020_gamelog.append(player_log)
HOU_2020_gamelog = pd.concat(HOU_2020_gamelog)    
HOU_2020_gamelogs = HOU_2020_gamelog.copy()
HOU_2020_gamelogs['GAME_SCORE'] = HOU_2020_gamelogs['GAME_SCORE'].astype(float)
HOU_2020_games = HOU_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2020_games_csv = HOU_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2020_games.csv', index=False)
HOU_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2020_games.csv')
HOU_2020_games_proc.head()

You searched for "Ryan Anderson"
14 results found.
0: Ryan Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ron Anderson
5: Kyle Anderson
6: Eric Anderson
7: Greg Anderson
8: J.J. Anderson
9: Kenny Anderson
10: Kim Anderson
11: Nick Anderson
12: Alan Henderson
13: Ryan Robertson
Pick one: 0
Results for Ryan Anderson:

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "DeMarre Carroll"
1 result found.
DeMarre Carroll
Results for DeMarre Carroll:

You searched for "Tyson Chandler"
3 results found.
0: Tyson Chandler
1: Wilson Chandler
2: Tyson Wheeler
Pick one: 0
Results for Tyson Chandler:

You searched for "Gary Clark"
15 results found.
0: Gary Clark
1: Earl Clark
2: Ian Clark
3: Gary Alcorn
4: Cory Carr
5: Carlos Clark
6: Keon Clark
7: Coty Clarke
8: Gary Grant
9: Gary Gray
10: Gar Heard
11: Gary Neal
12: Jay Carty
13: Gary Keller
14: Gary Zeller
Pick one: 0
Results for Gary Clark:

You searched for "Chris Clemons"
2 results found.
0: Chris Clemons
1: Chris Owens
Pick one: 0
Results for Chris Clemons:

You searched for "Robert Covington"
1 result found.
Robert Covington
Results for Robert Covington:

You searched for "Michael Frazier"
2 results found.
0: Michael Frazier
1: Michael Bradley
Pick one: 0
Results for Michael Frazier:

You searched for "Eric Gordon"
12 results found.
0: Eric Gordon
1: Drew Gordon
2: Eric Dawson
3: Aaron Gordon
4: Ben Gordon
5: Paul Gordon
6: Erick Green
7: Eric Johnson
8: Phil Jordon
9: Eric Murdock
10: Eric Maynor
11: Eric Money
Pick one: 0
Results for Eric Gordon:

You searched for "Jeff Green"
21 results found.
0: Jeff Green
1: Josh Green
2: Jeff Adrien
3: Jeff Grayer
4: Ken Green
5: Sean Green
6: Jeff Ayres
7: Jeff Cross
8: A.C. Green
9: Devin Green
10: Kenny Green
11: Mike Green
12: Si Green
13: Steve Green
14: Jeff Lebo
15: Jeff Martin
16: Jeff Turner
17: Jeff Webb
18: Jeff Foote
19: Jeff Slade
20: Jeff Teague
Pick one: 0
Results for Jeff Green:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "Isaiah Hartenstein"
1 result found.
Isaiah Hartenstein
Results for Isaiah Hartenstein:

You searched for "Danuel House"
2 results found.
0: Danuel House
1: Daniel Theis
Pick one: 0
Results for Danuel House:

You searched for "William Howard"
1 result found.
William Howard
Results for William Howard:

You searched for "Luc Mbah a Moute"
1 result found.
Luc Mbah a Moute
Results for Luc Mbah a Moute:

You searched for "Ben McLemore"
3 results found.
0: Ben McLemore
1: Len Elmore
2: Ben Moore
Pick one: 0
Results for Ben McLemore:

You searched for "Austin Rivers"
1 result found.
Austin Rivers
Results for Austin Rivers:

You searched for "Thabo Sefolosha"
1 result found.
Thabo Sefolosha
Results for Thabo Sefolosha:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

You searched for "Russell Westbrook"
1 result found.
Russell Westbrook
Results for Russell Westbrook:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-11-30,30-096,HOU,HOME,ATL,W (+47),1,30:41,16,24,...,3,8,3,1,5,3,60,52.4,50,James Harden
1,2020-07-31,30-340,HOU,AWAY,DAL,W (+4),1,43:29,14,20,...,9,8,3,3,1,5,49,49.8,8,James Harden
2,2019-10-30,30-065,HOU,AWAY,WAS,W (+1),1,37:30,18,32,...,3,9,1,0,4,3,59,46.8,6,James Harden
3,2019-12-13,30-109,HOU,AWAY,ORL,W (+23),1,36:14,19,31,...,5,7,2,3,3,5,54,46.2,21,James Harden
4,2020-01-27,31-033,HOU,AWAY,UTA,W (+9),1,38:17,14,22,...,6,3,2,1,2,0,50,43.2,12,Eric Gordon

In [66]:
# removed clint capella
# removed Armoni Brooks
HOU_2021_gamelog = []

for p in HOU_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    HOU_2021_gamelog.append(player_log)
HOU_2021_gamelog = pd.concat(HOU_2021_gamelog)    
HOU_2021_gamelogs = HOU_2021_gamelog.copy()
HOU_2021_gamelogs['GAME_SCORE'] = HOU_2021_gamelogs['GAME_SCORE'].astype(float)
HOU_2021_games = HOU_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_2021_games_csv = HOU_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2021_games.csv', index=False)
HOU_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2021_games.csv')
HOU_2021_games_proc.head()

You searched for "D.J. Augustin"
1 result found.
D.J. Augustin
Results for D.J. Augustin:

You searched for "Avery Bradley"
4 results found.
0: Avery Bradley
1: Alex Bradley
2: Joe Bradley
3: Tony Bradley
Pick one: 0
Results for Avery Bradley:

You searched for "Sterling Brown"
1 result found.
Sterling Brown
Results for Sterling Brown:

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Eric Gordon"
12 results found.
0: Eric Gordon
1: Drew Gordon
2: Eric Dawson
3: Aaron Gordon
4: Ben Gordon
5: Paul Gordon
6: Erick Green
7: Eric Johnson
8: Phil Jordon
9: Eric Murdock
10: Eric Maynor
11: Eric Money
Pick one: 0
Results for Eric Gordon:

You searched for "James Harden"
11 results found.
0: James Harden
1: James Hardy
2: James Bailey
3: Jimmy Darden
4: Jared Harper
5: James Edwards
6: James Lang
7: James Phelan
8: James Ennis
9: Jaylen Hoard
10: James Thomas
Pick one: 0
Results for James Harden:

You searched for "Danuel House"
2 results found.
0: Danuel House
1: Daniel Theis
Pick one: 0
Results for Danuel House:

You searched for "DaQuan Jeffries"
1 result found.
DaQuan Jeffries
Results for DaQuan Jeffries:

You searched for "Mason Jones"
18 results found.
0: Mason Jones
1: Damon Jones
2: Major Jones
3: Jalen Jones
4: Mark Jones
5: Mark Jones
6: Aaron James
7: Alvin Jones
8: Askia Jones
9: Damian Jones
10: Earl Jones
11: Jake Jones
12: James Jones
13: Kevin Jones
14: Larry Jones
15: Robin Jones
16: Sam Jones
17: Wali Jones
Pick one: 0
Results for Mason Jones:

You searched for "Rodions Kurucs"
1 result found.
Rodions Kurucs
Results for Rodions Kurucs:

You searched for "Anthony Lamb"
4 results found.
0: Anthony Lamb
1: Anthony Cook
2: Anthony Davis
3: Anthony Mason
Pick one: 0
Results for Anthony Lamb:

You searched for "Kenyon Martin"
6 results found.
0: Kenyon Martin
1: Kelan Martin
2: Kevin Martin
3: Kenyon Martin Jr.
4: Dino Martin
5: Don Martin
Pick one: 3
Results for Kenyon Martin Jr.:

You searched for "Ben McLemore"
3 results found.
0: Ben McLemore
1: Len Elmore
2: Ben Moore
Pick one: 0
Results for Ben McLemore:

You searched for "David Nwaba"
6 results found.
0: David Nwaba
1: David Noel
2: David Wear
3: David West
4: David Wood
5: David Burns
Pick one: 0
Results for David Nwaba:

You searched for "Victor Oladipo"
1 result found.
Victor Oladipo
Results for Victor Oladipo:

You searched for "Kelly Olynyk"
1 result found.
Kelly Olynyk
Results for Kelly Olynyk:

You searched for "Justin Patton"
4 results found.
0: Justin Patton
1: Justin Dentmon
2: Justin Hamilton
3: Justin Jackson
Pick one: 0
Results for Justin Patton:

You searched for "Cameron Reynolds"
1 result found.
Cameron Reynolds
Results for Cameron Reynolds:

You searched for "Ray Spalding"
1 result found.
Ray Spalding
Results for Ray Spalding:

You searched for "Brodric Thomas"
1 result found.
Brodric Thomas
Results for Brodric Thomas:

You searched for "Khyri Thomas"
6 results found.
0: Khyri Thomas
1: Kurt Thomas
2: Carl Thomas
3: Kenny Thomas
4: Terry Thomas
5: Tyrus Thomas
Pick one: 0
Results for Khyri Thomas:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

You searched for "John Wall"
21 results found.
0: John Wall
1: Josh Hall
2: John Barr
3: John Mills
4: John Salley
5: John Wallace
6: John Bagley
7: John Battle
8: John Drew
9: John Hazen
10: John Long
11: John Pilch
12: John Rudd
13: John Trapp
14: John Vallely
15: John Warren
16: John Wetzel
17: Joe Wolf
18: John Brown
19: John Logan
20: John Lucas
Pick one: 0
Results for John Wall:

You searched for "D.J. Wilson"
7 results found.
0: D.J. Wilson
1: C.J. Watson
2: C.J. Wilcox
3: J.J. Hickson
4: Bob Wilson
5: Jim Wilson
6: Rick Wilson
Pick one: 0
Results for D.J. Wilson:

You searched for "Christian Wood"
1 result found.
Christian Wood
Results for Christian Wood:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-12-26,31-122,HOU,AWAY,POR,L (-2),1,43:16,12,21,...,4,17,1,0,5,1,44,42.4,-6,James Harden
1,2021-03-17,31-203,BRK,AWAY,IND,W (+9),1,42:07,13,27,...,10,15,2,0,2,4,40,38.2,25,James Harden
2,2021-02-16,31-174,BRK,AWAY,PHO,W (+4),1,36:49,14,22,...,7,11,1,0,2,2,38,36.2,0,James Harden
3,2021-03-01,31-187,BRK,AWAY,SAS,W (+11),1,44:02,12,23,...,14,15,2,0,0,3,30,35.4,16,James Harden
4,2021-01-27,31-154,BRK,AWAY,ATL,W (+4),1,45:54,9,20,...,8,15,2,1,3,1,31,34.0,2,James Harden

## combine all seasons

In [67]:
HOU_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2000_games.csv')
HOU_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2001_games.csv')
HOU_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2002_games.csv')
HOU_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2003_games.csv')
HOU_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2004_games.csv')
HOU_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2005_games.csv')
HOU_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2006_games.csv')
HOU_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2007_games.csv')
HOU_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2008_games.csv')
HOU_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2009_games.csv')
HOU_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2010_games.csv')
HOU_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2011_games.csv')
HOU_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2012_games.csv')
HOU_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2013_games.csv')
HOU_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2014_games.csv')
HOU_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2015_games.csv')
HOU_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2016_games.csv')
HOU_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2017_games.csv')
HOU_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2018_games.csv')
HOU_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2019_games.csv')
HOU_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2020_games.csv')
HOU_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/HOU/HOU_2021_games.csv')

In [68]:
HOU_season_dfs = [HOU_2000_games_io, HOU_2001_games_io, HOU_2002_games_io, HOU_2003_games_io, HOU_2004_games_io, HOU_2005_games_io,
                 HOU_2006_games_io, HOU_2007_games_io, HOU_2008_games_io, HOU_2009_games_io, HOU_2010_games_io, HOU_2011_games_io,
                 HOU_2012_games_io, HOU_2013_games_io, HOU_2014_games_io, HOU_2015_games_io, HOU_2016_games_io, HOU_2017_games_io,
                 HOU_2018_games_io, HOU_2019_games_io, HOU_2020_games_io, HOU_2021_games_io]

In [69]:
HOU_all = pd.concat(HOU_season_dfs)
HOU_all_sorted = HOU_all.sort_values(by=['GAME_SCORE'], ascending=False)
HOU_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-01-30,28-157,HOU,HOME,ORL,W (+7),1,46:26,19,30,...,10,11,4,1,5,2,60,56.6,7,James Harden
0,2019-11-30,30-096,HOU,HOME,ATL,W (+47),1,30:41,16,24,...,3,8,3,1,5,3,60,52.4,50,James Harden
0,2019-02-28,29-186,HOU,HOME,MIA,W (+3),1,43:52,16,32,...,7,10,4,1,4,1,58,52.2,10,James Harden
1,2020-07-31,30-340,HOU,AWAY,DAL,W (+4),1,43:29,14,20,...,9,8,3,3,1,5,49,49.8,8,James Harden
1,2017-11-05,28-071,HOU,HOME,UTA,W (+27),1,35:15,19,25,...,2,13,2,0,7,3,56,49.2,25,James Harden
0,2016-12-31,27-127,HOU,HOME,NYK,W (+7),1,42:05,14,26,...,16,17,0,0,8,2,53,48.7,13,James Harden
1,2019-01-23,29-150,HOU,AWAY,NYK,W (+4),1,40:00,17,38,...,15,4,5,0,5,3,61,48.5,19,James Harden
1,2017-01-27,27-154,HOU,AWAY,PHI,W (+5),1,39:09,16,28,...,13,13,2,1,5,4,51,46.9,13,James Harden
2,2019-10-30,30-065,HOU,AWAY,WAS,W (+1),1,37:30,18,32,...,3,9,1,0,4,3,59,46.8,6,James Harden
3,2019-12-13,30-109,HOU,AWAY,ORL,W (+23),1,36:14,19,31,...,5,7,2,3,3,5,54,46.2,21,James Harden
2,2019-03-22,29-208,HOU,HOME,SAS,W (+6),1,36:40,19,34,...,7,1,3,0,3,3,61,46.0,18,James Harden
0,2013-02-20,23-178,HOU,HOME,OKC,W (+3),1,44:14,14,19,...,7,6,2,1,2,2,46,44.5,8,James Harden
3,2019-03-20,29-206,HOU,AWAY,MEM,L (-1),1,45:37,18,39,...,7,8,2,2,3,3,57,44.2,11,James Harden
4,2020-01-27,31-033,HOU,AWAY,UTA,W (+9),1,38:17,14,22,...,6,3,2,1,2,0,50,43.2,12,Eric Gordon
4,2019-01-16,29-143,HOU,HOME,BRK,L (-3),1,45:02,16,34,...,10,6,1,1,4,5,58,43.1,-8,James Harden
5,2018-12-13,29-109,HOU,HOME,LAL,W (+15),1,35:28,14,26,...,10,11,2,0,6,4,50,42.9,14,James Harden
0,2005-03-28,25-308,HOU,AWAY,UTA,W (+14),1,37:44,15,21,...,6,4,5,1,0,2,44,42.8,6,Tracy McGrady
5,2020-08-12,30-352,HOU,HOME,IND,L (-4),1,35:28,13,21,...,17,9,3,0,6,2,45,42.7,11,James Harden
2,2016-11-01,27-067,HOU,AWAY,CLE,L (-8),1,38:10,13,20,...,7,15,1,0,1,3,41,42.4,10,James Harden
0,2020-12-26,31-122,HOU,AWAY,POR,L (-2),1,43:16,12,21,...,4,17,1,0,5,1,44,42.4,-6,James Harden
1,2015-04-01,25-218,HOU,HOME,SAC,W (+4),1,37:33,16,25,...,8,6,3,0,7,1,51,42.1,10,James Harden
0,2015-01-19,25-146,HOU,HOME,IND,W (+12),1,39:56,12,18,...,1,7,4,1,5,0,45,42.1,17,James Harden
6,2019-12-11,30-107,HOU,AWAY,CLE,W (+6),1,41:16,20,34,...,3,8,2,2,6,3,55,41.9,10,James Harden
6,2019-02-02,29-160,HOU,AWAY,UTA,W (+27),1,39:42,12,22,...,12,5,6,4,5,4,43,41.7,31,James Harden
7,2019-01-14,29-141,HOU,HOME,MEM,W (+18),1,34:06,17,33,...,9,2,2,1,5,4,57,41.3,25,James Harden