In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [8]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2014-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [10]:
season = 2002
appended_data_MEM = []

# MEM
while season <= 2021:
    df_MEM = get_roster('MEM', season)
    df_MEM['Season'] = season
    df_MEM['Team'] = 'MEM'
    appended_data_MEM.append(df_MEM)
    season = season + 1
appended_data_MEM = pd.concat(appended_data_MEM)

In [11]:
MEM_df_all = appended_data_MEM.copy()
MEM_df_all_csv = MEM_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_players_all.csv', index=False)
MEM_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_players_all.csv')
MEM_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,25,Nick Anderson,SG,6-6,205,1968-01-20,US,12,Illinois,2002,MEM
1,9,Isaac Austin,C,6-10,255,1969-08-18,US,8,Arizona State,2002,MEM
2,31,Shane Battier,SF,6-8,220,1978-09-09,US,R,Duke,2002,MEM
3,32,Rodney Buford,SG,6-5,189,1977-11-02,US,2,Creighton,2002,MEM
4,8,Michael Dickerson,SG,6-5,190,1975-06-25,US,3,Arizona,2002,MEM

In [12]:
#MEM_df_2000 = MEM_df_all[MEM_df_all['Season'] == 2000]
#MEM_df_2001 = MEM_df_all[MEM_df_all['Season'] == 2001]
MEM_df_2002 = MEM_df_all[MEM_df_all['Season'] == 2002]
MEM_df_2003 = MEM_df_all[MEM_df_all['Season'] == 2003]
MEM_df_2004 = MEM_df_all[MEM_df_all['Season'] == 2004]
MEM_df_2005 = MEM_df_all[MEM_df_all['Season'] == 2005]
MEM_df_2006 = MEM_df_all[MEM_df_all['Season'] == 2006]
MEM_df_2007 = MEM_df_all[MEM_df_all['Season'] == 2007]
MEM_df_2008 = MEM_df_all[MEM_df_all['Season'] == 2008]
MEM_df_2009 = MEM_df_all[MEM_df_all['Season'] == 2009]
MEM_df_2010 = MEM_df_all[MEM_df_all['Season'] == 2010]
MEM_df_2011 = MEM_df_all[MEM_df_all['Season'] == 2011]
MEM_df_2012 = MEM_df_all[MEM_df_all['Season'] == 2012]
MEM_df_2013 = MEM_df_all[MEM_df_all['Season'] == 2013]
MEM_df_2014 = MEM_df_all[MEM_df_all['Season'] == 2014]
MEM_df_2015 = MEM_df_all[MEM_df_all['Season'] == 2015]
MEM_df_2016 = MEM_df_all[MEM_df_all['Season'] == 2016]
MEM_df_2017 = MEM_df_all[MEM_df_all['Season'] == 2017]
MEM_df_2018 = MEM_df_all[MEM_df_all['Season'] == 2018]
MEM_df_2019 = MEM_df_all[MEM_df_all['Season'] == 2019]
MEM_df_2020 = MEM_df_all[MEM_df_all['Season'] == 2020]
MEM_df_2021 = MEM_df_all[MEM_df_all['Season'] == 2021]

In [ ]:
# changing names
#MEM_df_2002.loc[MEM_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#MEM_df_2004.loc[MEM_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [13]:
#MEM_df_2000_players = MEM_df_2000['PLAYER'].to_list()
#MEM_df_2001_players = MEM_df_2001['PLAYER'].to_list()
MEM_df_2002_players = MEM_df_2002['PLAYER'].to_list()
MEM_df_2003_players = MEM_df_2003['PLAYER'].to_list()
MEM_df_2004_players = MEM_df_2004['PLAYER'].to_list()
MEM_df_2005_players = MEM_df_2005['PLAYER'].to_list()

MEM_df_2006_players = MEM_df_2006['PLAYER'].to_list()
MEM_df_2007_players = MEM_df_2007['PLAYER'].to_list()
MEM_df_2008_players = MEM_df_2008['PLAYER'].to_list()
MEM_df_2009_players = MEM_df_2009['PLAYER'].to_list()
MEM_df_2010_players = MEM_df_2010['PLAYER'].to_list()
MEM_df_2011_players = MEM_df_2011['PLAYER'].to_list()

MEM_df_2012_players = MEM_df_2012['PLAYER'].to_list()
MEM_df_2013_players = MEM_df_2013['PLAYER'].to_list()
MEM_df_2014_players = MEM_df_2014['PLAYER'].to_list()
MEM_df_2015_players = MEM_df_2015['PLAYER'].to_list()
MEM_df_2016_players = MEM_df_2016['PLAYER'].to_list()
MEM_df_2017_players = MEM_df_2017['PLAYER'].to_list()

MEM_df_2018_players = MEM_df_2018['PLAYER'].to_list()
MEM_df_2019_players = MEM_df_2019['PLAYER'].to_list()
MEM_df_2020_players = MEM_df_2020['PLAYER'].to_list()
MEM_df_2021_players = MEM_df_2021['PLAYER'].to_list()

## players to drop

In [52]:

#MEM_df_2008_players.remove("Bobby Jones")
#MEM_df_2008_players.remove("Juan Carlos Navarro")
#MEM_df_2016_players.remove("P.J. Hairston")
#MEM_df_2016_players.remove("Xavier Munford")
#MEM_df_2019_players.remove("Jaren Jackson")
#MEM_df_2020_players.remove("Jaren Jackson")
#MEM_df_2021_players.remove("Jaren Jackson")
MEM_df_2021_players.remove("Xavier Tillman")

In [16]:

MEM_2002_gamelog = []


for p in MEM_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2002_gamelog.append(player_log)
MEM_2002_gamelog = pd.concat(MEM_2002_gamelog)    
MEM_2002_gamelogs = MEM_2002_gamelog.copy()
MEM_2002_gamelogs['GAME_SCORE'] = MEM_2002_gamelogs['GAME_SCORE'].astype(float)
MEM_2002_games = MEM_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2002_games_csv = MEM_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2002_games.csv', index=False)
MEM_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2002_games.csv')
MEM_2002_games_proc.head()

You searched for "Nick Anderson"
14 results found.
0: Nick Anderson
1: Eric Anderson
2: Kim Anderson
3: Alan Anderson
4: Cliff Anderson
5: Dan Anderson
6: Dan Anderson
7: Derek Anderson
8: Greg Anderson
9: J.J. Anderson
10: Kyle Anderson
11: Ron Anderson
12: Ryan Anderson
13: Rick Roberson
Pick one: 0
Results for Nick Anderson:

You searched for "Isaac Austin"
1 result found.
Isaac Austin
Results for Isaac Austin:

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Rodney Buford"
2 results found.
0: Rodney Buford
1: Rodney Hood
Pick one: 0
Results for Rodney Buford:

You searched for "Michael Dickerson"
3 results found.
0: Michael Dickerson
1: Michael Anderson
2: Michael Jackson
Pick one: 0
Results for Michael Dickerson:

You searched for "Isaac Fontaine"
1 result found.
Isaac Fontaine
Results for Isaac Fontaine:

You searched for "Antonis Fotsis"
1 result found.
Antonis Fotsis
Results for Antonis Fotsis:

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

You searched for "Eddie Gill"
4 results found.
0: Eddie Gill
1: Eddie Miles
2: Eddie Miller
3: Eddie Mast
Pick one: 0
Results for Eddie Gill:

You searched for "Brevin Knight"
5 results found.
0: Brevin Knight
1: Brandin Knight
2: Travis Knight
3: Brandon Knight
4: Ron Knight
Pick one: 0
Results for Brevin Knight:

You searched for "Grant Long"
6 results found.
0: Grant Long
1: Art Long
2: Grant Hill
3: John Long
4: Paul Long
5: Shawn Long
Pick one: 0
Results for Grant Long:

You searched for "Tony Massenburg"
1 result found.
Tony Massenburg
Results for Tony Massenburg:

You searched for "Elliot Perry"
1 result found.
Elliot Perry
Results for Elliot Perry:

You searched for "Will Solomon"
1 result found.
Will Solomon
Results for Will Solomon:

You searched for "Stromile Swift"
1 result found.
Stromile Swift
Results for Stromile Swift:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

You searched for "Lorenzen Wright"
2 results found.
0: Lorenzen Wright
1: Lonnie Wright
Pick one: 0
Results for Lorenzen Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-11-30,26-012,MEM,HOME,HOU,W (+17),1,37:24,16,28,...,6,11,4,0,3,3,38,34.1,13,Jason Williams
1,2001-11-04,26-000,MEM,HOME,DAL,L (-9),1,43:57,10,21,...,26,2,1,1,5,2,33,29.4,-5,Lorenzen Wright
2,2001-11-15,23-067,MEM,HOME,POR,L (-16),1,44:06,10,13,...,4,5,0,3,1,4,30,29.1,-14,Shane Battier
3,2002-04-05,21-273,MEM,HOME,HOU,W (+18),1,43:58,12,22,...,14,4,0,2,2,0,32,29.0,21,Pau Gasol
4,2001-12-26,21-173,MEM,HOME,CHI,W (+22),1,36:35,11,15,...,14,3,1,4,2,4,27,27.8,22,Pau Gasol

In [17]:

    
MEM_2003_gamelog = []



for p in MEM_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2003_gamelog.append(player_log)
MEM_2003_gamelog = pd.concat(MEM_2003_gamelog)    
MEM_2003_gamelogs = MEM_2003_gamelog.copy()
MEM_2003_gamelogs['GAME_SCORE'] = MEM_2003_gamelogs['GAME_SCORE'].astype(float)
MEM_2003_games = MEM_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2003_games_csv = MEM_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2003_games.csv', index=False)
MEM_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2003_games.csv')
MEM_2003_games_proc.head()

You searched for "Robert Archibald"
1 result found.
Robert Archibald
Results for Robert Archibald:

You searched for "Mike Batiste"
8 results found.
0: Mike Batiste
1: Mike Barrett
2: Mike Davis
3: Mike Davis
4: Mike Bantom
5: Mike Butler
6: Mike Ratliff
7: Mickey Davis
Pick one: 0
Results for Mike Batiste:

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Michael Dickerson"
3 results found.
0: Michael Dickerson
1: Michael Anderson
2: Michael Jackson
Pick one: 0
Results for Michael Dickerson:

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

You searched for "Gordan Giriček"
1 result found.
Gordan Giricek
Results for Gordan Giricek:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Ryan Humphrey"
1 result found.
Ryan Humphrey
Results for Ryan Humphrey:

You searched for "Brevin Knight"
5 results found.
0: Brevin Knight
1: Brandin Knight
2: Travis Knight
3: Brandon Knight
4: Ron Knight
Pick one: 0
Results for Brevin Knight:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Chris Owens"
20 results found.
0: Chris Owens
1: Chris Jent
2: Tariq Owens
3: Chris Welp
4: Chris Clemons
5: Chris King
6: Chris Mills
7: Chris Morris
8: Chris Munk
9: Eddie Owens
10: Jim Owens
11: Larry Owens
12: Red Owens
13: Chris Quinn
14: Chris Bosh
15: Chris Duhon
16: Chris Herren
17: Chris Kaman
18: Chris Porter
19: Curtis Rowe
Pick one: 0
Results for Chris Owens:

You searched for "Wesley Person"
2 results found.
0: Wesley Person
1: Wesley Johnson
Pick one: 0
Results for Wesley Person:

You searched for "Stromile Swift"
1 result found.
Stromile Swift
Results for Stromile Swift:

You searched for "Cezary Trybański"
1 result found.
Cezary Trybanski
Results for Cezary Trybanski:

You searched for "Earl Watson"
9 results found.
0: Earl Watson
1: Paul Watson
2: Earl Barron
3: Mark Eaton
4: Earl Shannon
5: Earl Tatum
6: C.J. Watson
7: Jamie Watson
8: Earl Jones
Pick one: 0
Results for Earl Watson:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

You searched for "Lorenzen Wright"
2 results found.
0: Lorenzen Wright
1: Lonnie Wright
Pick one: 0
Results for Lorenzen Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-11-27,27-009,MEM,HOME,SEA,W (+18),1,31:24,11,17,...,2,6,4,0,0,2,28,28.9,22,Jason Williams
1,2003-01-31,22-209,MEM,HOME,NYK,L (-6),1,41:20,13,19,...,9,3,1,4,1,5,32,28.7,2,Pau Gasol
2,2003-03-09,22-246,MEM,AWAY,TOR,W (+13),1,37:33,14,19,...,6,2,1,1,2,3,32,27.2,9,Pau Gasol
3,2003-01-06,27-049,MEM,HOME,NOH,W (+4),1,39:13,10,17,...,7,14,1,0,4,2,28,27.0,13,Jason Williams
4,2003-01-22,22-200,MEM,AWAY,SAS,W (+5),1,38:05,10,17,...,17,3,0,3,2,4,28,25.8,8,Pau Gasol

In [18]:


MEM_2004_gamelog = []



for p in MEM_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2004_gamelog.append(player_log)
MEM_2004_gamelog = pd.concat(MEM_2004_gamelog)    
MEM_2004_gamelogs = MEM_2004_gamelog.copy()
MEM_2004_gamelogs['GAME_SCORE'] = MEM_2004_gamelogs['GAME_SCORE'].astype(float)
MEM_2004_games = MEM_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2004_games_csv = MEM_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2004_games.csv', index=False)
MEM_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2004_games.csv')
MEM_2004_games_proc.head()

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Troy Bell"
8 results found.
0: Troy Bell
1: Raja Bell
2: Troy Brown
3: Tony Delk
4: Tom Kelly
5: Tony Snell
6: Trey Burke
7: Bo Ellis
Pick one: 0
Results for Troy Bell:

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

You searched for "Ryan Humphrey"
1 result found.
Ryan Humphrey
Results for Ryan Humphrey:

You searched for "Dahntay Jones"
5 results found.
0: Dahntay Jones
1: Damian Jones
2: Dontae' Jones
3: Johnny Jones
4: Wah Wah Jones
Pick one: 0
Results for Dahntay Jones:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "Wesley Person"
2 results found.
0: Wesley Person
1: Wesley Johnson
Pick one: 0
Results for Wesley Person:

You searched for "James Posey"
14 results found.
0: James Posey
1: James Jones
2: James Bailey
3: James Hardy
4: James Ray
5: Jalen Rose
6: James Worthy
7: James Young
8: James Ennis
9: James Scott
10: James Silas
11: James Thomas
12: James Webb
13: James White
Pick one: 0
Results for James Posey:

You searched for "Theron Smith"
13 results found.
0: Theron Smith
1: Leon Smith
2: Chris Smith
3: Chris Smith
4: Derek Smith
5: Don Smith
6: Don Smith
7: Jason Smith
8: Jerry Smith
9: Ken Smith
10: Steven Smith
11: Stevin Smith
12: Tony Smith
Pick one: 0
Results for Theron Smith:

You searched for "Stromile Swift"
1 result found.
Stromile Swift
Results for Stromile Swift:

You searched for "Jake Tsakalidis"
1 result found.
Jake Tsakalidis
Results for Jake Tsakalidis:

You searched for "Earl Watson"
9 results found.
0: Earl Watson
1: Paul Watson
2: Earl Barron
3: Mark Eaton
4: Earl Shannon
5: Earl Tatum
6: C.J. Watson
7: Jamie Watson
8: Earl Jones
Pick one: 0
Results for Earl Watson:

You searched for "Bonzi Wells"
3 results found.
0: Bonzi Wells
1: Bubba Wells
2: Owen Wells
Pick one: 0
Results for Bonzi Wells:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

You searched for "Lorenzen Wright"
2 results found.
0: Lorenzen Wright
1: Lonnie Wright
Pick one: 0
Results for Lorenzen Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-03-29,27-076,MEM,AWAY,ATL,W (+3),1,48:28,10,17,...,11,3,1,1,2,4,38,34.4,10,James Posey
1,2004-04-07,27-085,MEM,HOME,CLE,W (+18),1,37:49,8,12,...,6,3,3,0,1,3,35,34.1,27,James Posey
2,2003-11-29,23-146,MEM,AWAY,CLE,W (+7),1,47:36,12,20,...,11,1,1,5,4,2,37,31.5,-9,Pau Gasol
3,2004-02-04,27-022,MEM,AWAY,WAS,W (+2),1,30:42,10,13,...,4,2,1,1,2,3,31,27.0,19,James Posey
4,2003-12-30,23-177,MEM,HOME,SEA,L (-6),1,34:01,9,14,...,11,2,0,2,5,2,32,26.9,-3,Pau Gasol

In [19]:


MEM_2005_gamelog = []

for p in MEM_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2005_gamelog.append(player_log)
MEM_2005_gamelog = pd.concat(MEM_2005_gamelog)    
MEM_2005_gamelogs = MEM_2005_gamelog.copy()
MEM_2005_gamelogs['GAME_SCORE'] = MEM_2005_gamelogs['GAME_SCORE'].astype(float)
MEM_2005_games = MEM_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2005_games_csv = MEM_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2005_games.csv', index=False)
MEM_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2005_games.csv')
MEM_2005_games_proc.head()

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Antonio Burks"
2 results found.
0: Antonio Burks
1: Antonio Davis
Pick one: 0
Results for Antonio Burks:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Andre Emmett"
2 results found.
0: Andre Emmett
1: Andre Barrett
Pick one: 0
Results for Andre Emmett:

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

You searched for "Ryan Humphrey"
1 result found.
Ryan Humphrey
Results for Ryan Humphrey:

You searched for "Dahntay Jones"
5 results found.
0: Dahntay Jones
1: Damian Jones
2: Dontae' Jones
3: Johnny Jones
4: Wah Wah Jones
Pick one: 0
Results for Dahntay Jones:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "James Posey"
14 results found.
0: James Posey
1: James Jones
2: James Bailey
3: James Hardy
4: James Ray
5: Jalen Rose
6: James Worthy
7: James Young
8: James Ennis
9: James Scott
10: James Silas
11: James Thomas
12: James Webb
13: James White
Pick one: 0
Results for James Posey:

You searched for "Stromile Swift"
1 result found.
Stromile Swift
Results for Stromile Swift:

You searched for "Jake Tsakalidis"
1 result found.
Jake Tsakalidis
Results for Jake Tsakalidis:

You searched for "Earl Watson"
9 results found.
0: Earl Watson
1: Paul Watson
2: Earl Barron
3: Mark Eaton
4: Earl Shannon
5: Earl Tatum
6: C.J. Watson
7: Jamie Watson
8: Earl Jones
Pick one: 0
Results for Earl Watson:

You searched for "Bonzi Wells"
3 results found.
0: Bonzi Wells
1: Bubba Wells
2: Owen Wells
Pick one: 0
Results for Bonzi Wells:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

You searched for "Lorenzen Wright"
2 results found.
0: Lorenzen Wright
1: Lonnie Wright
Pick one: 0
Results for Lorenzen Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-12-03,24-150,MEM,HOME,PHI,W (+8),1,38:27,12,19,...,15,2,1,3,2,1,34,33.7,7,Pau Gasol
1,2005-04-10,26-213,MEM,HOME,CHA,W (+7),1,35:55,8,13,...,11,2,3,3,0,1,25,29.3,-1,Shane Battier
2,2005-04-13,25-053,MEM,AWAY,HOU,L (-8),1,37:09,15,24,...,1,5,1,1,1,5,37,28.7,10,Mike Miller
3,2005-01-15,29-058,MEM,HOME,MIL,W (+19),1,31:43,9,17,...,2,8,5,0,0,1,25,27.9,30,Jason Williams
4,2005-03-04,26-176,MEM,HOME,TOR,W (+11),1,41:15,10,17,...,6,2,3,1,5,3,33,26.6,14,Shane Battier

In [20]:


MEM_2006_gamelog = []

for p in MEM_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2006_gamelog.append(player_log)
MEM_2006_gamelog = pd.concat(MEM_2006_gamelog)    
MEM_2006_gamelogs = MEM_2006_gamelog.copy()
MEM_2006_gamelogs['GAME_SCORE'] = MEM_2006_gamelogs['GAME_SCORE'].astype(float)
MEM_2006_games = MEM_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2006_games_csv = MEM_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2006_games.csv', index=False)
MEM_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2006_games.csv')
MEM_2006_games_proc.head()

You searched for "Chucky Atkins"
1 result found.
Chucky Atkins
Results for Chucky Atkins:

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Antonio Burks"
2 results found.
0: Antonio Burks
1: Antonio Davis
Pick one: 0
Results for Antonio Burks:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

You searched for "Bobby Jackson"
10 results found.
0: Bobby Jackson
1: Tony Jackson
2: Tony Jackson
3: Bobby Watson
4: Josh Jackson
5: Tracy Jackson
6: Bobby Wilson
7: Bobby Wilson
8: Bobby Jones
9: Bobby Jones
Pick one: 0
Results for Bobby Jackson:

You searched for "Dahntay Jones"
5 results found.
0: Dahntay Jones
1: Damian Jones
2: Dontae' Jones
3: Johnny Jones
4: Wah Wah Jones
Pick one: 0
Results for Dahntay Jones:

You searched for "Eddie Jones"
21 results found.
0: Eddie Jones
1: Edgar Jones
2: Eddie Miles
3: Eddie Owens
4: Tre Jones
5: Eddie House
6: Eddie Hughes
7: Eddie Johnson
8: Eddie Johnson
9: Alvin Jones
10: Askia Jones
11: Earl Jones
12: Jake Jones
13: Kevin Jones
14: Robin Jones
15: Steve Jones
16: Wali Jones
17: Wil Jones
18: Willie Jones
19: Eddie Jordan
20: Eddie Mast
Pick one: 0
Results for Eddie Jones:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Anthony Roberson"
4 results found.
0: Anthony Roberson
1: Anthony Roberts
2: Anthony Johnson
3: Tony Robertson
Pick one: 0
Results for Anthony Roberson:

You searched for "Lawrence Roberts"
1 result found.
Lawrence Roberts
Results for Lawrence Roberts:

You searched for "Damon Stoudamire"
2 results found.
0: Damon Stoudamire
1: Salim Stoudamire
Pick one: 0
Results for Damon Stoudamire:

You searched for "John Thomas"
21 results found.
0: John Thomas
1: Joe Thomas
2: Etan Thomas
3: Jim Thomas
4: John Thompson
5: John Logan
6: John Lucas
7: John Shumate
8: Carl Thomas
9: Jamel Thomas
10: James Thomas
11: Kenny Thomas
12: Kurt Thomas
13: Matt Thomas
14: Tim Thomas
15: John Hazen
16: John Oldham
17: John Stroud
18: John Trapp
19: John Tschogl
20: Johan Petro
Pick one: 0
Results for John Thomas:

You searched for "Jake Tsakalidis"
1 result found.
Jake Tsakalidis
Results for Jake Tsakalidis:

You searched for "Hakim Warrick"
1 result found.
Hakim Warrick
Results for Hakim Warrick:

You searched for "Lorenzen Wright"
2 results found.
0: Lorenzen Wright
1: Lonnie Wright
Pick one: 0
Results for Lorenzen Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-04-07,25-275,MEM,HOME,MIL,W (+10),1,42:55,13,15,...,14,8,2,3,5,3,33,35.0,10,Pau Gasol
1,2006-03-28,25-265,MEM,HOME,SEA,L (-1),1,45:22,17,28,...,9,3,1,2,4,1,44,33.6,0,Pau Gasol
2,2005-11-26,25-143,MEM,AWAY,DAL,W (+20),1,41:42,13,23,...,15,5,0,2,2,0,36,32.9,21,Pau Gasol
3,2006-01-25,25-203,MEM,HOME,MIN,W (+20),1,39:21,9,14,...,8,6,1,1,3,0,30,30.7,22,Pau Gasol
4,2006-02-27,25-236,MEM,HOME,WAS,W (+10),1,40:06,16,22,...,10,3,1,3,6,2,39,30.6,14,Pau Gasol

In [21]:


MEM_2007_gamelog = []

for p in MEM_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2007_gamelog.append(player_log)
MEM_2007_gamelog = pd.concat(MEM_2007_gamelog)    
MEM_2007_gamelogs = MEM_2007_gamelog.copy()
MEM_2007_gamelogs['GAME_SCORE'] = MEM_2007_gamelogs['GAME_SCORE'].astype(float)
MEM_2007_games = MEM_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2007_games_csv = MEM_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2007_games.csv', index=False)
MEM_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2007_games.csv')
MEM_2007_games_proc.head()

You searched for "Chucky Atkins"
1 result found.
Chucky Atkins
Results for Chucky Atkins:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Will Conroy"
6 results found.
0: Will Conroy
1: Will Cherry
2: Bill Crow
3: Bill Henry
4: Will Barton
5: Willie Long
Pick one: 0
Results for Will Conroy:

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Junior Harrington"
1 result found.
Junior Harrington
Results for Junior Harrington:

You searched for "Alexander Johnson"
1 result found.
Alexander Johnson
Results for Alexander Johnson:

You searched for "Dahntay Jones"
5 results found.
0: Dahntay Jones
1: Damian Jones
2: Dontae' Jones
3: Johnny Jones
4: Wah Wah Jones
Pick one: 0
Results for Dahntay Jones:

You searched for "Eddie Jones"
21 results found.
0: Eddie Jones
1: Edgar Jones
2: Eddie Miles
3: Eddie Owens
4: Tre Jones
5: Eddie House
6: Eddie Hughes
7: Eddie Johnson
8: Eddie Johnson
9: Alvin Jones
10: Askia Jones
11: Earl Jones
12: Jake Jones
13: Kevin Jones
14: Robin Jones
15: Steve Jones
16: Wali Jones
17: Wil Jones
18: Willie Jones
19: Eddie Jordan
20: Eddie Mast
Pick one: 0
Results for Eddie Jones:

You searched for "Tarence Kinsey"
1 result found.
Tarence Kinsey
Results for Tarence Kinsey:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Scott Padgett"
1 result found.
Scott Padgett
Results for Scott Padgett:

You searched for "Lawrence Roberts"
1 result found.
Lawrence Roberts
Results for Lawrence Roberts:

You searched for "Damon Stoudamire"
2 results found.
0: Damon Stoudamire
1: Salim Stoudamire
Pick one: 0
Results for Damon Stoudamire:

You searched for "Stromile Swift"
1 result found.
Stromile Swift
Results for Stromile Swift:

You searched for "Jake Tsakalidis"
1 result found.
Jake Tsakalidis
Results for Jake Tsakalidis:

You searched for "Hakim Warrick"
1 result found.
Hakim Warrick
Results for Hakim Warrick:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-01-29,26-207,MEM,HOME,SAC,W (+7),1,37:50,14,17,...,8,1,0,8,4,1,34,32.4,12,Pau Gasol
1,2007-02-21,27-002,MEM,AWAY,GSW,L (-3),1,49:08,16,27,...,5,6,1,0,6,1,45,32.0,0,Mike Miller
2,2007-03-02,26-239,MEM,AWAY,PHI,L (-5),1,45:04,13,20,...,13,6,1,3,3,2,31,31.2,-4,Pau Gasol
3,2007-03-20,26-257,MEM,HOME,NOK,L (-11),1,37:38,11,14,...,10,6,2,1,2,2,28,30.9,-14,Pau Gasol
4,2007-03-22,26-259,MEM,HOME,LAL,L (-2),1,44:08,17,23,...,15,2,0,1,1,4,35,30.9,1,Pau Gasol

In [26]:
# removed bobby jones
# removed Juan Carlos Navarro

MEM_2008_gamelog = []

for p in MEM_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2008_gamelog.append(player_log)
MEM_2008_gamelog = pd.concat(MEM_2008_gamelog)    
MEM_2008_gamelogs = MEM_2008_gamelog.copy()
MEM_2008_gamelogs['GAME_SCORE'] = MEM_2008_gamelogs['GAME_SCORE'].astype(float)
MEM_2008_games = MEM_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2008_games_csv = MEM_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2008_games.csv', index=False)
MEM_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2008_games.csv')
MEM_2008_games_proc.head()

You searched for "Andre Brown"
15 results found.
0: Andre Brown
1: Dee Brown
2: Dee Brown
3: Randy Brown
4: Bruce Brown
5: Damone Brown
6: Fred Brown
7: George Brown
8: Jabari Brown
9: Kwame Brown
10: Larry Brown
11: Mike Brown
12: Tierre Brown
13: Andre Moore
14: Andre Owens
Pick one: 0
Results for Andre Brown:

You searched for "Kwame Brown"
9 results found.
0: Kwame Brown
1: Andre Brown
2: Bruce Brown
3: Damone Brown
4: Dee Brown
5: Dee Brown
6: Mike Brown
7: Stan Brown
8: Jim Browne
Pick one: 0
Results for Kwame Brown:

You searched for "Brian Cardinal"
2 results found.
0: Brian Cardinal
1: Brian Martin
Pick one: 0
Results for Brian Cardinal:

You searched for "Jason Collins"
11 results found.
0: Jason Collins
1: Jason Collier
2: Jarron Collins
3: Don Collins
4: James Collins
5: John Collins
6: Art Collins
7: Jimmy Collins
8: Mardy Collins
9: Zach Collins
10: Jason Williams
Pick one: 0
Results for Jason Collins:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Javaris Crittenton"
1 result found.
Javaris Crittenton
Results for Javaris Crittenton:

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Casey Jacobsen"
1 result found.
Casey Jacobsen
Results for Casey Jacobsen:

You searched for "Tarence Kinsey"
1 result found.
Tarence Kinsey
Results for Tarence Kinsey:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Darko Miličić"
2 results found.
0: Darko Milicic
1: Marko Milic
Pick one: 0
Results for Darko Milicic:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Jeremy Richardson"
2 results found.
0: Jeremy Richardson
1: Norm Richardson
Pick one: 0
Results for Jeremy Richardson:

You searched for "Damon Stoudamire"
2 results found.
0: Damon Stoudamire
1: Salim Stoudamire
Pick one: 0
Results for Damon Stoudamire:

You searched for "Stromile Swift"
1 result found.
Stromile Swift
Results for Stromile Swift:

You searched for "Hakim Warrick"
1 result found.
Hakim Warrick
Results for Hakim Warrick:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-01-11,27-189,MEM,AWAY,GSW,L (-12),1,44:43,17,25,...,11,3,1,1,3,2,43,36.0,2,Pau Gasol
1,2008-04-06,28-047,MEM,AWAY,MIN,W (+12),1,38:02,12,20,...,10,6,0,2,0,0,34,33.8,18,Mike Miller
2,2008-03-04,27-242,LAL,AWAY,SAC,W (+12),1,42:16,10,15,...,10,4,2,3,3,2,31,31.0,17,Pau Gasol
3,2008-03-21,28-031,MEM,AWAY,NYK,W (+14),1,35:54,12,16,...,7,4,1,1,3,2,34,30.4,18,Mike Miller
4,2008-04-08,21-235,MEM,HOME,PHO,L (-14),1,42:58,13,22,...,8,3,0,2,2,2,36,29.3,-12,Rudy Gay

In [27]:


MEM_2009_gamelog = []

for p in MEM_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2009_gamelog.append(player_log)
MEM_2009_gamelog = pd.concat(MEM_2009_gamelog)    
MEM_2009_gamelogs = MEM_2009_gamelog.copy()
MEM_2009_gamelogs['GAME_SCORE'] = MEM_2009_gamelogs['GAME_SCORE'].astype(float)
MEM_2009_games = MEM_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2009_games_csv = MEM_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2009_games.csv', index=False)
MEM_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2009_games.csv')
MEM_2009_games_proc.head()

You searched for "Darrell Arthur"
3 results found.
0: Darrell Arthur
1: Darrell Hardy
2: Darrell Walker
Pick one: 0
Results for Darrell Arthur:

You searched for "Greg Buckner"
4 results found.
0: Greg Buckner
1: Greg Butler
2: Greg Bunch
3: Greg Jackson
Pick one: 0
Results for Greg Buckner:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Javaris Crittenton"
1 result found.
Javaris Crittenton
Results for Javaris Crittenton:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Hamed Haddadi"
1 result found.
Hamed Haddadi
Results for Hamed Haddadi:

You searched for "Marko Jarić"
10 results found.
0: Marko Jaric
1: Marko Milic
2: Dario Saric
3: Mark Alarie
4: Mark Davis
5: Mark Davis
6: Marko Guduric
7: Mark Price
8: Mark Acres
9: Mark Macon
Pick one: 0
Results for Marko Jaric:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "O.J. Mayo"
2 results found.
0: O.J. Mayo
1: T.J. Leaf
Pick one: 0
Results for O.J. Mayo:

You searched for "Darius Miles"
6 results found.
0: Darius Miles
1: Darius Miller
2: Darius Bazley
3: Aaron Miles
4: Chris Mills
5: Darius Morris
Pick one: 0
Results for Darius Miles:

You searched for "Darko Miličić"
2 results found.
0: Darko Milicic
1: Marko Milic
Pick one: 0
Results for Darko Milicic:

You searched for "Quinton Ross"
2 results found.
0: Quinton Ross
1: Quinton Rose
Pick one: 0
Results for Quinton Ross:

You searched for "Hakim Warrick"
1 result found.
Hakim Warrick
Results for Hakim Warrick:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2009-03-04,22-199,MEM,AWAY,LAC,W (+23),1,37:29,12,22,...,8,4,2,0,1,2,35,31.0,13,Rudy Gay
1,2009-02-04,21-091,MEM,HOME,HOU,W (+11),1,41:27,13,22,...,3,4,3,1,1,2,32,27.4,12,O.J. Mayo
2,2009-03-07,24-037,MEM,HOME,PHI,L (-5),1,39:09,11,15,...,13,2,0,3,2,5,30,27.3,1,Marc Gasol
3,2008-11-10,21-005,MEM,AWAY,PHO,L (-5),1,44:16,12,23,...,3,5,3,0,2,2,33,26.3,-3,O.J. Mayo
4,2009-03-07,21-147,MEM,HOME,PHI,L (-5),1,43:54,14,21,...,4,9,1,1,4,3,31,25.9,-2,Mike Conley

In [28]:


MEM_2010_gamelog = []

for p in MEM_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2010_gamelog.append(player_log)
MEM_2010_gamelog = pd.concat(MEM_2010_gamelog)    
MEM_2010_gamelogs = MEM_2010_gamelog.copy()
MEM_2010_gamelogs['GAME_SCORE'] = MEM_2010_gamelogs['GAME_SCORE'].astype(float)
MEM_2010_games = MEM_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2010_games_csv = MEM_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2010_games.csv', index=False)
MEM_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2010_games.csv')
MEM_2010_games_proc.head()

You searched for "Darrell Arthur"
3 results found.
0: Darrell Arthur
1: Darrell Hardy
2: Darrell Walker
Pick one: 0
Results for Darrell Arthur:

You searched for "Ronnie Brewer"
4 results found.
0: Ronnie Brewer
1: Ron Brewer
2: Ronnie Lester
3: Ronnie Price
Pick one: 0
Results for Ronnie Brewer:

You searched for "DeMarre Carroll"
1 result found.
DeMarre Carroll
Results for DeMarre Carroll:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Trey Gilder"
2 results found.
0: Trey Gilder
1: Trey Lyles
Pick one: 0
Results for Trey Gilder:

You searched for "Hamed Haddadi"
1 result found.
Hamed Haddadi
Results for Hamed Haddadi:

You searched for "Lester Hudson"
1 result found.
Lester Hudson
Results for Lester Hudson:

You searched for "Steven Hunter"
4 results found.
0: Steven Hunter
1: Steve Colter
2: Steve Hamer
3: Steven Kramer
Pick one: 0
Results for Steven Hunter:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "O.J. Mayo"
2 results found.
0: O.J. Mayo
1: T.J. Leaf
Pick one: 0
Results for O.J. Mayo:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Hasheem Thabeet"
1 result found.
Hasheem Thabeet
Results for Hasheem Thabeet:

You searched for "Jamaal Tinsley"
1 result found.
Jamaal Tinsley
Results for Jamaal Tinsley:

You searched for "Marcus Williams"
10 results found.
0: Marcus Williams
1: Marcus Williams
2: Marvin Williams
3: Aaron Williams
4: Art Williams
5: Charles Williams
6: Earl Williams
7: Gus Williams
8: Matt Williams
9: Ward Williams
Pick one: 0
Results for Marcus Williams:

You searched for "Sam Young"
10 results found.
0: Sam Young
1: Tim Young
2: James Young
3: Joe Young
4: Trae Young
5: Sam Bowie
6: Sam Jones
7: Danny Young
8: Nick Young
9: Sam Lacey
Pick one: 0
Results for Sam Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2009-11-01,21-361,MEM,AWAY,DEN,L (-10),1,37:47,17,25,...,5,4,1,0,0,2,40,34.2,-4,O.J. Mayo
1,2009-12-20,28-157,MEM,HOME,DEN,W (+6),1,43:12,13,21,...,24,3,1,1,2,3,32,33.9,-2,Zach Randolph
2,2009-12-08,28-145,MEM,HOME,CLE,W (+2),1,47:22,10,19,...,14,2,4,1,1,4,32,33.2,4,Zach Randolph
3,2009-12-22,28-159,MEM,HOME,GSW,W (+13),1,39:59,14,21,...,18,2,1,0,3,3,33,29.9,10,Zach Randolph
4,2010-02-27,28-226,MEM,AWAY,NYK,W (+11),1,38:56,10,24,...,25,2,2,1,2,3,31,29.8,4,Zach Randolph

In [29]:

MEM_2011_gamelog = []

for p in MEM_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2011_gamelog.append(player_log)
MEM_2011_gamelog = pd.concat(MEM_2011_gamelog)    
MEM_2011_gamelogs = MEM_2011_gamelog.copy()
MEM_2011_gamelogs['GAME_SCORE'] = MEM_2011_gamelogs['GAME_SCORE'].astype(float)
MEM_2011_games = MEM_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2011_games_csv = MEM_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2011_games.csv', index=False)
MEM_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2011_games.csv')
MEM_2011_games_proc.head()

You searched for "Tony Allen"
26 results found.
0: Tony Allen
1: Bob Allen
2: Randy Allen
3: Ray Allen
4: Tony Fuller
5: Tony Kappen
6: Bill Allen
7: Lavoy Allen
8: Toby Bailey
9: Tony Bradley
10: Tony Brown
11: Tony Dawson
12: Tony Delk
13: Tony Farmer
14: Tony Parker
15: Tony Wroten
16: Tony Zeno
17: Tony Battie
18: Tony Dumas
19: Tony Jaros
20: Tony Lavelli
21: Tony Price
22: Tony Snell
23: Tony White
24: Lonzo Ball
25: Donta Hall
Pick one: 0
Results for Tony Allen:

You searched for "Darrell Arthur"
3 results found.
0: Darrell Arthur
1: Darrell Hardy
2: Darrell Walker
Pick one: 0
Results for Darrell Arthur:

You searched for "Shane Battier"
1 result found.
Shane Battier
Results for Shane Battier:

You searched for "Rodney Carney"
3 results found.
0: Rodney Carney
1: Rodney McCray
2: Rodney Monroe
Pick one: 0
Results for Rodney Carney:

You searched for "DeMarre Carroll"
1 result found.
DeMarre Carroll
Results for DeMarre Carroll:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Hamed Haddadi"
1 result found.
Hamed Haddadi
Results for Hamed Haddadi:

You searched for "Xavier Henry"
3 results found.
0: Xavier Henry
1: Conner Henry
2: Xavier Sneed
Pick one: 0
Results for Xavier Henry:

You searched for "Acie Law"
3 results found.
0: Acie Law
1: Acie Earl
2: Vic Law
Pick one: 0
Results for Acie Law:

You searched for "O.J. Mayo"
2 results found.
0: O.J. Mayo
1: T.J. Leaf
Pick one: 0
Results for O.J. Mayo:

You searched for "Leon Powe"
5 results found.
0: Leon Powe
1: Leon Brown
2: Leon Wood
3: Lou Roe
4: Leon Benbow
Pick one: 0
Results for Leon Powe:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Hasheem Thabeet"
1 result found.
Hasheem Thabeet
Results for Hasheem Thabeet:

You searched for "Greivis Vásquez"
1 result found.
Greivis Vasquez
Results for Greivis Vasquez:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

You searched for "Sam Young"
10 results found.
0: Sam Young
1: Tim Young
2: James Young
3: Joe Young
4: Trae Young
5: Sam Bowie
6: Sam Jones
7: Danny Young
8: Nick Young
9: Sam Lacey
Pick one: 0
Results for Sam Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-12-29,29-166,MEM,AWAY,SAC,L (-2),1,36:55,15,27,...,17,3,2,0,0,3,35,33.3,-4,Zach Randolph
1,2011-01-12,29-180,MEM,AWAY,DET,W (+8),1,39:24,10,17,...,17,2,2,1,3,1,34,32.7,5,Zach Randolph
2,2010-12-26,24-131,MEM,AWAY,IND,W (+14),1,39:38,11,20,...,8,5,5,1,1,4,30,31.0,17,Rudy Gay
3,2010-12-08,29-145,MEM,AWAY,PHO,W (+6),1,43:19,15,19,...,17,0,0,0,2,4,34,29.8,18,Zach Randolph
4,2011-04-08,29-266,MEM,HOME,SAC,W (+5),1,42:30,10,18,...,15,4,4,0,1,2,27,28.7,16,Zach Randolph

In [30]:

MEM_2012_gamelog = []

for p in MEM_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2012_gamelog.append(player_log)
MEM_2012_gamelog = pd.concat(MEM_2012_gamelog)    
MEM_2012_gamelogs = MEM_2012_gamelog.copy()
MEM_2012_gamelogs['GAME_SCORE'] = MEM_2012_gamelogs['GAME_SCORE'].astype(float)
MEM_2012_games = MEM_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2012_games_csv = MEM_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2012_games.csv', index=False)
MEM_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2012_games.csv')
MEM_2012_games_proc.head()

You searched for "Tony Allen"
26 results found.
0: Tony Allen
1: Bob Allen
2: Randy Allen
3: Ray Allen
4: Tony Fuller
5: Tony Kappen
6: Bill Allen
7: Lavoy Allen
8: Toby Bailey
9: Tony Bradley
10: Tony Brown
11: Tony Dawson
12: Tony Delk
13: Tony Farmer
14: Tony Parker
15: Tony Wroten
16: Tony Zeno
17: Tony Battie
18: Tony Dumas
19: Tony Jaros
20: Tony Lavelli
21: Tony Price
22: Tony Snell
23: Tony White
24: Lonzo Ball
25: Donta Hall
Pick one: 0
Results for Tony Allen:

You searched for "Gilbert Arenas"
1 result found.
Gilbert Arenas
Results for Gilbert Arenas:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Dante Cunningham"
3 results found.
0: Dante Cunningham
1: Dick Cunningham
2: Jared Cunningham
Pick one: 0
Results for Dante Cunningham:

You searched for "Josh Davis"
27 results found.
0: Josh Davis
1: Bob Davis
2: Jim Davis
3: Ron Davis
4: Josh Reaves
5: Josh Hall
6: Bob Davies
7: Ben Davis
8: Bill Davis
9: Brad Davis
10: Dale Davis
11: Ed Davis
12: Glen Davis
13: Johnny Davis
14: Lee Davis
15: Mark Davis
16: Mark Davis
17: Mel Davis
18: Mike Davis
19: Mike Davis
20: Monti Davis
21: Paul Davis
22: Ralph Davis
23: Red Davis
24: Walt Davis
25: Josh Hart
26: Josh Grant
Pick one: 0
Results for Josh Davis:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Hamed Haddadi"
1 result found.
Hamed Haddadi
Results for Hamed Haddadi:

You searched for "Lester Hudson"
1 result found.
Lester Hudson
Results for Lester Hudson:

You searched for "O.J. Mayo"
2 results found.
0: O.J. Mayo
1: T.J. Leaf
Pick one: 0
Results for O.J. Mayo:

You searched for "Jeremy Pargo"
4 results found.
0: Jeremy Pargo
1: Jeremy Lamb
2: Jeremy Evans
3: Jeremy Tyler
Pick one: 0
Results for Jeremy Pargo:

You searched for "Quincy Pondexter"
1 result found.
Quincy Pondexter
Results for Quincy Pondexter:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Josh Selby"
8 results found.
0: Josh Selby
1: Josh Hall
2: Josh Gray
3: Josh Smith
4: Josh Green
5: Josh Boone
6: Josh Davis
7: Josh Powell
Pick one: 0
Results for Josh Selby:

You searched for "Brian Skinner"
6 results found.
0: Brian Skinner
1: Brian Oliver
2: Brian Quinnett
3: Al Skinner
4: Tal Skinner
5: Brian Winters
Pick one: 0
Results for Brian Skinner:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Sam Young"
10 results found.
0: Sam Young
1: Tim Young
2: James Young
3: Joe Young
4: Trae Young
5: Sam Bowie
6: Sam Jones
7: Danny Young
8: Nick Young
9: Sam Lacey
Pick one: 0
Results for Sam Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-04-11,25-238,MEM,HOME,PHO,W (+11),1,42:01,13,20,...,7,1,2,1,0,2,32,29.5,23,Rudy Gay
1,2012-04-18,25-245,MEM,HOME,NOH,W (+12),1,30:08,9,14,...,5,4,1,2,1,0,26,26.7,27,Rudy Gay
2,2012-01-21,26-357,MEM,HOME,SAC,W (+33),1,31:56,8,11,...,11,5,1,6,0,3,20,26.3,39,Marc Gasol
3,2012-03-07,25-203,MEM,AWAY,GSW,W (+18),1,39:14,10,20,...,12,5,1,1,0,2,26,26.0,18,Rudy Gay
4,2012-04-14,25-241,MEM,HOME,UTA,W (+5),1,40:23,8,16,...,12,1,1,2,1,1,26,24.5,-1,Rudy Gay

In [31]:
MEM_2013_gamelog = []

for p in MEM_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2013_gamelog.append(player_log)
MEM_2013_gamelog = pd.concat(MEM_2013_gamelog)    
MEM_2013_gamelogs = MEM_2013_gamelog.copy()
MEM_2013_gamelogs['GAME_SCORE'] = MEM_2013_gamelogs['GAME_SCORE'].astype(float)
MEM_2013_games = MEM_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2013_games_csv = MEM_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2013_games.csv', index=False)
MEM_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2013_games.csv')
MEM_2013_games_proc.head()

You searched for "Tony Allen"
26 results found.
0: Tony Allen
1: Bob Allen
2: Randy Allen
3: Ray Allen
4: Tony Fuller
5: Tony Kappen
6: Bill Allen
7: Lavoy Allen
8: Toby Bailey
9: Tony Bradley
10: Tony Brown
11: Tony Dawson
12: Tony Delk
13: Tony Farmer
14: Tony Parker
15: Tony Wroten
16: Tony Zeno
17: Tony Battie
18: Tony Dumas
19: Tony Jaros
20: Tony Lavelli
21: Tony Price
22: Tony Snell
23: Tony White
24: Lonzo Ball
25: Donta Hall
Pick one: 0
Results for Tony Allen:

You searched for "Darrell Arthur"
3 results found.
0: Darrell Arthur
1: Darrell Hardy
2: Darrell Walker
Pick one: 0
Results for Darrell Arthur:

You searched for "Jerryd Bayless"
1 result found.
Jerryd Bayless
Results for Jerryd Bayless:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Ed Davis"
34 results found.
0: Ed Davis
1: Red Davis
2: Ben Davis
3: Lee Davis
4: Mel Davis
5: Bob Davis
6: Brad Davis
7: Glen Davis
8: Jim Davis
9: Ron Davis
10: Ed Kasid
11: Ed Rains
12: Ed Dahler
13: Bob Davies
14: Bill Davis
15: Dale Davis
16: Josh Davis
17: Mark Davis
18: Mark Davis
19: Mike Davis
20: Mike Davis
21: Paul Davis
22: Terry Davis
23: Tyler Davis
24: Walt Davis
25: Ed Earle
26: Ed Gayda
27: Ed Melvin
28: Ed Beach
29: Ed Leede
30: Ed Mikan
31: Ed Nealy
32: Med Park
33: Todd Day
Pick one: 0
Results for Ed Davis:

You searched for "Austin Daye"
4 results found.
0: Austin Daye
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Austin Daye:

You searched for "Keyon Dooling"
1 result found.
Keyon Dooling
Results for Keyon Dooling:

You searched for "Wayne Ellington"
1 result found.
Wayne Ellington
Results for Wayne Ellington:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Hamed Haddadi"
1 result found.
Hamed Haddadi
Results for Hamed Haddadi:

You searched for "Chris Johnson"
27 results found.
0: Chris Johnson
1: Chris Johnson
2: Charles Johnson
3: Cheese Johnson
4: Eric Johnson
5: Chris Robinson
6: Chris Duhon
7: Amir Johnson
8: Arnie Johnson
9: Brice Johnson
10: Clay Johnson
11: Dennis Johnson
12: Eddie Johnson
13: Eddie Johnson
14: Ervin Johnson
15: Gus Johnson
16: James Johnson
17: Kevin Johnson
18: Larry Johnson
19: Larry Johnson
20: Magic Johnson
21: Neil Johnson
22: Ollie Johnson
23: Omari Johnson
24: Rich Johnson
25: Ron Johnson
26: Trey Johnson
Pick one: 0
Results for Chris Johnson:

You searched for "Jon Leuer"
18 results found.
0: Jon Leuer
1: Ron Lee
2: Jon Teske
3: Ron Baker
4: Ron Brewer
5: John Coker
6: Don Dee
7: Fat Lever
8: Ron Mercer
9: Ron Reed
10: Von Wafer
11: Joe DePre
12: John Drew
13: Joe Kleine
14: John Long
15: John Olive
16: Ron Riley
17: John Wall
Pick one: 0
Results for Jon Leuer:

You searched for "Dexter Pittman"
1 result found.
Dexter Pittman
Results for Dexter Pittman:

You searched for "Quincy Pondexter"
1 result found.
Quincy Pondexter
Results for Quincy Pondexter:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Josh Selby"
8 results found.
0: Josh Selby
1: Josh Hall
2: Josh Gray
3: Josh Smith
4: Josh Green
5: Josh Boone
6: Josh Davis
7: Josh Powell
Pick one: 0
Results for Josh Selby:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Tony Wroten"
9 results found.
0: Tony Wroten
1: Tony Brown
2: Tony White
3: Tony Allen
4: Tony Kappen
5: Tony Price
6: Tony Battie
7: Tony Dawson
8: Tony Zeno
Pick one: 0
Results for Tony Wroten:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-12-04,31-141,MEM,HOME,PHO,W (+10),1,44:16,15,22,...,22,0,1,3,3,2,38,37.3,16,Zach Randolph
1,2014-01-31,27-167,SAC,AWAY,DAL,L (-4),1,35:36,10,16,...,12,6,1,0,3,0,35,34.0,5,Rudy Gay
2,2013-04-01,26-227,TOR,HOME,DET,L (-10),1,40:16,13,18,...,6,5,1,1,1,4,34,31.4,-11,Rudy Gay
3,2014-01-21,27-157,SAC,AWAY,NOP,W (+17),1,42:28,16,25,...,8,5,0,0,3,5,41,31.2,12,Rudy Gay
4,2014-01-15,27-151,SAC,AWAY,MIN,W (+3),1,37:17,12,19,...,5,6,2,1,2,2,33,30.5,2,Rudy Gay

In [32]:
MEM_2014_gamelog = []

for p in MEM_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2014_gamelog.append(player_log)
MEM_2014_gamelog = pd.concat(MEM_2014_gamelog)    
MEM_2014_gamelogs = MEM_2014_gamelog.copy()
MEM_2014_gamelogs['GAME_SCORE'] = MEM_2014_gamelogs['GAME_SCORE'].astype(float)
MEM_2014_games = MEM_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2014_games_csv = MEM_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2014_games.csv', index=False)
MEM_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2014_games.csv')
MEM_2014_games_proc.head()

You searched for "Tony Allen"
26 results found.
0: Tony Allen
1: Bob Allen
2: Randy Allen
3: Ray Allen
4: Tony Fuller
5: Tony Kappen
6: Bill Allen
7: Lavoy Allen
8: Toby Bailey
9: Tony Bradley
10: Tony Brown
11: Tony Dawson
12: Tony Delk
13: Tony Farmer
14: Tony Parker
15: Tony Wroten
16: Tony Zeno
17: Tony Battie
18: Tony Dumas
19: Tony Jaros
20: Tony Lavelli
21: Tony Price
22: Tony Snell
23: Tony White
24: Lonzo Ball
25: Donta Hall
Pick one: 0
Results for Tony Allen:

You searched for "Jerryd Bayless"
1 result found.
Jerryd Bayless
Results for Jerryd Bayless:

You searched for "Nick Calathes"
1 result found.
Nick Calathes
Results for Nick Calathes:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Seth Curry"
4 results found.
0: Seth Curry
1: Dell Curry
2: Eddy Curry
3: Stephen Curry
Pick one: 0
Results for Seth Curry:

You searched for "Ed Davis"
34 results found.
0: Ed Davis
1: Red Davis
2: Ben Davis
3: Lee Davis
4: Mel Davis
5: Bob Davis
6: Brad Davis
7: Glen Davis
8: Jim Davis
9: Ron Davis
10: Ed Kasid
11: Ed Rains
12: Ed Dahler
13: Bob Davies
14: Bill Davis
15: Dale Davis
16: Josh Davis
17: Mark Davis
18: Mark Davis
19: Mike Davis
20: Mike Davis
21: Paul Davis
22: Terry Davis
23: Tyler Davis
24: Walt Davis
25: Ed Earle
26: Ed Gayda
27: Ed Melvin
28: Ed Beach
29: Ed Leede
30: Ed Mikan
31: Ed Nealy
32: Med Park
33: Todd Day
Pick one: 0
Results for Ed Davis:

You searched for "Jamaal Franklin"
1 result found.
Jamaal Franklin
Results for Jamaal Franklin:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "James Johnson"
32 results found.
0: James Johnson
1: Amir Johnson
2: Dave Johnson
3: Joe Johnson
4: James Robinson
5: James Cotton
6: Andy Johnson
7: Armon Johnson
8: Avery Johnson
9: Cameron Johnson
10: Charles Johnson
11: Cheese Johnson
12: Chris Johnson
13: Chris Johnson
14: Ed Johnson
15: Gus Johnson
16: JaJuan Johnson
17: John Johnson
18: Ken Johnson
19: Ken Johnson
20: Larry Johnson
21: Larry Johnson
22: Lee Johnson
23: Magic Johnson
24: Marques Johnson
25: Ralph Johnson
26: Stew Johnson
27: Trey Johnson
28: Tyler Johnson
29: Nate Johnston
30: James Jones
31: James Collins
Pick one: 0
Results for James Johnson:

You searched for "Kosta Koufos"
1 result found.
Kosta Koufos
Results for Kosta Koufos:

You searched for "Courtney Lee"
3 results found.
0: Courtney Lee
1: Courtney Sims
2: Joe Courtney
Pick one: 00
Results for Courtney Lee:

You searched for "Jon Leuer"
18 results found.
0: Jon Leuer
1: Ron Lee
2: Jon Teske
3: Ron Baker
4: Ron Brewer
5: John Coker
6: Don Dee
7: Fat Lever
8: Ron Mercer
9: Ron Reed
10: Von Wafer
11: Joe DePre
12: John Drew
13: Joe Kleine
14: John Long
15: John Olive
16: Ron Riley
17: John Wall
Pick one: 0
Results for Jon Leuer:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Darius Morris"
5 results found.
0: Darius Morris
1: Marcus Morris
2: Chris Morris
3: Darius Miles
4: Darius Miller
Pick one: 0
Results for Darius Morris:

You searched for "Quincy Pondexter"
1 result found.
Quincy Pondexter
Results for Quincy Pondexter:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-12-30,26-080,MEM,HOME,CHI,L (-4),1,36:33,9,19,...,6,9,6,0,1,2,26,29.0,5,Mike Conley
1,2013-11-18,32-125,MEM,AWAY,LAC,W (+4),1,36:24,10,16,...,15,2,2,0,0,4,26,26.7,7,Zach Randolph
2,2014-01-29,26-110,MEM,AWAY,SAC,W (+10),1,34:25,8,13,...,3,10,2,0,4,2,27,26.6,10,Mike Conley
3,2014-01-10,26-091,MEM,HOME,PHO,W (+5),1,38:59,11,19,...,0,7,0,0,0,2,31,26.2,-1,Mike Conley
4,2014-03-01,32-228,MEM,HOME,CLE,W (+14),1,37:05,11,17,...,14,3,4,0,2,0,23,26.2,23,Zach Randolph

In [33]:

MEM_2015_gamelog = []

for p in MEM_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2015_gamelog.append(player_log)
MEM_2015_gamelog = pd.concat(MEM_2015_gamelog)    
MEM_2015_gamelogs = MEM_2015_gamelog.copy()
MEM_2015_gamelogs['GAME_SCORE'] = MEM_2015_gamelogs['GAME_SCORE'].astype(float)
MEM_2015_games = MEM_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2015_games_csv = MEM_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2015_games.csv', index=False)
MEM_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2015_games.csv')
MEM_2015_games_proc.head()

You searched for "Jordan Adams"
8 results found.
0: Jordan Adams
1: Alvan Adams
2: Don Adams
3: Hassan Adams
4: Jaylen Adams
5: Jordan Nwora
6: Jordan Farmar
7: Jordan McRae
Pick one: 0
Results for Jordan Adams:

You searched for "Tony Allen"
26 results found.
0: Tony Allen
1: Bob Allen
2: Randy Allen
3: Ray Allen
4: Tony Fuller
5: Tony Kappen
6: Bill Allen
7: Lavoy Allen
8: Toby Bailey
9: Tony Bradley
10: Tony Brown
11: Tony Dawson
12: Tony Delk
13: Tony Farmer
14: Tony Parker
15: Tony Wroten
16: Tony Zeno
17: Tony Battie
18: Tony Dumas
19: Tony Jaros
20: Tony Lavelli
21: Tony Price
22: Tony Snell
23: Tony White
24: Lonzo Ball
25: Donta Hall
Pick one: 0
Results for Tony Allen:

You searched for "Nick Calathes"
1 result found.
Nick Calathes
Results for Nick Calathes:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "JaMychal Green"
1 result found.
JaMychal Green
Results for JaMychal Green:

You searched for "Jeff Green"
21 results found.
0: Jeff Green
1: Josh Green
2: Jeff Adrien
3: Jeff Grayer
4: Ken Green
5: Sean Green
6: Jeff Ayres
7: Jeff Cross
8: A.C. Green
9: Devin Green
10: Kenny Green
11: Mike Green
12: Si Green
13: Steve Green
14: Jeff Lebo
15: Jeff Martin
16: Jeff Turner
17: Jeff Webb
18: Jeff Foote
19: Jeff Slade
20: Jeff Teague
Pick one: 0
Results for Jeff Green:

You searched for "Kosta Koufos"
1 result found.
Kosta Koufos
Results for Kosta Koufos:

You searched for "Courtney Lee"
3 results found.
0: Courtney Lee
1: Courtney Sims
2: Joe Courtney
Pick one: 0
Results for Courtney Lee:

You searched for "Jon Leuer"
18 results found.
0: Jon Leuer
1: Ron Lee
2: Jon Teske
3: Ron Baker
4: Ron Brewer
5: John Coker
6: Don Dee
7: Fat Lever
8: Ron Mercer
9: Ron Reed
10: Von Wafer
11: Joe DePre
12: John Drew
13: Joe Kleine
14: John Long
15: John Olive
16: Ron Riley
17: John Wall
Pick one: 0
Results for Jon Leuer:

You searched for "Kalin Lucas"
3 results found.
0: Kalin Lucas
1: Al Lucas
2: John Lucas
Pick one: 0
Results for Kalin Lucas:

You searched for "Quincy Pondexter"
1 result found.
Quincy Pondexter
Results for Quincy Pondexter:

You searched for "Tayshaun Prince"
2 results found.
0: Tayshaun Prince
1: Taurean Prince
Pick one: 0
Results for Tayshaun Prince:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Russ Smith"
31 results found.
0: Russ Smith
1: Ish Smith
2: Josh Smith
3: Otis Smith
4: Al Smith
5: Bill Smith
6: Chris Smith
7: Chris Smith
8: Craig Smith
9: Deb Smith
10: Don Smith
11: Don Smith
12: Doug Smith
13: Ed Smith
14: Greg Smith
15: Greg Smith
16: J.R. Smith
17: Jason Smith
18: Jim Smith
19: Joe Smith
20: John Smith
21: Ken Smith
22: Leon Smith
23: Mike Smith
24: Pete Smith
25: Phil Smith
26: Randy Smith
27: Sam Smith
28: Sam Smith
29: Tony Smith
30: Rik Smits
Pick one: 0
Results for Russ Smith:

You searched for "Jarnell Stokes"
1 result found.
Jarnell Stokes
Results for Jarnell Stokes:

You searched for "Tyrus Thomas"
7 results found.
0: Tyrus Thomas
1: Terry Thomas
2: Carl Thomas
3: James Thomas
4: Khyri Thomas
5: Kurt Thomas
6: Tim Thomas
Pick one: 0
Results for Tyrus Thomas:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-04-15,30-076,MEM,HOME,IND,W (+12),1,37:42,13,19,...,13,0,2,1,1,3,33,30.5,1,Marc Gasol
1,2014-10-29,29-273,MEM,HOME,MIN,W (+4),1,36:55,12,17,...,9,3,2,2,3,1,32,29.7,9,Marc Gasol
2,2014-12-09,29-314,MEM,HOME,DAL,W (+9),1,37:08,9,14,...,6,6,1,0,1,2,30,29.4,13,Marc Gasol
3,2014-12-13,27-063,MEM,AWAY,PHI,W (+5),1,42:21,13,22,...,3,9,0,0,4,3,36,27.0,-6,Mike Conley
4,2014-12-30,27-080,MEM,HOME,SAS,W (+8),1,32:40,10,13,...,7,6,1,0,4,3,30,26.6,9,Mike Conley

In [39]:


MEM_2016_gamelog = []

for p in MEM_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2016_gamelog.append(player_log)
MEM_2016_gamelog = pd.concat(MEM_2016_gamelog)    
MEM_2016_gamelogs = MEM_2016_gamelog.copy()
MEM_2016_gamelogs['GAME_SCORE'] = MEM_2016_gamelogs['GAME_SCORE'].astype(float)
MEM_2016_games = MEM_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2016_games_csv = MEM_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2016_games.csv', index=False)
MEM_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2016_games.csv')
MEM_2016_games_proc.head()

You searched for "Jordan Adams"
8 results found.
0: Jordan Adams
1: Alvan Adams
2: Don Adams
3: Hassan Adams
4: Jaylen Adams
5: Jordan Nwora
6: Jordan Farmar
7: Jordan McRae
Pick one: 0
Results for Jordan Adams:

You searched for "Tony Allen"
26 results found.
0: Tony Allen
1: Bob Allen
2: Randy Allen
3: Ray Allen
4: Tony Fuller
5: Tony Kappen
6: Bill Allen
7: Lavoy Allen
8: Toby Bailey
9: Tony Bradley
10: Tony Brown
11: Tony Dawson
12: Tony Delk
13: Tony Farmer
14: Tony Parker
15: Tony Wroten
16: Tony Zeno
17: Tony Battie
18: Tony Dumas
19: Tony Jaros
20: Tony Lavelli
21: Tony Price
22: Tony Snell
23: Tony White
24: Lonzo Ball
25: Donta Hall
Pick one: 0
Results for Tony Allen:

You searched for "Chris Andersen"
4 results found.
0: Chris Andersen
1: David Andersen
2: Eric Anderson
3: Chris Herren
Pick one: 0
Results for Chris Andersen:

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Mario Chalmers"
1 result found.
Mario Chalmers
Results for Mario Chalmers:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Bryce Cotton"
2 results found.
0: Bryce Cotton
1: Jack Cotton
Pick one: 0
Results for Bryce Cotton:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Jordan Farmar"
4 results found.
0: Jordan Farmar
1: Jordan Ford
2: Jordan McRae
3: Jordan Adams
Pick one: 0
Results for Jordan Farmar:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "JaMychal Green"
1 result found.
JaMychal Green
Results for JaMychal Green:

You searched for "Jeff Green"
21 results found.
0: Jeff Green
1: Josh Green
2: Jeff Adrien
3: Jeff Grayer
4: Ken Green
5: Sean Green
6: Jeff Ayres
7: Jeff Cross
8: A.C. Green
9: Devin Green
10: Kenny Green
11: Mike Green
12: Si Green
13: Steve Green
14: Jeff Lebo
15: Jeff Martin
16: Jeff Turner
17: Jeff Webb
18: Jeff Foote
19: Jeff Slade
20: Jeff Teague
Pick one: 0
Results for Jeff Green:

You searched for "Ryan Hollins"
3 results found.
0: Ryan Hollins
1: Don Collins
2: John Collins
Pick one: 0
Results for Ryan Hollins:

You searched for "Courtney Lee"
3 results found.
0: Courtney Lee
1: Courtney Sims
2: Joe Courtney
Pick one: 0
Results for Courtney Lee:

You searched for "Jarell Martin"
6 results found.
0: Jarell Martin
1: Jamel Artis
2: Bill Martin
3: Caleb Martin
4: Jeff Martin
5: LaRue Martin
Pick one: 0
Results for Jarell Martin:

You searched for "Ray McCallum"
2 results found.
0: Ray McCallum
1: CJ McCollum
Pick one: 0
Results for Ray McCallum:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Russ Smith"
31 results found.
0: Russ Smith
1: Ish Smith
2: Josh Smith
3: Otis Smith
4: Al Smith
5: Bill Smith
6: Chris Smith
7: Chris Smith
8: Craig Smith
9: Deb Smith
10: Don Smith
11: Don Smith
12: Doug Smith
13: Ed Smith
14: Greg Smith
15: Greg Smith
16: J.R. Smith
17: Jason Smith
18: Jim Smith
19: Joe Smith
20: John Smith
21: Ken Smith
22: Leon Smith
23: Mike Smith
24: Pete Smith
25: Phil Smith
26: Randy Smith
27: Sam Smith
28: Sam Smith
29: Tony Smith
30: Rik Smits
Pick one: 0
Results for Russ Smith:

You searched for "Lance Stephenson"
1 result found.
Lance Stephenson
Results for Lance Stephenson:

You searched for "Alex Stepheson"
1 result found.
Alex Stepheson
Results for Alex Stepheson:

You searched for "Jarnell Stokes"
1 result found.
Jarnell Stokes
Results for Jarnell Stokes:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

You searched for "Briante Weber"
1 result found.
Briante Weber
Results for Briante Weber:

You searched for "Elliot Williams"
8 results found.
0: Elliot Williams
1: Alvin Williams
2: Cliff Williams
3: Eric Williams
4: Lou Williams
5: Milt Williams
6: Walt Williams
7: Willie Williams
Pick one: 0
Results for Elliot Williams:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-12-01,30-306,MEM,AWAY,NOP,W (+9),1,42:11,11,22,...,13,6,0,4,3,1,38,34.5,8,Marc Gasol
1,2015-11-13,30-288,MEM,HOME,POR,W (+1),1,40:49,11,18,...,4,5,0,0,0,2,31,27.1,0,Marc Gasol
2,2016-03-11,36-002,MEM,HOME,NOP,W (+7),1,43:36,8,19,...,11,10,2,0,0,5,26,27.0,3,Matt Barnes
3,2016-04-11,25-285,NOP,HOME,CHI,L (-5),1,39:54,9,14,...,5,4,1,1,1,3,29,27.0,-9,James Ennis
4,2016-01-16,30-352,MEM,HOME,NYK,W (+8),1,40:44,15,29,...,8,3,0,3,1,4,37,26.7,11,Marc Gasol

In [40]:


MEM_2017_gamelog = []

for p in MEM_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2017_gamelog.append(player_log)
MEM_2017_gamelog = pd.concat(MEM_2017_gamelog)    
MEM_2017_gamelogs = MEM_2017_gamelog.copy()
MEM_2017_gamelogs['GAME_SCORE'] = MEM_2017_gamelogs['GAME_SCORE'].astype(float)
MEM_2017_games = MEM_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2017_games_csv = MEM_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2017_games.csv', index=False)
MEM_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2017_games.csv')
MEM_2017_games_proc.head()

You searched for "Tony Allen"
26 results found.
0: Tony Allen
1: Bob Allen
2: Randy Allen
3: Ray Allen
4: Tony Fuller
5: Tony Kappen
6: Bill Allen
7: Lavoy Allen
8: Toby Bailey
9: Tony Bradley
10: Tony Brown
11: Tony Dawson
12: Tony Delk
13: Tony Farmer
14: Tony Parker
15: Tony Wroten
16: Tony Zeno
17: Tony Battie
18: Tony Dumas
19: Tony Jaros
20: Tony Lavelli
21: Tony Price
22: Tony Snell
23: Tony White
24: Lonzo Ball
25: Donta Hall
Pick one: 0
Results for Tony Allen:

You searched for "Wade Baldwin"
1 result found.
Wade Baldwin
Results for Wade Baldwin:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Troy Daniels"
4 results found.
0: Troy Daniels
1: Erik Daniels
2: Lloyd Daniels
3: Mel Daniels
Pick one: 0
Results for Troy Daniels:

You searched for "Deyonta Davis"
2 results found.
0: Deyonta Davis
1: Monti Davis
Pick one: 0
Results for Deyonta Davis:

You searched for "Toney Douglas"
4 results found.
0: Toney Douglas
1: John Douglas
2: Leon Douglas
3: Tony Dumas
Pick one: 0
Results for Toney Douglas:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "JaMychal Green"
1 result found.
JaMychal Green
Results for JaMychal Green:

You searched for "Andrew Harrison"
2 results found.
0: Andrew Harrison
1: Aaron Harrison
Pick one: 0
Results for Andrew Harrison:

You searched for "Jarell Martin"
6 results found.
0: Jarell Martin
1: Jamel Artis
2: Bill Martin
3: Caleb Martin
4: Jeff Martin
5: LaRue Martin
Pick one: 0
Results for Jarell Martin:

You searched for "Chandler Parsons"
1 result found.
Chandler Parsons
Results for Chandler Parsons:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Wayne Selden"
5 results found.
0: Wayne Selden
1: Wayne See
2: Wayne Simien
3: Wayne Stevens
4: Dwayne Polee
Pick one: 0
Results for Wayne Selden:

You searched for "Troy Williams"
46 results found.
0: Troy Williams
1: Ray Williams
2: Rob Williams
3: Ron Williams
4: Aaron Williams
5: Art Williams
6: Bob Williams
7: Corey Williams
8: Deron Williams
9: Eric Williams
10: Fly Williams
11: Guy Williams
12: Jay Williams
13: Lou Williams
14: Mo Williams
15: Sly Williams
16: Al Williams
17: Alan Williams
18: Buck Williams
19: C.J. Williams
20: Duck Williams
21: Earl Williams
22: Frank Williams
23: Gene Williams
24: Grant Williams
25: Gus Williams
26: Hank Williams
27: Herb Williams
28: Hot Rod Williams
29: Jason Williams
30: Jerome Williams
31: John Williams
32: Kenny Williams
33: Matt Williams
34: Mike Williams
35: Milt Williams
36: Monty Williams
37: Nate Williams
38: Pete Williams
39: Sam Williams
40: Sam Williams
41: Scott Williams
42: Sean Williams
43: Travis Williams
44: Walt Williams
45: Ward Williams
Pick one: 0
Results for Troy Williams:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-01-30,29-111,MEM,AWAY,PHO,W (+19),1,32:48,12,18,...,6,9,2,0,2,2,38,37.1,29,Mike Conley
1,2017-03-29,29-169,MEM,HOME,IND,W (+13),1,37:57,13,21,...,3,6,4,0,1,1,36,34.2,17,Mike Conley
2,2016-12-21,31-327,MEM,AWAY,DET,W (+12),1,37:01,14,17,...,5,4,2,2,3,3,38,34.0,8,Marc Gasol
3,2017-01-25,31-362,MEM,HOME,TOR,W (+2),1,38:23,14,25,...,7,2,1,2,2,1,42,33.2,9,Marc Gasol
4,2016-11-16,29-036,MEM,AWAY,LAC,W (+4),1,37:49,9,12,...,5,8,3,0,4,2,30,30.1,7,Mike Conley

In [41]:


MEM_2018_gamelog = []

for p in MEM_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2018_gamelog.append(player_log)
MEM_2018_gamelog = pd.concat(MEM_2018_gamelog)    
MEM_2018_gamelogs = MEM_2018_gamelog.copy()
MEM_2018_gamelogs['GAME_SCORE'] = MEM_2018_gamelogs['GAME_SCORE'].astype(float)
MEM_2018_games = MEM_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2018_games_csv = MEM_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2018_games.csv', index=False)
MEM_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2018_games.csv')
MEM_2018_games_proc.head()

You searched for "Dillon Brooks"
2 results found.
0: Dillon Brooks
1: Aaron Brooks
Pick one: 0
Results for Dillon Brooks:

You searched for "MarShon Brooks"
2 results found.
0: MarShon Brooks
1: Aaron Brooks
Pick one: 0
Results for MarShon Brooks:

You searched for "Mario Chalmers"
1 result found.
Mario Chalmers
Results for Mario Chalmers:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Deyonta Davis"
2 results found.
0: Deyonta Davis
1: Monti Davis
Pick one: 0
Results for Deyonta Davis:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Tyreke Evans"
3 results found.
0: Tyreke Evans
1: Jeremy Evans
2: Mike Evans
Pick one: 0
Results for Tyreke Evans:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "JaMychal Green"
1 result found.
JaMychal Green
Results for JaMychal Green:

You searched for "Andrew Harrison"
2 results found.
0: Andrew Harrison
1: Aaron Harrison
Pick one: 0
Results for Andrew Harrison:

You searched for "Myke Henry"
6 results found.
0: Myke Henry
1: Al Henry
2: Bill Henry
3: Carl Henry
4: Mike Glenn
5: Mike Green
Pick one: 0
Results for Myke Henry:

You searched for "Vince Hunter"
3 results found.
0: Vince Hunter
1: Vince Carter
2: Lindsey Hunter
Pick one: 0
Results for Vince Hunter:

You searched for "Brice Johnson"
26 results found.
0: Brice Johnson
1: Eric Johnson
2: Rich Johnson
3: Alize Johnson
4: Arnie Johnson
5: Buck Johnson
6: Nick Johnson
7: Amir Johnson
8: Armon Johnson
9: B.J. Johnson
10: Chris Johnson
11: Chris Johnson
12: Dave Johnson
13: Eddie Johnson
14: Eddie Johnson
15: Ervin Johnson
16: Frank Johnson
17: Joe Johnson
18: Lee Johnson
19: Magic Johnson
20: Mickey Johnson
21: Neil Johnson
22: Ollie Johnson
23: Ron Johnson
24: Steve Johnson
25: Trey Johnson
Pick one: 0
Results for Brice Johnson:

You searched for "Omari Johnson"
18 results found.
0: Omari Johnson
1: Amir Johnson
2: Dakari Johnson
3: Magic Johnson
4: Arnie Johnson
5: Avery Johnson
6: Chris Johnson
7: Chris Johnson
8: Clay Johnson
9: Dave Johnson
10: DeMarco Johnson
11: DerMarr Johnson
12: Eric Johnson
13: Frank Johnson
14: Ivan Johnson
15: Larry Johnson
16: Larry Johnson
17: Ollie Johnson
Pick one: 0
Results for Omari Johnson:

You searched for "Jarell Martin"
6 results found.
0: Jarell Martin
1: Jamel Artis
2: Bill Martin
3: Caleb Martin
4: Jeff Martin
5: LaRue Martin
Pick one: 0
Results for Jarell Martin:

You searched for "Ben McLemore"
3 results found.
0: Ben McLemore
1: Len Elmore
2: Ben Moore
Pick one: 0
Results for Ben McLemore:

You searched for "Chandler Parsons"
1 result found.
Chandler Parsons
Results for Chandler Parsons:

You searched for "Ivan Rabb"
2 results found.
0: Ivan Rabb
1: Allan Ray
Pick one: 0
Results for Ivan Rabb:

You searched for "Xavier Rathan-Mayes"
1 result found.
Xavier Rathan-Mayes
Results for Xavier Rathan-Mayes:

You searched for "Wayne Selden"
5 results found.
0: Wayne Selden
1: Wayne See
2: Wayne Simien
3: Wayne Stevens
4: Dwayne Polee
Pick one: 0
Results for Wayne Selden:

You searched for "Kobi Simmons"
4 results found.
0: Kobi Simmons
1: Bobby Simmons
2: Ben Simmons
3: Connie Simmons
Pick one: 0
Results for Kobi Simmons:

You searched for "Marquis Teague"
1 result found.
Marquis Teague
Results for Marquis Teague:

You searched for "Briante Weber"
1 result found.
Briante Weber
Results for Briante Weber:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-11-15,32-290,MEM,HOME,IND,L (-3),1,39:24,12,24,...,13,5,0,5,2,1,35,31.9,0,Marc Gasol
1,2017-12-02,28-074,MEM,AWAY,CLE,L (-5),1,39:02,10,20,...,7,12,1,0,1,1,31,31.5,-5,Tyreke Evans
2,2017-12-23,28-095,MEM,HOME,LAC,W (+3),1,38:28,10,20,...,7,11,3,0,2,3,30,30.0,3,Tyreke Evans
3,2018-04-11,22-079,MEM,AWAY,OKC,L (-14),1,32:59,14,22,...,7,1,2,0,2,2,36,28.6,0,Dillon Brooks
4,2017-12-27,28-099,MEM,AWAY,LAL,W (+10),1,31:54,8,17,...,7,7,0,0,2,2,32,27.1,22,Tyreke Evans

In [45]:


MEM_2019_gamelog = []

for p in MEM_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2019_gamelog.append(player_log)
MEM_2019_gamelog = pd.concat(MEM_2019_gamelog)    
MEM_2019_gamelogs = MEM_2019_gamelog.copy()
MEM_2019_gamelogs['GAME_SCORE'] = MEM_2019_gamelogs['GAME_SCORE'].astype(float)
MEM_2019_games = MEM_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2019_games_csv = MEM_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2019_games.csv', index=False)
MEM_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2019_games.csv')
MEM_2019_games_proc.head()

You searched for "Kyle Anderson"
16 results found.
0: Kyle Anderson
1: Kim Anderson
2: Ryan Anderson
3: Alan Anderson
4: Dan Anderson
5: Dan Anderson
6: Derek Anderson
7: Eric Anderson
8: Greg Anderson
9: J.J. Anderson
10: James Anderson
11: Kenny Anderson
12: Nick Anderson
13: Ron Anderson
14: Willie Anderson
15: Kyle Alexander
Pick one: 0
Results for Kyle Anderson:

You searched for "Avery Bradley"
4 results found.
0: Avery Bradley
1: Alex Bradley
2: Joe Bradley
3: Tony Bradley
Pick one: 0
Results for Avery Bradley:

You searched for "Dillon Brooks"
2 results found.
0: Dillon Brooks
1: Aaron Brooks
Pick one: 0
Results for Dillon Brooks:

You searched for "MarShon Brooks"
2 results found.
0: MarShon Brooks
1: Aaron Brooks
Pick one: 0
Results for MarShon Brooks:

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "Jevon Carter"
5 results found.
0: Jevon Carter
1: Ron Carter
2: Jake Carter
3: Kevin Porter
4: Kevin Porter
Pick one: 0
Results for Jevon Carter:

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Mike Conley"
17 results found.
0: Mike Conley
1: Gene Conley
2: Mike Tobey
3: Mike Butler
4: Ken Corley
5: Mike Dunleavy
6: Mike Dunleavy
7: Mike Gale
8: Mike Maloy
9: Mike Miller
10: Mike Niles
11: Mike Glenn
12: Mike Lynn
13: Mike Flynn
14: Mike Gibson
15: Mike Lewis
16: Mike Jackson
Pick one: 0
Results for Mike Conley:

You searched for "Tyler Dorsey"
3 results found.
0: Tyler Dorsey
1: Tyler Bey
2: Joey Dorsey
Pick one: 0
Results for Tyler Dorsey:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "JaMychal Green"
1 result found.
JaMychal Green
Results for JaMychal Green:

You searched for "Dusty Hannahs"
1 result found.
Dusty Hannahs
Results for Dusty Hannahs:

You searched for "Andrew Harrison"
2 results found.
0: Andrew Harrison
1: Aaron Harrison
Pick one: 0
Results for Andrew Harrison:

You searched for "Justin Holiday"
1 result found.
Justin Holiday
Results for Justin Holiday:

You searched for "Shelvin Mack"
2 results found.
0: Shelvin Mack
1: Sheldon Mac
Pick one: 0
Results for Shelvin Mack:

You searched for "C.J. Miles"
7 results found.
0: C.J. Miles
1: C.J. Kupec
2: B.J. Tyler
3: C.J. Wilcox
4: T.J. Leaf
5: A.J. Price
6: D.J. White
Pick one: 0
Results for C.J. Miles:

You searched for "Joakim Noah"
1 result found.
Joakim Noah
Results for Joakim Noah:

You searched for "Chandler Parsons"
1 result found.
Chandler Parsons
Results for Chandler Parsons:

You searched for "Ivan Rabb"
2 results found.
0: Ivan Rabb
1: Allan Ray
Pick one: 0
Results for Ivan Rabb:

You searched for "Wayne Selden"
5 results found.
0: Wayne Selden
1: Wayne See
2: Wayne Simien
3: Wayne Stevens
4: Dwayne Polee
Pick one: 0
Results for Wayne Selden:

You searched for "D.J. Stephens"
3 results found.
0: D.J. Stephens
1: Jack Stephens
2: Joe Stephens
Pick one: 0
Results for D.J. Stephens:

You searched for "Garrett Temple"
1 result found.
Garrett Temple
Results for Garrett Temple:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Julian Washburn"
1 result found.
Julian Washburn
Results for Julian Washburn:

You searched for "Yuta Watanabe"
1 result found.
Yuta Watanabe
Results for Yuta Watanabe:

You searched for "Delon Wright"
4 results found.
0: Delon Wright
1: Leroy Wright
2: Dorell Wright
3: Julian Wright
Pick one: 0
Results for Delon Wright:

You searched for "Tyler Zeller"
4 results found.
0: Tyler Zeller
1: Dave Zeller
2: Luke Zeller
3: Tyler Herro
Pick one: 0
Results for Tyler Zeller:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-03-30,26-328,MEM,AWAY,PHO,W (+5),1,34:01,16,28,...,20,5,2,2,3,3,34,33.9,2,Jonas Valančiūnas
1,2019-03-05,31-145,MEM,HOME,POR,W (+9),1,34:41,12,18,...,4,4,1,0,1,4,40,33.0,15,Mike Conley
2,2019-04-05,26-344,MEM,AWAY,DAL,W (+10),1,39:03,10,19,...,10,14,2,0,0,1,26,31.1,20,Delon Wright
3,2018-11-30,31-050,MEM,AWAY,BRK,W (+6),1,45:41,13,25,...,5,10,0,1,3,3,37,29.7,9,Mike Conley
4,2019-03-20,31-160,MEM,HOME,HOU,W (+1),1,42:18,12,23,...,5,8,0,0,1,2,35,29.0,3,Mike Conley

In [48]:


MEM_2020_gamelog = []

for p in MEM_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2020_gamelog.append(player_log)
MEM_2020_gamelog = pd.concat(MEM_2020_gamelog)    
MEM_2020_gamelogs = MEM_2020_gamelog.copy()
MEM_2020_gamelogs['GAME_SCORE'] = MEM_2020_gamelogs['GAME_SCORE'].astype(float)
MEM_2020_games = MEM_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2020_games_csv = MEM_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2020_games.csv', index=False)
MEM_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2020_games.csv')
MEM_2020_games_proc.head()

You searched for "Grayson Allen"
2 results found.
0: Grayson Allen
1: Ray Allen
Pick one: 0
Results for Grayson Allen:

You searched for "Kyle Anderson"
16 results found.
0: Kyle Anderson
1: Kim Anderson
2: Ryan Anderson
3: Alan Anderson
4: Dan Anderson
5: Dan Anderson
6: Derek Anderson
7: Eric Anderson
8: Greg Anderson
9: J.J. Anderson
10: James Anderson
11: Kenny Anderson
12: Nick Anderson
13: Ron Anderson
14: Willie Anderson
15: Kyle Alexander
Pick one: 0
Results for Kyle Anderson:

You searched for "Jordan Bell"
10 results found.
0: Jordan Bell
1: Jordan Hill
2: Jordan Bone
3: Jordan Ford
4: Jordan Loyd
5: Jordan Poole
6: Jordan Sibert
7: Jordan Bowden
8: Ryan Kelly
9: Jordan McRae
Pick one: 0
Results for Jordan Bell:

You searched for "Dillon Brooks"
2 results found.
0: Dillon Brooks
1: Aaron Brooks
Pick one: 0
Results for Dillon Brooks:

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "Brandon Clarke"
1 result found.
Brandon Clarke
Results for Brandon Clarke:

You searched for "Jae Crowder"
4 results found.
0: Jae Crowder
1: Joe Cooper
2: Corey Crowder
3: Joe Strawder
Pick one: 0
Results for Jae Crowder:

You searched for "Gorgui Dieng"
1 result found.
Gorgui Dieng
Results for Gorgui Dieng:

You searched for "Marko Guduric"
2 results found.
0: Marko Guduric
1: Marko Jaric
Pick one: 0
Results for Marko Guduric:

You searched for "Dusty Hannahs"
1 result found.
Dusty Hannahs
Results for Dusty Hannahs:

You searched for "Solomon Hill"
2 results found.
0: Solomon Hill
1: Solomon Alabi
Pick one: 0
Results for Solomon Hill:

You searched for "Josh Jackson"
18 results found.
0: Josh Jackson
1: Jim Jackson
2: Tony Jackson
3: Tony Jackson
4: John Dickson
5: Al Jackson
6: Bobby Jackson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Mike Jackson
16: Phil Jackson
17: Ralph Jackson
Pick one: 0
Results for Josh Jackson:

You searched for "Tyus Jones"
17 results found.
0: Tyus Jones
1: Tre Jones
2: Tyus Edney
3: Bill Jones
4: Earl Jones
5: Fred Jones
6: Jake Jones
7: James Jones
8: K.C. Jones
9: Mark Jones
10: Mark Jones
11: Nick Jones
12: Rich Jones
13: Sam Jones
14: Steve Jones
15: Wali Jones
16: Wil Jones
Pick one: 0
Results for Tyus Jones:

You searched for "John Konchar"
8 results found.
0: John Konchar
1: Jon Koncak
2: John Oldham
3: John Roche
4: John Chaney
5: John Janisch
6: John Dickson
7: John Hargis
Pick one: 0
Results for John Konchar:

You searched for "De'Anthony Melton"
1 result found.
De'Anthony Melton
Results for De'Anthony Melton:

You searched for "Ja Morant"
7 results found.
0: Ja Morant
1: Jack Marin
2: Guy Morgan
3: Juwan Morgan
4: Rex Morgan
5: Jim Nolan
6: Jake Ford
Pick one: 0
Results for Ja Morant:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

You searched for "Jarrod Uthoff"
1 result found.
Jarrod Uthoff
Results for Jarrod Uthoff:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Yuta Watanabe"
1 result found.
Yuta Watanabe
Results for Yuta Watanabe:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-01-12,27-251,MEM,HOME,GSW,W (+20),1,28:42,13,17,...,19,1,1,2,3,0,31,33.3,24,Jonas Valančiūnas
1,2019-11-27,27-205,MEM,HOME,LAC,L (-2),1,33:59,12,17,...,16,3,1,1,2,1,30,31.5,14,Jonas Valančiūnas
2,2020-03-07,27-306,MEM,HOME,ATL,W (+17),1,32:10,10,13,...,17,2,0,3,0,3,27,30.9,14,Jonas Valančiūnas
3,2020-01-04,29-182,MEM,AWAY,LAC,W (+26),1,31:20,9,17,...,8,7,3,3,1,3,27,29.7,39,Jae Crowder
4,2020-08-13,28-099,MEM,HOME,MIL,W (+13),1,32:32,11,17,...,19,12,0,0,3,3,26,29.6,18,Jonas Valančiūnas

In [53]:

MEM_2021_gamelog = []

for p in MEM_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    MEM_2021_gamelog.append(player_log)
MEM_2021_gamelog = pd.concat(MEM_2021_gamelog)    
MEM_2021_gamelogs = MEM_2021_gamelog.copy()
MEM_2021_gamelogs['GAME_SCORE'] = MEM_2021_gamelogs['GAME_SCORE'].astype(float)
MEM_2021_games = MEM_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_2021_games_csv = MEM_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2021_games.csv', index=False)
MEM_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2021_games.csv')
MEM_2021_games_proc.head()

You searched for "Grayson Allen"
2 results found.
0: Grayson Allen
1: Ray Allen
Pick one: 0
Results for Grayson Allen:

You searched for "Kyle Anderson"
16 results found.
0: Kyle Anderson
1: Kim Anderson
2: Ryan Anderson
3: Alan Anderson
4: Dan Anderson
5: Dan Anderson
6: Derek Anderson
7: Eric Anderson
8: Greg Anderson
9: J.J. Anderson
10: James Anderson
11: Kenny Anderson
12: Nick Anderson
13: Ron Anderson
14: Willie Anderson
15: Kyle Alexander
Pick one: 0
Results for Kyle Anderson:

You searched for "Desmond Bane"
2 results found.
0: Desmond Bane
1: Desmond Mason
Pick one: 0
Results for Desmond Bane:

You searched for "Dillon Brooks"
2 results found.
0: Dillon Brooks
1: Aaron Brooks
Pick one: 0
Results for Dillon Brooks:

You searched for "Brandon Clarke"
1 result found.
Brandon Clarke
Results for Brandon Clarke:

You searched for "Gorgui Dieng"
1 result found.
Gorgui Dieng
Results for Gorgui Dieng:

You searched for "Tim Frazier"
4 results found.
0: Tim Frazier
1: Will Frazier
2: Jim Farmer
3: Walt Frazier
Pick one: 0
Results for Tim Frazier:

You searched for "Tyus Jones"
17 results found.
0: Tyus Jones
1: Tre Jones
2: Tyus Edney
3: Bill Jones
4: Earl Jones
5: Fred Jones
6: Jake Jones
7: James Jones
8: K.C. Jones
9: Mark Jones
10: Mark Jones
11: Nick Jones
12: Rich Jones
13: Sam Jones
14: Steve Jones
15: Wali Jones
16: Wil Jones
Pick one: 0
Results for Tyus Jones:

You searched for "John Konchar"
8 results found.
0: John Konchar
1: Jon Koncak
2: John Oldham
3: John Roche
4: John Chaney
5: John Janisch
6: John Dickson
7: John Hargis
Pick one: 0
Results for John Konchar:

You searched for "Sean McDermott"
2 results found.
0: Sean McDermott
1: Doug McDermott
Pick one: 0
Results for Sean McDermott:

You searched for "De'Anthony Melton"
1 result found.
De'Anthony Melton
Results for De'Anthony Melton:

You searched for "Ja Morant"
7 results found.
0: Ja Morant
1: Jack Marin
2: Guy Morgan
3: Juwan Morgan
4: Rex Morgan
5: Jim Nolan
6: Jake Ford
Pick one: 0
Results for Ja Morant:

You searched for "Jontay Porter"
1 result found.
Otto Porter
Results for Otto Porter:

You searched for "Killian Tillie"
1 result found.
Killian Tillie
Results for Killian Tillie:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Justise Winslow"
1 result found.
Justise Winslow
Results for Justise Winslow:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-12-23,21-135,MEM,HOME,SAS,L (-12),1,35:10,18,27,...,2,9,2,1,1,1,44,40.1,10,Ja Morant
1,2021-04-23,21-256,MEM,AWAY,POR,W (+2),1,36:16,11,17,...,5,13,1,0,0,0,33,36.7,4,Ja Morant
2,2021-04-11,28-340,MEM,HOME,IND,L (-7),1,32:14,16,25,...,22,2,0,2,1,2,34,35.3,-12,Jonas Valančiūnas
3,2021-04-19,21-252,MEM,AWAY,DEN,L (-2),1,45:26,13,24,...,8,12,3,1,4,1,36,34.1,9,Ja Morant
4,2020-12-31,27-211,CHI,AWAY,WAS,W (+3),1,30:54,10,14,...,12,3,3,0,0,0,28,31.3,0,Jontay Porter

## combine all seasons

In [55]:

MEM_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2002_games.csv')
MEM_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2003_games.csv')
MEM_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2004_games.csv')
MEM_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2005_games.csv')
MEM_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2006_games.csv')
MEM_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2007_games.csv')
MEM_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2008_games.csv')
MEM_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2009_games.csv')
MEM_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2010_games.csv')
MEM_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2011_games.csv')
MEM_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2012_games.csv')
MEM_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2013_games.csv')
MEM_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2014_games.csv')
MEM_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2015_games.csv')
MEM_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2016_games.csv')
MEM_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2017_games.csv')
MEM_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2018_games.csv')
MEM_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2019_games.csv')
MEM_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2020_games.csv')
MEM_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/MEM/MEM_2021_games.csv')

In [57]:
MEM_season_dfs = [MEM_2002_games_io, MEM_2003_games_io, MEM_2004_games_io, MEM_2005_games_io,
                 MEM_2006_games_io, MEM_2007_games_io, MEM_2008_games_io, MEM_2009_games_io, MEM_2010_games_io, MEM_2011_games_io,
                 MEM_2012_games_io, MEM_2013_games_io, MEM_2014_games_io, MEM_2015_games_io, MEM_2016_games_io, MEM_2017_games_io,
                 MEM_2018_games_io, MEM_2019_games_io, MEM_2020_games_io, MEM_2021_games_io]

In [58]:
MEM_all = pd.concat(MEM_season_dfs)
MEM_all_sorted = MEM_all.sort_values(by=['GAME_SCORE'], ascending=False)
MEM_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-12-23,21-135,MEM,HOME,SAS,L (-12),1,35:10,18,27,...,2,9,2,1,1,1,44,40.1,10,Ja Morant
0,2012-12-04,31-141,MEM,HOME,PHO,W (+10),1,44:16,15,22,...,22,0,1,3,3,2,38,37.3,16,Zach Randolph
0,2017-01-30,29-111,MEM,AWAY,PHO,W (+19),1,32:48,12,18,...,6,9,2,0,2,2,38,37.1,29,Mike Conley
1,2021-04-23,21-256,MEM,AWAY,POR,W (+2),1,36:16,11,17,...,5,13,1,0,0,0,33,36.7,4,Ja Morant
0,2008-01-11,27-189,MEM,AWAY,GSW,L (-12),1,44:43,17,25,...,11,3,1,1,3,2,43,36.0,2,Pau Gasol
2,2021-04-11,28-340,MEM,HOME,IND,L (-7),1,32:14,16,25,...,22,2,0,2,1,2,34,35.3,-12,Jonas Valančiūnas
0,2006-04-07,25-275,MEM,HOME,MIL,W (+10),1,42:55,13,15,...,14,8,2,3,5,3,33,35.0,10,Pau Gasol
0,2015-12-01,30-306,MEM,AWAY,NOP,W (+9),1,42:11,11,22,...,13,6,0,4,3,1,38,34.5,8,Marc Gasol
0,2004-03-29,27-076,MEM,AWAY,ATL,W (+3),1,48:28,10,17,...,11,3,1,1,2,4,38,34.4,10,James Posey
0,2009-11-01,21-361,MEM,AWAY,DEN,L (-10),1,37:47,17,25,...,5,4,1,0,0,2,40,34.2,-4,O.J. Mayo
1,2017-03-29,29-169,MEM,HOME,IND,W (+13),1,37:57,13,21,...,3,6,4,0,1,1,36,34.2,17,Mike Conley
0,2001-11-30,26-012,MEM,HOME,HOU,W (+17),1,37:24,16,28,...,6,11,4,0,3,3,38,34.1,13,Jason Williams
3,2021-04-19,21-252,MEM,AWAY,DEN,L (-2),1,45:26,13,24,...,8,12,3,1,4,1,36,34.1,9,Ja Morant
1,2004-04-07,27-085,MEM,HOME,CLE,W (+18),1,37:49,8,12,...,6,3,3,0,1,3,35,34.1,27,James Posey
1,2014-01-31,27-167,SAC,AWAY,DAL,L (-4),1,35:36,10,16,...,12,6,1,0,3,0,35,34.0,5,Rudy Gay
2,2016-12-21,31-327,MEM,AWAY,DET,W (+12),1,37:01,14,17,...,5,4,2,2,3,3,38,34.0,8,Marc Gasol
0,2019-03-30,26-328,MEM,AWAY,PHO,W (+5),1,34:01,16,28,...,20,5,2,2,3,3,34,33.9,2,Jonas Valančiūnas
1,2009-12-20,28-157,MEM,HOME,DEN,W (+6),1,43:12,13,21,...,24,3,1,1,2,3,32,33.9,-2,Zach Randolph
1,2008-04-06,28-047,MEM,AWAY,MIN,W (+12),1,38:02,12,20,...,10,6,0,2,0,0,34,33.8,18,Mike Miller
0,2004-12-03,24-150,MEM,HOME,PHI,W (+8),1,38:27,12,19,...,15,2,1,3,2,1,34,33.7,7,Pau Gasol
1,2006-03-28,25-265,MEM,HOME,SEA,L (-1),1,45:22,17,28,...,9,3,1,2,4,1,44,33.6,0,Pau Gasol
0,2010-12-29,29-166,MEM,AWAY,SAC,L (-2),1,36:55,15,27,...,17,3,2,0,0,3,35,33.3,-4,Zach Randolph
0,2020-01-12,27-251,MEM,HOME,GSW,W (+20),1,28:42,13,17,...,19,1,1,2,3,0,31,33.3,24,Jonas Valančiūnas
2,2009-12-08,28-145,MEM,HOME,CLE,W (+2),1,47:22,10,19,...,14,2,4,1,1,4,32,33.2,4,Zach Randolph
3,2017-01-25,31-362,MEM,HOME,TOR,W (+2),1,38:23,14,25,...,7,2,1,2,2,1,42,33.2,9,Marc Gasol