In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2013-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_ORL = []

# ORL
while season <= 2021:
    df_ORL = get_roster('ORL', season)
    df_ORL['Season'] = season
    df_ORL['Team'] = 'ORL'
    appended_data_ORL.append(df_ORL)
    season = season + 1
appended_data_ORL = pd.concat(appended_data_ORL)

In [4]:
ORL_df_all = appended_data_ORL.copy()
ORL_df_all_csv = ORL_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_players_all.csv', index=False)
ORL_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_players_all.csv')
ORL_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,9,Tariq Abdul-Wahad,SG,6-6,223,1974-11-03,FR,2,"Michigan, San Jose State",2000,ORL
1,13,John Amaechi,C,6-10,270,1970-11-26,US,1,"Vanderbilt, Penn State",2000,ORL
2,10,Darrell Armstrong,PG,6-0,170,1968-06-22,US,5,Fayetteville State University,2000,ORL
3,31,Chucky Atkins,PG,5-11,160,1974-08-14,US,R,South Florida,2000,ORL
4,11,Earl Boykins,PG,5-5,135,1976-06-02,US,1,Eastern Michigan,2000,ORL

In [5]:
ORL_df_2000 = ORL_df_all[ORL_df_all['Season'] == 2000]
ORL_df_2001 = ORL_df_all[ORL_df_all['Season'] == 2001]
ORL_df_2002 = ORL_df_all[ORL_df_all['Season'] == 2002]
ORL_df_2003 = ORL_df_all[ORL_df_all['Season'] == 2003]
ORL_df_2004 = ORL_df_all[ORL_df_all['Season'] == 2004]
ORL_df_2005 = ORL_df_all[ORL_df_all['Season'] == 2005]
ORL_df_2006 = ORL_df_all[ORL_df_all['Season'] == 2006]
ORL_df_2007 = ORL_df_all[ORL_df_all['Season'] == 2007]
ORL_df_2008 = ORL_df_all[ORL_df_all['Season'] == 2008]
ORL_df_2009 = ORL_df_all[ORL_df_all['Season'] == 2009]
ORL_df_2010 = ORL_df_all[ORL_df_all['Season'] == 2010]
ORL_df_2011 = ORL_df_all[ORL_df_all['Season'] == 2011]
ORL_df_2012 = ORL_df_all[ORL_df_all['Season'] == 2012]
ORL_df_2013 = ORL_df_all[ORL_df_all['Season'] == 2013]
ORL_df_2014 = ORL_df_all[ORL_df_all['Season'] == 2014]
ORL_df_2015 = ORL_df_all[ORL_df_all['Season'] == 2015]
ORL_df_2016 = ORL_df_all[ORL_df_all['Season'] == 2016]
ORL_df_2017 = ORL_df_all[ORL_df_all['Season'] == 2017]
ORL_df_2018 = ORL_df_all[ORL_df_all['Season'] == 2018]
ORL_df_2019 = ORL_df_all[ORL_df_all['Season'] == 2019]
ORL_df_2020 = ORL_df_all[ORL_df_all['Season'] == 2020]
ORL_df_2021 = ORL_df_all[ORL_df_all['Season'] == 2021]

In [6]:
# changing names
#ORL_df_2002.loc[ORL_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#ORL_df_2004.loc[ORL_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [7]:
ORL_df_2000_players = ORL_df_2000['PLAYER'].to_list()
ORL_df_2001_players = ORL_df_2001['PLAYER'].to_list()
ORL_df_2002_players = ORL_df_2002['PLAYER'].to_list()
ORL_df_2003_players = ORL_df_2003['PLAYER'].to_list()
ORL_df_2004_players = ORL_df_2004['PLAYER'].to_list()
ORL_df_2005_players = ORL_df_2005['PLAYER'].to_list()

ORL_df_2006_players = ORL_df_2006['PLAYER'].to_list()
ORL_df_2007_players = ORL_df_2007['PLAYER'].to_list()
ORL_df_2008_players = ORL_df_2008['PLAYER'].to_list()
ORL_df_2009_players = ORL_df_2009['PLAYER'].to_list()
ORL_df_2010_players = ORL_df_2010['PLAYER'].to_list()
ORL_df_2011_players = ORL_df_2011['PLAYER'].to_list()

ORL_df_2012_players = ORL_df_2012['PLAYER'].to_list()
ORL_df_2013_players = ORL_df_2013['PLAYER'].to_list()
ORL_df_2014_players = ORL_df_2014['PLAYER'].to_list()
ORL_df_2015_players = ORL_df_2015['PLAYER'].to_list()
ORL_df_2016_players = ORL_df_2016['PLAYER'].to_list()
ORL_df_2017_players = ORL_df_2017['PLAYER'].to_list()

ORL_df_2018_players = ORL_df_2018['PLAYER'].to_list()
ORL_df_2019_players = ORL_df_2019['PLAYER'].to_list()
ORL_df_2020_players = ORL_df_2020['PLAYER'].to_list()
ORL_df_2021_players = ORL_df_2021['PLAYER'].to_list()

## players to drop

In [52]:
#ORL_df_2000_players.remove("Larry Johnson")
#ORL_df_2005_players.remove("Kiwane Garris")
#ORL_df_2005_players.remove("Mark Jones")
#ORL_df_2013_players.remove("E'Twaun Moore")
#ORL_df_2013_players.remove("Kyle O'Quinn")
#ORL_df_2014_players.remove("Kyle O'Quinn")
#ORL_df_2015_players.remove("Kyle O'Quinn")
#ORL_df_2014_players.remove("E'Twaun Moore")
#ORL_df_2019_players.remove("Mohamed Bamba")
#ORL_df_2020_players.remove("Mohamed Bamba")
#ORL_df_2021_players.remove("Mohamed Bamba")
#ORL_df_2021_players.remove("Wendell Carter")
#ORL_df_2021_players.remove("Robert Franks")
ORL_df_2021_players.remove("Frank Mason")

In [12]:
# removed Kiwane Garris
ORL_2000_gamelog = []


for p in ORL_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2000_gamelog.append(player_log)
ORL_2000_gamelog = pd.concat(ORL_2000_gamelog)    
ORL_2000_gamelogs = ORL_2000_gamelog.copy()
ORL_2000_gamelogs['GAME_SCORE'] = ORL_2000_gamelogs['GAME_SCORE'].astype(float)
ORL_2000_games = ORL_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2000_games_csv = ORL_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2000_games.csv', index=False)
ORL_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2000_games.csv')
ORL_2000_games_proc.head()

You searched for "Tariq Abdul-Wahad"
1 result found.
Tariq Abdul-Wahad
Results for Tariq Abdul-Wahad:

You searched for "John Amaechi"
6 results found.
0: John Amaechi
1: John Janisch
2: John Lambert
3: John Mandic
4: John Wallace
5: John Shumate
Pick one: 0
Results for John Amaechi:

You searched for "Darrell Armstrong"
1 result found.
Darrell Armstrong
Results for Darrell Armstrong:

You searched for "Chucky Atkins"
1 result found.
Chucky Atkins
Results for Chucky Atkins:

You searched for "Earl Boykins"
1 result found.
Earl Boykins
Results for Earl Boykins:

You searched for "Michael Doleac"
8 results found.
0: Michael Doleac
1: Michael Holton
2: Michael Jordan
3: Michael Wiley
4: Michael Ansley
5: Michael Cooper
6: Michael Finley
7: Michael Porter
Pick one: 0
Results for Michael Doleac:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Chris Gatling"
4 results found.
0: Chris Gatling
1: Chris King
2: Chris Mullin
3: Chris Garner
Pick one: 0
Results for Chris Gatling:

You searched for "Matt Harpring"
1 result found.
Matt Harpring
Results for Matt Harpring:

You searched for "Anthony Johnson"
8 results found.
0: Anthony Johnson
1: Andy Johnson
2: Armon Johnson
3: Linton Johnson
4: Anthony Jones
5: Anthony Mason
6: Anthony Roberson
7: Anthony Bonner
Pick one: 0
Results for Anthony Johnson:

You searched for "Corey Maggette"
1 result found.
Corey Maggette
Results for Corey Maggette:

You searched for "Ron Mercer"
15 results found.
0: Ron Mercer
1: Ron Carter
2: Ron Harper
3: Ron Baker
4: Ron Brewer
5: Ron Crevier
6: Ron Dorsey
7: Ron Lee
8: Jon Leuer
9: Ron Moore
10: Ron Perry
11: Ron Reed
12: Gene Berce
13: Thon Maker
14: Roy Marble
Pick one: 0
Results for Ron Mercer:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "Anthony Parker"
10 results found.
0: Anthony Parker
1: Anthony Carter
2: Tony Parker
3: Anthony Peeler
4: Anthony Tucker
5: Anthony Bonner
6: Anthony Miller
7: Anthony Taylor
8: Anthony Avent
9: Anthony Pullard
Pick one: 0
Results for Anthony Parker:

You searched for "Derek Strong"
2 results found.
0: Derek Strong
1: Derek Fisher
Pick one: 0
Results for Derek Strong:

You searched for "Johnny Taylor"
7 results found.
0: Johnny Taylor
1: Johnny Payak
2: Anthony Taylor
3: Jay Taylor
4: Johnny Moore
5: Johnny Orr
6: Johnny Horan
Pick one: 0
Results for Johnny Taylor:

You searched for "Ben Wallace"
4 results found.
0: Ben Wallace
1: Red Wallace
2: John Wallace
3: Ben Warley
Pick one: 0
Results for Ben Wallace:

You searched for "Monty Williams"
26 results found.
0: Monty Williams
1: Corey Williams
2: Kenny Williams
3: Matt Williams
4: Milt Williams
5: Mo Williams
6: Ron Williams
7: Art Williams
8: Bob Williams
9: Fly Williams
10: Gene Williams
11: Grant Williams
12: Guy Williams
13: Hank Williams
14: Jay Williams
15: John Williams
16: Lou Williams
17: Mike Williams
18: Nate Williams
19: Pete Williams
20: Ray Williams
21: Rob Williams
22: Scott Williams
23: Sly Williams
24: Troy Williams
25: Walt Williams
Pick one: 0
Results for Monty Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,1999-11-24,31-155,ORL,HOME,DAL,W (+12),1,36:55,12,20,...,4,14,5,0,5,2,33,34.0,18,Darrell Armstrong
1,2000-02-16,31-239,ORL,HOME,LAC,W (+33),1,31:05,10,12,...,3,9,4,0,3,0,26,29.8,26,Darrell Armstrong
2,1999-11-30,31-161,ORL,HOME,SAC,L (-9),1,34:52,13,22,...,4,12,5,0,6,3,29,27.4,-15,Darrell Armstrong
3,1999-12-23,31-184,ORL,AWAY,CHH,W (+4),1,41:21,9,14,...,2,10,1,0,3,1,28,27.0,24,Darrell Armstrong
4,2000-04-19,31-302,ORL,HOME,TOR,W (+6),1,24:49,7,11,...,3,6,4,0,1,1,22,24.8,15,Darrell Armstrong

In [13]:

ORL_2001_gamelog = []


for p in ORL_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2001_gamelog.append(player_log)
ORL_2001_gamelog = pd.concat(ORL_2001_gamelog)    
ORL_2001_gamelogs = ORL_2001_gamelog.copy()
ORL_2001_gamelogs['GAME_SCORE'] = ORL_2001_gamelogs['GAME_SCORE'].astype(float)
ORL_2001_games = ORL_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2001_games_csv = ORL_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2001_games.csv', index=False)
ORL_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2001_games.csv')
ORL_2001_games_proc.head()

You searched for "Cory Alexander"
7 results found.
0: Cory Alexander
1: Gary Alexander
2: Joe Alexander
3: Cliff Alexander
4: Courtney Alexander
5: Kyle Alexander
6: Victor Alexander
Pick one: 0
Results for Cory Alexander:

You searched for "John Amaechi"
6 results found.
0: John Amaechi
1: John Janisch
2: John Lambert
3: John Mandic
4: John Wallace
5: John Shumate
Pick one: 0
Results for John Amaechi:

You searched for "Darrell Armstrong"
1 result found.
Darrell Armstrong
Results for Darrell Armstrong:

You searched for "Dee Brown"
24 results found.
0: Dee Brown
1: Dee Brown
2: Andre Brown
3: Bob Brown
4: Devin Brown
5: Fred Brown
6: Leon Brown
7: Mike Brown
8: Bruce Brown
9: Damone Brown
10: George Brown
11: John Brown
12: Kwame Brown
13: Lewis Brown
14: Moses Brown
15: P.J. Brown
16: Roger Brown
17: Roger Brown
18: Stan Brown
19: Tierre Brown
20: Tony Brown
21: Troy Brown
22: Jim Browne
23: Dee Gibson
Pick one: 0
Results for Dee Brown:

You searched for "Andrew DeClercq"
1 result found.
Andrew DeClercq
Results for Andrew DeClercq:

You searched for "Michael Doleac"
8 results found.
0: Michael Doleac
1: Michael Holton
2: Michael Jordan
3: Michael Wiley
4: Michael Ansley
5: Michael Cooper
6: Michael Finley
7: Michael Porter
Pick one: 0
Results for Michael Doleac:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Troy Hudson"
3 results found.
0: Troy Hudson
1: Roy Hinson
2: Lou Hudson
Pick one: 0
Results for Troy Hudson:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "Elliot Perry"
1 result found.
Elliot Perry
Results for Elliot Perry:

You searched for "Don Reid"
33 results found.
0: Don Reid
1: Ron Reed
2: Don Dee
3: Don Ford
4: Don Ray
5: Davon Reed
6: Jim Reid
7: Naz Reid
8: Ryan Reid
9: Don Buse
10: Don Grate
11: John Greig
12: Don Kojis
13: Ron Lee
14: Don Martin
15: Don May
16: Don Ohl
17: Hub Reed
18: J.R. Reid
19: John Rudd
20: Don Smith
21: Don Smith
22: Don Boven
23: John Drew
24: Deng Gai
25: Ron Horn
26: Doug Lee
27: Don Otten
28: Ron Riley
29: Rob Rose
30: Bob Rule
31: Doug Moe
32: Ron Moore
Pick one: 0
Results for Don Reid:

You searched for "James Robinson"
13 results found.
0: James Robinson
1: Jamal Robinson
2: James Johnson
3: Nate Robinson
4: Samuel Robinson
5: Chris Robinson
6: David Robinson
7: Jackie Robinson
8: Jerome Robinson
9: Larry Robinson
10: Rumeal Robinson
11: Thomas Robinson
12: Wayne Robinson
Pick one: 0
Results for James Robinson:

You searched for "Monty Williams"
26 results found.
0: Monty Williams
1: Corey Williams
2: Kenny Williams
3: Matt Williams
4: Milt Williams
5: Mo Williams
6: Ron Williams
7: Art Williams
8: Bob Williams
9: Fly Williams
10: Gene Williams
11: Grant Williams
12: Guy Williams
13: Hank Williams
14: Jay Williams
15: John Williams
16: Lou Williams
17: Mike Williams
18: Nate Williams
19: Pete Williams
20: Ray Williams
21: Rob Williams
22: Scott Williams
23: Sly Williams
24: Troy Williams
25: Walt Williams
Pick one: 0
Results for Monty Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-04-13,21-324,ORL,AWAY,WAS,L (-3),1,44:19,19,31,...,8,7,2,4,6,3,49,39.0,3,Tracy McGrady
1,2000-12-02,21-192,ORL,AWAY,NJN,W (+21),1,42:14,18,32,...,10,5,3,3,3,3,40,34.2,27,Tracy McGrady
2,2001-04-04,21-315,ORL,HOME,BOS,W (+7),1,45:03,15,24,...,8,11,2,1,1,1,34,34.2,10,Tracy McGrady
3,2001-03-02,21-282,ORL,HOME,CLE,W (+26),1,31:18,13,22,...,6,5,2,1,1,2,36,33.6,24,Tracy McGrady
4,2001-02-02,32-225,ORL,AWAY,PHI,W (+6),1,49:15,11,21,...,8,13,0,0,0,5,34,33.6,6,Darrell Armstrong

In [14]:

ORL_2002_gamelog = []


for p in ORL_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2002_gamelog.append(player_log)
ORL_2002_gamelog = pd.concat(ORL_2002_gamelog)    
ORL_2002_gamelogs = ORL_2002_gamelog.copy()
ORL_2002_gamelogs['GAME_SCORE'] = ORL_2002_gamelogs['GAME_SCORE'].astype(float)
ORL_2002_games = ORL_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2002_games_csv = ORL_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2002_games.csv', index=False)
ORL_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2002_games.csv')
ORL_2002_games_proc.head()

You searched for "Darrell Armstrong"
1 result found.
Darrell Armstrong
Results for Darrell Armstrong:

You searched for "Dee Brown"
24 results found.
0: Dee Brown
1: Dee Brown
2: Andre Brown
3: Bob Brown
4: Devin Brown
5: Fred Brown
6: Leon Brown
7: Mike Brown
8: Bruce Brown
9: Damone Brown
10: George Brown
11: John Brown
12: Kwame Brown
13: Lewis Brown
14: Moses Brown
15: P.J. Brown
16: Roger Brown
17: Roger Brown
18: Stan Brown
19: Tierre Brown
20: Tony Brown
21: Troy Brown
22: Jim Browne
23: Dee Gibson
Pick one: 0
Results for Dee Brown:

You searched for "Jud Buechler"
1 result found.
Jud Buechler
Results for Jud Buechler:

You searched for "Andrew DeClercq"
1 result found.
Andrew DeClercq
Results for Andrew DeClercq:

You searched for "Patrick Ewing"
4 results found.
0: Patrick Ewing
1: Patrick Ewing
2: Patrick Eddie
3: Patrick McCaw
Pick one: 0
Results for Patrick Ewing:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Horace Grant"
3 results found.
0: Horace Grant
1: Harvey Grant
2: Jerami Grant
Pick one: 0
Results for Horace Grant:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Troy Hudson"
3 results found.
0: Troy Hudson
1: Roy Hinson
2: Lou Hudson
Pick one: 0
Results for Troy Hudson:

You searched for "Steven Hunter"
4 results found.
0: Steven Hunter
1: Steve Colter
2: Steve Hamer
3: Steven Kramer
Pick one: 0
Results for Steven Hunter:

You searched for "Jaren Jackson"
19 results found.
0: Jaren Jackson
1: Jaren Jackson
2: Aaron Jackson
3: Greg Jackson
4: Marc Jackson
5: Mark Jackson
6: Myron Jackson
7: Al Jackson
8: Darnell Jackson
9: Frank Jackson
10: Jim Jackson
11: Josh Jackson
12: Justin Jackson
13: Luke Jackson
14: Luke Jackson
15: Mervin Jackson
16: Mike Jackson
17: Ralph Jackson
18: Wardell Jackson
Pick one: 0
Results for Jaren Jackson:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "Don Reid"
33 results found.
0: Don Reid
1: Ron Reed
2: Don Dee
3: Don Ford
4: Don Ray
5: Davon Reed
6: Jim Reid
7: Naz Reid
8: Ryan Reid
9: Don Buse
10: Don Grate
11: John Greig
12: Don Kojis
13: Ron Lee
14: Don Martin
15: Don May
16: Don Ohl
17: Hub Reed
18: J.R. Reid
19: John Rudd
20: Don Smith
21: Don Smith
22: Don Boven
23: John Drew
24: Deng Gai
25: Ron Horn
26: Doug Lee
27: Don Otten
28: Ron Riley
29: Rob Rose
30: Bob Rule
31: Doug Moe
32: Ron Moore
Pick one: 0
Results for Don Reid:

You searched for "Jeryl Sasser"
2 results found.
0: Jeryl Sasser
1: Jason Sasser
Pick one: 0
Results for Jeryl Sasser:

You searched for "Monty Williams"
26 results found.
0: Monty Williams
1: Corey Williams
2: Kenny Williams
3: Matt Williams
4: Milt Williams
5: Mo Williams
6: Ron Williams
7: Art Williams
8: Bob Williams
9: Fly Williams
10: Gene Williams
11: Grant Williams
12: Guy Williams
13: Hank Williams
14: Jay Williams
15: John Williams
16: Lou Williams
17: Mike Williams
18: Nate Williams
19: Pete Williams
20: Ray Williams
21: Rob Williams
22: Scott Williams
23: Sly Williams
24: Troy Williams
25: Walt Williams
Pick one: 0
Results for Monty Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-03-08,22-288,ORL,HOME,WAS,W (+3),1,41:56,18,29,...,10,3,2,0,3,1,50,38.6,7,Tracy McGrady
1,2001-11-09,22-169,ORL,HOME,SAC,W (+10),1,42:18,14,30,...,13,6,3,2,2,0,44,38.3,10,Tracy McGrady
2,2001-12-15,22-205,ORL,AWAY,POR,L (-11),1,45:05,11,22,...,7,9,2,1,0,2,36,35.3,-14,Tracy McGrady
3,2002-03-19,22-299,ORL,HOME,MIL,W (+10),1,43:56,18,35,...,12,3,3,0,3,2,48,35.2,9,Tracy McGrady
4,2002-03-15,22-295,ORL,HOME,DEN,W (+22),1,39:08,9,17,...,7,9,6,2,2,1,30,35.1,18,Tracy McGrady

In [15]:

    
ORL_2003_gamelog = []



for p in ORL_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2003_gamelog.append(player_log)
ORL_2003_gamelog = pd.concat(ORL_2003_gamelog)    
ORL_2003_gamelogs = ORL_2003_gamelog.copy()
ORL_2003_gamelogs['GAME_SCORE'] = ORL_2003_gamelogs['GAME_SCORE'].astype(float)
ORL_2003_games = ORL_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2003_games_csv = ORL_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2003_games.csv', index=False)
ORL_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2003_games.csv')
ORL_2003_games_proc.head()

You searched for "Darrell Armstrong"
1 result found.
Darrell Armstrong
Results for Darrell Armstrong:

You searched for "Pat Burke"
7 results found.
0: Pat Burke
1: Walt Budko
2: Trey Burke
3: Pat Dunn
4: Pat Durham
5: Pat Frink
6: Walt Kirk
Pick one: 0
Results for Pat Burke:

You searched for "Andrew DeClercq"
1 result found.
Andrew DeClercq
Results for Andrew DeClercq:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Gordan Giriček"
1 result found.
Gordan Giricek
Results for Gordan Giricek:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Horace Grant"
3 results found.
0: Horace Grant
1: Harvey Grant
2: Jerami Grant
Pick one: 0
Results for Horace Grant:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Ryan Humphrey"
1 result found.
Ryan Humphrey
Results for Ryan Humphrey:

You searched for "Steven Hunter"
4 results found.
0: Steven Hunter
1: Steve Colter
2: Steve Hamer
3: Steven Kramer
Pick one: 0
Results for Steven Hunter:

You searched for "Shawn Kemp"
2 results found.
0: Shawn Kemp
1: Shawn Long
Pick one: 0
Results for Shawn Kemp:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Mike Miller"
26 results found.
0: Mike Miller
1: Mike Butler
2: Bill Miller
3: Dick Miller
4: Mike Niles
5: Mike Conley
6: Mike Farmer
7: Mike Gale
8: Mike Hall
9: Mike Harper
10: Mike Maloy
11: Mike McGee
12: Andre Miller
13: Bob Miller
14: Brad Miller
15: Eddie Miller
16: Jay Miller
17: Oliver Miller
18: Walt Miller
19: Mike Taylor
20: Mike Wilks
21: Luke Zeller
22: Mike Glenn
23: Mike Mitchell
24: Mike Lewis
25: Mike O'Neill
Pick one: 0
Results for Mike Miller:

You searched for "Olumide Oyedeji"
1 result found.
Olumide Oyedeji
Results for Olumide Oyedeji:

You searched for "Jeryl Sasser"
2 results found.
0: Jeryl Sasser
1: Jason Sasser
Pick one: 0
Results for Jeryl Sasser:

You searched for "Jacque Vaughn"
1 result found.
Jacque Vaughn
Results for Jacque Vaughn:

You searched for "Chris Whitney"
4 results found.
0: Chris Whitney
1: Kahlil Whitney
2: Chris Anstey
3: Hank Whitney
Pick one: 0
Results for Chris Whitney:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-02-23,23-275,ORL,AWAY,NJN,W (+8),1,45:18,16,27,...,10,13,0,2,4,0,46,42.2,7,Tracy McGrady
1,2003-02-21,23-273,ORL,HOME,CHI,W (+14),1,32:48,15,32,...,5,3,3,1,1,5,52,38.7,20,Tracy McGrady
2,2002-12-25,23-215,ORL,HOME,DET,W (+5),1,43:36,14,26,...,6,1,3,0,1,2,46,36.3,4,Tracy McGrady
3,2002-11-02,23-162,ORL,AWAY,MIL,W (+10),1,38:07,16,29,...,6,7,2,0,4,5,47,36.2,19,Tracy McGrady
4,2003-03-09,23-289,ORL,HOME,DEN,W (+13),1,31:17,13,24,...,2,3,2,0,0,0,43,34.9,29,Tracy McGrady

In [16]:


ORL_2004_gamelog = []



for p in ORL_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2004_gamelog.append(player_log)
ORL_2004_gamelog = pd.concat(ORL_2004_gamelog)    
ORL_2004_gamelogs = ORL_2004_gamelog.copy()
ORL_2004_gamelogs['GAME_SCORE'] = ORL_2004_gamelogs['GAME_SCORE'].astype(float)
ORL_2004_games = ORL_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2004_games_csv = ORL_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2004_games.csv', index=False)
ORL_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2004_games.csv')
ORL_2004_games_proc.head()

You searched for "Robert Archibald"
1 result found.
Robert Archibald
Results for Robert Archibald:

You searched for "Keith Bogans"
5 results found.
0: Keith Bogans
1: Keith Owens
2: Keith Askins
3: Keith Booth
4: Keith Benson
Pick one: 0
Results for Keith Bogans:

You searched for "Andrew DeClercq"
1 result found.
Andrew DeClercq
Results for Andrew DeClercq:

You searched for "Derrick Dial"
4 results found.
0: Derrick Dial
1: Derrick Byars
2: Derrick Rose
3: Derrick White
Pick one: 0
Results for Derrick Dial:

You searched for "Reece Gaines"
1 result found.
Reece Gaines
Results for Reece Gaines:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Gordan Giriček"
1 result found.
Gordan Giricek
Results for Gordan Giricek:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Donnell Harvey"
1 result found.
Donnell Harvey
Results for Donnell Harvey:

You searched for "Juwan Howard"
4 results found.
0: Juwan Howard
1: Brian Howard
2: Josh Howard
3: Juwan Morgan
Pick one: 0
Results for Juwan Howard:

You searched for "Steven Hunter"
4 results found.
0: Steven Hunter
1: Steve Colter
2: Steve Hamer
3: Steven Kramer
Pick one: 0
Results for Steven Hunter:

You searched for "Britton Johnsen"
2 results found.
0: Britton Johnsen
1: Linton Johnson
Pick one: 0
Results for Britton Johnsen:

You searched for "Tyronn Lue"
3 results found.
0: Tyronn Lue
1: Ron Lee
2: Tyrone Hill
Pick one: 0
Results for Tyronn Lue:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Lee Nailon"
2 results found.
0: Lee Nailon
1: Zeke Nnaji
Pick one: 0
Results for Lee Nailon:

You searched for "Zaza Pachulia"
1 result found.
Zaza Pachulia
Results for Zaza Pachulia:

You searched for "Desmond Penigar"
1 result found.
Desmond Penigar
Results for Desmond Penigar:

You searched for "Sean Rooks"
8 results found.
0: Sean Rooks
1: Sean Marks
2: Kevin Brooks
3: Stan Brown
4: Sean Colson
5: Brian Cook
6: Sean Green
7: Jerry Rook
Pick one: 0
Results for Sean Rooks:

You searched for "DeShawn Stevenson"
1 result found.
DeShawn Stevenson
Results for DeShawn Stevenson:

You searched for "Rod Strickland"
4 results found.
0: Rod Strickland
1: Roger Strickland
2: Erick Strickland
3: Mark Strickland
Pick one: 0
Results for Rod Strickland:

You searched for "Shammond Williams"
2 results found.
0: Shammond Williams
1: Shawne Williams
Pick one: 0
Results for Shammond Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-03-10,24-291,ORL,HOME,WAS,W (+9),1,45:50,20,37,...,10,5,1,0,6,1,62,42.8,10,Tracy McGrady
1,2003-11-14,24-174,ORL,AWAY,DEN,L (-5),1,41:34,20,30,...,6,5,2,2,4,2,51,42.7,-1,Tracy McGrady
2,2003-12-25,24-215,ORL,HOME,CLE,W (+12),1,49:32,15,29,...,8,11,3,1,2,1,41,37.7,10,Tracy McGrady
3,2004-01-16,24-237,ORL,HOME,BOS,W (+6),1,44:56,16,31,...,6,6,3,0,2,1,44,35.3,0,Tracy McGrady
4,2004-03-13,24-294,ORL,HOME,SEA,L (-14),1,40:53,12,29,...,6,3,5,1,1,1,40,33.5,-10,Tracy McGrady

In [20]:
# removed mark jones
ORL_2005_gamelog = []



for p in ORL_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2005_gamelog.append(player_log)
ORL_2005_gamelog = pd.concat(ORL_2005_gamelog)    
ORL_2005_gamelogs = ORL_2005_gamelog.copy()
ORL_2005_gamelogs['GAME_SCORE'] = ORL_2005_gamelogs['GAME_SCORE'].astype(float)
ORL_2005_games = ORL_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2005_games_csv = ORL_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2005_games.csv', index=False)
ORL_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2005_games.csv')
ORL_2005_games_proc.head()

You searched for "Stacey Augmon"
1 result found.
Stacey Augmon
Results for Stacey Augmon:

You searched for "Andre Barrett"
5 results found.
0: Andre Barrett
1: Ernie Barrett
2: Mike Barrett
3: RJ Barrett
4: Andre Emmett
Pick one: 0
Results for Andre Barrett:

You searched for "Tony Battie"
8 results found.
0: Tony Battie
1: John Battle
2: Kenny Battle
3: Tony Harris
4: Tony White
5: Tony Allen
6: Tony Bobbitt
7: Tony Bennett
Pick one: 0
Results for Tony Battie:

You searched for "Michael Bradley"
7 results found.
0: Michael Bradley
1: Michael Beasley
2: Michael Ansley
3: Michael Finley
4: Michael Frazier
5: Michael Wiley
6: Michael Bytzura
Pick one: 0
Results for Michael Bradley:

You searched for "Kelvin Cato"
4 results found.
0: Kelvin Cato
1: Calvin Natt
2: Kevin Knox
3: Kevin Love
Pick one: 0
Results for Kelvin Cato:

You searched for "Doug Christie"
2 results found.
0: Doug Christie
1: Doug Kistler
Pick one: 0
Results for Doug Christie:

You searched for "Andrew DeClercq"
1 result found.
Andrew DeClercq
Results for Andrew DeClercq:

You searched for "Steve Francis"
3 results found.
0: Steve Francis
1: Steve Bracey
2: Steve Harris
Pick one: 0
Results for Steve Francis:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Brandon Hunter"
1 result found.
Brandon Hunter
Results for Brandon Hunter:

You searched for "Mario Kasun"
2 results found.
0: Mario Kasun
1: Mario West
Pick one: 0
Results for Mario Kasun:

You searched for "Cuttino Mobley"
1 result found.
Cuttino Mobley
Results for Cuttino Mobley:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "DeShawn Stevenson"
1 result found.
DeShawn Stevenson
Results for DeShawn Stevenson:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-02-15,32-133,ORL,HOME,LAC,W (+5),1,42:17,12,16,...,7,3,2,0,2,4,39,35.2,5,Grant Hill
1,2004-12-10,27-293,ORL,AWAY,GSW,W (+4),1,39:16,11,26,...,8,8,1,0,1,3,36,29.8,2,Steve Francis
2,2005-04-13,23-063,ORL,AWAY,DET,L (-9),1,39:38,10,18,...,5,8,5,0,2,5,30,29.5,-4,Jameer Nelson
3,2005-04-06,28-044,ORL,HOME,CHI,L (-1),1,47:38,9,21,...,6,11,5,0,1,3,28,29.2,10,Steve Francis
4,2004-11-17,27-270,ORL,HOME,UTA,W (+15),1,43:33,11,16,...,9,11,1,0,7,3,33,28.6,21,Steve Francis

In [21]:

ORL_2006_gamelog = []

for p in ORL_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2006_gamelog.append(player_log)
ORL_2006_gamelog = pd.concat(ORL_2006_gamelog)    
ORL_2006_gamelogs = ORL_2006_gamelog.copy()
ORL_2006_gamelogs['GAME_SCORE'] = ORL_2006_gamelogs['GAME_SCORE'].astype(float)
ORL_2006_games = ORL_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2006_games_csv = ORL_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2006_games.csv', index=False)
ORL_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2006_games.csv')
ORL_2006_games_proc.head()

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Carlos Arroyo"
2 results found.
0: Carlos Arroyo
1: Carlos Terry
Pick one: 0
Results for Carlos Arroyo:

You searched for "Stacey Augmon"
1 result found.
Stacey Augmon
Results for Stacey Augmon:

You searched for "Tony Battie"
8 results found.
0: Tony Battie
1: John Battle
2: Kenny Battle
3: Tony Harris
4: Tony White
5: Tony Allen
6: Tony Bobbitt
7: Tony Bennett
Pick one: 0
Results for Tony Battie:

You searched for "Kelvin Cato"
4 results found.
0: Kelvin Cato
1: Calvin Natt
2: Kevin Knox
3: Kevin Love
Pick one: 0
Results for Kelvin Cato:

You searched for "Travis Diener"
4 results found.
0: Travis Diener
1: Travis Wear
2: Travis Hansen
3: Travis Leslie
Pick one: 0
Results for Travis Diener:

You searched for "Keyon Dooling"
1 result found.
Keyon Dooling
Results for Keyon Dooling:

You searched for "Steve Francis"
3 results found.
0: Steve Francis
1: Steve Bracey
2: Steve Harris
Pick one: 0
Results for Steve Francis:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Mario Kasun"
2 results found.
0: Mario Kasun
1: Mario West
Pick one: 0
Results for Mario Kasun:

You searched for "Darko Miličić"
2 results found.
0: Darko Milicic
1: Marko Milic
Pick one: 0
Results for Darko Milicic:

You searched for "Terence Morris"
2 results found.
0: Terence Morris
1: Terence Davis
Pick one: 0
Results for Terence Morris:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "DeShawn Stevenson"
1 result found.
DeShawn Stevenson
Results for DeShawn Stevenson:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-04-15,20-128,ORL,HOME,PHI,W (+5),1,39:45,9,14,...,26,1,2,1,3,4,28,28.4,12,Dwight Howard
1,2006-01-15,23-340,ORL,AWAY,SAC,L (-4),1,35:28,12,19,...,3,9,3,0,2,5,29,27.5,-5,Jameer Nelson
2,2005-12-28,33-084,ORL,HOME,NYK,W (+10),1,35:10,9,15,...,5,4,5,0,1,2,26,27.0,4,Grant Hill
3,2005-12-23,28-305,ORL,HOME,LAL,L (-16),1,41:09,8,14,...,5,9,2,1,2,5,28,26.7,-8,Steve Francis
4,2006-01-27,28-340,ORL,AWAY,NYK,L (-3),1,39:20,12,19,...,2,5,1,0,4,6,36,26.6,1,Steve Francis

In [22]:


ORL_2007_gamelog = []

for p in ORL_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2007_gamelog.append(player_log)
ORL_2007_gamelog = pd.concat(ORL_2007_gamelog)    
ORL_2007_gamelogs = ORL_2007_gamelog.copy()
ORL_2007_gamelogs['GAME_SCORE'] = ORL_2007_gamelogs['GAME_SCORE'].astype(float)
ORL_2007_games = ORL_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2007_games_csv = ORL_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2007_games.csv', index=False)
ORL_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2007_games.csv')
ORL_2007_games_proc.head()

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Carlos Arroyo"
2 results found.
0: Carlos Arroyo
1: Carlos Terry
Pick one: 0
Results for Carlos Arroyo:

You searched for "James Augustine"
1 result found.
James Augustine
Results for James Augustine:

You searched for "Tony Battie"
8 results found.
0: Tony Battie
1: John Battle
2: Kenny Battle
3: Tony Harris
4: Tony White
5: Tony Allen
6: Tony Bobbitt
7: Tony Bennett
Pick one: 0
Results for Tony Battie:

You searched for "Keith Bogans"
5 results found.
0: Keith Bogans
1: Keith Owens
2: Keith Askins
3: Keith Booth
4: Keith Benson
Pick one: 0
Results for Keith Bogans:

You searched for "Travis Diener"
4 results found.
0: Travis Diener
1: Travis Wear
2: Travis Hansen
3: Travis Leslie
Pick one: 0
Results for Travis Diener:

You searched for "Keyon Dooling"
1 result found.
Keyon Dooling
Results for Keyon Dooling:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Darko Miličić"
2 results found.
0: Darko Milicic
1: Marko Milic
Pick one: 0
Results for Darko Milicic:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-04-14,21-127,ORL,AWAY,PHI,W (+17),1,42:34,14,15,...,11,5,3,0,5,3,35,34.5,23,Dwight Howard
1,2007-03-14,21-096,ORL,HOME,UTA,W (+11),1,44:25,13,16,...,15,2,0,2,3,3,31,29.3,10,Dwight Howard
2,2007-02-09,21-063,ORL,HOME,SAS,W (+2),1,43:18,11,14,...,8,3,4,3,4,3,30,28.8,4,Dwight Howard
3,2006-11-20,20-347,ORL,AWAY,MEM,L (-9),1,40:54,9,12,...,23,1,1,1,3,0,24,27.9,-3,Dwight Howard
4,2007-02-07,21-061,ORL,AWAY,TOR,L (-10),1,42:26,13,14,...,9,4,0,2,5,5,32,27.7,-4,Dwight Howard

In [23]:


ORL_2008_gamelog = []

for p in ORL_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2008_gamelog.append(player_log)
ORL_2008_gamelog = pd.concat(ORL_2008_gamelog)    
ORL_2008_gamelogs = ORL_2008_gamelog.copy()
ORL_2008_gamelogs['GAME_SCORE'] = ORL_2008_gamelogs['GAME_SCORE'].astype(float)
ORL_2008_games = ORL_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2008_games_csv = ORL_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2008_games.csv', index=False)
ORL_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2008_games.csv')
ORL_2008_games_proc.head()

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Carlos Arroyo"
2 results found.
0: Carlos Arroyo
1: Carlos Terry
Pick one: 0
Results for Carlos Arroyo:

You searched for "James Augustine"
1 result found.
James Augustine
Results for James Augustine:

You searched for "Keith Bogans"
5 results found.
0: Keith Bogans
1: Keith Owens
2: Keith Askins
3: Keith Booth
4: Keith Benson
Pick one: 0
Results for Keith Bogans:

You searched for "Brian Cook"
9 results found.
0: Brian Cook
1: Quinn Cook
2: Brian Bowen
3: Bert Cook
4: Bobby Cook
5: Darwin Cook
6: Omar Cook
7: Brian Rowsom
8: Brian Shaw
Pick one: 0
Results for Brian Cook:

You searched for "Keyon Dooling"
1 result found.
Keyon Dooling
Results for Keyon Dooling:

You searched for "Maurice Evans"
6 results found.
0: Maurice Evans
1: Mike Evans
2: Maurice King
3: Maurice Lucas
4: Maurice Ager
5: Maurice Baker
Pick one: 0
Results for Maurice Evans:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Pat Garrity"
1 result found.
Pat Garrity
Results for Pat Garrity:

You searched for "Marcin Gortat"
1 result found.
Marcin Gortat
Results for Marcin Gortat:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Rashard Lewis"
1 result found.
Rashard Lewis
Results for Rashard Lewis:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-11-23,21-350,ORL,HOME,CHA,W (+13),1,37:07,11,14,...,17,2,3,4,3,4,34,35.1,15,Dwight Howard
1,2008-02-20,22-074,ORL,AWAY,TOR,L (-17),1,42:21,13,16,...,15,0,1,1,3,4,37,35.0,-22,Dwight Howard
2,2007-12-15,22-007,ORL,HOME,MEM,L (-4),1,41:54,10,11,...,20,3,0,0,1,1,31,33.6,6,Dwight Howard
3,2007-11-14,21-341,ORL,AWAY,CLE,W (+1),1,48:54,11,17,...,16,2,0,4,3,3,35,33.5,-1,Dwight Howard
4,2007-11-28,21-355,ORL,AWAY,SEA,W (+16),1,41:24,12,17,...,16,1,0,5,6,4,39,32.9,18,Dwight Howard

In [24]:


ORL_2009_gamelog = []

for p in ORL_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2009_gamelog.append(player_log)
ORL_2009_gamelog = pd.concat(ORL_2009_gamelog)    
ORL_2009_gamelogs = ORL_2009_gamelog.copy()
ORL_2009_gamelogs['GAME_SCORE'] = ORL_2009_gamelogs['GAME_SCORE'].astype(float)
ORL_2009_games = ORL_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2009_games_csv = ORL_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2009_games.csv', index=False)
ORL_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2009_games.csv')
ORL_2009_games_proc.head()

You searched for "Rafer Alston"
1 result found.
Rafer Alston
Results for Rafer Alston:

You searched for "Tony Battie"
8 results found.
0: Tony Battie
1: John Battle
2: Kenny Battle
3: Tony Harris
4: Tony White
5: Tony Allen
6: Tony Bobbitt
7: Tony Bennett
Pick one: 0
Results for Tony Battie:

You searched for "Keith Bogans"
5 results found.
0: Keith Bogans
1: Keith Owens
2: Keith Askins
3: Keith Booth
4: Keith Benson
Pick one: 0
Results for Keith Bogans:

You searched for "Brian Cook"
9 results found.
0: Brian Cook
1: Quinn Cook
2: Brian Bowen
3: Bert Cook
4: Bobby Cook
5: Darwin Cook
6: Omar Cook
7: Brian Rowsom
8: Brian Shaw
Pick one: 0
Results for Brian Cook:

You searched for "Adonal Foyle"
2 results found.
0: Adonal Foyle
1: Donald Royal
Pick one: 0
Results for Adonal Foyle:

You searched for "Marcin Gortat"
1 result found.
Marcin Gortat
Results for Marcin Gortat:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Anthony Johnson"
8 results found.
0: Anthony Johnson
1: Andy Johnson
2: Armon Johnson
3: Linton Johnson
4: Anthony Jones
5: Anthony Mason
6: Anthony Roberson
7: Anthony Bonner
Pick one: 0
Results for Anthony Johnson:

You searched for "Courtney Lee"
3 results found.
0: Courtney Lee
1: Courtney Sims
2: Joe Courtney
Pick one: 0
Results for Courtney Lee:

You searched for "Rashard Lewis"
1 result found.
Rashard Lewis
Results for Rashard Lewis:

You searched for "Tyronn Lue"
3 results found.
0: Tyronn Lue
1: Ron Lee
2: Tyrone Hill
Pick one: 0
Results for Tyronn Lue:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Jeremy Richardson"
2 results found.
0: Jeremy Richardson
1: Norm Richardson
Pick one: 0
Results for Jeremy Richardson:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2009-02-17,23-071,ORL,HOME,CHA,W (+5),1,46:41,16,23,...,19,0,1,8,5,5,45,41.8,16,Dwight Howard
1,2008-11-08,22-336,ORL,HOME,WAS,W (+25),1,35:01,11,13,...,16,3,0,3,2,2,31,32.9,21,Dwight Howard
2,2008-11-29,22-357,ORL,HOME,IND,W (+14),1,41:57,11,15,...,21,3,0,4,3,2,32,32.9,16,Dwight Howard
3,2009-01-04,23-027,ORL,AWAY,TOR,L (-6),1,36:38,14,19,...,8,2,0,1,1,4,39,32.4,4,Dwight Howard
4,2008-11-12,22-340,ORL,AWAY,OKC,W (+17),1,38:06,12,21,...,19,3,0,10,1,3,30,31.9,16,Dwight Howard

In [25]:

ORL_2010_gamelog = []

for p in ORL_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2010_gamelog.append(player_log)
ORL_2010_gamelog = pd.concat(ORL_2010_gamelog)    
ORL_2010_gamelogs = ORL_2010_gamelog.copy()
ORL_2010_gamelogs['GAME_SCORE'] = ORL_2010_gamelogs['GAME_SCORE'].astype(float)
ORL_2010_games = ORL_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2010_games_csv = ORL_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2010_games.csv', index=False)
ORL_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2010_games.csv')
ORL_2010_games_proc.head()

You searched for "Ryan Anderson"
14 results found.
0: Ryan Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ron Anderson
5: Kyle Anderson
6: Eric Anderson
7: Greg Anderson
8: J.J. Anderson
9: Kenny Anderson
10: Kim Anderson
11: Nick Anderson
12: Alan Henderson
13: Ryan Robertson
Pick one: 0
Results for Ryan Anderson:

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Brandon Bass"
5 results found.
0: Brandon Bass
1: Brandon Paul
2: Brandon Rush
3: Brandon Davies
4: Brandon Roy
Pick one: 0
Results for Brandon Bass:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Marcin Gortat"
1 result found.
Marcin Gortat
Results for Marcin Gortat:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Anthony Johnson"
8 results found.
0: Anthony Johnson
1: Andy Johnson
2: Armon Johnson
3: Linton Johnson
4: Anthony Jones
5: Anthony Mason
6: Anthony Roberson
7: Anthony Bonner
Pick one: 0
Results for Anthony Johnson:

You searched for "Rashard Lewis"
1 result found.
Rashard Lewis
Results for Rashard Lewis:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-02-17,24-071,ORL,HOME,DET,W (+25),1,41:15,11,16,...,17,3,0,7,1,1,33,38.1,20,Dwight Howard
1,2010-02-08,33-013,ORL,HOME,NOH,W (+6),1,38:03,19,27,...,7,2,0,0,2,5,48,36.2,19,Vince Carter
2,2010-01-12,24-035,ORL,AWAY,SAC,W (+21),1,41:27,9,15,...,16,5,3,3,3,3,30,31.5,17,Dwight Howard
3,2010-03-13,24-095,ORL,AWAY,WAS,W (+14),1,37:18,11,13,...,15,5,1,2,4,1,28,29.7,20,Dwight Howard
4,2010-03-26,24-108,ORL,HOME,MIN,W (+9),1,30:47,6,7,...,19,4,3,4,5,4,24,29.6,18,Dwight Howard

In [26]:

ORL_2011_gamelog = []

for p in ORL_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2011_gamelog.append(player_log)
ORL_2011_gamelog = pd.concat(ORL_2011_gamelog)    
ORL_2011_gamelogs = ORL_2011_gamelog.copy()
ORL_2011_gamelogs['GAME_SCORE'] = ORL_2011_gamelogs['GAME_SCORE'].astype(float)
ORL_2011_games = ORL_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2011_games_csv = ORL_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2011_games.csv', index=False)
ORL_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2011_games.csv')
ORL_2011_games_proc.head()

You searched for "Malik Allen"
10 results found.
0: Malik Allen
1: Bill Allen
2: Lavoy Allen
3: Randy Allen
4: Ray Allen
5: Willie Allen
6: Malik Beasley
7: Malik Rose
8: Malik Monk
9: Malik Sealy
Pick one: 0
Results for Malik Allen:

You searched for "Ryan Anderson"
14 results found.
0: Ryan Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ron Anderson
5: Kyle Anderson
6: Eric Anderson
7: Greg Anderson
8: J.J. Anderson
9: Kenny Anderson
10: Kim Anderson
11: Nick Anderson
12: Alan Henderson
13: Ryan Robertson
Pick one: 0
Results for Ryan Anderson:

You searched for "Gilbert Arenas"
1 result found.
Gilbert Arenas
Results for Gilbert Arenas:

You searched for "Brandon Bass"
5 results found.
0: Brandon Bass
1: Brandon Paul
2: Brandon Rush
3: Brandon Davies
4: Brandon Roy
Pick one: 0
Results for Brandon Bass:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Earl Clark"
7 results found.
0: Earl Clark
1: Gary Clark
2: Carlos Clark
3: Ian Clark
4: Keon Clark
5: Earl Evans
6: Earl Lloyd
Pick one: 0
Results for Earl Clark:

You searched for "Chris Duhon"
16 results found.
0: Chris Duhon
1: Chris Quinn
2: Chris Dudley
3: Kris Dunn
4: Chris Johnson
5: Chris Johnson
6: Chris Kaman
7: Chris Mihm
8: Chris Mullin
9: Chris Munk
10: Chris Bosh
11: Chris Ford
12: Chris Jent
13: Chris King
14: Chris Smith
15: Chris Smith
Pick one: 0
Results for Chris Duhon:

You searched for "Marcin Gortat"
1 result found.
Marcin Gortat
Results for Marcin Gortat:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Rashard Lewis"
1 result found.
Rashard Lewis
Results for Rashard Lewis:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Quentin Richardson"
1 result found.
Quentin Richardson
Results for Quentin Richardson:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2011-01-28,25-051,ORL,AWAY,CHI,L (-9),1,42:18,14,20,...,15,2,4,3,3,2,40,40.2,-11,Dwight Howard
1,2011-02-25,25-079,ORL,HOME,OKC,W (+23),1,42:18,16,20,...,15,0,2,6,5,1,40,38.5,23,Dwight Howard
2,2011-01-13,25-036,ORL,AWAY,OKC,L (-1),1,42:50,11,19,...,18,1,0,2,2,4,39,36.0,1,Dwight Howard
3,2010-11-28,29-312,PHO,AWAY,DEN,L (-5),1,36:10,15,24,...,10,3,1,1,1,2,39,34.8,-11,Jason Richardson
4,2011-03-21,25-103,ORL,AWAY,CLE,W (+11),1,41:38,9,11,...,18,4,4,4,4,3,28,34.5,14,Dwight Howard

In [27]:


ORL_2012_gamelog = []

for p in ORL_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2012_gamelog.append(player_log)
ORL_2012_gamelog = pd.concat(ORL_2012_gamelog)    
ORL_2012_gamelogs = ORL_2012_gamelog.copy()
ORL_2012_gamelogs['GAME_SCORE'] = ORL_2012_gamelogs['GAME_SCORE'].astype(float)
ORL_2012_games = ORL_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2012_games_csv = ORL_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2012_games.csv', index=False)
ORL_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2012_games.csv')
ORL_2012_games_proc.head()

You searched for "Ryan Anderson"
14 results found.
0: Ryan Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ron Anderson
5: Kyle Anderson
6: Eric Anderson
7: Greg Anderson
8: J.J. Anderson
9: Kenny Anderson
10: Kim Anderson
11: Nick Anderson
12: Alan Henderson
13: Ryan Robertson
Pick one: 0
Results for Ryan Anderson:

You searched for "Earl Clark"
7 results found.
0: Earl Clark
1: Gary Clark
2: Carlos Clark
3: Ian Clark
4: Keon Clark
5: Earl Evans
6: Earl Lloyd
Pick one: 0
Results for Earl Clark:

You searched for "Glen Davis"
28 results found.
0: Glen Davis
1: Ben Davis
2: Lee Davis
3: Dale Davis
4: Ed Davis
5: Mel Davis
6: Red Davis
7: Ron Davis
8: Tyler Davis
9: Glen Combs
10: Baron Davis
11: Bill Davis
12: Bob Davis
13: Brad Davis
14: Brian Davis
15: Jim Davis
16: Josh Davis
17: Mark Davis
18: Mark Davis
19: Mike Davis
20: Mike Davis
21: Paul Davis
22: Ralph Davis
23: Walt Davis
24: Walter Davis
25: Warren Davis
26: Glen Rice
27: Glen Rice
Pick one: 0
Results for Glen Davis:

You searched for "Chris Duhon"
16 results found.
0: Chris Duhon
1: Chris Quinn
2: Chris Dudley
3: Kris Dunn
4: Chris Johnson
5: Chris Johnson
6: Chris Kaman
7: Chris Mihm
8: Chris Mullin
9: Chris Munk
10: Chris Bosh
11: Chris Ford
12: Chris Jent
13: Chris King
14: Chris Smith
15: Chris Smith
Pick one: 0
Results for Chris Duhon:

You searched for "Justin Harper"
4 results found.
0: Justin Harper
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Justin Harper:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Larry Hughes"
6 results found.
0: Larry Hughes
1: Larry Bunce
2: Larry Fogle
3: Larry Jones
4: Larry Sykes
5: Larry Wright
Pick one: 0
Results for Larry Hughes:

You searched for "DeAndre Liggins"
2 results found.
0: DeAndre Liggins
1: Andrew Wiggins
Pick one: 0
Results for DeAndre Liggins:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Daniel Orton"
3 results found.
0: Daniel Orton
1: Daniel Oturu
2: Daniel Gibson
Pick one: 0
Results for Daniel Orton:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Quentin Richardson"
1 result found.
Quentin Richardson
Results for Quentin Richardson:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

You searched for "Von Wafer"
14 results found.
0: Von Wafer
1: Ron Baker
2: Vin Baker
3: Ron Carter
4: Ron Harper
5: Jon Leuer
6: Thon Maker
7: Bob Naber
8: Ron Watts
9: Don Ford
10: Don Grate
11: Dean Wade
12: John Wall
13: Ron Rowan
Pick one: 0
Results for Von Wafer:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-01-12,26-035,ORL,AWAY,GSW,W (+8),1,43:37,12,21,...,23,3,4,2,3,2,45,41.3,12,Dwight Howard
1,2012-03-11,26-094,ORL,HOME,IND,W (+13),1,36:56,11,14,...,13,5,4,1,3,3,30,32.9,17,Dwight Howard
2,2012-02-08,26-062,ORL,HOME,MIA,W (+13),1,42:37,9,14,...,24,4,3,2,3,3,25,30.6,8,Dwight Howard
3,2012-03-05,26-088,ORL,AWAY,TOR,W (+4),1,36:19,16,20,...,13,0,1,2,2,3,36,28.7,6,Dwight Howard
4,2012-03-01,26-084,ORL,HOME,OKC,L (-3),1,39:14,14,20,...,9,2,2,1,3,2,33,28.4,0,Dwight Howard

In [32]:
# removed E'Twaun Moore
# Kyle O'Quinn
ORL_2013_gamelog = []

for p in ORL_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2013_gamelog.append(player_log)
ORL_2013_gamelog = pd.concat(ORL_2013_gamelog)    
ORL_2013_gamelogs = ORL_2013_gamelog.copy()
ORL_2013_gamelogs['GAME_SCORE'] = ORL_2013_gamelogs['GAME_SCORE'].astype(float)
ORL_2013_games = ORL_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2013_games_csv = ORL_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2013_games.csv', index=False)
ORL_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2013_games.csv')
ORL_2013_games_proc.head()

You searched for "Arron Afflalo"
1 result found.
Arron Afflalo
Results for Arron Afflalo:

You searched for "Gustavo Ayón"
1 result found.
Gustavo Ayon
Results for Gustavo Ayon:

You searched for "Glen Davis"
28 results found.
0: Glen Davis
1: Ben Davis
2: Lee Davis
3: Dale Davis
4: Ed Davis
5: Mel Davis
6: Red Davis
7: Ron Davis
8: Tyler Davis
9: Glen Combs
10: Baron Davis
11: Bill Davis
12: Bob Davis
13: Brad Davis
14: Brian Davis
15: Jim Davis
16: Josh Davis
17: Mark Davis
18: Mark Davis
19: Mike Davis
20: Mike Davis
21: Paul Davis
22: Ralph Davis
23: Walt Davis
24: Walter Davis
25: Warren Davis
26: Glen Rice
27: Glen Rice
Pick one: 0
Results for Glen Davis:

You searched for "Maurice Harkless"
2 results found.
0: Maurice Harkless
1: Maurice McHartley
Pick one: 0
Results for Maurice Harkless:

You searched for "Al Harrington"
5 results found.
0: Al Harrington
1: Adam Harrington
2: Bob Carrington
3: Al Hairston
4: Matt Harpring
Pick one: 0
Results for Al Harrington:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "DeQuan Jones"
6 results found.
0: DeQuan Jones
1: Damian Jones
2: Damon Jones
3: Edgar Jones
4: Kevin Jones
5: Daequan Cook
Pick one: 0
Results for DeQuan Jones:

You searched for "Doron Lamb"
2 results found.
0: Doron Lamb
1: Darvin Ham
Pick one: 0
Results for Doron Lamb:

You searched for "Josh McRoberts"
2 results found.
0: Josh McRoberts
1: Joe Roberts
Pick one: 0
Results for Josh McRoberts:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Andrew Nicholson"
1 result found.
Andrew Nicholson
Results for Andrew Nicholson:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-04-10,20-269,ORL,HOME,MIL,W (+10),1,45:01,13,20,...,19,5,0,0,2,4,30,28.8,12,Tobias Harris
1,2012-12-31,22-068,ORL,HOME,MIA,L (-2),1,46:34,9,17,...,29,2,3,2,0,4,20,28.2,6,Nikola Vučević
2,2013-01-12,27-089,ORL,AWAY,LAC,W (+3),1,40:05,10,19,...,7,7,1,0,1,1,30,28.1,-3,Arron Afflalo
3,2013-03-06,22-133,ORL,AWAY,MIA,L (-1),1,42:08,11,16,...,21,4,1,0,2,6,25,27.5,9,Nikola Vučević
4,2013-03-27,20-255,ORL,AWAY,CHA,L (-6),1,45:07,10,20,...,9,6,1,3,1,3,29,26.8,3,Tobias Harris

In [36]:
# removed etwan moore

ORL_2014_gamelog = []

for p in ORL_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2014_gamelog.append(player_log)
ORL_2014_gamelog = pd.concat(ORL_2014_gamelog)    
ORL_2014_gamelogs = ORL_2014_gamelog.copy()
ORL_2014_gamelogs['GAME_SCORE'] = ORL_2014_gamelogs['GAME_SCORE'].astype(float)
ORL_2014_games = ORL_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2014_games_csv = ORL_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2014_games.csv', index=False)
ORL_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2014_games.csv')
ORL_2014_games_proc.head()

You searched for "Arron Afflalo"
1 result found.
Arron Afflalo
Results for Arron Afflalo:

You searched for "Glen Davis"
28 results found.
0: Glen Davis
1: Ben Davis
2: Lee Davis
3: Dale Davis
4: Ed Davis
5: Mel Davis
6: Red Davis
7: Ron Davis
8: Tyler Davis
9: Glen Combs
10: Baron Davis
11: Bill Davis
12: Bob Davis
13: Brad Davis
14: Brian Davis
15: Jim Davis
16: Josh Davis
17: Mark Davis
18: Mark Davis
19: Mike Davis
20: Mike Davis
21: Paul Davis
22: Ralph Davis
23: Walt Davis
24: Walter Davis
25: Warren Davis
26: Glen Rice
27: Glen Rice
Pick one: 0
Results for Glen Davis:

You searched for "Dewayne Dedmon"
1 result found.
Dewayne Dedmon
Results for Dewayne Dedmon:

You searched for "Maurice Harkless"
2 results found.
0: Maurice Harkless
1: Maurice McHartley
Pick one: 0
Results for Maurice Harkless:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "Solomon Jones"
3 results found.
0: Solomon Jones
1: Damon Jones
2: Shelton Jones
Pick one: 0
Results for Solomon Jones:

You searched for "Doron Lamb"
2 results found.
0: Doron Lamb
1: Darvin Ham
Pick one: 0
Results for Doron Lamb:

You searched for "Jason Maxiell"
1 result found.
Jason Maxiell
Results for Jason Maxiell:

You searched for "Jameer Nelson"
2 results found.
0: Jameer Nelson
1: Jasper Wilson
Pick one: 0
Results for Jameer Nelson:

You searched for "Andrew Nicholson"
1 result found.
Andrew Nicholson
Results for Andrew Nicholson:

You searched for "Victor Oladipo"
1 result found.
Victor Oladipo
Results for Victor Oladipo:

You searched for "Ronnie Price"
5 results found.
0: Ronnie Price
1: Donnie Boyce
2: Ronnie Brewer
3: Tony Price
4: Connie Rea
Pick one: 0
Results for Ronnie Price:

You searched for "Adonis Thomas"
2 results found.
0: Adonis Thomas
1: Willis Thomas
Pick one: 0
Results for Adonis Thomas:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-11-13,28-029,ORL,HOME,MIL,W (+3),1,40:08,11,15,...,8,6,2,0,4,2,36,34.1,4,Arron Afflalo
1,2013-12-03,28-049,ORL,AWAY,PHI,L (-1),1,52:25,14,27,...,6,5,2,0,3,5,43,32.0,5,Arron Afflalo
2,2014-02-21,21-293,ORL,HOME,NYK,W (+8),1,49:16,11,23,...,9,14,2,0,3,1,30,30.6,20,Victor Oladipo
3,2013-11-06,23-013,ORL,HOME,LAC,W (+8),1,38:26,11,19,...,21,3,1,1,4,3,30,28.0,6,Nikola Vučević
4,2013-12-13,21-223,ORL,HOME,CLE,L (-9),1,36:48,9,13,...,5,4,4,3,2,5,26,27.3,1,Victor Oladipo

In [37]:


ORL_2015_gamelog = []

for p in ORL_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2015_gamelog.append(player_log)
ORL_2015_gamelog = pd.concat(ORL_2015_gamelog)    
ORL_2015_gamelogs = ORL_2015_gamelog.copy()
ORL_2015_gamelogs['GAME_SCORE'] = ORL_2015_gamelogs['GAME_SCORE'].astype(float)
ORL_2015_games = ORL_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2015_games_csv = ORL_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2015_games.csv', index=False)
ORL_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2015_games.csv')
ORL_2015_games_proc.head()

You searched for "Dewayne Dedmon"
1 result found.
Dewayne Dedmon
Results for Dewayne Dedmon:

You searched for "Evan Fournier"
2 results found.
0: Evan Fournier
1: Evan Turner
Pick one: 0
Results for Evan Fournier:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Aaron Gordon"
6 results found.
0: Aaron Gordon
1: Ben Gordon
2: Drew Gordon
3: Eric Gordon
4: Paul Gordon
5: Aaron Gray
Pick one: 0
Results for Aaron Gordon:

You searched for "Ben Gordon"
9 results found.
0: Ben Gordon
1: Drew Gordon
2: Aaron Gordon
3: Eric Gordon
4: Paul Gordon
5: Ken Green
6: Ed Horton
7: Ken Norman
8: Ben Moore
Pick one: 0
Results for Ben Gordon:

You searched for "Willie Green"
14 results found.
0: Willie Green
1: Willie Reed
2: Willie Allen
3: Willis Reed
4: Willie Warren
5: Willie Burton
6: Mike Green
7: Tommie Green
8: Willie Jones
9: Willie Porter
10: Willie Wise
11: Willie Long
12: Willie Rogers
13: Willie White
Pick one: 0
Results for Willie Green:

You searched for "Maurice Harkless"
2 results found.
0: Maurice Harkless
1: Maurice McHartley
Pick one: 0
Results for Maurice Harkless:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "Devyn Marble"
3 results found.
0: Devyn Marble
1: Kevin Gamble
2: Roy Marble
Pick one: 0
Results for Devyn Marble:

You searched for "Andrew Nicholson"
1 result found.
Andrew Nicholson
Results for Andrew Nicholson:

You searched for "Victor Oladipo"
1 result found.
Victor Oladipo
Results for Victor Oladipo:

You searched for "Elfrid Payton"
1 result found.
Elfrid Payton
Results for Elfrid Payton:

You searched for "Luke Ridnour"
1 result found.
Luke Ridnour
Results for Luke Ridnour:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-04-03,24-161,ORL,AWAY,MIN,W (+13),1,40:08,18,25,...,17,2,1,0,2,2,37,33.0,14,Nikola Vučević
1,2015-01-23,24-091,ORL,AWAY,NYK,L (-7),1,37:46,16,22,...,18,3,1,1,2,3,34,32.6,-1,Nikola Vučević
2,2015-03-20,21-026,ORL,HOME,POR,W (+7),1,36:35,10,13,...,10,10,4,0,1,2,22,31.1,2,Elfrid Payton
3,2014-11-22,24-029,ORL,HOME,MIA,L (-7),1,37:13,12,24,...,17,1,0,1,0,2,33,30.3,-8,Nikola Vučević
4,2015-03-06,22-306,ORL,HOME,SAC,W (+5),1,40:09,14,24,...,3,10,5,0,3,2,32,30.3,13,Victor Oladipo

In [38]:
# removed kyle o'qiuinn

ORL_2016_gamelog = []

for p in ORL_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2016_gamelog.append(player_log)
ORL_2016_gamelog = pd.concat(ORL_2016_gamelog)    
ORL_2016_gamelogs = ORL_2016_gamelog.copy()
ORL_2016_gamelogs['GAME_SCORE'] = ORL_2016_gamelogs['GAME_SCORE'].astype(float)
ORL_2016_games = ORL_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2016_games_csv = ORL_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2016_games.csv', index=False)
ORL_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2016_games.csv')
ORL_2016_games_proc.head()

You searched for "Keith Appling"
2 results found.
0: Keith Appling
1: Keith Askins
Pick one: 0
Results for Keith Appling:

You searched for "Dewayne Dedmon"
1 result found.
Dewayne Dedmon
Results for Dewayne Dedmon:

You searched for "Evan Fournier"
2 results found.
0: Evan Fournier
1: Evan Turner
Pick one: 0
Results for Evan Fournier:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Aaron Gordon"
6 results found.
0: Aaron Gordon
1: Ben Gordon
2: Drew Gordon
3: Eric Gordon
4: Paul Gordon
5: Aaron Gray
Pick one: 0
Results for Aaron Gordon:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "Mario Hezonja"
1 result found.
Mario Hezonja
Results for Mario Hezonja:

You searched for "Ersan İlyasova"
1 result found.
Ersan Ilyasova
Results for Ersan Ilyasova:

You searched for "Brandon Jennings"
1 result found.
Brandon Jennings
Results for Brandon Jennings:

You searched for "Devyn Marble"
3 results found.
0: Devyn Marble
1: Kevin Gamble
2: Roy Marble
Pick one: 0
Results for Devyn Marble:

You searched for "Shabazz Napier"
1 result found.
Shabazz Napier
Results for Shabazz Napier:

You searched for "Andrew Nicholson"
1 result found.
Andrew Nicholson
Results for Andrew Nicholson:

You searched for "Victor Oladipo"
1 result found.
Victor Oladipo
Results for Victor Oladipo:

You searched for "Elfrid Payton"
1 result found.
Elfrid Payton
Results for Elfrid Payton:

You searched for "Jason Smith"
27 results found.
0: Jason Smith
1: Jalen Smith
2: Don Smith
3: Don Smith
4: Joe Smith
5: John Smith
6: Josh Smith
7: Leon Smith
8: Aaron Nesmith
9: Jason Hart
10: Jason Kidd
11: Al Smith
12: Ish Smith
13: J.R. Smith
14: Jabari Smith
15: Jerry Smith
16: Jim Smith
17: Ken Smith
18: Larry Smith
19: Nolan Smith
20: Randy Smith
21: Russ Smith
22: Sam Smith
23: Sam Smith
24: Theron Smith
25: Tony Smith
26: Joe Smyth
Pick one: 0
Results for Jason Smith:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

You searched for "C.J. Watson"
6 results found.
0: C.J. Watson
1: D.J. Wilson
2: T.J. Warren
3: Earl Watson
4: Paul Watson
5: C.J. Wilcox
Pick one: 0
Results for C.J. Watson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-03-18,23-319,ORL,HOME,CLE,L (-6),1,39:19,16,22,...,5,3,3,2,3,3,45,39.8,-1,Victor Oladipo
1,2016-02-03,23-275,ORL,AWAY,OKC,L (-3),1,40:48,13,20,...,7,4,1,1,0,4,37,33.6,-4,Victor Oladipo
2,2016-02-23,25-122,ORL,AWAY,PHI,W (+9),1,36:39,13,21,...,9,4,0,1,1,1,35,31.5,10,Nikola Vučević
3,2015-12-18,23-156,ORL,HOME,POR,W (+8),1,36:26,9,13,...,12,2,3,0,0,0,25,28.3,9,Tobias Harris
4,2016-02-08,25-107,ORL,AWAY,ATL,W (+7),1,43:22,11,16,...,13,6,0,1,1,4,28,28.2,2,Nikola Vučević

In [39]:


ORL_2017_gamelog = []

for p in ORL_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2017_gamelog.append(player_log)
ORL_2017_gamelog = pd.concat(ORL_2017_gamelog)    
ORL_2017_gamelogs = ORL_2017_gamelog.copy()
ORL_2017_gamelogs['GAME_SCORE'] = ORL_2017_gamelogs['GAME_SCORE'].astype(float)
ORL_2017_games = ORL_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2017_games_csv = ORL_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2017_games.csv', index=False)
ORL_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2017_games.csv')
ORL_2017_games_proc.head()

You searched for "D.J. Augustin"
1 result found.
D.J. Augustin
Results for D.J. Augustin:

You searched for "Bismack Biyombo"
1 result found.
Bismack Biyombo
Results for Bismack Biyombo:

You searched for "Anthony Brown"
8 results found.
0: Anthony Brown
1: Anthony Bowie
2: Tony Brown
3: Anthony Bonner
4: Troy Brown
5: Anthony Cook
6: Anthony Mason
7: Anthony Morrow
Pick one: 0
Results for Anthony Brown:

You searched for "Evan Fournier"
2 results found.
0: Evan Fournier
1: Evan Turner
Pick one: 0
Results for Evan Fournier:

You searched for "Patricio Garino"
1 result found.
Patricio Garino
Results for Patricio Garino:

You searched for "Marcus Georges-Hunt"
1 result found.
Marcus Georges-Hunt
Results for Marcus Georges-Hunt:

You searched for "Aaron Gordon"
6 results found.
0: Aaron Gordon
1: Ben Gordon
2: Drew Gordon
3: Eric Gordon
4: Paul Gordon
5: Aaron Gray
Pick one: 0
Results for Aaron Gordon:

You searched for "Jeff Green"
21 results found.
0: Jeff Green
1: Josh Green
2: Jeff Adrien
3: Jeff Grayer
4: Ken Green
5: Sean Green
6: Jeff Ayres
7: Jeff Cross
8: A.C. Green
9: Devin Green
10: Kenny Green
11: Mike Green
12: Si Green
13: Steve Green
14: Jeff Lebo
15: Jeff Martin
16: Jeff Turner
17: Jeff Webb
18: Jeff Foote
19: Jeff Slade
20: Jeff Teague
Pick one: 0
Results for Jeff Green:

You searched for "Mario Hezonja"
1 result found.
Mario Hezonja
Results for Mario Hezonja:

You searched for "Serge Ibaka"
1 result found.
Serge Ibaka
Results for Serge Ibaka:

You searched for "Jodie Meeks"
1 result found.
Jodie Meeks
Results for Jodie Meeks:

You searched for "Arinze Onuaku"
1 result found.
Arinze Onuaku
Results for Arinze Onuaku:

You searched for "Elfrid Payton"
1 result found.
Elfrid Payton
Results for Elfrid Payton:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Damjan Rudež"
1 result found.
Damjan Rudez
Results for Damjan Rudez:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

You searched for "C.J. Watson"
6 results found.
0: C.J. Watson
1: D.J. Wilson
2: T.J. Warren
3: Earl Watson
4: Paul Watson
5: C.J. Wilcox
Pick one: 0
Results for C.J. Watson:

You searched for "C.J. Wilcox"
5 results found.
0: C.J. Wilcox
1: D.J. Wilson
2: C.J. Miles
3: C.J. Watson
4: Chris Wilcox
Pick one: 0
Results for C.J. Wilcox:

You searched for "Stephen Zimmerman"
1 result found.
Stephen Zimmerman
Results for Stephen Zimmerman:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-03-08,23-014,ORL,HOME,CHI,W (+7),1,35:41,8,12,...,14,14,2,2,2,0,22,34.2,12,Elfrid Payton
1,2017-01-13,26-081,ORL,AWAY,POR,W (+6),1,31:47,13,18,...,10,4,1,2,1,1,30,29.8,12,Nikola Vučević
2,2017-01-14,22-327,ORL,AWAY,UTA,L (-7),1,39:21,10,17,...,9,9,2,1,1,4,28,28.8,7,Elfrid Payton
3,2017-04-12,21-208,ORL,HOME,DET,W (+4),1,34:54,11,20,...,12,0,1,2,0,2,32,28.4,17,Aaron Gordon
4,2017-03-31,21-196,ORL,AWAY,BOS,L (-1),1,36:21,11,24,...,16,1,1,2,0,2,32,28.3,0,Aaron Gordon

In [40]:

ORL_2018_gamelog = []

for p in ORL_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2018_gamelog.append(player_log)
ORL_2018_gamelog = pd.concat(ORL_2018_gamelog)    
ORL_2018_gamelogs = ORL_2018_gamelog.copy()
ORL_2018_gamelogs['GAME_SCORE'] = ORL_2018_gamelogs['GAME_SCORE'].astype(float)
ORL_2018_games = ORL_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2018_games_csv = ORL_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2018_games.csv', index=False)
ORL_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2018_games.csv')
ORL_2018_games_proc.head()

You searched for "Arron Afflalo"
1 result found.
Arron Afflalo
Results for Arron Afflalo:

You searched for "Jamel Artis"
5 results found.
0: Jamel Artis
1: Jalen Harris
2: James Ennis
3: Jarell Martin
4: James Hardy
Pick one: 0
Results for Jamel Artis:

You searched for "D.J. Augustin"
1 result found.
D.J. Augustin
Results for D.J. Augustin:

You searched for "Khem Birch"
1 result found.
Khem Birch
Results for Khem Birch:

You searched for "Bismack Biyombo"
1 result found.
Bismack Biyombo
Results for Bismack Biyombo:

You searched for "Evan Fournier"
2 results found.
0: Evan Fournier
1: Evan Turner
Pick one: 0
Results for Evan Fournier:

You searched for "Aaron Gordon"
6 results found.
0: Aaron Gordon
1: Ben Gordon
2: Drew Gordon
3: Eric Gordon
4: Paul Gordon
5: Aaron Gray
Pick one: 0
Results for Aaron Gordon:

You searched for "Mario Hezonja"
1 result found.
Mario Hezonja
Results for Mario Hezonja:

You searched for "Jonathan Isaac"
2 results found.
0: Jonathan Isaac
1: Jonathan Gibson
Pick one: 0
Results for Jonathan Isaac:

You searched for "Wesley Iwundu"
1 result found.
Wesley Iwundu
Results for Wesley Iwundu:

You searched for "Shelvin Mack"
2 results found.
0: Shelvin Mack
1: Sheldon Mac
Pick one: 0
Results for Shelvin Mack:

You searched for "Adreian Payne"
1 result found.
Adreian Payne
Results for Adreian Payne:

You searched for "Elfrid Payton"
1 result found.
Elfrid Payton
Results for Elfrid Payton:

You searched for "Rodney Purvis"
2 results found.
0: Rodney Purvis
1: Rodney Buford
Pick one: 0
Results for Rodney Purvis:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Jonathon Simmons"
1 result found.
Jonathon Simmons
Results for Jonathon Simmons:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Rashad Vaughn"
3 results found.
0: Rashad Vaughn
1: David Vaughn
2: David Vaughn
Pick one: 0
Results for Rashad Vaughn:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-11-29,22-074,ORL,HOME,OKC,W (+13),1,43:57,13,23,...,15,4,4,1,1,1,40,38.5,17,Aaron Gordon
1,2017-10-24,22-038,ORL,HOME,BRK,W (+4),1,36:38,14,18,...,14,2,0,0,1,3,41,38.2,7,Aaron Gordon
2,2017-12-09,27-046,ORL,AWAY,ATL,L (-7),1,37:34,13,18,...,13,10,1,1,2,3,31,33.8,-1,Nikola Vučević
3,2017-12-30,22-105,ORL,HOME,MIA,L (-6),1,35:51,14,22,...,7,1,0,2,0,2,39,32.6,-3,Aaron Gordon
4,2017-12-23,23-304,ORL,AWAY,WAS,L (-27),1,35:34,11,16,...,5,10,4,1,3,3,30,32.2,-11,Elfrid Payton

In [43]:
# removed Mohamed Bamba
ORL_2019_gamelog = []

for p in ORL_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2019_gamelog.append(player_log)
ORL_2019_gamelog = pd.concat(ORL_2019_gamelog)    
ORL_2019_gamelogs = ORL_2019_gamelog.copy()
ORL_2019_gamelogs['GAME_SCORE'] = ORL_2019_gamelogs['GAME_SCORE'].astype(float)
ORL_2019_games = ORL_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2019_games_csv = ORL_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2019_games.csv', index=False)
ORL_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2019_games.csv')
ORL_2019_games_proc.head()

You searched for "D.J. Augustin"
1 result found.
D.J. Augustin
Results for D.J. Augustin:

You searched for "Khem Birch"
1 result found.
Khem Birch
Results for Khem Birch:

You searched for "Isaiah Briscoe"
2 results found.
0: Isaiah Briscoe
1: Isaiah Rider
Pick one: 0
Results for Isaiah Briscoe:

You searched for "Michael Carter-Williams"
1 result found.
Michael Carter-Williams
Results for Michael Carter-Williams:

You searched for "Troy Caupain"
1 result found.
Troy Caupain
Results for Troy Caupain:

You searched for "Evan Fournier"
2 results found.
0: Evan Fournier
1: Evan Turner
Pick one: 0
Results for Evan Fournier:

You searched for "Melvin Frazier"
1 result found.
Melvin Frazier
Results for Melvin Frazier:

You searched for "Aaron Gordon"
6 results found.
0: Aaron Gordon
1: Ben Gordon
2: Drew Gordon
3: Eric Gordon
4: Paul Gordon
5: Aaron Gray
Pick one: 0
Results for Aaron Gordon:

You searched for "Jerian Grant"
3 results found.
0: Jerian Grant
1: Brian Grant
2: Jerami Grant
Pick one: 0
Results for Jerian Grant:

You searched for "Jonathan Isaac"
2 results found.
0: Jonathan Isaac
1: Jonathan Gibson
Pick one: 0
Results for Jonathan Isaac:

You searched for "Wesley Iwundu"
1 result found.
Wesley Iwundu
Results for Wesley Iwundu:

You searched for "Amile Jefferson"
2 results found.
0: Amile Jefferson
1: Al Jefferson
Pick one: 0
Results for Amile Jefferson:

You searched for "Jarell Martin"
6 results found.
0: Jarell Martin
1: Jamel Artis
2: Bill Martin
3: Caleb Martin
4: Jeff Martin
5: LaRue Martin
Pick one: 0
Results for Jarell Martin:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Jonathon Simmons"
1 result found.
Jonathon Simmons
Results for Jonathon Simmons:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-12-28,28-065,ORL,HOME,TOR,W (+29),1,33:22,12,17,...,19,8,2,1,1,1,30,36.3,33,Nikola Vučević
1,2018-10-20,27-361,ORL,AWAY,PHI,L (-1),1,37:35,10,15,...,13,12,2,0,2,2,27,33.6,12,Nikola Vučević
2,2018-11-25,28-032,ORL,AWAY,LAL,W (+4),1,35:51,10,20,...,15,7,2,3,3,2,31,31.5,16,Nikola Vučević
3,2019-03-03,28-130,ORL,AWAY,CLE,L (-14),1,35:45,13,16,...,13,6,2,2,3,2,28,30.9,3,Nikola Vučević
4,2018-11-18,28-025,ORL,HOME,NYK,W (+14),1,31:37,10,15,...,10,9,0,2,3,2,28,30.0,14,Nikola Vučević

In [45]:

ORL_2020_gamelog = []

for p in ORL_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2020_gamelog.append(player_log)
ORL_2020_gamelog = pd.concat(ORL_2020_gamelog)    
ORL_2020_gamelogs = ORL_2020_gamelog.copy()
ORL_2020_gamelogs['GAME_SCORE'] = ORL_2020_gamelogs['GAME_SCORE'].astype(float)
ORL_2020_games = ORL_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2020_games_csv = ORL_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2020_games.csv', index=False)
ORL_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2020_games.csv')
ORL_2020_games_proc.head()

You searched for "Al-Farouq Aminu"
1 result found.
Al-Farouq Aminu
Results for Al-Farouq Aminu:

You searched for "D.J. Augustin"
1 result found.
D.J. Augustin
Results for D.J. Augustin:

You searched for "Khem Birch"
1 result found.
Khem Birch
Results for Khem Birch:

You searched for "Michael Carter-Williams"
1 result found.
Michael Carter-Williams
Results for Michael Carter-Williams:

You searched for "Gary Clark"
15 results found.
0: Gary Clark
1: Earl Clark
2: Ian Clark
3: Gary Alcorn
4: Cory Carr
5: Carlos Clark
6: Keon Clark
7: Coty Clarke
8: Gary Grant
9: Gary Gray
10: Gar Heard
11: Gary Neal
12: Jay Carty
13: Gary Keller
14: Gary Zeller
Pick one: 0
Results for Gary Clark:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Evan Fournier"
2 results found.
0: Evan Fournier
1: Evan Turner
Pick one: 0
Results for Evan Fournier:

You searched for "Melvin Frazier"
1 result found.
Melvin Frazier
Results for Melvin Frazier:

You searched for "Markelle Fultz"
1 result found.
Markelle Fultz
Results for Markelle Fultz:

You searched for "Aaron Gordon"
6 results found.
0: Aaron Gordon
1: Ben Gordon
2: Drew Gordon
3: Eric Gordon
4: Paul Gordon
5: Aaron Gray
Pick one: 0
Results for Aaron Gordon:

You searched for "Jonathan Isaac"
2 results found.
0: Jonathan Isaac
1: Jonathan Gibson
Pick one: 0
Results for Jonathan Isaac:

You searched for "Wesley Iwundu"
1 result found.
Wesley Iwundu
Results for Wesley Iwundu:

You searched for "Amile Jefferson"
2 results found.
0: Amile Jefferson
1: Al Jefferson
Pick one: 0
Results for Amile Jefferson:

You searched for "B.J. Johnson"
22 results found.
0: B.J. Johnson
1: Buck Johnson
2: Amir Johnson
3: Andy Johnson
4: Brice Johnson
5: Clay Johnson
6: Dave Johnson
7: Ed Johnson
8: Eric Johnson
9: Gus Johnson
10: Ivan Johnson
11: Joe Johnson
12: John Johnson
13: Ken Johnson
14: Ken Johnson
15: Lee Johnson
16: Neil Johnson
17: Nick Johnson
18: Rich Johnson
19: Ron Johnson
20: Stew Johnson
21: Trey Johnson
Pick one: 0
Results for B.J. Johnson:

You searched for "Vic Law"
5 results found.
0: Vic Law
1: Acie Law
2: Dick Lee
3: Jim Les
4: Jim Ray
Pick one: 0
Results for Vic Law:

You searched for "Josh Magette"
1 result found.
Josh Magette
Results for Josh Magette:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-11-17,29-024,ORL,HOME,WAS,W (+4),1,32:52,11,14,...,17,6,0,1,3,3,30,33.2,10,Nikola Vučević
1,2019-12-04,24-079,ORL,HOME,PHO,W (+14),1,33:32,13,15,...,5,5,1,0,1,1,32,30.9,12,Aaron Gordon
2,2020-02-26,24-163,ORL,AWAY,ATL,W (+10),1,40:55,9,14,...,10,6,1,3,1,0,25,29.3,6,Aaron Gordon
3,2020-02-12,24-149,ORL,HOME,DET,W (+4),1,42:48,8,15,...,9,9,1,1,1,0,25,29.0,5,Aaron Gordon
4,2020-02-10,29-109,ORL,HOME,ATL,W (+9),1,33:13,10,15,...,9,9,0,1,0,1,24,27.2,4,Nikola Vučević

In [53]:

ORL_2021_gamelog = []

for p in ORL_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    ORL_2021_gamelog.append(player_log)
ORL_2021_gamelog = pd.concat(ORL_2021_gamelog)    
ORL_2021_gamelogs = ORL_2021_gamelog.copy()
ORL_2021_gamelogs['GAME_SCORE'] = ORL_2021_gamelogs['GAME_SCORE'].astype(float)
ORL_2021_games = ORL_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_2021_games_csv = ORL_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2021_games.csv', index=False)
ORL_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2021_games.csv')
ORL_2021_games_proc.head()

You searched for "Al-Farouq Aminu"
1 result found.
Al-Farouq Aminu
Results for Al-Farouq Aminu:

You searched for "Cole Anthony"
3 results found.
0: Cole Anthony
1: Joel Anthony
2: Greg Anthony
Pick one: 0
Results for Cole Anthony:

You searched for "Dwayne Bacon"
4 results found.
0: Dwayne Bacon
1: Dwayne Sutton
2: Dwayne Morton
3: Wayne Pack
Pick one: 0
Results for Dwayne Bacon:

You searched for "Khem Birch"
1 result found.
Khem Birch
Results for Khem Birch:

You searched for "Jordan Bone"
10 results found.
0: Jordan Bone
1: Jordan Bowden
2: Jordan Ford
3: Jordan Bell
4: Jordan Loyd
5: Jordan Poole
6: Jordan Nwora
7: Jordan Hill
8: Jordan McRae
9: Ryan Bowen
Pick one: 0
Results for Jordan Bone:

You searched for "Ignas Brazdeikis"
1 result found.
Ignas Brazdeikis
Results for Ignas Brazdeikis:

You searched for "Devin Cannady"
2 results found.
0: Devin Cannady
1: Kevin McKenna
Pick one: 0
Results for Devin Cannady:

You searched for "Michael Carter-Williams"
1 result found.
Michael Carter-Williams
Results for Michael Carter-Williams:

You searched for "Gary Clark"
15 results found.
0: Gary Clark
1: Earl Clark
2: Ian Clark
3: Gary Alcorn
4: Cory Carr
5: Carlos Clark
6: Keon Clark
7: Coty Clarke
8: Gary Grant
9: Gary Gray
10: Gar Heard
11: Gary Neal
12: Jay Carty
13: Gary Keller
14: Gary Zeller
Pick one: 0
Results for Gary Clark:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Evan Fournier"
2 results found.
0: Evan Fournier
1: Evan Turner
Pick one: 0
Results for Evan Fournier:

You searched for "Markelle Fultz"
1 result found.
Markelle Fultz
Results for Markelle Fultz:

You searched for "Aaron Gordon"
6 results found.
0: Aaron Gordon
1: Ben Gordon
2: Drew Gordon
3: Eric Gordon
4: Paul Gordon
5: Aaron Gray
Pick one: 0
Results for Aaron Gordon:

You searched for "Donta Hall"
5 results found.
0: Donta Hall
1: Josh Hall
2: Lonzo Ball
3: Devon Hall
4: Donta Smith
Pick one: 0
Results for Donta Hall:

You searched for "R.J. Hampton"
3 results found.
0: R.J. Hampton
1: P.J. Hairston
2: A.J. Hammons
Pick one: 0
Results for R.J. Hampton:

You searched for "Gary Harris"
14 results found.
0: Gary Harris
1: Art Harris
2: Manny Harris
3: Tony Harris
4: Jalen Harris
5: Art Burris
6: Gary Forbes
7: Billy Harris
8: Bob Harris
9: Chris Harris
10: Joe Harris
11: Mike Harris
12: Gary Hill
13: Gary Turner
Pick one: 0
Results for Gary Harris:

You searched for "Karim Mané"
2 results found.
0: Karim Mane
1: Karl Malone
Pick one: 0
Results for Karim Mane:

You searched for "Chuma Okeke"
1 result found.
Chuma Okeke
Results for Chuma Okeke:

You searched for "Otto Porter"
2 results found.
0: Otto Porter
1: Otto Moore
Pick one: 0
Results for Otto Porter:

You searched for "Chasson Randle"
1 result found.
Chasson Randle
Results for Chasson Randle:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Sindarius Thornwell"
1 result found.
Sindarius Thornwell
Results for Sindarius Thornwell:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

You searched for "Moritz Wagner"
2 results found.
0: Moritz Wagner
1: Milt Wagner
Pick one: 0
Results for Moritz Wagner:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-02-12,30-111,ORL,AWAY,SAC,W (+11),1,34:09,17,22,...,9,4,2,0,1,1,42,39.5,9,Nikola Vučević
1,2021-02-05,30-104,ORL,HOME,CHI,W (+4),1,37:18,17,29,...,19,4,0,1,1,2,43,37.7,10,Nikola Vučević
2,2021-01-16,30-084,ORL,AWAY,BRK,L (-7),1,35:42,14,22,...,10,7,5,0,4,4,34,33.1,0,Nikola Vučević
3,2021-02-19,30-118,ORL,HOME,GSW,W (+4),1,38:58,13,23,...,16,10,1,1,0,1,30,32.2,25,Nikola Vučević
4,2020-12-31,27-211,CHI,AWAY,WAS,W (+3),1,30:54,10,14,...,12,3,3,0,0,0,28,31.3,0,Otto Porter

## combine all seasons

In [54]:
ORL_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2000_games.csv')
ORL_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2001_games.csv')
ORL_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2002_games.csv')
ORL_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2003_games.csv')
ORL_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2004_games.csv')
ORL_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2005_games.csv')
ORL_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2006_games.csv')
ORL_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2007_games.csv')
ORL_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2008_games.csv')
ORL_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2009_games.csv')
ORL_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2010_games.csv')
ORL_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2011_games.csv')
ORL_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2012_games.csv')
ORL_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2013_games.csv')
ORL_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2014_games.csv')
ORL_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2015_games.csv')
ORL_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2016_games.csv')
ORL_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2017_games.csv')
ORL_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2018_games.csv')
ORL_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2019_games.csv')
ORL_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2020_games.csv')
ORL_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/ORL/ORL_2021_games.csv')

In [55]:
ORL_season_dfs = [ORL_2000_games_io, ORL_2001_games_io, ORL_2002_games_io, ORL_2003_games_io, ORL_2004_games_io, ORL_2005_games_io,
                 ORL_2006_games_io, ORL_2007_games_io, ORL_2008_games_io, ORL_2009_games_io, ORL_2010_games_io, ORL_2011_games_io,
                 ORL_2012_games_io, ORL_2013_games_io, ORL_2014_games_io, ORL_2015_games_io, ORL_2016_games_io, ORL_2017_games_io,
                 ORL_2018_games_io, ORL_2019_games_io, ORL_2020_games_io, ORL_2021_games_io]

In [56]:
ORL_all = pd.concat(ORL_season_dfs)
ORL_all_sorted = ORL_all.sort_values(by=['GAME_SCORE'], ascending=False)
ORL_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-03-10,24-291,ORL,HOME,WAS,W (+9),1,45:50,20,37,...,10,5,1,0,6,1,62,42.8,10,Tracy McGrady
1,2003-11-14,24-174,ORL,AWAY,DEN,L (-5),1,41:34,20,30,...,6,5,2,2,4,2,51,42.7,-1,Tracy McGrady
0,2003-02-23,23-275,ORL,AWAY,NJN,W (+8),1,45:18,16,27,...,10,13,0,2,4,0,46,42.2,7,Tracy McGrady
0,2009-02-17,23-071,ORL,HOME,CHA,W (+5),1,46:41,16,23,...,19,0,1,8,5,5,45,41.8,16,Dwight Howard
0,2012-01-12,26-035,ORL,AWAY,GSW,W (+8),1,43:37,12,21,...,23,3,4,2,3,2,45,41.3,12,Dwight Howard
0,2011-01-28,25-051,ORL,AWAY,CHI,L (-9),1,42:18,14,20,...,15,2,4,3,3,2,40,40.2,-11,Dwight Howard
0,2016-03-18,23-319,ORL,HOME,CLE,L (-6),1,39:19,16,22,...,5,3,3,2,3,3,45,39.8,-1,Victor Oladipo
0,2021-02-12,30-111,ORL,AWAY,SAC,W (+11),1,34:09,17,22,...,9,4,2,0,1,1,42,39.5,9,Nikola Vučević
0,2001-04-13,21-324,ORL,AWAY,WAS,L (-3),1,44:19,19,31,...,8,7,2,4,6,3,49,39.0,3,Tracy McGrady
1,2003-02-21,23-273,ORL,HOME,CHI,W (+14),1,32:48,15,32,...,5,3,3,1,1,5,52,38.7,20,Tracy McGrady
0,2002-03-08,22-288,ORL,HOME,WAS,W (+3),1,41:56,18,29,...,10,3,2,0,3,1,50,38.6,7,Tracy McGrady
0,2017-11-29,22-074,ORL,HOME,OKC,W (+13),1,43:57,13,23,...,15,4,4,1,1,1,40,38.5,17,Aaron Gordon
1,2011-02-25,25-079,ORL,HOME,OKC,W (+23),1,42:18,16,20,...,15,0,2,6,5,1,40,38.5,23,Dwight Howard
1,2001-11-09,22-169,ORL,HOME,SAC,W (+10),1,42:18,14,30,...,13,6,3,2,2,0,44,38.3,10,Tracy McGrady
1,2017-10-24,22-038,ORL,HOME,BRK,W (+4),1,36:38,14,18,...,14,2,0,0,1,3,41,38.2,7,Aaron Gordon
0,2010-02-17,24-071,ORL,HOME,DET,W (+25),1,41:15,11,16,...,17,3,0,7,1,1,33,38.1,20,Dwight Howard
1,2021-02-05,30-104,ORL,HOME,CHI,W (+4),1,37:18,17,29,...,19,4,0,1,1,2,43,37.7,10,Nikola Vučević
2,2003-12-25,24-215,ORL,HOME,CLE,W (+12),1,49:32,15,29,...,8,11,3,1,2,1,41,37.7,10,Tracy McGrady
0,2018-12-28,28-065,ORL,HOME,TOR,W (+29),1,33:22,12,17,...,19,8,2,1,1,1,30,36.3,33,Nikola Vučević
2,2002-12-25,23-215,ORL,HOME,DET,W (+5),1,43:36,14,26,...,6,1,3,0,1,2,46,36.3,4,Tracy McGrady
3,2002-11-02,23-162,ORL,AWAY,MIL,W (+10),1,38:07,16,29,...,6,7,2,0,4,5,47,36.2,19,Tracy McGrady
1,2010-02-08,33-013,ORL,HOME,NOH,W (+6),1,38:03,19,27,...,7,2,0,0,2,5,48,36.2,19,Vince Carter
2,2011-01-13,25-036,ORL,AWAY,OKC,L (-1),1,42:50,11,19,...,18,1,0,2,2,4,39,36.0,1,Dwight Howard
3,2004-01-16,24-237,ORL,HOME,BOS,W (+6),1,44:56,16,31,...,6,6,3,0,2,1,44,35.3,0,Tracy McGrady
2,2001-12-15,22-205,ORL,AWAY,POR,L (-11),1,45:05,11,22,...,7,9,2,1,0,2,36,35.3,-14,Tracy McGrady