In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2013-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_PHI = []

# PHI
while season <= 2021:
    df_PHI = get_roster('PHI', season)
    df_PHI['Season'] = season
    df_PHI['Team'] = 'PHI'
    appended_data_PHI.append(df_PHI)
    season = season + 1
appended_data_PHI = pd.concat(appended_data_PHI)

In [4]:
PHI_df_all = appended_data_PHI.copy()
PHI_df_all_csv = PHI_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_players_all.csv', index=False)
PHI_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_players_all.csv')
PHI_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,12,Bruce Bowen,SF,6-7,185,1971-06-14,US,3,Cal State Fullerton,2000,PHI
1,11,Ira Bowman,SG,6-5,195,1973-06-11,US,R,"Providence, Penn",2000,PHI
2,52,Matt Geiger,C,7-0,243,1969-09-10,US,7,"Auburn, Georgia Tech",2000,PHI
3,40,Tyrone Hill,PF,6-9,240,1968-03-19,US,9,Xavier,2000,PHI
4,21,Larry Hughes,SG,6-5,184,1979-01-23,US,1,Saint Louis,2000,PHI

In [5]:
PHI_df_2000 = PHI_df_all[PHI_df_all['Season'] == 2000]
PHI_df_2001 = PHI_df_all[PHI_df_all['Season'] == 2001]
PHI_df_2002 = PHI_df_all[PHI_df_all['Season'] == 2002]
PHI_df_2003 = PHI_df_all[PHI_df_all['Season'] == 2003]
PHI_df_2004 = PHI_df_all[PHI_df_all['Season'] == 2004]
PHI_df_2005 = PHI_df_all[PHI_df_all['Season'] == 2005]
PHI_df_2006 = PHI_df_all[PHI_df_all['Season'] == 2006]
PHI_df_2007 = PHI_df_all[PHI_df_all['Season'] == 2007]
PHI_df_2008 = PHI_df_all[PHI_df_all['Season'] == 2008]
PHI_df_2009 = PHI_df_all[PHI_df_all['Season'] == 2009]
PHI_df_2010 = PHI_df_all[PHI_df_all['Season'] == 2010]
PHI_df_2011 = PHI_df_all[PHI_df_all['Season'] == 2011]
PHI_df_2012 = PHI_df_all[PHI_df_all['Season'] == 2012]
PHI_df_2013 = PHI_df_all[PHI_df_all['Season'] == 2013]
PHI_df_2014 = PHI_df_all[PHI_df_all['Season'] == 2014]
PHI_df_2015 = PHI_df_all[PHI_df_all['Season'] == 2015]
PHI_df_2016 = PHI_df_all[PHI_df_all['Season'] == 2016]
PHI_df_2017 = PHI_df_all[PHI_df_all['Season'] == 2017]
PHI_df_2018 = PHI_df_all[PHI_df_all['Season'] == 2018]
PHI_df_2019 = PHI_df_all[PHI_df_all['Season'] == 2019]
PHI_df_2020 = PHI_df_all[PHI_df_all['Season'] == 2020]
PHI_df_2021 = PHI_df_all[PHI_df_all['Season'] == 2021]

In [6]:
# changing names
#PHI_df_2002.loc[PHI_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#PHI_df_2004.loc[PHI_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [7]:
PHI_df_2000_players = PHI_df_2000['PLAYER'].to_list()
PHI_df_2001_players = PHI_df_2001['PLAYER'].to_list()
PHI_df_2002_players = PHI_df_2002['PLAYER'].to_list()
PHI_df_2003_players = PHI_df_2003['PLAYER'].to_list()
PHI_df_2004_players = PHI_df_2004['PLAYER'].to_list()
PHI_df_2005_players = PHI_df_2005['PLAYER'].to_list()

PHI_df_2006_players = PHI_df_2006['PLAYER'].to_list()
PHI_df_2007_players = PHI_df_2007['PLAYER'].to_list()
PHI_df_2008_players = PHI_df_2008['PLAYER'].to_list()
PHI_df_2009_players = PHI_df_2009['PLAYER'].to_list()
PHI_df_2010_players = PHI_df_2010['PLAYER'].to_list()
PHI_df_2011_players = PHI_df_2011['PLAYER'].to_list()

PHI_df_2012_players = PHI_df_2012['PLAYER'].to_list()
PHI_df_2013_players = PHI_df_2013['PLAYER'].to_list()
PHI_df_2014_players = PHI_df_2014['PLAYER'].to_list()
PHI_df_2015_players = PHI_df_2015['PLAYER'].to_list()
PHI_df_2016_players = PHI_df_2016['PLAYER'].to_list()
PHI_df_2017_players = PHI_df_2017['PLAYER'].to_list()

PHI_df_2018_players = PHI_df_2018['PLAYER'].to_list()
PHI_df_2019_players = PHI_df_2019['PLAYER'].to_list()
PHI_df_2020_players = PHI_df_2020['PLAYER'].to_list()
PHI_df_2021_players = PHI_df_2021['PLAYER'].to_list()

## players to drop

In [51]:
#PHI_df_2000_players.remove("Larry Johnson")
#PHI_df_2003_players.remove("Efthimios Rentzias")
#PHI_df_2007_players.remove("Bobby Jones")
#PHI_df_2015_players.remove("Larry Drew")
#PHI_df_2015_players.remove("Chris Johnson")
#PHI_df_2015_players.remove("Glenn Robinson")
#PHI_df_2017_players.remove("Gerald Henderson")
#PHI_df_2018_players.remove("Larry Drew")
#PHI_df_2018_players.remove("James Michael McAdoo")
#PHI_df_2020_players.remove("Kyle O'Quinn")
#PHI_df_2020_players.remove("Glenn Robinson")
PHI_df_2021_players.remove("Dakota Mathias")

In [8]:

PHI_2000_gamelog = []


for p in PHI_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2000_gamelog.append(player_log)
PHI_2000_gamelog = pd.concat(PHI_2000_gamelog)    
PHI_2000_gamelogs = PHI_2000_gamelog.copy()
PHI_2000_gamelogs['GAME_SCORE'] = PHI_2000_gamelogs['GAME_SCORE'].astype(float)
PHI_2000_games = PHI_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2000_games_csv = PHI_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2000_games.csv', index=False)
PHI_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2000_games.csv')
PHI_2000_games_proc.head()

You searched for "Bruce Bowen"
6 results found.
0: Bruce Bowen
1: Bruce Brown
2: Brian Bowen
3: Ryan Bowen
4: Bruce Flowers
5: Bruce Hale
Pick one: 0
Results for Bruce Bowen:

You searched for "Ira Bowman"
3 results found.
0: Ira Bowman
1: Ky Bowman
2: Nate Bowman
Pick one: 0
Results for Ira Bowman:

You searched for "Matt Geiger"
4 results found.
0: Matt Geiger
1: Matt Bonner
2: Matt Freije
3: Tate George
Pick one: 0
Results for Matt Geiger:

You searched for "Tyrone Hill"
5 results found.
0: Tyrone Hill
1: Tyrone Britt
2: Armond Hill
3: Grant Hill
4: Tyronn Lue
Pick one: 0
Results for Tyrone Hill:

You searched for "Larry Hughes"
6 results found.
0: Larry Hughes
1: Larry Bunce
2: Larry Fogle
3: Larry Jones
4: Larry Sykes
5: Larry Wright
Pick one: 0
Results for Larry Hughes:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Jumaine Jones"
3 results found.
0: Jumaine Jones
1: Dwayne Jones
2: Jake Jones
Pick one: 0
Results for Jumaine Jones:

You searched for "Toni Kukoč"
2 results found.
0: Toni Kukoc
1: Tony Koski
Pick one: 0
Results for Toni Kukoc:

You searched for "Antonio Lang"
2 results found.
0: Antonio Lang
1: Antonio Davis
Pick one: 0
Results for Antonio Lang:

You searched for "George Lynch"
12 results found.
0: George Lynch
1: George Blaney
2: George Bucci
3: George King
4: George King
5: George Lee
6: George Brown
7: George Bruns
8: George Hill
9: George Mikan
10: George Stone
11: George Wilson
Pick one: 0
Results for George Lynch:

You searched for "Todd MacCulloch"
1 result found.
Todd MacCulloch
Results for Todd MacCulloch:

You searched for "Aaron McKie"
3 results found.
0: Aaron McKie
1: Aaron Miles
2: Aaron James
Pick one: 0
Results for Aaron McKie:

You searched for "Nazr Mohammed"
1 result found.
Nazr Mohammed
Results for Nazr Mohammed:

You searched for "Kevin Ollie"
8 results found.
0: Kevin Ollie
1: Kevin Love
2: Kevin Willis
3: Kevin Joyce
4: Kevin Loder
5: Kevin O'Shea
6: Kevin Jones
7: Kelvin Cato
Pick one: 0
Results for Kevin Ollie:

You searched for "Billy Owens"
9 results found.
0: Billy Owens
1: Billy Evans
2: Billy James
3: Bill Jones
4: Jim Owens
5: Larry Owens
6: Billy Reid
7: Bill Downey
8: Bill Henry
Pick one: 0
Results for Billy Owens:

You searched for "Theo Ratliff"
3 results found.
0: Theo Ratliff
1: Ed Ratleff
2: Mike Ratliff
Pick one: 0
Results for Theo Ratliff:

You searched for "Stanley Roberts"
2 results found.
0: Stanley Roberts
1: Tony Robertson
Pick one: 0
Results for Stanley Roberts:

You searched for "Eric Snow"
5 results found.
0: Eric Snow
1: Eric Maynor
2: Eric Mika
3: Eric Money
4: Eric Dawson
Pick one: 0
Results for Eric Snow:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-03-22,24-289,PHI,HOME,TOR,W (+13),1,41:24,17,29,...,4,4,3,0,0,2,44,36.7,21,Allen Iverson
1,2000-01-07,31-111,CHI,AWAY,WAS,W (+7),1,39:09,9,15,...,2,10,3,2,1,1,33,35.9,2,Toni Kukoč
2,2000-04-09,21-077,GSW,HOME,DEN,W (+14),1,44:18,16,29,...,6,7,3,1,3,2,44,35.1,21,Larry Hughes
3,2000-03-09,21-046,GSW,HOME,LAL,L (-17),1,40:34,15,25,...,3,3,3,1,0,3,41,33.8,-3,Larry Hughes
4,2000-03-28,24-295,PHI,AWAY,MIN,W (+2),1,45:01,15,28,...,5,4,2,0,4,2,43,31.3,-3,Allen Iverson

In [9]:

PHI_2001_gamelog = []


for p in PHI_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2001_gamelog.append(player_log)
PHI_2001_gamelog = pd.concat(PHI_2001_gamelog)    
PHI_2001_gamelogs = PHI_2001_gamelog.copy()
PHI_2001_gamelogs['GAME_SCORE'] = PHI_2001_gamelogs['GAME_SCORE'].astype(float)
PHI_2001_games = PHI_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2001_games_csv = PHI_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2001_games.csv', index=False)
PHI_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2001_games.csv')
PHI_2001_games_proc.head()

You searched for "Raja Bell"
2 results found.
0: Raja Bell
1: Troy Bell
Pick one: 0
Results for Raja Bell:

You searched for "Rodney Buford"
2 results found.
0: Rodney Buford
1: Rodney Hood
Pick one: 0
Results for Rodney Buford:

You searched for "Matt Geiger"
4 results found.
0: Matt Geiger
1: Matt Bonner
2: Matt Freije
3: Tate George
Pick one: 0
Results for Matt Geiger:

You searched for "Tyrone Hill"
5 results found.
0: Tyrone Hill
1: Tyrone Britt
2: Armond Hill
3: Grant Hill
4: Tyronn Lue
Pick one: 0
Results for Tyrone Hill:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Jumaine Jones"
3 results found.
0: Jumaine Jones
1: Dwayne Jones
2: Jake Jones
Pick one: 0
Results for Jumaine Jones:

You searched for "Toni Kukoč"
2 results found.
0: Toni Kukoc
1: Tony Koski
Pick one: 0
Results for Toni Kukoc:

You searched for "George Lynch"
12 results found.
0: George Lynch
1: George Blaney
2: George Bucci
3: George King
4: George King
5: George Lee
6: George Brown
7: George Bruns
8: George Hill
9: George Mikan
10: George Stone
11: George Wilson
Pick one: 0
Results for George Lynch:

You searched for "Todd MacCulloch"
1 result found.
Todd MacCulloch
Results for Todd MacCulloch:

You searched for "Vernon Maxwell"
1 result found.
Vernon Maxwell
Results for Vernon Maxwell:

You searched for "Aaron McKie"
3 results found.
0: Aaron McKie
1: Aaron Miles
2: Aaron James
Pick one: 0
Results for Aaron McKie:

You searched for "Roshown McLeod"
1 result found.
Roshown McLeod
Results for Roshown McLeod:

You searched for "Anthony Miller"
9 results found.
0: Anthony Miller
1: Anthony Peeler
2: Anthony Bonner
3: Anthony Carter
4: Anthony Parker
5: Anthony Pullard
6: Anthony Taylor
7: Anthony Tolliver
8: Anthony Tucker
Pick one: 0
Results for Anthony Miller:

You searched for "Nazr Mohammed"
1 result found.
Nazr Mohammed
Results for Nazr Mohammed:

You searched for "Dikembe Mutombo"
1 result found.
Dikembe Mutombo
Results for Dikembe Mutombo:

You searched for "Kevin Ollie"
8 results found.
0: Kevin Ollie
1: Kevin Love
2: Kevin Willis
3: Kevin Joyce
4: Kevin Loder
5: Kevin O'Shea
6: Kevin Jones
7: Kelvin Cato
Pick one: 0
Results for Kevin Ollie:

You searched for "Theo Ratliff"
3 results found.
0: Theo Ratliff
1: Ed Ratleff
2: Mike Ratliff
Pick one: 0
Results for Theo Ratliff:

You searched for "Pepe Sánchez"
1 result found.
Pepe Sanchez
Results for Pepe Sanchez:

You searched for "Eric Snow"
5 results found.
0: Eric Snow
1: Eric Maynor
2: Eric Mika
3: Eric Money
4: Eric Dawson
Pick one: 0
Results for Eric Snow:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-01-06,25-213,PHI,AWAY,CLE,W (+4),1,43:56,20,30,...,3,3,3,1,4,3,54,41.3,5,Allen Iverson
1,2000-12-30,25-206,PHI,AWAY,SAC,W (+3),1,51:44,18,36,...,9,9,3,0,3,2,46,37.0,7,Allen Iverson
2,2001-03-09,25-275,PHI,HOME,ATL,W (+5),1,43:15,16,30,...,2,6,4,0,4,4,47,35.2,7,Allen Iverson
3,2001-01-17,25-224,PHI,HOME,CHI,W (+11),1,46:21,15,25,...,3,5,4,0,5,1,43,34.1,13,Allen Iverson
4,2001-01-26,25-233,PHI,HOME,DET,W (+16),1,47:09,14,29,...,3,3,5,0,3,1,44,33.9,16,Allen Iverson

In [10]:

PHI_2002_gamelog = []


for p in PHI_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2002_gamelog.append(player_log)
PHI_2002_gamelog = pd.concat(PHI_2002_gamelog)    
PHI_2002_gamelogs = PHI_2002_gamelog.copy()
PHI_2002_gamelogs['GAME_SCORE'] = PHI_2002_gamelogs['GAME_SCORE'].astype(float)
PHI_2002_games = PHI_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2002_games_csv = PHI_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2002_games.csv', index=False)
PHI_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2002_games.csv')
PHI_2002_games_proc.head()

You searched for "Raja Bell"
2 results found.
0: Raja Bell
1: Troy Bell
Pick one: 0
Results for Raja Bell:

You searched for "Corie Blount"
2 results found.
0: Corie Blount
1: Mark Blount
Pick one: 0
Results for Corie Blount:

You searched for "Ira Bowman"
3 results found.
0: Ira Bowman
1: Ky Bowman
2: Nate Bowman
Pick one: 0
Results for Ira Bowman:

You searched for "Damone Brown"
14 results found.
0: Damone Brown
1: Raymond Brown
2: Andre Brown
3: Dee Brown
4: Dee Brown
5: Devin Brown
6: Harold Brown
7: Kwame Brown
8: Leon Brown
9: Mike Brown
10: Moses Brown
11: Myron Brown
12: Tony Brown
13: Damon Jones
Pick one: 0
Results for Damone Brown:

You searched for "Speedy Claxton"
1 result found.
Speedy Claxton
Results for Speedy Claxton:

You searched for "Derrick Coleman"
2 results found.
0: Derrick Coleman
1: Norris Coleman
Pick one: 0
Results for Derrick Coleman:

You searched for "Vonteego Cummings"
1 result found.
Vonteego Cummings
Results for Vonteego Cummings:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Matt Geiger"
4 results found.
0: Matt Geiger
1: Matt Bonner
2: Matt Freije
3: Tate George
Pick one: 0
Results for Matt Geiger:

You searched for "Matt Harpring"
1 result found.
Matt Harpring
Results for Matt Harpring:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Tim James"
19 results found.
0: Tim James
1: Jim Hayes
2: Mike James
3: Mike James
4: Tre Jones
5: Jim Barnes
6: Jim Davis
7: Jim Farmer
8: Billy James
9: Gene James
10: Justin James
11: Jim Jarvis
12: Sam Jones
13: Wil Jones
14: Jim Les
15: Jim Palmer
16: Tim Thomas
17: Jim Ware
18: Tom Payne
Pick one: 0
Results for Tim James:

You searched for "Alvin Jones"
18 results found.
0: Alvin Jones
1: Kevin Jones
2: Askia Jones
3: Jalen Jones
4: Robin Jones
5: Wali Jones
6: Mason Jones
7: Elvin Hayes
8: Alvin Heggs
9: Collis Jones
10: Damian Jones
11: Damon Jones
12: Eddie Jones
13: Wil Jones
14: Willie Jones
15: Alvin Sims
16: Kevin Joyce
17: Alvin Scott
Pick one: 0
Results for Alvin Jones:

You searched for "Derrick McKey"
5 results found.
0: Derrick McKey
1: Derrek Dickey
2: Derrick Jones
3: Derrick Rose
4: Derrick White
Pick one: 0
Results for Derrick McKey:

You searched for "Aaron McKie"
3 results found.
0: Aaron McKie
1: Aaron Miles
2: Aaron James
Pick one: 0
Results for Aaron McKie:

You searched for "Dikembe Mutombo"
1 result found.
Dikembe Mutombo
Results for Dikembe Mutombo:

You searched for "Michael Ruffin"
1 result found.
Michael Ruffin
Results for Michael Ruffin:

You searched for "Jabari Smith"
8 results found.
0: Jabari Smith
1: Jalen Smith
2: Jabari Bird
3: J.R. Smith
4: Jason Smith
5: Jerry Smith
6: Larry Smith
7: Robert Smith
Pick one: 0
Results for Jabari Smith:

You searched for "Eric Snow"
5 results found.
0: Eric Snow
1: Eric Maynor
2: Eric Mika
3: Eric Money
4: Eric Dawson
Pick one: 0
Results for Eric Snow:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-01-15,26-222,PHI,HOME,HOU,W (+6),1,49:50,21,42,...,2,6,2,0,6,2,58,37.0,8,Allen Iverson
1,2002-02-20,26-258,PHI,HOME,GSW,W (+7),1,45:01,14,36,...,8,6,5,0,2,2,46,34.8,7,Allen Iverson
2,2002-01-25,26-232,PHI,AWAY,BOS,W (+16),1,46:52,16,31,...,4,5,3,0,5,1,47,33.6,14,Allen Iverson
3,2002-03-06,26-272,PHI,HOME,CLE,W (+9),1,47:05,15,30,...,7,4,2,0,3,0,46,33.3,12,Allen Iverson
4,2001-12-15,26-191,PHI,AWAY,CLE,W (+3),1,46:25,18,29,...,6,9,3,0,6,1,40,31.6,1,Allen Iverson

In [13]:
# removed Efthimios Rentzias
    
PHI_2003_gamelog = []



for p in PHI_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2003_gamelog.append(player_log)
PHI_2003_gamelog = pd.concat(PHI_2003_gamelog)    
PHI_2003_gamelogs = PHI_2003_gamelog.copy()
PHI_2003_gamelogs['GAME_SCORE'] = PHI_2003_gamelogs['GAME_SCORE'].astype(float)
PHI_2003_games = PHI_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2003_games_csv = PHI_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2003_games.csv', index=False)
PHI_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2003_games.csv')
PHI_2003_games_proc.head()

You searched for "Mark Bryant"
11 results found.
0: Mark Bryant
1: Mark Blount
2: Mark Bradtke
3: Em Bryant
4: Joe Bryant
5: Kobe Bryant
6: Gary Grant
7: Markel Brown
8: Mark Eaton
9: Mark Workman
10: Mark Sibley
Pick one: 0
Results for Mark Bryant:

You searched for "Greg Buckner"
4 results found.
0: Greg Buckner
1: Greg Butler
2: Greg Bunch
3: Greg Jackson
Pick one: 0
Results for Greg Buckner:

You searched for "Derrick Coleman"
2 results found.
0: Derrick Coleman
1: Norris Coleman
Pick one: 0
Results for Derrick Coleman:

You searched for "Tyrone Hill"
5 results found.
0: Tyrone Hill
1: Tyrone Britt
2: Armond Hill
3: Grant Hill
4: Tyronn Lue
Pick one: 0
Results for Tyrone Hill:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Art Long"
7 results found.
0: Art Long
1: Grant Long
2: Paul Long
3: John Long
4: Shawn Long
5: Walt Lemon
6: Alex Len
Pick one: 0
Results for Art Long:

You searched for "Todd MacCulloch"
1 result found.
Todd MacCulloch
Results for Todd MacCulloch:

You searched for "Aaron McKie"
3 results found.
0: Aaron McKie
1: Aaron Miles
2: Aaron James
Pick one: 0
Results for Aaron McKie:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Kenny Satterfield"
1 result found.
Kenny Satterfield
Results for Kenny Satterfield:

You searched for "Brian Skinner"
6 results found.
0: Brian Skinner
1: Brian Oliver
2: Brian Quinnett
3: Al Skinner
4: Tal Skinner
5: Brian Winters
Pick one: 0
Results for Brian Skinner:

You searched for "Eric Snow"
5 results found.
0: Eric Snow
1: Eric Maynor
2: Eric Mika
3: Eric Money
4: Eric Dawson
Pick one: 0
Results for Eric Snow:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Keith Van Horn"
2 results found.
0: Keith Van Horn
1: Keith Langford
Pick one: 0
Results for Keith Van Horn:

You searched for "Monty Williams"
26 results found.
0: Monty Williams
1: Corey Williams
2: Kenny Williams
3: Matt Williams
4: Milt Williams
5: Mo Williams
6: Ron Williams
7: Art Williams
8: Bob Williams
9: Fly Williams
10: Gene Williams
11: Grant Williams
12: Guy Williams
13: Hank Williams
14: Jay Williams
15: John Williams
16: Lou Williams
17: Mike Williams
18: Nate Williams
19: Pete Williams
20: Ray Williams
21: Rob Williams
22: Scott Williams
23: Sly Williams
24: Troy Williams
25: Walt Williams
Pick one: 0
Results for Monty Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-03-29,27-295,PHI,AWAY,ATL,W (+21),1,43:34,17,25,...,3,9,8,0,5,0,38,37.5,26,Allen Iverson
1,2003-02-21,27-259,PHI,AWAY,CLE,W (+20),1,41:19,12,23,...,2,6,4,0,2,3,41,34.9,21,Allen Iverson
2,2003-04-15,27-312,PHI,AWAY,CHI,L (-9),1,42:40,11,28,...,8,6,2,0,3,2,42,32.8,-17,Allen Iverson
3,2003-03-07,27-273,PHI,AWAY,SEA,W (+9),1,45:54,15,27,...,1,4,3,0,0,1,40,32.8,7,Allen Iverson
4,2003-03-03,27-269,PHI,AWAY,SAC,L (-8),1,47:10,13,23,...,5,4,5,1,2,0,35,30.9,-8,Allen Iverson

In [14]:


PHI_2004_gamelog = []



for p in PHI_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2004_gamelog.append(player_log)
PHI_2004_gamelog = pd.concat(PHI_2004_gamelog)    
PHI_2004_gamelogs = PHI_2004_gamelog.copy()
PHI_2004_gamelogs['GAME_SCORE'] = PHI_2004_gamelogs['GAME_SCORE'].astype(float)
PHI_2004_games = PHI_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2004_games_csv = PHI_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2004_games.csv', index=False)
PHI_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2004_games.csv')
PHI_2004_games_proc.head()

You searched for "Greg Buckner"
4 results found.
0: Greg Buckner
1: Greg Butler
2: Greg Bunch
3: Greg Jackson
Pick one: 0
Results for Greg Buckner:

You searched for "Derrick Coleman"
2 results found.
0: Derrick Coleman
1: Norris Coleman
Pick one: 0
Results for Derrick Coleman:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Willie Green"
14 results found.
0: Willie Green
1: Willie Reed
2: Willie Allen
3: Willis Reed
4: Willie Warren
5: Willie Burton
6: Mike Green
7: Tommie Green
8: Willie Jones
9: Willie Porter
10: Willie Wise
11: Willie Long
12: Willie Rogers
13: Willie White
Pick one: 0
Results for Willie Green:

You searched for "Zendon Hamilton"
3 results found.
0: Zendon Hamilton
1: Dennis Hamilton
2: Jordan Hamilton
Pick one: 0
Results for Zendon Hamilton:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Marc Jackson"
24 results found.
0: Marc Jackson
1: Mark Jackson
2: Aaron Jackson
3: Al Jackson
4: Jaren Jackson
5: Jaren Jackson
6: Mike Jackson
7: Myron Jackson
8: Marc Gasol
9: Cedric Jackson
10: Frank Jackson
11: Greg Jackson
12: Jim Jackson
13: Josh Jackson
14: Luke Jackson
15: Luke Jackson
16: Mervin Jackson
17: Phil Jackson
18: Ralph Jackson
19: Tony Jackson
20: Tony Jackson
21: Tracy Jackson
22: Mark Macon
23: Marcus Banks
Pick one: 0
Results for Marc Jackson:

You searched for "Kyle Korver"
3 results found.
0: Kyle Korver
1: Kyle Weaver
2: Kyle Lowry
Pick one: 0
Results for Kyle Korver:

You searched for "Amal McCaskill"
1 result found.
Amal McCaskill
Results for Amal McCaskill:

You searched for "Aaron McKie"
3 results found.
0: Aaron McKie
1: Aaron Miles
2: Aaron James
Pick one: 0
Results for Aaron McKie:

You searched for "Glenn Robinson"
6 results found.
0: Glenn Robinson
1: Glenn Robinson
2: Flynn Robinson
3: Cliff Robinson
4: Devin Robinson
5: Wayne Robinson
Pick one: 0
Results for Glenn Robinson:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Eric Snow"
5 results found.
0: Eric Snow
1: Eric Maynor
2: Eric Mika
3: Eric Money
4: Eric Dawson
Pick one: 0
Results for Eric Snow:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-11-29,28-175,PHI,HOME,ATL,W (+12),1,43:20,20,34,...,5,6,2,0,2,3,50,38.7,11,Allen Iverson
1,2003-11-07,28-153,PHI,AWAY,CHI,W (+21),1,35:21,11,21,...,2,11,8,0,1,2,33,37.2,29,Allen Iverson
2,2004-02-19,28-257,PHI,AWAY,SEA,W (+11),1,47:31,10,24,...,2,11,5,0,4,0,40,35.3,11,Allen Iverson
3,2004-02-05,28-243,PHI,HOME,LAL,W (+23),1,41:27,15,29,...,3,6,2,0,2,2,39,27.4,24,Allen Iverson
4,2003-11-11,28-157,PHI,AWAY,WAS,W (+7),1,45:54,12,29,...,3,4,4,0,4,0,40,26.6,1,Allen Iverson

In [15]:

PHI_2005_gamelog = []



for p in PHI_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2005_gamelog.append(player_log)
PHI_2005_gamelog = pd.concat(PHI_2005_gamelog)    
PHI_2005_gamelogs = PHI_2005_gamelog.copy()
PHI_2005_gamelogs['GAME_SCORE'] = PHI_2005_gamelogs['GAME_SCORE'].astype(float)
PHI_2005_games = PHI_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2005_games_csv = PHI_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2005_games.csv', index=False)
PHI_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2005_games.csv')
PHI_2005_games_proc.head()

You searched for "Michael Bradley"
7 results found.
0: Michael Bradley
1: Michael Beasley
2: Michael Ansley
3: Michael Finley
4: Michael Frazier
5: Michael Wiley
6: Michael Bytzura
Pick one: 0
Results for Michael Bradley:

You searched for "Kedrick Brown"
2 results found.
0: Kedrick Brown
1: Derrick Brown
Pick one: 0
Results for Kedrick Brown:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Josh Davis"
27 results found.
0: Josh Davis
1: Bob Davis
2: Jim Davis
3: Ron Davis
4: Josh Reaves
5: Josh Hall
6: Bob Davies
7: Ben Davis
8: Bill Davis
9: Brad Davis
10: Dale Davis
11: Ed Davis
12: Glen Davis
13: Johnny Davis
14: Lee Davis
15: Mark Davis
16: Mark Davis
17: Mel Davis
18: Mike Davis
19: Mike Davis
20: Monti Davis
21: Paul Davis
22: Ralph Davis
23: Red Davis
24: Walt Davis
25: Josh Hart
26: Josh Grant
Pick one: 0
Results for Josh Davis:

You searched for "Willie Green"
14 results found.
0: Willie Green
1: Willie Reed
2: Willie Allen
3: Willis Reed
4: Willie Warren
5: Willie Burton
6: Mike Green
7: Tommie Green
8: Willie Jones
9: Willie Porter
10: Willie Wise
11: Willie Long
12: Willie Rogers
13: Willie White
Pick one: 0
Results for Willie Green:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Marc Jackson"
24 results found.
0: Marc Jackson
1: Mark Jackson
2: Aaron Jackson
3: Al Jackson
4: Jaren Jackson
5: Jaren Jackson
6: Mike Jackson
7: Myron Jackson
8: Marc Gasol
9: Cedric Jackson
10: Frank Jackson
11: Greg Jackson
12: Jim Jackson
13: Josh Jackson
14: Luke Jackson
15: Luke Jackson
16: Mervin Jackson
17: Phil Jackson
18: Ralph Jackson
19: Tony Jackson
20: Tony Jackson
21: Tracy Jackson
22: Mark Macon
23: Marcus Banks
Pick one: 0
Results for Marc Jackson:

You searched for "Kyle Korver"
3 results found.
0: Kyle Korver
1: Kyle Weaver
2: Kyle Lowry
Pick one: 0
Results for Kyle Korver:

You searched for "Aaron McKie"
3 results found.
0: Aaron McKie
1: Aaron Miles
2: Aaron James
Pick one: 0
Results for Aaron McKie:

You searched for "Kevin Ollie"
8 results found.
0: Kevin Ollie
1: Kevin Love
2: Kevin Willis
3: Kevin Joyce
4: Kevin Loder
5: Kevin O'Shea
6: Kevin Jones
7: Kelvin Cato
Pick one: 0
Results for Kevin Ollie:

You searched for "Rodney Rogers"
4 results found.
0: Rodney Rogers
1: Johnny Rogers
2: Roy Rogers
3: Rodney Monroe
Pick one: 0
Results for Rodney Rogers:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Brian Skinner"
6 results found.
0: Brian Skinner
1: Brian Oliver
2: Brian Quinnett
3: Al Skinner
4: Tal Skinner
5: Brian Winters
Pick one: 0
Results for Brian Skinner:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-02-12,29-250,PHI,HOME,ORL,W (+13),1,42:01,17,36,...,4,6,5,1,3,1,60,48.5,27,Allen Iverson
1,2004-12-18,29-194,PHI,AWAY,MIL,W (+19),1,40:39,17,29,...,8,5,2,0,3,0,54,44.2,25,Allen Iverson
2,2005-03-01,29-267,PHI,AWAY,MIL,W (+7),1,44:13,18,30,...,3,8,4,0,4,1,48,39.9,10,Allen Iverson
3,2005-04-14,29-311,PHI,HOME,MIA,W (+7),1,53:00,11,24,...,6,16,3,0,2,0,38,39.6,7,Allen Iverson
4,2005-01-24,29-231,PHI,HOME,MIA,W (+8),1,44:27,13,30,...,2,10,4,0,1,1,45,39.0,11,Allen Iverson

In [16]:

PHI_2006_gamelog = []

for p in PHI_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2006_gamelog.append(player_log)
PHI_2006_gamelog = pd.concat(PHI_2006_gamelog)    
PHI_2006_gamelogs = PHI_2006_gamelog.copy()
PHI_2006_gamelogs['GAME_SCORE'] = PHI_2006_gamelogs['GAME_SCORE'].astype(float)
PHI_2006_games = PHI_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2006_games_csv = PHI_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2006_games.csv', index=False)
PHI_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2006_games.csv')
PHI_2006_games_proc.head()

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Michael Bradley"
7 results found.
0: Michael Bradley
1: Michael Beasley
2: Michael Ansley
3: Michael Finley
4: Michael Frazier
5: Michael Wiley
6: Michael Bytzura
Pick one: 0
Results for Michael Bradley:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Deng Gai"
4 results found.
0: Deng Gai
1: Deng Adel
2: Don May
3: Don Ray
Pick one: 0
Results for Deng Gai:

You searched for "Willie Green"
14 results found.
0: Willie Green
1: Willie Reed
2: Willie Allen
3: Willis Reed
4: Willie Warren
5: Willie Burton
6: Mike Green
7: Tommie Green
8: Willie Jones
9: Willie Porter
10: Willie Wise
11: Willie Long
12: Willie Rogers
13: Willie White
Pick one: 0
Results for Willie Green:

You searched for "Zendon Hamilton"
3 results found.
0: Zendon Hamilton
1: Dennis Hamilton
2: Jordan Hamilton
Pick one: 0
Results for Zendon Hamilton:

You searched for "Steven Hunter"
4 results found.
0: Steven Hunter
1: Steve Colter
2: Steve Hamer
3: Steven Kramer
Pick one: 0
Results for Steven Hunter:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Kyle Korver"
3 results found.
0: Kyle Korver
1: Kyle Weaver
2: Kyle Lowry
Pick one: 0
Results for Kyle Korver:

You searched for "Lee Nailon"
2 results found.
0: Lee Nailon
1: Zeke Nnaji
Pick one: 0
Results for Lee Nailon:

You searched for "Kevin Ollie"
8 results found.
0: Kevin Ollie
1: Kevin Love
2: Kevin Willis
3: Kevin Joyce
4: Kevin Loder
5: Kevin O'Shea
6: Kevin Jones
7: Kelvin Cato
Pick one: 0
Results for Kevin Ollie:

You searched for "Shavlik Randolph"
1 result found.
Shavlik Randolph
Results for Shavlik Randolph:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "James Thomas"
18 results found.
0: James Thomas
1: Jamel Thomas
2: Jim Thomas
3: Joe Thomas
4: James Jones
5: James Phelan
6: James Silas
7: Carl Thomas
8: Charles Thomas
9: John Thomas
10: Lance Thomas
11: Matt Thomas
12: Tim Thomas
13: Tyrus Thomas
14: James Hardy
15: James Posey
16: James Cotton
17: James Worthy
Pick one: 0
Results for James Thomas:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-12-23,30-199,PHI,AWAY,ATL,L (-3),1,44:30,17,31,...,6,5,2,0,0,0,53,44.6,-5,Allen Iverson
1,2006-01-11,30-218,PHI,HOME,UTA,L (-8),1,43:52,16,25,...,3,9,4,0,2,5,46,41.3,-11,Allen Iverson
2,2006-03-03,30-269,PHI,HOME,WAS,W (+6),1,47:58,17,28,...,2,12,1,0,4,2,47,39.0,6,Allen Iverson
3,2006-03-31,30-297,PHI,AWAY,NYK,W (+5),1,45:46,13,29,...,6,9,3,0,4,3,47,37.4,6,Allen Iverson
4,2005-12-10,30-186,PHI,AWAY,NJN,W (+12),1,47:25,15,28,...,5,12,4,0,6,0,42,34.3,12,Allen Iverson

In [19]:
# removed Bobby Jones

PHI_2007_gamelog = []

for p in PHI_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2007_gamelog.append(player_log)
PHI_2007_gamelog = pd.concat(PHI_2007_gamelog)    
PHI_2007_gamelogs = PHI_2007_gamelog.copy()
PHI_2007_gamelogs['GAME_SCORE'] = PHI_2007_gamelogs['GAME_SCORE'].astype(float)
PHI_2007_games = PHI_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2007_games_csv = PHI_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2007_games.csv', index=False)
PHI_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2007_games.csv')
PHI_2007_games_proc.head()

You searched for "Lou Amundson"
2 results found.
0: Lou Amundson
1: Lou Hudson
Pick one: 0
Results for Lou Amundson:

You searched for "Rodney Carney"
3 results found.
0: Rodney Carney
1: Rodney McCray
2: Rodney Monroe
Pick one: 0
Results for Rodney Carney:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Willie Green"
14 results found.
0: Willie Green
1: Willie Reed
2: Willie Allen
3: Willis Reed
4: Willie Warren
5: Willie Burton
6: Mike Green
7: Tommie Green
8: Willie Jones
9: Willie Porter
10: Willie Wise
11: Willie Long
12: Willie Rogers
13: Willie White
Pick one: 0
Results for Willie Green:

You searched for "Alan Henderson"
9 results found.
0: Alan Henderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ryan Anderson
5: Dave Henderson
6: J.R. Henderson
7: Kevin Henderson
8: Tom Henderson
Pick one: 0
Results for Alan Henderson:

You searched for "Steven Hunter"
4 results found.
0: Steven Hunter
1: Steve Colter
2: Steve Hamer
3: Steven Kramer
Pick one: 0
Results for Steven Hunter:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Kyle Korver"
3 results found.
0: Kyle Korver
1: Kyle Weaver
2: Kyle Lowry
Pick one: 0
Results for Kyle Korver:

You searched for "Ivan McFarlin"
1 result found.
Ivan McFarlin
Results for Ivan McFarlin:

You searched for "Andre Miller"
7 results found.
0: Andre Miller
1: Eddie Miller
2: Harry Miller
3: Larry Miller
4: Mike Miller
5: Andre Moore
6: Andre Turner
Pick one: 0
Results for Andre Miller:

You searched for "Kevin Ollie"
8 results found.
0: Kevin Ollie
1: Kevin Love
2: Kevin Willis
3: Kevin Joyce
4: Kevin Loder
5: Kevin O'Shea
6: Kevin Jones
7: Kelvin Cato
Pick one: 0
Results for Kevin Ollie:

You searched for "Shavlik Randolph"
1 result found.
Shavlik Randolph
Results for Shavlik Randolph:

You searched for "Joe Smith"
41 results found.
0: Joe Smith
1: Joe Smyth
2: Don Smith
3: Don Smith
4: Jim Smith
5: John Smith
6: Josh Smith
7: Jalen Smith
8: Al Smith
9: Deb Smith
10: Doug Smith
11: Ed Smith
12: Greg Smith
13: Greg Smith
14: Ish Smith
15: J.R. Smith
16: Jason Smith
17: Ken Smith
18: Leon Smith
19: Mike Smith
20: Pete Smith
21: Sam Smith
22: Sam Smith
23: Tony Smith
24: Tom Stith
25: Bill Smith
26: Bobby Smith
27: Derek Smith
28: Donta Smith
29: Elmore Smith
30: Jerry Smith
31: Nolan Smith
32: Otis Smith
33: Phil Smith
34: Robert Smith
35: Russ Smith
36: Steve Smith
37: Rik Smits
38: Sam Stith
39: Joe Ellis
40: Joe Fulks
Pick one: 0
Results for Joe Smith:

You searched for "Steven Smith"
12 results found.
0: Steven Smith
1: Steve Smith
2: Stevin Smith
3: Jalen Smith
4: Steven Hill
5: Steve Mix
6: Derek Smith
7: Ken Smith
8: Leon Smith
9: Pete Smith
10: Theron Smith
11: Steven Adams
Pick one: 0
Results for Steven Smith:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-03-17,31-283,DEN,HOME,PHO,W (+24),1,42:38,16,22,...,5,15,0,1,1,2,44,45.1,31,Allen Iverson
1,2006-11-24,31-170,PHI,HOME,CHI,W (+15),1,44:38,15,30,...,5,10,2,1,2,2,46,39.0,12,Allen Iverson
2,2007-01-29,31-236,DEN,HOME,CHA,L (-4),1,42:54,10,15,...,3,8,4,1,0,1,31,34.5,-7,Allen Iverson
3,2006-11-14,30-240,DEN,AWAY,MIA,W (+7),1,36:47,9,15,...,8,10,3,0,1,2,29,33.1,19,Andre Miller
4,2006-12-02,31-178,PHI,AWAY,NJN,L (-5),1,39:57,11,25,...,3,10,5,0,3,3,37,32.6,-14,Allen Iverson

In [20]:


PHI_2008_gamelog = []

for p in PHI_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2008_gamelog.append(player_log)
PHI_2008_gamelog = pd.concat(PHI_2008_gamelog)    
PHI_2008_gamelogs = PHI_2008_gamelog.copy()
PHI_2008_gamelogs['GAME_SCORE'] = PHI_2008_gamelogs['GAME_SCORE'].astype(float)
PHI_2008_games = PHI_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2008_games_csv = PHI_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2008_games.csv', index=False)
PHI_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2008_games.csv')
PHI_2008_games_proc.head()

You searched for "Lou Amundson"
2 results found.
0: Lou Amundson
1: Lou Hudson
Pick one: 0
Results for Lou Amundson:

You searched for "Calvin Booth"
3 results found.
0: Calvin Booth
1: Calvin Natt
2: Alvin Scott
Pick one: 0
Results for Calvin Booth:

You searched for "Rodney Carney"
3 results found.
0: Rodney Carney
1: Rodney McCray
2: Rodney Monroe
Pick one: 0
Results for Rodney Carney:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Reggie Evans"
10 results found.
0: Reggie Evans
1: Reggie Geary
2: Reggie Hanson
3: Reggie Hearn
4: Reggie King
5: Reggie Lewis
6: Reggie Royals
7: Reggie Theus
8: Reggie Perry
9: Reggie Jordan
Pick one: 0
Results for Reggie Evans:

You searched for "Gordan Giriček"
1 result found.
Gordan Giricek
Results for Gordan Giricek:

You searched for "Willie Green"
14 results found.
0: Willie Green
1: Willie Reed
2: Willie Allen
3: Willis Reed
4: Willie Warren
5: Willie Burton
6: Mike Green
7: Tommie Green
8: Willie Jones
9: Willie Porter
10: Willie Wise
11: Willie Long
12: Willie Rogers
13: Willie White
Pick one: 0
Results for Willie Green:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Kyle Korver"
3 results found.
0: Kyle Korver
1: Kyle Weaver
2: Kyle Lowry
Pick one: 0
Results for Kyle Korver:

You searched for "Andre Miller"
7 results found.
0: Andre Miller
1: Eddie Miller
2: Harry Miller
3: Larry Miller
4: Mike Miller
5: Andre Moore
6: Andre Turner
Pick one: 0
Results for Andre Miller:

You searched for "Kevin Ollie"
8 results found.
0: Kevin Ollie
1: Kevin Love
2: Kevin Willis
3: Kevin Joyce
4: Kevin Loder
5: Kevin O'Shea
6: Kevin Jones
7: Kelvin Cato
Pick one: 0
Results for Kevin Ollie:

You searched for "Shavlik Randolph"
1 result found.
Shavlik Randolph
Results for Shavlik Randolph:

You searched for "Jason Smith"
27 results found.
0: Jason Smith
1: Jalen Smith
2: Don Smith
3: Don Smith
4: Joe Smith
5: John Smith
6: Josh Smith
7: Leon Smith
8: Aaron Nesmith
9: Jason Hart
10: Jason Kidd
11: Al Smith
12: Ish Smith
13: J.R. Smith
14: Jabari Smith
15: Jerry Smith
16: Jim Smith
17: Ken Smith
18: Larry Smith
19: Nolan Smith
20: Randy Smith
21: Russ Smith
22: Sam Smith
23: Sam Smith
24: Theron Smith
25: Tony Smith
26: Joe Smyth
Pick one: 0
Results for Jason Smith:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

You searched for "Thaddeus Young"
1 result found.
Thaddeus Young
Results for Thaddeus Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-03-15,31-362,PHI,HOME,SAS,W (+7),1,42:43,11,14,...,5,7,2,0,0,1,32,34.6,0,Andre Miller
1,2008-04-04,24-067,PHI,AWAY,ATL,W (+5),1,44:54,9,15,...,3,10,1,1,1,5,30,29.3,10,Andre Iguodala
2,2008-02-27,26-214,PHI,HOME,ORL,W (+12),1,36:38,11,18,...,6,5,2,2,0,0,26,26.5,8,Willie Green
3,2007-12-05,31-261,PHI,HOME,BOS,L (-10),1,42:42,10,16,...,5,12,0,0,2,2,26,26.3,-12,Andre Miller
4,2008-04-09,24-072,PHI,HOME,DET,W (+7),1,42:10,7,14,...,5,6,5,0,2,0,25,25.9,2,Andre Iguodala

In [21]:


PHI_2009_gamelog = []

for p in PHI_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2009_gamelog.append(player_log)
PHI_2009_gamelog = pd.concat(PHI_2009_gamelog)    
PHI_2009_gamelogs = PHI_2009_gamelog.copy()
PHI_2009_gamelogs['GAME_SCORE'] = PHI_2009_gamelogs['GAME_SCORE'].astype(float)
PHI_2009_games = PHI_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2009_games_csv = PHI_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2009_games.csv', index=False)
PHI_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2009_games.csv')
PHI_2009_games_proc.head()

You searched for "Elton Brand"
1 result found.
Elton Brand
Results for Elton Brand:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Reggie Evans"
10 results found.
0: Reggie Evans
1: Reggie Geary
2: Reggie Hanson
3: Reggie Hearn
4: Reggie King
5: Reggie Lewis
6: Reggie Royals
7: Reggie Theus
8: Reggie Perry
9: Reggie Jordan
Pick one: 0
Results for Reggie Evans:

You searched for "Willie Green"
14 results found.
0: Willie Green
1: Willie Reed
2: Willie Allen
3: Willis Reed
4: Willie Warren
5: Willie Burton
6: Mike Green
7: Tommie Green
8: Willie Jones
9: Willie Porter
10: Willie Wise
11: Willie Long
12: Willie Rogers
13: Willie White
Pick one: 0
Results for Willie Green:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Royal Ivey"
1 result found.
Royal Ivey
Results for Royal Ivey:

You searched for "Donyell Marshall"
3 results found.
0: Donyell Marshall
1: Donny Marshall
2: Kendall Marshall
Pick one: 0
Results for Donyell Marshall:

You searched for "Andre Miller"
7 results found.
0: Andre Miller
1: Eddie Miller
2: Harry Miller
3: Larry Miller
4: Mike Miller
5: Andre Moore
6: Andre Turner
Pick one: 0
Results for Andre Miller:

You searched for "Theo Ratliff"
3 results found.
0: Theo Ratliff
1: Ed Ratleff
2: Mike Ratliff
Pick one: 0
Results for Theo Ratliff:

You searched for "Kareem Rush"
1 result found.
Kareem Rush
Results for Kareem Rush:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

You searched for "Thaddeus Young"
1 result found.
Thaddeus Young
Results for Thaddeus Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2009-01-17,24-355,PHI,AWAY,NYK,W (+10),1,41:35,10,17,...,10,7,3,0,1,2,28,28.8,17,Andre Iguodala
1,2009-02-11,32-329,PHI,HOME,MEM,W (+4),1,38:15,9,11,...,3,9,2,0,2,1,24,27.1,8,Andre Miller
2,2009-04-15,33-027,PHI,AWAY,CLE,W (+1),1,44:14,10,18,...,1,8,3,0,1,3,30,26.9,2,Andre Miller
3,2009-01-14,24-352,PHI,HOME,POR,W (+21),1,37:42,10,17,...,4,6,2,0,1,2,29,26.3,19,Andre Iguodala
4,2008-12-10,24-317,PHI,HOME,CLE,L (-8),1,39:50,11,16,...,9,5,1,0,2,1,27,26.2,-1,Andre Iguodala

In [22]:

PHI_2010_gamelog = []

for p in PHI_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2010_gamelog.append(player_log)
PHI_2010_gamelog = pd.concat(PHI_2010_gamelog)    
PHI_2010_gamelogs = PHI_2010_gamelog.copy()
PHI_2010_gamelogs['GAME_SCORE'] = PHI_2010_gamelogs['GAME_SCORE'].astype(float)
PHI_2010_games = PHI_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2010_games_csv = PHI_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2010_games.csv', index=False)
PHI_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2010_games.csv')
PHI_2010_games_proc.head()

You searched for "Elton Brand"
1 result found.
Elton Brand
Results for Elton Brand:

You searched for "Primož Brezec"
1 result found.
Primoz Brezec
Results for Primoz Brezec:

You searched for "Rodney Carney"
3 results found.
0: Rodney Carney
1: Rodney McCray
2: Rodney Monroe
Pick one: 0
Results for Rodney Carney:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Francisco Elson"
1 result found.
Francisco Elson
Results for Francisco Elson:

You searched for "Willie Green"
14 results found.
0: Willie Green
1: Willie Reed
2: Willie Allen
3: Willis Reed
4: Willie Warren
5: Willie Burton
6: Mike Green
7: Tommie Green
8: Willie Jones
9: Willie Porter
10: Willie Wise
11: Willie Long
12: Willie Rogers
13: Willie White
Pick one: 0
Results for Willie Green:

You searched for "Jrue Holiday"
2 results found.
0: Jrue Holiday
1: Aaron Holiday
Pick one: 0
Results for Jrue Holiday:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Allen Iverson"
2 results found.
0: Allen Iverson
1: Willie Iverson
Pick one: 0
Results for Allen Iverson:

You searched for "Royal Ivey"
1 result found.
Royal Ivey
Results for Royal Ivey:

You searched for "Jason Kapono"
2 results found.
0: Jason Kapono
1: Jason Lawson
Pick one: 0
Results for Jason Kapono:

You searched for "Jodie Meeks"
1 result found.
Jodie Meeks
Results for Jodie Meeks:

You searched for "Jason Smith"
27 results found.
0: Jason Smith
1: Jalen Smith
2: Don Smith
3: Don Smith
4: Joe Smith
5: John Smith
6: Josh Smith
7: Leon Smith
8: Aaron Nesmith
9: Jason Hart
10: Jason Kidd
11: Al Smith
12: Ish Smith
13: J.R. Smith
14: Jabari Smith
15: Jerry Smith
16: Jim Smith
17: Ken Smith
18: Larry Smith
19: Nolan Smith
20: Randy Smith
21: Russ Smith
22: Sam Smith
23: Sam Smith
24: Theron Smith
25: Tony Smith
26: Joe Smyth
Pick one: 0
Results for Jason Smith:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

You searched for "Thaddeus Young"
1 result found.
Thaddeus Young
Results for Thaddeus Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-04-03,26-065,PHI,HOME,TOR,L (-5),1,49:14,9,14,...,8,11,5,1,3,3,33,38.0,2,Andre Iguodala
1,2010-03-07,21-259,PHI,AWAY,TOR,W (+13),1,42:56,13,18,...,5,2,4,0,1,2,32,30.9,18,Thaddeus Young
2,2009-11-20,23-024,PHI,HOME,MEM,L (-5),1,39:43,12,16,...,2,5,6,0,4,1,31,30.3,5,Lou Williams
3,2009-10-31,23-004,PHI,AWAY,NYK,W (+14),1,42:26,10,12,...,10,7,1,0,1,4,27,28.5,21,Lou Williams
4,2009-10-31,25-276,PHI,AWAY,NYK,W (+14),1,45:18,12,21,...,11,8,1,0,3,2,32,28.2,19,Andre Iguodala

In [23]:

PHI_2011_gamelog = []

for p in PHI_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2011_gamelog.append(player_log)
PHI_2011_gamelog = pd.concat(PHI_2011_gamelog)    
PHI_2011_gamelogs = PHI_2011_gamelog.copy()
PHI_2011_gamelogs['GAME_SCORE'] = PHI_2011_gamelogs['GAME_SCORE'].astype(float)
PHI_2011_games = PHI_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2011_games_csv = PHI_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2011_games.csv', index=False)
PHI_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2011_games.csv')
PHI_2011_games_proc.head()

You searched for "Tony Battie"
8 results found.
0: Tony Battie
1: John Battle
2: Kenny Battle
3: Tony Harris
4: Tony White
5: Tony Allen
6: Tony Bobbitt
7: Tony Bennett
Pick one: 0
Results for Tony Battie:

You searched for "Craig Brackins"
1 result found.
Craig Brackins
Results for Craig Brackins:

You searched for "Elton Brand"
1 result found.
Elton Brand
Results for Elton Brand:

You searched for "Antonio Daniels"
2 results found.
0: Antonio Daniels
1: Antonio Davis
Pick one: 0
Results for Antonio Daniels:

You searched for "Spencer Hawes"
3 results found.
0: Spencer Hawes
1: Steve Hawes
2: Spencer Haywood
Pick one: 0
Results for Spencer Hawes:

You searched for "Jrue Holiday"
2 results found.
0: Jrue Holiday
1: Aaron Holiday
Pick one: 0
Results for Jrue Holiday:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Jason Kapono"
2 results found.
0: Jason Kapono
1: Jason Lawson
Pick one: 0
Results for Jason Kapono:

You searched for "Jodie Meeks"
1 result found.
Jodie Meeks
Results for Jodie Meeks:

You searched for "Andrés Nocioni"
1 result found.
Andres Nocioni
Results for Andres Nocioni:

You searched for "Darius Songaila"
2 results found.
0: Darius Songaila
1: Darius Garland
Pick one: 0
Results for Darius Songaila:

You searched for "Marreese Speights"
1 result found.
Marreese Speights
Results for Marreese Speights:

You searched for "Evan Turner"
11 results found.
0: Evan Turner
1: Evan Fournier
2: John Turner
3: Bill Turner
4: Elston Turner
5: Gary Turner
6: Henry Turner
7: Jack Turner
8: Jack Turner
9: Jeff Turner
10: Wayne Turner
Pick one: 0
Results for Evan Turner:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

You searched for "Thaddeus Young"
1 result found.
Thaddeus Young
Results for Thaddeus Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2011-02-04,31-330,PHI,HOME,NYK,W (+2),1,42:01,14,23,...,16,1,2,2,0,4,33,31.8,15,Elton Brand
1,2011-03-04,27-035,PHI,HOME,MIN,W (+11),1,37:55,7,13,...,10,13,1,1,2,1,22,27.5,18,Andre Iguodala
2,2010-11-03,31-237,PHI,HOME,IND,W (+26),1,35:44,9,15,...,12,4,1,2,0,4,25,27.3,23,Elton Brand
3,2010-11-05,20-146,PHI,HOME,CLE,L (-7),1,38:34,10,17,...,2,8,2,1,0,6,29,27.2,2,Jrue Holiday
4,2011-03-27,20-288,PHI,HOME,SAC,L (-3),1,40:15,11,19,...,9,7,0,1,2,1,28,26.6,3,Jrue Holiday

In [25]:


PHI_2012_gamelog = []

for p in PHI_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2012_gamelog.append(player_log)
PHI_2012_gamelog = pd.concat(PHI_2012_gamelog)    
PHI_2012_gamelogs = PHI_2012_gamelog.copy()
PHI_2012_gamelogs['GAME_SCORE'] = PHI_2012_gamelogs['GAME_SCORE'].astype(float)
PHI_2012_games = PHI_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2012_games_csv = PHI_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2012_games.csv', index=False)
PHI_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2012_games.csv')
PHI_2012_games_proc.head()

You searched for "Lavoy Allen"
6 results found.
0: Lavoy Allen
1: Randy Allen
2: Ray Allen
3: Bob Allen
4: Malik Allen
5: Tony Allen
Pick one: 0
Results for Lavoy Allen:

You searched for "Tony Battie"
8 results found.
0: Tony Battie
1: John Battle
2: Kenny Battle
3: Tony Harris
4: Tony White
5: Tony Allen
6: Tony Bobbitt
7: Tony Bennett
Pick one: 0
Results for Tony Battie:

You searched for "Craig Brackins"
1 result found.
Craig Brackins
Results for Craig Brackins:

You searched for "Elton Brand"
1 result found.
Elton Brand
Results for Elton Brand:

You searched for "Francisco Elson"
1 result found.
Francisco Elson
Results for Francisco Elson:

You searched for "Spencer Hawes"
3 results found.
0: Spencer Hawes
1: Steve Hawes
2: Spencer Haywood
Pick one: 0
Results for Spencer Hawes:

You searched for "Jrue Holiday"
2 results found.
0: Jrue Holiday
1: Aaron Holiday
Pick one: 0
Results for Jrue Holiday:

You searched for "Andre Iguodala"
1 result found.
Andre Iguodala
Results for Andre Iguodala:

You searched for "Jodie Meeks"
1 result found.
Jodie Meeks
Results for Jodie Meeks:

You searched for "Andrés Nocioni"
1 result found.
Andres Nocioni
Results for Andres Nocioni:

You searched for "Xavier Silas"
4 results found.
0: Xavier Silas
1: Xavier Tillman
2: Xavier Sneed
3: James Silas
Pick one: 0
Results for Xavier Silas:

You searched for "Evan Turner"
11 results found.
0: Evan Turner
1: Evan Fournier
2: John Turner
3: Bill Turner
4: Elston Turner
5: Gary Turner
6: Henry Turner
7: Jack Turner
8: Jack Turner
9: Jeff Turner
10: Wayne Turner
Pick one: 0
Results for Evan Turner:

You searched for "Nikola Vučević"
2 results found.
0: Nikola Vucevic
1: Nikola Pekovic
Pick one: 0
Results for Nikola Vucevic:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

You searched for "Sam Young"
10 results found.
0: Sam Young
1: Tim Young
2: James Young
3: Joe Young
4: Trae Young
5: Sam Bowie
6: Sam Jones
7: Danny Young
8: Nick Young
9: Sam Lacey
Pick one: 0
Results for Sam Young:

You searched for "Thaddeus Young"
1 result found.
Thaddeus Young
Results for Thaddeus Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-03-31,33-020,PHI,HOME,ATL,W (+5),1,37:19,10,12,...,10,5,0,3,1,5,25,27.4,11,Elton Brand
1,2012-01-13,24-145,PHI,HOME,WAS,W (+31),1,35:42,10,11,...,4,2,2,0,0,1,26,26.9,36,Jodie Meeks
2,2012-03-27,24-219,PHI,HOME,CLE,W (+18),1,36:07,11,16,...,2,2,1,0,2,2,31,24.8,15,Jodie Meeks
3,2012-03-11,28-043,PHI,AWAY,NYK,W (+12),1,38:31,7,11,...,7,8,4,1,2,3,19,23.7,10,Andre Iguodala
4,2012-03-14,23-139,PHI,AWAY,IND,L (-17),1,38:20,9,12,...,5,4,3,2,0,3,21,23.3,-11,Evan Turner

In [26]:

PHI_2013_gamelog = []

for p in PHI_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2013_gamelog.append(player_log)
PHI_2013_gamelog = pd.concat(PHI_2013_gamelog)    
PHI_2013_gamelogs = PHI_2013_gamelog.copy()
PHI_2013_gamelogs['GAME_SCORE'] = PHI_2013_gamelogs['GAME_SCORE'].astype(float)
PHI_2013_games = PHI_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2013_games_csv = PHI_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2013_games.csv', index=False)
PHI_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2013_games.csv')
PHI_2013_games_proc.head()

You searched for "Lavoy Allen"
6 results found.
0: Lavoy Allen
1: Randy Allen
2: Ray Allen
3: Bob Allen
4: Malik Allen
5: Tony Allen
Pick one: 0
Results for Lavoy Allen:

You searched for "Kwame Brown"
9 results found.
0: Kwame Brown
1: Andre Brown
2: Bruce Brown
3: Damone Brown
4: Dee Brown
5: Dee Brown
6: Mike Brown
7: Stan Brown
8: Jim Browne
Pick one: 0
Results for Kwame Brown:

You searched for "Spencer Hawes"
3 results found.
0: Spencer Hawes
1: Steve Hawes
2: Spencer Haywood
Pick one: 0
Results for Spencer Hawes:

You searched for "Jrue Holiday"
2 results found.
0: Jrue Holiday
1: Aaron Holiday
Pick one: 0
Results for Jrue Holiday:

You searched for "Justin Holiday"
1 result found.
Justin Holiday
Results for Justin Holiday:

You searched for "Royal Ivey"
1 result found.
Royal Ivey
Results for Royal Ivey:

You searched for "Charles Jenkins"
5 results found.
0: Charles Jenkins
1: Charles Jones
2: Charles Jones
3: Charles Jones
4: Charles Johnson
Pick one: 0
Results for Charles Jenkins:

You searched for "Shelvin Mack"
2 results found.
0: Shelvin Mack
1: Sheldon Mac
Pick one: 0
Results for Shelvin Mack:

You searched for "Arnett Moultrie"
1 result found.
Arnett Moultrie
Results for Arnett Moultrie:

You searched for "Jeremy Pargo"
4 results found.
0: Jeremy Pargo
1: Jeremy Lamb
2: Jeremy Evans
3: Jeremy Tyler
Pick one: 0
Results for Jeremy Pargo:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Evan Turner"
11 results found.
0: Evan Turner
1: Evan Fournier
2: John Turner
3: Bill Turner
4: Elston Turner
5: Gary Turner
6: Henry Turner
7: Jack Turner
8: Jack Turner
9: Jeff Turner
10: Wayne Turner
Pick one: 0
Results for Evan Turner:

You searched for "Maalik Wayns"
1 result found.
Maalik Wayns
Results for Maalik Wayns:

You searched for "Damien Wilkins"
1 result found.
Damien Wilkins
Results for Damien Wilkins:

You searched for "Dorell Wright"
2 results found.
0: Dorell Wright
1: Delon Wright
Pick one: 0
Results for Dorell Wright:

You searched for "Nick Young"
10 results found.
0: Nick Young
1: Rick Mount
2: Tim Young
3: Dick Bunt
4: Nick Jones
5: Joe Young
6: Sam Young
7: Trae Young
8: Dick Holub
9: Nick Vanos
Pick one: 0
Results for Nick Young:

You searched for "Thaddeus Young"
1 result found.
Thaddeus Young
Results for Thaddeus Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-01-18,22-220,PHI,HOME,TOR,W (+7),1,45:30,13,23,...,5,14,3,0,3,3,33,31.8,7,Jrue Holiday
1,2012-11-25,22-166,PHI,HOME,PHO,W (+3),1,38:57,13,21,...,3,13,0,0,2,1,33,30.7,11,Jrue Holiday
2,2013-01-15,22-217,PHI,HOME,NOH,L (-12),1,36:13,10,17,...,5,11,4,0,4,3,29,29.5,-22,Jrue Holiday
3,2013-01-26,22-228,PHI,HOME,NYK,W (+17),1,38:29,16,25,...,5,6,1,0,1,2,35,28.4,30,Jrue Holiday
4,2012-12-26,27-024,PHI,AWAY,MEM,W (+10),1,35:27,8,11,...,6,1,1,2,0,2,28,27.2,10,Dorell Wright

In [27]:


PHI_2014_gamelog = []

for p in PHI_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2014_gamelog.append(player_log)
PHI_2014_gamelog = pd.concat(PHI_2014_gamelog)    
PHI_2014_gamelogs = PHI_2014_gamelog.copy()
PHI_2014_gamelogs['GAME_SCORE'] = PHI_2014_gamelogs['GAME_SCORE'].astype(float)
PHI_2014_games = PHI_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2014_games_csv = PHI_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2014_games.csv', index=False)
PHI_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2014_games.csv')
PHI_2014_games_proc.head()

You searched for "Lavoy Allen"
6 results found.
0: Lavoy Allen
1: Randy Allen
2: Ray Allen
3: Bob Allen
4: Malik Allen
5: Tony Allen
Pick one: 0
Results for Lavoy Allen:

You searched for "James Anderson"
10 results found.
0: James Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Derek Anderson
5: Greg Anderson
6: J.J. Anderson
7: Jerome Anderson
8: Kim Anderson
9: Kyle Anderson
Pick one: 0
Results for James Anderson:

You searched for "Lorenzo Brown"
2 results found.
0: Lorenzo Brown
1: Lorenzo Romar
Pick one: 0
Results for Lorenzo Brown:

You searched for "Michael Carter-Williams"
1 result found.
Michael Carter-Williams
Results for Michael Carter-Williams:

You searched for "Brandon Davies"
5 results found.
0: Brandon Davies
1: Brandon Bass
2: Baron Davis
3: Brad Davis
4: Brandon Clarke
Pick one: 0
Results for Brandon Davies:

You searched for "Dewayne Dedmon"
1 result found.
Dewayne Dedmon
Results for Dewayne Dedmon:

You searched for "Spencer Hawes"
3 results found.
0: Spencer Hawes
1: Steve Hawes
2: Spencer Haywood
Pick one: 0
Results for Spencer Hawes:

You searched for "Darius Johnson-Odom"
1 result found.
Darius Johnson-Odom
Results for Darius Johnson-Odom:

You searched for "Eric Maynor"
5 results found.
0: Eric Maynor
1: Eric Dawson
2: Eric Money
3: Eric Snow
4: Eric Mobley
Pick one: 0
Results for Eric Maynor:

You searched for "Darius Morris"
5 results found.
0: Darius Morris
1: Marcus Morris
2: Chris Morris
3: Darius Miles
4: Darius Miller
Pick one: 0
Results for Darius Morris:

You searched for "Arnett Moultrie"
1 result found.
Arnett Moultrie
Results for Arnett Moultrie:

You searched for "Byron Mullens"
2 results found.
0: Byron Mullens
1: Bob Mullens
Pick one: 0
Results for Byron Mullens:

You searched for "James Nunnally"
1 result found.
James Nunnally
Results for James Nunnally:

You searched for "Daniel Orton"
3 results found.
0: Daniel Orton
1: Daniel Oturu
2: Daniel Gibson
Pick one: 0
Results for Daniel Orton:

You searched for "Henry Sims"
5 results found.
0: Henry Sims
1: Henry James
2: Henry Akin
3: Henry Bibby
4: Henry Ward
Pick one: 0
Results for Henry Sims:

You searched for "Adonis Thomas"
2 results found.
0: Adonis Thomas
1: Willis Thomas
Pick one: 0
Results for Adonis Thomas:

You searched for "Hollis Thompson"
2 results found.
0: Hollis Thompson
1: Billy Thompson
Pick one: 0
Results for Hollis Thompson:

You searched for "Evan Turner"
11 results found.
0: Evan Turner
1: Evan Fournier
2: John Turner
3: Bill Turner
4: Elston Turner
5: Gary Turner
6: Henry Turner
7: Jack Turner
8: Jack Turner
9: Jeff Turner
10: Wayne Turner
Pick one: 0
Results for Evan Turner:

You searched for "Jarvis Varnado"
1 result found.
Jarvis Varnado
Results for Jarvis Varnado:

You searched for "Casper Ware"
1 result found.
Casper Ware
Results for Casper Ware:

You searched for "Elliot Williams"
8 results found.
0: Elliot Williams
1: Alvin Williams
2: Cliff Williams
3: Eric Williams
4: Lou Williams
5: Milt Williams
6: Walt Williams
7: Willie Williams
Pick one: 0
Results for Elliot Williams:

You searched for "Tony Wroten"
9 results found.
0: Tony Wroten
1: Tony Brown
2: Tony White
3: Tony Allen
4: Tony Kappen
5: Tony Price
6: Tony Battie
7: Tony Dawson
8: Tony Zeno
Pick one: 0
Results for Tony Wroten:

You searched for "Thaddeus Young"
1 result found.
Thaddeus Young
Results for Thaddeus Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-10-30,22-020,PHI,HOME,MIA,W (+4),1,36:10,6,10,...,7,12,9,0,1,1,22,34.7,12,Michael Carter-Williams
1,2013-11-13,24-233,PHI,HOME,HOU,W (+6),1,44:22,12,16,...,5,0,3,0,0,5,36,32.5,7,James Anderson
2,2014-01-02,25-195,PHI,AWAY,SAC,W (+9),1,36:26,9,16,...,7,4,6,1,0,2,28,32.0,9,Thaddeus Young
3,2014-02-24,25-248,PHI,HOME,MIL,L (-20),1,34:06,11,19,...,5,7,6,0,2,1,28,29.1,-3,Thaddeus Young
4,2014-02-21,25-245,PHI,HOME,DAL,L (-12),1,43:22,12,29,...,13,6,7,0,5,1,30,26.6,-3,Thaddeus Young

In [34]:
# removed larry drew
# removed chris johnson
# removed glenn robinson 

PHI_2015_gamelog = []

for p in PHI_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2015_gamelog.append(player_log)
PHI_2015_gamelog = pd.concat(PHI_2015_gamelog)    
PHI_2015_gamelogs = PHI_2015_gamelog.copy()
PHI_2015_gamelogs['GAME_SCORE'] = PHI_2015_gamelogs['GAME_SCORE'].astype(float)
PHI_2015_games = PHI_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2015_games_csv = PHI_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2015_games.csv', index=False)
PHI_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2015_games.csv')
PHI_2015_games_proc.head()

You searched for "Furkan Aldemir"
1 result found.
Furkan Aldemir
Results for Furkan Aldemir:

You searched for "Isaiah Canaan"
1 result found.
Isaiah Canaan
Results for Isaiah Canaan:

You searched for "Michael Carter-Williams"
1 result found.
Michael Carter-Williams
Results for Michael Carter-Williams:

You searched for "Robert Covington"
1 result found.
Robert Covington
Results for Robert Covington:

You searched for "Brandon Davies"
5 results found.
0: Brandon Davies
1: Brandon Bass
2: Baron Davis
3: Brad Davis
4: Brandon Clarke
Pick one: 0
Results for Brandon Davies:

You searched for "Tim Frazier"
4 results found.
0: Tim Frazier
1: Will Frazier
2: Jim Farmer
3: Walt Frazier
Pick one: 0
Results for Tim Frazier:

You searched for "Drew Gordon"
6 results found.
0: Drew Gordon
1: Drew Gooden
2: Ben Gordon
3: Eric Gordon
4: Aaron Gordon
5: Paul Gordon
Pick one: 0
Results for Drew Gordon:

You searched for "Jerami Grant"
4 results found.
0: Jerami Grant
1: Jerian Grant
2: Horace Grant
3: Travis Grant
Pick one: 0
Results for Jerami Grant:

You searched for "Malcolm Lee"
2 results found.
0: Malcolm Lee
1: Malcolm Miller
Pick one: 0
Results for Malcolm Lee:

You searched for "Luc Mbah a Moute"
1 result found.
Luc Mbah a Moute
Results for Luc Mbah a Moute:

You searched for "K.J. McDaniels"
2 results found.
0: K.J. McDaniels
1: Jim McDaniels
Pick one: 0
Results for K.J. McDaniels:

You searched for "JaVale McGee"
1 result found.
JaVale McGee
Results for JaVale McGee:

You searched for "Nerlens Noel"
1 result found.
Nerlens Noel
Results for Nerlens Noel:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Thomas Robinson"
4 results found.
0: Thomas Robinson
1: Chris Robinson
2: Jamal Robinson
3: James Robinson
Pick one: 0
Results for Thomas Robinson:

You searched for "JaKarr Sampson"
2 results found.
0: JaKarr Sampson
1: Jamal Sampson
Pick one: 0
Results for JaKarr Sampson:

You searched for "Alexey Shved"
1 result found.
Alexey Shved
Results for Alexey Shved:

You searched for "Henry Sims"
5 results found.
0: Henry Sims
1: Henry James
2: Henry Akin
3: Henry Bibby
4: Henry Ward
Pick one: 0
Results for Henry Sims:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Malcolm Thomas"
1 result found.
Malcolm Thomas
Results for Malcolm Thomas:

You searched for "Hollis Thompson"
2 results found.
0: Hollis Thompson
1: Billy Thompson
Pick one: 0
Results for Hollis Thompson:

You searched for "Tony Wroten"
9 results found.
0: Tony Wroten
1: Tony Brown
2: Tony White
3: Tony Allen
4: Tony Kappen
5: Tony Price
6: Tony Battie
7: Tony Dawson
8: Tony Zeno
Pick one: 0
Results for Tony Wroten:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-03-20,20-344,PHI,HOME,NYK,W (+16),1,32:03,9,14,...,14,1,5,3,1,2,23,29.0,7,Nerlens Noel
1,2015-03-04,23-287,PHI,AWAY,OKC,L (-5),1,41:36,10,16,...,7,6,1,0,3,1,31,27.7,5,Isaiah Canaan
2,2015-03-27,20-351,PHI,HOME,LAC,L (-21),1,39:03,12,17,...,14,2,2,0,4,3,30,26.5,-8,Nerlens Noel
3,2015-04-13,23-185,MIL,AWAY,PHI,W (+10),1,30:00,11,17,...,5,5,3,1,2,3,30,26.0,19,Michael Carter-Williams
4,2015-04-08,24-115,PHI,HOME,WAS,L (-29),1,24:21,8,11,...,3,1,2,0,1,1,27,25.1,-12,Robert Covington

In [35]:


PHI_2016_gamelog = []

for p in PHI_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2016_gamelog.append(player_log)
PHI_2016_gamelog = pd.concat(PHI_2016_gamelog)    
PHI_2016_gamelogs = PHI_2016_gamelog.copy()
PHI_2016_gamelogs['GAME_SCORE'] = PHI_2016_gamelogs['GAME_SCORE'].astype(float)
PHI_2016_games = PHI_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2016_games_csv = PHI_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2016_games.csv', index=False)
PHI_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2016_games.csv')
PHI_2016_games_proc.head()

You searched for "Elton Brand"
1 result found.
Elton Brand
Results for Elton Brand:

You searched for "Isaiah Canaan"
1 result found.
Isaiah Canaan
Results for Isaiah Canaan:

You searched for "Robert Covington"
1 result found.
Robert Covington
Results for Robert Covington:

You searched for "Jerami Grant"
4 results found.
0: Jerami Grant
1: Jerian Grant
2: Horace Grant
3: Travis Grant
Pick one: 0
Results for Jerami Grant:

You searched for "Richaun Holmes"
1 result found.
Richaun Holmes
Results for Richaun Holmes:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Kendall Marshall"
2 results found.
0: Kendall Marshall
1: Donyell Marshall
Pick one: 0
Results for Kendall Marshall:

You searched for "T.J. McConnell"
1 result found.
T.J. McConnell
Results for T.J. McConnell:

You searched for "Nerlens Noel"
1 result found.
Nerlens Noel
Results for Nerlens Noel:

You searched for "Jahlil Okafor"
1 result found.
Jahlil Okafor
Results for Jahlil Okafor:

You searched for "Phil Pressey"
2 results found.
0: Phil Pressey
1: Paul Pressey
Pick one: 0
Results for Phil Pressey:

You searched for "JaKarr Sampson"
2 results found.
0: JaKarr Sampson
1: Jamal Sampson
Pick one: 0
Results for JaKarr Sampson:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "Nik Stauskas"
1 result found.
Nik Stauskas
Results for Nik Stauskas:

You searched for "Hollis Thompson"
2 results found.
0: Hollis Thompson
1: Billy Thompson
Pick one: 0
Results for Hollis Thompson:

You searched for "Sonny Weems"
1 result found.
Sonny Weems
Results for Sonny Weems:

You searched for "Christian Wood"
1 result found.
Christian Wood
Results for Christian Wood:

You searched for "Tony Wroten"
9 results found.
0: Tony Wroten
1: Tony Brown
2: Tony White
3: Tony Allen
4: Tony Kappen
5: Tony Price
6: Tony Battie
7: Tony Dawson
8: Tony Zeno
Pick one: 0
Results for Tony Wroten:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-11-27,24-348,PHI,AWAY,HOU,L (-2),1,37:48,7,12,...,7,5,8,1,4,4,28,31.1,1,Robert Covington
1,2016-02-06,20-053,PHI,HOME,BRK,W (+5),1,32:39,9,16,...,17,0,1,3,1,2,22,23.6,12,Jahlil Okafor
2,2016-01-09,27-188,PHI,HOME,TOR,L (-13),1,33:09,12,22,...,5,4,3,0,1,1,28,22.9,-13,Ish Smith
3,2016-04-08,25-116,PHI,HOME,NYK,L (-7),1,34:10,10,21,...,11,2,1,0,1,4,30,22.8,9,Robert Covington
4,2016-03-27,27-266,PHI,AWAY,GSW,L (-12),1,35:57,9,14,...,3,10,3,0,2,1,20,22.3,1,Ish Smith

In [38]:
# removed Gerald Henderson

PHI_2017_gamelog = []

for p in PHI_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2017_gamelog.append(player_log)
PHI_2017_gamelog = pd.concat(PHI_2017_gamelog)    
PHI_2017_gamelogs = PHI_2017_gamelog.copy()
PHI_2017_gamelogs['GAME_SCORE'] = PHI_2017_gamelogs['GAME_SCORE'].astype(float)
PHI_2017_games = PHI_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2017_games_csv = PHI_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2017_games.csv', index=False)
PHI_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2017_games.csv')
PHI_2017_games_proc.head()

You searched for "Justin Anderson"
1 result found.
Justin Anderson
Results for Justin Anderson:

You searched for "Jerryd Bayless"
1 result found.
Jerryd Bayless
Results for Jerryd Bayless:

You searched for "Robert Covington"
1 result found.
Robert Covington
Results for Robert Covington:

You searched for "Joel Embiid"
1 result found.
Joel Embiid
Results for Joel Embiid:

You searched for "Jerami Grant"
4 results found.
0: Jerami Grant
1: Jerian Grant
2: Horace Grant
3: Travis Grant
Pick one: 0
Results for Jerami Grant:

You searched for "Justin Harper"
4 results found.
0: Justin Harper
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Justin Harper:

You searched for "Richaun Holmes"
1 result found.
Richaun Holmes
Results for Richaun Holmes:

You searched for "Ersan İlyasova"
1 result found.
Ersan Ilyasova
Results for Ersan Ilyasova:

You searched for "Shawn Long"
8 results found.
0: Shawn Long
1: Shawn Kemp
2: Art Long
3: Grant Long
4: John Long
5: Paul Long
6: Stan Love
7: Shawn Marion
Pick one: 0
Results for Shawn Long:

You searched for "Timothé Luwawu-Cabarrot"
1 result found.
Timothe Luwawu-Cabarrot
Results for Timothe Luwawu-Cabarrot:

You searched for "T.J. McConnell"
1 result found.
T.J. McConnell
Results for T.J. McConnell:

You searched for "Nerlens Noel"
1 result found.
Nerlens Noel
Results for Nerlens Noel:

You searched for "Jahlil Okafor"
1 result found.
Jahlil Okafor
Results for Jahlil Okafor:

You searched for "Alex Poythress"
1 result found.
Alex Poythress
Results for Alex Poythress:

You searched for "Chasson Randle"
1 result found.
Chasson Randle
Results for Chasson Randle:

You searched for "Sergio Rodríguez"
1 result found.
Sergio Rodriguez
Results for Sergio Rodriguez:

You searched for "Dario Šarić"
2 results found.
0: Dario Saric
1: Marko Jaric
Pick one: 0
Results for Dario Saric:

You searched for "Tiago Splitter"
1 result found.
Tiago Splitter
Results for Tiago Splitter:

You searched for "Nik Stauskas"
1 result found.
Nik Stauskas
Results for Nik Stauskas:

You searched for "Hollis Thompson"
2 results found.
0: Hollis Thompson
1: Billy Thompson
Pick one: 0
Results for Hollis Thompson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-12-18,22-277,PHI,HOME,BRK,W (+1),1,27:19,12,17,...,10,1,2,3,3,2,33,30.3,9,Joel Embiid
1,2017-01-27,22-317,PHI,HOME,HOU,L (-5),1,28:10,11,20,...,7,4,3,2,5,3,32,25.9,0,Joel Embiid
2,2017-02-24,26-072,PHI,HOME,WAS,W (+8),1,39:02,9,14,...,11,3,4,0,2,3,25,25.8,5,Robert Covington
3,2017-01-29,29-259,PHI,AWAY,CHI,L (-13),1,34:57,11,19,...,11,1,1,0,3,2,31,24.5,11,Ersan İlyasova
4,2017-02-25,21-072,PHI,AWAY,NYK,L (-1),1,28:45,11,19,...,10,1,0,0,0,2,28,24.4,3,Jahlil Okafor

In [43]:
# removed larry drew
# removed James Michael McAdoo
PHI_2018_gamelog = []

for p in PHI_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2018_gamelog.append(player_log)
PHI_2018_gamelog = pd.concat(PHI_2018_gamelog)    
PHI_2018_gamelogs = PHI_2018_gamelog.copy()
PHI_2018_gamelogs['GAME_SCORE'] = PHI_2018_gamelogs['GAME_SCORE'].astype(float)
PHI_2018_games = PHI_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2018_games_csv = PHI_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2018_games.csv', index=False)
PHI_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2018_games.csv')
PHI_2018_games_proc.head()

You searched for "Justin Anderson"
1 result found.
Justin Anderson
Results for Justin Anderson:

You searched for "Jerryd Bayless"
1 result found.
Jerryd Bayless
Results for Jerryd Bayless:

You searched for "Marco Belinelli"
1 result found.
Marco Belinelli
Results for Marco Belinelli:

You searched for "Trevor Booker"
3 results found.
0: Trevor Booker
1: Devin Booker
2: Trevor Winter
Pick one: 0
Results for Trevor Booker:

You searched for "Robert Covington"
1 result found.
Robert Covington
Results for Robert Covington:

You searched for "Joel Embiid"
1 result found.
Joel Embiid
Results for Joel Embiid:

You searched for "Markelle Fultz"
1 result found.
Markelle Fultz
Results for Markelle Fultz:

You searched for "Richaun Holmes"
1 result found.
Richaun Holmes
Results for Richaun Holmes:

You searched for "Ersan İlyasova"
1 result found.
Ersan Ilyasova
Results for Ersan Ilyasova:

You searched for "Demetrius Jackson"
1 result found.
Demetrius Jackson
Results for Demetrius Jackson:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Furkan Korkmaz"
1 result found.
Furkan Korkmaz
Results for Furkan Korkmaz:

You searched for "Timothé Luwawu-Cabarrot"
1 result found.
Timothe Luwawu-Cabarrot
Results for Timothe Luwawu-Cabarrot:

You searched for "T.J. McConnell"
1 result found.
T.J. McConnell
Results for T.J. McConnell:

You searched for "Jahlil Okafor"
1 result found.
Jahlil Okafor
Results for Jahlil Okafor:

You searched for "Jacob Pullen"
4 results found.
0: Jacob Pullen
1: Jacob Wiley
2: Bob Mullens
3: Jakob Poeltl
Pick one: 0
Results for Jacob Pullen:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Dario Šarić"
2 results found.
0: Dario Saric
1: Marko Jaric
Pick one: 0
Results for Dario Saric:

You searched for "Ben Simmons"
4 results found.
0: Ben Simmons
1: Bobby Simmons
2: Grant Simmons
3: Kobi Simmons
Pick one: 0
Results for Ben Simmons:

You searched for "Nik Stauskas"
1 result found.
Nik Stauskas
Results for Nik Stauskas:

You searched for "James Young"
12 results found.
0: James Young
1: James Lang
2: Joe Young
3: Sam Young
4: James Jones
5: James Posey
6: Danny Young
7: Tim Young
8: Trae Young
9: James Cotton
10: James Hardy
11: James Scott
Pick one: 0
Results for James Young:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-11-15,23-244,PHI,AWAY,LAL,W (+6),1,34:29,14,20,...,15,7,0,7,2,4,46,47.9,19,Joel Embiid
1,2018-04-06,21-260,PHI,HOME,CLE,W (+2),1,36:08,12,17,...,15,13,4,1,3,4,27,34.0,-3,Ben Simmons
2,2018-02-22,23-343,PHI,AWAY,CHI,W (+1),1,34:32,11,17,...,13,5,3,4,1,2,30,33.5,6,Joel Embiid
3,2018-02-22,21-217,PHI,AWAY,CHI,W (+1),1,34:12,13,18,...,7,11,1,1,2,1,32,32.9,15,Ben Simmons
4,2017-11-13,26-334,PHI,AWAY,LAC,W (+4),1,35:29,9,12,...,6,4,4,0,2,3,31,32.0,10,Robert Covington

In [44]:

PHI_2019_gamelog = []

for p in PHI_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2019_gamelog.append(player_log)
PHI_2019_gamelog = pd.concat(PHI_2019_gamelog)    
PHI_2019_gamelogs = PHI_2019_gamelog.copy()
PHI_2019_gamelogs['GAME_SCORE'] = PHI_2019_gamelogs['GAME_SCORE'].astype(float)
PHI_2019_games = PHI_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2019_games_csv = PHI_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2019_games.csv', index=False)
PHI_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2019_games.csv')
PHI_2019_games_proc.head()

You searched for "Jonah Bolden"
2 results found.
0: Jonah Bolden
1: Jordan Bowden
Pick one: 0
Results for Jonah Bolden:

You searched for "Corey Brewer"
4 results found.
0: Corey Brewer
1: Corey Crowder
2: Corey Beck
3: Ron Brewer
Pick one: 0
Results for Corey Brewer:

You searched for "Jimmy Butler"
6 results found.
0: Jimmy Butler
1: Mike Butler
2: Jimmy Conner
3: Jimmy Foster
4: Jimmy Oliver
5: Jimmy Walker
Pick one: 0
Results for Jimmy Butler:

You searched for "Wilson Chandler"
2 results found.
0: Wilson Chandler
1: Tyson Chandler
Pick one: 0
Results for Wilson Chandler:

You searched for "Robert Covington"
1 result found.
Robert Covington
Results for Robert Covington:

You searched for "Joel Embiid"
1 result found.
Joel Embiid
Results for Joel Embiid:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Markelle Fultz"
1 result found.
Markelle Fultz
Results for Markelle Fultz:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "Haywood Highsmith"
1 result found.
Haywood Highsmith
Results for Haywood Highsmith:

You searched for "Demetrius Jackson"
1 result found.
Demetrius Jackson
Results for Demetrius Jackson:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Furkan Korkmaz"
1 result found.
Furkan Korkmaz
Results for Furkan Korkmaz:

You searched for "Boban Marjanović"
1 result found.
Boban Marjanovic
Results for Boban Marjanovic:

You searched for "T.J. McConnell"
1 result found.
T.J. McConnell
Results for T.J. McConnell:

You searched for "Shake Milton"
1 result found.
Shake Milton
Results for Shake Milton:

You searched for "Greg Monroe"
7 results found.
0: Greg Monroe
1: Greg Minor
2: Earl Monroe
3: Greg Foster
4: Greg Howard
5: Greg Oden
6: Greg Sutton
Pick one: 0
Results for Greg Monroe:

You searched for "Mike Muscala"
2 results found.
0: Mike Muscala
1: Mike Maloy
Pick one: 0
Results for Mike Muscala:

You searched for "Justin Patton"
4 results found.
0: Justin Patton
1: Justin Dentmon
2: Justin Hamilton
3: Justin Jackson
Pick one: 0
Results for Justin Patton:

You searched for "J.J. Redick"
2 results found.
0: J.J. Redick
1: J.R. Reid
Pick one: 0
Results for J.J. Redick:

You searched for "Dario Šarić"
2 results found.
0: Dario Saric
1: Marko Jaric
Pick one: 0
Results for Dario Saric:

You searched for "Mike Scott"
22 results found.
0: Mike Scott
1: Mike Pratt
2: Mike Smith
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike McGee
7: James Scott
8: Ray Scott
9: Willie Scott
10: Mike Smrek
11: Mike Davis
12: Mike Davis
13: Mike Evans
14: Mike Grosso
15: Mike James
16: Mike James
17: Mike Lewis
18: Mike Maloy
19: Mike Niles
20: Mike Price
21: Mike Wilks
Pick one: 0
Results for Mike Scott:

You searched for "Landry Shamet"
1 result found.
Landry Shamet
Results for Landry Shamet:

You searched for "Ben Simmons"
4 results found.
0: Ben Simmons
1: Bobby Simmons
2: Grant Simmons
3: Kobi Simmons
Pick one: 0
Results for Ben Simmons:

You searched for "Jonathon Simmons"
1 result found.
Jonathon Simmons
Results for Jonathon Simmons:

You searched for "Zhaire Smith"
11 results found.
0: Zhaire Smith
1: Charles Smith
2: Charles Smith
3: Charles Smith
4: Chris Smith
5: Chris Smith
6: Craig Smith
7: Elmore Smith
8: Larry Smith
9: Mike Smith
10: Phil Smith
Pick one: 0
Results for Zhaire Smith:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-11-09,24-238,PHI,HOME,CHO,W (+1),1,39:03,11,18,...,18,4,0,4,3,4,42,39.8,9,Joel Embiid
1,2019-03-28,25-012,PHI,HOME,BRK,W (+13),1,27:47,12,20,...,13,6,3,1,2,3,39,38.0,13,Joel Embiid
2,2019-01-02,24-292,PHI,AWAY,PHO,W (+5),1,36:11,12,23,...,18,2,3,2,4,3,42,37.5,6,Joel Embiid
3,2018-10-19,29-035,MIN,HOME,CLE,W (+8),1,36:05,10,12,...,7,3,4,2,2,0,33,37.0,-3,Jimmy Butler
4,2019-03-20,25-004,PHI,HOME,BOS,W (+3),1,41:10,8,17,...,22,4,1,1,3,4,37,36.8,12,Joel Embiid

In [49]:
# removed kyle o'quinn
# removed glenn robinson
PHI_2020_gamelog = []

for p in PHI_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2020_gamelog.append(player_log)
PHI_2020_gamelog = pd.concat(PHI_2020_gamelog)    
PHI_2020_gamelogs = PHI_2020_gamelog.copy()
PHI_2020_gamelogs['GAME_SCORE'] = PHI_2020_gamelogs['GAME_SCORE'].astype(float)
PHI_2020_games = PHI_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2020_games_csv = PHI_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2020_games.csv', index=False)
PHI_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2020_games.csv')
PHI_2020_games_proc.head()

You searched for "Jonah Bolden"
2 results found.
0: Jonah Bolden
1: Jordan Bowden
Pick one: 0
Results for Jonah Bolden:

You searched for "Trey Burke"
5 results found.
0: Trey Burke
1: Pat Burke
2: Alec Burks
3: Corey Beck
4: Troy Bell
Pick one: 0
Results for Trey Burke:

You searched for "Alec Burks"
3 results found.
0: Alec Burks
1: Trey Burke
2: Alex Kirk
Pick one: 0
Results for Alec Burks:

You searched for "Joel Embiid"
1 result found.
Joel Embiid
Results for Joel Embiid:

You searched for "James Ennis"
11 results found.
0: James Ennis
1: James Jones
2: Jamel Artis
3: Tyler Ennis
4: James Lang
5: James Silas
6: James Posey
7: James White
8: James Young
9: James Harden
10: James Phelan
Pick one: 0
Results for James Ennis:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "Al Horford"
5 results found.
0: Al Horford
1: Alton Ford
2: Tito Horford
3: Al Wood
4: Al Thornton
Pick one: 0
Results for Al Horford:

You searched for "Furkan Korkmaz"
1 result found.
Furkan Korkmaz
Results for Furkan Korkmaz:

You searched for "Shake Milton"
1 result found.
Shake Milton
Results for Shake Milton:

You searched for "Raul Neto"
7 results found.
0: Raul Neto
1: Paul Reed
2: Al Cueto
3: Paul Noel
4: Paul Long
5: Raul Lopez
6: Paul Nolen
Pick one: 0
Results for Raul Neto:

You searched for "Norvel Pelle"
1 result found.
Norvel Pelle
Results for Norvel Pelle:

You searched for "Josh Richardson"
4 results found.
0: Josh Richardson
1: Pooh Richardson
2: Jason Richardson
3: Norm Richardson
Pick one: 0
Results for Josh Richardson:

You searched for "Mike Scott"
22 results found.
0: Mike Scott
1: Mike Pratt
2: Mike Smith
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike McGee
7: James Scott
8: Ray Scott
9: Willie Scott
10: Mike Smrek
11: Mike Davis
12: Mike Davis
13: Mike Evans
14: Mike Grosso
15: Mike James
16: Mike James
17: Mike Lewis
18: Mike Maloy
19: Mike Niles
20: Mike Price
21: Mike Wilks
Pick one: 0
Results for Mike Scott:

You searched for "Marial Shayok"
1 result found.
Marial Shayok
Results for Marial Shayok:

You searched for "Ben Simmons"
4 results found.
0: Ben Simmons
1: Bobby Simmons
2: Grant Simmons
3: Kobi Simmons
Pick one: 0
Results for Ben Simmons:

You searched for "Zhaire Smith"
11 results found.
0: Zhaire Smith
1: Charles Smith
2: Charles Smith
3: Charles Smith
4: Chris Smith
5: Chris Smith
6: Craig Smith
7: Elmore Smith
8: Larry Smith
9: Mike Smith
10: Phil Smith
Pick one: 0
Results for Zhaire Smith:

You searched for "Matisse Thybulle"
1 result found.
Matisse Thybulle
Results for Matisse Thybulle:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-02-24,25-345,PHI,HOME,ATL,W (+17),1,36:22,17,24,...,14,3,3,1,4,4,49,44.6,19,Joel Embiid
1,2020-01-20,23-184,PHI,AWAY,BRK,W (+6),1,42:20,12,14,...,12,12,5,2,3,3,34,42.4,13,Ben Simmons
2,2020-08-01,26-138,PHI,AWAY,IND,L (-6),1,34:01,15,23,...,21,4,1,3,4,3,41,40.7,21,Joel Embiid
3,2019-12-07,23-140,PHI,HOME,CLE,W (+47),1,25:39,12,14,...,3,7,1,2,1,2,34,34.2,32,Ben Simmons
4,2020-02-20,25-341,PHI,HOME,BRK,W (+8),1,41:06,10,20,...,16,2,2,2,5,4,39,34.0,24,Joel Embiid

In [52]:
# remvoed dakota mathias
PHI_2021_gamelog = []

for p in PHI_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    PHI_2021_gamelog.append(player_log)
PHI_2021_gamelog = pd.concat(PHI_2021_gamelog)    
PHI_2021_gamelogs = PHI_2021_gamelog.copy()
PHI_2021_gamelogs['GAME_SCORE'] = PHI_2021_gamelogs['GAME_SCORE'].astype(float)
PHI_2021_games = PHI_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_2021_games_csv = PHI_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2021_games.csv', index=False)
PHI_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2021_games.csv')
PHI_2021_games_proc.head()

You searched for "Tony Bradley"
10 results found.
0: Tony Bradley
1: Toby Bailey
2: Joe Bradley
3: Tony Allen
4: Alex Bradley
5: Alonzo Bradley
6: Avery Bradley
7: Bill Bradley
8: Bill Bradley
9: Jim Bradley
Pick one: 0
Results for Tony Bradley:

You searched for "Ignas Brazdeikis"
1 result found.
Ignas Brazdeikis
Results for Ignas Brazdeikis:

You searched for "Gary Clark"
15 results found.
0: Gary Clark
1: Earl Clark
2: Ian Clark
3: Gary Alcorn
4: Cory Carr
5: Carlos Clark
6: Keon Clark
7: Coty Clarke
8: Gary Grant
9: Gary Gray
10: Gar Heard
11: Gary Neal
12: Jay Carty
13: Gary Keller
14: Gary Zeller
Pick one: 0
Results for Gary Clark:

You searched for "Seth Curry"
4 results found.
0: Seth Curry
1: Dell Curry
2: Eddy Curry
3: Stephen Curry
Pick one: 0
Results for Seth Curry:

You searched for "Joel Embiid"
1 result found.
Joel Embiid
Results for Joel Embiid:

You searched for "Terrance Ferguson"
1 result found.
Terrance Ferguson
Results for Terrance Ferguson:

You searched for "Danny Green"
20 results found.
0: Danny Green
1: Kenny Green
2: Johnny Green
3: Danny Finn
4: Danny Granger
5: A.C. Green
6: Devin Green
7: Ken Green
8: Lamar Green
9: Sean Green
10: Sidney Green
11: Donte Greene
12: Lynn Greer
13: Danny Vranes
14: Danny Ainge
15: Danny Doyle
16: Danny Ferry
17: Dennis Grey
18: Danny Wagner
19: Danny Young
Pick one: 0
Results for Danny Green:

You searched for "Tobias Harris"
6 results found.
0: Tobias Harris
1: Elias Harris
2: Bob Harris
3: Chris Harris
4: Tony Harris
5: Bob Harrison
Pick one: 0
Results for Tobias Harris:

You searched for "George Hill"
11 results found.
0: George Hill
1: George Karl
2: George King
3: George King
4: Gary Hill
5: George Lee
6: George Mikan
7: George Wilson
8: George Zidek
9: George Bucci
10: George Lynch
Pick one: 0
Results for George Hill:

You searched for "Dwight Howard"
2 results found.
0: Dwight Howard
1: Dwight Powell
Pick one: 0
Results for Dwight Howard:

You searched for "Isaiah Joe"
3 results found.
0: Isaiah Joe
1: Isaiah Roby
2: Isaiah Rider
Pick one: 0
Results for Isaiah Joe:

You searched for "Mason Jones"
18 results found.
0: Mason Jones
1: Damon Jones
2: Major Jones
3: Jalen Jones
4: Mark Jones
5: Mark Jones
6: Aaron James
7: Alvin Jones
8: Askia Jones
9: Damian Jones
10: Earl Jones
11: Jake Jones
12: James Jones
13: Kevin Jones
14: Larry Jones
15: Robin Jones
16: Sam Jones
17: Wali Jones
Pick one: 0
Results for Mason Jones:

You searched for "Furkan Korkmaz"
1 result found.
Furkan Korkmaz
Results for Furkan Korkmaz:

You searched for "Tyrese Maxey"
1 result found.
Tyrese Maxey
Results for Tyrese Maxey:

You searched for "Shake Milton"
1 result found.
Shake Milton
Results for Shake Milton:

You searched for "Vincent Poirier"
1 result found.
Vincent Poirier
Results for Vincent Poirier:

You searched for "Paul Reed"
16 results found.
0: Paul Reed
1: Paul Noel
2: Hub Reed
3: Paul Cloyd
4: Paul Grant
5: Hal Greer
6: Paul Long
7: Raul Neto
8: Paul Nolen
9: Paul Pressey
10: Davon Reed
11: Ron Reed
12: Naz Reid
13: Paul George
14: Paul Hogue
15: Paul Pierce
Pick one: 0
Results for Paul Reed:

You searched for "Mike Scott"
22 results found.
0: Mike Scott
1: Mike Pratt
2: Mike Smith
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike McGee
7: James Scott
8: Ray Scott
9: Willie Scott
10: Mike Smrek
11: Mike Davis
12: Mike Davis
13: Mike Evans
14: Mike Grosso
15: Mike James
16: Mike James
17: Mike Lewis
18: Mike Maloy
19: Mike Niles
20: Mike Price
21: Mike Wilks
Pick one: 0
Results for Mike Scott:

You searched for "Ben Simmons"
4 results found.
0: Ben Simmons
1: Bobby Simmons
2: Grant Simmons
3: Kobi Simmons
Pick one: 0
Results for Ben Simmons:

You searched for "Matisse Thybulle"
1 result found.
Matisse Thybulle
Results for Matisse Thybulle:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

You searched for "Rayjon Tucker"
1 result found.
Rayjon Tucker
Results for Rayjon Tucker:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-02-19,26-340,PHI,HOME,CHI,W (+7),1,35:16,17,26,...,17,5,2,4,2,2,50,50.8,22,Joel Embiid
1,2021-01-12,26-302,PHI,HOME,MIA,W (+3),1,39:20,16,23,...,16,4,5,1,4,2,45,44.6,4,Joel Embiid
2,2021-02-15,24-210,PHI,AWAY,UTA,L (-11),1,38:09,15,26,...,9,12,1,1,4,2,42,38.6,-5,Ben Simmons
3,2021-02-27,26-348,PHI,HOME,CLE,L (-3),1,40:28,13,22,...,13,6,1,2,3,4,42,38.1,5,Joel Embiid
4,2021-01-20,26-310,PHI,HOME,BOS,W (+8),1,32:53,12,19,...,10,2,1,1,1,2,42,36.2,15,Joel Embiid

## combine all seasons

In [53]:
PHI_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2000_games.csv')
PHI_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2001_games.csv')
PHI_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2002_games.csv')
PHI_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2003_games.csv')
PHI_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2004_games.csv')
PHI_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2005_games.csv')
PHI_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2006_games.csv')
PHI_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2007_games.csv')
PHI_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2008_games.csv')
PHI_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2009_games.csv')
PHI_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2010_games.csv')
PHI_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2011_games.csv')
PHI_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2012_games.csv')
PHI_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2013_games.csv')
PHI_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2014_games.csv')
PHI_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2015_games.csv')
PHI_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2016_games.csv')
PHI_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2017_games.csv')
PHI_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2018_games.csv')
PHI_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2019_games.csv')
PHI_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2020_games.csv')
PHI_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHI/PHI_2021_games.csv')

In [54]:
PHI_season_dfs = [PHI_2000_games_io, PHI_2001_games_io, PHI_2002_games_io, PHI_2003_games_io, PHI_2004_games_io, PHI_2005_games_io,
                 PHI_2006_games_io, PHI_2007_games_io, PHI_2008_games_io, PHI_2009_games_io, PHI_2010_games_io, PHI_2011_games_io,
                 PHI_2012_games_io, PHI_2013_games_io, PHI_2014_games_io, PHI_2015_games_io, PHI_2016_games_io, PHI_2017_games_io,
                 PHI_2018_games_io, PHI_2019_games_io, PHI_2020_games_io, PHI_2021_games_io]

In [55]:
PHI_all = pd.concat(PHI_season_dfs)
PHI_all_sorted = PHI_all.sort_values(by=['GAME_SCORE'], ascending=False)
PHI_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-02-19,26-340,PHI,HOME,CHI,W (+7),1,35:16,17,26,...,17,5,2,4,2,2,50,50.8,22,Joel Embiid
0,2005-02-12,29-250,PHI,HOME,ORL,W (+13),1,42:01,17,36,...,4,6,5,1,3,1,60,48.5,27,Allen Iverson
0,2017-11-15,23-244,PHI,AWAY,LAL,W (+6),1,34:29,14,20,...,15,7,0,7,2,4,46,47.9,19,Joel Embiid
0,2007-03-17,31-283,DEN,HOME,PHO,W (+24),1,42:38,16,22,...,5,15,0,1,1,2,44,45.1,31,Allen Iverson
0,2005-12-23,30-199,PHI,AWAY,ATL,L (-3),1,44:30,17,31,...,6,5,2,0,0,0,53,44.6,-5,Allen Iverson
0,2020-02-24,25-345,PHI,HOME,ATL,W (+17),1,36:22,17,24,...,14,3,3,1,4,4,49,44.6,19,Joel Embiid
1,2021-01-12,26-302,PHI,HOME,MIA,W (+3),1,39:20,16,23,...,16,4,5,1,4,2,45,44.6,4,Joel Embiid
1,2004-12-18,29-194,PHI,AWAY,MIL,W (+19),1,40:39,17,29,...,8,5,2,0,3,0,54,44.2,25,Allen Iverson
1,2020-01-20,23-184,PHI,AWAY,BRK,W (+6),1,42:20,12,14,...,12,12,5,2,3,3,34,42.4,13,Ben Simmons
0,2001-01-06,25-213,PHI,AWAY,CLE,W (+4),1,43:56,20,30,...,3,3,3,1,4,3,54,41.3,5,Allen Iverson
1,2006-01-11,30-218,PHI,HOME,UTA,L (-8),1,43:52,16,25,...,3,9,4,0,2,5,46,41.3,-11,Allen Iverson
2,2020-08-01,26-138,PHI,AWAY,IND,L (-6),1,34:01,15,23,...,21,4,1,3,4,3,41,40.7,21,Joel Embiid
2,2005-03-01,29-267,PHI,AWAY,MIL,W (+7),1,44:13,18,30,...,3,8,4,0,4,1,48,39.9,10,Allen Iverson
0,2018-11-09,24-238,PHI,HOME,CHO,W (+1),1,39:03,11,18,...,18,4,0,4,3,4,42,39.8,9,Joel Embiid
3,2005-04-14,29-311,PHI,HOME,MIA,W (+7),1,53:00,11,24,...,6,16,3,0,2,0,38,39.6,7,Allen Iverson
1,2006-11-24,31-170,PHI,HOME,CHI,W (+15),1,44:38,15,30,...,5,10,2,1,2,2,46,39.0,12,Allen Iverson
4,2005-01-24,29-231,PHI,HOME,MIA,W (+8),1,44:27,13,30,...,2,10,4,0,1,1,45,39.0,11,Allen Iverson
2,2006-03-03,30-269,PHI,HOME,WAS,W (+6),1,47:58,17,28,...,2,12,1,0,4,2,47,39.0,6,Allen Iverson
0,2003-11-29,28-175,PHI,HOME,ATL,W (+12),1,43:20,20,34,...,5,6,2,0,2,3,50,38.7,11,Allen Iverson
2,2021-02-15,24-210,PHI,AWAY,UTA,L (-11),1,38:09,15,26,...,9,12,1,1,4,2,42,38.6,-5,Ben Simmons
3,2021-02-27,26-348,PHI,HOME,CLE,L (-3),1,40:28,13,22,...,13,6,1,2,3,4,42,38.1,5,Joel Embiid
0,2010-04-03,26-065,PHI,HOME,TOR,L (-5),1,49:14,9,14,...,8,11,5,1,3,3,33,38.0,2,Andre Iguodala
1,2019-03-28,25-012,PHI,HOME,BRK,W (+13),1,27:47,12,20,...,13,6,3,1,2,3,39,38.0,13,Joel Embiid
0,2003-03-29,27-295,PHI,AWAY,ATL,W (+21),1,43:34,17,25,...,3,9,8,0,5,0,38,37.5,26,Allen Iverson
2,2019-01-02,24-292,PHI,AWAY,PHO,W (+5),1,36:11,12,23,...,18,2,3,2,4,3,42,37.5,6,Joel Embiid