In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2013-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_PHO = []

# PHO
while season <= 2021:
    df_PHO = get_roster('PHO', season)
    df_PHO['Season'] = season
    df_PHO['Team'] = 'PHO'
    appended_data_PHO.append(df_PHO)
    season = season + 1
appended_data_PHO = pd.concat(appended_data_PHO)

In [4]:
PHO_df_all = appended_data_PHO.copy()
PHO_df_all_csv = PHO_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_players_all.csv', index=False)
PHO_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_players_all.csv')
PHO_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,12,Toby Bailey,SG,6-6,213,1975-11-19,US,1,UCLA,2000,PHO
1,40,Corie Blount,PF,6-9,240,1969-01-04,US,6,Cincinnati,2000,PHO
2,3,Rex Chapman,SG,6-4,185,1967-10-05,US,11,Kentucky,2000,PHO
3,43,Ben Davis,PF,6-9,240,1972-12-26,US,3,"Kansas, Arizona",2000,PHO
4,11,Todd Day,SG,6-6,188,1970-01-07,US,6,Arkansas,2000,PHO

In [6]:
PHO_df_2000 = PHO_df_all[PHO_df_all['Season'] == 2000]
PHO_df_2001 = PHO_df_all[PHO_df_all['Season'] == 2001]
PHO_df_2002 = PHO_df_all[PHO_df_all['Season'] == 2002]
PHO_df_2003 = PHO_df_all[PHO_df_all['Season'] == 2003]
PHO_df_2004 = PHO_df_all[PHO_df_all['Season'] == 2004]
PHO_df_2005 = PHO_df_all[PHO_df_all['Season'] == 2005]
PHO_df_2006 = PHO_df_all[PHO_df_all['Season'] == 2006]
PHO_df_2007 = PHO_df_all[PHO_df_all['Season'] == 2007]
PHO_df_2008 = PHO_df_all[PHO_df_all['Season'] == 2008]
PHO_df_2009 = PHO_df_all[PHO_df_all['Season'] == 2009]
PHO_df_2010 = PHO_df_all[PHO_df_all['Season'] == 2010]
PHO_df_2011 = PHO_df_all[PHO_df_all['Season'] == 2011]
PHO_df_2012 = PHO_df_all[PHO_df_all['Season'] == 2012]
PHO_df_2013 = PHO_df_all[PHO_df_all['Season'] == 2013]
PHO_df_2014 = PHO_df_all[PHO_df_all['Season'] == 2014]
PHO_df_2015 = PHO_df_all[PHO_df_all['Season'] == 2015]
PHO_df_2016 = PHO_df_all[PHO_df_all['Season'] == 2016]
PHO_df_2017 = PHO_df_all[PHO_df_all['Season'] == 2017]
PHO_df_2018 = PHO_df_all[PHO_df_all['Season'] == 2018]
PHO_df_2019 = PHO_df_all[PHO_df_all['Season'] == 2019]
PHO_df_2020 = PHO_df_all[PHO_df_all['Season'] == 2020]
PHO_df_2021 = PHO_df_all[PHO_df_all['Season'] == 2021]

In [6]:
# changing names
#PHO_df_2002.loc[PHO_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#PHO_df_2004.loc[PHO_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [7]:
PHO_df_2000_players = PHO_df_2000['PLAYER'].to_list()
PHO_df_2001_players = PHO_df_2001['PLAYER'].to_list()
PHO_df_2002_players = PHO_df_2002['PLAYER'].to_list()
PHO_df_2003_players = PHO_df_2003['PLAYER'].to_list()
PHO_df_2004_players = PHO_df_2004['PLAYER'].to_list()
PHO_df_2005_players = PHO_df_2005['PLAYER'].to_list()

PHO_df_2006_players = PHO_df_2006['PLAYER'].to_list()
PHO_df_2007_players = PHO_df_2007['PLAYER'].to_list()
PHO_df_2008_players = PHO_df_2008['PLAYER'].to_list()
PHO_df_2009_players = PHO_df_2009['PLAYER'].to_list()
PHO_df_2010_players = PHO_df_2010['PLAYER'].to_list()
PHO_df_2011_players = PHO_df_2011['PLAYER'].to_list()

PHO_df_2012_players = PHO_df_2012['PLAYER'].to_list()
PHO_df_2013_players = PHO_df_2013['PLAYER'].to_list()
PHO_df_2014_players = PHO_df_2014['PLAYER'].to_list()
PHO_df_2015_players = PHO_df_2015['PLAYER'].to_list()
PHO_df_2016_players = PHO_df_2016['PLAYER'].to_list()
PHO_df_2017_players = PHO_df_2017['PLAYER'].to_list()

PHO_df_2018_players = PHO_df_2018['PLAYER'].to_list()
PHO_df_2019_players = PHO_df_2019['PLAYER'].to_list()
PHO_df_2020_players = PHO_df_2020['PLAYER'].to_list()
PHO_df_2021_players = PHO_df_2021['PLAYER'].to_list()

## players to drop

In [57]:
#PHO_df_2000_players.remove("Larry Johnson")
#PHO_df_2008_players.remove("Shaquille O'Neal")
#PHO_df_2009_players.remove("Dee Brown")
#PHO_df_2009_players.remove("Shaquille O'Neal")
#PHO_df_2013_players.remove("Jermaine O'Neal")
#PHO_df_2017_players.remove("Derrick Jones")
#PHO_df_2018_players.remove("Mike James")
#PHO_df_2018_players.remove("Derrick Jones")
#PHO_df_2019_players.remove("George King")
#PHO_df_2019_players.remove("Kelly Oubre")
#PHO_df_2020_players.remove("Kelly Oubre")
PHO_df_2021_players.remove("E'Twaun Moore")

In [8]:

PHO_2000_gamelog = []


for p in PHO_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2000_gamelog.append(player_log)
PHO_2000_gamelog = pd.concat(PHO_2000_gamelog)    
PHO_2000_gamelogs = PHO_2000_gamelog.copy()
PHO_2000_gamelogs['GAME_SCORE'] = PHO_2000_gamelogs['GAME_SCORE'].astype(float)
PHO_2000_games = PHO_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2000_games_csv = PHO_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2000_games.csv', index=False)
PHO_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2000_games.csv')
PHO_2000_games_proc.head()

You searched for "Toby Bailey"
10 results found.
0: Toby Bailey
1: Tony Bradley
2: Tony Allen
3: John Bagley
4: Carl Bailey
5: Gus Bailey
6: Thurl Bailey
7: Bob Riley
8: Tony Battie
9: Toby Kimball
Pick one: 0
Results for Toby Bailey:

You searched for "Corie Blount"
2 results found.
0: Corie Blount
1: Mark Blount
Pick one: 0
Results for Corie Blount:

You searched for "Rex Chapman"
1 result found.
Rex Chapman
Results for Rex Chapman:

You searched for "Ben Davis"
29 results found.
0: Ben Davis
1: Bob Davis
2: Ed Davis
3: Glen Davis
4: Lee Davis
5: Mel Davis
6: Red Davis
7: Ron Davis
8: Bob Davies
9: Baron Davis
10: Bill Davis
11: Brad Davis
12: Brian Davis
13: Jim Davis
14: Aubrey Davis
15: Dale Davis
16: Hubert Davis
17: Josh Davis
18: Mark Davis
19: Mark Davis
20: Mike Davis
21: Mike Davis
22: Monti Davis
23: Paul Davis
24: Terry Davis
25: Tyler Davis
26: Walt Davis
27: Warren Davis
28: Ben Clyde
Pick one: 0
Results for Ben Davis:

You searched for "Todd Day"
5 results found.
0: Todd Day
1: Rudy Gay
2: Don May
3: Don Ray
4: Todd Mundt
Pick one: 0
Results for Todd Day:

You searched for "Tom Gugliotta"
1 result found.
Tom Gugliotta
Results for Tom Gugliotta:

You searched for "Anfernee Hardaway"
1 result found.
Anfernee Hardaway
Results for Anfernee Hardaway:

You searched for "Kevin Johnson"
30 results found.
0: Kevin Johnson
1: Ervin Johnson
2: Ken Johnson
3: Ken Johnson
4: Eric Johnson
5: Ivan Johnson
6: Keldon Johnson
7: Neil Johnson
8: Amir Johnson
9: Armon Johnson
10: Arnie Johnson
11: Chris Johnson
12: Chris Johnson
13: Clemon Johnson
14: Dave Johnson
15: Dennis Johnson
16: Ed Johnson
17: Eddie Johnson
18: Eddie Johnson
19: John Johnson
20: Lee Johnson
21: Magic Johnson
22: Ollie Johnson
23: Reggie Johnson
24: Ron Johnson
25: Steve Johnson
26: Neil Johnston
27: Kevin Jones
28: Devin Robinson
29: Kevin Thompson
Pick one: 0
Results for Kevin Johnson:

You searched for "Jason Kidd"
5 results found.
0: Jason Kidd
1: Jason Hart
2: Stanton Kidd
3: Warren Kidd
4: Jason Smith
Pick one: 0
Results for Jason Kidd:

You searched for "Randy Livingston"
2 results found.
0: Randy Livingston
1: Ron Livingstone
Pick one: 0
Results for Randy Livingston:

You searched for "Luc Longley"
1 result found.
Luc Longley
Results for Luc Longley:

You searched for "Don MacLean"
7 results found.
0: Don MacLean
1: Don Ackerman
2: Don Carlson
3: Don Martin
4: Don Chaney
5: Dan Majerle
6: Sheldon Mac
Pick one: 0
Results for Don MacLean:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Oliver Miller"
3 results found.
0: Oliver Miller
1: Mike Miller
2: Oliver Taylor
Pick one: 0
Results for Oliver Miller:

You searched for "Clifford Robinson"
2 results found.
0: Clifford Robinson
1: Cliff Robinson
Pick one: 0
Results for Clifford Robinson:

You searched for "Rodney Rogers"
4 results found.
0: Rodney Rogers
1: Johnny Rogers
2: Roy Rogers
3: Rodney Monroe
Pick one: 0
Results for Rodney Rogers:

You searched for "Mark West"
15 results found.
0: Mark West
1: Mario West
2: Mark Wade
3: Mark Acres
4: Mark Crow
5: Mark Eaton
6: Mark Jones
7: Mark Jones
8: Mark Pope
9: David West
10: Doug West
11: Jerry West
12: Mark Davis
13: Mark Davis
14: Mark Price
Pick one: 0
Results for Mark West:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-01-16,33-031,PHO,HOME,DEN,W (+13),1,42:31,17,26,...,8,4,0,2,0,2,50,44.8,25,Clifford Robinson
1,1999-12-18,26-270,PHO,HOME,SAC,W (+16),1,41:58,10,18,...,14,14,4,0,2,2,27,35.6,6,Jason Kidd
2,1999-12-17,26-269,PHO,AWAY,POR,W (+8),1,40:38,14,23,...,12,10,2,0,1,3,32,32.7,10,Jason Kidd
3,1999-12-23,26-275,PHO,HOME,DAL,L (-1),1,43:53,11,19,...,6,15,5,0,1,2,25,31.6,1,Jason Kidd
4,2000-02-06,26-320,PHO,HOME,SEA,W (+12),1,38:19,7,12,...,7,12,2,2,1,1,22,29.3,18,Jason Kidd

In [9]:

PHO_2001_gamelog = []


for p in PHO_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2001_gamelog.append(player_log)
PHO_2001_gamelog = pd.concat(PHO_2001_gamelog)    
PHO_2001_gamelogs = PHO_2001_gamelog.copy()
PHO_2001_gamelogs['GAME_SCORE'] = PHO_2001_gamelogs['GAME_SCORE'].astype(float)
PHO_2001_games = PHO_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2001_games_csv = PHO_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2001_games.csv', index=False)
PHO_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2001_games.csv')
PHO_2001_games_proc.head()

You searched for "Corie Blount"
2 results found.
0: Corie Blount
1: Mark Blount
Pick one: 0
Results for Corie Blount:

You searched for "Vinny Del Negro"
1 result found.
Vinny Del Negro
Results for Vinny Del Negro:

You searched for "Tony Delk"
12 results found.
0: Tony Delk
1: Tony Snell
2: Tony Zeno
3: Tony Allen
4: Troy Bell
5: Don Dee
6: Tony Dumas
7: Tony Koski
8: Deng Adel
9: Sonny Dove
10: Tony Price
11: Tony White
Pick one: 0
Results for Tony Delk:

You searched for "Chris Dudley"
8 results found.
0: Chris Dudley
1: Charles Dudley
2: Chris Anstey
3: Jared Dudley
4: Chris Duhon
5: Chris Engler
6: Chris Hunter
7: Chris Mullin
Pick one: 0
Results for Chris Dudley:

You searched for "Mario Elie"
3 results found.
0: Mario Elie
1: Marko Milic
2: Mario West
Pick one: 0
Results for Mario Elie:

You searched for "Rubén Garcés"
1 result found.
Ruben Garces
Results for Ruben Garces:

You searched for "Tom Gugliotta"
1 result found.
Tom Gugliotta
Results for Tom Gugliotta:

You searched for "Anfernee Hardaway"
1 result found.
Anfernee Hardaway
Results for Anfernee Hardaway:

You searched for "Jason Kidd"
5 results found.
0: Jason Kidd
1: Jason Hart
2: Stanton Kidd
3: Warren Kidd
4: Jason Smith
Pick one: 0
Results for Jason Kidd:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Paul McPherson"
1 result found.
Paul McPherson
Results for Paul McPherson:

You searched for "Elliot Perry"
1 result found.
Elliot Perry
Results for Elliot Perry:

You searched for "Clifford Robinson"
2 results found.
0: Clifford Robinson
1: Cliff Robinson
Pick one: 0
Results for Clifford Robinson:

You searched for "Rodney Rogers"
4 results found.
0: Rodney Rogers
1: Johnny Rogers
2: Roy Rogers
3: Rodney Monroe
Pick one: 0
Results for Rodney Rogers:

You searched for "Daniel Santiago"
1 result found.
Daniel Santiago
Results for Daniel Santiago:

You searched for "Jake Tsakalidis"
1 result found.
Jake Tsakalidis
Results for Jake Tsakalidis:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-01-02,26-340,PHO,AWAY,SAC,L (-4),1,49:51,20,27,...,6,0,1,0,2,1,53,42.9,7,Tony Delk
1,2001-04-11,22-339,PHO,HOME,DAL,W (+5),1,45:54,16,23,...,11,2,3,1,1,6,38,34.9,0,Shawn Marion
2,2001-04-13,28-021,PHO,HOME,SEA,W (+9),1,47:21,10,22,...,9,17,4,0,4,1,30,33.2,10,Jason Kidd
3,2001-04-01,28-009,PHO,HOME,MIL,W (+7),1,43:00,11,18,...,2,12,6,0,3,2,30,33.0,4,Jason Kidd
4,2001-02-01,34-047,PHO,AWAY,POR,L (-8),1,38:45,14,24,...,8,2,1,1,3,5,42,32.5,-14,Clifford Robinson

In [10]:

PHO_2002_gamelog = []


for p in PHO_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2002_gamelog.append(player_log)
PHO_2002_gamelog = pd.concat(PHO_2002_gamelog)    
PHO_2002_gamelogs = PHO_2002_gamelog.copy()
PHO_2002_gamelogs['GAME_SCORE'] = PHO_2002_gamelogs['GAME_SCORE'].astype(float)
PHO_2002_games = PHO_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2002_games_csv = PHO_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2002_games.csv', index=False)
PHO_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2002_games.csv')
PHO_2002_games_proc.head()

You searched for "Charlie Bell"
6 results found.
0: Charlie Bell
1: Charlie Black
2: Charlie Brown
3: Charlie Paulk
4: Charlie Tyra
5: Charlie Ward
Pick one: 0
Results for Charlie Bell:

You searched for "Jud Buechler"
1 result found.
Jud Buechler
Results for Jud Buechler:

You searched for "Joe Crispin"
1 result found.
Joe Crispin
Results for Joe Crispin:

You searched for "Vinny Del Negro"
1 result found.
Vinny Del Negro
Results for Vinny Del Negro:

You searched for "Tony Delk"
12 results found.
0: Tony Delk
1: Tony Snell
2: Tony Zeno
3: Tony Allen
4: Troy Bell
5: Don Dee
6: Tony Dumas
7: Tony Koski
8: Deng Adel
9: Sonny Dove
10: Tony Price
11: Tony White
Pick one: 0
Results for Tony Delk:

You searched for "Alton Ford"
6 results found.
0: Alton Ford
1: Don Ford
2: Alphonso Ford
3: Bob Ford
4: Al Horford
5: Leon Wood
Pick one: 0
Results for Alton Ford:

You searched for "Tom Gugliotta"
1 result found.
Tom Gugliotta
Results for Tom Gugliotta:

You searched for "Anfernee Hardaway"
1 result found.
Anfernee Hardaway
Results for Anfernee Hardaway:

You searched for "Joe Johnson"
40 results found.
0: Joe Johnson
1: John Johnson
2: Lee Johnson
3: Ron Johnson
4: Dave Johnson
5: Ed Johnson
6: Gus Johnson
7: James Johnson
8: Ken Johnson
9: Ken Johnson
10: Stew Johnson
11: Trey Johnson
12: Joe Binion
13: Joe Dolhon
14: Alize Johnson
15: Amir Johnson
16: Andy Johnson
17: Armon Johnson
18: Arnie Johnson
19: Avery Johnson
20: B.J. Johnson
21: Brice Johnson
22: Buck Johnson
23: Clay Johnson
24: Eddie Johnson
25: Eddie Johnson
26: Eric Johnson
27: George Johnson
28: George Johnson
29: George Johnson
30: Ivan Johnson
31: Neil Johnson
32: Nick Johnson
33: Ollie Johnson
34: Rich Johnson
35: Steve Johnson
36: Tyler Johnson
37: Nate Johnston
38: Jim Johnstone
39: Joe Colone
Pick one: 0
Results for Joe Johnson:

You searched for "Dan Majerle"
1 result found.
Dan Majerle
Results for Dan Majerle:

You searched for "Stephon Marbury"
1 result found.
Stephon Marbury
Results for Stephon Marbury:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "Milt Palacio"
1 result found.
Milt Palacio
Results for Milt Palacio:

You searched for "Rodney Rogers"
4 results found.
0: Rodney Rogers
1: Johnny Rogers
2: Roy Rogers
3: Rodney Monroe
Pick one: 0
Results for Rodney Rogers:

You searched for "Daniel Santiago"
1 result found.
Daniel Santiago
Results for Daniel Santiago:

You searched for "Jake Tsakalidis"
1 result found.
Jake Tsakalidis
Results for Jake Tsakalidis:

You searched for "Jake Voskuhl"
1 result found.
Jake Voskuhl
Results for Jake Voskuhl:

You searched for "John Wallace"
11 results found.
0: John Wallace
1: John Wall
2: Ben Wallace
3: John Havlicek
4: John Holland
5: John Salley
6: John Vallely
7: Red Wallace
8: John Williams
9: John Bagley
10: John Warren
Pick one: 0
Results for John Wallace:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-02-26,25-006,PHO,AWAY,SAS,L (-8),1,44:32,13,20,...,5,10,1,0,2,4,35,31.7,-10,Stephon Marbury
1,2002-03-27,23-324,PHO,HOME,LAL,W (+12),1,47:20,13,21,...,18,4,2,1,3,4,32,30.8,15,Shawn Marion
2,2002-02-24,25-004,PHO,HOME,SAS,W (+9),1,41:39,14,24,...,7,7,1,1,3,3,36,30.5,11,Stephon Marbury
3,2002-04-09,25-048,PHO,HOME,SEA,W (+7),1,37:52,11,16,...,3,11,0,2,3,1,27,26.4,16,Stephon Marbury
4,2002-03-23,23-320,PHO,AWAY,LAC,W (+3),1,46:08,13,28,...,14,1,6,1,3,3,32,26.2,2,Shawn Marion

In [11]:

    
PHO_2003_gamelog = []



for p in PHO_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2003_gamelog.append(player_log)
PHO_2003_gamelog = pd.concat(PHO_2003_gamelog)    
PHO_2003_gamelogs = PHO_2003_gamelog.copy()
PHO_2003_gamelogs['GAME_SCORE'] = PHO_2003_gamelogs['GAME_SCORE'].astype(float)
PHO_2003_games = PHO_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2003_games_csv = PHO_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2003_games.csv', index=False)
PHO_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2003_games.csv')
PHO_2003_games_proc.head()

You searched for "Randy Brown"
18 results found.
0: Randy Brown
1: Andre Brown
2: Larry Brown
3: Tony Brown
4: Randy Allen
5: Randy Breuer
6: Bobby Brown
7: Fred Brown
8: Gerald Brown
9: Raymond Brown
10: Rickey Brown
11: Roger Brown
12: Roger Brown
13: Stan Brown
14: Troy Brown
15: Randy Foye
16: Randy Stoll
17: Randy Woods
Pick one: 0
Results for Randy Brown:

You searched for "Alton Ford"
6 results found.
0: Alton Ford
1: Don Ford
2: Alphonso Ford
3: Bob Ford
4: Al Horford
5: Leon Wood
Pick one: 0
Results for Alton Ford:

You searched for "Tom Gugliotta"
1 result found.
Tom Gugliotta
Results for Tom Gugliotta:

You searched for "Anfernee Hardaway"
1 result found.
Anfernee Hardaway
Results for Anfernee Hardaway:

You searched for "Casey Jacobsen"
1 result found.
Casey Jacobsen
Results for Casey Jacobsen:

You searched for "Joe Johnson"
40 results found.
0: Joe Johnson
1: John Johnson
2: Lee Johnson
3: Ron Johnson
4: Dave Johnson
5: Ed Johnson
6: Gus Johnson
7: James Johnson
8: Ken Johnson
9: Ken Johnson
10: Stew Johnson
11: Trey Johnson
12: Joe Binion
13: Joe Dolhon
14: Alize Johnson
15: Amir Johnson
16: Andy Johnson
17: Armon Johnson
18: Arnie Johnson
19: Avery Johnson
20: B.J. Johnson
21: Brice Johnson
22: Buck Johnson
23: Clay Johnson
24: Eddie Johnson
25: Eddie Johnson
26: Eric Johnson
27: George Johnson
28: George Johnson
29: George Johnson
30: Ivan Johnson
31: Neil Johnson
32: Nick Johnson
33: Ollie Johnson
34: Rich Johnson
35: Steve Johnson
36: Tyler Johnson
37: Nate Johnston
38: Jim Johnstone
39: Joe Colone
Pick one: 0
Results for Joe Johnson:

You searched for "Dan Langhi"
6 results found.
0: Dan Langhi
1: Dan King
2: James Lang
3: Grant Long
4: Shawn Long
5: Dan Tieman
Pick one: 0
Results for Dan Langhi:

You searched for "Stephon Marbury"
1 result found.
Stephon Marbury
Results for Stephon Marbury:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "Jake Tsakalidis"
1 result found.
Jake Tsakalidis
Results for Jake Tsakalidis:

You searched for "Jake Voskuhl"
1 result found.
Jake Voskuhl
Results for Jake Voskuhl:

You searched for "Scott Williams"
22 results found.
0: Scott Williams
1: Matt Williams
2: Art Williams
3: Bob Williams
4: C.J. Williams
5: Corey Williams
6: Grant Williams
7: John Williams
8: Lou Williams
9: Milt Williams
10: Mo Williams
11: Monty Williams
12: Nate Williams
13: Pete Williams
14: Rob Williams
15: Ron Williams
16: Sam Williams
17: Sam Williams
18: Sean Williams
19: Sly Williams
20: Troy Williams
21: Walt Williams
Pick one: 0
Results for Scott Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-02-14,25-359,PHO,HOME,NYK,L (-1),1,43:24,15,27,...,3,9,4,0,3,2,43,37.1,6,Stephon Marbury
1,2003-01-17,25-331,PHO,HOME,DAL,W (+5),1,46:03,15,28,...,4,11,1,1,0,4,41,36.4,5,Stephon Marbury
2,2003-02-26,26-006,PHO,AWAY,MIL,W (+6),1,42:58,14,21,...,6,7,0,0,2,2,41,34.6,8,Stephon Marbury
3,2002-11-29,25-282,PHO,HOME,SAS,W (+7),1,43:50,18,34,...,5,5,3,0,0,2,43,34.4,5,Stephon Marbury
4,2003-03-04,26-012,PHO,AWAY,SAS,W (+7),1,48:00,12,14,...,3,13,0,0,4,4,35,33.2,7,Stephon Marbury

In [12]:


PHO_2004_gamelog = []



for p in PHO_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2004_gamelog.append(player_log)
PHO_2004_gamelog = pd.concat(PHO_2004_gamelog)    
PHO_2004_gamelogs = PHO_2004_gamelog.copy()
PHO_2004_gamelogs['GAME_SCORE'] = PHO_2004_gamelogs['GAME_SCORE'].astype(float)
PHO_2004_games = PHO_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2004_games_csv = PHO_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2004_games.csv', index=False)
PHO_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2004_games.csv')
PHO_2004_games_proc.head()

You searched for "Robert Archibald"
1 result found.
Robert Archibald
Results for Robert Archibald:

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Žarko Čabarkapa"
1 result found.
Zarko Cabarkapa
Results for Zarko Cabarkapa:

You searched for "Howard Eisley"
1 result found.
Howard Eisley
Results for Howard Eisley:

You searched for "Tom Gugliotta"
1 result found.
Tom Gugliotta
Results for Tom Gugliotta:

You searched for "Anfernee Hardaway"
1 result found.
Anfernee Hardaway
Results for Anfernee Hardaway:

You searched for "Donnell Harvey"
1 result found.
Donnell Harvey
Results for Donnell Harvey:

You searched for "Casey Jacobsen"
1 result found.
Casey Jacobsen
Results for Casey Jacobsen:

You searched for "Joe Johnson"
40 results found.
0: Joe Johnson
1: John Johnson
2: Lee Johnson
3: Ron Johnson
4: Dave Johnson
5: Ed Johnson
6: Gus Johnson
7: James Johnson
8: Ken Johnson
9: Ken Johnson
10: Stew Johnson
11: Trey Johnson
12: Joe Binion
13: Joe Dolhon
14: Alize Johnson
15: Amir Johnson
16: Andy Johnson
17: Armon Johnson
18: Arnie Johnson
19: Avery Johnson
20: B.J. Johnson
21: Brice Johnson
22: Buck Johnson
23: Clay Johnson
24: Eddie Johnson
25: Eddie Johnson
26: Eric Johnson
27: George Johnson
28: George Johnson
29: George Johnson
30: Ivan Johnson
31: Neil Johnson
32: Nick Johnson
33: Ollie Johnson
34: Rich Johnson
35: Steve Johnson
36: Tyler Johnson
37: Nate Johnston
38: Jim Johnstone
39: Joe Colone
Pick one: 0
Results for Joe Johnson:

You searched for "Brevin Knight"
5 results found.
0: Brevin Knight
1: Brandin Knight
2: Travis Knight
3: Brandon Knight
4: Ron Knight
Pick one: 0
Results for Brevin Knight:

You searched for "Maciej Lampe"
1 result found.
Maciej Lampe
Results for Maciej Lampe:

You searched for "Stephon Marbury"
1 result found.
Stephon Marbury
Results for Stephon Marbury:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Antonio McDyess"
1 result found.
Antonio McDyess
Results for Antonio McDyess:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "Cezary Trybański"
1 result found.
Cezary Trybanski
Results for Cezary Trybanski:

You searched for "Jake Voskuhl"
1 result found.
Jake Voskuhl
Results for Jake Voskuhl:

You searched for "Jahidi White"
3 results found.
0: Jahidi White
1: James White
2: Randy White
Pick one: 0
Results for Jahidi White:

You searched for "Scott Williams"
22 results found.
0: Scott Williams
1: Matt Williams
2: Art Williams
3: Bob Williams
4: C.J. Williams
5: Corey Williams
6: Grant Williams
7: John Williams
8: Lou Williams
9: Milt Williams
10: Mo Williams
11: Monty Williams
12: Nate Williams
13: Pete Williams
14: Rob Williams
15: Ron Williams
16: Sam Williams
17: Sam Williams
18: Sean Williams
19: Sly Williams
20: Troy Williams
21: Walt Williams
Pick one: 0
Results for Scott Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-12-29,26-312,PHO,AWAY,LAC,W (+8),1,41:46,15,23,...,4,9,5,0,2,1,40,40.4,8,Stephon Marbury
1,2004-02-08,26-353,NYK,HOME,LAC,W (+6),1,45:07,15,20,...,1,8,2,0,4,1,42,37.1,6,Stephon Marbury
2,2004-01-12,26-326,NYK,HOME,DAL,L (-6),1,51:50,14,24,...,3,14,1,0,4,3,38,32.9,-5,Stephon Marbury
3,2003-12-14,25-221,PHO,AWAY,SAC,L (-5),1,43:30,14,26,...,12,6,4,2,1,2,32,32.8,1,Shawn Marion
4,2004-03-05,27-014,NYK,AWAY,TOR,W (+6),1,42:48,12,21,...,4,9,2,0,2,2,35,31.8,10,Stephon Marbury

In [14]:

PHO_2005_gamelog = []



for p in PHO_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2005_gamelog.append(player_log)
PHO_2005_gamelog = pd.concat(PHO_2005_gamelog)    
PHO_2005_gamelogs = PHO_2005_gamelog.copy()
PHO_2005_gamelogs['GAME_SCORE'] = PHO_2005_gamelogs['GAME_SCORE'].astype(float)
PHO_2005_games = PHO_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2005_games_csv = PHO_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2005_games.csv', index=False)
PHO_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2005_games.csv')
PHO_2005_games_proc.head()

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Žarko Čabarkapa"
1 result found.
Zarko Cabarkapa
Results for Zarko Cabarkapa:

You searched for "Steven Hunter"
4 results found.
0: Steven Hunter
1: Steve Colter
2: Steve Hamer
3: Steven Kramer
Pick one: 0
Results for Steven Hunter:

You searched for "Jim Jackson"
21 results found.
0: Jim Jackson
1: Al Jackson
2: Josh Jackson
3: Mike Jackson
4: Phil Jackson
5: Jim Paxson
6: Jim Paxson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Tony Jackson
16: Tony Jackson
17: Sam Jacobson
18: Jim Wilson
19: Jim Eakins
20: Jim Chones
Pick one: 0
Results for Jim Jackson:

You searched for "Casey Jacobsen"
1 result found.
Casey Jacobsen
Results for Casey Jacobsen:

You searched for "Joe Johnson"
40 results found.
0: Joe Johnson
1: John Johnson
2: Lee Johnson
3: Ron Johnson
4: Dave Johnson
5: Ed Johnson
6: Gus Johnson
7: James Johnson
8: Ken Johnson
9: Ken Johnson
10: Stew Johnson
11: Trey Johnson
12: Joe Binion
13: Joe Dolhon
14: Alize Johnson
15: Amir Johnson
16: Andy Johnson
17: Armon Johnson
18: Arnie Johnson
19: Avery Johnson
20: B.J. Johnson
21: Brice Johnson
22: Buck Johnson
23: Clay Johnson
24: Eddie Johnson
25: Eddie Johnson
26: Eric Johnson
27: George Johnson
28: George Johnson
29: George Johnson
30: Ivan Johnson
31: Neil Johnson
32: Nick Johnson
33: Ollie Johnson
34: Rich Johnson
35: Steve Johnson
36: Tyler Johnson
37: Nate Johnston
38: Jim Johnstone
39: Joe Colone
Pick one: 0
Results for Joe Johnson:

You searched for "Maciej Lampe"
1 result found.
Maciej Lampe
Results for Maciej Lampe:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Walter McCarty"
1 result found.
Walter McCarty
Results for Walter McCarty:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Bo Outlaw"
5 results found.
0: Bo Outlaw
1: Ibo Kutluay
2: Bo Lamar
3: Bob Cousy
4: Bob Tough
Pick one: 0
Results for Bo Outlaw:

You searched for "Smush Parker"
2 results found.
0: Smush Parker
1: Sonny Parker
Pick one: 0
Results for Smush Parker:

You searched for "Quentin Richardson"
1 result found.
Quentin Richardson
Results for Quentin Richardson:

You searched for "Paul Shirley"
2 results found.
0: Paul Shirley
1: Paul Silas
Pick one: 0
Results for Paul Shirley:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "Yuta Tabuse"
1 result found.
Yuta Tabuse
Results for Yuta Tabuse:

You searched for "Jake Voskuhl"
1 result found.
Jake Voskuhl
Results for Jake Voskuhl:

You searched for "Jackson Vroman"
1 result found.
Jackson Vroman
Results for Jackson Vroman:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-01-02,22-047,PHO,HOME,POR,W (+19),1,41:11,20,27,...,11,3,1,1,1,3,50,43.2,25,Amar'e Stoudemire
1,2005-04-08,22-143,PHO,AWAY,GSW,L (-8),1,42:09,15,25,...,16,5,1,2,3,5,44,40.6,-4,Amar'e Stoudemire
2,2004-12-18,26-225,PHO,HOME,WAS,W (+14),1,43:40,13,18,...,14,2,6,1,1,2,36,40.3,16,Shawn Marion
3,2005-02-14,22-090,PHO,HOME,UTA,W (+8),1,39:52,14,22,...,12,2,3,2,2,4,42,38.4,11,Amar'e Stoudemire
4,2005-01-28,22-073,PHO,AWAY,BOS,W (+9),1,40:30,14,23,...,5,2,3,1,1,1,42,36.7,1,Amar'e Stoudemire

In [15]:

PHO_2006_gamelog = []

for p in PHO_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2006_gamelog.append(player_log)
PHO_2006_gamelog = pd.concat(PHO_2006_gamelog)    
PHO_2006_gamelogs = PHO_2006_gamelog.copy()
PHO_2006_gamelogs['GAME_SCORE'] = PHO_2006_gamelogs['GAME_SCORE'].astype(float)
PHO_2006_games = PHO_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2006_games_csv = PHO_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2006_games.csv', index=False)
PHO_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2006_games.csv')
PHO_2006_games_proc.head()

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Andre Barrett"
5 results found.
0: Andre Barrett
1: Ernie Barrett
2: Mike Barrett
3: RJ Barrett
4: Andre Emmett
Pick one: 0
Results for Andre Barrett:

You searched for "Raja Bell"
2 results found.
0: Raja Bell
1: Troy Bell
Pick one: 0
Results for Raja Bell:

You searched for "Pat Burke"
7 results found.
0: Pat Burke
1: Walt Budko
2: Trey Burke
3: Pat Dunn
4: Pat Durham
5: Pat Frink
6: Walt Kirk
Pick one: 0
Results for Pat Burke:

You searched for "Josh Davis"
27 results found.
0: Josh Davis
1: Bob Davis
2: Jim Davis
3: Ron Davis
4: Josh Reaves
5: Josh Hall
6: Bob Davies
7: Ben Davis
8: Bill Davis
9: Brad Davis
10: Dale Davis
11: Ed Davis
12: Glen Davis
13: Johnny Davis
14: Lee Davis
15: Mark Davis
16: Mark Davis
17: Mel Davis
18: Mike Davis
19: Mike Davis
20: Monti Davis
21: Paul Davis
22: Ralph Davis
23: Red Davis
24: Walt Davis
25: Josh Hart
26: Josh Grant
Pick one: 0
Results for Josh Davis:

You searched for "Boris Diaw"
1 result found.
Boris Diaw
Results for Boris Diaw:

You searched for "Sharrod Ford"
2 results found.
0: Sharrod Ford
1: Sherell Ford
Pick one: 0
Results for Sharrod Ford:

You searched for "Brian Grant"
9 results found.
0: Brian Grant
1: Jerian Grant
2: Brian Evans
3: Bud Grant
4: Greg Grant
5: Brian Heaney
6: Brian Shaw
7: Brian Bowen
8: Brian Martin
Pick one: 0
Results for Brian Grant:

You searched for "Eddie House"
6 results found.
0: Eddie House
1: Eddie Hughes
2: Eddie Jones
3: Eddie Mast
4: Eddie Miles
5: Eddie Owens
Pick one: 0
Results for Eddie House:

You searched for "Jim Jackson"
21 results found.
0: Jim Jackson
1: Al Jackson
2: Josh Jackson
3: Mike Jackson
4: Phil Jackson
5: Jim Paxson
6: Jim Paxson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Tony Jackson
16: Tony Jackson
17: Sam Jacobson
18: Jim Wilson
19: Jim Eakins
20: Jim Chones
Pick one: 0
Results for Jim Jackson:

You searched for "James Jones"
32 results found.
0: James Jones
1: Jake Jones
2: Jalen Jones
3: James Ennis
4: Damon Jones
5: Jimmy Jones
6: Sam Jones
7: James Posey
8: Tre Jones
9: Mason Jones
10: James Johnson
11: Charles Jones
12: Charles Jones
13: Charles Jones
14: Damian Jones
15: Earl Jones
16: Fred Jones
17: Larry Jones
18: Major Jones
19: Mark Jones
20: Mark Jones
21: Tyus Jones
22: Wali Jones
23: James Lang
24: James Silas
25: James Thomas
26: James Wilkes
27: James Young
28: James Cotton
29: James Scott
30: James Webb
31: James White
Pick one: 0
Results for James Jones:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "Kurt Thomas"
12 results found.
0: Kurt Thomas
1: Carl Thomas
2: Khyri Thomas
3: Matt Thomas
4: Etan Thomas
5: Jim Thomas
6: Joe Thomas
7: John Thomas
8: Kenny Thomas
9: Terry Thomas
10: Tim Thomas
11: Tyrus Thomas
Pick one: 0
Results for Kurt Thomas:

You searched for "Tim Thomas"
16 results found.
0: Tim Thomas
1: Jim Thomas
2: Etan Thomas
3: Joe Thomas
4: Jim Chones
5: Tim James
6: Billy Thomas
7: Carl Thomas
8: Isiah Thomas
9: Jamel Thomas
10: James Thomas
11: John Thomas
12: Kurt Thomas
13: Matt Thomas
14: Terry Thomas
15: Tyrus Thomas
Pick one: 0
Results for Tim Thomas:

You searched for "Dijon Thompson"
6 results found.
0: Dijon Thompson
1: Jason Thompson
2: John Thompson
3: Billy Thompson
4: David Thompson
5: Kevin Thompson
Pick one: 0
Results for Dijon Thompson:

You searched for "Nikoloz Tskitishvili"
1 result found.
Nikoloz Tskitishvili
Results for Nikoloz Tskitishvili:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-02-22,27-291,PHO,HOME,BOS,W (+9),1,43:02,15,22,...,15,0,4,3,2,3,44,44.8,7,Shawn Marion
1,2006-02-25,27-294,PHO,HOME,CHA,W (+15),1,42:38,11,19,...,24,3,1,2,2,1,31,32.6,18,Shawn Marion
2,2006-01-22,27-260,PHO,HOME,SEA,L (-3),1,53:27,15,30,...,10,4,1,5,1,5,37,32.1,-4,Shawn Marion
3,2006-03-30,27-327,PHO,AWAY,IND,W (+10),1,42:13,13,18,...,8,6,3,1,0,4,29,31.9,5,Shawn Marion
4,2006-01-02,27-240,PHO,AWAY,NYK,L (-7),1,60:06,15,26,...,14,1,1,1,1,5,39,31.6,-3,Shawn Marion

In [17]:


PHO_2007_gamelog = []

for p in PHO_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2007_gamelog.append(player_log)
PHO_2007_gamelog = pd.concat(PHO_2007_gamelog)    
PHO_2007_gamelogs = PHO_2007_gamelog.copy()
PHO_2007_gamelogs['GAME_SCORE'] = PHO_2007_gamelogs['GAME_SCORE'].astype(float)
PHO_2007_games = PHO_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2007_games_csv = PHO_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2007_games.csv', index=False)
PHO_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2007_games.csv')
PHO_2007_games_proc.head()

You searched for "Marcus Banks"
6 results found.
0: Marcus Banks
1: Marcus Brown
2: Marcus Camby
3: Marcus Landry
4: Marcus Paige
5: Marcus Smart
Pick one: 0
Results for Marcus Banks:

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Raja Bell"
2 results found.
0: Raja Bell
1: Troy Bell
Pick one: 0
Results for Raja Bell:

You searched for "Pat Burke"
7 results found.
0: Pat Burke
1: Walt Budko
2: Trey Burke
3: Pat Dunn
4: Pat Durham
5: Pat Frink
6: Walt Kirk
Pick one: 0
Results for Pat Burke:

You searched for "Boris Diaw"
1 result found.
Boris Diaw
Results for Boris Diaw:

You searched for "James Jones"
32 results found.
0: James Jones
1: Jake Jones
2: Jalen Jones
3: James Ennis
4: Damon Jones
5: Jimmy Jones
6: Sam Jones
7: James Posey
8: Tre Jones
9: Mason Jones
10: James Johnson
11: Charles Jones
12: Charles Jones
13: Charles Jones
14: Damian Jones
15: Earl Jones
16: Fred Jones
17: Larry Jones
18: Major Jones
19: Mark Jones
20: Mark Jones
21: Tyus Jones
22: Wali Jones
23: James Lang
24: James Silas
25: James Thomas
26: James Wilkes
27: James Young
28: James Cotton
29: James Scott
30: James Webb
31: James White
Pick one: 0
Results for James Jones:

You searched for "Jumaine Jones"
3 results found.
0: Jumaine Jones
1: Dwayne Jones
2: Jake Jones
Pick one: 0
Results for Jumaine Jones:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Sean Marks"
6 results found.
0: Sean Marks
1: Sean May
2: Sean Rooks
3: Sam Mack
4: Keon Clark
5: Stan Miasek
Pick one: 0
Results for Sean Marks:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Eric Piatkowski"
1 result found.
Eric Piatkowski
Results for Eric Piatkowski:

You searched for "Jalen Rose"
9 results found.
0: Jalen Rose
1: Jalen Jones
2: Malik Rose
3: Jaylen Brown
4: James Posey
5: Glen Rice
6: Glen Rice
7: Jalen Harris
8: Al Roges
Pick one: 0
Results for Jalen Rose:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "Kurt Thomas"
12 results found.
0: Kurt Thomas
1: Carl Thomas
2: Khyri Thomas
3: Matt Thomas
4: Etan Thomas
5: Jim Thomas
6: Joe Thomas
7: John Thomas
8: Kenny Thomas
9: Terry Thomas
10: Tim Thomas
11: Tyrus Thomas
Pick one: 0
Results for Kurt Thomas:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-02-25,24-101,PHO,AWAY,ATL,W (+9),1,44:33,14,25,...,16,6,0,3,1,3,43,42.0,17,Amar'e Stoudemire
1,2006-12-07,32-303,PHO,AWAY,NJN,W (+4),1,47:57,16,25,...,6,13,1,0,3,3,42,38.6,6,Steve Nash
2,2007-01-15,24-060,PHO,AWAY,MEM,W (+15),1,36:37,15,21,...,9,2,1,0,4,5,42,34.0,5,Amar'e Stoudemire
3,2006-12-31,32-327,PHO,AWAY,DET,W (+7),1,39:34,12,19,...,4,12,1,0,3,1,35,33.7,13,Steve Nash
4,2007-03-22,24-126,PHO,HOME,SAC,W (+18),1,36:40,12,17,...,21,2,2,3,2,3,33,33.7,24,Amar'e Stoudemire

In [20]:


PHO_2008_gamelog = []

for p in PHO_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2008_gamelog.append(player_log)
PHO_2008_gamelog = pd.concat(PHO_2008_gamelog)    
PHO_2008_gamelogs = PHO_2008_gamelog.copy()
PHO_2008_gamelogs['GAME_SCORE'] = PHO_2008_gamelogs['GAME_SCORE'].astype(float)
PHO_2008_games = PHO_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2008_games_csv = PHO_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2008_games.csv', index=False)
PHO_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2008_games.csv')
PHO_2008_games_proc.head()

You searched for "Marcus Banks"
6 results found.
0: Marcus Banks
1: Marcus Brown
2: Marcus Camby
3: Marcus Landry
4: Marcus Paige
5: Marcus Smart
Pick one: 0
Results for Marcus Banks:

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Raja Bell"
2 results found.
0: Raja Bell
1: Troy Bell
Pick one: 0
Results for Raja Bell:

You searched for "Boris Diaw"
1 result found.
Boris Diaw
Results for Boris Diaw:

You searched for "Gordan Giriček"
1 result found.
Gordan Giricek
Results for Gordan Giricek:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Linton Johnson"
9 results found.
0: Linton Johnson
1: Britton Johnsen
2: Anthony Johnson
3: Armon Johnson
4: Clemon Johnson
5: Ivan Johnson
6: Keldon Johnson
7: Ron Johnson
8: Vinnie Johnson
Pick one: 0
Results for Linton Johnson:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Sean Marks"
6 results found.
0: Sean Marks
1: Sean May
2: Sean Rooks
3: Sam Mack
4: Keon Clark
5: Stan Miasek
Pick one: 0
Results for Sean Marks:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Eric Piatkowski"
1 result found.
Eric Piatkowski
Results for Eric Piatkowski:

You searched for "Brian Skinner"
6 results found.
0: Brian Skinner
1: Brian Oliver
2: Brian Quinnett
3: Al Skinner
4: Tal Skinner
5: Brian Winters
Pick one: 0
Results for Brian Skinner:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "D.J. Strawberry"
1 result found.
D.J. Strawberry
Results for D.J. Strawberry:

You searched for "Alando Tucker"
2 results found.
0: Alando Tucker
1: Al Tucker
Pick one: 0
Results for Alando Tucker:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-03-31,25-136,PHO,HOME,DEN,W (+15),1,42:00,12,22,...,14,2,2,0,1,4,41,37.8,23,Amar'e Stoudemire
1,2007-12-04,25-018,PHO,AWAY,IND,W (+4),1,35:57,15,24,...,13,4,1,1,2,5,42,36.4,15,Amar'e Stoudemire
2,2008-03-22,25-127,PHO,HOME,HOU,W (+9),1,39:20,9,15,...,13,0,0,4,2,5,38,34.6,9,Amar'e Stoudemire
3,2008-03-31,34-053,PHO,HOME,DEN,W (+15),1,37:57,11,18,...,3,8,1,0,0,3,36,34.1,26,Steve Nash
4,2008-03-13,25-118,PHO,HOME,GSW,W (+8),1,39:42,13,21,...,11,4,0,4,1,2,36,34.0,13,Amar'e Stoudemire

In [28]:
# removed dee brown

PHO_2009_gamelog = []

for p in PHO_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2009_gamelog.append(player_log)
PHO_2009_gamelog = pd.concat(PHO_2009_gamelog)    
PHO_2009_gamelogs = PHO_2009_gamelog.copy()
PHO_2009_gamelogs['GAME_SCORE'] = PHO_2009_gamelogs['GAME_SCORE'].astype(float)
PHO_2009_games = PHO_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2009_games_csv = PHO_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2009_games.csv', index=False)
PHO_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2009_games.csv')
PHO_2009_games_proc.head()

You searched for "Lou Amundson"
2 results found.
0: Lou Amundson
1: Lou Hudson
Pick one: 0
Results for Lou Amundson:

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Raja Bell"
2 results found.
0: Raja Bell
1: Troy Bell
Pick one: 0
Results for Raja Bell:

You searched for "Boris Diaw"
1 result found.
Boris Diaw
Results for Boris Diaw:

You searched for "Goran Dragić"
2 results found.
0: Goran Dragic
1: Zoran Dragic
Pick one: 0
Results for Goran Dragic:

You searched for "Jared Dudley"
3 results found.
0: Jared Dudley
1: Charles Dudley
2: Chris Dudley
Pick one: 0
Results for Jared Dudley:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Robin Lopez"
4 results found.
0: Robin Lopez
1: Robin Jones
2: Brook Lopez
3: Raul Lopez
Pick one: 0
Results for Robin Lopez:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Courtney Sims"
2 results found.
0: Courtney Sims
1: Courtney Lee
Pick one: 0
Results for Courtney Sims:

You searched for "Sean Singletary"
1 result found.
Sean Singletary
Results for Sean Singletary:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "Stromile Swift"
1 result found.
Stromile Swift
Results for Stromile Swift:

You searched for "Alando Tucker"
2 results found.
0: Alando Tucker
1: Al Tucker
Pick one: 0
Results for Alando Tucker:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-11-05,25-355,PHO,AWAY,IND,W (+10),1,44:00,17,21,...,11,6,5,2,4,3,49,50.2,11,Amar'e Stoudemire
1,2009-02-20,26-084,PHO,HOME,OKC,W (+22),1,41:42,16,21,...,7,7,6,0,1,3,41,43.5,29,Leandro Barbosa
2,2009-02-18,26-094,PHO,AWAY,LAC,W (+23),1,36:09,15,20,...,11,1,0,0,1,3,42,37.4,38,Amar'e Stoudemire
3,2009-03-21,28-060,PHO,HOME,WAS,W (+32),1,37:07,13,18,...,7,3,1,2,2,1,35,31.8,30,Jason Richardson
4,2009-04-01,35-053,PHO,HOME,HOU,W (+5),1,38:47,9,15,...,1,17,3,0,1,1,25,31.1,18,Steve Nash

In [29]:

PHO_2010_gamelog = []

for p in PHO_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2010_gamelog.append(player_log)
PHO_2010_gamelog = pd.concat(PHO_2010_gamelog)    
PHO_2010_gamelogs = PHO_2010_gamelog.copy()
PHO_2010_gamelogs['GAME_SCORE'] = PHO_2010_gamelogs['GAME_SCORE'].astype(float)
PHO_2010_games = PHO_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2010_games_csv = PHO_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2010_games.csv', index=False)
PHO_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2010_games.csv')
PHO_2010_games_proc.head()

You searched for "Lou Amundson"
2 results found.
0: Lou Amundson
1: Lou Hudson
Pick one: 0
Results for Lou Amundson:

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Earl Clark"
7 results found.
0: Earl Clark
1: Gary Clark
2: Carlos Clark
3: Ian Clark
4: Keon Clark
5: Earl Evans
6: Earl Lloyd
Pick one: 0
Results for Earl Clark:

You searched for "Jarron Collins"
10 results found.
0: Jarron Collins
1: Jason Collins
2: Sherron Collins
3: Jason Collier
4: Art Collins
5: Don Collins
6: James Collins
7: John Collins
8: Mardy Collins
9: Darren Collison
Pick one: 0
Results for Jarron Collins:

You searched for "Goran Dragić"
2 results found.
0: Goran Dragic
1: Zoran Dragic
Pick one: 0
Results for Goran Dragic:

You searched for "Jared Dudley"
3 results found.
0: Jared Dudley
1: Charles Dudley
2: Chris Dudley
Pick one: 0
Results for Jared Dudley:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Taylor Griffin"
2 results found.
0: Taylor Griffin
1: Paul Griffin
Pick one: 0
Results for Taylor Griffin:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Dwayne Jones"
12 results found.
0: Dwayne Jones
1: Dwayne Polee
2: Damon Jones
3: Dwight Jones
4: Jake Jones
5: Jumaine Jones
6: Wali Jones
7: Wayne Molis
8: Wayne Yates
9: Dwayne Bacon
10: Dwayne Morton
11: Dwayne Sutton
Pick one: 0
Results for Dwayne Jones:

You searched for "Robin Lopez"
4 results found.
0: Robin Lopez
1: Robin Jones
2: Brook Lopez
3: Raul Lopez
Pick one: 0
Results for Robin Lopez:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Amar'e Stoudemire"
1 result found.
Amar'e Stoudemire
Results for Amar'e Stoudemire:

You searched for "Alando Tucker"
2 results found.
0: Alando Tucker
1: Al Tucker
Pick one: 0
Results for Alando Tucker:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-03-19,27-123,PHO,HOME,UTA,W (+10),1,35:08,14,16,...,7,0,1,2,5,4,44,36.3,15,Amar'e Stoudemire
1,2010-03-03,27-107,PHO,AWAY,LAC,W (+26),1,28:39,12,16,...,14,1,2,3,1,0,30,33.2,22,Amar'e Stoudemire
2,2009-12-26,35-322,PHO,AWAY,GSW,L (-5),1,36:24,14,22,...,4,9,2,0,4,2,36,31.3,-6,Steve Nash
3,2010-03-22,27-126,PHO,AWAY,GSW,W (+2),1,34:25,12,15,...,8,2,0,0,4,2,37,30.3,9,Amar'e Stoudemire
4,2010-03-14,27-118,PHO,HOME,NOH,W (+14),1,31:50,11,17,...,12,0,0,1,3,2,36,30.2,18,Amar'e Stoudemire

In [30]:

PHO_2011_gamelog = []

for p in PHO_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2011_gamelog.append(player_log)
PHO_2011_gamelog = pd.concat(PHO_2011_gamelog)    
PHO_2011_gamelogs = PHO_2011_gamelog.copy()
PHO_2011_gamelogs['GAME_SCORE'] = PHO_2011_gamelogs['GAME_SCORE'].astype(float)
PHO_2011_games = PHO_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2011_games_csv = PHO_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2011_games.csv', index=False)
PHO_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2011_games.csv')
PHO_2011_games_proc.head()

You searched for "Earl Barron"
10 results found.
0: Earl Barron
1: Earl Watson
2: Dana Barros
3: Will Barton
4: Carl Braun
5: Earl Cureton
6: Earl Monroe
7: Earl Shannon
8: Earl Gardner
9: Earl Jones
Pick one: 0
Results for Earl Barron:

You searched for "Aaron Brooks"
5 results found.
0: Aaron Brooks
1: MarShon Brooks
2: Dillon Brooks
3: Kevin Brooks
4: Aaron Gordon
Pick one: 0
Results for Aaron Brooks:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Josh Childress"
1 result found.
Josh Childress
Results for Josh Childress:

You searched for "Earl Clark"
7 results found.
0: Earl Clark
1: Gary Clark
2: Carlos Clark
3: Ian Clark
4: Keon Clark
5: Earl Evans
6: Earl Lloyd
Pick one: 0
Results for Earl Clark:

You searched for "Zabian Dowdell"
1 result found.
Zabian Dowdell
Results for Zabian Dowdell:

You searched for "Goran Dragić"
2 results found.
0: Goran Dragic
1: Zoran Dragic
Pick one: 0
Results for Goran Dragic:

You searched for "Jared Dudley"
3 results found.
0: Jared Dudley
1: Charles Dudley
2: Chris Dudley
Pick one: 0
Results for Jared Dudley:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Marcin Gortat"
1 result found.
Marcin Gortat
Results for Marcin Gortat:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Gani Lawal"
1 result found.
Gani Lawal
Results for Gani Lawal:

You searched for "Robin Lopez"
4 results found.
0: Robin Lopez
1: Robin Jones
2: Brook Lopez
3: Raul Lopez
Pick one: 0
Results for Robin Lopez:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "Jason Richardson"
3 results found.
0: Jason Richardson
1: Josh Richardson
2: Pooh Richardson
Pick one: 0
Results for Jason Richardson:

You searched for "Garret Siler"
1 result found.
Garret Siler
Results for Garret Siler:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

You searched for "Hakim Warrick"
1 result found.
Hakim Warrick
Results for Hakim Warrick:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-11-28,29-312,PHO,AWAY,DEN,L (-5),1,36:10,15,24,...,10,3,1,1,1,2,39,34.8,-11,Jason Richardson
1,2011-01-26,36-353,PHO,HOME,CHA,L (-7),1,36:01,11,15,...,5,15,1,0,2,0,27,32.7,-7,Steve Nash
2,2010-12-23,25-166,PHO,HOME,MIA,L (-12),1,41:33,11,16,...,12,0,3,0,2,1,33,31.6,-3,Jared Dudley
3,2010-11-12,36-278,PHO,HOME,SAC,W (+14),1,35:26,13,18,...,7,14,1,0,2,0,28,31.1,14,Steve Nash
4,2010-11-14,29-298,PHO,AWAY,LAL,W (+5),1,35:50,13,20,...,8,3,3,0,2,2,35,30.9,8,Jason Richardson

In [31]:


PHO_2012_gamelog = []

for p in PHO_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2012_gamelog.append(player_log)
PHO_2012_gamelog = pd.concat(PHO_2012_gamelog)    
PHO_2012_gamelogs = PHO_2012_gamelog.copy()
PHO_2012_gamelogs['GAME_SCORE'] = PHO_2012_gamelogs['GAME_SCORE'].astype(float)
PHO_2012_games = PHO_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2012_games_csv = PHO_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2012_games.csv', index=False)
PHO_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2012_games.csv')
PHO_2012_games_proc.head()

You searched for "Shannon Brown"
2 results found.
0: Shannon Brown
1: Stan Brown
Pick one: 0
Results for Shannon Brown:

You searched for "Josh Childress"
1 result found.
Josh Childress
Results for Josh Childress:

You searched for "Jared Dudley"
3 results found.
0: Jared Dudley
1: Charles Dudley
2: Chris Dudley
Pick one: 0
Results for Jared Dudley:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Marcin Gortat"
1 result found.
Marcin Gortat
Results for Marcin Gortat:

You searched for "Grant Hill"
8 results found.
0: Grant Hill
1: Grant Riller
2: Gary Hill
3: Craig Dill
4: Armond Hill
5: Jordan Hill
6: Tyrone Hill
7: Grant Long
Pick one: 0
Results for Grant Hill:

You searched for "Robin Lopez"
4 results found.
0: Robin Lopez
1: Robin Jones
2: Brook Lopez
3: Raul Lopez
Pick one: 0
Results for Robin Lopez:

You searched for "Markieff Morris"
1 result found.
Markieff Morris
Results for Markieff Morris:

You searched for "Steve Nash"
14 results found.
0: Steve Nash
1: Steve Bardo
2: Steve Blake
3: Steve Hamer
4: Steve Hawes
5: Steve Hayes
6: Steve Jones
7: Steve Kerr
8: Steve Mix
9: Steve Novak
10: Steve Smith
11: Steven Adams
12: Steve Green
13: Steve Harris
Pick one: 0
Results for Steve Nash:

You searched for "Ronnie Price"
5 results found.
0: Ronnie Price
1: Donnie Boyce
2: Ronnie Brewer
3: Tony Price
4: Connie Rea
Pick one: 0
Results for Ronnie Price:

You searched for "Michael Redd"
5 results found.
0: Michael Redd
1: Michael Cage
2: Michael Curry
3: Michael Porter
4: Michael Wiley
Pick one: 0
Results for Michael Redd:

You searched for "Sebastian Telfair"
1 result found.
Sebastian Telfair
Results for Sebastian Telfair:

You searched for "Hakim Warrick"
1 result found.
Hakim Warrick
Results for Hakim Warrick:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-02-01,37-359,PHO,AWAY,NOH,W (+17),1,28:53,13,16,...,2,10,1,1,1,1,30,31.9,29,Steve Nash
1,2012-01-18,37-345,PHO,AWAY,NYK,W (+3),1,37:36,9,12,...,5,11,0,0,3,0,26,27.4,4,Steve Nash
2,2012-03-27,26-119,PHO,HOME,SAS,L (-7),1,42:06,11,18,...,1,3,0,0,0,0,32,26.2,-1,Shannon Brown
3,2012-03-12,26-246,PHO,HOME,MIN,L (-3),1,36:13,10,15,...,9,1,1,1,1,1,28,26.0,1,Jared Dudley
4,2012-03-12,38-034,PHO,HOME,MIN,L (-3),1,32:20,10,16,...,3,10,0,0,0,2,25,25.3,1,Steve Nash

In [34]:
# removed jermaine o'neakl 
PHO_2013_gamelog = []

for p in PHO_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2013_gamelog.append(player_log)
PHO_2013_gamelog = pd.concat(PHO_2013_gamelog)    
PHO_2013_gamelogs = PHO_2013_gamelog.copy()
PHO_2013_gamelogs['GAME_SCORE'] = PHO_2013_gamelogs['GAME_SCORE'].astype(float)
PHO_2013_games = PHO_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2013_games_csv = PHO_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2013_games.csv', index=False)
PHO_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2013_games.csv')
PHO_2013_games_proc.head()

You searched for "Michael Beasley"
5 results found.
0: Michael Beasley
1: Michael Bradley
2: Michael Ansley
3: Michael Finley
4: Michael Wiley
Pick one: 0
Results for Michael Beasley:

You searched for "Shannon Brown"
2 results found.
0: Shannon Brown
1: Stan Brown
Pick one: 0
Results for Shannon Brown:

You searched for "Goran Dragić"
2 results found.
0: Goran Dragic
1: Zoran Dragic
Pick one: 0
Results for Goran Dragic:

You searched for "Jared Dudley"
3 results found.
0: Jared Dudley
1: Charles Dudley
2: Chris Dudley
Pick one: 0
Results for Jared Dudley:

You searched for "Diante Garrett"
3 results found.
0: Diante Garrett
1: Dean Garrett
2: Dick Garrett
Pick one: 0
Results for Diante Garrett:

You searched for "Marcin Gortat"
1 result found.
Marcin Gortat
Results for Marcin Gortat:

You searched for "Hamed Haddadi"
1 result found.
Hamed Haddadi
Results for Hamed Haddadi:

You searched for "Wesley Johnson"
10 results found.
0: Wesley Johnson
1: Clay Johnson
2: Lee Johnson
3: Mickey Johnson
4: Neil Johnson
5: Stanley Johnson
6: Stew Johnson
7: Trey Johnson
8: Tyler Johnson
9: Wesley Person
Pick one: 0
Results for Wesley Johnson:

You searched for "Kendall Marshall"
2 results found.
0: Kendall Marshall
1: Donyell Marshall
Pick one: 0
Results for Kendall Marshall:

You searched for "Marcus Morris"
5 results found.
0: Marcus Morris
1: Darius Morris
2: Marcus Cousin
3: Chris Morris
4: Max Morris
Pick one: 0
Results for Marcus Morris:

You searched for "Markieff Morris"
1 result found.
Markieff Morris
Results for Markieff Morris:

You searched for "Luis Scola"
1 result found.
Luis Scola
Results for Luis Scola:

You searched for "Sebastian Telfair"
1 result found.
Sebastian Telfair
Results for Sebastian Telfair:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

You searched for "Luke Zeller"
7 results found.
0: Luke Zeller
1: Dave Zeller
2: Ken Keller
3: Mike Miller
4: Cody Zeller
5: Gary Zeller
6: Tyler Zeller
Pick one: 0
Results for Luke Zeller:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-12-26,27-169,PHO,HOME,NYK,L (-2),1,42:07,11,17,...,5,3,1,0,3,2,36,29.3,2,Jared Dudley
1,2012-12-29,32-243,PHO,AWAY,MIN,L (-4),1,43:06,16,26,...,10,2,1,2,0,3,33,27.6,-5,Luis Scola
2,2013-03-24,26-322,PHO,HOME,BRK,L (-2),1,38:17,10,19,...,9,12,0,0,4,4,31,27.6,3,Goran Dragić
3,2013-04-05,26-334,PHO,HOME,GSW,L (-4),1,43:24,11,13,...,2,3,1,0,5,1,32,25.6,2,Goran Dragić
4,2012-11-07,28-264,PHO,AWAY,CHA,W (+7),1,38:19,10,14,...,10,2,1,7,1,5,23,25.3,9,Marcin Gortat

In [35]:


PHO_2014_gamelog = []

for p in PHO_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2014_gamelog.append(player_log)
PHO_2014_gamelog = pd.concat(PHO_2014_gamelog)    
PHO_2014_gamelogs = PHO_2014_gamelog.copy()
PHO_2014_gamelogs['GAME_SCORE'] = PHO_2014_gamelogs['GAME_SCORE'].astype(float)
PHO_2014_games = PHO_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2014_games_csv = PHO_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2014_games.csv', index=False)
PHO_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2014_games.csv')
PHO_2014_games_proc.head()

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Eric Bledsoe"
1 result found.
Eric Bledsoe
Results for Eric Bledsoe:

You searched for "Dionte Christmas"
1 result found.
Dionte Christmas
Results for Dionte Christmas:

You searched for "Goran Dragić"
2 results found.
0: Goran Dragic
1: Zoran Dragic
Pick one: 0
Results for Goran Dragic:

You searched for "Channing Frye"
1 result found.
Channing Frye
Results for Channing Frye:

You searched for "Archie Goodwin"
1 result found.
Archie Goodwin
Results for Archie Goodwin:

You searched for "Gerald Green"
6 results found.
0: Gerald Green
1: Gerald Brown
2: Gerald Govan
3: Gerald Glass
4: Erick Green
5: Sean Green
Pick one: 0
Results for Gerald Green:

You searched for "Viacheslav Kravtsov"
1 result found.
Viacheslav Kravtsov
Results for Viacheslav Kravtsov:

You searched for "Alex Len"
7 results found.
0: Alex Len
1: Saben Lee
2: Alex Acker
3: Alex Kirk
4: Greg Lee
5: Alex Scales
6: Hal Hale
Pick one: 0
Results for Alex Len:

You searched for "Marcus Morris"
5 results found.
0: Marcus Morris
1: Darius Morris
2: Marcus Cousin
3: Chris Morris
4: Max Morris
Pick one: 0
Results for Marcus Morris:

You searched for "Markieff Morris"
1 result found.
Markieff Morris
Results for Markieff Morris:

You searched for "Miles Plumlee"
2 results found.
0: Miles Plumlee
1: Mason Plumlee
Pick one: 0
Results for Miles Plumlee:

You searched for "Shavlik Randolph"
1 result found.
Shavlik Randolph
Results for Shavlik Randolph:

You searched for "Ish Smith"
34 results found.
0: Ish Smith
1: Josh Smith
2: Al Smith
3: Bill Smith
4: Deb Smith
5: Don Smith
6: Don Smith
7: Ed Smith
8: Jim Smith
9: Joe Smith
10: John Smith
11: Keith Smith
12: Ken Smith
13: Mike Smith
14: Otis Smith
15: Russ Smith
16: Sam Smith
17: Sam Smith
18: Bingo Smith
19: Chris Smith
20: Chris Smith
21: Doug Smith
22: Greg Smith
23: Greg Smith
24: J.R. Smith
25: Jason Smith
26: Leon Smith
27: Pete Smith
28: Phil Smith
29: Tony Smith
30: Rik Smits
31: Joe Smyth
32: Sam Stith
33: Tom Stith
Pick one: 0
Results for Ish Smith:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-02-08,27-278,PHO,HOME,GSW,W (+13),1,40:00,10,13,...,2,10,2,0,3,3,34,33.5,19,Goran Dragić
1,2014-03-06,28-039,PHO,HOME,OKC,W (+6),1,40:44,12,22,...,5,2,3,1,3,3,41,32.0,11,Gerald Green
2,2014-02-28,27-298,PHO,HOME,NOP,W (+12),1,41:43,14,21,...,3,5,0,0,3,3,40,31.1,14,Goran Dragić
3,2013-12-13,24-004,PHO,HOME,SAC,W (+9),1,35:04,11,16,...,5,8,3,2,3,2,28,28.9,8,Eric Bledsoe
4,2014-04-11,24-123,PHO,AWAY,SAS,L (-8),1,37:17,11,16,...,11,9,3,0,7,2,30,28.0,1,Eric Bledsoe

In [36]:


PHO_2015_gamelog = []

for p in PHO_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2015_gamelog.append(player_log)
PHO_2015_gamelog = pd.concat(PHO_2015_gamelog)    
PHO_2015_gamelogs = PHO_2015_gamelog.copy()
PHO_2015_gamelogs['GAME_SCORE'] = PHO_2015_gamelogs['GAME_SCORE'].astype(float)
PHO_2015_games = PHO_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2015_games_csv = PHO_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2015_games.csv', index=False)
PHO_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2015_games.csv')
PHO_2015_games_proc.head()

You searched for "Earl Barron"
10 results found.
0: Earl Barron
1: Earl Watson
2: Dana Barros
3: Will Barton
4: Carl Braun
5: Earl Cureton
6: Earl Monroe
7: Earl Shannon
8: Earl Gardner
9: Earl Jones
Pick one: 0
Results for Earl Barron:

You searched for "Eric Bledsoe"
1 result found.
Eric Bledsoe
Results for Eric Bledsoe:

You searched for "Reggie Bullock"
1 result found.
Reggie Bullock
Results for Reggie Bullock:

You searched for "Seth Curry"
4 results found.
0: Seth Curry
1: Dell Curry
2: Eddy Curry
3: Stephen Curry
Pick one: 0
Results for Seth Curry:

You searched for "Goran Dragić"
2 results found.
0: Goran Dragic
1: Zoran Dragic
Pick one: 0
Results for Goran Dragic:

You searched for "Zoran Dragić"
2 results found.
0: Zoran Dragic
1: Goran Dragic
Pick one: 0
Results for Zoran Dragic:

You searched for "Tyler Ennis"
6 results found.
0: Tyler Ennis
1: Tyler Davis
2: Tyler Ulis
3: James Ennis
4: Tyler Herro
5: Tyler Lydon
Pick one: 0
Results for Tyler Ennis:

You searched for "Archie Goodwin"
1 result found.
Archie Goodwin
Results for Archie Goodwin:

You searched for "Gerald Green"
6 results found.
0: Gerald Green
1: Gerald Brown
2: Gerald Govan
3: Gerald Glass
4: Erick Green
5: Sean Green
Pick one: 0
Results for Gerald Green:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "Alex Len"
7 results found.
0: Alex Len
1: Saben Lee
2: Alex Acker
3: Alex Kirk
4: Greg Lee
5: Alex Scales
6: Hal Hale
Pick one: 0
Results for Alex Len:

You searched for "Jerel McNeal"
1 result found.
Jerel McNeal
Results for Jerel McNeal:

You searched for "Marcus Morris"
5 results found.
0: Marcus Morris
1: Darius Morris
2: Marcus Cousin
3: Chris Morris
4: Max Morris
Pick one: 0
Results for Marcus Morris:

You searched for "Markieff Morris"
1 result found.
Markieff Morris
Results for Markieff Morris:

You searched for "Miles Plumlee"
2 results found.
0: Miles Plumlee
1: Mason Plumlee
Pick one: 0
Results for Miles Plumlee:

You searched for "A.J. Price"
6 results found.
0: A.J. Price
1: Jim Price
2: Mark Price
3: Mike Price
4: Tony Price
5: D.J. White
Pick one: 0
Results for A.J. Price:

You searched for "Shavlik Randolph"
1 result found.
Shavlik Randolph
Results for Shavlik Randolph:

You searched for "Isaiah Thomas"
5 results found.
0: Isaiah Thomas
1: Isiah Thomas
2: Isaiah Hicks
3: Irving Thomas
4: Isaiah Taylor
Pick one: 0
Results for Isaiah Thomas:

You searched for "Marcus Thornton"
2 results found.
0: Marcus Thornton
1: Dallas Thornton
Pick one: 0
Results for Marcus Thornton:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

You searched for "T.J. Warren"
5 results found.
0: T.J. Warren
1: J.J. Barea
2: Bob Warren
3: John Warren
4: C.J. Watson
Pick one: 0
Results for T.J. Warren:

You searched for "Brandan Wright"
5 results found.
0: Brandan Wright
1: Brandin Knight
2: Brandon Knight
3: Brad Wright
4: Bracey Wright
Pick one: 0
Results for Brandan Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-12-02,28-210,PHO,HOME,IND,W (+17),1,35:12,11,15,...,5,3,4,0,3,2,34,31.7,24,Goran Dragić
1,2015-03-21,25-102,PHO,AWAY,HOU,W (+15),1,36:37,11,18,...,8,4,3,1,3,2,34,31.3,22,Eric Bledsoe
2,2014-12-08,24-364,PHO,AWAY,LAC,L (-1),1,45:22,8,16,...,11,16,2,2,5,4,27,30.7,-3,Eric Bledsoe
3,2014-12-05,28-213,PHO,AWAY,DAL,W (+12),1,37:27,10,15,...,2,13,0,1,1,1,28,30.1,15,Goran Dragić
4,2014-11-17,25-076,PHO,AWAY,BOS,W (+4),1,39:17,14,21,...,7,5,4,0,1,3,30,28.3,11,Markieff Morris

In [37]:


PHO_2016_gamelog = []

for p in PHO_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2016_gamelog.append(player_log)
PHO_2016_gamelog = pd.concat(PHO_2016_gamelog)    
PHO_2016_gamelogs = PHO_2016_gamelog.copy()
PHO_2016_gamelogs['GAME_SCORE'] = PHO_2016_gamelogs['GAME_SCORE'].astype(float)
PHO_2016_games = PHO_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2016_games_csv = PHO_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2016_games.csv', index=False)
PHO_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2016_games.csv')
PHO_2016_games_proc.head()

You searched for "Eric Bledsoe"
1 result found.
Eric Bledsoe
Results for Eric Bledsoe:

You searched for "Devin Booker"
11 results found.
0: Devin Booker
1: Melvin Booker
2: Vin Baker
3: Trevor Booker
4: Kevin Brooks
5: Devin Brown
6: David Cooke
7: Kevin Loder
8: Kevin Porter
9: Kevin Porter
10: Devin Ebanks
Pick one: 0
Results for Devin Booker:

You searched for "Lorenzo Brown"
2 results found.
0: Lorenzo Brown
1: Lorenzo Romar
Pick one: 0
Results for Lorenzo Brown:

You searched for "Chase Budinger"
1 result found.
Chase Budinger
Results for Chase Budinger:

You searched for "Tyson Chandler"
3 results found.
0: Tyson Chandler
1: Wilson Chandler
2: Tyson Wheeler
Pick one: 0
Results for Tyson Chandler:

You searched for "Bryce Cotton"
2 results found.
0: Bryce Cotton
1: Jack Cotton
Pick one: 0
Results for Bryce Cotton:

You searched for "Archie Goodwin"
1 result found.
Archie Goodwin
Results for Archie Goodwin:

You searched for "Kris Humphries"
2 results found.
0: Kris Humphries
1: Jay Humphries
Pick one: 0
Results for Kris Humphries:

You searched for "Cory Jefferson"
2 results found.
0: Cory Jefferson
1: Al Jefferson
Pick one: 0
Results for Cory Jefferson:

You searched for "John Jenkins"
5 results found.
0: John Jenkins
1: John Collins
2: John Henson
3: John Johnson
4: John Mahnken
Pick one: 0
Results for John Jenkins:

You searched for "Orlando Johnson"
3 results found.
0: Orlando Johnson
1: Andy Johnson
2: Frank Johnson
Pick one: 0
Results for Orlando Johnson:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "Alex Len"
7 results found.
0: Alex Len
1: Saben Lee
2: Alex Acker
3: Alex Kirk
4: Greg Lee
5: Alex Scales
6: Hal Hale
Pick one: 0
Results for Alex Len:

You searched for "Jon Leuer"
18 results found.
0: Jon Leuer
1: Ron Lee
2: Jon Teske
3: Ron Baker
4: Ron Brewer
5: John Coker
6: Don Dee
7: Fat Lever
8: Ron Mercer
9: Ron Reed
10: Von Wafer
11: Joe DePre
12: John Drew
13: Joe Kleine
14: John Long
15: John Olive
16: Ron Riley
17: John Wall
Pick one: 0
Results for Jon Leuer:

You searched for "Jordan McRae"
9 results found.
0: Jordan McRae
1: Jordan Nwora
2: Jordan Ford
3: Jordan Bone
4: Jordan Farmar
5: Jordan Mickey
6: Jordan Poole
7: Jordan Adams
8: Jordan Bell
Pick one: 0
Results for Jordan McRae:

You searched for "Markieff Morris"
1 result found.
Markieff Morris
Results for Markieff Morris:

You searched for "Phil Pressey"
2 results found.
0: Phil Pressey
1: Paul Pressey
Pick one: 0
Results for Phil Pressey:

You searched for "Ronnie Price"
5 results found.
0: Ronnie Price
1: Donnie Boyce
2: Ronnie Brewer
3: Tony Price
4: Connie Rea
Pick one: 0
Results for Ronnie Price:

You searched for "Mirza Teletović"
1 result found.
Mirza Teletovic
Results for Mirza Teletovic:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

You searched for "T.J. Warren"
5 results found.
0: T.J. Warren
1: J.J. Barea
2: Bob Warren
3: John Warren
4: C.J. Watson
Pick one: 0
Results for T.J. Warren:

You searched for "Sonny Weems"
1 result found.
Sonny Weems
Results for Sonny Weems:

You searched for "Alan Williams"
49 results found.
0: Alan Williams
1: Al Williams
2: Alvin Williams
3: Sean Williams
4: Aaron Williams
5: Art Williams
6: Fly Williams
7: Frank Williams
8: Grant Williams
9: Hank Williams
10: Jason Williams
11: Jawad Williams
12: Jay Williams
13: John Williams
14: Lou Williams
15: Ray Williams
16: Ron Williams
17: Sam Williams
18: Sam Williams
19: Sly Williams
20: Walt Williams
21: Bob Williams
22: Buck Williams
23: C.J. Williams
24: Cliff Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Eric Williams
29: Gene Williams
30: Gus Williams
31: Guy Williams
32: Herb Williams
33: Jayson Williams
34: Jordan Williams
35: Kenny Williams
36: Kevin Williams
37: Marvin Williams
38: Matt Williams
39: Mike Williams
40: Milt Williams
41: Mo Williams
42: Nate Williams
43: Pete Williams
44: Rob Williams
45: Shawne Williams
46: Troy Williams
47: Ward Williams
48: Armen Gilliam
Pick one: 0
Results for Alan Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-11-20,23-353,PHO,AWAY,DEN,W (+7),1,36:19,11,20,...,11,6,2,1,5,1,38,34.0,10,Brandon Knight
1,2015-11-16,23-349,PHO,HOME,LAL,W (+19),1,40:47,11,23,...,10,15,4,0,2,3,30,33.0,21,Brandon Knight
2,2015-10-31,25-326,PHO,AWAY,POR,W (+11),1,38:23,12,21,...,3,6,4,2,2,1,33,30.4,11,Eric Bledsoe
3,2015-12-31,22-117,PHO,AWAY,OKC,L (-4),1,40:54,11,17,...,9,3,4,0,0,3,29,29.5,-8,T.J. Warren
4,2015-11-25,23-358,PHO,HOME,NOP,L (-6),1,42:23,10,21,...,4,10,4,0,1,1,29,28.3,-1,Brandon Knight

In [40]:
# removed Derrick Jones

PHO_2017_gamelog = []

for p in PHO_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2017_gamelog.append(player_log)
PHO_2017_gamelog = pd.concat(PHO_2017_gamelog)    
PHO_2017_gamelogs = PHO_2017_gamelog.copy()
PHO_2017_gamelogs['GAME_SCORE'] = PHO_2017_gamelogs['GAME_SCORE'].astype(float)
PHO_2017_games = PHO_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2017_games_csv = PHO_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2017_games.csv', index=False)
PHO_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2017_games.csv')
PHO_2017_games_proc.head()

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Dragan Bender"
1 result found.
Dragan Bender
Results for Dragan Bender:

You searched for "Eric Bledsoe"
1 result found.
Eric Bledsoe
Results for Eric Bledsoe:

You searched for "Devin Booker"
11 results found.
0: Devin Booker
1: Melvin Booker
2: Vin Baker
3: Trevor Booker
4: Kevin Brooks
5: Devin Brown
6: David Cooke
7: Kevin Loder
8: Kevin Porter
9: Kevin Porter
10: Devin Ebanks
Pick one: 0
Results for Devin Booker:

You searched for "Tyson Chandler"
3 results found.
0: Tyson Chandler
1: Wilson Chandler
2: Tyson Wheeler
Pick one: 0
Results for Tyson Chandler:

You searched for "Marquese Chriss"
1 result found.
Marquese Chriss
Results for Marquese Chriss:

You searched for "Jared Dudley"
3 results found.
0: Jared Dudley
1: Charles Dudley
2: Chris Dudley
Pick one: 0
Results for Jared Dudley:

You searched for "Jarell Eddie"
1 result found.
Jarell Eddie
Results for Jarell Eddie:

You searched for "John Jenkins"
5 results found.
0: John Jenkins
1: John Collins
2: John Henson
3: John Johnson
4: John Mahnken
Pick one: 0
Results for John Jenkins:

You searched for "Brandon Knight"
5 results found.
0: Brandon Knight
1: Brandin Knight
2: Brandan Wright
3: Brevin Knight
4: Ron Knight
Pick one: 0
Results for Brandon Knight:

You searched for "Alex Len"
7 results found.
0: Alex Len
1: Saben Lee
2: Alex Acker
3: Alex Kirk
4: Greg Lee
5: Alex Scales
6: Hal Hale
Pick one: 0
Results for Alex Len:

You searched for "Elijah Millsap"
1 result found.
Elijah Millsap
Results for Elijah Millsap:

You searched for "Ronnie Price"
5 results found.
0: Ronnie Price
1: Donnie Boyce
2: Ronnie Brewer
3: Tony Price
4: Connie Rea
Pick one: 0
Results for Ronnie Price:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

You searched for "Tyler Ulis"
5 results found.
0: Tyler Ulis
1: Tyler Davis
2: Tyler Ennis
3: Tyler Bey
4: Tyler Cook
Pick one: 0
Results for Tyler Ulis:

You searched for "T.J. Warren"
5 results found.
0: T.J. Warren
1: J.J. Barea
2: Bob Warren
3: John Warren
4: C.J. Watson
Pick one: 0
Results for T.J. Warren:

You searched for "Alan Williams"
49 results found.
0: Alan Williams
1: Al Williams
2: Alvin Williams
3: Sean Williams
4: Aaron Williams
5: Art Williams
6: Fly Williams
7: Frank Williams
8: Grant Williams
9: Hank Williams
10: Jason Williams
11: Jawad Williams
12: Jay Williams
13: John Williams
14: Lou Williams
15: Ray Williams
16: Ron Williams
17: Sam Williams
18: Sam Williams
19: Sly Williams
20: Walt Williams
21: Bob Williams
22: Buck Williams
23: C.J. Williams
24: Cliff Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Eric Williams
29: Gene Williams
30: Gus Williams
31: Guy Williams
32: Herb Williams
33: Jayson Williams
34: Jordan Williams
35: Kenny Williams
36: Kevin Williams
37: Marvin Williams
38: Matt Williams
39: Mike Williams
40: Milt Williams
41: Mo Williams
42: Nate Williams
43: Pete Williams
44: Rob Williams
45: Shawne Williams
46: Troy Williams
47: Ward Williams
48: Armen Gilliam
Pick one: 0
Results for Alan Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-03-24,20-145,PHO,AWAY,BOS,L (-10),1,44:58,21,40,...,8,6,3,1,5,3,70,54.5,-6,Devin Booker
1,2017-01-22,27-044,PHO,AWAY,TOR,W (+12),1,41:45,11,17,...,6,13,0,0,4,3,40,38.2,23,Eric Bledsoe
2,2017-01-28,27-050,PHO,HOME,DEN,L (-11),1,45:17,12,27,...,6,7,2,0,3,3,41,31.8,-9,Eric Bledsoe
3,2016-12-09,27-000,PHO,AWAY,LAL,W (+4),1,32:35,10,18,...,4,9,3,1,1,0,30,31.2,18,Eric Bledsoe
4,2017-04-02,21-087,PHO,HOME,HOU,L (-7),1,45:13,15,22,...,9,9,1,0,4,4,34,29.8,-3,Tyler Ulis

In [46]:
# removed mike james
# removed derrick jones

PHO_2018_gamelog = []

for p in PHO_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2018_gamelog.append(player_log)
PHO_2018_gamelog = pd.concat(PHO_2018_gamelog)    
PHO_2018_gamelogs = PHO_2018_gamelog.copy()
PHO_2018_gamelogs['GAME_SCORE'] = PHO_2018_gamelogs['GAME_SCORE'].astype(float)
PHO_2018_games = PHO_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2018_games_csv = PHO_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2018_games.csv', index=False)
PHO_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2018_games.csv')
PHO_2018_games_proc.head()

You searched for "Dragan Bender"
1 result found.
Dragan Bender
Results for Dragan Bender:

You searched for "Eric Bledsoe"
1 result found.
Eric Bledsoe
Results for Eric Bledsoe:

You searched for "Devin Booker"
11 results found.
0: Devin Booker
1: Melvin Booker
2: Vin Baker
3: Trevor Booker
4: Kevin Brooks
5: Devin Brown
6: David Cooke
7: Kevin Loder
8: Kevin Porter
9: Kevin Porter
10: Devin Ebanks
Pick one: 0
Results for Devin Booker:

You searched for "Isaiah Canaan"
1 result found.
Isaiah Canaan
Results for Isaiah Canaan:

You searched for "Tyson Chandler"
3 results found.
0: Tyson Chandler
1: Wilson Chandler
2: Tyson Wheeler
Pick one: 0
Results for Tyson Chandler:

You searched for "Marquese Chriss"
1 result found.
Marquese Chriss
Results for Marquese Chriss:

You searched for "Troy Daniels"
4 results found.
0: Troy Daniels
1: Erik Daniels
2: Lloyd Daniels
3: Mel Daniels
Pick one: 0
Results for Troy Daniels:

You searched for "Jared Dudley"
3 results found.
0: Jared Dudley
1: Charles Dudley
2: Chris Dudley
Pick one: 0
Results for Jared Dudley:

You searched for "Josh Gray"
10 results found.
0: Josh Gray
1: Josh Grant
2: Josh Green
3: Josh Hall
4: Ed Gray
5: Gary Gray
6: Josh Hart
7: Don Ray
8: Jim Ray
9: Josh Selby
Pick one: 0
Results for Josh Gray:

You searched for "Shaquille Harrison"
1 result found.
Shaquille Harrison
Results for Shaquille Harrison:

You searched for "Danuel House"
2 results found.
0: Danuel House
1: Daniel Theis
Pick one: 0
Results for Danuel House:

You searched for "Josh Jackson"
18 results found.
0: Josh Jackson
1: Jim Jackson
2: Tony Jackson
3: Tony Jackson
4: John Dickson
5: Al Jackson
6: Bobby Jackson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Mike Jackson
16: Phil Jackson
17: Ralph Jackson
Pick one: 0
Results for Josh Jackson:

You searched for "Alex Len"
7 results found.
0: Alex Len
1: Saben Lee
2: Alex Acker
3: Alex Kirk
4: Greg Lee
5: Alex Scales
6: Hal Hale
Pick one: 0
Results for Alex Len:

You searched for "Greg Monroe"
7 results found.
0: Greg Monroe
1: Greg Minor
2: Earl Monroe
3: Greg Foster
4: Greg Howard
5: Greg Oden
6: Greg Sutton
Pick one: 0
Results for Greg Monroe:

You searched for "Elfrid Payton"
1 result found.
Elfrid Payton
Results for Elfrid Payton:

You searched for "Alec Peters"
2 results found.
0: Alec Peters
1: Alec Kessler
Pick one: 0
Results for Alec Peters:

You searched for "Davon Reed"
9 results found.
0: Davon Reed
1: Ron Reed
2: Don Reid
3: Paul Reed
4: Don Dee
5: Devin Green
6: Damion Lee
7: David Lee
8: David Lee
Pick one: 0
Results for Davon Reed:

You searched for "Tyler Ulis"
5 results found.
0: Tyler Ulis
1: Tyler Davis
2: Tyler Ennis
3: Tyler Bey
4: Tyler Cook
Pick one: 0
Results for Tyler Ulis:

You searched for "T.J. Warren"
5 results found.
0: T.J. Warren
1: J.J. Barea
2: Bob Warren
3: John Warren
4: C.J. Watson
Pick one: 0
Results for T.J. Warren:

You searched for "Alan Williams"
49 results found.
0: Alan Williams
1: Al Williams
2: Alvin Williams
3: Sean Williams
4: Aaron Williams
5: Art Williams
6: Fly Williams
7: Frank Williams
8: Grant Williams
9: Hank Williams
10: Jason Williams
11: Jawad Williams
12: Jay Williams
13: John Williams
14: Lou Williams
15: Ray Williams
16: Ron Williams
17: Sam Williams
18: Sam Williams
19: Sly Williams
20: Walt Williams
21: Bob Williams
22: Buck Williams
23: C.J. Williams
24: Cliff Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Eric Williams
29: Gene Williams
30: Gus Williams
31: Guy Williams
32: Herb Williams
33: Jayson Williams
34: Jordan Williams
35: Kenny Williams
36: Kevin Williams
37: Marvin Williams
38: Matt Williams
39: Mike Williams
40: Milt Williams
41: Mo Williams
42: Nate Williams
43: Pete Williams
44: Rob Williams
45: Shawne Williams
46: Troy Williams
47: Ward Williams
48: Armen Gilliam
Pick one: 0
Results for Alan Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-03-30,28-111,MIL,AWAY,LAL,W (+2),1,34:08,15,24,...,3,6,4,0,0,2,39,36.5,4,Eric Bledsoe
1,2017-11-01,24-057,PHO,AWAY,WAS,W (+6),1,35:20,16,22,...,10,1,1,2,1,1,40,35.7,12,T.J. Warren
2,2018-01-16,21-078,PHO,AWAY,POR,L (-7),1,41:05,14,29,...,6,8,2,1,4,1,43,34.0,-6,Devin Booker
3,2017-12-04,21-035,PHO,AWAY,PHI,W (+14),1,38:52,17,32,...,8,1,2,1,3,1,46,33.6,10,Devin Booker
4,2017-12-23,23-304,ORL,AWAY,WAS,L (-27),1,35:34,11,16,...,5,10,4,1,3,3,30,32.2,-11,Elfrid Payton

In [52]:
# remove george king
# removed kelly oubre 
PHO_2019_gamelog = []

for p in PHO_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2019_gamelog.append(player_log)
PHO_2019_gamelog = pd.concat(PHO_2019_gamelog)    
PHO_2019_gamelogs = PHO_2019_gamelog.copy()
PHO_2019_gamelogs['GAME_SCORE'] = PHO_2019_gamelogs['GAME_SCORE'].astype(float)
PHO_2019_games = PHO_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2019_games_csv = PHO_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2019_games.csv', index=False)
PHO_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2019_games.csv')
PHO_2019_games_proc.head()

You searched for "Quincy Acy"
2 results found.
0: Quincy Acy
1: Quincy Douby
Pick one: 0
Results for Quincy Acy:

You searched for "Ryan Anderson"
14 results found.
0: Ryan Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Ron Anderson
5: Kyle Anderson
6: Eric Anderson
7: Greg Anderson
8: J.J. Anderson
9: Kenny Anderson
10: Kim Anderson
11: Nick Anderson
12: Alan Henderson
13: Ryan Robertson
Pick one: 0
Results for Ryan Anderson:

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Deandre Ayton"
1 result found.
Deandre Ayton
Results for Deandre Ayton:

You searched for "Dragan Bender"
1 result found.
Dragan Bender
Results for Dragan Bender:

You searched for "Devin Booker"
11 results found.
0: Devin Booker
1: Melvin Booker
2: Vin Baker
3: Trevor Booker
4: Kevin Brooks
5: Devin Brown
6: David Cooke
7: Kevin Loder
8: Kevin Porter
9: Kevin Porter
10: Devin Ebanks
Pick one: 0
Results for Devin Booker:

You searched for "Mikal Bridges"
3 results found.
0: Mikal Bridges
1: Bill Bridges
2: Miles Bridges
Pick one: 0
Results for Mikal Bridges:

You searched for "Isaiah Canaan"
1 result found.
Isaiah Canaan
Results for Isaiah Canaan:

You searched for "Tyson Chandler"
3 results found.
0: Tyson Chandler
1: Wilson Chandler
2: Tyson Wheeler
Pick one: 0
Results for Tyson Chandler:

You searched for "Jamal Crawford"
3 results found.
0: Jamal Crawford
1: Joe Crawford
2: Jordan Crawford
Pick one: 0
Results for Jamal Crawford:

You searched for "Troy Daniels"
4 results found.
0: Troy Daniels
1: Erik Daniels
2: Lloyd Daniels
3: Mel Daniels
Pick one: 0
Results for Troy Daniels:

You searched for "Jawun Evans"
4 results found.
0: Jawun Evans
1: Jacob Evans
2: Brian Evans
3: Earl Evans
Pick one: 0
Results for Jawun Evans:

You searched for "Jimmer Fredette"
1 result found.
Jimmer Fredette
Results for Jimmer Fredette:

You searched for "Richaun Holmes"
1 result found.
Richaun Holmes
Results for Richaun Holmes:

You searched for "Josh Jackson"
18 results found.
0: Josh Jackson
1: Jim Jackson
2: Tony Jackson
3: Tony Jackson
4: John Dickson
5: Al Jackson
6: Bobby Jackson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Mike Jackson
16: Phil Jackson
17: Ralph Jackson
Pick one: 0
Results for Josh Jackson:

You searched for "Tyler Johnson"
18 results found.
0: Tyler Johnson
1: Lee Johnson
2: Trey Johnson
3: Amir Johnson
4: Avery Johnson
5: Clay Johnson
6: Dave Johnson
7: Ed Johnson
8: James Johnson
9: Joe Johnson
10: Ken Johnson
11: Ken Johnson
12: Ollie Johnson
13: Ralph Johnson
14: Stanley Johnson
15: Steve Johnson
16: Stew Johnson
17: Wesley Johnson
Pick one: 0
Results for Tyler Johnson:

You searched for "De'Anthony Melton"
1 result found.
De'Anthony Melton
Results for De'Anthony Melton:

You searched for "Eric Moreland"
1 result found.
Eric Moreland
Results for Eric Moreland:

You searched for "Elie Okobo"
1 result found.
Elie Okobo
Results for Elie Okobo:

You searched for "Ray Spalding"
1 result found.
Ray Spalding
Results for Ray Spalding:

You searched for "Emanuel Terry"
1 result found.
Emanuel Terry
Results for Emanuel Terry:

You searched for "T.J. Warren"
5 results found.
0: T.J. Warren
1: J.J. Barea
2: Bob Warren
3: John Warren
4: C.J. Watson
Pick one: 0
Results for T.J. Warren:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-03-25,22-146,PHO,AWAY,UTA,L (-33),1,41:06,19,34,...,4,4,1,0,6,5,59,39.8,-13,Devin Booker
1,2019-03-27,22-148,PHO,HOME,WAS,L (-3),1,36:54,19,29,...,10,4,1,1,5,3,50,39.0,8,Devin Booker
2,2019-03-30,22-151,PHO,HOME,MEM,L (-5),1,42:44,19,29,...,3,11,0,0,6,3,48,36.7,1,Devin Booker
3,2018-12-29,20-159,PHO,HOME,DEN,L (-4),1,39:24,16,20,...,14,1,4,0,0,2,33,36.7,0,Deandre Ayton
4,2019-03-10,22-131,PHO,AWAY,GSW,W (+4),1,40:36,13,23,...,8,11,2,0,5,3,37,32.4,12,Devin Booker

In [55]:
# removed kelly oubre

PHO_2020_gamelog = []

for p in PHO_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2020_gamelog.append(player_log)
PHO_2020_gamelog = pd.concat(PHO_2020_gamelog)    
PHO_2020_gamelogs = PHO_2020_gamelog.copy()
PHO_2020_gamelogs['GAME_SCORE'] = PHO_2020_gamelogs['GAME_SCORE'].astype(float)
PHO_2020_games = PHO_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2020_games_csv = PHO_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2020_games.csv', index=False)
PHO_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2020_games.csv')
PHO_2020_games_proc.head()

You searched for "Deandre Ayton"
1 result found.
Deandre Ayton
Results for Deandre Ayton:

You searched for "Aron Baynes"
8 results found.
0: Aron Baynes
1: Ron Baker
2: Harry Barnes
3: Marvin Barnes
4: Ron Boone
5: Aaron James
6: Tharon Mayes
7: Cameron Payne
Pick one: 0
Results for Aron Baynes:

You searched for "Jonah Bolden"
2 results found.
0: Jonah Bolden
1: Jordan Bowden
Pick one: 0
Results for Jonah Bolden:

You searched for "Devin Booker"
11 results found.
0: Devin Booker
1: Melvin Booker
2: Vin Baker
3: Trevor Booker
4: Kevin Brooks
5: Devin Brown
6: David Cooke
7: Kevin Loder
8: Kevin Porter
9: Kevin Porter
10: Devin Ebanks
Pick one: 0
Results for Devin Booker:

You searched for "Mikal Bridges"
3 results found.
0: Mikal Bridges
1: Bill Bridges
2: Miles Bridges
Pick one: 0
Results for Mikal Bridges:

You searched for "Jevon Carter"
5 results found.
0: Jevon Carter
1: Ron Carter
2: Jake Carter
3: Kevin Porter
4: Kevin Porter
Pick one: 0
Results for Jevon Carter:

You searched for "Cheick Diallo"
1 result found.
Cheick Diallo
Results for Cheick Diallo:

You searched for "Jared Harper"
8 results found.
0: Jared Harper
1: Derek Harper
2: Fred Carter
3: Jake Carter
4: James Harden
5: Mike Harper
6: Ron Harper
7: Jared Reiner
Pick one: 0
Results for Jared Harper:

You searched for "Ty Jerome"
3 results found.
0: Ty Jerome
1: Tony Jaros
2: Tony Zeno
Pick one: 0
Results for Ty Jerome:

You searched for "Cameron Johnson"
7 results found.
0: Cameron Johnson
1: Clemon Johnson
2: Amir Johnson
3: Armon Johnson
4: Avery Johnson
5: James Johnson
6: Ron Johnson
Pick one: 0
Results for Cameron Johnson:

You searched for "Tyler Johnson"
18 results found.
0: Tyler Johnson
1: Lee Johnson
2: Trey Johnson
3: Amir Johnson
4: Avery Johnson
5: Clay Johnson
6: Dave Johnson
7: Ed Johnson
8: James Johnson
9: Joe Johnson
10: Ken Johnson
11: Ken Johnson
12: Ollie Johnson
13: Ralph Johnson
14: Stanley Johnson
15: Steve Johnson
16: Stew Johnson
17: Wesley Johnson
Pick one: 0
Results for Tyler Johnson:

You searched for "Frank Kaminsky"
2 results found.
0: Frank Kaminsky
1: Frank Ramsey
Pick one: 0
Results for Frank Kaminsky:

You searched for "Jalen Lecque"
1 result found.
Jalen Lecque
Results for Jalen Lecque:

You searched for "Elie Okobo"
1 result found.
Elie Okobo
Results for Elie Okobo:

You searched for "Tariq Owens"
8 results found.
0: Tariq Owens
1: Chris Owens
2: Larry Owens
3: Eddie Owens
4: Jim Owens
5: Red Owens
6: Tom Owens
7: Mario West
Pick one: 0
Results for Tariq Owens:

You searched for "Cameron Payne"
2 results found.
0: Cameron Payne
1: Aron Baynes
Pick one: 0
Results for Cameron Payne:

You searched for "Ricky Rubio"
7 results found.
0: Ricky Rubio
1: Ricky Davis
2: Ricky Ledo
3: Rick Robey
4: Ricky Berry
5: Ricky Grace
6: Ricky Marsh
Pick one: 0
Results for Ricky Rubio:

You searched for "Dario Šarić"
2 results found.
0: Dario Saric
1: Marko Jaric
Pick one: 0
Results for Dario Saric:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-12-05,23-036,PHO,AWAY,NOP,W (+7),1,42:27,13,23,...,8,9,2,0,5,4,44,38.0,11,Devin Booker
1,2020-01-18,23-080,PHO,AWAY,BOS,W (+4),1,40:39,12,20,...,10,9,2,0,4,4,39,35.1,17,Devin Booker
2,2020-01-05,23-067,PHO,HOME,MEM,L (-7),1,37:14,13,20,...,2,6,0,0,2,2,40,32.8,5,Devin Booker
3,2020-03-06,33-088,PHO,HOME,POR,W (+10),1,36:19,12,23,...,16,1,1,2,2,4,37,32.4,17,Aron Baynes
4,2019-11-04,23-005,PHO,HOME,PHI,W (+5),1,32:05,15,19,...,4,3,0,1,3,5,40,31.7,3,Devin Booker

In [58]:
# remvoed E'Twaun Moore
PHO_2021_gamelog = []

for p in PHO_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    PHO_2021_gamelog.append(player_log)
PHO_2021_gamelog = pd.concat(PHO_2021_gamelog)    
PHO_2021_gamelogs = PHO_2021_gamelog.copy()
PHO_2021_gamelogs['GAME_SCORE'] = PHO_2021_gamelogs['GAME_SCORE'].astype(float)
PHO_2021_games = PHO_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_2021_games_csv = PHO_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2021_games.csv', index=False)
PHO_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2021_games.csv')
PHO_2021_games_proc.head()

You searched for "Ty-Shon Alexander"
1 result found.
Ty-Shon Alexander
Results for Ty-Shon Alexander:

You searched for "Deandre Ayton"
1 result found.
Deandre Ayton
Results for Deandre Ayton:

You searched for "Devin Booker"
11 results found.
0: Devin Booker
1: Melvin Booker
2: Vin Baker
3: Trevor Booker
4: Kevin Brooks
5: Devin Brown
6: David Cooke
7: Kevin Loder
8: Kevin Porter
9: Kevin Porter
10: Devin Ebanks
Pick one: 0
Results for Devin Booker:

You searched for "Mikal Bridges"
3 results found.
0: Mikal Bridges
1: Bill Bridges
2: Miles Bridges
Pick one: 0
Results for Mikal Bridges:

You searched for "Jevon Carter"
5 results found.
0: Jevon Carter
1: Ron Carter
2: Jake Carter
3: Kevin Porter
4: Kevin Porter
Pick one: 0
Results for Jevon Carter:

You searched for "Torrey Craig"
1 result found.
Torrey Craig
Results for Torrey Craig:

You searched for "Jae Crowder"
4 results found.
0: Jae Crowder
1: Joe Cooper
2: Corey Crowder
3: Joe Strawder
Pick one: 0
Results for Jae Crowder:

You searched for "Langston Galloway"
1 result found.
Langston Galloway
Results for Langston Galloway:

You searched for "Cameron Johnson"
7 results found.
0: Cameron Johnson
1: Clemon Johnson
2: Amir Johnson
3: Armon Johnson
4: Avery Johnson
5: James Johnson
6: Ron Johnson
Pick one: 0
Results for Cameron Johnson:

You searched for "Damian Jones"
14 results found.
0: Damian Jones
1: Damon Jones
2: Damion James
3: DeQuan Jones
4: Mason Jones
5: Alvin Jones
6: Askia Jones
7: Dahntay Jones
8: Jalen Jones
9: James Jones
10: Kevin Jones
11: Robin Jones
12: Sam Jones
13: Wali Jones
Pick one: 0
Results for Damian Jones:

You searched for "Frank Kaminsky"
2 results found.
0: Frank Kaminsky
1: Frank Ramsey
Pick one: 0
Results for Frank Kaminsky:

You searched for "Abdel Nader"
1 result found.
Abdel Nader
Results for Abdel Nader:

You searched for "Chris Paul"
15 results found.
0: Chris Paul
1: Chris Babb
2: Chris Carr
3: Chris Taft
4: Chris Bosh
5: Chris Ford
6: Chris Jent
7: Chris Kaman
8: Chris King
9: Chris Mihm
10: Chris Mills
11: Chris Munk
12: Charlie Paulk
13: Chris Welp
14: Chris Silva
Pick one: 0
Results for Chris Paul:

You searched for "Cameron Payne"
2 results found.
0: Cameron Payne
1: Aron Baynes
Pick one: 0
Results for Cameron Payne:

You searched for "Dario Šarić"
2 results found.
0: Dario Saric
1: Marko Jaric
Pick one: 0
Results for Dario Saric:

You searched for "Jalen Smith"
33 results found.
0: Jalen Smith
1: Jason Smith
2: Al Smith
3: Joe Smith
4: John Smith
5: Ken Smith
6: Leon Smith
7: Nolan Smith
8: Bill Smith
9: Charles Smith
10: Charles Smith
11: Charles Smith
12: Deb Smith
13: Derek Smith
14: Don Smith
15: Don Smith
16: Ed Smith
17: Greg Smith
18: Greg Smith
19: J.R. Smith
20: Jabari Smith
21: Jerry Smith
22: Jim Smith
23: Josh Smith
24: Larry Smith
25: Mike Smith
26: Pete Smith
27: Randy Smith
28: Sam Smith
29: Sam Smith
30: Steven Smith
31: Joe Smyth
32: Jalen Jones
Pick one: 0
Results for Jalen Smith:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-03-31,24-152,PHO,HOME,CHI,W (+5),1,35:14,17,24,...,4,4,1,1,5,3,45,34.5,7,Devin Booker
1,2021-02-28,24-121,PHO,AWAY,MIN,W (+19),1,34:07,15,26,...,5,5,0,1,2,3,43,32.9,18,Devin Booker
2,2021-05-04,35-363,PHO,AWAY,CLE,W (+16),1,35:31,8,16,...,6,16,4,2,0,4,23,31.8,20,Chris Paul
3,2021-02-01,35-271,PHO,AWAY,DAL,W (+1),1,38:03,14,20,...,9,9,2,0,5,3,34,31.2,-3,Chris Paul
4,2021-02-22,24-115,PHO,HOME,POR,W (+32),1,29:03,12,17,...,4,4,0,0,1,0,34,30.3,28,Devin Booker

## combine all seasons

In [59]:
PHO_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2000_games.csv')
PHO_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2001_games.csv')
PHO_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2002_games.csv')
PHO_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2003_games.csv')
PHO_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2004_games.csv')
PHO_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2005_games.csv')
PHO_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2006_games.csv')
PHO_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2007_games.csv')
PHO_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2008_games.csv')
PHO_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2009_games.csv')
PHO_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2010_games.csv')
PHO_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2011_games.csv')
PHO_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2012_games.csv')
PHO_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2013_games.csv')
PHO_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2014_games.csv')
PHO_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2015_games.csv')
PHO_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2016_games.csv')
PHO_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2017_games.csv')
PHO_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2018_games.csv')
PHO_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2019_games.csv')
PHO_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2020_games.csv')
PHO_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/PHO/PHO_2021_games.csv')

In [60]:
PHO_season_dfs = [PHO_2000_games_io, PHO_2001_games_io, PHO_2002_games_io, PHO_2003_games_io, PHO_2004_games_io, PHO_2005_games_io,
                 PHO_2006_games_io, PHO_2007_games_io, PHO_2008_games_io, PHO_2009_games_io, PHO_2010_games_io, PHO_2011_games_io,
                 PHO_2012_games_io, PHO_2013_games_io, PHO_2014_games_io, PHO_2015_games_io, PHO_2016_games_io, PHO_2017_games_io,
                 PHO_2018_games_io, PHO_2019_games_io, PHO_2020_games_io, PHO_2021_games_io]

In [61]:
PHO_all = pd.concat(PHO_season_dfs)
PHO_all_sorted = PHO_all.sort_values(by=['GAME_SCORE'], ascending=False)
PHO_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-03-24,20-145,PHO,AWAY,BOS,L (-10),1,44:58,21,40,...,8,6,3,1,5,3,70,54.5,-6,Devin Booker
0,2008-11-05,25-355,PHO,AWAY,IND,W (+10),1,44:00,17,21,...,11,6,5,2,4,3,49,50.2,11,Amar'e Stoudemire
0,2000-01-16,33-031,PHO,HOME,DEN,W (+13),1,42:31,17,26,...,8,4,0,2,0,2,50,44.8,25,Clifford Robinson
0,2006-02-22,27-291,PHO,HOME,BOS,W (+9),1,43:02,15,22,...,15,0,4,3,2,3,44,44.8,7,Shawn Marion
1,2009-02-20,26-084,PHO,HOME,OKC,W (+22),1,41:42,16,21,...,7,7,6,0,1,3,41,43.5,29,Leandro Barbosa
0,2005-01-02,22-047,PHO,HOME,POR,W (+19),1,41:11,20,27,...,11,3,1,1,1,3,50,43.2,25,Amar'e Stoudemire
0,2001-01-02,26-340,PHO,AWAY,SAC,L (-4),1,49:51,20,27,...,6,0,1,0,2,1,53,42.9,7,Tony Delk
0,2007-02-25,24-101,PHO,AWAY,ATL,W (+9),1,44:33,14,25,...,16,6,0,3,1,3,43,42.0,17,Amar'e Stoudemire
1,2005-04-08,22-143,PHO,AWAY,GSW,L (-8),1,42:09,15,25,...,16,5,1,2,3,5,44,40.6,-4,Amar'e Stoudemire
0,2003-12-29,26-312,PHO,AWAY,LAC,W (+8),1,41:46,15,23,...,4,9,5,0,2,1,40,40.4,8,Stephon Marbury
2,2004-12-18,26-225,PHO,HOME,WAS,W (+14),1,43:40,13,18,...,14,2,6,1,1,2,36,40.3,16,Shawn Marion
0,2019-03-25,22-146,PHO,AWAY,UTA,L (-33),1,41:06,19,34,...,4,4,1,0,6,5,59,39.8,-13,Devin Booker
1,2019-03-27,22-148,PHO,HOME,WAS,L (-3),1,36:54,19,29,...,10,4,1,1,5,3,50,39.0,8,Devin Booker
1,2006-12-07,32-303,PHO,AWAY,NJN,W (+4),1,47:57,16,25,...,6,13,1,0,3,3,42,38.6,6,Steve Nash
3,2005-02-14,22-090,PHO,HOME,UTA,W (+8),1,39:52,14,22,...,12,2,3,2,2,4,42,38.4,11,Amar'e Stoudemire
1,2017-01-22,27-044,PHO,AWAY,TOR,W (+12),1,41:45,11,17,...,6,13,0,0,4,3,40,38.2,23,Eric Bledsoe
0,2019-12-05,23-036,PHO,AWAY,NOP,W (+7),1,42:27,13,23,...,8,9,2,0,5,4,44,38.0,11,Devin Booker
0,2008-03-31,25-136,PHO,HOME,DEN,W (+15),1,42:00,12,22,...,14,2,2,0,1,4,41,37.8,23,Amar'e Stoudemire
2,2009-02-18,26-094,PHO,AWAY,LAC,W (+23),1,36:09,15,20,...,11,1,0,0,1,3,42,37.4,38,Amar'e Stoudemire
1,2004-02-08,26-353,NYK,HOME,LAC,W (+6),1,45:07,15,20,...,1,8,2,0,4,1,42,37.1,6,Stephon Marbury
0,2003-02-14,25-359,PHO,HOME,NYK,L (-1),1,43:24,15,27,...,3,9,4,0,3,2,43,37.1,6,Stephon Marbury
3,2018-12-29,20-159,PHO,HOME,DEN,L (-4),1,39:24,16,20,...,14,1,4,0,0,2,33,36.7,0,Deandre Ayton
4,2005-01-28,22-073,PHO,AWAY,BOS,W (+9),1,40:30,14,23,...,5,2,3,1,1,1,42,36.7,1,Amar'e Stoudemire
2,2019-03-30,22-151,PHO,HOME,MEM,L (-5),1,42:44,19,29,...,3,11,0,0,6,3,48,36.7,1,Devin Booker
0,2018-03-30,28-111,MIL,AWAY,LAL,W (+2),1,34:08,15,24,...,3,6,4,0,0,2,39,36.5,4,Eric Bledsoe