In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2013-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_SAC = []

# SAC
while season <= 2021:
    df_SAC = get_roster('SAC', season)
    df_SAC['Season'] = season
    df_SAC['Team'] = 'SAC'
    appended_data_SAC.append(df_SAC)
    season = season + 1
appended_data_SAC = pd.concat(appended_data_SAC)

In [4]:
SAC_df_all = appended_data_SAC.copy()
SAC_df_all_csv = SAC_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_players_all.csv', index=False)
SAC_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_players_all.csv')
SAC_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,25,Nick Anderson,SG,6-6,205,1968-01-20,US,10,Illinois,2000,SAC
1,20,Jon Barry,SG,6-4,195,1969-07-25,US,7,"University of the Pacific, Georgia Tech",2000,SAC
2,23,Tyrone Corbin,SF,6-6,210,1962-12-31,US,14,DePaul,2000,SAC
3,0,Tony Delk,PG,6-1,189,1974-01-28,US,3,Kentucky,2000,SAC
4,21,Vlade Divac,C,7-1,243,1968-02-03,RS,10,NaN,2000,SAC

In [5]:
SAC_df_2000 = SAC_df_all[SAC_df_all['Season'] == 2000]
SAC_df_2001 = SAC_df_all[SAC_df_all['Season'] == 2001]
SAC_df_2002 = SAC_df_all[SAC_df_all['Season'] == 2002]
SAC_df_2003 = SAC_df_all[SAC_df_all['Season'] == 2003]
SAC_df_2004 = SAC_df_all[SAC_df_all['Season'] == 2004]
SAC_df_2005 = SAC_df_all[SAC_df_all['Season'] == 2005]
SAC_df_2006 = SAC_df_all[SAC_df_all['Season'] == 2006]
SAC_df_2007 = SAC_df_all[SAC_df_all['Season'] == 2007]
SAC_df_2008 = SAC_df_all[SAC_df_all['Season'] == 2008]
SAC_df_2009 = SAC_df_all[SAC_df_all['Season'] == 2009]
SAC_df_2010 = SAC_df_all[SAC_df_all['Season'] == 2010]
SAC_df_2011 = SAC_df_all[SAC_df_all['Season'] == 2011]
SAC_df_2012 = SAC_df_all[SAC_df_all['Season'] == 2012]
SAC_df_2013 = SAC_df_all[SAC_df_all['Season'] == 2013]
SAC_df_2014 = SAC_df_all[SAC_df_all['Season'] == 2014]
SAC_df_2015 = SAC_df_all[SAC_df_all['Season'] == 2015]
SAC_df_2016 = SAC_df_all[SAC_df_all['Season'] == 2016]
SAC_df_2017 = SAC_df_all[SAC_df_all['Season'] == 2017]
SAC_df_2018 = SAC_df_all[SAC_df_all['Season'] == 2018]
SAC_df_2019 = SAC_df_all[SAC_df_all['Season'] == 2019]
SAC_df_2020 = SAC_df_all[SAC_df_all['Season'] == 2020]
SAC_df_2021 = SAC_df_all[SAC_df_all['Season'] == 2021]

In [6]:
# changing names
#SAC_df_2002.loc[SAC_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#SAC_df_2004.loc[SAC_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [6]:
SAC_df_2000_players = SAC_df_2000['PLAYER'].to_list()
SAC_df_2001_players = SAC_df_2001['PLAYER'].to_list()
SAC_df_2002_players = SAC_df_2002['PLAYER'].to_list()
SAC_df_2003_players = SAC_df_2003['PLAYER'].to_list()
SAC_df_2004_players = SAC_df_2004['PLAYER'].to_list()
SAC_df_2005_players = SAC_df_2005['PLAYER'].to_list()

SAC_df_2006_players = SAC_df_2006['PLAYER'].to_list()
SAC_df_2007_players = SAC_df_2007['PLAYER'].to_list()
SAC_df_2008_players = SAC_df_2008['PLAYER'].to_list()
SAC_df_2009_players = SAC_df_2009['PLAYER'].to_list()
SAC_df_2010_players = SAC_df_2010['PLAYER'].to_list()
SAC_df_2011_players = SAC_df_2011['PLAYER'].to_list()

SAC_df_2012_players = SAC_df_2012['PLAYER'].to_list()
SAC_df_2013_players = SAC_df_2013['PLAYER'].to_list()
SAC_df_2014_players = SAC_df_2014['PLAYER'].to_list()
SAC_df_2015_players = SAC_df_2015['PLAYER'].to_list()
SAC_df_2016_players = SAC_df_2016['PLAYER'].to_list()
SAC_df_2017_players = SAC_df_2017['PLAYER'].to_list()

SAC_df_2018_players = SAC_df_2018['PLAYER'].to_list()
SAC_df_2019_players = SAC_df_2019['PLAYER'].to_list()
SAC_df_2020_players = SAC_df_2020['PLAYER'].to_list()
SAC_df_2021_players = SAC_df_2021['PLAYER'].to_list()

## players to drop

In [46]:
#SAC_df_2006_players.remove("Metta World Peace")
#SAC_df_2007_players.remove("Metta World Peace")
#SAC_df_2008_players.remove("Metta World Peace")
#SAC_df_2014_players.remove("Hamady N'Diaye")
#SAC_df_2018_players.remove("Frank Mason")
#SAC_df_2019_players.remove("Marvin Bagley")
#SAC_df_2019_players.remove("Frank Mason")
#SAC_df_2020_players.remove("Marvin Bagley")
#SAC_df_2021_players.remove("Marvin Bagley")
SAC_df_2021_players.remove("Glenn Robinson")

In [8]:

SAC_2000_gamelog = []


for p in SAC_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2000_gamelog.append(player_log)
SAC_2000_gamelog = pd.concat(SAC_2000_gamelog)    
SAC_2000_gamelogs = SAC_2000_gamelog.copy()
SAC_2000_gamelogs['GAME_SCORE'] = SAC_2000_gamelogs['GAME_SCORE'].astype(float)
SAC_2000_games = SAC_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2000_games_csv = SAC_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2000_games.csv', index=False)
SAC_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2000_games.csv')
SAC_2000_games_proc.head()

You searched for "Nick Anderson"
14 results found.
0: Nick Anderson
1: Eric Anderson
2: Kim Anderson
3: Alan Anderson
4: Cliff Anderson
5: Dan Anderson
6: Dan Anderson
7: Derek Anderson
8: Greg Anderson
9: J.J. Anderson
10: Kyle Anderson
11: Ron Anderson
12: Ryan Anderson
13: Rick Roberson
Pick one: 0
Results for Nick Anderson:

You searched for "Jon Barry"
30 results found.
0: Jon Barry
1: John Barr
2: Moe Barr
3: Ron Perry
4: John Bagley
5: Ron Baker
6: John Barber
7: Brent Barry
8: Drew Barry
9: Rick Barry
10: Jay Carty
11: Bob Ferry
12: John Garris
13: Joe Harris
14: Don May
15: Don Ray
16: Jason Terry
17: John Warren
18: Vin Baker
19: Tom Barker
20: Mike Barr
21: Cory Carr
22: Ron Carter
23: Ron Harper
24: Jason Hart
25: Josh Hart
26: Jon Leuer
27: Jack Parr
28: Von Wafer
29: John Wall
Pick one: 0
Results for Jon Barry:

You searched for "Tyrone Corbin"
2 results found.
0: Tyrone Corbin
1: Tyrone Britt
Pick one: 0
Results for Tyrone Corbin:

You searched for "Tony Delk"
12 results found.
0: Tony Delk
1: Tony Snell
2: Tony Zeno
3: Tony Allen
4: Troy Bell
5: Don Dee
6: Tony Dumas
7: Tony Koski
8: Deng Adel
9: Sonny Dove
10: Tony Price
11: Tony White
Pick one: 0
Results for Tony Delk:

You searched for "Vlade Divac"
1 result found.
Vlade Divac
Results for Vlade Divac:

You searched for "Lawrence Funderburke"
1 result found.
Lawrence Funderburke
Results for Lawrence Funderburke:

You searched for "Darrick Martin"
5 results found.
0: Darrick Martin
1: Maurice Martin
2: Derrick Gervin
3: Cartier Martin
4: Derrick Walton
Pick one: 0
Results for Darrick Martin:

You searched for "Scot Pollard"
2 results found.
0: Scot Pollard
1: Jim Pollard
Pick one: 0
Results for Scot Pollard:

You searched for "Ryan Robertson"
7 results found.
0: Ryan Robertson
1: Ryan Anderson
2: Rick Roberson
3: Brian Roberts
4: Alvin Robertson
5: Oscar Robertson
6: Tony Robertson
Pick one: 0
Results for Ryan Robertson:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

You searched for "Bill Wennington"
1 result found.
Bill Wennington
Results for Bill Wennington:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-01-15,26-320,SAC,AWAY,GSW,W (+15),1,38:37,13,19,...,16,3,2,4,5,3,37,34.8,11,Chris Webber
1,1999-11-23,26-267,SAC,HOME,NJN,W (+13),1,41:54,11,18,...,22,10,3,4,2,3,26,34.8,4,Chris Webber
2,2000-01-13,26-318,SAC,HOME,SAS,W (+4),1,41:06,13,27,...,19,3,2,2,0,3,34,32.3,13,Chris Webber
3,1999-12-11,26-285,SAC,HOME,POR,L (-5),1,40:51,16,26,...,12,5,1,3,2,4,36,31.6,2,Chris Webber
4,2000-01-04,26-309,SAC,AWAY,CLE,W (+4),1,44:11,14,22,...,10,4,2,1,3,4,37,31.1,9,Chris Webber

In [9]:

SAC_2001_gamelog = []


for p in SAC_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2001_gamelog.append(player_log)
SAC_2001_gamelog = pd.concat(SAC_2001_gamelog)    
SAC_2001_gamelogs = SAC_2001_gamelog.copy()
SAC_2001_gamelogs['GAME_SCORE'] = SAC_2001_gamelogs['GAME_SCORE'].astype(float)
SAC_2001_games = SAC_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2001_games_csv = SAC_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2001_games.csv', index=False)
SAC_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2001_games.csv')
SAC_2001_games_proc.head()

You searched for "Nick Anderson"
14 results found.
0: Nick Anderson
1: Eric Anderson
2: Kim Anderson
3: Alan Anderson
4: Cliff Anderson
5: Dan Anderson
6: Dan Anderson
7: Derek Anderson
8: Greg Anderson
9: J.J. Anderson
10: Kyle Anderson
11: Ron Anderson
12: Ryan Anderson
13: Rick Roberson
Pick one: 0
Results for Nick Anderson:

You searched for "Jon Barry"
30 results found.
0: Jon Barry
1: John Barr
2: Moe Barr
3: Ron Perry
4: John Bagley
5: Ron Baker
6: John Barber
7: Brent Barry
8: Drew Barry
9: Rick Barry
10: Jay Carty
11: Bob Ferry
12: John Garris
13: Joe Harris
14: Don May
15: Don Ray
16: Jason Terry
17: John Warren
18: Vin Baker
19: Tom Barker
20: Mike Barr
21: Cory Carr
22: Ron Carter
23: Ron Harper
24: Jason Hart
25: Josh Hart
26: Jon Leuer
27: Jack Parr
28: Von Wafer
29: John Wall
Pick one: 0
Results for Jon Barry:

You searched for "Doug Christie"
2 results found.
0: Doug Christie
1: Doug Kistler
Pick one: 0
Results for Doug Christie:

You searched for "Vlade Divac"
1 result found.
Vlade Divac
Results for Vlade Divac:

You searched for "Lawrence Funderburke"
1 result found.
Lawrence Funderburke
Results for Lawrence Funderburke:

You searched for "Bobby Jackson"
10 results found.
0: Bobby Jackson
1: Tony Jackson
2: Tony Jackson
3: Bobby Watson
4: Josh Jackson
5: Tracy Jackson
6: Bobby Wilson
7: Bobby Wilson
8: Bobby Jones
9: Bobby Jones
Pick one: 0
Results for Bobby Jackson:

You searched for "Art Long"
7 results found.
0: Art Long
1: Grant Long
2: Paul Long
3: John Long
4: Shawn Long
5: Walt Lemon
6: Alex Len
Pick one: 0
Results for Art Long:

You searched for "Darrick Martin"
5 results found.
0: Darrick Martin
1: Maurice Martin
2: Derrick Gervin
3: Cartier Martin
4: Derrick Walton
Pick one: 0
Results for Darrick Martin:

You searched for "Scot Pollard"
2 results found.
0: Scot Pollard
1: Jim Pollard
Pick one: 0
Results for Scot Pollard:

You searched for "Jabari Smith"
8 results found.
0: Jabari Smith
1: Jalen Smith
2: Jabari Bird
3: J.R. Smith
4: Jason Smith
5: Jerry Smith
6: Larry Smith
7: Robert Smith
Pick one: 0
Results for Jabari Smith:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

You searched for "Jason Williams"
36 results found.
0: Jason Williams
1: Jayson Williams
2: Aaron Williams
3: Alan Williams
4: Deron Williams
5: Jawad Williams
6: Jay Williams
7: John Williams
8: Justin Williams
9: Ron Williams
10: Jason Collins
11: Al Williams
12: Alvin Williams
13: Art Williams
14: Bob Williams
15: Brandon Williams
16: Earl Williams
17: Gus Williams
18: Hank Williams
19: Jerome Williams
20: Jordan Williams
21: Kevin Williams
22: Lou Williams
23: Marvin Williams
24: Matt Williams
25: Mo Williams
26: Nate Williams
27: Ray Williams
28: Rob Williams
29: Sam Williams
30: Sam Williams
31: Sean Williams
32: Sly Williams
33: Troy Williams
34: Walt Williams
35: Ward Williams
Pick one: 0
Results for Jason Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-01-05,27-310,SAC,HOME,IND,L (-2),1,49:58,24,47,...,26,5,3,2,4,4,51,40.6,-1,Chris Webber
1,2001-02-02,27-338,SAC,HOME,VAN,W (+10),1,38:42,15,23,...,15,4,1,2,2,2,41,39.0,15,Chris Webber
2,2001-03-27,28-026,SAC,HOME,NYK,W (+7),1,49:52,16,26,...,15,5,3,1,4,3,39,32.5,7,Chris Webber
3,2001-01-02,32-334,SAC,HOME,PHO,W (+4),1,42:52,11,15,...,12,6,1,2,4,4,34,32.5,-9,Vlade Divac
4,2000-12-08,27-282,SAC,HOME,HOU,W (+13),1,42:38,15,26,...,18,2,2,1,4,3,37,31.1,12,Chris Webber

In [10]:

SAC_2002_gamelog = []


for p in SAC_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2002_gamelog.append(player_log)
SAC_2002_gamelog = pd.concat(SAC_2002_gamelog)    
SAC_2002_gamelogs = SAC_2002_gamelog.copy()
SAC_2002_gamelogs['GAME_SCORE'] = SAC_2002_gamelogs['GAME_SCORE'].astype(float)
SAC_2002_games = SAC_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2002_games_csv = SAC_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2002_games.csv', index=False)
SAC_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2002_games.csv')
SAC_2002_games_proc.head()

You searched for "Mike Bibby"
17 results found.
0: Mike Bibby
1: Mike Tobey
2: Mike Barr
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike Gibson
7: Mike Maloy
8: Mike Niles
9: Mike Wilks
10: Mike Dabich
11: Mike Davis
12: Mike Davis
13: Mike Lewis
14: Mike Lynn
15: Mike Price
16: Mike Smith
Pick one: 0
Results for Mike Bibby:

You searched for "Chucky Brown"
3 results found.
0: Chucky Brown
1: Bruce Brown
2: Rickey Brown
Pick one: 0
Results for Chucky Brown:

You searched for "Doug Christie"
2 results found.
0: Doug Christie
1: Doug Kistler
Pick one: 0
Results for Doug Christie:

You searched for "Mateen Cleaves"
1 result found.
Mateen Cleaves
Results for Mateen Cleaves:

You searched for "Vlade Divac"
1 result found.
Vlade Divac
Results for Vlade Divac:

You searched for "Lawrence Funderburke"
1 result found.
Lawrence Funderburke
Results for Lawrence Funderburke:

You searched for "Bobby Jackson"
10 results found.
0: Bobby Jackson
1: Tony Jackson
2: Tony Jackson
3: Bobby Watson
4: Josh Jackson
5: Tracy Jackson
6: Bobby Wilson
7: Bobby Wilson
8: Bobby Jones
9: Bobby Jones
Pick one: 0
Results for Bobby Jackson:

You searched for "Scot Pollard"
2 results found.
0: Scot Pollard
1: Jim Pollard
Pick one: 0
Results for Scot Pollard:

You searched for "Brent Price"
5 results found.
0: Brent Price
1: Tony Price
2: Glen Rice
3: Glen Rice
4: Brent Barry
Pick one: 0
Results for Brent Price:

You searched for "Jabari Smith"
8 results found.
0: Jabari Smith
1: Jalen Smith
2: Jabari Bird
3: J.R. Smith
4: Jason Smith
5: Jerry Smith
6: Larry Smith
7: Robert Smith
Pick one: 0
Results for Jabari Smith:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

You searched for "Gerald Wallace"
2 results found.
0: Gerald Wallace
1: Red Wallace
Pick one: 0
Results for Gerald Wallace:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2002-03-19,29-018,SAC,HOME,HOU,W (+23),1,31:54,15,20,...,12,5,3,1,0,3,35,38.2,21,Chris Webber
1,2002-03-26,29-025,SAC,HOME,LAC,W (+17),1,45:03,15,21,...,13,1,3,2,1,5,35,33.1,18,Chris Webber
2,2002-01-15,28-320,SAC,HOME,CLE,W (+7),1,42:42,14,27,...,14,8,1,3,1,1,34,32.2,17,Chris Webber
3,2002-04-05,29-035,SAC,AWAY,UTA,W (+8),1,40:12,13,22,...,10,6,5,3,1,4,28,31.1,14,Chris Webber
4,2002-03-01,29-000,SAC,AWAY,GSW,W (+8),1,40:11,13,26,...,9,8,2,1,0,1,32,30.8,23,Chris Webber

In [11]:

    
SAC_2003_gamelog = []



for p in SAC_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2003_gamelog.append(player_log)
SAC_2003_gamelog = pd.concat(SAC_2003_gamelog)    
SAC_2003_gamelogs = SAC_2003_gamelog.copy()
SAC_2003_gamelogs['GAME_SCORE'] = SAC_2003_gamelogs['GAME_SCORE'].astype(float)
SAC_2003_games = SAC_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2003_games_csv = SAC_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2003_games.csv', index=False)
SAC_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2003_games.csv')
SAC_2003_games_proc.head()

You searched for "Mike Bibby"
17 results found.
0: Mike Bibby
1: Mike Tobey
2: Mike Barr
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike Gibson
7: Mike Maloy
8: Mike Niles
9: Mike Wilks
10: Mike Dabich
11: Mike Davis
12: Mike Davis
13: Mike Lewis
14: Mike Lynn
15: Mike Price
16: Mike Smith
Pick one: 0
Results for Mike Bibby:

You searched for "Doug Christie"
2 results found.
0: Doug Christie
1: Doug Kistler
Pick one: 0
Results for Doug Christie:

You searched for "Keon Clark"
5 results found.
0: Keon Clark
1: Ian Clark
2: Kenny Carr
3: Earl Clark
4: Gary Clark
Pick one: 0
Results for Keon Clark:

You searched for "Mateen Cleaves"
1 result found.
Mateen Cleaves
Results for Mateen Cleaves:

You searched for "Vlade Divac"
1 result found.
Vlade Divac
Results for Vlade Divac:

You searched for "Lawrence Funderburke"
1 result found.
Lawrence Funderburke
Results for Lawrence Funderburke:

You searched for "Bobby Jackson"
10 results found.
0: Bobby Jackson
1: Tony Jackson
2: Tony Jackson
3: Bobby Watson
4: Josh Jackson
5: Tracy Jackson
6: Bobby Wilson
7: Bobby Wilson
8: Bobby Jones
9: Bobby Jones
Pick one: 0
Results for Bobby Jackson:

You searched for "Jim Jackson"
21 results found.
0: Jim Jackson
1: Al Jackson
2: Josh Jackson
3: Mike Jackson
4: Phil Jackson
5: Jim Paxson
6: Jim Paxson
7: Greg Jackson
8: Jaren Jackson
9: Jaren Jackson
10: Justin Jackson
11: Luke Jackson
12: Luke Jackson
13: Marc Jackson
14: Mark Jackson
15: Tony Jackson
16: Tony Jackson
17: Sam Jacobson
18: Jim Wilson
19: Jim Eakins
20: Jim Chones
Pick one: 0
Results for Jim Jackson:

You searched for "Damon Jones"
24 results found.
0: Damon Jones
1: Mason Jones
2: Damian Jones
3: Damion James
4: Jalen Jones
5: James Jones
6: Major Jones
7: Sam Jones
8: Aaron James
9: Alvin Jones
10: DeQuan Jones
11: Dwayne Jones
12: Earl Jones
13: Jake Jones
14: Jimmy Jones
15: Kevin Jones
16: Larry Jones
17: Mark Jones
18: Mark Jones
19: Robin Jones
20: Solomon Jones
21: Wali Jones
22: Diamond Stone
23: Damone Brown
Pick one: 0
Results for Damon Jones:

You searched for "Scot Pollard"
2 results found.
0: Scot Pollard
1: Jim Pollard
Pick one: 0
Results for Scot Pollard:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

You searched for "Gerald Wallace"
2 results found.
0: Gerald Wallace
1: Red Wallace
Pick one: 0
Results for Gerald Wallace:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-01-21,29-326,SAC,HOME,NJN,W (+7),1,43:56,13,21,...,15,8,4,1,1,3,36,36.7,3,Chris Webber
1,2003-01-18,25-223,SAC,AWAY,LAC,L (-5),1,35:05,16,22,...,7,3,1,0,0,3,37,32.8,-8,Peja Stojaković
2,2002-12-21,29-295,SAC,AWAY,PHO,L (-9),1,43:54,14,25,...,15,11,5,0,2,3,29,32.3,-3,Chris Webber
3,2003-01-15,29-320,SAC,HOME,DAL,W (+29),1,40:28,12,20,...,15,11,0,2,4,2,29,29.8,22,Chris Webber
4,2002-11-29,29-261,SAC,HOME,LAC,W (+13),1,38:28,12,17,...,8,5,2,0,3,2,31,28.4,19,Bobby Jackson

In [12]:


SAC_2004_gamelog = []



for p in SAC_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2004_gamelog.append(player_log)
SAC_2004_gamelog = pd.concat(SAC_2004_gamelog)    
SAC_2004_gamelogs = SAC_2004_gamelog.copy()
SAC_2004_gamelogs['GAME_SCORE'] = SAC_2004_gamelogs['GAME_SCORE'].astype(float)
SAC_2004_games = SAC_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2004_games_csv = SAC_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2004_games.csv', index=False)
SAC_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2004_games.csv')
SAC_2004_games_proc.head()

You searched for "Mike Bibby"
17 results found.
0: Mike Bibby
1: Mike Tobey
2: Mike Barr
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike Gibson
7: Mike Maloy
8: Mike Niles
9: Mike Wilks
10: Mike Dabich
11: Mike Davis
12: Mike Davis
13: Mike Lewis
14: Mike Lynn
15: Mike Price
16: Mike Smith
Pick one: 0
Results for Mike Bibby:

You searched for "Rodney Buford"
2 results found.
0: Rodney Buford
1: Rodney Hood
Pick one: 0
Results for Rodney Buford:

You searched for "Doug Christie"
2 results found.
0: Doug Christie
1: Doug Kistler
Pick one: 0
Results for Doug Christie:

You searched for "Vlade Divac"
1 result found.
Vlade Divac
Results for Vlade Divac:

You searched for "Bobby Jackson"
10 results found.
0: Bobby Jackson
1: Tony Jackson
2: Tony Jackson
3: Bobby Watson
4: Josh Jackson
5: Tracy Jackson
6: Bobby Wilson
7: Bobby Wilson
8: Bobby Jones
9: Bobby Jones
Pick one: 0
Results for Bobby Jackson:

You searched for "Tony Massenburg"
1 result found.
Tony Massenburg
Results for Tony Massenburg:

You searched for "Brad Miller"
12 results found.
0: Brad Miller
1: Bill Miller
2: Bob Miller
3: Jay Miller
4: Brad Sellers
5: Grant Riller
6: Dick Miller
7: Harry Miller
8: Larry Miller
9: Mike Miller
10: Walt Miller
11: Brady Walker
Pick one: 0
Results for Brad Miller:

You searched for "Anthony Peeler"
8 results found.
0: Anthony Peeler
1: Anthony Miller
2: Anthony Parker
3: Anthony Bonner
4: Anthony Carter
5: Anthony Pullard
6: Anthony Taylor
7: Anthony Tucker
Pick one: 0
Results for Anthony Peeler:

You searched for "Jabari Smith"
8 results found.
0: Jabari Smith
1: Jalen Smith
2: Jabari Bird
3: J.R. Smith
4: Jason Smith
5: Jerry Smith
6: Larry Smith
7: Robert Smith
Pick one: 0
Results for Jabari Smith:

You searched for "Darius Songaila"
2 results found.
0: Darius Songaila
1: Darius Garland
Pick one: 0
Results for Darius Songaila:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Gerald Wallace"
2 results found.
0: Gerald Wallace
1: Red Wallace
Pick one: 0
Results for Gerald Wallace:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-12-28,26-202,SAC,HOME,UTA,W (+9),1,45:18,10,22,...,7,1,6,0,2,2,37,33.2,12,Peja Stojaković
1,2004-02-29,33-296,SAC,HOME,PHO,W (+14),1,46:34,10,17,...,8,9,4,1,0,2,28,33.1,14,Doug Christie
2,2004-01-19,26-224,SAC,AWAY,LAC,W (+25),1,32:03,9,14,...,4,5,2,1,2,2,31,30.2,28,Peja Stojaković
3,2003-11-21,27-223,SAC,HOME,ORL,W (+30),1,36:31,7,8,...,14,10,1,1,3,1,22,29.9,27,Brad Miller
4,2003-11-16,26-160,SAC,HOME,GSW,W (+2),1,43:28,9,18,...,11,4,1,1,3,3,33,29.6,9,Peja Stojaković

In [13]:

SAC_2005_gamelog = []



for p in SAC_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2005_gamelog.append(player_log)
SAC_2005_gamelog = pd.concat(SAC_2005_gamelog)    
SAC_2005_gamelogs = SAC_2005_gamelog.copy()
SAC_2005_gamelogs['GAME_SCORE'] = SAC_2005_gamelogs['GAME_SCORE'].astype(float)
SAC_2005_games = SAC_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2005_games_csv = SAC_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2005_games.csv', index=False)
SAC_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2005_games.csv')
SAC_2005_games_proc.head()

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Mike Bibby"
17 results found.
0: Mike Bibby
1: Mike Tobey
2: Mike Barr
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike Gibson
7: Mike Maloy
8: Mike Niles
9: Mike Wilks
10: Mike Dabich
11: Mike Davis
12: Mike Davis
13: Mike Lewis
14: Mike Lynn
15: Mike Price
16: Mike Smith
Pick one: 0
Results for Mike Bibby:

You searched for "Michael Bradley"
7 results found.
0: Michael Bradley
1: Michael Beasley
2: Michael Ansley
3: Michael Finley
4: Michael Frazier
5: Michael Wiley
6: Michael Bytzura
Pick one: 0
Results for Michael Bradley:

You searched for "Doug Christie"
2 results found.
0: Doug Christie
1: Doug Kistler
Pick one: 0
Results for Doug Christie:

You searched for "Erik Daniels"
4 results found.
0: Erik Daniels
1: Troy Daniels
2: Mel Daniels
3: Erick Dampier
Pick one: 0
Results for Erik Daniels:

You searched for "Maurice Evans"
6 results found.
0: Maurice Evans
1: Mike Evans
2: Maurice King
3: Maurice Lucas
4: Maurice Ager
5: Maurice Baker
Pick one: 0
Results for Maurice Evans:

You searched for "Eddie House"
6 results found.
0: Eddie House
1: Eddie Hughes
2: Eddie Jones
3: Eddie Mast
4: Eddie Miles
5: Eddie Owens
Pick one: 0
Results for Eddie House:

You searched for "Bobby Jackson"
10 results found.
0: Bobby Jackson
1: Tony Jackson
2: Tony Jackson
3: Bobby Watson
4: Josh Jackson
5: Tracy Jackson
6: Bobby Wilson
7: Bobby Wilson
8: Bobby Jones
9: Bobby Jones
Pick one: 0
Results for Bobby Jackson:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Brad Miller"
12 results found.
0: Brad Miller
1: Bill Miller
2: Bob Miller
3: Jay Miller
4: Brad Sellers
5: Grant Riller
6: Dick Miller
7: Harry Miller
8: Larry Miller
9: Mike Miller
10: Walt Miller
11: Brady Walker
Pick one: 0
Results for Brad Miller:

You searched for "Cuttino Mobley"
1 result found.
Cuttino Mobley
Results for Cuttino Mobley:

You searched for "Greg Ostertag"
2 results found.
0: Greg Ostertag
1: Greg Foster
Pick one: 0
Results for Greg Ostertag:

You searched for "Brian Skinner"
6 results found.
0: Brian Skinner
1: Brian Oliver
2: Brian Quinnett
3: Al Skinner
4: Tal Skinner
5: Brian Winters
Pick one: 0
Results for Brian Skinner:

You searched for "Darius Songaila"
2 results found.
0: Darius Songaila
1: Darius Garland
Pick one: 0
Results for Darius Songaila:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Chris Webber"
8 results found.
0: Chris Webber
1: Chris Babb
2: Chris Engler
3: Chris Garner
4: Chris Herren
5: Chris Hunter
6: Chris Porter
7: Chris Welp
Pick one: 0
Results for Chris Webber:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-02-02,28-296,SAC,AWAY,GSW,W (+4),1,49:51,14,22,...,17,4,4,2,6,0,38,36.3,11,Brad Miller
1,2005-02-04,26-267,SAC,HOME,NYK,W (+1),1,42:59,16,25,...,3,7,3,0,1,0,40,34.3,11,Mike Bibby
2,2005-03-24,27-288,SAC,HOME,DAL,W (+8),1,41:28,9,13,...,9,2,1,0,3,5,38,33.0,12,Peja Stojaković
3,2005-02-27,26-290,SAC,AWAY,WAS,W (+2),1,42:21,13,23,...,6,7,4,0,5,3,38,32.0,2,Mike Bibby
4,2005-02-04,28-298,SAC,HOME,NYK,W (+1),1,41:53,11,20,...,9,4,1,2,1,1,35,31.5,3,Brad Miller

In [16]:

SAC_2006_gamelog = []

for p in SAC_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2006_gamelog.append(player_log)
SAC_2006_gamelog = pd.concat(SAC_2006_gamelog)    
SAC_2006_gamelogs = SAC_2006_gamelog.copy()
SAC_2006_gamelogs['GAME_SCORE'] = SAC_2006_gamelogs['GAME_SCORE'].astype(float)
SAC_2006_games = SAC_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2006_games_csv = SAC_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2006_games.csv', index=False)
SAC_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2006_games.csv')
SAC_2006_games_proc.head()

You searched for "Shareef Abdur-Rahim"
1 result found.
Shareef Abdur-Rahim
Results for Shareef Abdur-Rahim:

You searched for "Mike Bibby"
17 results found.
0: Mike Bibby
1: Mike Tobey
2: Mike Barr
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike Gibson
7: Mike Maloy
8: Mike Niles
9: Mike Wilks
10: Mike Dabich
11: Mike Davis
12: Mike Davis
13: Mike Lewis
14: Mike Lynn
15: Mike Price
16: Mike Smith
Pick one: 0
Results for Mike Bibby:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Jason Hart"
9 results found.
0: Jason Hart
1: Josh Hart
2: Jaxson Hayes
3: Jason Kidd
4: Jason Smith
5: Jason Terry
6: Jon Barry
7: Jay Carty
8: Jason Sasser
Pick one: 0
Results for Jason Hart:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Brad Miller"
12 results found.
0: Brad Miller
1: Bill Miller
2: Bob Miller
3: Jay Miller
4: Brad Sellers
5: Grant Riller
6: Dick Miller
7: Harry Miller
8: Larry Miller
9: Mike Miller
10: Walt Miller
11: Brady Walker
Pick one: 0
Results for Brad Miller:

You searched for "Sergei Monia"
1 result found.
Sergei Monia
Results for Sergei Monia:

You searched for "Vitaly Potapenko"
1 result found.
Vitaly Potapenko
Results for Vitaly Potapenko:

You searched for "Ronnie Price"
5 results found.
0: Ronnie Price
1: Donnie Boyce
2: Ronnie Brewer
3: Tony Price
4: Connie Rea
Pick one: 0
Results for Ronnie Price:

You searched for "Jamal Sampson"
3 results found.
0: Jamal Sampson
1: JaKarr Sampson
2: Ralph Sampson
Pick one: 0
Results for Jamal Sampson:

You searched for "Brian Skinner"
6 results found.
0: Brian Skinner
1: Brian Oliver
2: Brian Quinnett
3: Al Skinner
4: Tal Skinner
5: Brian Winters
Pick one: 0
Results for Brian Skinner:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Bonzi Wells"
3 results found.
0: Bonzi Wells
1: Bubba Wells
2: Owen Wells
Pick one: 0
Results for Bonzi Wells:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-01-24,27-256,SAC,AWAY,PHI,L (-6),1,42:35,17,25,...,3,4,1,0,3,3,44,33.8,-10,Mike Bibby
1,2005-12-27,27-228,SAC,AWAY,LAC,W (+17),1,40:53,10,20,...,4,10,1,0,4,2,38,32.0,12,Mike Bibby
2,2006-01-03,29-266,SAC,HOME,PHI,L (-13),1,39:39,13,22,...,11,3,1,1,1,4,36,30.7,-10,Brad Miller
3,2006-01-15,27-247,SAC,HOME,ORL,W (+4),1,46:18,13,23,...,1,4,0,0,2,4,42,30.2,4,Mike Bibby
4,2005-12-30,27-231,SAC,HOME,BOS,W (+4),1,43:37,11,19,...,6,10,1,0,4,1,33,29.5,1,Mike Bibby

In [19]:


SAC_2007_gamelog = []

for p in SAC_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2007_gamelog.append(player_log)
SAC_2007_gamelog = pd.concat(SAC_2007_gamelog)    
SAC_2007_gamelogs = SAC_2007_gamelog.copy()
SAC_2007_gamelogs['GAME_SCORE'] = SAC_2007_gamelogs['GAME_SCORE'].astype(float)
SAC_2007_games = SAC_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2007_games_csv = SAC_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2007_games.csv', index=False)
SAC_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2007_games.csv')
SAC_2007_games_proc.head()

You searched for "Shareef Abdur-Rahim"
1 result found.
Shareef Abdur-Rahim
Results for Shareef Abdur-Rahim:

You searched for "Mike Bibby"
17 results found.
0: Mike Bibby
1: Mike Tobey
2: Mike Barr
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike Gibson
7: Mike Maloy
8: Mike Niles
9: Mike Wilks
10: Mike Dabich
11: Mike Davis
12: Mike Davis
13: Mike Lewis
14: Mike Lynn
15: Mike Price
16: Mike Smith
Pick one: 0
Results for Mike Bibby:

You searched for "Quincy Douby"
2 results found.
0: Quincy Douby
1: Quincy Acy
Pick one: 0
Results for Quincy Douby:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Jason Hart"
9 results found.
0: Jason Hart
1: Josh Hart
2: Jaxson Hayes
3: Jason Kidd
4: Jason Smith
5: Jason Terry
6: Jon Barry
7: Jay Carty
8: Jason Sasser
Pick one: 0
Results for Jason Hart:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Brad Miller"
12 results found.
0: Brad Miller
1: Bill Miller
2: Bob Miller
3: Jay Miller
4: Brad Sellers
5: Grant Riller
6: Dick Miller
7: Harry Miller
8: Larry Miller
9: Mike Miller
10: Walt Miller
11: Brady Walker
Pick one: 0
Results for Brad Miller:

You searched for "Vitaly Potapenko"
1 result found.
Vitaly Potapenko
Results for Vitaly Potapenko:

You searched for "Ronnie Price"
5 results found.
0: Ronnie Price
1: Donnie Boyce
2: Ronnie Brewer
3: Tony Price
4: Connie Rea
Pick one: 0
Results for Ronnie Price:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Maurice Taylor"
6 results found.
0: Maurice Taylor
1: Marlon Taylor
2: Maurice Ager
3: Maurice Baker
4: Maurice Carter
5: Mike Taylor
Pick one: 0
Results for Maurice Taylor:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Justin Williams"
10 results found.
0: Justin Williams
1: Jason Williams
2: Alvin Williams
3: Gus Williams
4: Jayson Williams
5: John Williams
6: Jordan Williams
7: Kevin Williams
8: Marvin Williams
9: Sean Williams
Pick one: 0
Results for Justin Williams:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-12-21,23-323,SAC,HOME,WAS,L (-7),1,45:50,13,23,...,4,4,1,1,2,3,40,31.6,-8,Kevin Martin
1,2007-03-02,28-293,SAC,AWAY,LAL,W (+8),1,36:44,8,15,...,4,7,1,0,1,0,33,31.0,10,Mike Bibby
2,2007-03-03,24-030,SAC,AWAY,POR,W (+8),1,38:08,11,19,...,6,6,1,0,0,3,33,30.3,8,Kevin Martin
3,2006-11-24,23-296,SAC,AWAY,SEA,W (+9),1,39:00,12,19,...,4,3,2,0,0,3,35,29.8,15,Kevin Martin
4,2007-02-28,24-027,SAC,HOME,CHA,W (+15),1,46:22,13,19,...,5,4,2,0,3,2,36,29.6,17,Kevin Martin

In [21]:


SAC_2008_gamelog = []

for p in SAC_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2008_gamelog.append(player_log)
SAC_2008_gamelog = pd.concat(SAC_2008_gamelog)    
SAC_2008_gamelogs = SAC_2008_gamelog.copy()
SAC_2008_gamelogs['GAME_SCORE'] = SAC_2008_gamelogs['GAME_SCORE'].astype(float)
SAC_2008_games = SAC_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2008_games_csv = SAC_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2008_games.csv', index=False)
SAC_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2008_games.csv')
SAC_2008_games_proc.head()

You searched for "Shareef Abdur-Rahim"
1 result found.
Shareef Abdur-Rahim
Results for Shareef Abdur-Rahim:

You searched for "Mike Bibby"
17 results found.
0: Mike Bibby
1: Mike Tobey
2: Mike Barr
3: Mike Bloom
4: Mike Bratz
5: Mike Brown
6: Mike Gibson
7: Mike Maloy
8: Mike Niles
9: Mike Wilks
10: Mike Dabich
11: Mike Davis
12: Mike Davis
13: Mike Lewis
14: Mike Lynn
15: Mike Price
16: Mike Smith
Pick one: 0
Results for Mike Bibby:

You searched for "Quincy Douby"
2 results found.
0: Quincy Douby
1: Quincy Acy
Pick one: 0
Results for Quincy Douby:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Orien Greene"
6 results found.
0: Orien Greene
1: Erick Green
2: Ken Green
3: Donte Greene
4: Rickey Green
5: Tommie Green
Pick one: 0
Results for Orien Greene:

You searched for "Spencer Hawes"
3 results found.
0: Spencer Hawes
1: Steve Hawes
2: Spencer Haywood
Pick one: 0
Results for Spencer Hawes:

You searched for "Anthony Johnson"
8 results found.
0: Anthony Johnson
1: Andy Johnson
2: Armon Johnson
3: Linton Johnson
4: Anthony Jones
5: Anthony Mason
6: Anthony Roberson
7: Anthony Bonner
Pick one: 0
Results for Anthony Johnson:

You searched for "Dahntay Jones"
5 results found.
0: Dahntay Jones
1: Damian Jones
2: Dontae' Jones
3: Johnny Jones
4: Wah Wah Jones
Pick one: 0
Results for Dahntay Jones:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Brad Miller"
12 results found.
0: Brad Miller
1: Bill Miller
2: Bob Miller
3: Jay Miller
4: Brad Sellers
5: Grant Riller
6: Dick Miller
7: Harry Miller
8: Larry Miller
9: Mike Miller
10: Walt Miller
11: Brady Walker
Pick one: 0
Results for Brad Miller:

You searched for "Mikki Moore"
2 results found.
0: Mikki Moore
1: Jackie Moore
Pick one: 0
Results for Mikki Moore:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

You searched for "Darryl Watkins"
2 results found.
0: Darryl Watkins
1: Darryl Dawkins
Pick one: 0
Results for Darryl Watkins:

You searched for "Justin Williams"
10 results found.
0: Justin Williams
1: Jason Williams
2: Alvin Williams
3: Gus Williams
4: Jayson Williams
5: John Williams
6: Jordan Williams
7: Kevin Williams
8: Marvin Williams
9: Sean Williams
Pick one: 0
Results for Justin Williams:

You searched for "Shelden Williams"
3 results found.
0: Shelden Williams
1: Sean Williams
2: Shawne Williams
Pick one: 0
Results for Shelden Williams:

You searched for "Lorenzen Wright"
2 results found.
0: Lorenzen Wright
1: Lonnie Wright
Pick one: 0
Results for Lorenzen Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-03-07,25-035,SAC,HOME,MIN,L (-8),1,41:34,12,23,...,6,1,0,0,1,3,48,37.0,-2,Kevin Martin
1,2008-01-02,28-021,SAC,AWAY,NYK,W (+10),1,44:04,13,18,...,11,6,6,1,3,4,32,35.0,12,John Salmons
2,2007-11-16,24-288,SAC,HOME,NYK,W (+5),1,49:13,11,21,...,10,2,0,0,3,4,43,32.1,12,Kevin Martin
3,2008-03-28,29-320,ATL,HOME,CHI,W (+3),1,41:23,11,15,...,3,8,1,0,0,3,30,30.2,13,Mike Bibby
4,2007-12-18,28-006,SAC,AWAY,NJN,W (+5),1,43:24,13,18,...,4,7,3,0,2,5,31,28.7,12,John Salmons

In [22]:

SAC_2009_gamelog = []

for p in SAC_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2009_gamelog.append(player_log)
SAC_2009_gamelog = pd.concat(SAC_2009_gamelog)    
SAC_2009_gamelogs = SAC_2009_gamelog.copy()
SAC_2009_gamelogs['GAME_SCORE'] = SAC_2009_gamelogs['GAME_SCORE'].astype(float)
SAC_2009_games = SAC_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2009_games_csv = SAC_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2009_games.csv', index=False)
SAC_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2009_games.csv')
SAC_2009_games_proc.head()

You searched for "Calvin Booth"
3 results found.
0: Calvin Booth
1: Calvin Natt
2: Alvin Scott
Pick one: 0
Results for Calvin Booth:

You searched for "Bobby Brown"
14 results found.
0: Bobby Brown
1: Bob Brown
2: Tony Brown
3: Bobby Croft
4: Bruce Brown
5: John Brown
6: Larry Brown
7: Moses Brown
8: Randy Brown
9: Roger Brown
10: Roger Brown
11: Troy Brown
12: Bobby Cook
13: Bobby Lloyd
Pick one: 0
Results for Bobby Brown:

You searched for "Ike Diogu"
4 results found.
0: Ike Diogu
1: Ike Anigbogu
2: Mike Davis
3: Mike Davis
Pick one: 0
Results for Ike Diogu:

You searched for "Quincy Douby"
2 results found.
0: Quincy Douby
1: Quincy Acy
Pick one: 0
Results for Quincy Douby:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Drew Gooden"
3 results found.
0: Drew Gooden
1: Drew Gordon
2: Greg Oden
Pick one: 0
Results for Drew Gooden:

You searched for "Donté Greene"
6 results found.
0: Donte Greene
1: Danny Green
2: Javonte Green
3: Orien Greene
4: Johnny Green
5: Tommie Green
Pick one: 0
Results for Donte Greene:

You searched for "Spencer Hawes"
3 results found.
0: Spencer Hawes
1: Steve Hawes
2: Spencer Haywood
Pick one: 0
Results for Spencer Hawes:

You searched for "Bobby Jackson"
10 results found.
0: Bobby Jackson
1: Tony Jackson
2: Tony Jackson
3: Bobby Watson
4: Josh Jackson
5: Tracy Jackson
6: Bobby Wilson
7: Bobby Wilson
8: Bobby Jones
9: Bobby Jones
Pick one: 0
Results for Bobby Jackson:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Rashad McCants"
1 result found.
Rashad McCants
Results for Rashad McCants:

You searched for "Brad Miller"
12 results found.
0: Brad Miller
1: Bill Miller
2: Bob Miller
3: Jay Miller
4: Brad Sellers
5: Grant Riller
6: Dick Miller
7: Harry Miller
8: Larry Miller
9: Mike Miller
10: Walt Miller
11: Brady Walker
Pick one: 0
Results for Brad Miller:

You searched for "Mikki Moore"
2 results found.
0: Mikki Moore
1: Jackie Moore
Pick one: 0
Results for Mikki Moore:

You searched for "Andrés Nocioni"
1 result found.
Andres Nocioni
Results for Andres Nocioni:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Cedric Simmons"
2 results found.
0: Cedric Simmons
1: Connie Simmons
Pick one: 0
Results for Cedric Simmons:

You searched for "Will Solomon"
1 result found.
Will Solomon
Results for Will Solomon:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

You searched for "Shelden Williams"
3 results found.
0: Shelden Williams
1: Sean Williams
2: Shawne Williams
Pick one: 0
Results for Shelden Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2009-04-01,26-059,SAC,AWAY,GSW,L (-2),1,46:05,11,22,...,3,3,2,0,5,3,50,37.0,-4,Kevin Martin
1,2009-01-27,25-361,SAC,AWAY,CLE,L (-7),1,44:00,8,17,...,7,7,4,1,3,3,35,33.4,-10,Kevin Martin
2,2009-03-17,29-095,CHI,HOME,BOS,W (+6),1,43:19,14,20,...,3,0,1,1,0,3,38,31.0,-1,John Salmons
3,2009-02-08,26-218,SAC,AWAY,OKC,L (-3),1,38:03,11,14,...,6,3,2,1,0,2,29,29.4,5,Beno Udrih
4,2008-11-26,28-350,SAC,HOME,NJN,L (-2),1,50:11,11,19,...,7,0,1,0,2,1,38,28.6,-3,John Salmons

In [23]:

SAC_2010_gamelog = []

for p in SAC_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2010_gamelog.append(player_log)
SAC_2010_gamelog = pd.concat(SAC_2010_gamelog)    
SAC_2010_gamelogs = SAC_2010_gamelog.copy()
SAC_2010_gamelogs['GAME_SCORE'] = SAC_2010_gamelogs['GAME_SCORE'].astype(float)
SAC_2010_games = SAC_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2010_games_csv = SAC_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2010_games.csv', index=False)
SAC_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2010_games.csv')
SAC_2010_games_proc.head()

You searched for "Hilton Armstrong"
1 result found.
Hilton Armstrong
Results for Hilton Armstrong:

You searched for "Jon Brockman"
1 result found.
Jon Brockman
Results for Jon Brockman:

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Joey Dorsey"
4 results found.
0: Joey Dorsey
1: Jacky Dorsey
2: Ron Dorsey
3: Tyler Dorsey
Pick one: 0
Results for Joey Dorsey:

You searched for "Tyreke Evans"
3 results found.
0: Tyreke Evans
1: Jeremy Evans
2: Mike Evans
Pick one: 0
Results for Tyreke Evans:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Donté Greene"
6 results found.
0: Donte Greene
1: Danny Green
2: Javonte Green
3: Orien Greene
4: Johnny Green
5: Tommie Green
Pick one: 0
Results for Donte Greene:

You searched for "Spencer Hawes"
3 results found.
0: Spencer Hawes
1: Steve Hawes
2: Spencer Haywood
Pick one: 0
Results for Spencer Hawes:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Kevin Martin"
15 results found.
0: Kevin Martin
1: Kelan Martin
2: Kenyon Martin
3: Devin Harris
4: Brian Martin
5: Dino Martin
6: Don Martin
7: Jeff Martin
8: Phil Martin
9: Kevin Murphy
10: Kevin Porter
11: Kevin Porter
12: Kevin Durant
13: Kevin Garnett
14: Kevin McHale
Pick one: 0
Results for Kevin Martin:

You searched for "Desmond Mason"
2 results found.
0: Desmond Mason
1: Desmond Bane
Pick one: 0
Results for Desmond Mason:

You searched for "Sean May"
9 results found.
0: Sean May
1: Sean Marks
2: Don May
3: Sam Mack
4: Scott May
5: Allan Ray
6: Don Ray
7: Dean Wade
8: Sun Yue
Pick one: 0
Results for Sean May:

You searched for "Dominic McGuire"
1 result found.
Dominic McGuire
Results for Dominic McGuire:

You searched for "Andrés Nocioni"
1 result found.
Andres Nocioni
Results for Andres Nocioni:

You searched for "Sergio Rodríguez"
1 result found.
Sergio Rodriguez
Results for Sergio Rodriguez:

You searched for "Garrett Temple"
1 result found.
Garrett Temple
Results for Garrett Temple:

You searched for "Kenny Thomas"
9 results found.
0: Kenny Thomas
1: Terry Thomas
2: Kenny Higgs
3: Billy Thomas
4: Etan Thomas
5: John Thomas
6: Khyri Thomas
7: Kurt Thomas
8: Lance Thomas
Pick one: 0
Results for Kenny Thomas:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "Ime Udoka"
2 results found.
0: Ime Udoka
1: Ekpe Udoh
Pick one: 0
Results for Ime Udoka:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2009-11-02,26-274,SAC,HOME,MEM,W (+11),1,52:28,14,27,...,5,4,4,1,3,2,48,38.3,10,Kevin Martin
1,2010-01-18,20-121,SAC,AWAY,CHA,L (-2),1,40:32,13,20,...,4,7,2,3,3,2,34,30.8,6,Tyreke Evans
2,2010-03-14,20-176,SAC,HOME,MIN,W (+14),1,38:45,10,19,...,9,11,2,0,2,2,29,29.7,25,Tyreke Evans
3,2010-04-12,27-070,HOU,AWAY,SAC,W (+10),1,39:50,11,20,...,2,1,0,0,1,3,39,28.5,10,Kevin Martin
4,2010-02-03,20-137,SAC,HOME,SAS,L (-2),1,38:46,11,18,...,7,8,2,1,4,5,32,27.4,5,Tyreke Evans

In [24]:

SAC_2011_gamelog = []

for p in SAC_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2011_gamelog.append(player_log)
SAC_2011_gamelog = pd.concat(SAC_2011_gamelog)    
SAC_2011_gamelogs = SAC_2011_gamelog.copy()
SAC_2011_gamelogs['GAME_SCORE'] = SAC_2011_gamelogs['GAME_SCORE'].astype(float)
SAC_2011_games = SAC_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2011_games_csv = SAC_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2011_games.csv', index=False)
SAC_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2011_games.csv')
SAC_2011_games_proc.head()

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Samuel Dalembert"
1 result found.
Samuel Dalembert
Results for Samuel Dalembert:

You searched for "Tyreke Evans"
3 results found.
0: Tyreke Evans
1: Jeremy Evans
2: Mike Evans
Pick one: 0
Results for Tyreke Evans:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Donté Greene"
6 results found.
0: Donte Greene
1: Danny Green
2: Javonte Green
3: Orien Greene
4: Johnny Green
5: Tommie Green
Pick one: 0
Results for Donte Greene:

You searched for "Luther Head"
2 results found.
0: Luther Head
1: Luther Green
Pick one: 0
Results for Luther Head:

You searched for "Darnell Jackson"
5 results found.
0: Darnell Jackson
1: Wardell Jackson
2: Randell Jackson
3: Jaren Jackson
4: Jaren Jackson
Pick one: 0
Results for Darnell Jackson:

You searched for "Eugene Jeter"
1 result found.
Eugene Jeter
Results for Eugene Jeter:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Jermaine Taylor"
1 result found.
Jermaine Taylor
Results for Jermaine Taylor:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "Marcus Thornton"
2 results found.
0: Marcus Thornton
1: Dallas Thornton
Pick one: 0
Results for Marcus Thornton:

You searched for "Beno Udrih"
2 results found.
0: Beno Udrih
1: Ben Uzoh
Pick one: 0
Results for Beno Udrih:

You searched for "Hassan Whiteside"
1 result found.
Hassan Whiteside
Results for Hassan Whiteside:

You searched for "Antoine Wright"
2 results found.
0: Antoine Wright
1: Antoine Walker
Pick one: 0
Results for Antoine Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2011-03-14,23-282,SAC,HOME,GSW,W (+10),1,41:27,13,20,...,3,1,4,0,0,2,42,37.2,17,Marcus Thornton
1,2011-01-06,21-109,SAC,HOME,DEN,W (+20),1,41:32,11,18,...,5,12,2,0,1,2,27,29.3,15,Tyreke Evans
2,2011-01-04,21-107,SAC,HOME,ATL,L (-6),1,37:36,11,19,...,4,8,5,2,1,5,29,29.1,2,Tyreke Evans
3,2011-01-14,28-193,SAC,AWAY,NYK,W (+10),1,39:49,11,14,...,5,4,4,0,2,3,29,28.3,14,Beno Udrih
4,2011-03-27,23-295,SAC,AWAY,PHI,W (+3),1,49:09,11,21,...,7,4,1,0,1,2,32,26.6,5,Marcus Thornton

In [25]:


SAC_2012_gamelog = []

for p in SAC_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2012_gamelog.append(player_log)
SAC_2012_gamelog = pd.concat(SAC_2012_gamelog)    
SAC_2012_gamelogs = SAC_2012_gamelog.copy()
SAC_2012_gamelogs['GAME_SCORE'] = SAC_2012_gamelogs['GAME_SCORE'].astype(float)
SAC_2012_games = SAC_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2012_games_csv = SAC_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2012_games.csv', index=False)
SAC_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2012_games.csv')
SAC_2012_games_proc.head()

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Tyreke Evans"
3 results found.
0: Tyreke Evans
1: Jeremy Evans
2: Mike Evans
Pick one: 0
Results for Tyreke Evans:

You searched for "Jimmer Fredette"
1 result found.
Jimmer Fredette
Results for Jimmer Fredette:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Donté Greene"
6 results found.
0: Donte Greene
1: Danny Green
2: Javonte Green
3: Orien Greene
4: Johnny Green
5: Tommie Green
Pick one: 0
Results for Donte Greene:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "J.J. Hickson"
3 results found.
0: J.J. Hickson
1: John Dickson
2: D.J. Wilson
Pick one: 0
Results for J.J. Hickson:

You searched for "Tyler Honeycutt"
1 result found.
Tyler Honeycutt
Results for Tyler Honeycutt:

You searched for "Travis Outlaw"
1 result found.
Travis Outlaw
Results for Travis Outlaw:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Isaiah Thomas"
5 results found.
0: Isaiah Thomas
1: Isiah Thomas
2: Isaiah Hicks
3: Irving Thomas
4: Isaiah Taylor
Pick one: 0
Results for Isaiah Thomas:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "Marcus Thornton"
2 results found.
0: Marcus Thornton
1: Dallas Thornton
Pick one: 0
Results for Marcus Thornton:

You searched for "Hassan Whiteside"
1 result found.
Hassan Whiteside
Results for Hassan Whiteside:

You searched for "Terrence Williams"
3 results found.
0: Terrence Williams
1: Bernie Williams
2: Derrick Williams
Pick one: 0
Results for Terrence Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-04-03,21-234,SAC,HOME,PHO,L (-9),1,37:37,16,25,...,12,2,2,1,2,4,41,34.0,3,DeMarcus Cousins
1,2012-03-16,24-285,SAC,HOME,BOS,W (+25),1,44:56,13,24,...,4,4,5,0,1,3,36,31.2,29,Marcus Thornton
2,2012-01-28,22-131,SAC,AWAY,UTA,L (-3),1,40:13,12,20,...,6,9,2,1,4,3,31,29.0,-1,Tyreke Evans
3,2012-03-20,24-289,SAC,HOME,MEM,W (+9),1,42:22,12,22,...,7,6,3,0,1,1,31,28.7,5,Marcus Thornton
4,2012-03-26,21-226,SAC,AWAY,HOU,L (-7),1,49:33,15,26,...,14,2,2,1,5,4,38,28.7,-2,DeMarcus Cousins

In [26]:

SAC_2013_gamelog = []

for p in SAC_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2013_gamelog.append(player_log)
SAC_2013_gamelog = pd.concat(SAC_2013_gamelog)    
SAC_2013_gamelogs = SAC_2013_gamelog.copy()
SAC_2013_gamelogs['GAME_SCORE'] = SAC_2013_gamelogs['GAME_SCORE'].astype(float)
SAC_2013_games = SAC_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2013_games_csv = SAC_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2013_games.csv', index=False)
SAC_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2013_games.csv')
SAC_2013_games_proc.head()

You searched for "Cole Aldrich"
1 result found.
Cole Aldrich
Results for Cole Aldrich:

You searched for "Aaron Brooks"
5 results found.
0: Aaron Brooks
1: MarShon Brooks
2: Dillon Brooks
3: Kevin Brooks
4: Aaron Gordon
Pick one: 0
Results for Aaron Brooks:

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Toney Douglas"
4 results found.
0: Toney Douglas
1: John Douglas
2: Leon Douglas
3: Tony Dumas
Pick one: 0
Results for Toney Douglas:

You searched for "Tyreke Evans"
3 results found.
0: Tyreke Evans
1: Jeremy Evans
2: Mike Evans
Pick one: 0
Results for Tyreke Evans:

You searched for "Jimmer Fredette"
1 result found.
Jimmer Fredette
Results for Jimmer Fredette:

You searched for "Francisco García"
1 result found.
Francisco Garcia
Results for Francisco Garcia:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Tyler Honeycutt"
1 result found.
Tyler Honeycutt
Results for Tyler Honeycutt:

You searched for "James Johnson"
32 results found.
0: James Johnson
1: Amir Johnson
2: Dave Johnson
3: Joe Johnson
4: James Robinson
5: James Cotton
6: Andy Johnson
7: Armon Johnson
8: Avery Johnson
9: Cameron Johnson
10: Charles Johnson
11: Cheese Johnson
12: Chris Johnson
13: Chris Johnson
14: Ed Johnson
15: Gus Johnson
16: JaJuan Johnson
17: John Johnson
18: Ken Johnson
19: Ken Johnson
20: Larry Johnson
21: Larry Johnson
22: Lee Johnson
23: Magic Johnson
24: Marques Johnson
25: Ralph Johnson
26: Stew Johnson
27: Trey Johnson
28: Tyler Johnson
29: Nate Johnston
30: James Jones
31: James Collins
Pick one: 0
Results for James Johnson:

You searched for "Travis Outlaw"
1 result found.
Travis Outlaw
Results for Travis Outlaw:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "Thomas Robinson"
4 results found.
0: Thomas Robinson
1: Chris Robinson
2: Jamal Robinson
3: James Robinson
Pick one: 0
Results for Thomas Robinson:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Isaiah Thomas"
5 results found.
0: Isaiah Thomas
1: Isiah Thomas
2: Isaiah Hicks
3: Irving Thomas
4: Isaiah Taylor
Pick one: 0
Results for Isaiah Thomas:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "Marcus Thornton"
2 results found.
0: Marcus Thornton
1: Dallas Thornton
Pick one: 0
Results for Marcus Thornton:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-04-17,22-247,SAC,HOME,LAC,L (-4),1,41:23,14,24,...,22,3,0,3,3,4,36,31.4,2,DeMarcus Cousins
1,2013-03-28,22-227,SAC,AWAY,PHO,W (+14),1,30:00,12,16,...,14,2,1,1,5,4,34,30.3,11,DeMarcus Cousins
2,2013-01-04,22-144,SAC,AWAY,TOR,W (+9),1,32:44,11,18,...,20,4,2,0,4,4,31,29.2,18,DeMarcus Cousins
3,2013-03-08,24-029,SAC,HOME,PHO,W (+9),1,33:03,8,13,...,5,6,5,0,2,3,27,29.0,20,Isaiah Thomas
4,2013-03-13,23-175,SAC,HOME,CHI,W (+42),1,36:24,11,13,...,5,7,3,1,2,3,26,28.2,33,Tyreke Evans

In [29]:
# removed Hamady N'Diaye

SAC_2014_gamelog = []

for p in SAC_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2014_gamelog.append(player_log)
SAC_2014_gamelog = pd.concat(SAC_2014_gamelog)    
SAC_2014_gamelogs = SAC_2014_gamelog.copy()
SAC_2014_gamelogs['GAME_SCORE'] = SAC_2014_gamelogs['GAME_SCORE'].astype(float)
SAC_2014_games = SAC_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2014_games_csv = SAC_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2014_games.csv', index=False)
SAC_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2014_games.csv')
SAC_2014_games_proc.head()

You searched for "Quincy Acy"
2 results found.
0: Quincy Acy
1: Quincy Douby
Pick one: 0
Results for Quincy Acy:

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Jared Cunningham"
2 results found.
0: Jared Cunningham
1: Dante Cunningham
Pick one: 0
Results for Jared Cunningham:

You searched for "Reggie Evans"
10 results found.
0: Reggie Evans
1: Reggie Geary
2: Reggie Hanson
3: Reggie Hearn
4: Reggie King
5: Reggie Lewis
6: Reggie Royals
7: Reggie Theus
8: Reggie Perry
9: Reggie Jordan
Pick one: 0
Results for Reggie Evans:

You searched for "Jimmer Fredette"
1 result found.
Jimmer Fredette
Results for Jimmer Fredette:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Aaron Gray"
8 results found.
0: Aaron Gray
1: Gary Gray
2: Aaron Gordon
3: Devin Gray
4: Evric Gray
5: Allan Ray
6: Don Ray
7: Don Grate
Pick one: 0
Results for Aaron Gray:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Orlando Johnson"
3 results found.
0: Orlando Johnson
1: Andy Johnson
2: Frank Johnson
Pick one: 0
Results for Orlando Johnson:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Luc Mbah a Moute"
1 result found.
Luc Mbah a Moute
Results for Luc Mbah a Moute:

You searched for "Ray McCallum"
2 results found.
0: Ray McCallum
1: CJ McCollum
Pick one: 0
Results for Ray McCallum:

You searched for "Ben McLemore"
3 results found.
0: Ben McLemore
1: Len Elmore
2: Ben Moore
Pick one: 0
Results for Ben McLemore:

You searched for "Travis Outlaw"
1 result found.
Travis Outlaw
Results for Travis Outlaw:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Isaiah Thomas"
5 results found.
0: Isaiah Thomas
1: Isiah Thomas
2: Isaiah Hicks
3: Irving Thomas
4: Isaiah Taylor
Pick one: 0
Results for Isaiah Thomas:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "Marcus Thornton"
2 results found.
0: Marcus Thornton
1: Dallas Thornton
Pick one: 0
Results for Marcus Thornton:

You searched for "Greivis Vásquez"
1 result found.
Greivis Vasquez
Results for Greivis Vasquez:

You searched for "Royce White"
10 results found.
0: Royce White
1: Rodney White
2: Rory White
3: Coby White
4: Eric White
5: Hubie White
6: Jo Jo White
7: Randy White
8: Rudy White
9: Tony White
Pick one: 0
Results for Royce White:

You searched for "Derrick Williams"
8 results found.
0: Derrick Williams
1: Patrick Williams
2: Eric Williams
3: Kenrich Williams
4: Bernie Williams
5: Deron Williams
6: Duck Williams
7: Terrence Williams
Pick one: 0
Results for Derrick Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-03-26,23-225,SAC,HOME,NYK,L (-8),1,42:57,10,15,...,15,8,2,2,4,4,32,35.0,-4,DeMarcus Cousins
1,2014-01-31,27-167,SAC,AWAY,DAL,L (-4),1,35:36,10,16,...,12,6,1,0,3,0,35,34.0,5,Rudy Gay
2,2014-03-31,23-230,SAC,AWAY,NOP,W (+5),1,37:26,13,18,...,14,3,1,2,3,3,35,32.1,22,DeMarcus Cousins
3,2014-01-19,24-346,SAC,AWAY,OKC,L (-15),1,39:06,11,18,...,1,6,0,0,1,2,38,32.1,-6,Isaiah Thomas
4,2014-03-23,23-222,SAC,HOME,MIL,W (+17),1,29:07,14,19,...,12,4,2,1,1,3,32,31.2,35,DeMarcus Cousins

In [30]:


SAC_2015_gamelog = []

for p in SAC_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2015_gamelog.append(player_log)
SAC_2015_gamelog = pd.concat(SAC_2015_gamelog)    
SAC_2015_gamelogs = SAC_2015_gamelog.copy()
SAC_2015_gamelogs['GAME_SCORE'] = SAC_2015_gamelogs['GAME_SCORE'].astype(float)
SAC_2015_games = SAC_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2015_games_csv = SAC_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2015_games.csv', index=False)
SAC_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2015_games.csv')
SAC_2015_games_proc.head()

You searched for "Sim Bhullar"
1 result found.
Sim Bhullar
Results for Sim Bhullar:

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Darren Collison"
3 results found.
0: Darren Collison
1: Darren Tillis
2: Jarron Collins
Pick one: 0
Results for Darren Collison:

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Reggie Evans"
10 results found.
0: Reggie Evans
1: Reggie Geary
2: Reggie Hanson
3: Reggie Hearn
4: Reggie King
5: Reggie Lewis
6: Reggie Royals
7: Reggie Theus
8: Reggie Perry
9: Reggie Jordan
Pick one: 0
Results for Reggie Evans:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Ryan Hollins"
3 results found.
0: Ryan Hollins
1: Don Collins
2: John Collins
Pick one: 0
Results for Ryan Hollins:

You searched for "Carl Landry"
4 results found.
0: Carl Landry
1: Carl Henry
2: Carl Bailey
3: Marcus Landry
Pick one: 0
Results for Carl Landry:

You searched for "Ray McCallum"
2 results found.
0: Ray McCallum
1: CJ McCollum
Pick one: 0
Results for Ray McCallum:

You searched for "Ben McLemore"
3 results found.
0: Ben McLemore
1: Len Elmore
2: Ben Moore
Pick one: 0
Results for Ben McLemore:

You searched for "Andre Miller"
7 results found.
0: Andre Miller
1: Eddie Miller
2: Harry Miller
3: Larry Miller
4: Mike Miller
5: Andre Moore
6: Andre Turner
Pick one: 0
Results for Andre Miller:

You searched for "Quincy Miller"
3 results found.
0: Quincy Miller
1: Dick Miller
2: Quincy Lewis
Pick one: 0
Results for Quincy Miller:

You searched for "Eric Moreland"
1 result found.
Eric Moreland
Results for Eric Moreland:

You searched for "Ramon Sessions"
1 result found.
Ramon Sessions
Results for Ramon Sessions:

You searched for "Nik Stauskas"
1 result found.
Nik Stauskas
Results for Nik Stauskas:

You searched for "David Stockton"
1 result found.
David Stockton
Results for David Stockton:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "David Wear"
12 results found.
0: David Wear
1: David West
2: David Lee
3: David Lee
4: Travis Wear
5: David Wood
6: David Noel
7: David Nwaba
8: David Pope
9: David Wesley
10: David Cooke
11: Acie Earl
Pick one: 0
Results for David Wear:

You searched for "Derrick Williams"
8 results found.
0: Derrick Williams
1: Patrick Williams
2: Eric Williams
3: Kenrich Williams
4: Bernie Williams
5: Deron Williams
6: Duck Williams
7: Terrence Williams
Pick one: 0
Results for Derrick Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2015-03-13,24-212,SAC,AWAY,PHI,L (-7),1,40:14,12,24,...,24,1,2,1,3,2,39,35.4,5,DeMarcus Cousins
1,2014-10-31,28-075,SAC,HOME,POR,W (+9),1,36:25,13,19,...,8,1,1,0,0,2,40,35.2,14,Rudy Gay
2,2015-03-27,24-226,SAC,AWAY,NOP,L (-14),1,41:00,16,28,...,20,2,1,3,3,3,39,33.3,-1,DeMarcus Cousins
3,2015-03-06,28-201,SAC,AWAY,ORL,L (-5),1,41:56,16,26,...,8,3,3,2,5,2,39,31.9,-5,Rudy Gay
4,2014-11-22,24-101,SAC,AWAY,MIN,W (+12),1,39:22,11,15,...,18,2,1,2,3,4,31,31.5,17,DeMarcus Cousins

In [31]:


SAC_2016_gamelog = []

for p in SAC_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2016_gamelog.append(player_log)
SAC_2016_gamelog = pd.concat(SAC_2016_gamelog)    
SAC_2016_gamelogs = SAC_2016_gamelog.copy()
SAC_2016_gamelogs['GAME_SCORE'] = SAC_2016_gamelogs['GAME_SCORE'].astype(float)
SAC_2016_games = SAC_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2016_games_csv = SAC_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2016_games.csv', index=False)
SAC_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2016_games.csv')
SAC_2016_games_proc.head()

You searched for "Quincy Acy"
2 results found.
0: Quincy Acy
1: Quincy Douby
Pick one: 0
Results for Quincy Acy:

You searched for "James Anderson"
10 results found.
0: James Anderson
1: Alan Anderson
2: Dan Anderson
3: Dan Anderson
4: Derek Anderson
5: Greg Anderson
6: J.J. Anderson
7: Jerome Anderson
8: Kim Anderson
9: Kyle Anderson
Pick one: 0
Results for James Anderson:

You searched for "Marco Belinelli"
1 result found.
Marco Belinelli
Results for Marco Belinelli:

You searched for "Caron Butler"
4 results found.
0: Caron Butler
1: Al Butler
2: Greg Butler
3: Carl Fuller
Pick one: 0
Results for Caron Butler:

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Willie Cauley-Stein"
1 result found.
Willie Cauley-Stein
Results for Willie Cauley-Stein:

You searched for "Darren Collison"
3 results found.
0: Darren Collison
1: Darren Tillis
2: Jarron Collins
Pick one: 0
Results for Darren Collison:

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Seth Curry"
4 results found.
0: Seth Curry
1: Dell Curry
2: Eddy Curry
3: Stephen Curry
Pick one: 0
Results for Seth Curry:

You searched for "Duje Dukan"
1 result found.
Duje Dukan
Results for Duje Dukan:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Kosta Koufos"
1 result found.
Kosta Koufos
Results for Kosta Koufos:

You searched for "Ben McLemore"
3 results found.
0: Ben McLemore
1: Len Elmore
2: Ben Moore
Pick one: 0
Results for Ben McLemore:

You searched for "Eric Moreland"
1 result found.
Eric Moreland
Results for Eric Moreland:

You searched for "Rajon Rondo"
2 results found.
0: Rajon Rondo
1: Brandon Roy
Pick one: 0
Results for Rajon Rondo:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-01-25,25-165,SAC,HOME,CHO,L (-1),1,45:40,21,30,...,12,4,1,2,7,6,56,42.0,15,DeMarcus Cousins
1,2016-01-23,25-163,SAC,HOME,IND,W (+11),1,39:07,17,29,...,13,2,1,0,5,4,48,32.2,16,DeMarcus Cousins
2,2016-03-07,25-207,SAC,AWAY,NOP,L (-3),1,41:08,16,29,...,16,4,4,1,5,4,40,32.2,9,DeMarcus Cousins
3,2016-01-20,25-160,SAC,AWAY,LAL,W (+19),1,35:01,13,22,...,16,3,1,1,2,5,36,32.0,26,DeMarcus Cousins
4,2016-02-19,25-190,SAC,HOME,DEN,W (+6),1,38:43,12,20,...,20,2,1,4,6,4,37,30.6,4,DeMarcus Cousins

In [32]:

SAC_2017_gamelog = []

for p in SAC_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2017_gamelog.append(player_log)
SAC_2017_gamelog = pd.concat(SAC_2017_gamelog)    
SAC_2017_gamelogs = SAC_2017_gamelog.copy()
SAC_2017_gamelogs['GAME_SCORE'] = SAC_2017_gamelogs['GAME_SCORE'].astype(float)
SAC_2017_games = SAC_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2017_games_csv = SAC_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2017_games.csv', index=False)
SAC_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2017_games.csv')
SAC_2017_games_proc.head()

You searched for "Arron Afflalo"
1 result found.
Arron Afflalo
Results for Arron Afflalo:

You searched for "Matt Barnes"
10 results found.
0: Matt Barnes
1: Matt Bonner
2: Marty Byrnes
3: Harry Barnes
4: Jim Barnes
5: Marvin Barnes
6: Matt Maloney
7: Matt Mooney
8: Matt Walsh
9: Matt Bullard
Pick one: 0
Results for Matt Barnes:

You searched for "Omri Casspi"
1 result found.
Omri Casspi
Results for Omri Casspi:

You searched for "Willie Cauley-Stein"
1 result found.
Willie Cauley-Stein
Results for Willie Cauley-Stein:

You searched for "Darren Collison"
3 results found.
0: Darren Collison
1: Darren Tillis
2: Jarron Collins
Pick one: 0
Results for Darren Collison:

You searched for "DeMarcus Cousins"
2 results found.
0: DeMarcus Cousins
1: Marcus Cousin
Pick one: 0
Results for DeMarcus Cousins:

You searched for "Tyreke Evans"
3 results found.
0: Tyreke Evans
1: Jeremy Evans
2: Mike Evans
Pick one: 0
Results for Tyreke Evans:

You searched for "Jordan Farmar"
4 results found.
0: Jordan Farmar
1: Jordan Ford
2: Jordan McRae
3: Jordan Adams
Pick one: 0
Results for Jordan Farmar:

You searched for "Langston Galloway"
1 result found.
Langston Galloway
Results for Langston Galloway:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Buddy Hield"
1 result found.
Buddy Hield
Results for Buddy Hield:

You searched for "Kosta Koufos"
1 result found.
Kosta Koufos
Results for Kosta Koufos:

You searched for "Skal Labissière"
1 result found.
Skal Labissiere
Results for Skal Labissiere:

You searched for "Ty Lawson"
3 results found.
0: Ty Lawson
1: Tony Dawson
2: Mo Layton
Pick one: 0
Results for Ty Lawson:

You searched for "Ben McLemore"
3 results found.
0: Ben McLemore
1: Len Elmore
2: Ben Moore
Pick one: 0
Results for Ben McLemore:

You searched for "Georgios Papagiannis"
1 result found.
Georgios Papagiannis
Results for Georgios Papagiannis:

You searched for "Malachi Richardson"
1 result found.
Malachi Richardson
Results for Malachi Richardson:

You searched for "Garrett Temple"
1 result found.
Garrett Temple
Results for Garrett Temple:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-12-20,26-129,SAC,HOME,POR,W (+5),1,40:35,17,28,...,14,1,1,3,5,5,55,43.2,3,DeMarcus Cousins
1,2017-01-30,26-170,SAC,AWAY,PHI,L (-3),1,32:16,11,16,...,15,5,1,1,8,6,46,39.3,-6,DeMarcus Cousins
2,2017-03-21,26-220,NOP,HOME,MEM,W (+13),1,36:48,14,27,...,16,2,2,2,2,5,41,34.5,22,DeMarcus Cousins
3,2017-01-21,26-161,SAC,AWAY,CHI,L (-3),1,35:23,16,28,...,14,3,1,2,2,4,42,34.3,-6,DeMarcus Cousins
4,2016-11-27,26-106,SAC,AWAY,BRK,W (+17),1,35:45,13,24,...,11,2,4,1,1,2,37,33.0,17,DeMarcus Cousins

In [35]:


SAC_2018_gamelog = []

for p in SAC_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2018_gamelog.append(player_log)
SAC_2018_gamelog = pd.concat(SAC_2018_gamelog)    
SAC_2018_gamelogs = SAC_2018_gamelog.copy()
SAC_2018_gamelogs['GAME_SCORE'] = SAC_2018_gamelogs['GAME_SCORE'].astype(float)
SAC_2018_games = SAC_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2018_games_csv = SAC_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2018_games.csv', index=False)
SAC_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2018_games.csv')
SAC_2018_games_proc.head()

You searched for "Bogdan Bogdanović"
2 results found.
0: Bogdan Bogdanovic
1: Bojan Bogdanovic
Pick one: 0
Results for Bogdan Bogdanovic:

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Willie Cauley-Stein"
1 result found.
Willie Cauley-Stein
Results for Willie Cauley-Stein:

You searched for "Jack Cooley"
15 results found.
0: Jack Cooley
1: Jack Foley
2: Jack Haley
3: Jack Kiley
4: Jack Smiley
5: Jack Toomay
6: Jack Coleman
7: Ray Corley
8: Jack Cotton
9: Jacky Dorsey
10: Jack Rocker
11: Jack George
12: Jackie Moore
13: Jack Nichols
14: Jack Tingle
Pick one: 0
Results for Jack Cooley:

You searched for "De'Aaron Fox"
1 result found.
De'Aaron Fox
Results for De'Aaron Fox:

You searched for "Nigel Hayes"
2 results found.
0: Nigel Hayes
1: Jim Hayes
Pick one: 0
Results for Nigel Hayes:

You searched for "Buddy Hield"
1 result found.
Buddy Hield
Results for Buddy Hield:

You searched for "George Hill"
11 results found.
0: George Hill
1: George Karl
2: George King
3: George King
4: Gary Hill
5: George Lee
6: George Mikan
7: George Wilson
8: George Zidek
9: George Bucci
10: George Lynch
Pick one: 0
Results for George Hill:

You searched for "Justin Jackson"
8 results found.
0: Justin Jackson
1: Jaren Jackson
2: Jaren Jackson
3: Jim Jackson
4: Josh Jackson
5: Mervin Jackson
6: Justin James
7: Justin Patton
Pick one: 0
Results for Justin Jackson:

You searched for "Kosta Koufos"
1 result found.
Kosta Koufos
Results for Kosta Koufos:

You searched for "Skal Labissière"
1 result found.
Skal Labissiere
Results for Skal Labissiere:

You searched for "Georgios Papagiannis"
1 result found.
Georgios Papagiannis
Results for Georgios Papagiannis:

You searched for "Zach Randolph"
1 result found.
Zach Randolph
Results for Zach Randolph:

You searched for "Malachi Richardson"
1 result found.
Malachi Richardson
Results for Malachi Richardson:

You searched for "JaKarr Sampson"
2 results found.
0: JaKarr Sampson
1: Jamal Sampson
Pick one: 0
Results for JaKarr Sampson:

You searched for "Garrett Temple"
1 result found.
Garrett Temple
Results for Garrett Temple:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-12-08,36-145,SAC,AWAY,NOP,W (+7),1,33:54,14,22,...,13,2,1,0,3,4,35,28.1,4,Zach Randolph
1,2018-01-17,31-258,SAC,HOME,UTA,L (-15),1,36:38,6,10,...,4,5,3,0,0,0,20,23.5,-12,George Hill
2,2018-03-04,25-198,SAC,HOME,NYK,W (+3),1,27:23,7,11,...,1,7,1,0,0,1,22,22.9,10,Bogdan Bogdanović
3,2017-12-01,36-138,SAC,AWAY,CHI,W (+1),1,31:41,12,19,...,13,3,0,1,1,1,25,22.6,10,Zach Randolph
4,2018-04-11,24-236,SAC,HOME,HOU,W (+13),1,30:24,9,12,...,11,4,1,0,1,1,22,22.5,3,Willie Cauley-Stein

In [40]:
# removed Marvin BAgley
SAC_2019_gamelog = []

for p in SAC_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2019_gamelog.append(player_log)
SAC_2019_gamelog = pd.concat(SAC_2019_gamelog)    
SAC_2019_gamelogs = SAC_2019_gamelog.copy()
SAC_2019_gamelogs['GAME_SCORE'] = SAC_2019_gamelogs['GAME_SCORE'].astype(float)
SAC_2019_games = SAC_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2019_games_csv = SAC_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2019_games.csv', index=False)
SAC_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2019_games.csv')
SAC_2019_games_proc.head()

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Nemanja Bjelica"
1 result found.
Nemanja Bjelica
Results for Nemanja Bjelica:

You searched for "Bogdan Bogdanović"
2 results found.
0: Bogdan Bogdanovic
1: Bojan Bogdanovic
Pick one: 0
Results for Bogdan Bogdanovic:

You searched for "Corey Brewer"
4 results found.
0: Corey Brewer
1: Corey Crowder
2: Corey Beck
3: Ron Brewer
Pick one: 0
Results for Corey Brewer:

You searched for "Alec Burks"
3 results found.
0: Alec Burks
1: Trey Burke
2: Alex Kirk
Pick one: 0
Results for Alec Burks:

You searched for "Willie Cauley-Stein"
1 result found.
Willie Cauley-Stein
Results for Willie Cauley-Stein:

You searched for "Yogi Ferrell"
1 result found.
Yogi Ferrell
Results for Yogi Ferrell:

You searched for "De'Aaron Fox"
1 result found.
De'Aaron Fox
Results for De'Aaron Fox:

You searched for "Harry Giles"
15 results found.
0: Harry Giles
1: Harry Miller
2: Harry Barnes
3: Harry Davis
4: Harry Dinnel
5: Larry Jones
6: Aaron Miles
7: Larry Miller
8: Terry Mills
9: Harry Rogers
10: Larry Sykes
11: Garry Witts
12: Barry Yates
13: Harry Zeller
14: Larry Fogle
Pick one: 0
Results for Harry Giles:

You searched for "Buddy Hield"
1 result found.
Buddy Hield
Results for Buddy Hield:

You searched for "Justin Jackson"
8 results found.
0: Justin Jackson
1: Jaren Jackson
2: Jaren Jackson
3: Jim Jackson
4: Josh Jackson
5: Mervin Jackson
6: Justin James
7: Justin Patton
Pick one: 0
Results for Justin Jackson:

You searched for "B.J. Johnson"
22 results found.
0: B.J. Johnson
1: Buck Johnson
2: Amir Johnson
3: Andy Johnson
4: Brice Johnson
5: Clay Johnson
6: Dave Johnson
7: Ed Johnson
8: Eric Johnson
9: Gus Johnson
10: Ivan Johnson
11: Joe Johnson
12: John Johnson
13: Ken Johnson
14: Ken Johnson
15: Lee Johnson
16: Neil Johnson
17: Nick Johnson
18: Rich Johnson
19: Ron Johnson
20: Stew Johnson
21: Trey Johnson
Pick one: 0
Results for B.J. Johnson:

You searched for "Kosta Koufos"
1 result found.
Kosta Koufos
Results for Kosta Koufos:

You searched for "Skal Labissière"
1 result found.
Skal Labissiere
Results for Skal Labissiere:

You searched for "Ben McLemore"
3 results found.
0: Ben McLemore
1: Len Elmore
2: Ben Moore
Pick one: 0
Results for Ben McLemore:

You searched for "Iman Shumpert"
1 result found.
Iman Shumpert
Results for Iman Shumpert:

You searched for "Caleb Swanigan"
1 result found.
Caleb Swanigan
Results for Caleb Swanigan:

You searched for "Troy Williams"
46 results found.
0: Troy Williams
1: Ray Williams
2: Rob Williams
3: Ron Williams
4: Aaron Williams
5: Art Williams
6: Bob Williams
7: Corey Williams
8: Deron Williams
9: Eric Williams
10: Fly Williams
11: Guy Williams
12: Jay Williams
13: Lou Williams
14: Mo Williams
15: Sly Williams
16: Al Williams
17: Alan Williams
18: Buck Williams
19: C.J. Williams
20: Duck Williams
21: Earl Williams
22: Frank Williams
23: Gene Williams
24: Grant Williams
25: Gus Williams
26: Hank Williams
27: Herb Williams
28: Hot Rod Williams
29: Jason Williams
30: Jerome Williams
31: John Williams
32: Kenny Williams
33: Matt Williams
34: Mike Williams
35: Milt Williams
36: Monty Williams
37: Nate Williams
38: Pete Williams
39: Sam Williams
40: Sam Williams
41: Scott Williams
42: Sean Williams
43: Travis Williams
44: Walt Williams
45: Ward Williams
Pick one: 0
Results for Troy Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-11-01,20-316,SAC,AWAY,ATL,W (+31),1,33:55,9,13,...,10,15,1,0,3,3,31,36.6,34,De'Aaron Fox
1,2018-12-07,20-352,SAC,AWAY,CLE,W (+19),1,29:03,12,16,...,2,12,3,0,1,4,30,32.6,31,De'Aaron Fox
2,2019-01-19,26-033,SAC,AWAY,DET,W (+2),1,37:33,13,22,...,9,3,0,1,1,3,35,29.3,10,Buddy Hield
3,2018-12-19,26-002,SAC,HOME,OKC,L (-19),1,34:57,11,25,...,6,3,2,0,0,2,37,29.0,-11,Buddy Hield
4,2018-12-19,20-364,SAC,HOME,OKC,L (-19),1,37:07,10,18,...,3,12,2,2,4,0,28,27.3,-9,De'Aaron Fox

In [43]:
# removed kelly oubre

SAC_2020_gamelog = []

for p in SAC_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2020_gamelog.append(player_log)
SAC_2020_gamelog = pd.concat(SAC_2020_gamelog)    
SAC_2020_gamelogs = SAC_2020_gamelog.copy()
SAC_2020_gamelogs['GAME_SCORE'] = SAC_2020_gamelogs['GAME_SCORE'].astype(float)
SAC_2020_games = SAC_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2020_games_csv = SAC_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2020_games.csv', index=False)
SAC_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2020_games.csv')
SAC_2020_games_proc.head()

You searched for "Trevor Ariza"
1 result found.
Trevor Ariza
Results for Trevor Ariza:

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Kent Bazemore"
1 result found.
Kent Bazemore
Results for Kent Bazemore:

You searched for "Nemanja Bjelica"
1 result found.
Nemanja Bjelica
Results for Nemanja Bjelica:

You searched for "Bogdan Bogdanović"
2 results found.
0: Bogdan Bogdanovic
1: Bojan Bogdanovic
Pick one: 0
Results for Bogdan Bogdanovic:

You searched for "Corey Brewer"
4 results found.
0: Corey Brewer
1: Corey Crowder
2: Corey Beck
3: Ron Brewer
Pick one: 0
Results for Corey Brewer:

You searched for "Dewayne Dedmon"
1 result found.
Dewayne Dedmon
Results for Dewayne Dedmon:

You searched for "Yogi Ferrell"
1 result found.
Yogi Ferrell
Results for Yogi Ferrell:

You searched for "De'Aaron Fox"
1 result found.
De'Aaron Fox
Results for De'Aaron Fox:

You searched for "Wenyen Gabriel"
1 result found.
Wenyen Gabriel
Results for Wenyen Gabriel:

You searched for "Harry Giles"
15 results found.
0: Harry Giles
1: Harry Miller
2: Harry Barnes
3: Harry Davis
4: Harry Dinnel
5: Larry Jones
6: Aaron Miles
7: Larry Miller
8: Terry Mills
9: Harry Rogers
10: Larry Sykes
11: Garry Witts
12: Barry Yates
13: Harry Zeller
14: Larry Fogle
Pick one: 0
Results for Harry Giles:

You searched for "Kyle Guy"
5 results found.
0: Kyle Guy
1: Kyle Macy
2: Tyler Bey
3: Kyle Kuzma
4: Kyle Lowry
Pick one: 0
Results for Kyle Guy:

You searched for "Buddy Hield"
1 result found.
Buddy Hield
Results for Buddy Hield:

You searched for "Richaun Holmes"
1 result found.
Richaun Holmes
Results for Richaun Holmes:

You searched for "Justin James"
6 results found.
0: Justin James
1: Austin Daye
2: Justin Harper
3: Justin Jackson
4: Tim James
5: Justin Reed
Pick one: 0
Results for Justin James:

You searched for "DaQuan Jeffries"
1 result found.
DaQuan Jeffries
Results for DaQuan Jeffries:

You searched for "Cory Joseph"
4 results found.
0: Cory Joseph
1: Garth Joseph
2: Kris Joseph
3: Yvon Joseph
Pick one: 0
Results for Cory Joseph:

You searched for "Alex Len"
7 results found.
0: Alex Len
1: Saben Lee
2: Alex Acker
3: Alex Kirk
4: Greg Lee
5: Alex Scales
6: Hal Hale
Pick one: 0
Results for Alex Len:

You searched for "Eric Mika"
6 results found.
0: Eric Mika
1: Ed Mikan
2: Eric Money
3: Eric Riley
4: Eric Snow
5: Eric White
Pick one: 0
Results for Eric Mika:

You searched for "Jabari Parker"
1 result found.
Jabari Parker
Results for Jabari Parker:

You searched for "Caleb Swanigan"
1 result found.
Caleb Swanigan
Results for Caleb Swanigan:

You searched for "Anthony Tolliver"
3 results found.
0: Anthony Tolliver
1: Anthony Miller
2: Anthony Goldwire
Pick one: 0
Results for Anthony Tolliver:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-01-13,31-249,SAC,HOME,ORL,L (-2),1,33:15,13,16,...,7,2,2,0,1,3,34,31.3,6,Nemanja Bjelica
1,2020-01-02,22-013,SAC,HOME,MEM,W (+5),1,29:53,9,18,...,4,9,5,2,1,3,27,30.1,9,De'Aaron Fox
2,2020-08-06,27-354,SAC,HOME,NOP,W (+15),1,37:29,13,20,...,4,3,1,0,0,3,35,29.7,16,Bogdan Bogdanović
3,2020-01-30,22-041,SAC,AWAY,LAC,W (+21),1,35:12,14,24,...,3,8,4,2,3,3,34,29.7,13,De'Aaron Fox
4,2020-01-13,22-024,SAC,HOME,ORL,L (-2),1,37:21,12,18,...,8,10,1,1,4,3,31,29.5,-3,De'Aaron Fox

In [47]:
# remvoed Marvin Bagley
SAC_2021_gamelog = []

for p in SAC_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    SAC_2021_gamelog.append(player_log)
SAC_2021_gamelog = pd.concat(SAC_2021_gamelog)    
SAC_2021_gamelogs = SAC_2021_gamelog.copy()
SAC_2021_gamelogs['GAME_SCORE'] = SAC_2021_gamelogs['GAME_SCORE'].astype(float)
SAC_2021_games = SAC_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_2021_games_csv = SAC_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2021_games.csv', index=False)
SAC_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2021_games.csv')
SAC_2021_games_proc.head()

You searched for "Harrison Barnes"
3 results found.
0: Harrison Barnes
1: Harry Barnes
2: Marvin Barnes
Pick one: 0
Results for Harrison Barnes:

You searched for "Nemanja Bjelica"
1 result found.
Nemanja Bjelica
Results for Nemanja Bjelica:

You searched for "Terence Davis"
3 results found.
0: Terence Davis
1: Terry Davis
2: Terence Morris
Pick one: 0
Results for Terence Davis:

You searched for "De'Aaron Fox"
1 result found.
De'Aaron Fox
Results for De'Aaron Fox:

You searched for "Kyle Guy"
5 results found.
0: Kyle Guy
1: Kyle Macy
2: Tyler Bey
3: Kyle Kuzma
4: Kyle Lowry
Pick one: 0
Results for Kyle Guy:

You searched for "Tyrese Haliburton"
1 result found.
Tyrese Haliburton
Results for Tyrese Haliburton:

You searched for "Maurice Harkless"
2 results found.
0: Maurice Harkless
1: Maurice McHartley
Pick one: 0
Results for Maurice Harkless:

You searched for "Buddy Hield"
1 result found.
Buddy Hield
Results for Buddy Hield:

You searched for "Richaun Holmes"
1 result found.
Richaun Holmes
Results for Richaun Holmes:

You searched for "Justin James"
6 results found.
0: Justin James
1: Austin Daye
2: Justin Harper
3: Justin Jackson
4: Tim James
5: Justin Reed
Pick one: 0
Results for Justin James:

You searched for "DaQuan Jeffries"
1 result found.
DaQuan Jeffries
Results for DaQuan Jeffries:

You searched for "Damian Jones"
14 results found.
0: Damian Jones
1: Damon Jones
2: Damion James
3: DeQuan Jones
4: Mason Jones
5: Alvin Jones
6: Askia Jones
7: Dahntay Jones
8: Jalen Jones
9: James Jones
10: Kevin Jones
11: Robin Jones
12: Sam Jones
13: Wali Jones
Pick one: 0
Results for Damian Jones:

You searched for "Cory Joseph"
4 results found.
0: Cory Joseph
1: Garth Joseph
2: Kris Joseph
3: Yvon Joseph
Pick one: 0
Results for Cory Joseph:

You searched for "Louis King"
7 results found.
0: Louis King
1: Chris King
2: Loyd King
3: Jim King
4: Ron King
5: Tom King
6: Louis Orr
Pick one: 0
Results for Louis King:

You searched for "Chimezie Metu"
1 result found.
Chimezie Metu
Results for Chimezie Metu:

You searched for "Jabari Parker"
1 result found.
Jabari Parker
Results for Jabari Parker:

You searched for "Norvel Pelle"
1 result found.
Norvel Pelle
Results for Norvel Pelle:

You searched for "Jahmi'us Ramsey"
1 result found.
Jahmi'us Ramsey
Results for Jahmi'us Ramsey:

You searched for "Chris Silva"
15 results found.
0: Chris Silva
1: Chris Mills
2: Chris Childs
3: Chris King
4: Chris Mihm
5: Chris Smith
6: Chris Smith
7: Chris Welp
8: Chris Wilcox
9: Chris Babb
10: Chris Carr
11: Chris Owens
12: Chris Paul
13: Chris Quinn
14: Chris Taft
Pick one: 0
Results for Chris Silva:

You searched for "Hassan Whiteside"
1 result found.
Hassan Whiteside
Results for Hassan Whiteside:

You searched for "Robert Woodard"
2 results found.
0: Robert Woodard
1: Robert Werdann
Pick one: 0
Results for Robert Woodard:

You searched for "Delon Wright"
4 results found.
0: Delon Wright
1: Leroy Wright
2: Dorell Wright
3: Julian Wright
Pick one: 0
Results for Delon Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-01-17,23-028,SAC,HOME,NOP,L (-5),1,39:02,17,27,...,4,13,4,0,2,3,43,41.6,18,De'Aaron Fox
1,2021-03-25,23-095,SAC,HOME,GSW,W (+22),1,35:40,16,22,...,2,7,3,0,2,3,44,39.9,9,De'Aaron Fox
2,2021-02-01,23-043,SAC,AWAY,NOP,W (+9),1,39:41,14,24,...,4,12,1,0,6,3,38,31.0,7,De'Aaron Fox
3,2021-01-25,28-274,DET,HOME,PHI,W (+15),1,36:00,8,12,...,7,9,2,1,3,1,28,30.9,22,Delon Wright
4,2021-04-18,23-119,SAC,AWAY,DAL,W (+14),1,36:47,12,21,...,4,12,2,0,0,2,30,30.5,23,De'Aaron Fox

## combine all seasons

In [48]:
SAC_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2000_games.csv')
SAC_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2001_games.csv')
SAC_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2002_games.csv')
SAC_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2003_games.csv')
SAC_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2004_games.csv')
SAC_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2005_games.csv')
SAC_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2006_games.csv')
SAC_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2007_games.csv')
SAC_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2008_games.csv')
SAC_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2009_games.csv')
SAC_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2010_games.csv')
SAC_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2011_games.csv')
SAC_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2012_games.csv')
SAC_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2013_games.csv')
SAC_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2014_games.csv')
SAC_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2015_games.csv')
SAC_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2016_games.csv')
SAC_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2017_games.csv')
SAC_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2018_games.csv')
SAC_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2019_games.csv')
SAC_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2020_games.csv')
SAC_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/SAC/SAC_2021_games.csv')

In [49]:
SAC_season_dfs = [SAC_2000_games_io, SAC_2001_games_io, SAC_2002_games_io, SAC_2003_games_io, SAC_2004_games_io, SAC_2005_games_io,
                 SAC_2006_games_io, SAC_2007_games_io, SAC_2008_games_io, SAC_2009_games_io, SAC_2010_games_io, SAC_2011_games_io,
                 SAC_2012_games_io, SAC_2013_games_io, SAC_2014_games_io, SAC_2015_games_io, SAC_2016_games_io, SAC_2017_games_io,
                 SAC_2018_games_io, SAC_2019_games_io, SAC_2020_games_io, SAC_2021_games_io]

In [50]:
SAC_all = pd.concat(SAC_season_dfs)
SAC_all_sorted = SAC_all.sort_values(by=['GAME_SCORE'], ascending=False)
SAC_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-12-20,26-129,SAC,HOME,POR,W (+5),1,40:35,17,28,...,14,1,1,3,5,5,55,43.2,3,DeMarcus Cousins
0,2016-01-25,25-165,SAC,HOME,CHO,L (-1),1,45:40,21,30,...,12,4,1,2,7,6,56,42.0,15,DeMarcus Cousins
0,2021-01-17,23-028,SAC,HOME,NOP,L (-5),1,39:02,17,27,...,4,13,4,0,2,3,43,41.6,18,De'Aaron Fox
0,2001-01-05,27-310,SAC,HOME,IND,L (-2),1,49:58,24,47,...,26,5,3,2,4,4,51,40.6,-1,Chris Webber
1,2021-03-25,23-095,SAC,HOME,GSW,W (+22),1,35:40,16,22,...,2,7,3,0,2,3,44,39.9,9,De'Aaron Fox
1,2017-01-30,26-170,SAC,AWAY,PHI,L (-3),1,32:16,11,16,...,15,5,1,1,8,6,46,39.3,-6,DeMarcus Cousins
1,2001-02-02,27-338,SAC,HOME,VAN,W (+10),1,38:42,15,23,...,15,4,1,2,2,2,41,39.0,15,Chris Webber
0,2009-11-02,26-274,SAC,HOME,MEM,W (+11),1,52:28,14,27,...,5,4,4,1,3,2,48,38.3,10,Kevin Martin
0,2002-03-19,29-018,SAC,HOME,HOU,W (+23),1,31:54,15,20,...,12,5,3,1,0,3,35,38.2,21,Chris Webber
0,2011-03-14,23-282,SAC,HOME,GSW,W (+10),1,41:27,13,20,...,3,1,4,0,0,2,42,37.2,17,Marcus Thornton
0,2009-04-01,26-059,SAC,AWAY,GSW,L (-2),1,46:05,11,22,...,3,3,2,0,5,3,50,37.0,-4,Kevin Martin
0,2008-03-07,25-035,SAC,HOME,MIN,L (-8),1,41:34,12,23,...,6,1,0,0,1,3,48,37.0,-2,Kevin Martin
0,2003-01-21,29-326,SAC,HOME,NJN,W (+7),1,43:56,13,21,...,15,8,4,1,1,3,36,36.7,3,Chris Webber
0,2018-11-01,20-316,SAC,AWAY,ATL,W (+31),1,33:55,9,13,...,10,15,1,0,3,3,31,36.6,34,De'Aaron Fox
0,2005-02-02,28-296,SAC,AWAY,GSW,W (+4),1,49:51,14,22,...,17,4,4,2,6,0,38,36.3,11,Brad Miller
0,2015-03-13,24-212,SAC,AWAY,PHI,L (-7),1,40:14,12,24,...,24,1,2,1,3,2,39,35.4,5,DeMarcus Cousins
1,2014-10-31,28-075,SAC,HOME,POR,W (+9),1,36:25,13,19,...,8,1,1,0,0,2,40,35.2,14,Rudy Gay
1,2008-01-02,28-021,SAC,AWAY,NYK,W (+10),1,44:04,13,18,...,11,6,6,1,3,4,32,35.0,12,John Salmons
0,2014-03-26,23-225,SAC,HOME,NYK,L (-8),1,42:57,10,15,...,15,8,2,2,4,4,32,35.0,-4,DeMarcus Cousins
1,1999-11-23,26-267,SAC,HOME,NJN,W (+13),1,41:54,11,18,...,22,10,3,4,2,3,26,34.8,4,Chris Webber
0,2000-01-15,26-320,SAC,AWAY,GSW,W (+15),1,38:37,13,19,...,16,3,2,4,5,3,37,34.8,11,Chris Webber
2,2017-03-21,26-220,NOP,HOME,MEM,W (+13),1,36:48,14,27,...,16,2,2,2,2,5,41,34.5,22,DeMarcus Cousins
3,2017-01-21,26-161,SAC,AWAY,CHI,L (-3),1,35:23,16,28,...,14,3,1,2,2,4,42,34.3,-6,DeMarcus Cousins
1,2005-02-04,26-267,SAC,HOME,NYK,W (+1),1,42:59,16,25,...,3,7,3,0,1,0,40,34.3,11,Mike Bibby
0,2012-04-03,21-234,SAC,HOME,PHO,L (-9),1,37:37,16,25,...,12,2,2,1,2,4,41,34.0,3,DeMarcus Cousins