In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import scipy.stats as stats
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats,get_team_misc

In [2]:
# Constants
SEASON_2000_START = '1999-11-02'
SEASON_2000_END = '2000-04-19'

SEASON_2001_START = '2000-11-01'
SEASON_2001_END = '2001-04-18'

SEASON_2002_START = '2001-10-30'
SEASON_2002_END = '2002-04-17'

SEASON_2003_START = '2002-10-30'
SEASON_2003_END = '2003-04-16'

SEASON_2004_START = '2003-10-29'
SEASON_2004_END = '2004-04-12'

SEASON_2005_START = '2004-11-03'
SEASON_2005_END = '2005-04-20'

SEASON_2006_START = '2005-11-02'
SEASON_2006_END = '2006-04-19'

SEASON_2007_START = '2006-11-01'
SEASON_2007_END = '2007-04-18'

SEASON_2008_START = '2007-11-02'
SEASON_2008_END = '2008-04-16'

SEASON_2009_START = '2008-10-28'
SEASON_2009_END = '2009-04-15'

SEASON_2010_START = '2009-10-27'
SEASON_2010_END = '2010-04-14'

SEASON_2011_START = '2010-10-26'
SEASON_2011_END = '2011-04-13'

SEASON_2012_START = '2011-11-25'
SEASON_2012_END = '2012-04-26'

SEASON_2013_START = '2012-10-30'
SEASON_2013_END = '2013-04-17'

SEASON_2014_START = '2013-10-30'
SEASON_2014_END = '2014-04-16'

SEASON_2015_START = '2014-10-29'
SEASON_2015_END = '2015-04-15'

SEASON_2016_START = '2015-10-28' 
SEASON_2016_END = '2016-04-13'

SEASON_2017_START = '2016-10-25'
SEASON_2017_END = '2017-04-14'

SEASON_2018_START = '2017-10-17'
SEASON_2018_END = '2018-04-14'

SEASON_2019_START = '2018-10-18'
SEASON_2019_END = '2019-04-12'

SEASON_2020_START = '2019-10-22'
SEASON_2020_END = '2020-08-15'

SEASON_2021_START = '2020-12-22'
SEASON_2021_END = '2021-05-16'

In [3]:
season = 2000
appended_data_TOR = []

# TOR
while season <= 2021:
    df_TOR = get_roster('TOR', season)
    df_TOR['Season'] = season
    df_TOR['Team'] = 'TOR'
    appended_data_TOR.append(df_TOR)
    season = season + 1
appended_data_TOR = pd.concat(appended_data_TOR)

In [4]:
TOR_df_all = appended_data_TOR.copy()
TOR_df_all_csv = TOR_df_all.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_players_all.csv', index=False)
TOR_df_all_csv_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_players_all.csv')
TOR_df_all_csv_io.head()

,NUMBER,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE,Season,Team
0,14,Muggsy Bogues,PG,5-3,136,1965-01-09,US,12,Wake Forest,2000,TOR
1,7,Dee Brown,PG,6-1,160,1968-11-29,US,9,Jacksonville University,2000,TOR
2,15,Vince Carter,SF,6-6,220,1977-01-26,US,1,UNC,2000,TOR
3,13,Doug Christie,SG,6-6,200,1970-05-09,US,7,Pepperdine,2000,TOR
4,30,Dell Curry,SG,6-4,190,1964-06-25,US,13,Virginia Tech,2000,TOR

In [5]:
TOR_df_2000 = TOR_df_all[TOR_df_all['Season'] == 2000]
TOR_df_2001 = TOR_df_all[TOR_df_all['Season'] == 2001]
TOR_df_2002 = TOR_df_all[TOR_df_all['Season'] == 2002]
TOR_df_2003 = TOR_df_all[TOR_df_all['Season'] == 2003]
TOR_df_2004 = TOR_df_all[TOR_df_all['Season'] == 2004]
TOR_df_2005 = TOR_df_all[TOR_df_all['Season'] == 2005]
TOR_df_2006 = TOR_df_all[TOR_df_all['Season'] == 2006]
TOR_df_2007 = TOR_df_all[TOR_df_all['Season'] == 2007]
TOR_df_2008 = TOR_df_all[TOR_df_all['Season'] == 2008]
TOR_df_2009 = TOR_df_all[TOR_df_all['Season'] == 2009]
TOR_df_2010 = TOR_df_all[TOR_df_all['Season'] == 2010]
TOR_df_2011 = TOR_df_all[TOR_df_all['Season'] == 2011]
TOR_df_2012 = TOR_df_all[TOR_df_all['Season'] == 2012]
TOR_df_2013 = TOR_df_all[TOR_df_all['Season'] == 2013]
TOR_df_2014 = TOR_df_all[TOR_df_all['Season'] == 2014]
TOR_df_2015 = TOR_df_all[TOR_df_all['Season'] == 2015]
TOR_df_2016 = TOR_df_all[TOR_df_all['Season'] == 2016]
TOR_df_2017 = TOR_df_all[TOR_df_all['Season'] == 2017]
TOR_df_2018 = TOR_df_all[TOR_df_all['Season'] == 2018]
TOR_df_2019 = TOR_df_all[TOR_df_all['Season'] == 2019]
TOR_df_2020 = TOR_df_all[TOR_df_all['Season'] == 2020]
TOR_df_2021 = TOR_df_all[TOR_df_all['Season'] == 2021]

In [6]:
# changing names
#TOR_df_2002.loc[TOR_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'
#TOR_df_2004.loc[TOR_df_2003.PLAYER == 'Nenê Hilário', 'PLAYER'] = 'Nene Hilario'

In [6]:
TOR_df_2000_players = TOR_df_2000['PLAYER'].to_list()
TOR_df_2001_players = TOR_df_2001['PLAYER'].to_list()
TOR_df_2002_players = TOR_df_2002['PLAYER'].to_list()
TOR_df_2003_players = TOR_df_2003['PLAYER'].to_list()
TOR_df_2004_players = TOR_df_2004['PLAYER'].to_list()
TOR_df_2005_players = TOR_df_2005['PLAYER'].to_list()

TOR_df_2006_players = TOR_df_2006['PLAYER'].to_list()
TOR_df_2007_players = TOR_df_2007['PLAYER'].to_list()
TOR_df_2008_players = TOR_df_2008['PLAYER'].to_list()
TOR_df_2009_players = TOR_df_2009['PLAYER'].to_list()
TOR_df_2010_players = TOR_df_2010['PLAYER'].to_list()
TOR_df_2011_players = TOR_df_2011['PLAYER'].to_list()

TOR_df_2012_players = TOR_df_2012['PLAYER'].to_list()
TOR_df_2013_players = TOR_df_2013['PLAYER'].to_list()
TOR_df_2014_players = TOR_df_2014['PLAYER'].to_list()
TOR_df_2015_players = TOR_df_2015['PLAYER'].to_list()
TOR_df_2016_players = TOR_df_2016['PLAYER'].to_list()
TOR_df_2017_players = TOR_df_2017['PLAYER'].to_list()

TOR_df_2018_players = TOR_df_2018['PLAYER'].to_list()
TOR_df_2019_players = TOR_df_2019['PLAYER'].to_list()
TOR_df_2020_players = TOR_df_2020['PLAYER'].to_list()
TOR_df_2021_players = TOR_df_2021['PLAYER'].to_list()

## players to drop

In [46]:
#TOR_df_2001_players.remove("Mamadou N'Diaye")
#TOR_df_2002_players.remove("Mamadou N'Diaye")
#TOR_df_2003_players.remove("Mamadou N'Diaye")
#TOR_df_2007_players.remove("Luke Jackson")
#TOR_df_2009_players.remove("Patrick O'Bryant")
#TOR_df_2009_players.remove("Jermaine O'Neal")
#TOR_df_2010_players.remove("Patrick O'Bryant")
TOR_df_2021_players.remove("Gary Trent")

In [8]:

TOR_2000_gamelog = []


for p in TOR_df_2000_players:
    player_log = get_game_logs(str(p), SEASON_2000_START, SEASON_2000_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2000_gamelog.append(player_log)
TOR_2000_gamelog = pd.concat(TOR_2000_gamelog)    
TOR_2000_gamelogs = TOR_2000_gamelog.copy()
TOR_2000_gamelogs['GAME_SCORE'] = TOR_2000_gamelogs['GAME_SCORE'].astype(float)
TOR_2000_games = TOR_2000_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2000_games_csv = TOR_2000_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2000_games.csv', index=False)
TOR_2000_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2000_games.csv')
TOR_2000_games_proc.head()

You searched for "Muggsy Bogues"
1 result found.
Muggsy Bogues
Results for Muggsy Bogues:

You searched for "Dee Brown"
24 results found.
0: Dee Brown
1: Dee Brown
2: Andre Brown
3: Bob Brown
4: Devin Brown
5: Fred Brown
6: Leon Brown
7: Mike Brown
8: Bruce Brown
9: Damone Brown
10: George Brown
11: John Brown
12: Kwame Brown
13: Lewis Brown
14: Moses Brown
15: P.J. Brown
16: Roger Brown
17: Roger Brown
18: Stan Brown
19: Tierre Brown
20: Tony Brown
21: Troy Brown
22: Jim Browne
23: Dee Gibson
Pick one: 0
Results for Dee Brown:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Doug Christie"
2 results found.
0: Doug Christie
1: Doug Kistler
Pick one: 0
Results for Doug Christie:

You searched for "Dell Curry"
5 results found.
0: Dell Curry
1: Seth Curry
2: Will Cherry
3: Bill Curley
4: Eddy Curry
Pick one: 0
Results for Dell Curry:

You searched for "Antonio Davis"
6 results found.
0: Antonio Davis
1: Antonio Daniels
2: Anthony Davis
3: Antonio Burks
4: Antonio Harvey
5: Antonio Lang
Pick one: 0
Results for Antonio Davis:

You searched for "Antonio Lang"
2 results found.
0: Antonio Lang
1: Antonio Davis
Pick one: 0
Results for Antonio Lang:

You searched for "Sean Marks"
6 results found.
0: Sean Marks
1: Sean May
2: Sean Rooks
3: Sam Mack
4: Keon Clark
5: Stan Miasek
Pick one: 0
Results for Sean Marks:

You searched for "Tracy McGrady"
2 results found.
0: Tracy McGrady
1: Tracy Murray
Pick one: 0
Results for Tracy McGrady:

You searched for "Charles Oakley"
8 results found.
0: Charles Oakley
1: Charles Barkley
2: Charles Beasley
3: Charles Bradley
4: Charles Dudley
5: Charles Cooke
6: Charles Jordan
7: Charles Thomas
Pick one: 0
Results for Charles Oakley:

You searched for "Aleksandar Radojević"
2 results found.
0: Aleksandar Radojevic
1: Aleksandar Dordevic
Pick one: 0
Results for Aleksandar Radojevic:

You searched for "Michael Stewart"
1 result found.
Michael Stewart
Results for Michael Stewart:

You searched for "John Thomas"
21 results found.
0: John Thomas
1: Joe Thomas
2: Etan Thomas
3: Jim Thomas
4: John Thompson
5: John Logan
6: John Lucas
7: John Shumate
8: Carl Thomas
9: Jamel Thomas
10: James Thomas
11: Kenny Thomas
12: Kurt Thomas
13: Matt Thomas
14: Tim Thomas
15: John Hazen
16: John Oldham
17: John Stroud
18: John Trapp
19: John Tschogl
20: Johan Petro
Pick one: 0
Results for John Thomas:

You searched for "Alvin Williams"
24 results found.
0: Alvin Williams
1: Alan Williams
2: Kevin Williams
3: Marvin Williams
4: Aaron Williams
5: Al Williams
6: Art Williams
7: Cliff Williams
8: Deron Williams
9: Elliot Williams
10: Eric Williams
11: Fly Williams
12: Jason Williams
13: Jayson Williams
14: John Williams
15: Justin Williams
16: Lou Williams
17: Ron Williams
18: Sean Williams
19: Sly Williams
20: Travis Williams
21: Walt Williams
22: Willie Williams
23: Kevin Willis
Pick one: 0
Results for Alvin Williams:

You searched for "Kevin Willis"
4 results found.
0: Kevin Willis
1: Kevin Williams
2: Kevin Ollie
3: Alvin Williams
Pick one: 0
Results for Kevin Willis:

You searched for "Haywoode Workman"
1 result found.
Haywoode Workman
Results for Haywoode Workman:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-02-27,23-032,TOR,HOME,PHO,W (+1),1,43:13,17,32,...,9,1,3,0,5,5,51,36.8,5,Vince Carter
1,2000-01-14,22-353,TOR,HOME,MIL,W (+5),1,42:58,20,32,...,5,4,2,2,3,5,47,36.5,3,Vince Carter
2,2000-04-14,23-079,TOR,HOME,NYK,W (+15),1,33:50,14,19,...,5,6,2,3,2,3,34,32.5,15,Vince Carter
3,2000-04-10,23-075,TOR,HOME,CLE,W (+9),1,43:46,13,19,...,11,10,1,1,2,3,31,32.1,10,Vince Carter
4,2000-02-08,23-013,TOR,HOME,ATL,W (+21),1,39:39,14,27,...,4,5,4,0,0,2,36,31.0,31,Vince Carter

In [11]:
# removed Mamadou N'Diaye
TOR_2001_gamelog = []


for p in TOR_df_2001_players:
    player_log = get_game_logs(str(p), SEASON_2001_START, SEASON_2001_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2001_gamelog.append(player_log)
TOR_2001_gamelog = pd.concat(TOR_2001_gamelog)    
TOR_2001_gamelogs = TOR_2001_gamelog.copy()
TOR_2001_gamelogs['GAME_SCORE'] = TOR_2001_gamelogs['GAME_SCORE'].astype(float)
TOR_2001_games = TOR_2001_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2001_games_csv = TOR_2001_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2001_games.csv', index=False)
TOR_2001_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2001_games.csv')
TOR_2001_games_proc.head()

You searched for "Muggsy Bogues"
1 result found.
Muggsy Bogues
Results for Muggsy Bogues:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Chris Childs"
5 results found.
0: Chris Childs
1: Chris Mills
2: Chris Chiozza
3: Chris Silva
4: Chris Richard
Pick one: 0
Results for Chris Childs:

You searched for "Keon Clark"
5 results found.
0: Keon Clark
1: Ian Clark
2: Kenny Carr
3: Earl Clark
4: Gary Clark
Pick one: 0
Results for Keon Clark:

You searched for "Tyrone Corbin"
2 results found.
0: Tyrone Corbin
1: Tyrone Britt
Pick one: 0
Results for Tyrone Corbin:

You searched for "Dell Curry"
5 results found.
0: Dell Curry
1: Seth Curry
2: Will Cherry
3: Bill Curley
4: Eddy Curry
Pick one: 0
Results for Dell Curry:

You searched for "Kornél Dávid"
1 result found.
Kornel David
Results for Kornel David:

You searched for "Antonio Davis"
6 results found.
0: Antonio Davis
1: Antonio Daniels
2: Anthony Davis
3: Antonio Burks
4: Antonio Harvey
5: Antonio Lang
Pick one: 0
Results for Antonio Davis:

You searched for "Mark Jackson"
25 results found.
0: Mark Jackson
1: Marc Jackson
2: Aaron Jackson
3: Al Jackson
4: Frank Jackson
5: Jaren Jackson
6: Jaren Jackson
7: Mike Jackson
8: Myron Jackson
9: Mark Macon
10: Mark Eaton
11: Greg Jackson
12: Jim Jackson
13: Josh Jackson
14: Luke Jackson
15: Luke Jackson
16: Mervin Jackson
17: Phil Jackson
18: Ralph Jackson
19: Tony Jackson
20: Tony Jackson
21: Tracy Jackson
22: Mark Madsen
23: Mark Jones
24: Mark Jones
Pick one: 0
Results for Mark Jackson:

You searched for "Garth Joseph"
3 results found.
0: Garth Joseph
1: Cory Joseph
2: Kris Joseph
Pick one: 0
Results for Garth Joseph:

You searched for "Eric Montross"
1 result found.
Eric Montross
Results for Eric Montross:

You searched for "Tracy Murray"
4 results found.
0: Tracy Murray
1: Tracy McGrady
2: Tracy Moore
3: Troy Murphy
Pick one: 0
Results for Tracy Murray:

You searched for "Charles Oakley"
8 results found.
0: Charles Oakley
1: Charles Barkley
2: Charles Beasley
3: Charles Bradley
4: Charles Dudley
5: Charles Cooke
6: Charles Jordan
7: Charles Thomas
Pick one: 0
Results for Charles Oakley:

You searched for "Morris Peterson"
1 result found.
Morris Peterson
Results for Morris Peterson:

You searched for "Michael Stewart"
1 result found.
Michael Stewart
Results for Michael Stewart:

You searched for "Alvin Williams"
24 results found.
0: Alvin Williams
1: Alan Williams
2: Kevin Williams
3: Marvin Williams
4: Aaron Williams
5: Al Williams
6: Art Williams
7: Cliff Williams
8: Deron Williams
9: Elliot Williams
10: Eric Williams
11: Fly Williams
12: Jason Williams
13: Jayson Williams
14: John Williams
15: Justin Williams
16: Lou Williams
17: Ron Williams
18: Sean Williams
19: Sly Williams
20: Travis Williams
21: Walt Williams
22: Willie Williams
23: Kevin Willis
Pick one: 0
Results for Alvin Williams:

You searched for "Jerome Williams"
16 results found.
0: Jerome Williams
1: Bernie Williams
2: Deron Williams
3: Aaron Williams
4: Eric Williams
5: Gene Williams
6: Herb Williams
7: Jason Williams
8: John Williams
9: Jordan Williams
10: Pete Williams
11: Reggie Williams
12: Reggie Williams
13: Rob Williams
14: Ron Williams
15: Troy Williams
Pick one: 0
Results for Jerome Williams:

You searched for "Corliss Williamson"
1 result found.
Corliss Williamson
Results for Corliss Williamson:

You searched for "Kevin Willis"
4 results found.
0: Kevin Willis
1: Kevin Williams
2: Kevin Ollie
3: Alvin Williams
Pick one: 0
Results for Kevin Willis:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2000-11-18,23-297,TOR,HOME,MIL,W (+9),1,44:43,14,31,...,10,4,3,2,2,3,48,40.5,8,Vince Carter
1,2001-01-14,23-354,TOR,HOME,CHH,W (+8),1,42:17,16,23,...,8,3,1,1,1,4,40,35.5,8,Vince Carter
2,2000-12-30,23-339,TOR,AWAY,PHO,L (-6),1,43:56,11,26,...,6,6,1,1,3,5,46,34.5,3,Vince Carter
3,2001-04-08,24-072,TOR,HOME,CHI,W (+12),1,43:49,12,19,...,3,6,4,3,2,1,33,32.5,21,Vince Carter
4,2001-03-27,24-060,TOR,AWAY,MIA,W (+9),1,44:45,14,27,...,6,2,1,4,0,0,38,32.1,6,Vince Carter

In [14]:
# removed Mamadou N'Diaye
TOR_2002_gamelog = []


for p in TOR_df_2002_players:
    player_log = get_game_logs(str(p), SEASON_2002_START, SEASON_2002_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2002_gamelog.append(player_log)
TOR_2002_gamelog = pd.concat(TOR_2002_gamelog)    
TOR_2002_gamelogs = TOR_2002_gamelog.copy()
TOR_2002_gamelogs['GAME_SCORE'] = TOR_2002_gamelogs['GAME_SCORE'].astype(float)
TOR_2002_games = TOR_2002_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2002_games_csv = TOR_2002_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2002_games.csv', index=False)
TOR_2002_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2002_games.csv')
TOR_2002_games_proc.head()

You searched for "Carlos Arroyo"
2 results found.
0: Carlos Arroyo
1: Carlos Terry
Pick one: 0
Results for Carlos Arroyo:

You searched for "Michael Bradley"
7 results found.
0: Michael Bradley
1: Michael Beasley
2: Michael Ansley
3: Michael Finley
4: Michael Frazier
5: Michael Wiley
6: Michael Bytzura
Pick one: 0
Results for Michael Bradley:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Chris Childs"
5 results found.
0: Chris Childs
1: Chris Mills
2: Chris Chiozza
3: Chris Silva
4: Chris Richard
Pick one: 0
Results for Chris Childs:

You searched for "Keon Clark"
5 results found.
0: Keon Clark
1: Ian Clark
2: Kenny Carr
3: Earl Clark
4: Gary Clark
Pick one: 0
Results for Keon Clark:

You searched for "Dell Curry"
5 results found.
0: Dell Curry
1: Seth Curry
2: Will Cherry
3: Bill Curley
4: Eddy Curry
Pick one: 0
Results for Dell Curry:

You searched for "Antonio Davis"
6 results found.
0: Antonio Davis
1: Antonio Daniels
2: Anthony Davis
3: Antonio Burks
4: Antonio Harvey
5: Antonio Lang
Pick one: 0
Results for Antonio Davis:

You searched for "Derrick Dial"
4 results found.
0: Derrick Dial
1: Derrick Byars
2: Derrick Rose
3: Derrick White
Pick one: 0
Results for Derrick Dial:

You searched for "Jermaine Jackson"
2 results found.
0: Jermaine Jackson
1: Mervin Jackson
Pick one: 0
Results for Jermaine Jackson:

You searched for "Eric Montross"
1 result found.
Eric Montross
Results for Eric Montross:

You searched for "Tracy Murray"
4 results found.
0: Tracy Murray
1: Tracy McGrady
2: Tracy Moore
3: Troy Murphy
Pick one: 0
Results for Tracy Murray:

You searched for "Hakeem Olajuwon"
1 result found.
Hakeem Olajuwon
Results for Hakeem Olajuwon:

You searched for "Morris Peterson"
1 result found.
Morris Peterson
Results for Morris Peterson:

You searched for "Michael Stewart"
1 result found.
Michael Stewart
Results for Michael Stewart:

You searched for "Alvin Williams"
24 results found.
0: Alvin Williams
1: Alan Williams
2: Kevin Williams
3: Marvin Williams
4: Aaron Williams
5: Al Williams
6: Art Williams
7: Cliff Williams
8: Deron Williams
9: Elliot Williams
10: Eric Williams
11: Fly Williams
12: Jason Williams
13: Jayson Williams
14: John Williams
15: Justin Williams
16: Lou Williams
17: Ron Williams
18: Sean Williams
19: Sly Williams
20: Travis Williams
21: Walt Williams
22: Willie Williams
23: Kevin Willis
Pick one: 0
Results for Alvin Williams:

You searched for "Jerome Williams"
16 results found.
0: Jerome Williams
1: Bernie Williams
2: Deron Williams
3: Aaron Williams
4: Eric Williams
5: Gene Williams
6: Herb Williams
7: Jason Williams
8: John Williams
9: Jordan Williams
10: Pete Williams
11: Reggie Williams
12: Reggie Williams
13: Rob Williams
14: Ron Williams
15: Troy Williams
Pick one: 0
Results for Jerome Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2001-12-07,24-315,TOR,HOME,DEN,W (+2),1,50:45,13,30,...,15,6,5,2,4,4,42,37.3,3,Vince Carter
1,2001-11-07,24-285,TOR,HOME,GSW,W (+17),1,41:57,12,24,...,10,6,1,1,3,2,39,32.9,19,Vince Carter
2,2001-11-10,24-288,TOR,AWAY,UTA,W (+21),1,40:36,14,32,...,5,4,3,1,1,2,43,32.8,29,Vince Carter
3,2002-01-04,24-343,TOR,HOME,CLE,W (+10),1,42:02,15,24,...,4,8,2,1,1,2,34,31.7,17,Vince Carter
4,2002-03-05,25-038,TOR,AWAY,HOU,L (-3),1,44:18,18,31,...,7,1,1,0,1,3,43,30.9,-10,Vince Carter

In [18]:
# removed Mamadou N'Diaye
    
TOR_2003_gamelog = []



for p in TOR_df_2003_players:
    player_log = get_game_logs(str(p), SEASON_2003_START, SEASON_2003_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2003_gamelog.append(player_log)
TOR_2003_gamelog = pd.concat(TOR_2003_gamelog)    
TOR_2003_gamelogs = TOR_2003_gamelog.copy()
TOR_2003_gamelogs['GAME_SCORE'] = TOR_2003_gamelogs['GAME_SCORE'].astype(float)
TOR_2003_games = TOR_2003_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2003_games_csv = TOR_2003_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2003_games.csv', index=False)
TOR_2003_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2003_games.csv')
TOR_2003_games_proc.head()

You searched for "Rafer Alston"
1 result found.
Rafer Alston
Results for Rafer Alston:

You searched for "Maceo Baston"
2 results found.
0: Maceo Baston
1: Dave Batton
Pick one: 0
Results for Maceo Baston:

You searched for "Michael Bradley"
7 results found.
0: Michael Bradley
1: Michael Beasley
2: Michael Ansley
3: Michael Finley
4: Michael Frazier
5: Michael Wiley
6: Michael Bytzura
Pick one: 0
Results for Michael Bradley:

You searched for "Damone Brown"
14 results found.
0: Damone Brown
1: Raymond Brown
2: Andre Brown
3: Dee Brown
4: Dee Brown
5: Devin Brown
6: Harold Brown
7: Kwame Brown
8: Leon Brown
9: Mike Brown
10: Moses Brown
11: Myron Brown
12: Tony Brown
13: Damon Jones
Pick one: 0
Results for Damone Brown:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Antonio Davis"
6 results found.
0: Antonio Davis
1: Antonio Daniels
2: Anthony Davis
3: Antonio Burks
4: Antonio Harvey
5: Antonio Lang
Pick one: 0
Results for Antonio Davis:

You searched for "Greg Foster"
12 results found.
0: Greg Foster
1: Fred Foster
2: Rod Foster
3: Greg Butler
4: Jeff Foster
5: Greg Hyder
6: Greg Kelser
7: Greg Kite
8: Greg Oden
9: Greg Ostertag
10: Greg Monroe
11: Greg Stokes
Pick one: 0
Results for Greg Foster:

You searched for "Zendon Hamilton"
3 results found.
0: Zendon Hamilton
1: Dennis Hamilton
2: Jordan Hamilton
Pick one: 0
Results for Zendon Hamilton:

You searched for "Nate Huffman"
3 results found.
0: Nate Huffman
1: Nate Bowman
2: Paul Hoffman
Pick one: 0
Results for Nate Huffman:

You searched for "Lindsey Hunter"
2 results found.
0: Lindsey Hunter
1: Vince Hunter
Pick one: 0
Results for Lindsey Hunter:

You searched for "Jermaine Jackson"
2 results found.
0: Jermaine Jackson
1: Mervin Jackson
Pick one: 0
Results for Jermaine Jackson:

You searched for "Chris Jefferies"
1 result found.
Chris Jefferies
Results for Chris Jefferies:

You searched for "Voshon Lenard"
1 result found.
Voshon Lenard
Results for Voshon Lenard:

You searched for "Art Long"
7 results found.
0: Art Long
1: Grant Long
2: Paul Long
3: John Long
4: Shawn Long
5: Walt Lemon
6: Alex Len
Pick one: 0
Results for Art Long:

You searched for "Jelani McCoy"
1 result found.
Jelani McCoy
Results for Jelani McCoy:

You searched for "Morris Peterson"
1 result found.
Morris Peterson
Results for Morris Peterson:

You searched for "Alvin Williams"
24 results found.
0: Alvin Williams
1: Alan Williams
2: Kevin Williams
3: Marvin Williams
4: Aaron Williams
5: Al Williams
6: Art Williams
7: Cliff Williams
8: Deron Williams
9: Elliot Williams
10: Eric Williams
11: Fly Williams
12: Jason Williams
13: Jayson Williams
14: John Williams
15: Justin Williams
16: Lou Williams
17: Ron Williams
18: Sean Williams
19: Sly Williams
20: Travis Williams
21: Walt Williams
22: Willie Williams
23: Kevin Willis
Pick one: 0
Results for Alvin Williams:

You searched for "Jerome Williams"
16 results found.
0: Jerome Williams
1: Bernie Williams
2: Deron Williams
3: Aaron Williams
4: Eric Williams
5: Gene Williams
6: Herb Williams
7: Jason Williams
8: John Williams
9: Jordan Williams
10: Pete Williams
11: Reggie Williams
12: Reggie Williams
13: Rob Williams
14: Ron Williams
15: Troy Williams
Pick one: 0
Results for Jerome Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2003-03-08,26-041,TOR,AWAY,ATL,W (+9),1,35:38,16,24,...,4,4,1,0,1,3,43,35.0,14,Vince Carter
1,2002-11-29,25-095,TOR,AWAY,BOS,W (+3),1,41:42,12,18,...,6,4,1,1,0,3,31,28.3,11,Morris Peterson
2,2002-11-12,28-098,TOR,AWAY,ORL,W (+6),1,37:48,9,18,...,4,3,3,2,1,5,32,28.1,20,Alvin Williams
3,2002-11-12,29-186,TOR,AWAY,ORL,W (+6),1,38:21,13,18,...,8,4,0,0,1,1,30,28.0,7,Jerome Williams
4,2003-03-30,26-063,TOR,HOME,NYK,W (+9),1,40:09,12,20,...,9,6,2,3,3,2,28,27.6,15,Vince Carter

In [19]:


TOR_2004_gamelog = []



for p in TOR_df_2004_players:
    player_log = get_game_logs(str(p), SEASON_2004_START, SEASON_2004_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2004_gamelog.append(player_log)
TOR_2004_gamelog = pd.concat(TOR_2004_gamelog)    
TOR_2004_gamelogs = TOR_2004_gamelog.copy()
TOR_2004_gamelogs['GAME_SCORE'] = TOR_2004_gamelogs['GAME_SCORE'].astype(float)
TOR_2004_games = TOR_2004_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2004_games_csv = TOR_2004_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2004_games.csv', index=False)
TOR_2004_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2004_games.csv')
TOR_2004_games_proc.head()

You searched for "Robert Archibald"
1 result found.
Robert Archibald
Results for Robert Archibald:

You searched for "Mengke Bateer"
1 result found.
Mengke Bateer
Results for Mengke Bateer:

You searched for "Lonny Baxter"
3 results found.
0: Lonny Baxter
1: Sonny Parker
2: Kenny Battle
Pick one: 0
Results for Lonny Baxter:

You searched for "Corie Blount"
2 results found.
0: Corie Blount
1: Mark Blount
Pick one: 0
Results for Corie Blount:

You searched for "Chris Bosh"
18 results found.
0: Chris Bosh
1: Chris Babb
2: Chris Ford
3: Chris Boucher
4: Chris Carr
5: Chris Jent
6: Chris King
7: Chris Mihm
8: Chris Munk
9: Chris Paul
10: Chris Smith
11: Chris Smith
12: Chris Taft
13: Chris Welp
14: Chris Duhon
15: Chris Mills
16: Chris Morris
17: Chris Owens
Pick one: 0
Results for Chris Bosh:

You searched for "Michael Bradley"
7 results found.
0: Michael Bradley
1: Michael Beasley
2: Michael Ansley
3: Michael Finley
4: Michael Frazier
5: Michael Wiley
6: Michael Bytzura
Pick one: 0
Results for Michael Bradley:

You searched for "Rick Brunson"
6 results found.
0: Rick Brunson
1: Ricky Blanton
2: Nick Johnson
3: Rich Johnson
4: Rick Wilson
5: Rickey Brown
Pick one: 0
Results for Rick Brunson:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Michael Curry"
7 results found.
0: Michael Curry
1: Michael Cage
2: Michael Wiley
3: Michael Cooper
4: Michael Porter
5: Michael Redd
6: Michael Young
Pick one: 0
Results for Michael Curry:

You searched for "Antonio Davis"
6 results found.
0: Antonio Davis
1: Antonio Daniels
2: Anthony Davis
3: Antonio Burks
4: Antonio Harvey
5: Antonio Lang
Pick one: 0
Results for Antonio Davis:

You searched for "Dion Glover"
3 results found.
0: Dion Glover
1: Don Boven
2: Dean Oliver
Pick one: 0
Results for Dion Glover:

You searched for "Chris Jefferies"
1 result found.
Chris Jefferies
Results for Chris Jefferies:

You searched for "Donyell Marshall"
3 results found.
0: Donyell Marshall
1: Donny Marshall
2: Kendall Marshall
Pick one: 0
Results for Donyell Marshall:

You searched for "Roger Mason"
3 results found.
0: Roger Mason
1: Roger Brown
2: Roger Brown
Pick one: 0
Results for Roger Mason:

You searched for "Jérôme Moïso"
5 results found.
0: Jerome Moiso
1: Jerome Dyson
2: Jerome Robinson
3: Jerome Harmon
4: Jerome James
Pick one: 0
Results for Jerome Moiso:

You searched for "Lamond Murray"
2 results found.
0: Lamond Murray
1: Jamal Murray
Pick one: 0
Results for Lamond Murray:

You searched for "Milt Palacio"
1 result found.
Milt Palacio
Results for Milt Palacio:

You searched for "Jannero Pargo"
1 result found.
Jannero Pargo
Results for Jannero Pargo:

You searched for "Morris Peterson"
1 result found.
Morris Peterson
Results for Morris Peterson:

You searched for "Jalen Rose"
9 results found.
0: Jalen Rose
1: Jalen Jones
2: Malik Rose
3: Jaylen Brown
4: James Posey
5: Glen Rice
6: Glen Rice
7: Jalen Harris
8: Al Roges
Pick one: 0
Results for Jalen Rose:

You searched for "Rod Strickland"
4 results found.
0: Rod Strickland
1: Roger Strickland
2: Erick Strickland
3: Mark Strickland
Pick one: 0
Results for Rod Strickland:

You searched for "Alvin Williams"
24 results found.
0: Alvin Williams
1: Alan Williams
2: Kevin Williams
3: Marvin Williams
4: Aaron Williams
5: Al Williams
6: Art Williams
7: Cliff Williams
8: Deron Williams
9: Elliot Williams
10: Eric Williams
11: Fly Williams
12: Jason Williams
13: Jayson Williams
14: John Williams
15: Justin Williams
16: Lou Williams
17: Ron Williams
18: Sean Williams
19: Sly Williams
20: Travis Williams
21: Walt Williams
22: Willie Williams
23: Kevin Willis
Pick one: 0
Results for Alvin Williams:

You searched for "Jerome Williams"
16 results found.
0: Jerome Williams
1: Bernie Williams
2: Deron Williams
3: Aaron Williams
4: Eric Williams
5: Gene Williams
6: Herb Williams
7: Jason Williams
8: John Williams
9: Jordan Williams
10: Pete Williams
11: Reggie Williams
12: Reggie Williams
13: Rob Williams
14: Ron Williams
15: Troy Williams
Pick one: 0
Results for Jerome Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2004-03-21,27-055,TOR,AWAY,NOH,W (+1),1,46:36,13,20,...,6,12,2,1,4,4,42,40.1,4,Vince Carter
1,2004-02-04,30-262,TOR,HOME,ORL,W (+20),1,30:15,12,18,...,9,3,1,4,1,3,32,31.8,21,Donyell Marshall
2,2003-11-26,26-304,TOR,AWAY,ATL,W (+2),1,45:56,18,28,...,7,3,2,2,6,2,43,31.0,4,Vince Carter
3,2004-03-14,27-048,TOR,HOME,ATL,W (+17),1,41:23,13,19,...,5,7,2,1,2,2,32,30.2,24,Vince Carter
4,2003-11-09,26-287,TOR,HOME,DEN,W (+13),1,38:43,14,22,...,10,6,0,1,2,3,34,30.1,22,Vince Carter

In [20]:

TOR_2005_gamelog = []



for p in TOR_df_2005_players:
    player_log = get_game_logs(str(p), SEASON_2005_START, SEASON_2005_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2005_gamelog.append(player_log)
TOR_2005_gamelog = pd.concat(TOR_2005_gamelog)    
TOR_2005_gamelogs = TOR_2005_gamelog.copy()
TOR_2005_gamelogs['GAME_SCORE'] = TOR_2005_gamelogs['GAME_SCORE'].astype(float)
TOR_2005_games = TOR_2005_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2005_games_csv = TOR_2005_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2005_games.csv', index=False)
TOR_2005_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2005_games.csv')
TOR_2005_games_proc.head()

You searched for "Rafer Alston"
1 result found.
Rafer Alston
Results for Rafer Alston:

You searched for "Rafael Araújo"
1 result found.
Rafael Araujo
Results for Rafael Araujo:

You searched for "Matt Bonner"
4 results found.
0: Matt Bonner
1: Matt Barnes
2: Matt Mooney
3: Matt Geiger
Pick one: 0
Results for Matt Bonner:

You searched for "Chris Bosh"
18 results found.
0: Chris Bosh
1: Chris Babb
2: Chris Ford
3: Chris Boucher
4: Chris Carr
5: Chris Jent
6: Chris King
7: Chris Mihm
8: Chris Munk
9: Chris Paul
10: Chris Smith
11: Chris Smith
12: Chris Taft
13: Chris Welp
14: Chris Duhon
15: Chris Mills
16: Chris Morris
17: Chris Owens
Pick one: 0
Results for Chris Bosh:

You searched for "Vince Carter"
6 results found.
0: Vince Carter
1: Vince Hunter
2: Butch Carter
3: Jake Carter
4: Ron Carter
5: Vince Taylor
Pick one: 0
Results for Vince Carter:

You searched for "Omar Cook"
9 results found.
0: Omar Cook
1: Omer Asik
2: Bert Cook
3: Bobby Cook
4: Brian Cook
5: Jeff Cook
6: Norm Cook
7: Tyler Cook
8: Mark Crow
Pick one: 0
Results for Omar Cook:

You searched for "Donyell Marshall"
3 results found.
0: Donyell Marshall
1: Donny Marshall
2: Kendall Marshall
Pick one: 0
Results for Donyell Marshall:

You searched for "Jérôme Moïso"
5 results found.
0: Jerome Moiso
1: Jerome Dyson
2: Jerome Robinson
3: Jerome Harmon
4: Jerome James
Pick one: 0
Results for Jerome Moiso:

You searched for "Lamond Murray"
2 results found.
0: Lamond Murray
1: Jamal Murray
Pick one: 0
Results for Lamond Murray:

You searched for "Milt Palacio"
1 result found.
Milt Palacio
Results for Milt Palacio:

You searched for "Morris Peterson"
1 result found.
Morris Peterson
Results for Morris Peterson:

You searched for "Jalen Rose"
9 results found.
0: Jalen Rose
1: Jalen Jones
2: Malik Rose
3: Jaylen Brown
4: James Posey
5: Glen Rice
6: Glen Rice
7: Jalen Harris
8: Al Roges
Pick one: 0
Results for Jalen Rose:

You searched for "Pape Sow"
2 results found.
0: Pape Sow
1: Pape Sy
Pick one: 0
Results for Pape Sow:

You searched for "Aaron Williams"
39 results found.
0: Aaron Williams
1: Deron Williams
2: Jason Williams
3: Ron Williams
4: Alan Williams
5: Alvin Williams
6: Art Williams
7: Earl Williams
8: Jayson Williams
9: Marvin Williams
10: Rob Williams
11: Troy Williams
12: Ward Williams
13: Al Williams
14: Bob Williams
15: Brandon Williams
16: Corey Williams
17: Eric Williams
18: Frank Williams
19: Grant Williams
20: Hank Williams
21: Herb Williams
22: Jawad Williams
23: Jay Williams
24: Jerome Williams
25: John Williams
26: Jordan Williams
27: Kevin Williams
28: Lou Williams
29: Marcus Williams
30: Marcus Williams
31: Matt Williams
32: Mo Williams
33: Nate Williams
34: Ray Williams
35: Sam Williams
36: Sam Williams
37: Sean Williams
38: Walt Williams
Pick one: 0
Results for Aaron Williams:

You searched for "Eric Williams"
56 results found.
0: Eric Williams
1: Eric McWilliams
2: Art Williams
3: Bernie Williams
4: Deron Williams
5: Derrick Williams
6: Earl Williams
7: Herb Williams
8: Kenrich Williams
9: Kevin Williams
10: Ray Williams
11: Rob Williams
12: Ron Williams
13: Troy Williams
14: Patrick Williams
15: Aaron Williams
16: Al Williams
17: Alan Williams
18: Alvin Williams
19: Bob Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Duck Williams
26: Elliot Williams
27: Fly Williams
28: Frank Williams
29: Gene Williams
30: Grant Williams
31: Gus Williams
32: Guy Williams
33: Hank Williams
34: Jay Williams
35: Jerome Williams
36: John Williams
37: Kenny Williams
38: Lou Williams
39: Marvin Williams
40: Matt Williams
41: Mike Williams
42: Milt Williams
43: Mo Williams
44: Nate Williams
45: Pete Williams
46: Reggie Williams
47: Reggie Williams
48: Rickey Williams
49: Sam Williams
50: Sam Williams
51: Sean Williams
52: Sly Williams
53: Travis Williams
54: Walt Williams
55: Ward Williams
Pick one: 0
Results for Eric Williams:

You searched for "Loren Woods"
3 results found.
0: Loren Woods
1: Leon Wood
2: Tommy Woods
Pick one: 0
Results for Loren Woods:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2005-04-09,28-073,NJN,HOME,BOS,W (+13),1,35:52,18,32,...,7,3,4,1,2,2,45,35.9,23,Vince Carter
1,2005-04-17,28-081,NJN,HOME,PHI,W (+21),1,42:07,17,33,...,11,5,2,0,1,0,43,34.9,25,Vince Carter
2,2005-02-11,28-016,NJN,HOME,SAS,L (-10),1,37:12,14,24,...,4,3,2,1,2,2,43,34.6,7,Vince Carter
3,2005-01-12,27-139,TOR,HOME,BOS,W (+11),1,44:12,12,22,...,4,6,2,2,0,3,37,34.0,14,Morris Peterson
4,2005-04-15,28-079,NJN,AWAY,TOR,W (+11),1,43:28,15,26,...,9,4,3,0,1,3,39,33.5,7,Vince Carter

In [21]:

TOR_2006_gamelog = []

for p in TOR_df_2006_players:
    player_log = get_game_logs(str(p), SEASON_2006_START, SEASON_2006_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2006_gamelog.append(player_log)
TOR_2006_gamelog = pd.concat(TOR_2006_gamelog)    
TOR_2006_gamelogs = TOR_2006_gamelog.copy()
TOR_2006_gamelogs['GAME_SCORE'] = TOR_2006_gamelogs['GAME_SCORE'].astype(float)
TOR_2006_games = TOR_2006_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2006_games_csv = TOR_2006_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2006_games.csv', index=False)
TOR_2006_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2006_games.csv')
TOR_2006_games_proc.head()

You searched for "Rafael Araújo"
1 result found.
Rafael Araujo
Results for Rafael Araujo:

You searched for "Andre Barrett"
5 results found.
0: Andre Barrett
1: Ernie Barrett
2: Mike Barrett
3: RJ Barrett
4: Andre Emmett
Pick one: 0
Results for Andre Barrett:

You searched for "Matt Bonner"
4 results found.
0: Matt Bonner
1: Matt Barnes
2: Matt Mooney
3: Matt Geiger
Pick one: 0
Results for Matt Bonner:

You searched for "Chris Bosh"
18 results found.
0: Chris Bosh
1: Chris Babb
2: Chris Ford
3: Chris Boucher
4: Chris Carr
5: Chris Jent
6: Chris King
7: Chris Mihm
8: Chris Munk
9: Chris Paul
10: Chris Smith
11: Chris Smith
12: Chris Taft
13: Chris Welp
14: Chris Duhon
15: Chris Mills
16: Chris Morris
17: Chris Owens
Pick one: 0
Results for Chris Bosh:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Antonio Davis"
6 results found.
0: Antonio Davis
1: Antonio Daniels
2: Anthony Davis
3: Antonio Burks
4: Antonio Harvey
5: Antonio Lang
Pick one: 0
Results for Antonio Davis:

You searched for "Joey Graham"
5 results found.
0: Joey Graham
1: Greg Graham
2: Mal Graham
3: Paul Graham
4: Joe Hamood
Pick one: 0
Results for Joey Graham:

You searched for "Mike James"
33 results found.
0: Mike James
1: Mike James
2: Mike Davis
3: Mike Davis
4: Mike Farmer
5: Mike Gale
6: Gene James
7: Tim James
8: Mike Niles
9: Mike Barr
10: Mike Evans
11: Mike Green
12: Mike Hall
13: Mike Harper
14: Mike Harris
15: Mike Jackson
16: Billy James
17: Damion James
18: Jake Jones
19: Mike Kearns
20: Mike Lewis
21: Mike Maloy
22: Mike McGee
23: Mike Sanders
24: Mike Smrek
25: Mike Tobey
26: Mike Wilks
27: Mike Bantom
28: Mike Bloom
29: Mike Bratz
30: Mike Novak
31: Mike Pratt
32: Mike Price
Pick one: 0
Results for Mike James:

You searched for "Darrick Martin"
5 results found.
0: Darrick Martin
1: Maurice Martin
2: Derrick Gervin
3: Cartier Martin
4: Derrick Walton
Pick one: 0
Results for Darrick Martin:

You searched for "Morris Peterson"
1 result found.
Morris Peterson
Results for Morris Peterson:

You searched for "Jalen Rose"
9 results found.
0: Jalen Rose
1: Jalen Jones
2: Malik Rose
3: Jaylen Brown
4: James Posey
5: Glen Rice
6: Glen Rice
7: Jalen Harris
8: Al Roges
Pick one: 0
Results for Jalen Rose:

You searched for "Pape Sow"
2 results found.
0: Pape Sow
1: Pape Sy
Pick one: 0
Results for Pape Sow:

You searched for "Charlie Villanueva"
1 result found.
Charlie Villanueva
Results for Charlie Villanueva:

You searched for "Aaron Williams"
39 results found.
0: Aaron Williams
1: Deron Williams
2: Jason Williams
3: Ron Williams
4: Alan Williams
5: Alvin Williams
6: Art Williams
7: Earl Williams
8: Jayson Williams
9: Marvin Williams
10: Rob Williams
11: Troy Williams
12: Ward Williams
13: Al Williams
14: Bob Williams
15: Brandon Williams
16: Corey Williams
17: Eric Williams
18: Frank Williams
19: Grant Williams
20: Hank Williams
21: Herb Williams
22: Jawad Williams
23: Jay Williams
24: Jerome Williams
25: John Williams
26: Jordan Williams
27: Kevin Williams
28: Lou Williams
29: Marcus Williams
30: Marcus Williams
31: Matt Williams
32: Mo Williams
33: Nate Williams
34: Ray Williams
35: Sam Williams
36: Sam Williams
37: Sean Williams
38: Walt Williams
Pick one: 0
Results for Aaron Williams:

You searched for "Alvin Williams"
24 results found.
0: Alvin Williams
1: Alan Williams
2: Kevin Williams
3: Marvin Williams
4: Aaron Williams
5: Al Williams
6: Art Williams
7: Cliff Williams
8: Deron Williams
9: Elliot Williams
10: Eric Williams
11: Fly Williams
12: Jason Williams
13: Jayson Williams
14: John Williams
15: Justin Williams
16: Lou Williams
17: Ron Williams
18: Sean Williams
19: Sly Williams
20: Travis Williams
21: Walt Williams
22: Willie Williams
23: Kevin Willis
Pick one: 0
Results for Alvin Williams:

You searched for "Eric Williams"
56 results found.
0: Eric Williams
1: Eric McWilliams
2: Art Williams
3: Bernie Williams
4: Deron Williams
5: Derrick Williams
6: Earl Williams
7: Herb Williams
8: Kenrich Williams
9: Kevin Williams
10: Ray Williams
11: Rob Williams
12: Ron Williams
13: Troy Williams
14: Patrick Williams
15: Aaron Williams
16: Al Williams
17: Alan Williams
18: Alvin Williams
19: Bob Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Duck Williams
26: Elliot Williams
27: Fly Williams
28: Frank Williams
29: Gene Williams
30: Grant Williams
31: Gus Williams
32: Guy Williams
33: Hank Williams
34: Jay Williams
35: Jerome Williams
36: John Williams
37: Kenny Williams
38: Lou Williams
39: Marvin Williams
40: Matt Williams
41: Mike Williams
42: Milt Williams
43: Mo Williams
44: Nate Williams
45: Pete Williams
46: Reggie Williams
47: Reggie Williams
48: Rickey Williams
49: Sam Williams
50: Sam Williams
51: Sean Williams
52: Sly Williams
53: Travis Williams
54: Walt Williams
55: Ward Williams
Pick one: 0
Results for Eric Williams:

You searched for "Loren Woods"
3 results found.
0: Loren Woods
1: Leon Wood
2: Tommy Woods
Pick one: 0
Results for Loren Woods:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2006-03-26,21-214,TOR,AWAY,MIL,L (-9),1,45:59,20,32,...,9,3,1,0,3,4,48,36.0,-6,Charlie Villanueva
1,2006-04-14,30-295,TOR,HOME,DET,W (+5),1,40:56,9,16,...,4,6,1,0,4,1,39,34.2,1,Mike James
2,2006-03-31,28-217,TOR,HOME,PHO,L (-14),1,46:42,13,19,...,8,3,1,0,2,2,38,32.6,-13,Morris Peterson
3,2005-12-27,21-278,TOR,AWAY,DET,L (-7),1,44:04,16,26,...,11,5,0,3,1,2,37,31.9,-12,Chris Bosh
4,2006-02-01,21-314,TOR,HOME,WAS,W (+5),1,41:47,14,19,...,13,4,0,1,1,3,33,31.3,8,Chris Bosh

In [24]:
# removed luke jackson

TOR_2007_gamelog = []

for p in TOR_df_2007_players:
    player_log = get_game_logs(str(p), SEASON_2007_START, SEASON_2007_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2007_gamelog.append(player_log)
TOR_2007_gamelog = pd.concat(TOR_2007_gamelog)    
TOR_2007_gamelogs = TOR_2007_gamelog.copy()
TOR_2007_gamelogs['GAME_SCORE'] = TOR_2007_gamelogs['GAME_SCORE'].astype(float)
TOR_2007_games = TOR_2007_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2007_games_csv = TOR_2007_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2007_games.csv', index=False)
TOR_2007_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2007_games.csv')
TOR_2007_games_proc.head()

You searched for "Andrea Bargnani"
1 result found.
Andrea Bargnani
Results for Andrea Bargnani:

You searched for "Chris Bosh"
18 results found.
0: Chris Bosh
1: Chris Babb
2: Chris Ford
3: Chris Boucher
4: Chris Carr
5: Chris Jent
6: Chris King
7: Chris Mihm
8: Chris Munk
9: Chris Paul
10: Chris Smith
11: Chris Smith
12: Chris Taft
13: Chris Welp
14: Chris Duhon
15: Chris Mills
16: Chris Morris
17: Chris Owens
Pick one: 0
Results for Chris Bosh:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Juan Dixon"
1 result found.
Juan Dixon
Results for Juan Dixon:

You searched for "T.J. Ford"
7 results found.
0: T.J. Ford
1: Bob Ford
2: Don Ford
3: Jake Ford
4: Phil Ford
5: T.J. Leaf
6: O.J. Mayo
Pick one: 0
Results for T.J. Ford:

You searched for "Jorge Garbajosa"
1 result found.
Jorge Garbajosa
Results for Jorge Garbajosa:

You searched for "Joey Graham"
5 results found.
0: Joey Graham
1: Greg Graham
2: Mal Graham
3: Paul Graham
4: Joe Hamood
Pick one: 0
Results for Joey Graham:

You searched for "Kris Humphries"
2 results found.
0: Kris Humphries
1: Jay Humphries
Pick one: 0
Results for Kris Humphries:

You searched for "Fred Jones"
29 results found.
0: Fred Jones
1: Tre Jones
2: Fred Foster
3: Fred Jacobs
4: Bill Jones
5: Earl Jones
6: Jake Jones
7: Jalen Jones
8: James Jones
9: K.C. Jones
10: Larry Jones
11: Mark Jones
12: Mark Jones
13: Nick Jones
14: Ozell Jones
15: Perry Jones
16: Rich Jones
17: Sam Jones
18: Steve Jones
19: Tyus Jones
20: Wali Jones
21: Wil Jones
22: Red Owens
23: Fred Paine
24: Fred Roberts
25: Fred Brown
26: Fred Diute
27: Fred Vinson
28: Fred Hilton
Pick one: 0
Results for Fred Jones:

You searched for "Darrick Martin"
5 results found.
0: Darrick Martin
1: Maurice Martin
2: Derrick Gervin
3: Cartier Martin
4: Derrick Walton
Pick one: 0
Results for Darrick Martin:

You searched for "Rasho Nesterović"
1 result found.
Rasho Nesterovic
Results for Rasho Nesterovic:

You searched for "Anthony Parker"
10 results found.
0: Anthony Parker
1: Anthony Carter
2: Tony Parker
3: Anthony Peeler
4: Anthony Tucker
5: Anthony Bonner
6: Anthony Miller
7: Anthony Taylor
8: Anthony Avent
9: Anthony Pullard
Pick one: 0
Results for Anthony Parker:

You searched for "Morris Peterson"
1 result found.
Morris Peterson
Results for Morris Peterson:

You searched for "Uroš Slokar"
1 result found.
Uros Slokar
Results for Uros Slokar:

You searched for "Pape Sow"
2 results found.
0: Pape Sow
1: Pape Sy
Pick one: 0
Results for Pape Sow:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2007-02-07,22-320,TOR,HOME,ORL,W (+10),1,45:37,13,25,...,8,3,1,1,1,1,41,33.9,13,Chris Bosh
1,2006-11-18,23-239,TOR,AWAY,DEN,L (-8),1,38:25,10,16,...,5,18,2,0,3,3,26,31.9,9,T.J. Ford
2,2007-01-31,22-313,TOR,HOME,WAS,W (+10),1,39:02,15,19,...,8,2,1,2,1,2,34,29.9,17,Chris Bosh
3,2007-01-10,22-292,TOR,AWAY,MIL,W (+13),1,41:28,11,16,...,8,2,0,6,3,2,30,28.6,7,Chris Bosh
4,2007-01-24,22-306,TOR,HOME,NOK,W (+2),1,46:20,11,19,...,7,4,0,2,1,3,35,28.2,5,Chris Bosh

In [25]:


TOR_2008_gamelog = []

for p in TOR_df_2008_players:
    player_log = get_game_logs(str(p), SEASON_2008_START, SEASON_2008_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2008_gamelog.append(player_log)
TOR_2008_gamelog = pd.concat(TOR_2008_gamelog)    
TOR_2008_gamelogs = TOR_2008_gamelog.copy()
TOR_2008_gamelogs['GAME_SCORE'] = TOR_2008_gamelogs['GAME_SCORE'].astype(float)
TOR_2008_games = TOR_2008_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2008_games_csv = TOR_2008_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2008_games.csv', index=False)
TOR_2008_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2008_games.csv')
TOR_2008_games_proc.head()

You searched for "Andrea Bargnani"
1 result found.
Andrea Bargnani
Results for Andrea Bargnani:

You searched for "Maceo Baston"
2 results found.
0: Maceo Baston
1: Dave Batton
Pick one: 0
Results for Maceo Baston:

You searched for "Chris Bosh"
18 results found.
0: Chris Bosh
1: Chris Babb
2: Chris Ford
3: Chris Boucher
4: Chris Carr
5: Chris Jent
6: Chris King
7: Chris Mihm
8: Chris Munk
9: Chris Paul
10: Chris Smith
11: Chris Smith
12: Chris Taft
13: Chris Welp
14: Chris Duhon
15: Chris Mills
16: Chris Morris
17: Chris Owens
Pick one: 0
Results for Chris Bosh:

You searched for "Primož Brezec"
1 result found.
Primoz Brezec
Results for Primoz Brezec:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Carlos Delfino"
1 result found.
Carlos Delfino
Results for Carlos Delfino:

You searched for "Juan Dixon"
1 result found.
Juan Dixon
Results for Juan Dixon:

You searched for "T.J. Ford"
7 results found.
0: T.J. Ford
1: Bob Ford
2: Don Ford
3: Jake Ford
4: Phil Ford
5: T.J. Leaf
6: O.J. Mayo
Pick one: 0
Results for T.J. Ford:

You searched for "Jorge Garbajosa"
1 result found.
Jorge Garbajosa
Results for Jorge Garbajosa:

You searched for "Joey Graham"
5 results found.
0: Joey Graham
1: Greg Graham
2: Mal Graham
3: Paul Graham
4: Joe Hamood
Pick one: 0
Results for Joey Graham:

You searched for "Kris Humphries"
2 results found.
0: Kris Humphries
1: Jay Humphries
Pick one: 0
Results for Kris Humphries:

You searched for "Linton Johnson"
9 results found.
0: Linton Johnson
1: Britton Johnsen
2: Anthony Johnson
3: Armon Johnson
4: Clemon Johnson
5: Ivan Johnson
6: Keldon Johnson
7: Ron Johnson
8: Vinnie Johnson
Pick one: 0
Results for Linton Johnson:

You searched for "Jason Kapono"
2 results found.
0: Jason Kapono
1: Jason Lawson
Pick one: 0
Results for Jason Kapono:

You searched for "Darrick Martin"
5 results found.
0: Darrick Martin
1: Maurice Martin
2: Derrick Gervin
3: Cartier Martin
4: Derrick Walton
Pick one: 0
Results for Darrick Martin:

You searched for "Jamario Moon"
1 result found.
Jamario Moon
Results for Jamario Moon:

You searched for "Rasho Nesterović"
1 result found.
Rasho Nesterovic
Results for Rasho Nesterovic:

You searched for "Anthony Parker"
10 results found.
0: Anthony Parker
1: Anthony Carter
2: Tony Parker
3: Anthony Peeler
4: Anthony Tucker
5: Anthony Bonner
6: Anthony Miller
7: Anthony Taylor
8: Anthony Avent
9: Anthony Pullard
Pick one: 0
Results for Anthony Parker:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-02-20,23-333,TOR,HOME,ORL,W (+17),1,38:54,14,16,...,5,5,1,1,1,3,40,40.1,28,Chris Bosh
1,2007-12-22,23-273,TOR,AWAY,PHO,L (-19),1,33:02,10,20,...,13,0,0,0,0,3,42,36.3,-10,Chris Bosh
2,2007-11-24,23-245,TOR,AWAY,CLE,L (-3),1,41:46,13,25,...,4,5,1,0,1,1,41,32.6,3,Chris Bosh
3,2008-04-09,24-016,TOR,HOME,MIL,W (+18),1,40:18,11,18,...,11,2,3,4,2,2,32,31.9,20,Chris Bosh
4,2008-01-29,23-311,TOR,AWAY,WAS,L (-4),1,50:06,11,22,...,12,1,3,1,2,2,37,31.2,-8,Chris Bosh

In [30]:
# removed patrick o'bruyant 
TOR_2009_gamelog = []

for p in TOR_df_2009_players:
    player_log = get_game_logs(str(p), SEASON_2009_START, SEASON_2009_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2009_gamelog.append(player_log)
TOR_2009_gamelog = pd.concat(TOR_2009_gamelog)    
TOR_2009_gamelogs = TOR_2009_gamelog.copy()
TOR_2009_gamelogs['GAME_SCORE'] = TOR_2009_gamelogs['GAME_SCORE'].astype(float)
TOR_2009_games = TOR_2009_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2009_games_csv = TOR_2009_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2009_games.csv', index=False)
TOR_2009_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2009_games.csv')
TOR_2009_games_proc.head()

You searched for "Hassan Adams"
4 results found.
0: Hassan Adams
1: Alvan Adams
2: Jaylen Adams
3: Jordan Adams
Pick one: 0
Results for Hassan Adams:

You searched for "Marcus Banks"
6 results found.
0: Marcus Banks
1: Marcus Brown
2: Marcus Camby
3: Marcus Landry
4: Marcus Paige
5: Marcus Smart
Pick one: 0
Results for Marcus Banks:

You searched for "Andrea Bargnani"
1 result found.
Andrea Bargnani
Results for Andrea Bargnani:

You searched for "Chris Bosh"
18 results found.
0: Chris Bosh
1: Chris Babb
2: Chris Ford
3: Chris Boucher
4: Chris Carr
5: Chris Jent
6: Chris King
7: Chris Mihm
8: Chris Munk
9: Chris Paul
10: Chris Smith
11: Chris Smith
12: Chris Taft
13: Chris Welp
14: Chris Duhon
15: Chris Mills
16: Chris Morris
17: Chris Owens
Pick one: 0
Results for Chris Bosh:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Quincy Douby"
2 results found.
0: Quincy Douby
1: Quincy Acy
Pick one: 0
Results for Quincy Douby:

You searched for "Joey Graham"
5 results found.
0: Joey Graham
1: Greg Graham
2: Mal Graham
3: Paul Graham
4: Joe Hamood
Pick one: 0
Results for Joey Graham:

You searched for "Kris Humphries"
2 results found.
0: Kris Humphries
1: Jay Humphries
Pick one: 0
Results for Kris Humphries:

You searched for "Nathan Jawai"
1 result found.
Nathan Jawai
Results for Nathan Jawai:

You searched for "Jason Kapono"
2 results found.
0: Jason Kapono
1: Jason Lawson
Pick one: 0
Results for Jason Kapono:

You searched for "Shawn Marion"
2 results found.
0: Shawn Marion
1: Shawn Long
Pick one: 0
Results for Shawn Marion:

You searched for "Pops Mensah-Bonsu"
1 result found.
Pops Mensah-Bonsu
Results for Pops Mensah-Bonsu:

You searched for "Jamario Moon"
1 result found.
Jamario Moon
Results for Jamario Moon:

You searched for "Anthony Parker"
10 results found.
0: Anthony Parker
1: Anthony Carter
2: Tony Parker
3: Anthony Peeler
4: Anthony Tucker
5: Anthony Bonner
6: Anthony Miller
7: Anthony Taylor
8: Anthony Avent
9: Anthony Pullard
Pick one: 0
Results for Anthony Parker:

You searched for "Will Solomon"
1 result found.
Will Solomon
Results for Will Solomon:

You searched for "Roko Ukić"
2 results found.
0: Roko Ukic
1: Ron King
Pick one: 0
Results for Roko Ukic:

You searched for "Jake Voskuhl"
1 result found.
Jake Voskuhl
Results for Jake Voskuhl:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2008-11-18,24-239,TOR,AWAY,ORL,L (-13),1,44:46,14,19,...,18,4,2,1,3,1,40,41.0,-7,Chris Bosh
1,2008-11-26,24-247,TOR,HOME,CHA,W (+7),1,45:05,15,20,...,11,0,1,2,1,3,39,34.9,5,Chris Bosh
2,2009-04-15,30-343,TOR,AWAY,CHI,W (+11),1,42:06,15,18,...,11,3,1,0,1,1,34,34.4,11,Shawn Marion
3,2008-11-21,24-242,TOR,HOME,NJN,L (-2),1,44:29,14,27,...,9,4,0,0,2,2,42,31.8,4,Chris Bosh
4,2009-01-09,24-291,TOR,HOME,MEM,W (+21),1,36:57,11,13,...,10,1,1,3,2,2,32,31.3,15,Chris Bosh

In [34]:

TOR_2010_gamelog = []

for p in TOR_df_2010_players:
    player_log = get_game_logs(str(p), SEASON_2010_START, SEASON_2010_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2010_gamelog.append(player_log)
TOR_2010_gamelog = pd.concat(TOR_2010_gamelog)    
TOR_2010_gamelogs = TOR_2010_gamelog.copy()
TOR_2010_gamelogs['GAME_SCORE'] = TOR_2010_gamelogs['GAME_SCORE'].astype(float)
TOR_2010_games = TOR_2010_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2010_games_csv = TOR_2010_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2010_games.csv', index=False)
TOR_2010_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2010_games.csv')
TOR_2010_games_proc.head()

You searched for "Marcus Banks"
6 results found.
0: Marcus Banks
1: Marcus Brown
2: Marcus Camby
3: Marcus Landry
4: Marcus Paige
5: Marcus Smart
Pick one: 0
Results for Marcus Banks:

You searched for "Andrea Bargnani"
1 result found.
Andrea Bargnani
Results for Andrea Bargnani:

You searched for "Marco Belinelli"
1 result found.
Marco Belinelli
Results for Marco Belinelli:

You searched for "Chris Bosh"
18 results found.
0: Chris Bosh
1: Chris Babb
2: Chris Ford
3: Chris Boucher
4: Chris Carr
5: Chris Jent
6: Chris King
7: Chris Mihm
8: Chris Munk
9: Chris Paul
10: Chris Smith
11: Chris Smith
12: Chris Taft
13: Chris Welp
14: Chris Duhon
15: Chris Mills
16: Chris Morris
17: Chris Owens
Pick one: 0
Results for Chris Bosh:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "Reggie Evans"
10 results found.
0: Reggie Evans
1: Reggie Geary
2: Reggie Hanson
3: Reggie Hearn
4: Reggie King
5: Reggie Lewis
6: Reggie Royals
7: Reggie Theus
8: Reggie Perry
9: Reggie Jordan
Pick one: 0
Results for Reggie Evans:

You searched for "Jarrett Jack"
1 result found.
Jarrett Jack
Results for Jarrett Jack:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Pops Mensah-Bonsu"
1 result found.
Pops Mensah-Bonsu
Results for Pops Mensah-Bonsu:

You searched for "Rasho Nesterović"
1 result found.
Rasho Nesterovic
Results for Rasho Nesterovic:

You searched for "Hedo Türkoğlu"
1 result found.
Hedo Turkoglu
Results for Hedo Turkoglu:

You searched for "Sonny Weems"
1 result found.
Sonny Weems
Results for Sonny Weems:

You searched for "Antoine Wright"
2 results found.
0: Antoine Wright
1: Antoine Walker
Pick one: 0
Results for Antoine Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-04-04,26-011,TOR,HOME,GSW,L (-1),1,41:18,11,19,...,13,0,5,1,3,3,42,38.9,3,Chris Bosh
1,2010-01-20,25-302,TOR,AWAY,MIL,L (-6),1,42:42,15,26,...,12,4,1,0,1,3,44,37.4,2,Chris Bosh
2,2010-02-07,25-320,TOR,HOME,SAC,W (+11),1,41:13,14,18,...,11,5,0,1,2,1,36,34.1,24,Chris Bosh
3,2009-12-30,25-281,TOR,HOME,CHA,W (+4),1,37:26,11,20,...,13,2,2,1,1,0,33,32.8,4,Chris Bosh
4,2009-10-30,25-220,TOR,AWAY,MEM,L (-8),1,38:26,13,25,...,12,4,1,2,1,4,37,30.9,-2,Chris Bosh

In [35]:

TOR_2011_gamelog = []

for p in TOR_df_2011_players:
    player_log = get_game_logs(str(p), SEASON_2011_START, SEASON_2011_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2011_gamelog.append(player_log)
TOR_2011_gamelog = pd.concat(TOR_2011_gamelog)    
TOR_2011_gamelogs = TOR_2011_gamelog.copy()
TOR_2011_gamelogs['GAME_SCORE'] = TOR_2011_gamelogs['GAME_SCORE'].astype(float)
TOR_2011_games = TOR_2011_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2011_games_csv = TOR_2011_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2011_games.csv', index=False)
TOR_2011_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2011_games.csv')
TOR_2011_games_proc.head()

You searched for "Alexis Ajinça"
1 result found.
Alexis Ajinca
Results for Alexis Ajinca:

You searched for "Solomon Alabi"
2 results found.
0: Solomon Alabi
1: Solomon Hill
Pick one: 0
Results for Solomon Alabi:

You searched for "David Andersen"
4 results found.
0: David Andersen
1: Chris Andersen
2: Dan Anderson
3: Dan Anderson
Pick one: 0
Results for David Andersen:

You searched for "Marcus Banks"
6 results found.
0: Marcus Banks
1: Marcus Brown
2: Marcus Camby
3: Marcus Landry
4: Marcus Paige
5: Marcus Smart
Pick one: 0
Results for Marcus Banks:

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Andrea Bargnani"
1 result found.
Andrea Bargnani
Results for Andrea Bargnani:

You searched for "Jerryd Bayless"
1 result found.
Jerryd Bayless
Results for Jerryd Bayless:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Ed Davis"
34 results found.
0: Ed Davis
1: Red Davis
2: Ben Davis
3: Lee Davis
4: Mel Davis
5: Bob Davis
6: Brad Davis
7: Glen Davis
8: Jim Davis
9: Ron Davis
10: Ed Kasid
11: Ed Rains
12: Ed Dahler
13: Bob Davies
14: Bill Davis
15: Dale Davis
16: Josh Davis
17: Mark Davis
18: Mark Davis
19: Mike Davis
20: Mike Davis
21: Paul Davis
22: Terry Davis
23: Tyler Davis
24: Walt Davis
25: Ed Earle
26: Ed Gayda
27: Ed Melvin
28: Ed Beach
29: Ed Leede
30: Ed Mikan
31: Ed Nealy
32: Med Park
33: Todd Day
Pick one: 0
Results for Ed Davis:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "Joey Dorsey"
4 results found.
0: Joey Dorsey
1: Jacky Dorsey
2: Ron Dorsey
3: Tyler Dorsey
Pick one: 0
Results for Joey Dorsey:

You searched for "Ronald Dupree"
2 results found.
0: Ronald Dupree
1: Ronald Murray
Pick one: 0
Results for Ronald Dupree:

You searched for "Reggie Evans"
10 results found.
0: Reggie Evans
1: Reggie Geary
2: Reggie Hanson
3: Reggie Hearn
4: Reggie King
5: Reggie Lewis
6: Reggie Royals
7: Reggie Theus
8: Reggie Perry
9: Reggie Jordan
Pick one: 0
Results for Reggie Evans:

You searched for "Sundiata Gaines"
1 result found.
Sundiata Gaines
Results for Sundiata Gaines:

You searched for "Jarrett Jack"
1 result found.
Jarrett Jack
Results for Jarrett Jack:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "James Johnson"
32 results found.
0: James Johnson
1: Amir Johnson
2: Dave Johnson
3: Joe Johnson
4: James Robinson
5: James Cotton
6: Andy Johnson
7: Armon Johnson
8: Avery Johnson
9: Cameron Johnson
10: Charles Johnson
11: Cheese Johnson
12: Chris Johnson
13: Chris Johnson
14: Ed Johnson
15: Gus Johnson
16: JaJuan Johnson
17: John Johnson
18: Ken Johnson
19: Ken Johnson
20: Larry Johnson
21: Larry Johnson
22: Lee Johnson
23: Magic Johnson
24: Marques Johnson
25: Ralph Johnson
26: Stew Johnson
27: Trey Johnson
28: Tyler Johnson
29: Nate Johnston
30: James Jones
31: James Collins
Pick one: 0
Results for James Johnson:

You searched for "Trey Johnson"
38 results found.
0: Trey Johnson
1: Andy Johnson
2: Avery Johnson
3: Clay Johnson
4: Ed Johnson
5: Eric Johnson
6: Joe Johnson
7: Ken Johnson
8: Ken Johnson
9: Larry Johnson
10: Larry Johnson
11: Lee Johnson
12: Ron Johnson
13: Stew Johnson
14: Tyler Johnson
15: Amir Johnson
16: Armon Johnson
17: Arnie Johnson
18: B.J. Johnson
19: Brice Johnson
20: Buck Johnson
21: Chris Johnson
22: Chris Johnson
23: Darryl Johnson
24: Dave Johnson
25: Ervin Johnson
26: Frank Johnson
27: Gus Johnson
28: Ivan Johnson
29: James Johnson
30: John Johnson
31: Mickey Johnson
32: Neil Johnson
33: Nick Johnson
34: Rich Johnson
35: Stanley Johnson
36: Steve Johnson
37: Wesley Johnson
Pick one: 0
Results for Trey Johnson:

You searched for "Linas Kleiza"
1 result found.
Linas Kleiza
Results for Linas Kleiza:

You searched for "Peja Stojaković"
1 result found.
Peja Stojakovic
Results for Peja Stojakovic:

You searched for "Sonny Weems"
1 result found.
Sonny Weems
Results for Sonny Weems:

You searched for "Julian Wright"
2 results found.
0: Julian Wright
1: Delon Wright
Pick one: 0
Results for Julian Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2010-12-08,25-043,TOR,AWAY,NYK,L (-3),1,39:27,16,24,...,7,6,2,0,1,0,41,37.1,-8,Andrea Bargnani
1,2011-03-01,29-154,TOR,HOME,NOH,W (+6),1,38:23,7,10,...,7,16,1,0,2,3,22,29.3,18,José Calderón
2,2010-12-11,22-113,TOR,AWAY,DET,W (+4),1,33:36,10,12,...,5,7,1,0,4,2,31,28.4,-4,Jerryd Bayless
3,2011-02-04,23-279,TOR,HOME,MIN,W (+11),1,36:09,8,10,...,12,6,3,2,0,3,19,28.2,14,Amir Johnson
4,2011-01-15,29-109,TOR,AWAY,WAS,L (-3),1,38:00,10,16,...,9,15,1,1,1,1,21,27.7,-1,José Calderón

In [36]:


TOR_2012_gamelog = []

for p in TOR_df_2012_players:
    player_log = get_game_logs(str(p), SEASON_2012_START, SEASON_2012_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2012_gamelog.append(player_log)
TOR_2012_gamelog = pd.concat(TOR_2012_gamelog)    
TOR_2012_gamelogs = TOR_2012_gamelog.copy()
TOR_2012_gamelogs['GAME_SCORE'] = TOR_2012_gamelogs['GAME_SCORE'].astype(float)
TOR_2012_games = TOR_2012_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2012_games_csv = TOR_2012_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2012_games.csv', index=False)
TOR_2012_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2012_games.csv')
TOR_2012_games_proc.head()

You searched for "Solomon Alabi"
2 results found.
0: Solomon Alabi
1: Solomon Hill
Pick one: 0
Results for Solomon Alabi:

You searched for "Alan Anderson"
15 results found.
0: Alan Anderson
1: Dan Anderson
2: Dan Anderson
3: Ryan Anderson
4: Alan Henderson
5: Ron Anderson
6: Cliff Anderson
7: Eric Anderson
8: Greg Anderson
9: J.J. Anderson
10: James Anderson
11: Kenny Anderson
12: Kim Anderson
13: Kyle Anderson
14: Nick Anderson
Pick one: 0
Results for Alan Anderson:

You searched for "Leandro Barbosa"
2 results found.
0: Leandro Barbosa
1: Leandro Bolmaro
Pick one: 0
Results for Leandro Barbosa:

You searched for "Andrea Bargnani"
1 result found.
Andrea Bargnani
Results for Andrea Bargnani:

You searched for "Jerryd Bayless"
1 result found.
Jerryd Bayless
Results for Jerryd Bayless:

You searched for "Rasual Butler"
2 results found.
0: Rasual Butler
1: Al Butler
Pick one: 0
Results for Rasual Butler:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Anthony Carter"
8 results found.
0: Anthony Carter
1: Anthony Parker
2: Anthony Bonner
3: Anthony Miller
4: Anthony Peeler
5: Anthony Taylor
6: Anthony Tucker
7: Anthony Avent
Pick one: 0
Results for Anthony Carter:

You searched for "Ed Davis"
34 results found.
0: Ed Davis
1: Red Davis
2: Ben Davis
3: Lee Davis
4: Mel Davis
5: Bob Davis
6: Brad Davis
7: Glen Davis
8: Jim Davis
9: Ron Davis
10: Ed Kasid
11: Ed Rains
12: Ed Dahler
13: Bob Davies
14: Bill Davis
15: Dale Davis
16: Josh Davis
17: Mark Davis
18: Mark Davis
19: Mike Davis
20: Mike Davis
21: Paul Davis
22: Terry Davis
23: Tyler Davis
24: Walt Davis
25: Ed Earle
26: Ed Gayda
27: Ed Melvin
28: Ed Beach
29: Ed Leede
30: Ed Mikan
31: Ed Nealy
32: Med Park
33: Todd Day
Pick one: 0
Results for Ed Davis:

You searched for "Justin Dentmon"
2 results found.
0: Justin Dentmon
1: Justin Patton
Pick one: 0
Results for Justin Dentmon:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "Gary Forbes"
11 results found.
0: Gary Forbes
1: Bryn Forbes
2: Gary Bergen
3: Gary Harris
4: Gary Turner
5: Gary Voce
6: Larry Fogle
7: Gary Trent
8: Gary Trent
9: Gary Alcorn
10: Gary Gregor
Pick one: 0
Results for Gary Forbes:

You searched for "Aaron Gray"
8 results found.
0: Aaron Gray
1: Gary Gray
2: Aaron Gordon
3: Devin Gray
4: Evric Gray
5: Allan Ray
6: Don Ray
7: Don Grate
Pick one: 0
Results for Aaron Gray:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "James Johnson"
32 results found.
0: James Johnson
1: Amir Johnson
2: Dave Johnson
3: Joe Johnson
4: James Robinson
5: James Cotton
6: Andy Johnson
7: Armon Johnson
8: Avery Johnson
9: Cameron Johnson
10: Charles Johnson
11: Cheese Johnson
12: Chris Johnson
13: Chris Johnson
14: Ed Johnson
15: Gus Johnson
16: JaJuan Johnson
17: John Johnson
18: Ken Johnson
19: Ken Johnson
20: Larry Johnson
21: Larry Johnson
22: Lee Johnson
23: Magic Johnson
24: Marques Johnson
25: Ralph Johnson
26: Stew Johnson
27: Trey Johnson
28: Tyler Johnson
29: Nate Johnston
30: James Jones
31: James Collins
Pick one: 0
Results for James Johnson:

You searched for "Linas Kleiza"
1 result found.
Linas Kleiza
Results for Linas Kleiza:

You searched for "Jamaal Magloire"
1 result found.
Jamaal Magloire
Results for Jamaal Magloire:

You searched for "Ben Uzoh"
5 results found.
0: Ben Uzoh
1: Ben Moore
2: Beno Udrih
3: Ben Kelso
4: Don Ohl
Pick one: 0
Results for Ben Uzoh:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2012-01-24,26-090,TOR,AWAY,PHO,W (+3),1,42:16,10,21,...,6,2,2,1,2,2,36,28.8,1,Andrea Bargnani
1,2012-01-04,26-070,TOR,HOME,CLE,W (+15),1,34:06,11,16,...,7,3,0,1,2,1,31,26.3,22,Andrea Bargnani
2,2012-03-16,23-209,TOR,AWAY,MEM,W (+4),1,43:35,9,17,...,6,9,3,1,3,6,28,25.7,-3,Jerryd Bayless
3,2012-02-12,30-137,TOR,HOME,LAL,L (-2),1,37:09,13,18,...,2,6,0,0,2,0,30,25.4,-3,José Calderón
4,2012-02-14,30-139,TOR,HOME,NYK,L (-3),1,38:43,11,17,...,7,9,3,1,4,2,25,25.2,-8,José Calderón

In [37]:

TOR_2013_gamelog = []

for p in TOR_df_2013_players:
    player_log = get_game_logs(str(p), SEASON_2013_START, SEASON_2013_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2013_gamelog.append(player_log)
TOR_2013_gamelog = pd.concat(TOR_2013_gamelog)    
TOR_2013_gamelogs = TOR_2013_gamelog.copy()
TOR_2013_gamelogs['GAME_SCORE'] = TOR_2013_gamelogs['GAME_SCORE'].astype(float)
TOR_2013_games = TOR_2013_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2013_games_csv = TOR_2013_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2013_games.csv', index=False)
TOR_2013_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2013_games.csv')
TOR_2013_games_proc.head()

You searched for "Quincy Acy"
2 results found.
0: Quincy Acy
1: Quincy Douby
Pick one: 0
Results for Quincy Acy:

You searched for "Alan Anderson"
15 results found.
0: Alan Anderson
1: Dan Anderson
2: Dan Anderson
3: Ryan Anderson
4: Alan Henderson
5: Ron Anderson
6: Cliff Anderson
7: Eric Anderson
8: Greg Anderson
9: J.J. Anderson
10: James Anderson
11: Kenny Anderson
12: Kim Anderson
13: Kyle Anderson
14: Nick Anderson
Pick one: 0
Results for Alan Anderson:

You searched for "Andrea Bargnani"
1 result found.
Andrea Bargnani
Results for Andrea Bargnani:

You searched for "José Calderón"
1 result found.
Jose Calderon
Results for Jose Calderon:

You searched for "Ed Davis"
34 results found.
0: Ed Davis
1: Red Davis
2: Ben Davis
3: Lee Davis
4: Mel Davis
5: Bob Davis
6: Brad Davis
7: Glen Davis
8: Jim Davis
9: Ron Davis
10: Ed Kasid
11: Ed Rains
12: Ed Dahler
13: Bob Davies
14: Bill Davis
15: Dale Davis
16: Josh Davis
17: Mark Davis
18: Mark Davis
19: Mike Davis
20: Mike Davis
21: Paul Davis
22: Terry Davis
23: Tyler Davis
24: Walt Davis
25: Ed Earle
26: Ed Gayda
27: Ed Melvin
28: Ed Beach
29: Ed Leede
30: Ed Mikan
31: Ed Nealy
32: Med Park
33: Todd Day
Pick one: 0
Results for Ed Davis:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "Landry Fields"
2 results found.
0: Landry Fields
1: Kenny Fields
Pick one: 0
Results for Landry Fields:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Aaron Gray"
8 results found.
0: Aaron Gray
1: Gary Gray
2: Aaron Gordon
3: Devin Gray
4: Evric Gray
5: Allan Ray
6: Don Ray
7: Don Grate
Pick one: 0
Results for Aaron Gray:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Linas Kleiza"
1 result found.
Linas Kleiza
Results for Linas Kleiza:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "John Lucas III"
2 results found.
0: John Lucas III
1: John Lucas
Pick one: 0
Results for John Lucas III:

You searched for "Dominic McGuire"
1 result found.
Dominic McGuire
Results for Dominic McGuire:

You searched for "Mickaël Piétrus"
1 result found.
Mickael Pietrus
Results for Mickael Pietrus:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Sebastian Telfair"
1 result found.
Sebastian Telfair
Results for Sebastian Telfair:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2013-04-01,26-227,TOR,HOME,DET,L (-10),1,40:16,13,18,...,6,5,1,1,1,4,34,31.4,-11,Rudy Gay
1,2012-12-05,26-255,TOR,AWAY,SAC,L (-7),1,38:02,9,20,...,5,11,1,0,3,5,34,28.8,-6,Kyle Lowry
2,2012-11-23,27-028,TOR,AWAY,DET,L (-1),1,37:41,13,20,...,5,4,1,1,2,3,34,28.4,-3,Andrea Bargnani
3,2012-11-04,26-224,TOR,HOME,MIN,W (+19),1,31:46,8,10,...,7,5,3,0,2,1,22,26.0,10,Kyle Lowry
4,2013-03-08,23-213,TOR,AWAY,LAL,L (-2),1,44:00,12,18,...,5,5,1,0,0,1,28,25.8,0,DeMar DeRozan

In [38]:


TOR_2014_gamelog = []

for p in TOR_df_2014_players:
    player_log = get_game_logs(str(p), SEASON_2014_START, SEASON_2014_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2014_gamelog.append(player_log)
TOR_2014_gamelog = pd.concat(TOR_2014_gamelog)    
TOR_2014_gamelogs = TOR_2014_gamelog.copy()
TOR_2014_gamelogs['GAME_SCORE'] = TOR_2014_gamelogs['GAME_SCORE'].astype(float)
TOR_2014_games = TOR_2014_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2014_games_csv = TOR_2014_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2014_games.csv', index=False)
TOR_2014_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2014_games.csv')
TOR_2014_games_proc.head()

You searched for "Quincy Acy"
2 results found.
0: Quincy Acy
1: Quincy Douby
Pick one: 0
Results for Quincy Acy:

You searched for "D.J. Augustin"
1 result found.
D.J. Augustin
Results for D.J. Augustin:

You searched for "Dwight Buycks"
1 result found.
Dwight Buycks
Results for Dwight Buycks:

You searched for "Austin Daye"
4 results found.
0: Austin Daye
1: Austin Carr
2: Justin James
3: Justin Reed
Pick one: 0
Results for Austin Daye:

You searched for "Nando De Colo"
1 result found.
Nando De Colo
Results for Nando De Colo:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "Landry Fields"
2 results found.
0: Landry Fields
1: Kenny Fields
Pick one: 0
Results for Landry Fields:

You searched for "Rudy Gay"
4 results found.
0: Rudy Gay
1: Todd Day
2: Ed Gray
3: Gary Gray
Pick one: 0
Results for Rudy Gay:

You searched for "Aaron Gray"
8 results found.
0: Aaron Gray
1: Gary Gray
2: Aaron Gordon
3: Devin Gray
4: Evric Gray
5: Allan Ray
6: Don Ray
7: Don Grate
Pick one: 0
Results for Aaron Gray:

You searched for "Tyler Hansbrough"
2 results found.
0: Tyler Hansbrough
1: Ben Hansbrough
Pick one: 0
Results for Tyler Hansbrough:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Steve Novak"
9 results found.
0: Steve Novak
1: Steve Blake
2: Steve Jones
3: Steve Nash
4: Mike Novak
5: Steve Bardo
6: Steve Green
7: Steve Kerr
8: Steve Henson
Pick one: 0
Results for Steve Novak:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "John Salmons"
7 results found.
0: John Salmons
1: John Collins
2: John Long
3: John Paxson
4: John Salley
5: Johnny Simmons
6: John Clawson
Pick one: 0
Results for John Salmons:

You searched for "Julyan Stone"
1 result found.
Julyan Stone
Results for Julyan Stone:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Greivis Vásquez"
1 result found.
Greivis Vasquez
Results for Greivis Vasquez:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-01-25,22-354,TOR,HOME,LAC,L (-8),1,43:53,16,29,...,9,1,1,0,3,4,51,37.7,-4,Terrence Ross
1,2014-01-31,27-167,SAC,AWAY,DAL,L (-4),1,35:36,10,16,...,12,6,1,0,3,0,35,34.0,5,Rudy Gay
2,2014-02-07,24-184,TOR,AWAY,LAC,L (-13),1,40:58,9,21,...,5,8,2,1,0,2,36,33.5,-15,DeMar DeRozan
3,2013-12-28,27-278,TOR,HOME,NYK,W (+15),1,37:37,10,17,...,8,11,1,0,1,3,32,32.6,17,Kyle Lowry
4,2014-01-21,27-157,SAC,AWAY,NOP,W (+17),1,42:28,16,25,...,8,5,0,0,3,5,41,31.2,12,Rudy Gay

In [39]:


TOR_2015_gamelog = []

for p in TOR_df_2015_players:
    player_log = get_game_logs(str(p), SEASON_2015_START, SEASON_2015_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2015_gamelog.append(player_log)
TOR_2015_gamelog = pd.concat(TOR_2015_gamelog)    
TOR_2015_gamelogs = TOR_2015_gamelog.copy()
TOR_2015_gamelogs['GAME_SCORE'] = TOR_2015_gamelogs['GAME_SCORE'].astype(float)
TOR_2015_games = TOR_2015_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2015_games_csv = TOR_2015_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2015_games.csv', index=False)
TOR_2015_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2015_games.csv')
TOR_2015_games_proc.head()

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "Landry Fields"
2 results found.
0: Landry Fields
1: Kenny Fields
Pick one: 0
Results for Landry Fields:

You searched for "Tyler Hansbrough"
2 results found.
0: Tyler Hansbrough
1: Ben Hansbrough
Pick one: 0
Results for Tyler Hansbrough:

You searched for "Chuck Hayes"
5 results found.
0: Chuck Hayes
1: Chuck Share
2: Chuck Lloyd
3: Chuck Noble
4: Chuck Terry
Pick one: 0
Results for Chuck Hayes:

You searched for "Amir Johnson"
43 results found.
0: Amir Johnson
1: Alize Johnson
2: Andy Johnson
3: Armon Johnson
4: Arnie Johnson
5: Avery Johnson
6: Eric Johnson
7: James Johnson
8: Magic Johnson
9: Neil Johnson
10: Omari Johnson
11: B.J. Johnson
12: Brice Johnson
13: Buck Johnson
14: Cameron Johnson
15: Chris Johnson
16: Chris Johnson
17: Clay Johnson
18: Dakari Johnson
19: Dave Johnson
20: Ed Johnson
21: Eddie Johnson
22: Eddie Johnson
23: Ervin Johnson
24: Gus Johnson
25: Ivan Johnson
26: Joe Johnson
27: John Johnson
28: Ken Johnson
29: Ken Johnson
30: Kevin Johnson
31: Larry Johnson
32: Larry Johnson
33: Lee Johnson
34: Nick Johnson
35: Ollie Johnson
36: Ralph Johnson
37: Rich Johnson
38: Ron Johnson
39: Stew Johnson
40: Trey Johnson
41: Tyler Johnson
42: Neil Johnston
Pick one: 0
Results for Amir Johnson:

You searched for "James Johnson"
32 results found.
0: James Johnson
1: Amir Johnson
2: Dave Johnson
3: Joe Johnson
4: James Robinson
5: James Cotton
6: Andy Johnson
7: Armon Johnson
8: Avery Johnson
9: Cameron Johnson
10: Charles Johnson
11: Cheese Johnson
12: Chris Johnson
13: Chris Johnson
14: Ed Johnson
15: Gus Johnson
16: JaJuan Johnson
17: John Johnson
18: Ken Johnson
19: Ken Johnson
20: Larry Johnson
21: Larry Johnson
22: Lee Johnson
23: Magic Johnson
24: Marques Johnson
25: Ralph Johnson
26: Stew Johnson
27: Trey Johnson
28: Tyler Johnson
29: Nate Johnston
30: James Jones
31: James Collins
Pick one: 0
Results for James Johnson:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Lucas Nogueira"
1 result found.
Lucas Nogueira
Results for Lucas Nogueira:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Greg Stiemsma"
1 result found.
Greg Stiemsma
Results for Greg Stiemsma:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Greivis Vásquez"
1 result found.
Greivis Vasquez
Results for Greivis Vasquez:

You searched for "Lou Williams"
44 results found.
0: Lou Williams
1: Bob Williams
2: Mo Williams
3: Rob Williams
4: Ron Williams
5: Al Williams
6: Alan Williams
7: Art Williams
8: Fly Williams
9: Gus Williams
10: Guy Williams
11: Jay Williams
12: John Williams
13: Ray Williams
14: Sam Williams
15: Sam Williams
16: Sly Williams
17: Troy Williams
18: Aaron Williams
19: Alvin Williams
20: Buck Williams
21: C.J. Williams
22: Chuck Williams
23: Cliff Williams
24: Corey Williams
25: Deron Williams
26: Duck Williams
27: Earl Williams
28: Elliot Williams
29: Eric Williams
30: Gene Williams
31: Hank Williams
32: Herb Williams
33: Jason Williams
34: Matt Williams
35: Mike Williams
36: Milt Williams
37: Monty Williams
38: Nate Williams
39: Pete Williams
40: Scott Williams
41: Sean Williams
42: Walt Williams
43: Ward Williams
Pick one: 0
Results for Lou Williams:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2014-12-03,28-253,TOR,AWAY,UTA,W (+19),1,37:34,13,22,...,5,4,1,0,2,1,39,32.5,8,Kyle Lowry
1,2014-11-05,28-225,TOR,AWAY,BOS,W (+3),1,35:30,12,17,...,4,3,2,0,0,4,35,31.6,4,Kyle Lowry
2,2015-03-02,25-207,TOR,AWAY,PHI,W (+11),1,38:14,12,24,...,9,5,2,0,2,1,35,28.8,13,DeMar DeRozan
3,2014-12-28,28-278,TOR,AWAY,DEN,W (+14),1,37:43,12,20,...,7,11,1,1,2,4,30,28.3,5,Kyle Lowry
4,2015-01-12,22-251,TOR,HOME,DET,L (-3),1,35:36,14,15,...,12,0,0,1,2,4,31,28.0,-14,Jonas Valančiūnas

In [40]:


TOR_2016_gamelog = []

for p in TOR_df_2016_players:
    player_log = get_game_logs(str(p), SEASON_2016_START, SEASON_2016_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2016_gamelog.append(player_log)
TOR_2016_gamelog = pd.concat(TOR_2016_gamelog)    
TOR_2016_gamelogs = TOR_2016_gamelog.copy()
TOR_2016_gamelogs['GAME_SCORE'] = TOR_2016_gamelogs['GAME_SCORE'].astype(float)
TOR_2016_games = TOR_2016_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2016_games_csv = TOR_2016_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2016_games.csv', index=False)
TOR_2016_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2016_games.csv')
TOR_2016_games_proc.head()

You searched for "Anthony Bennett"
3 results found.
0: Anthony Bennett
1: Tony Bennett
2: Anthony Bonner
Pick one: 0
Results for Anthony Bennett:

You searched for "Bismack Biyombo"
1 result found.
Bismack Biyombo
Results for Bismack Biyombo:

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "DeMarre Carroll"
1 result found.
DeMarre Carroll
Results for DeMarre Carroll:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "James Johnson"
32 results found.
0: James Johnson
1: Amir Johnson
2: Dave Johnson
3: Joe Johnson
4: James Robinson
5: James Cotton
6: Andy Johnson
7: Armon Johnson
8: Avery Johnson
9: Cameron Johnson
10: Charles Johnson
11: Cheese Johnson
12: Chris Johnson
13: Chris Johnson
14: Ed Johnson
15: Gus Johnson
16: JaJuan Johnson
17: John Johnson
18: Ken Johnson
19: Ken Johnson
20: Larry Johnson
21: Larry Johnson
22: Lee Johnson
23: Magic Johnson
24: Marques Johnson
25: Ralph Johnson
26: Stew Johnson
27: Trey Johnson
28: Tyler Johnson
29: Nate Johnston
30: James Jones
31: James Collins
Pick one: 0
Results for James Johnson:

You searched for "Cory Joseph"
4 results found.
0: Cory Joseph
1: Garth Joseph
2: Kris Joseph
3: Yvon Joseph
Pick one: 0
Results for Cory Joseph:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Lucas Nogueira"
1 result found.
Lucas Nogueira
Results for Lucas Nogueira:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "Norman Powell"
1 result found.
Norman Powell
Results for Norman Powell:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Luis Scola"
1 result found.
Luis Scola
Results for Luis Scola:

You searched for "Jason Thompson"
7 results found.
0: Jason Thompson
1: Dijon Thompson
2: Jack Thompson
3: John Thompson
4: David Thompson
5: Kevin Thompson
6: Paul Thompson
Pick one: 0
Results for Jason Thompson:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Delon Wright"
4 results found.
0: Delon Wright
1: Leroy Wright
2: Dorell Wright
3: Julian Wright
Pick one: 0
Results for Delon Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2016-02-26,29-338,TOR,HOME,CLE,W (+2),1,42:49,15,20,...,5,9,4,0,2,4,43,41.6,11,Kyle Lowry
1,2015-12-05,29-255,TOR,HOME,GSW,L (-3),1,38:29,14,26,...,3,7,4,1,1,2,41,37.1,8,Kyle Lowry
2,2016-01-18,29-299,TOR,HOME,BRK,W (+12),1,39:34,10,13,...,2,8,3,0,1,2,31,32.5,22,Kyle Lowry
3,2016-03-12,26-218,TOR,HOME,MIA,W (+8),1,43:11,13,26,...,10,7,2,1,3,1,38,31.0,4,DeMar DeRozan
4,2016-03-14,29-355,TOR,HOME,CHI,L (-2),1,40:36,10,20,...,11,7,3,0,3,4,33,29.2,-1,Kyle Lowry

In [41]:

TOR_2017_gamelog = []

for p in TOR_df_2017_players:
    player_log = get_game_logs(str(p), SEASON_2017_START, SEASON_2017_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2017_gamelog.append(player_log)
TOR_2017_gamelog = pd.concat(TOR_2017_gamelog)    
TOR_2017_gamelogs = TOR_2017_gamelog.copy()
TOR_2017_gamelogs['GAME_SCORE'] = TOR_2017_gamelogs['GAME_SCORE'].astype(float)
TOR_2017_games = TOR_2017_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2017_games_csv = TOR_2017_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2017_games.csv', index=False)
TOR_2017_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2017_games.csv')
TOR_2017_games_proc.head()

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "DeMarre Carroll"
1 result found.
DeMarre Carroll
Results for DeMarre Carroll:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "Serge Ibaka"
1 result found.
Serge Ibaka
Results for Serge Ibaka:

You searched for "Cory Joseph"
4 results found.
0: Cory Joseph
1: Garth Joseph
2: Kris Joseph
3: Yvon Joseph
Pick one: 0
Results for Cory Joseph:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Lucas Nogueira"
1 result found.
Lucas Nogueira
Results for Lucas Nogueira:

You searched for "Patrick Patterson"
1 result found.
Patrick Patterson
Results for Patrick Patterson:

You searched for "Jakob Poeltl"
1 result found.
Jakob Poeltl
Results for Jakob Poeltl:

You searched for "Norman Powell"
1 result found.
Norman Powell
Results for Norman Powell:

You searched for "Terrence Ross"
2 results found.
0: Terrence Ross
1: Terrence Jones
Pick one: 0
Results for Terrence Ross:

You searched for "Pascal Siakam"
1 result found.
Pascal Siakam
Results for Pascal Siakam:

You searched for "Jared Sullinger"
1 result found.
Jared Sullinger
Results for Jared Sullinger:

You searched for "P.J. Tucker"
5 results found.
0: P.J. Tucker
1: R.J. Hunter
2: Al Tucker
3: Jim Tucker
4: B.J. Tyler
Pick one: 0
Results for P.J. Tucker:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Fred VanVleet"
1 result found.
Fred VanVleet
Results for Fred VanVleet:

You searched for "Delon Wright"
4 results found.
0: Delon Wright
1: Leroy Wright
2: Dorell Wright
3: Julian Wright
Pick one: 0
Results for Delon Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2017-01-01,30-282,TOR,AWAY,LAL,W (+9),1,39:02,12,16,...,9,7,0,0,4,3,41,37.4,12,Kyle Lowry
1,2016-11-02,27-087,TOR,AWAY,WAS,W (+10),1,37:00,14,23,...,5,5,2,0,1,3,40,32.7,10,DeMar DeRozan
2,2017-03-23,27-228,TOR,AWAY,MIA,W (+17),1,36:05,14,25,...,6,3,1,0,1,0,40,32.0,3,DeMar DeRozan
3,2017-01-10,27-156,TOR,HOME,BOS,W (+8),1,37:54,16,29,...,13,0,2,0,1,1,41,32.0,19,DeMar DeRozan
4,2017-02-24,27-201,TOR,HOME,BOS,W (+10),1,37:08,15,28,...,5,5,0,0,3,2,43,30.6,15,DeMar DeRozan

In [42]:


TOR_2018_gamelog = []

for p in TOR_df_2018_players:
    player_log = get_game_logs(str(p), SEASON_2018_START, SEASON_2018_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2018_gamelog.append(player_log)
TOR_2018_gamelog = pd.concat(TOR_2018_gamelog)    
TOR_2018_gamelogs = TOR_2018_gamelog.copy()
TOR_2018_gamelogs['GAME_SCORE'] = TOR_2018_gamelogs['GAME_SCORE'].astype(float)
TOR_2018_games = TOR_2018_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2018_games_csv = TOR_2018_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2018_games.csv', index=False)
TOR_2018_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2018_games.csv')
TOR_2018_games_proc.head()

You searched for "OG Anunoby"
1 result found.
OG Anunoby
Results for OG Anunoby:

You searched for "Lorenzo Brown"
2 results found.
0: Lorenzo Brown
1: Lorenzo Romar
Pick one: 0
Results for Lorenzo Brown:

You searched for "Bruno Caboclo"
1 result found.
Bruno Caboclo
Results for Bruno Caboclo:

You searched for "DeMar DeRozan"
1 result found.
DeMar DeRozan
Results for DeMar DeRozan:

You searched for "Nigel Hayes"
2 results found.
0: Nigel Hayes
1: Jim Hayes
Pick one: 0
Results for Nigel Hayes:

You searched for "Serge Ibaka"
1 result found.
Serge Ibaka
Results for Serge Ibaka:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Alfonzo McKinnie"
1 result found.
Alfonzo McKinnie
Results for Alfonzo McKinnie:

You searched for "C.J. Miles"
7 results found.
0: C.J. Miles
1: C.J. Kupec
2: B.J. Tyler
3: C.J. Wilcox
4: T.J. Leaf
5: A.J. Price
6: D.J. White
Pick one: 0
Results for C.J. Miles:

You searched for "Malcolm Miller"
3 results found.
0: Malcolm Miller
1: Malcolm Lee
2: Malcolm Mackey
Pick one: 0
Results for Malcolm Miller:

You searched for "Lucas Nogueira"
1 result found.
Lucas Nogueira
Results for Lucas Nogueira:

You searched for "Jakob Poeltl"
1 result found.
Jakob Poeltl
Results for Jakob Poeltl:

You searched for "Norman Powell"
1 result found.
Norman Powell
Results for Norman Powell:

You searched for "Malachi Richardson"
1 result found.
Malachi Richardson
Results for Malachi Richardson:

You searched for "Pascal Siakam"
1 result found.
Pascal Siakam
Results for Pascal Siakam:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Fred VanVleet"
1 result found.
Fred VanVleet
Results for Fred VanVleet:

You searched for "Delon Wright"
4 results found.
0: Delon Wright
1: Leroy Wright
2: Dorell Wright
3: Julian Wright
Pick one: 0
Results for Delon Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2018-01-01,28-147,TOR,HOME,MIL,W (+4),1,43:27,17,29,...,5,8,1,1,2,4,52,44.1,9,DeMar DeRozan
1,2017-12-21,28-136,TOR,AWAY,PHI,W (+5),1,39:28,13,21,...,5,3,2,1,2,3,45,39.0,12,DeMar DeRozan
2,2018-03-07,28-212,TOR,AWAY,DET,W (+2),1,43:19,16,28,...,4,6,0,0,1,1,42,32.8,9,DeMar DeRozan
3,2018-01-03,28-149,TOR,AWAY,CHI,W (+9),1,33:37,10,20,...,3,6,3,0,0,2,35,32.3,-5,DeMar DeRozan
4,2018-01-20,31-301,TOR,AWAY,MIN,L (-6),1,33:46,14,25,...,5,5,0,0,0,5,40,31.1,5,Kyle Lowry

In [43]:

TOR_2019_gamelog = []

for p in TOR_df_2019_players:
    player_log = get_game_logs(str(p), SEASON_2019_START, SEASON_2019_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2019_gamelog.append(player_log)
TOR_2019_gamelog = pd.concat(TOR_2019_gamelog)    
TOR_2019_gamelogs = TOR_2019_gamelog.copy()
TOR_2019_gamelogs['GAME_SCORE'] = TOR_2019_gamelogs['GAME_SCORE'].astype(float)
TOR_2019_games = TOR_2019_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2019_games_csv = TOR_2019_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2019_games.csv', index=False)
TOR_2019_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2019_games.csv')
TOR_2019_games_proc.head()

You searched for "OG Anunoby"
1 result found.
OG Anunoby
Results for OG Anunoby:

You searched for "Chris Boucher"
5 results found.
0: Chris Boucher
1: Chris Bosh
2: Chris Hunter
3: Chris Porter
4: Chris Herren
Pick one: 0
Results for Chris Boucher:

You searched for "Lorenzo Brown"
2 results found.
0: Lorenzo Brown
1: Lorenzo Romar
Pick one: 0
Results for Lorenzo Brown:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "Danny Green"
20 results found.
0: Danny Green
1: Kenny Green
2: Johnny Green
3: Danny Finn
4: Danny Granger
5: A.C. Green
6: Devin Green
7: Ken Green
8: Lamar Green
9: Sean Green
10: Sidney Green
11: Donte Greene
12: Lynn Greer
13: Danny Vranes
14: Danny Ainge
15: Danny Doyle
16: Danny Ferry
17: Dennis Grey
18: Danny Wagner
19: Danny Young
Pick one: 0
Results for Danny Green:

You searched for "Serge Ibaka"
1 result found.
Serge Ibaka
Results for Serge Ibaka:

You searched for "Kawhi Leonard"
2 results found.
0: Kawhi Leonard
1: Gary Leonard
Pick one: 0
Results for Kawhi Leonard:

You searched for "Jeremy Lin"
5 results found.
0: Jeremy Lin
1: Jeremy Lamb
2: Jeremy Evans
3: Jerome Lane
4: Jeremy Tyler
Pick one: 0
Results for Jeremy Lin:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Jordan Loyd"
8 results found.
0: Jordan Loyd
1: Jordan Ford
2: Jordan Bone
3: Jordan Nwora
4: Jordan Bowden
5: Jordan Bell
6: Jordan Hill
7: Jordan Poole
Pick one: 0
Results for Jordan Loyd:

You searched for "Patrick McCaw"
1 result found.
Patrick McCaw
Results for Patrick McCaw:

You searched for "Jodie Meeks"
1 result found.
Jodie Meeks
Results for Jodie Meeks:

You searched for "C.J. Miles"
7 results found.
0: C.J. Miles
1: C.J. Kupec
2: B.J. Tyler
3: C.J. Wilcox
4: T.J. Leaf
5: A.J. Price
6: D.J. White
Pick one: 0
Results for C.J. Miles:

You searched for "Malcolm Miller"
3 results found.
0: Malcolm Miller
1: Malcolm Lee
2: Malcolm Mackey
Pick one: 0
Results for Malcolm Miller:

You searched for "Greg Monroe"
7 results found.
0: Greg Monroe
1: Greg Minor
2: Earl Monroe
3: Greg Foster
4: Greg Howard
5: Greg Oden
6: Greg Sutton
Pick one: 0
Results for Greg Monroe:

You searched for "Eric Moreland"
1 result found.
Eric Moreland
Results for Eric Moreland:

You searched for "Norman Powell"
1 result found.
Norman Powell
Results for Norman Powell:

You searched for "Malachi Richardson"
1 result found.
Malachi Richardson
Results for Malachi Richardson:

You searched for "Pascal Siakam"
1 result found.
Pascal Siakam
Results for Pascal Siakam:

You searched for "Jonas Valančiūnas"
1 result found.
Jonas Valanciunas
Results for Jonas Valanciunas:

You searched for "Fred VanVleet"
1 result found.
Fred VanVleet
Results for Fred VanVleet:

You searched for "Delon Wright"
4 results found.
0: Delon Wright
1: Leroy Wright
2: Dorell Wright
3: Julian Wright
Pick one: 0
Results for Delon Wright:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2019-01-13,27-198,TOR,AWAY,WAS,W (+2),1,44:59,15,29,...,11,5,3,2,3,3,41,35.7,-1,Kawhi Leonard
1,2019-01-01,27-186,TOR,HOME,UTA,W (+6),1,35:26,16,22,...,6,1,0,0,2,2,45,34.1,8,Kawhi Leonard
2,2019-03-30,26-328,MEM,AWAY,PHO,W (+5),1,34:01,16,28,...,20,5,2,2,3,3,34,33.9,2,Jonas Valančiūnas
3,2019-02-13,24-317,TOR,HOME,WAS,W (+9),1,32:40,15,25,...,10,2,0,3,4,5,44,33.4,23,Pascal Siakam
4,2019-03-01,27-245,TOR,HOME,POR,W (+2),1,34:25,14,22,...,3,5,3,0,2,1,38,33.2,14,Kawhi Leonard

In [44]:


TOR_2020_gamelog = []

for p in TOR_df_2020_players:
    player_log = get_game_logs(str(p), SEASON_2020_START, SEASON_2020_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2020_gamelog.append(player_log)
TOR_2020_gamelog = pd.concat(TOR_2020_gamelog)    
TOR_2020_gamelogs = TOR_2020_gamelog.copy()
TOR_2020_gamelogs['GAME_SCORE'] = TOR_2020_gamelogs['GAME_SCORE'].astype(float)
TOR_2020_games = TOR_2020_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2020_games_csv = TOR_2020_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2020_games.csv', index=False)
TOR_2020_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2020_games.csv')
TOR_2020_games_proc.head()

You searched for "OG Anunoby"
1 result found.
OG Anunoby
Results for OG Anunoby:

You searched for "Chris Boucher"
5 results found.
0: Chris Boucher
1: Chris Bosh
2: Chris Hunter
3: Chris Porter
4: Chris Herren
Pick one: 0
Results for Chris Boucher:

You searched for "Oshae Brissett"
1 result found.
Oshae Brissett
Results for Oshae Brissett:

You searched for "Terence Davis"
3 results found.
0: Terence Davis
1: Terry Davis
2: Terence Morris
Pick one: 0
Results for Terence Davis:

You searched for "Marc Gasol"
7 results found.
0: Marc Gasol
1: Pau Gasol
2: Mark Eaton
3: Marc Jackson
4: Mark Macon
5: Mark Davis
6: Mark Davis
Pick one: 0
Results for Marc Gasol:

You searched for "Dewan Hernandez"
1 result found.
Dewan Hernandez
Results for Dewan Hernandez:

You searched for "Rondae Hollis-Jefferson"
1 result found.
Rondae Hollis-Jefferson
Results for Rondae Hollis-Jefferson:

You searched for "Serge Ibaka"
1 result found.
Serge Ibaka
Results for Serge Ibaka:

You searched for "Stanley Johnson"
9 results found.
0: Stanley Johnson
1: Stanley Jackson
2: Andy Johnson
3: Charles Johnson
4: Steve Johnson
5: Stew Johnson
6: Trey Johnson
7: Tyler Johnson
8: Wesley Johnson
Pick one: 0
Results for Stanley Johnson:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Patrick McCaw"
1 result found.
Patrick McCaw
Results for Patrick McCaw:

You searched for "Malcolm Miller"
3 results found.
0: Malcolm Miller
1: Malcolm Lee
2: Malcolm Mackey
Pick one: 0
Results for Malcolm Miller:

You searched for "Shamorie Ponds"
1 result found.
Shamorie Ponds
Results for Shamorie Ponds:

You searched for "Norman Powell"
1 result found.
Norman Powell
Results for Norman Powell:

You searched for "Pascal Siakam"
1 result found.
Pascal Siakam
Results for Pascal Siakam:

You searched for "Matt Thomas"
15 results found.
0: Matt Thomas
1: Matt Guokas
2: Matt Guokas
3: Carl Thomas
4: Kurt Thomas
5: Etan Thomas
6: Jamel Thomas
7: James Thomas
8: Jim Thomas
9: Joe Thomas
10: John Thomas
11: Lance Thomas
12: Tim Thomas
13: Matt Mazza
14: Matt Othick
Pick one: 0
Results for Matt Thomas:

You searched for "Fred VanVleet"
1 result found.
Fred VanVleet
Results for Fred VanVleet:

You searched for "Paul Watson"
10 results found.
0: Paul Watson
1: Earl Watson
2: Pau Gasol
3: Paul Gordon
4: Paul Huston
5: Paul Walther
6: C.J. Watson
7: Jamie Watson
8: Paul Long
9: Samuel Watts
Pick one: 0
Results for Paul Watson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2020-03-01,22-228,TOR,AWAY,DEN,L (-15),1,39:47,12,16,...,7,3,7,0,0,5,32,35.6,-11,OG Anunoby
1,2020-02-21,25-325,TOR,HOME,PHO,W (+17),1,37:57,12,19,...,12,3,0,3,2,1,37,34.3,16,Pascal Siakam
2,2019-11-08,25-220,TOR,AWAY,NOP,W (+18),1,38:59,17,28,...,10,4,0,0,4,4,44,32.6,6,Pascal Siakam
3,2019-10-22,25-239,TOR,HOME,NOP,W (+8),1,44:21,12,18,...,5,7,2,0,2,0,34,32.2,18,Fred VanVleet
4,2020-02-05,33-317,TOR,HOME,IND,W (+1),1,37:32,12,21,...,8,10,2,0,3,3,32,30.5,13,Kyle Lowry

In [48]:

TOR_2021_gamelog = []

for p in TOR_df_2021_players:
    player_log = get_game_logs(str(p), SEASON_2021_START, SEASON_2021_END, playoffs = False)
    player_log['Player'] = p
    
    TOR_2021_gamelog.append(player_log)
TOR_2021_gamelog = pd.concat(TOR_2021_gamelog)    
TOR_2021_gamelogs = TOR_2021_gamelog.copy()
TOR_2021_gamelogs['GAME_SCORE'] = TOR_2021_gamelogs['GAME_SCORE'].astype(float)
TOR_2021_games = TOR_2021_gamelogs.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_2021_games_csv = TOR_2021_games.to_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2021_games.csv', index=False)
TOR_2021_games_proc = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2021_games.csv')
TOR_2021_games_proc.head()

You searched for "OG Anunoby"
1 result found.
OG Anunoby
Results for OG Anunoby:

You searched for "Aron Baynes"
8 results found.
0: Aron Baynes
1: Ron Baker
2: Harry Barnes
3: Marvin Barnes
4: Ron Boone
5: Aaron James
6: Tharon Mayes
7: Cameron Payne
Pick one: 0
Results for Aron Baynes:

You searched for "DeAndre' Bembry"
1 result found.
DeAndre' Bembry
Results for DeAndre' Bembry:

You searched for "Khem Birch"
1 result found.
Khem Birch
Results for Khem Birch:

You searched for "Chris Boucher"
5 results found.
0: Chris Boucher
1: Chris Bosh
2: Chris Hunter
3: Chris Porter
4: Chris Herren
Pick one: 0
Results for Chris Boucher:

You searched for "Terence Davis"
3 results found.
0: Terence Davis
1: Terry Davis
2: Terence Morris
Pick one: 0
Results for Terence Davis:

You searched for "Henry Ellenson"
1 result found.
Henry Ellenson
Results for Henry Ellenson:

You searched for "Malachi Flynn"
1 result found.
Malachi Flynn
Results for Malachi Flynn:

You searched for "Freddie Gillespie"
1 result found.
Freddie Gillespie
Results for Freddie Gillespie:

You searched for "Jalen Harris"
15 results found.
0: Jalen Harris
1: Joe Harris
2: Jaylen Morris
3: Jamel Artis
4: John Garris
5: John Hargis
6: Art Harris
7: Billy Harris
8: Devin Harris
9: Gary Harris
10: Manny Harris
11: Mike Harris
12: Jared Harper
13: Jaylen Hoard
14: Jalen Rose
Pick one: 0
Results for Jalen Harris:

You searched for "Rodney Hood"
4 results found.
0: Rodney Hood
1: Rodney Buford
2: Rodney Monroe
3: Rodney White
Pick one: 0
Results for Rodney Hood:

You searched for "Stanley Johnson"
9 results found.
0: Stanley Johnson
1: Stanley Jackson
2: Andy Johnson
3: Charles Johnson
4: Steve Johnson
5: Stew Johnson
6: Trey Johnson
7: Tyler Johnson
8: Wesley Johnson
Pick one: 0
Results for Stanley Johnson:

You searched for "Alex Len"
7 results found.
0: Alex Len
1: Saben Lee
2: Alex Acker
3: Alex Kirk
4: Greg Lee
5: Alex Scales
6: Hal Hale
Pick one: 0
Results for Alex Len:

You searched for "Kyle Lowry"
4 results found.
0: Kyle Lowry
1: Kyle Guy
2: Kyle Macy
3: Kyle Korver
Pick one: 0
Results for Kyle Lowry:

You searched for "Patrick McCaw"
1 result found.
Patrick McCaw
Results for Patrick McCaw:

You searched for "Norman Powell"
1 result found.
Norman Powell
Results for Norman Powell:

You searched for "Pascal Siakam"
1 result found.
Pascal Siakam
Results for Pascal Siakam:

You searched for "Matt Thomas"
15 results found.
0: Matt Thomas
1: Matt Guokas
2: Matt Guokas
3: Carl Thomas
4: Kurt Thomas
5: Etan Thomas
6: Jamel Thomas
7: James Thomas
8: Jim Thomas
9: Joe Thomas
10: John Thomas
11: Lance Thomas
12: Tim Thomas
13: Matt Mazza
14: Matt Othick
Pick one: 0
Results for Matt Thomas:

You searched for "Fred VanVleet"
1 result found.
Fred VanVleet
Results for Fred VanVleet:

You searched for "Yuta Watanabe"
1 result found.
Yuta Watanabe
Results for Yuta Watanabe:

You searched for "Paul Watson"
10 results found.
0: Paul Watson
1: Earl Watson
2: Pau Gasol
3: Paul Gordon
4: Paul Huston
5: Paul Walther
6: C.J. Watson
7: Jamie Watson
8: Paul Long
9: Samuel Watts
Pick one: 0
Results for Paul Watson:

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-02-02,26-343,TOR,AWAY,ORL,W (+15),1,37:06,17,23,...,3,2,3,3,1,2,54,50.3,20,Fred VanVleet
1,2021-04-08,28-087,TOR,HOME,CHI,L (-9),1,36:07,14,24,...,19,1,1,1,1,2,38,36.3,16,Chris Boucher
2,2021-05-06,27-034,TOR,HOME,WAS,L (-2),1,42:13,17,28,...,11,7,1,0,4,3,44,34.8,0,Pascal Siakam
3,2021-05-02,35-038,TOR,AWAY,LAL,W (+7),1,40:39,12,20,...,2,11,1,0,1,4,37,34.1,7,Kyle Lowry
4,2021-05-13,24-349,TOR,AWAY,CHI,L (-12),1,43:04,12,22,...,10,5,3,0,0,1,35,33.1,-8,Stanley Johnson

## combine all seasons

In [49]:
TOR_2000_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2000_games.csv')
TOR_2001_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2001_games.csv')
TOR_2002_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2002_games.csv')
TOR_2003_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2003_games.csv')
TOR_2004_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2004_games.csv')
TOR_2005_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2005_games.csv')
TOR_2006_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2006_games.csv')
TOR_2007_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2007_games.csv')
TOR_2008_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2008_games.csv')
TOR_2009_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2009_games.csv')
TOR_2010_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2010_games.csv')
TOR_2011_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2011_games.csv')
TOR_2012_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2012_games.csv')
TOR_2013_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2013_games.csv')
TOR_2014_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2014_games.csv')
TOR_2015_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2015_games.csv')
TOR_2016_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2016_games.csv')
TOR_2017_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2017_games.csv')
TOR_2018_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2018_games.csv')
TOR_2019_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2019_games.csv')
TOR_2020_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2020_games.csv')
TOR_2021_games_io = pd.read_csv('/Users/brendan/Desktop/Python/NBA_API/TOR/TOR_2021_games.csv')

In [50]:
TOR_season_dfs = [TOR_2000_games_io, TOR_2001_games_io, TOR_2002_games_io, TOR_2003_games_io, TOR_2004_games_io, TOR_2005_games_io,
                 TOR_2006_games_io, TOR_2007_games_io, TOR_2008_games_io, TOR_2009_games_io, TOR_2010_games_io, TOR_2011_games_io,
                 TOR_2012_games_io, TOR_2013_games_io, TOR_2014_games_io, TOR_2015_games_io, TOR_2016_games_io, TOR_2017_games_io,
                 TOR_2018_games_io, TOR_2019_games_io, TOR_2020_games_io, TOR_2021_games_io]

In [51]:
TOR_all = pd.concat(TOR_season_dfs)
TOR_all_sorted = TOR_all.sort_values(by=['GAME_SCORE'], ascending=False)
TOR_all_sorted.head(25)

,DATE,AGE,TEAM,HOME/AWAY,OPPONENT,RESULT,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GAME_SCORE,+/-,Player
0,2021-02-02,26-343,TOR,AWAY,ORL,W (+15),1,37:06,17,23,...,3,2,3,3,1,2,54,50.3,20,Fred VanVleet
0,2018-01-01,28-147,TOR,HOME,MIL,W (+4),1,43:27,17,29,...,5,8,1,1,2,4,52,44.1,9,DeMar DeRozan
0,2016-02-26,29-338,TOR,HOME,CLE,W (+2),1,42:49,15,20,...,5,9,4,0,2,4,43,41.6,11,Kyle Lowry
0,2008-11-18,24-239,TOR,AWAY,ORL,L (-13),1,44:46,14,19,...,18,4,2,1,3,1,40,41.0,-7,Chris Bosh
0,2000-11-18,23-297,TOR,HOME,MIL,W (+9),1,44:43,14,31,...,10,4,3,2,2,3,48,40.5,8,Vince Carter
0,2008-02-20,23-333,TOR,HOME,ORL,W (+17),1,38:54,14,16,...,5,5,1,1,1,3,40,40.1,28,Chris Bosh
0,2004-03-21,27-055,TOR,AWAY,NOH,W (+1),1,46:36,13,20,...,6,12,2,1,4,4,42,40.1,4,Vince Carter
1,2017-12-21,28-136,TOR,AWAY,PHI,W (+5),1,39:28,13,21,...,5,3,2,1,2,3,45,39.0,12,DeMar DeRozan
0,2010-04-04,26-011,TOR,HOME,GSW,L (-1),1,41:18,11,19,...,13,0,5,1,3,3,42,38.9,3,Chris Bosh
0,2014-01-25,22-354,TOR,HOME,LAC,L (-8),1,43:53,16,29,...,9,1,1,0,3,4,51,37.7,-4,Terrence Ross
1,2010-01-20,25-302,TOR,AWAY,MIL,L (-6),1,42:42,15,26,...,12,4,1,0,1,3,44,37.4,2,Chris Bosh
0,2017-01-01,30-282,TOR,AWAY,LAL,W (+9),1,39:02,12,16,...,9,7,0,0,4,3,41,37.4,12,Kyle Lowry
0,2001-12-07,24-315,TOR,HOME,DEN,W (+2),1,50:45,13,30,...,15,6,5,2,4,4,42,37.3,3,Vince Carter
1,2015-12-05,29-255,TOR,HOME,GSW,L (-3),1,38:29,14,26,...,3,7,4,1,1,2,41,37.1,8,Kyle Lowry
0,2010-12-08,25-043,TOR,AWAY,NYK,L (-3),1,39:27,16,24,...,7,6,2,0,1,0,41,37.1,-8,Andrea Bargnani
0,2000-02-27,23-032,TOR,HOME,PHO,W (+1),1,43:13,17,32,...,9,1,3,0,5,5,51,36.8,5,Vince Carter
1,2000-01-14,22-353,TOR,HOME,MIL,W (+5),1,42:58,20,32,...,5,4,2,2,3,5,47,36.5,3,Vince Carter
1,2021-04-08,28-087,TOR,HOME,CHI,L (-9),1,36:07,14,24,...,19,1,1,1,1,2,38,36.3,16,Chris Boucher
1,2007-12-22,23-273,TOR,AWAY,PHO,L (-19),1,33:02,10,20,...,13,0,0,0,0,3,42,36.3,-10,Chris Bosh
0,2006-03-26,21-214,TOR,AWAY,MIL,L (-9),1,45:59,20,32,...,9,3,1,0,3,4,48,36.0,-6,Charlie Villanueva
0,2005-04-09,28-073,NJN,HOME,BOS,W (+13),1,35:52,18,32,...,7,3,4,1,2,2,45,35.9,23,Vince Carter
0,2019-01-13,27-198,TOR,AWAY,WAS,W (+2),1,44:59,15,29,...,11,5,3,2,3,3,41,35.7,-1,Kawhi Leonard
0,2020-03-01,22-228,TOR,AWAY,DEN,L (-15),1,39:47,12,16,...,7,3,7,0,0,5,32,35.6,-11,OG Anunoby
1,2001-01-14,23-354,TOR,HOME,CHH,W (+8),1,42:17,16,23,...,8,3,1,1,1,4,40,35.5,8,Vince Carter
0,2003-03-08,26-041,TOR,AWAY,ATL,W (+9),1,35:38,16,24,...,4,4,1,0,1,3,43,35.0,14,Vince Carter